Repository kubevirt/kubevirt, pull requests merged in 2018-11, with the labels that each got.

#1667 Cleanups
  pkg/virt-controller/watch/vmi.go
  pkg/virt-controller/watch/vmi_test.go
Labels: release-note-none, size/M

#1666 Use fmt.Errorf instead of errors.New(fmt.Sprintf)
  pkg/cloud-init/cloud-init.go
  pkg/log/log.go
  pkg/registry-disk/registry-disk.go
Labels: release-note-none, size/S

#1524 Handle the (unlikely) event of spoofed MAC address being same
  pkg/virt-launcher/virtwrap/network/common.go
Labels: release-note-none, size/M

#1669 Fix 1668
  pkg/virt-api/webhooks/validating-webhook/validating-webhook.go
  pkg/virt-api/webhooks/validating-webhook/validating-webhook_test.go
  pkg/virt-launcher/virtwrap/cmd-server/server.go
  pkg/virt-launcher/virtwrap/errors/errors.go
Labels: release-note-none, size/M

#1675 backport of virtctl image-upload to release-0.9
  glide.lock
  manifests/testing/cdi-v1.3.0.yaml.in
  pkg/virtctl/imageupload/imageupload.go
  pkg/virtctl/imageupload/imageupload_suite_test.go
  pkg/virtctl/imageupload/imageupload_test.go
  pkg/virtctl/root.go
  tests/imageupload_test.go
  tests/utils.go
  vendor/github.com/mattn/go-runewidth/.travis.yml
  vendor/github.com/mattn/go-runewidth/LICENSE
  vendor/github.com/mattn/go-runewidth/README.mkd
  vendor/github.com/mattn/go-runewidth/runewidth.go
  vendor/github.com/mattn/go-runewidth/runewidth_js.go
  vendor/github.com/mattn/go-runewidth/runewidth_posix.go
  vendor/github.com/mattn/go-runewidth/runewidth_windows.go
  vendor/gopkg.in/cheggaaa/pb.v1/.travis.yml
  vendor/gopkg.in/cheggaaa/pb.v1/LICENSE
  vendor/gopkg.in/cheggaaa/pb.v1/README.md
  vendor/gopkg.in/cheggaaa/pb.v1/format.go
  vendor/gopkg.in/cheggaaa/pb.v1/pb.go
  vendor/gopkg.in/cheggaaa/pb.v1/pb_appengine.go
  vendor/gopkg.in/cheggaaa/pb.v1/pb_win.go
  vendor/gopkg.in/cheggaaa/pb.v1/pb_x.go
  vendor/gopkg.in/cheggaaa/pb.v1/pool.go
  vendor/gopkg.in/cheggaaa/pb.v1/pool_win.go
  vendor/gopkg.in/cheggaaa/pb.v1/pool_x.go
  vendor/gopkg.in/cheggaaa/pb.v1/reader.go
  vendor/gopkg.in/cheggaaa/pb.v1/runecount.go
  vendor/gopkg.in/cheggaaa/pb.v1/termios_bsd.go
  vendor/gopkg.in/cheggaaa/pb.v1/termios_sysv.go
Labels: release-note, size/XXL

#1543 Add libvirt channel
  images/cdi-http-import-server/Dockerfile
  pkg/api/v1/schema_test.go
  pkg/api/v1/types.go
  pkg/virt-handler/vm.go
  pkg/virt-handler/vm_test.go
  pkg/virt-launcher/notify-client/client.go
  pkg/virt-launcher/notify-client/notify_test.go
  pkg/virt-launcher/virtwrap/api/converter.go
  pkg/virt-launcher/virtwrap/api/converter_test.go
  pkg/virt-launcher/virtwrap/api/deepcopy_generated.go
  pkg/virt-launcher/virtwrap/api/schema.go
  pkg/virt-launcher/virtwrap/api/schema_test.go
  pkg/virt-launcher/virtwrap/cli/generated_mock_libvirt.go
  pkg/virt-launcher/virtwrap/cli/libvirt.go
  pkg/virt-launcher/virtwrap/util/libvirt_helper.go
  tests/utils.go
  tests/vmi_configuration_test.go
  tests/vmi_lifecycle_test.go
Labels: kind/api-change, release-note, size/XL

#1680 pkg/virt-api: Remove redundant codes
  pkg/virt-api/webhooks/utils.go
Labels: release-note-none, size/XS

#1685 openapi-gen removed from kubernetes/code-generator
  hack/docker-builder/Dockerfile
  pkg/api/v1/schema_swagger_generated.go
  pkg/api/v1/types_swagger_generated.go
Labels: release-note-none, size/S

#1665 Deprecating CreatedByLabel in favor of OwnerReferences
  pkg/api/v1/types.go
  pkg/controller/controller_ref.go
  pkg/controller/controller_ref_manager.go
  pkg/virt-controller/services/template.go
  pkg/virt-controller/watch/node.go
  pkg/virt-controller/watch/node_test.go
  pkg/virt-controller/watch/replicaset.go
  pkg/virt-controller/watch/vm.go
  pkg/virt-controller/watch/vmi.go
Labels: kind/api-change, release-note-none, size/L

#1693 improve 'not enough space' error log
  pkg/host-disk/host-disk.go
Labels: release-note-none, size/XS

#1688 Ensure that clusters have enough CPU cores to run multi-core tests
  cluster/ephemeral-provider-common.sh
  tests/vmi_configuration_test.go
  tests/vmi_iothreads_test.go
Labels: release-note-none, size/M

#1678 add variable for setting memory size for node
  cluster/ephemeral-provider-common.sh
  docs/getting-started.md
  hack/common.sh
Labels: release-note, size/S

#1695 Fix typo in virtctl imageupload usage example
  pkg/virtctl/imageupload/imageupload.go
Labels: release-note-none, size/XS

#1711 test.sh: use flock instead of a spinlock
  automation/test.sh
Labels: release-note-none, size/M

#1707 Tests: wait for VMI start to be sure that compute container exists
  tests/vmi_lifecycle_test.go
Labels: release-note-none, size/M

#1697 Use OpenShift v3.11.0 under cluster provider
  automation/check-patch.openshift-3.11-crio-release.mounts
  automation/check-patch.openshift-3.11-crio-release.packages
  automation/check-patch.openshift-3.11-crio-release.sh
  automation/check-patch.openshift-3.11-release.mounts
  automation/check-patch.openshift-3.11-release.packages
  automation/check-patch.openshift-3.11-release.sh
  automation/test.sh
  cluster/os-3.10.0-crio/provider.sh
  cluster/os-3.10.0-multus/provider.sh
  cluster/os-3.11.0-crio/README.md
  cluster/os-3.11.0-crio/provider.sh
  cluster/os-3.11.0/README.md
  cluster/os-3.11.0/provider.sh
  stdci.yaml
Labels: release-note-none, size/M

#1673 Add vnc script support for MAC OSX
  pkg/virtctl/vnc/vnc.go
Labels: release-note, size/L

#1216 add vnc script support for MAC OSX
  pkg/virtctl/vnc/vnc.go
Labels: release-note, size/M

#1625 Added sriov interface type support
  api/openapi-spec/swagger.json
  cluster/examples/vmi-sriov.yaml
  docs/sriov.md
  pkg/api/v1/deepcopy_generated.go
  pkg/api/v1/openapi_generated.go
  pkg/api/v1/schema.go
  pkg/api/v1/schema_swagger_generated.go
  pkg/virt-controller/services/template.go
  pkg/virt-controller/services/template_test.go
  pkg/virt-launcher/virtwrap/api/converter.go
  pkg/virt-launcher/virtwrap/api/converter_test.go
  pkg/virt-launcher/virtwrap/api/deepcopy_generated.go
  pkg/virt-launcher/virtwrap/api/schema.go
  pkg/virt-launcher/virtwrap/manager.go
  pkg/virt-launcher/virtwrap/manager_test.go
  pkg/virt-launcher/virtwrap/network/podinterface.go
  pkg/virt-launcher/virtwrap/network/podinterface_test.go
  tests/utils.go
  tests/vmi_multus_test.go
  tools/vms-generator/utils/utils.go
  tools/vms-generator/vms-generator.go
Labels: kind/api-change, release-note, size/XL

#1681 Add http to scheme of image-upload if not there
  pkg/virtctl/imageupload/imageupload.go
Labels: release-note, size/XS

#1717 Fix CPU placement test
  pkg/virt-launcher/virtwrap/api/converter.go
  pkg/virt-launcher/virtwrap/api/converter_test.go
  tests/vmi_configuration_test.go
Labels: release-note-none, size/M

#1687 Add unit tests to subresource
  Makefile
  hack/coverage.sh
  hack/goveralls.sh
  pkg/virt-api/rest/subresource_test.go
Labels: release-note, size/L

#1725 Few fixes to safe_download()
  automation/test.sh
Labels: do-not-merge/release-note-label-needed, size/M

#1727 Tolerate smaller PVs
  cmd/virt-handler/virt-handler.go
  cmd/virt-launcher/virt-launcher.go
  pkg/host-disk/host-disk.go
  pkg/host-disk/host-disk_test.go
  pkg/virt-controller/services/template.go
  pkg/virt-controller/services/template_test.go
  pkg/virt-handler/cache/cache.go
  pkg/virt-handler/cache/cache_test.go
  pkg/virt-handler/notify-server/server.go
  pkg/virt-launcher/notify-client/client.go
  pkg/virt-launcher/notify-client/notify_test.go
  pkg/virt-launcher/virtwrap/manager.go
  pkg/virt-launcher/virtwrap/manager_test.go
  tests/storage_test.go
  tests/utils.go
Labels: do-not-merge/hold, release-note, size/XL

#1734 [release-0.9] Tolerate smaller pvs
  cmd/virt-handler/virt-handler.go
  cmd/virt-launcher/virt-launcher.go
  hack/docker-builder/Dockerfile
  pkg/api/v1/schema_swagger_generated.go
  pkg/api/v1/types_swagger_generated.go
  pkg/host-disk/host-disk.go
  pkg/host-disk/host-disk_test.go
  pkg/virt-controller/services/template.go
  pkg/virt-controller/services/template_test.go
  pkg/virt-handler/cache/cache.go
  pkg/virt-handler/cache/cache_test.go
  pkg/virt-handler/cmd-client/client.go
  pkg/virt-handler/notify-server/server.go
  pkg/virt-launcher/notify-client/client.go
  pkg/virt-launcher/notify-client/notify_test.go
  pkg/virt-launcher/virtwrap/manager.go
  pkg/virt-launcher/virtwrap/manager_test.go
  tests/storage_test.go
  tests/utils.go
Labels: release-note, size/XL

#1639 Run only networking related tests on multus and genie test lanes
  automation/test.sh
  tests/vmi_slirp_interface_test.go
Labels: release-note-none, size/XS

#1743 Use libvirt-4.9.0
  cmd/virt-launcher/Dockerfile
  glide.yaml
  hack/docker-builder/Dockerfile
  hack/docker-builder/fedora-virt-preview.repo
Labels: release-note, size/M

#1748 Stabilize test where virt-handler should recover after crash
  tests/storage_test.go
  tests/utils.go
  tests/vmi_lifecycle_test.go
Labels: release-note-none, size/M

#1728 Added code to passthrough custom dhcp options to vm.
  api/openapi-spec/swagger.json
  pkg/api/v1/deepcopy_generated.go
  pkg/api/v1/openapi_generated.go
  pkg/api/v1/schema.go
  pkg/api/v1/schema_swagger_generated.go
  pkg/virt-launcher/virtwrap/network/common.go
  pkg/virt-launcher/virtwrap/network/dhcp/dhcp.go
  pkg/virt-launcher/virtwrap/network/dhcp/dhcp_test.go
  pkg/virt-launcher/virtwrap/network/generated_mock_common.go
  pkg/virt-launcher/virtwrap/network/podinterface.go
  pkg/virt-launcher/virtwrap/network/podinterface_test.go
  tests/vmi_networking_test.go
Labels: kind/api-change, release-note, size/L

#1672 Dropping OwnedByAnnotation from VMIs
  pkg/api/v1/types.go
  pkg/virt-controller/services/template.go
  pkg/virt-controller/services/template_test.go
  pkg/virt-controller/watch/migration_test.go
  pkg/virt-controller/watch/vm.go
  pkg/virt-controller/watch/vm_test.go
  pkg/virt-controller/watch/vmi.go
  pkg/virt-controller/watch/vmi_test.go
Labels: kind/api-change, release-note-none, size/L

#1671 basic VMI restart endpoint
  api/openapi-spec/swagger.json
  manifests/dev/rbac.authorization.k8s.yaml.in
  manifests/release/kubevirt.yaml.in
  pkg/kubecli/generated_mock_kubevirt.go
  pkg/kubecli/kubevirt.go
  pkg/kubecli/vm.go
  pkg/kubecli/vm_test.go
  pkg/virt-api/api.go
  pkg/virt-api/rest/authorizer.go
  pkg/virt-api/rest/subresource.go
  pkg/virt-api/rest/subresource_test.go
  pkg/virtctl/root.go
  pkg/virtctl/vm/vm.go
  pkg/virtctl/vm/vm_test.go
  tests/subresource_api_test.go
Labels: release-note, size/L

#1682 fix virtctl image-upload tests
  manifests/testing/cdi-v1.3.0.yaml.in
  manifests/testing/local-block-storage.yaml.in
  tests/imageupload_test.go
  tests/storage_test.go
  tests/utils.go
Labels: release-note-none, size/M

#1694 Add virt-viewer download instructions for Windows
  docs/getting-started.md
Labels: release-note-none, size/XS

#1769 better description of VM restart endpoint
  api/openapi-spec/swagger.json
  pkg/virt-api/api.go
Labels: release-note, size/S

#1732 Add feature gate for SR-IOV interface type
  docs/sriov.md
  pkg/feature-gates/feature-gates.go
  pkg/virt-api/webhooks/validating-webhook/validating-webhook.go
  pkg/virt-api/webhooks/validating-webhook/validating-webhook_test.go
  tools/vms-generator/vms-generator.go
Labels: release-note, size/M

#1773 correct link to the user guide
  README.md
Labels: release-note, size/XS

#1771 English change of tone
  CONTRIBUTING.md
Labels: release-note-none, size/XS

#1761 virtctl: Compatible with multiple TigerVNC versions on OSX
  pkg/virtctl/vnc/vnc.go
Labels: release-note-none, size/S

#1772 suggest a design principle: VM should behave like a native workload
  docs/architecture.md
Labels: release-note-none, size/XS

#1766 Turning TX offload off on DHCP interfaces.
  pkg/virt-launcher/virtwrap/network/dhcp/dhcp.go
  pkg/virt-launcher/virtwrap/network/dhcp/ethtool.go
  tests/vmi_networking_test.go
Labels: release-note-none, size/L
