Repository kubevirt/kubevirt, pull requests merged in 2018-07, with the labels that each got.

#980 Add test for creating VM from template via oc CLI
  hack/functests.sh
  tests/oc_template_test.go
  tests/types.go
  tests/utils.go
Labels: release-note-none, size/XL

#1250 Refactor the Template test for multiple VM Templates
  tests/oc_template_test.go
  tests/template_test.go
  tests/utils.go
Labels: release-note-none, size/XL

#1246 release-0.6: QEMU PID detection
  cmd/fake-qemu-process/fake-qemu.go
  cmd/virt-launcher/virt-launcher.go
  pkg/virt-launcher/monitor.go
  pkg/virt-launcher/monitor_test.go
  tests/vmi_lifecycle_test.go
Labels: release-note, size/M

#1245 docs: Add a note how to do stable branch cherry-picking
  docs/release.md
Labels: for/developers, needs/documentation, release-note-none, size/M

#1257 release-0.6: Release manifest templates
  .travis.yml
  cmd/virt-api/Dockerfile
  cmd/virt-controller/Dockerfile
  cmd/virt-handler/Dockerfile
  cmd/virt-launcher/Dockerfile
  cmd/virt-launcher/entrypoint.sh
  cmd/virt-launcher/sh.sh
  hack/build-manifests.sh
  hack/common.sh
  hack/docker-builder/Dockerfile
  manifests/dev/virt-api.yaml.in
  manifests/dev/virt-controller.yaml.in
  manifests/dev/virt-handler.yaml.in
  manifests/release/kubevirt.yaml.in
  pkg/virt-api/rest/subresource.go
  pkg/virt-controller/services/template.go
  pkg/virt-controller/services/template_test.go
  pkg/virt-launcher/virtwrap/util/libvirt_helper.go
Labels: release-note, size/M

#1254 Backport clusterrole aggregation to release-0.6
  manifests/dev/rbac.authorization.k8s.yaml.in
  manifests/release/kubevirt.yaml.in
Labels: release-note, size/XS

#1259 Merge pull request #1163 from rmohr/travis-release-nice-name
  .travis.yml
Labels: release-note-none, size/XS

#1262 Remove forgotten comment in imports
  pkg/virt-controller/watch/vm_test.go
Labels: release-note-none, size/XS

#1237 Make sure that the VMI replica set will remove VM's in the final state
  pkg/virt-controller/watch/replicaset.go
  pkg/virt-controller/watch/replicaset_test.go
  tests/replicaset_test.go
Labels: release-note, size/L

#1263 [cherry pick] Remove forgotten comment in inports
  pkg/virt-controller/watch/vm_test.go
Labels: release-note-none, size/XS

#1264 release-0.6: Fix VMIPreset name
  manifests/release/demo-content.yaml.in
Labels: release-note-none, size/XS

#1249 Add possibility to specify VM CPU model
  api/openapi-spec/swagger.json
  manifests/generated/vm-resource.yaml
  manifests/generated/vmi-resource.yaml
  manifests/generated/vmipreset-resource.yaml
  manifests/generated/vmirs-resource.yaml
  pkg/api/v1/openapi_generated.go
  pkg/api/v1/schema.go
  pkg/api/v1/schema_swagger_generated.go
  pkg/api/v1/schema_test.go
  pkg/virt-launcher/virtwrap/api/converter.go
  pkg/virt-launcher/virtwrap/api/converter_test.go
  pkg/virt-launcher/virtwrap/api/schema.go
  pkg/virt-launcher/virtwrap/api/schema_test.go
  tests/utils.go
  tests/vmi_configuration_test.go
Labels: priority/critical-urgent, release-note, size/L

#1266 Fix dp race
  pkg/virt-handler/device-manager/generic_device.go
  tests/vmi_lifecycle_test.go
Labels: priority/critical-urgent, release-note-none, size/S

#1213 Support interface.macAddress
  api/openapi-spec/swagger.json
  manifests/generated/vm-resource.yaml
  manifests/generated/vmi-resource.yaml
  manifests/generated/vmipreset-resource.yaml
  manifests/generated/vmirs-resource.yaml
  pkg/api/v1/openapi_generated.go
  pkg/api/v1/schema.go
  pkg/api/v1/schema_swagger_generated.go
  pkg/virt-api/validating-webhook/validating-webhook.go
  pkg/virt-api/validating-webhook/validating-webhook_test.go
  pkg/virt-launcher/virtwrap/network/podinterface.go
  pkg/virt-launcher/virtwrap/network/podinterface_test.go
  tests/utils.go
  tests/vmi_networking_test.go
  tests/vmi_slirp_interface_test.go
Labels: release-note, size/L

#1238 Add edge case tests for VMIRS when vms go down
  pkg/virt-controller/watch/replicaset.go
  pkg/virt-controller/watch/replicaset_test.go
Labels: release-note-none, size/M

#1209 launcher: Drop console hack
  cmd/virt-launcher/Dockerfile
  cmd/virt-launcher/entrypoint.sh
  cmd/virt-launcher/sh.sh
Labels: do-not-merge/hold, release-note, size/S

#1270 Check on KVM device only nodes with virt-handler pod
  tests/utils.go
Labels: release-note-none, size/S

#1267 release-0.6: Merge pull request #1249 from cynepco3hahue/cpu_model_support
  api/openapi-spec/swagger.json
  manifests/generated/vm-resource.yaml
  manifests/generated/vmi-resource.yaml
  manifests/generated/vmipreset-resource.yaml
  manifests/generated/vmirs-resource.yaml
  pkg/api/v1/openapi_generated.go
  pkg/api/v1/schema.go
  pkg/api/v1/schema_swagger_generated.go
  pkg/api/v1/schema_test.go
  pkg/virt-launcher/virtwrap/api/converter.go
  pkg/virt-launcher/virtwrap/api/converter_test.go
  pkg/virt-launcher/virtwrap/api/schema.go
  pkg/virt-launcher/virtwrap/api/schema_test.go
  tests/utils.go
  tests/vmi_configuration_test.go
Labels: release-note, size/L

#1215 move port configuration to the interface level and add them to the pod manifest
  api/openapi-spec/swagger.json
  cluster/examples/vmi-slirp.yaml
  manifests/generated/vm-resource.yaml
  manifests/generated/vmi-resource.yaml
  manifests/generated/vmipreset-resource.yaml
  manifests/generated/vmirs-resource.yaml
  pkg/api/v1/deepcopy_generated.go
  pkg/api/v1/openapi_generated.go
  pkg/api/v1/schema.go
  pkg/api/v1/schema_swagger_generated.go
  pkg/api/v1/schema_test.go
  pkg/virt-api/validating-webhook/validating-webhook.go
  pkg/virt-api/validating-webhook/validating-webhook_test.go
  pkg/virt-controller/services/template.go
  pkg/virt-controller/services/template_test.go
  pkg/virt-launcher/virtwrap/api/converter.go
  pkg/virt-launcher/virtwrap/api/converter_test.go
  tests/utils.go
  tests/vmi_slirp_interface_test.go
  tools/vms-generator/vms-generator.go
Labels: release-note, size/XL, topic/network

#1269 Set host-model CPU mode when CPU spec defined but model not
  pkg/virt-launcher/virtwrap/api/converter.go
  pkg/virt-launcher/virtwrap/api/converter_test.go
  tests/vmi_configuration_test.go
Labels: release-note-none, size/M

#1274 Merge pull request #1269 from cynepco3hahue/cpu_model_small_fixes
  pkg/virt-launcher/virtwrap/api/converter.go
  pkg/virt-launcher/virtwrap/api/converter_test.go
  tests/vmi_configuration_test.go
Labels: release-note-none, size/M

#1272 Don't validate origin header on websocket upgrades
  pkg/virt-api/rest/subresource.go
  tests/vnc_test.go
Labels: release-note, size/M

#1283 Turn on -race for test suite
  hack/build-go.sh
  pkg/virt-handler/device-manager/device_controller_test.go
  pkg/virt-launcher/monitor_test.go
Labels: release-note-none, size/M

#1171 Add hooking support
  .gitignore
  cluster/examples/vmi-with-sidecar-hook.yaml
  cmd/example-hook-sidecar/Dockerfile
  cmd/example-hook-sidecar/README.md
  cmd/example-hook-sidecar/smbios.go
  cmd/virt-launcher/virt-launcher.go
  glide.lock
  glide.yaml
  hack/config-default.sh
  hack/docker-builder/Dockerfile
  hack/generate.sh
  pkg/hooks/hooks.go
  pkg/hooks/hooks_suite_test.go
  pkg/hooks/hooks_test.go
  pkg/hooks/info/api.pb.go
  pkg/hooks/info/api.proto
  pkg/hooks/info/info.go
  pkg/hooks/manager.go
  pkg/hooks/v1alpha1/api.pb.go
  pkg/hooks/v1alpha1/api.proto
  pkg/hooks/v1alpha1/v1alpha1.go
  pkg/virt-controller/services/template.go
  pkg/virt-controller/services/template_test.go
  pkg/virt-launcher/virtwrap/manager.go
  tests/vmi_hook_sidecar_test.go
  tools/vms-generator/vms-generator.go
Labels: size/XXL

#1288 Fix spelling error in virt-controller
  pkg/virt-controller/watch/node.go
Labels: release-note-none, size/XS

#1297 getting started: VMI->virtual machine
  docs/getting-started.md
Labels: release-note-none, size/XS

#1300 docs: fix getting-started.md for vmis
  docs/getting-started.md
Labels: release-note, size/XS

#1298 getting-started: cleanup "code generation" section
  docs/getting-started.md
Labels: release-note-none, size/S

#1291 Remove debug message from slirp and network tests
  tests/vmi_networking_test.go
  tests/vmi_slirp_interface_test.go
Labels: release-note-none, size/XS

#1301 getting started: testing: fix English glitches
  docs/getting-started.md
Labels: release-note-none, size/S

#1299 Add KubeVirt custom fail handler
  tests/tests_suite_test.go
  tests/utils.go
Labels: release-note-none, size/M

#1317 Fix Interface name validation
  pkg/virt-api/validating-webhook/validating-webhook.go
  pkg/virt-api/validating-webhook/validating-webhook_test.go
Labels: release-note, size/M

#1312 Discover server version API version dynamically
  pkg/kubecli/version.go
  pkg/kubecli/version_test.go
Labels: release-note-none, size/S

#1286 Use latest os-3.10.0 image
  cluster/os-3.10.0/provider.sh
Labels: release-note-none, size/XS

#1336 Use git clone to fetch shfmt intead of go get
  hack/docker-builder/Dockerfile
Labels: release-note-none, size/XS

#1334 Fix typo in virtwrap converter
  pkg/virt-launcher/virtwrap/api/converter.go
Labels: size/XS

#1324 Support disconnected instances
  api/openapi-spec/swagger.json
  manifests/generated/vm-resource.yaml
  manifests/generated/vmi-resource.yaml
  manifests/generated/vmipreset-resource.yaml
  manifests/generated/vmirs-resource.yaml
  pkg/api/v1/deepcopy_generated.go
  pkg/api/v1/defaults.go
  pkg/api/v1/defaults_test.go
  pkg/api/v1/openapi_generated.go
  pkg/api/v1/schema.go
  pkg/api/v1/schema_swagger_generated.go
  pkg/virt-launcher/virtwrap/network/network.go
  pkg/virt-launcher/virtwrap/network/network_test.go
  tests/vmi_networking_test.go
Labels: release-note, size/M

#1275 hack: Update release script and mailMap
  .mailmap
  hack/release-announce.sh
Labels: release-note-none, size/S

#1292 Add a success message in virtctl
  pkg/virtctl/vm/vm.go
  pkg/virtctl/vm/vm_test.go
Labels: release-note-none, size/S

#1302 Fix stdci configuration for the project
  automation/check-patch.k8s-1.10.3-dev.mounts
  automation/check-patch.k8s-1.10.3-dev.packages
  automation/check-patch.k8s-1.10.3-dev.sh
  automation/check-patch.k8s-1.10.3-release.mounts
  automation/check-patch.k8s-1.10.3-release.packages
  automation/check-patch.k8s-1.10.3-release.sh
  automation/check-patch.openshift-3.10-release.mounts
  automation/check-patch.openshift-3.10-release.packages
  automation/check-patch.openshift-3.10-release.sh
  automation/check-patch.packages.el7
  automation/check-patch.sh
  automation/check-patch.windows2016-release.mounts
  automation/check-patch.windows2016-release.packages
  automation/check-patch.windows2016-release.sh
  automation/check-patch.yaml
  hack/version.sh
  stdci.yaml
Labels: do-not-merge/hold, release-note-none, size/L

#1285 Change affinity struct to use k8sv1
  api/openapi-spec/swagger.json
  manifests/generated/vm-resource.yaml
  manifests/generated/vmi-resource.yaml
  manifests/generated/vmirs-resource.yaml
  pkg/api/v1/deepcopy_generated.go
  pkg/api/v1/deepcopy_test.go
  pkg/api/v1/openapi_generated.go
  pkg/api/v1/types.go
  pkg/api/v1/types_swagger_generated.go
  pkg/virt-controller/services/template_test.go
  tests/utils.go
  tests/vmi_configuration_test.go
Labels: release-note-none, size/L

#1313 virtctl.sh: Call appropriate binary by architecture
  cluster/virtctl.sh
  hack/build-go.sh
Labels: release-note-none, size/S

#1345 Add possibility to use CPU passthrough for VM's
  api/openapi-spec/swagger.json
  pkg/api/v1/openapi_generated.go
  pkg/api/v1/schema.go
  pkg/api/v1/schema_swagger_generated.go
  pkg/virt-launcher/virtwrap/api/converter.go
  pkg/virt-launcher/virtwrap/api/converter_test.go
  tests/utils.go
  tests/vmi_configuration_test.go
Labels: release-note, size/L

#1304 Add paused reason to domain states
  pkg/virt-launcher/virtwrap/api/schema.go
  pkg/virt-launcher/virtwrap/manager_test.go
  pkg/virt-launcher/virtwrap/util/libvirt_helper.go
Labels: release-note, size/M

#1359 Small fixes for CI windows run
  automation/test.sh
  cluster/ephemeral-provider-common.sh
Labels: size/XS

#1271 Add Toleration to VMI
  api/openapi-spec/swagger.json
  manifests/generated/vm-resource.yaml
  manifests/generated/vmi-resource.yaml
  manifests/generated/vmirs-resource.yaml
  pkg/api/v1/deepcopy_generated.go
  pkg/api/v1/openapi_generated.go
  pkg/api/v1/types.go
  pkg/api/v1/types_swagger_generated.go
  pkg/virt-controller/services/template.go
  pkg/virt-controller/services/template_test.go
  pkg/virt-controller/watch/vmi.go
  tests/vmi_lifecycle_test.go
Labels: release-note, size/L

#1362 Do not skip windows tests when windows PV is bounded
  tests/utils.go
Labels: release-note-none, size/XS

#1280 Fix virtctl expose
  pkg/virtctl/expose/expose.go
  pkg/virtctl/expose/expose_test.go
  tests/expose_test.go
  tests/utils.go
Labels: release-note, size/L

#1365 CPU model syntax fixes
  api/openapi-spec/swagger.json
  pkg/api/v1/openapi_generated.go
  pkg/api/v1/schema.go
  pkg/api/v1/schema_swagger_generated.go
  tests/utils.go
Labels: release-note-none, size/S

#1323 virtctl console wait until the virtual machine is in running state
  pkg/kubecli/generated_mock_kubevirt.go
  pkg/kubecli/kubevirt.go
  pkg/kubecli/vmi.go
  pkg/virtctl/console/console.go
  tests/console_test.go
  tests/utils.go
Labels: release-note, size/L

#1268 Document kubevirt specific annotations and labels
  pkg/api/v1/types.go
Labels: release-note-none, size/S

#1373 Provide a useful message when VMI's time out
  tests/utils.go
Labels: release-note-none, size/XS

#1344 Graphics sockets to use UID folders
  cmd/virt-launcher/virt-launcher.go
  pkg/virt-api/rest/subresource.go
  pkg/virt-controller/services/template.go
  pkg/virt-controller/services/template_test.go
  pkg/virt-launcher/virtwrap/api/converter.go
  pkg/virt-launcher/virtwrap/api/converter_test.go
Labels: release-note, size/S

#1367 Disable unused VM devices
  pkg/virt-launcher/virtwrap/api/converter_test.go
  pkg/virt-launcher/virtwrap/api/deepcopy_generated.go
  pkg/virt-launcher/virtwrap/api/defaults.go
  pkg/virt-launcher/virtwrap/api/schema.go
  pkg/virt-launcher/virtwrap/api/schema_test.go
  pkg/virt-launcher/virtwrap/api/zz_generated.defaults.go
Labels: size/M

#1384 remove glossary info according to #1009
  README.md
  docs/components.md
Labels: release-note-none, size/XS

#1277 Take into account namespace memory limits when starting a Virtual Machine
  pkg/controller/virtinformers.go
  pkg/virt-controller/watch/application.go
  pkg/virt-controller/watch/preset.go
  pkg/virt-controller/watch/preset_test.go
  tests/utils.go
  tests/vmi_configuration_test.go
Labels: release-note, size/L

#1347 Add new preferences for PR structures to the reviewer guide
  docs/reviewer-guide.md
Labels: release-note-none, size/XS

#1387 Update invalid URLs in this repo
  CONTRIBUTING.md
  docs/debugging.md
  docs/direct-pv-disks.md
  docs/iscsi-authentication.md
  docs/release.md
Labels: release-note-none, size/S

#1353 Added k8s 1.11.0 provider
  automation/check-patch.k8s-1.10.4-release.mounts
  automation/check-patch.k8s-1.10.4-release.packages
  automation/check-patch.k8s-1.10.4-release.sh
  automation/check-patch.k8s-1.11.0-dev.mounts
  automation/check-patch.k8s-1.11.0-dev.packages
  automation/check-patch.k8s-1.11.0-dev.sh
  automation/check-patch.k8s-1.11.0-release.mounts
  automation/check-patch.k8s-1.11.0-release.packages
  automation/check-patch.k8s-1.11.0-release.sh
  automation/test.sh
  cluster/k8s-1.11.0/README.md
  cluster/k8s-1.11.0/provider.sh
  hack/config.sh
  stdci.yaml
  tests/access_test.go
  tests/utils.go
Labels: size/M

#1378 Merge pull request #1364 from rmohr/memory-overcommit
  api/openapi-spec/swagger.json
  manifests/generated/vm-resource.yaml
  manifests/generated/vmi-resource.yaml
  manifests/generated/vmipreset-resource.yaml
  manifests/generated/vmirs-resource.yaml
  pkg/api/v1/deepcopy_generated.go
  pkg/api/v1/openapi_generated.go
  pkg/api/v1/schema.go
  pkg/api/v1/schema_swagger_generated.go
  pkg/virt-api/rest/subresource.go
  pkg/virt-api/rest/subresource_test.go
  pkg/virt-controller/services/template.go
  pkg/virt-controller/services/template_test.go
  pkg/virt-launcher/virtwrap/api/converter.go
  pkg/virt-launcher/virtwrap/api/converter_test.go
  pkg/virt-launcher/virtwrap/api/defaults.go
  pkg/virt-launcher/virtwrap/api/zz_generated.defaults.go
Labels: release-note, size/L

#1394 fix expose example unclear
  pkg/virtctl/expose/expose.go
Labels: release-note-none, size/XS
