Repository kubevirt/kubevirt, pull requests merged in 2018-06, with the labels that each got.

#1200 Prepare Issues and PRs for Prow
  .github/ISSUE_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: release-note-none, size/M

#1197 Allow setting custom pkgdirs for cross-compilation
  hack/build-go.sh
  hack/common.sh
Labels: release-note-none, size/S

#1206 Fixed CPU / Cores in example vm templates
  cluster/examples/vm-template-fedora.yaml
  cluster/examples/vm-template-rhel7.yaml
  cluster/examples/vm-template-windows2012r2.yaml
  tools/vms-generator/vms-generator.go
Labels: release-note-none, size/S

#1207 Add optional serial number param to disk creation
  api/openapi-spec/swagger.json
  manifests/generated/vm-resource.yaml
  manifests/generated/vmi-resource.yaml
  manifests/generated/vmipreset-resource.yaml
  manifests/generated/vmirs-resource.yaml
  pkg/api/v1/openapi_generated.go
  pkg/api/v1/schema.go
  pkg/api/v1/schema_swagger_generated.go
  pkg/api/v1/schema_test.go
  pkg/virt-api/validating-webhook/validating-webhook.go
  pkg/virt-api/validating-webhook/validating-webhook_test.go
  tests/storage_test.go
Labels: release-note, size/L

#1210 Move binaries to /usr/bin
  cmd/virt-api/Dockerfile
  cmd/virt-controller/Dockerfile
  cmd/virt-handler/Dockerfile
  cmd/virt-launcher/Dockerfile
  cmd/virt-launcher/entrypoint.sh
  cmd/virt-launcher/sh.sh
  manifests/dev/virt-api.yaml.in
  manifests/dev/virt-controller.yaml.in
  manifests/dev/virt-handler.yaml.in
  manifests/release/kubevirt.yaml.in
  pkg/virt-api/rest/subresource.go
  pkg/virt-controller/services/template.go
  pkg/virt-controller/services/template_test.go
  pkg/virt-launcher/virtwrap/util/libvirt_helper.go
Labels: release-note-none, size/M

#1203 Add os-3.10.0 rc.0 provider
  automation/test.sh
  cluster/deploy.sh
  cluster/os-3.10.0/README.md
  cluster/os-3.10.0/provider.sh
Labels: release-note-none, size/S

#1214 Change virt-launcher SELinux type to spc_t
  pkg/virt-controller/services/template.go
Labels: release-note-none, size/XS

#1224 Verify build is clean
  .gitignore
  Makefile
  cluster/ephemeral-provider-common.sh
  hack/verify-build.sh
Labels: kind/bug, release-note-none, size/M

#1226 Skip virt-handler crush test on k8s version < 1.10.3
  tests/utils.go
  tests/vmi_lifecycle_test.go
Labels: release-note-none, size/M

#1231 Let the VM controller only delete VMIs once
  pkg/virt-controller/watch/vm.go
  pkg/virt-controller/watch/vm_test.go
Labels: release-note, size/S

#1235 Validate and sanitize hostname for DNS entries
  pkg/util/net/dns/sanitize.go
  pkg/virt-api/validating-webhook/validating-webhook.go
  pkg/virt-controller/services/template.go
  pkg/virt-launcher/virtwrap/manager.go
  tests/utils.go
Labels: release-note-none, size/M

#1116 Create and publish a jinja2 template of kubevirt.yaml
  .travis.yml
  hack/build-manifests.sh
  hack/common.sh
  hack/docker-builder/Dockerfile
Labels: size/M

#1234 Remove default kubeconfig value
  hack/config-default.sh
Labels: release-note-none, size/XS

#1239 Detect vm pid by domain uuid in cmd args
  cmd/fake-qemu-process/fake-qemu.go
  cmd/virt-launcher/virt-launcher.go
  pkg/virt-launcher/monitor.go
  pkg/virt-launcher/monitor_test.go
  tests/vmi_lifecycle_test.go
Labels: release-note-none, size/M

#1204 Ensure KVM devices are really allocatable before running test suite
  tests/utils.go
  tests/vmi_lifecycle_test.go
Labels: release-note-none, size/XS

#1241 Update outdated documentation
  docs/README.md
  docs/env-providers.md
Labels: release-note-none, size/M
