Repository kubevirt/kubevirt, pull requests merged in 2018-08, with the labels that each got.

#1389 Move VMI to failed state if compute container is terminated
  pkg/virt-controller/watch/vmi.go
  pkg/virt-controller/watch/vmi_test.go
Labels: release-note, size/S

#1074 Fix the logging messages
  pkg/virt-controller/watch/vm.go
Labels: size/S

#1402 Add OpenShift CRI-O provider and CI job
  automation/check-patch.openshift-3.10-crio-release.mounts
  automation/check-patch.openshift-3.10-crio-release.packages
  automation/check-patch.openshift-3.10-crio-release.sh
  automation/test.sh
  cluster/os-3.10.0-crio/README.md
  cluster/os-3.10.0-crio/provider.sh
  cluster/os-3.10.0/provider.sh
  cluster/os-3.9.0-crio/provider.sh
  stdci.yaml
Labels: release-note-none, size/M

#1311 Allow build-time configuration of Image Pull Policy
  hack/build-manifests.sh
  hack/config-default.sh
  hack/config.sh
  hack/dockerized
  manifests/dev/virt-api.yaml.in
  manifests/dev/virt-controller.yaml.in
  manifests/dev/virt-handler.yaml.in
  manifests/release/kubevirt.yaml.in
  pkg/virt-controller/services/template.go
  pkg/virt-controller/services/template_test.go
  tools/manifest-templator/manifest-templator.go
Labels: release-note, size/M

#1405 Increase the default number of cpus on test nodes
  cluster/ephemeral-provider-common.sh
Labels: release-note, size/XS

#1320 Use UID for Virtual Machine instace as the identifier
  cmd/virt-launcher/virt-launcher.go
  pkg/api/v1/types.go
  pkg/virt-api/rest/subresource.go
  pkg/virt-controller/services/template.go
  pkg/virt-controller/services/template_test.go
  pkg/virt-controller/watch/node.go
  pkg/virt-controller/watch/node_test.go
  pkg/virt-controller/watch/vmi.go
  pkg/virt-controller/watch/vmi_test.go
  pkg/virt-handler/cmd-client/client.go
  pkg/virt-handler/vm.go
  pkg/virt-handler/vm_test.go
  tests/utils.go
  tests/vm_test.go
  tests/vmi_configuration_test.go
  tests/vmi_hook_sidecar_test.go
  tests/vmi_lifecycle_test.go
  tests/vmi_networking_test.go
  tests/vmi_slirp_interface_test.go
  tests/vmi_userdata_test.go
Labels: release-note-none, size/L

#1414 Allow separating guest memory from resource request
  api/openapi-spec/swagger.json
  manifests/generated/vm-resource.yaml
  manifests/generated/vmi-resource.yaml
  manifests/generated/vmipreset-resource.yaml
  manifests/generated/vmirs-resource.yaml
  pkg/api/v1/deepcopy_generated.go
  pkg/api/v1/openapi_generated.go
  pkg/api/v1/schema.go
  pkg/api/v1/schema_swagger_generated.go
  pkg/virt-api/validating-webhook/validating-webhook.go
  pkg/virt-api/validating-webhook/validating-webhook_test.go
  pkg/virt-launcher/virtwrap/api/converter.go
  pkg/virt-launcher/virtwrap/api/converter_test.go
  tests/vmi_configuration_test.go
Labels: size/L

#1415 Fix manifest rbac
  manifests/dev/rbac.authorization.k8s.yaml.in
  manifests/release/kubevirt.yaml.in
Labels: release-note-none, size/L

#1411 add boot order to network interface
  api/openapi-spec/swagger.json
  manifests/generated/vm-resource.yaml
  manifests/generated/vmi-resource.yaml
  manifests/generated/vmipreset-resource.yaml
  manifests/generated/vmirs-resource.yaml
  pkg/api/v1/deepcopy_generated.go
  pkg/api/v1/openapi_generated.go
  pkg/api/v1/schema.go
  pkg/api/v1/schema_swagger_generated.go
  pkg/virt-api/validating-webhook/validating-webhook.go
  pkg/virt-api/validating-webhook/validating-webhook_test.go
  pkg/virt-launcher/virtwrap/api/converter.go
  pkg/virt-launcher/virtwrap/api/converter_test.go
Labels: release-note, size/M

#1399 Expose libvirtd logs to kubectl logs
  cmd/virt-launcher/libvirtd.sh
  pkg/virt-launcher/virtwrap/util/libvirt_helper.go
  tests/vmi_lifecycle_test.go
Labels: release-note, size/XS

#1422 virt-preview is missing the repo file
  hack/docker-builder/Dockerfile
  hack/docker-builder/fedora-virt-preview.repo
Labels: release-note-none, size/S

#1432 Fix windows test
  tests/windows_test.go
Labels: release-note-none, size/XS

#1408 consolidate kubectl/oc/virtctl RunCommand() into one
  tests/access_test.go
  tests/template_test.go
  tests/utils.go
  tests/vmi_hook_sidecar_test.go
  tests/windows_test.go
Labels: release-note-none, size/L

#1431 Add std-ci to release-0.6
  automation/check-patch.k8s-1.10.4-release.mounts
  automation/check-patch.k8s-1.10.4-release.packages
  automation/check-patch.k8s-1.10.4-release.sh
  automation/check-patch.openshift-3.10-crio-release.mounts
  automation/check-patch.openshift-3.10-crio-release.packages
  automation/check-patch.openshift-3.10-crio-release.sh
  automation/check-patch.openshift-3.10-release.mounts
  automation/check-patch.openshift-3.10-release.packages
  automation/check-patch.openshift-3.10-release.sh
  automation/check-patch.packages.el7
  automation/check-patch.sh
  automation/test.sh
  cluster/deploy.sh
  cluster/ephemeral-provider-common.sh
  cluster/k8s-1.11.0/README.md
  cluster/k8s-1.11.0/provider.sh
  cluster/k8s-1.9.3/provider.sh
  cluster/os-3.10.0-crio/README.md
  cluster/os-3.10.0-crio/provider.sh
  cluster/os-3.10.0/README.md
  cluster/os-3.10.0/provider.sh
  cluster/os-3.9.0-crio/README.md
  cluster/os-3.9.0-crio/provider.sh
  hack/version.sh
  stdci.yaml
Labels: release-note-none, size/L

#1427 add boot order to network interface for 0.6
  api/openapi-spec/swagger.json
  manifests/generated/vm-resource.yaml
  manifests/generated/vmi-resource.yaml
  manifests/generated/vmipreset-resource.yaml
  manifests/generated/vmirs-resource.yaml
  pkg/api/v1/deepcopy_generated.go
  pkg/api/v1/openapi_generated.go
  pkg/api/v1/schema.go
  pkg/api/v1/schema_swagger_generated.go
  pkg/virt-api/validating-webhook/validating-webhook.go
  pkg/virt-api/validating-webhook/validating-webhook_test.go
  pkg/virt-launcher/virtwrap/api/converter.go
  pkg/virt-launcher/virtwrap/api/converter_test.go
Labels: release-note-none, size/L

#1433 Fix VMI lifecycle test
  tests/vmi_lifecycle_test.go
Labels: release-note-none, size/XS

#1417 Fetch windows image from remote http server
  automation/check-patch.mounts
  automation/test.sh
  cluster/ephemeral-provider-common.sh
Labels: size/M

#1426 Merge pull request #1414 from rmohr/memory-overcommit-v2
  api/openapi-spec/swagger.json
  manifests/generated/vm-resource.yaml
  manifests/generated/vmi-resource.yaml
  manifests/generated/vmipreset-resource.yaml
  manifests/generated/vmirs-resource.yaml
  pkg/api/v1/deepcopy_generated.go
  pkg/api/v1/openapi_generated.go
  pkg/api/v1/schema.go
  pkg/api/v1/schema_swagger_generated.go
  pkg/virt-api/validating-webhook/validating-webhook.go
  pkg/virt-api/validating-webhook/validating-webhook_test.go
  pkg/virt-launcher/virtwrap/api/converter.go
  pkg/virt-launcher/virtwrap/api/converter_test.go
  tests/vmi_configuration_test.go
Labels: size/L

#1436 Always put default route last to ensure it can be applied
  pkg/virt-launcher/virtwrap/network/dhcp/dhcp.go
  pkg/virt-launcher/virtwrap/network/dhcp/dhcp_test.go
Labels: release-note, size/S

#1440 Revert go-restful-openapi to previous version.
  api/openapi-spec/swagger.json
  glide.lock
  glide.yaml
  vendor/github.com/emicklei/go-restful-openapi/CHANGES.md
  vendor/github.com/emicklei/go-restful-openapi/definition_builder.go
  vendor/github.com/emicklei/go-restful-openapi/spec_resource.go
Labels: release-note, size/L

#1446 Use libvirt-go from tagged branch
  glide.lock
  glide.yaml
  vendor/github.com/go-openapi/spec/.golangci.yml
  vendor/github.com/go-openapi/spec/expander.go
  vendor/github.com/go-openapi/spec/fixtures/bugs/1614/gitea.json
  vendor/github.com/go-openapi/spec/fixtures/bugs/1621/definitions.yaml
  vendor/github.com/go-openapi/spec/fixtures/bugs/1621/fixture-1621.yaml
  vendor/github.com/go-openapi/spec/fixtures/bugs/1621/parameters.yaml
  vendor/github.com/go-openapi/spec/fixtures/bugs/1621/responses.yaml
  vendor/github.com/golang/mock/mockgen/mockgen.go
  vendor/github.com/krolaw/dhcp4/packet.go
  vendor/github.com/onsi/gomega/matchers/be_numerically_matcher.go
  vendor/google.golang.org/appengine/internal/app_identity/app_identity_service.pb.go
  vendor/google.golang.org/appengine/internal/base/api_base.pb.go
  vendor/google.golang.org/appengine/internal/blobstore/blobstore_service.pb.go
  vendor/google.golang.org/appengine/internal/capability/capability_service.pb.go
  vendor/google.golang.org/appengine/internal/channel/channel_service.pb.go
  vendor/google.golang.org/appengine/internal/datastore/datastore_v3.pb.go
  vendor/google.golang.org/appengine/internal/image/images_service.pb.go
  vendor/google.golang.org/appengine/internal/log/log_service.pb.go
  vendor/google.golang.org/appengine/internal/mail/mail_service.pb.go
  vendor/google.golang.org/appengine/internal/memcache/memcache_service.pb.go
  vendor/google.golang.org/appengine/internal/modules/modules_service.pb.go
  vendor/google.golang.org/appengine/internal/remote_api/remote_api.pb.go
  vendor/google.golang.org/appengine/internal/search/search.pb.go
  vendor/google.golang.org/appengine/internal/socket/socket_service.pb.go
  vendor/google.golang.org/appengine/internal/system/system_service.pb.go
  vendor/google.golang.org/appengine/internal/taskqueue/taskqueue_service.pb.go
  vendor/google.golang.org/appengine/internal/urlfetch/urlfetch_service.pb.go
  vendor/google.golang.org/appengine/internal/user/user_service.pb.go
  vendor/google.golang.org/appengine/internal/xmpp/xmpp_service.pb.go
Labels: release-note-none, size/XXL

#1393 Allow setting vNIC pci address
  api/openapi-spec/swagger.json
  manifests/generated/vm-resource.yaml
  manifests/generated/vmi-resource.yaml
  manifests/generated/vmipreset-resource.yaml
  manifests/generated/vmirs-resource.yaml
  pkg/api/v1/openapi_generated.go
  pkg/api/v1/schema.go
  pkg/api/v1/schema_swagger_generated.go
  pkg/util/hw_helper.go
  pkg/virt-api/validating-webhook/validating-webhook.go
  pkg/virt-api/validating-webhook/validating-webhook_test.go
  pkg/virt-launcher/virtwrap/api/converter.go
  pkg/virt-launcher/virtwrap/api/converter_test.go
  tests/vmi_networking_test.go
Labels: release-note, size/L

#1377 Set reporting style for STDCI to plain HTML
  stdci.yaml
Labels: release-note-none, size/XS

#1450 Remove references to OVM
  pkg/api/v1/types.go
  pkg/kubecli/kubevirt.go
  pkg/kubecli/kubevirt_test_utils.go
  pkg/kubecli/vm.go
  pkg/virtctl/console/console.go
  pkg/virtctl/expose/expose.go
  pkg/virtctl/expose/expose_test.go
  pkg/virtctl/vm/vm.go
  pkg/virtctl/vm/vm_suite_test.go
  pkg/virtctl/vnc/vnc.go
Labels: release-note-none, size/L

#1453 Make virtctl short commands consistent with naming of objects
  pkg/virtctl/console/console.go
  pkg/virtctl/expose/expose.go
  pkg/virtctl/vm/vm.go
  pkg/virtctl/vnc/vnc.go
Labels: release-note-none, size/XS

#1451 Cnv 1 stabilize stdci
  automation/check-patch.mounts
  automation/check-patch.windows2016-release.mounts
  automation/check-patch.windows2016-release.packages
  automation/check-patch.windows2016-release.sh
  automation/test.sh
  cluster/ephemeral-provider-common.sh
  cmd/virt-launcher/virt-launcher.go
  pkg/api/v1/types.go
  pkg/kubecli/vmi.go
  pkg/virt-api/rest/subresource.go
  pkg/virt-controller/services/template.go
  pkg/virt-controller/services/template_test.go
  pkg/virt-controller/watch/node.go
  pkg/virt-controller/watch/node_test.go
  pkg/virt-controller/watch/vmi.go
  pkg/virt-controller/watch/vmi_test.go
  pkg/virt-handler/cmd-client/client.go
  pkg/virt-handler/vm.go
  pkg/virt-handler/vm_test.go
  pkg/virt-launcher/notify-client/client.go
  pkg/virt-launcher/virtwrap/api/deepcopy_generated.go
  pkg/virt-launcher/virtwrap/api/schema.go
  pkg/virt-launcher/virtwrap/cmd-server/server.go
  pkg/virt-launcher/virtwrap/cmd-server/server_test.go
  pkg/virt-launcher/virtwrap/generated_mock_manager.go
  pkg/virt-launcher/virtwrap/manager.go
  pkg/virt-launcher/virtwrap/manager_test.go
  pkg/virt-launcher/virtwrap/util/libvirt_helper.go
  stdci.yaml
  tests/utils.go
  tests/vmi_configuration_test.go
  tests/vmi_lifecycle_test.go
  tests/vmi_networking_test.go
  tests/vmi_userdata_test.go
Labels: release-note-none, size/XL

#1455 Fix MAC and bridge tests
  pkg/virt-launcher/virtwrap/network/podinterface.go
  pkg/virt-launcher/virtwrap/network/podinterface_test.go
  tests/vmi_bridge_test.go
  tests/vmi_networking_test.go
Labels: release-note-none, size/L

#1456 Update k8s providers for 1.10 and 1.11
  cluster/k8s-1.10.4/provider.sh
  cluster/k8s-1.11.0/provider.sh
Labels: release-note-none, size/XS

#1449 Save VMI UUID under map for future use on cleanup stage
  pkg/api/v1/types.go
  pkg/virt-handler/vm.go
  pkg/virt-handler/vm_test.go
  pkg/virt-launcher/virtwrap/api/schema.go
  pkg/watchdog/watchdog.go
Labels: release-note-none, size/M

#1452 Fix python client SDK generator
  hack/gen-client-python/generate.sh
  hack/gen-client-python/hard-coded-modules/v1_interface_bridge.py
  hack/gen-client-python/hard-coded-modules/v1_interface_slirp.py
Labels: release-note, size/L

#1430 static MAC on VM interfaces for 0.6
  api/openapi-spec/swagger.json
  manifests/generated/vm-resource.yaml
  manifests/generated/vmi-resource.yaml
  manifests/generated/vmipreset-resource.yaml
  manifests/generated/vmirs-resource.yaml
  pkg/api/v1/openapi_generated.go
  pkg/api/v1/schema.go
  pkg/api/v1/schema_swagger_generated.go
  pkg/virt-api/validating-webhook/validating-webhook.go
  pkg/virt-api/validating-webhook/validating-webhook_test.go
  pkg/virt-launcher/virtwrap/network/podinterface.go
  pkg/virt-launcher/virtwrap/network/podinterface_test.go
  tests/utils.go
  tests/vmi_networking_test.go
Labels: release-note-none, size/L

#1468 propagate device aliases to libvirt using user-aliases
  pkg/virt-launcher/virtwrap/api/converter_test.go
  pkg/virt-launcher/virtwrap/api/deepcopy_generated.go
  pkg/virt-launcher/virtwrap/api/schema.go
  pkg/virt-launcher/virtwrap/api/schema_test.go
  pkg/virt-launcher/virtwrap/network/podinterface_test.go
Labels: release-note-none, size/M

#1473 Fix wrong demo-content.yaml
  manifests/release/demo-content.yaml.in
Labels: release-note-none, size/XS

#1447 add --client flag to virtctl version
  pkg/virtctl/version/version.go
Labels: release-note, size/S

#1471 Use exec.Command to setup network under specific namespace
  cmd/virt-handler/Dockerfile
  pkg/virt-handler/devices/bridge.go
  pkg/virt-handler/ns/ns.go
Labels: release-note, size/XL

#1476 Use CRD to represent custom resource instead of TPR in arch doc
  docs/architecture.md
Labels: release-note-none, size/XS

#1482 Include 'git describe' result in all virt-* containers
  cmd/virt-api/Dockerfile
  cmd/virt-controller/Dockerfile
  cmd/virt-handler/Dockerfile
  cmd/virt-launcher/Dockerfile
  hack/build-docker.sh
Labels: release-note-none, size/XS

#1385 Virtiorng
  api/openapi-spec/swagger.json
  manifests/generated/vm-resource.yaml
  manifests/generated/vmi-resource.yaml
  manifests/generated/vmipreset-resource.yaml
  manifests/generated/vmirs-resource.yaml
  pkg/api/v1/deepcopy_generated.go
  pkg/api/v1/defaults.go
  pkg/api/v1/defaults_test.go
  pkg/api/v1/openapi_generated.go
  pkg/api/v1/schema.go
  pkg/api/v1/schema_swagger_generated.go
  pkg/api/v1/schema_test.go
  pkg/virt-launcher/virtwrap/api/converter.go
  pkg/virt-launcher/virtwrap/api/converter_test.go
  pkg/virt-launcher/virtwrap/api/deepcopy_generated.go
  pkg/virt-launcher/virtwrap/api/deepcopy_test.go
  pkg/virt-launcher/virtwrap/api/schema.go
  pkg/virt-launcher/virtwrap/api/schema_test.go
  tests/vmi_configuration_test.go
Labels: release-note, size/L, topic/performance

#1485 Introduce an optional subprotocol for browser websocket connections
  pkg/kubecli/vmi.go
  pkg/util/subresources/constants.go
  pkg/virt-api/rest/subresource.go
  tests/vnc_test.go
Labels: release-note, size/M
