Repository kubevirt/kubevirt, pull requests merged in 2018-10, with the labels that each got.

#1566 Added more details to local provider README
  cluster/local/README.md
Labels: release-note-none, size/M

#1480 Iothreads rethought
  api/openapi-spec/swagger.json
  manifests/generated/vm-resource.yaml
  manifests/generated/vmi-resource.yaml
  manifests/generated/vmipreset-resource.yaml
  manifests/generated/vmirs-resource.yaml
  pkg/api/v1/deepcopy_generated.go
  pkg/api/v1/defaults_test.go
  pkg/api/v1/openapi_generated.go
  pkg/api/v1/schema.go
  pkg/api/v1/schema_swagger_generated.go
  pkg/api/v1/schema_test.go
  pkg/virt-api/webhooks/mutating-webhook/preset.go
  pkg/virt-api/webhooks/mutating-webhook/preset_test.go
  pkg/virt-api/webhooks/validating-webhook/validating-webhook.go
  pkg/virt-launcher/virtwrap/api/converter.go
  pkg/virt-launcher/virtwrap/api/converter_test.go
  pkg/virt-launcher/virtwrap/api/deepcopy_generated.go
  pkg/virt-launcher/virtwrap/api/schema.go
  pkg/virt-launcher/virtwrap/api/schema_test.go
  tests/vmi_iothreads_test.go
Labels: release-note, size/XL

#1573 --now is cool
  cluster/local/README.md
Labels: release-note-none, size/XS

#1575 Wait in virt-api for cache sync before reporting it as ready
  pkg/virt-api/api.go
  pkg/virt-api/webhooks/utils.go
Labels: release-note-none, size/XS

#1577 Fix minor typo
  docs/cloud-init.md
Labels: release-note-none, size/XS

#1572 VMs lifecycle tests: fix assumption for compute nodes
  tests/utils.go
  tests/vmi_lifecycle_test.go
Labels: release-note-none, size/S

#1586 Merge pull request #1572 from lukas-bednar/test-lifecycle
  tests/utils.go
  tests/vmi_lifecycle_test.go
Labels: release-note-none, size/S

#1578 VMI configuration test: add retrying to make sure LimitRange cached
  pkg/api/v1/types.go
  tests/vmi_configuration_test.go
Labels: release-note-none, size/S

#1567 Add vhost-net support
  docs/software-emulation.md
  pkg/virt-controller/services/template.go
  pkg/virt-handler/device-manager/device_controller.go
  pkg/virt-launcher/virtwrap/api/converter.go
  tests/utils.go
Labels: release-note, size/M

#1582 Set option 15 for windows machines on DHCP requests
  pkg/util/net/dns/dns_suite_test.go
  pkg/util/net/dns/resolveconf.go
  pkg/util/net/dns/resolveconf_test.go
  pkg/virt-launcher/virtwrap/api/converter.go
  pkg/virt-launcher/virtwrap/api/converter_test.go
  pkg/virt-launcher/virtwrap/api/defaults.go
  pkg/virt-launcher/virtwrap/network/dhcp/dhcp.go
  pkg/virt-launcher/virtwrap/network/dhcp/dhcp_test.go
  tests/windows_test.go
Labels: release-note, size/L

#1597 Add regression test for creating a VMI with name longer than 63 characters
  tests/vmi_lifecycle_test.go
Labels: release-note-none, size/S

#1534 Set mac learning off on pod ifaces
  pkg/virt-launcher/virtwrap/network/common.go
  pkg/virt-launcher/virtwrap/network/generated_mock_common.go
  pkg/virt-launcher/virtwrap/network/podinterface.go
  pkg/virt-launcher/virtwrap/network/podinterface_test.go
  tests/vmi_networking_test.go
Labels: release-note-none, size/M, topic/network

#1599 Add a label to all PRs which potentially changes the API
  pkg/api/OWNERS
Labels: release-note-none, size/XS

#1592 Extend and refactor template test
  tests/access_test.go
  tests/template_test.go
  tests/utils.go
  tests/vmi_hook_sidecar_test.go
  tests/windows_test.go
  tools/vms-generator/utils/utils.go
Labels: release-note-none, size/XL

#1562 Introduce virtio multi-queue
  api/openapi-spec/swagger.json
  manifests/generated/vm-resource.yaml
  manifests/generated/vmi-resource.yaml
  manifests/generated/vmipreset-resource.yaml
  manifests/generated/vmirs-resource.yaml
  pkg/api/v1/deepcopy_generated.go
  pkg/api/v1/openapi_generated.go
  pkg/api/v1/schema.go
  pkg/api/v1/schema_swagger_generated.go
  pkg/api/v1/schema_test.go
  pkg/virt-api/webhooks/validating-webhook/validating-webhook.go
  pkg/virt-api/webhooks/validating-webhook/validating-webhook_test.go
  pkg/virt-launcher/virtwrap/api/converter.go
  pkg/virt-launcher/virtwrap/api/converter_test.go
  pkg/virt-launcher/virtwrap/api/deepcopy_generated.go
  pkg/virt-launcher/virtwrap/api/schema.go
  pkg/virt-launcher/virtwrap/api/schema_test.go
  tests/utils.go
  tests/vmi_configuration_test.go
Labels: release-note, size/L

#1603 DiskSecret: either have Usage or UUID, not both
  pkg/virt-launcher/virtwrap/api/schema.go
Labels: do-not-merge/release-note-label-needed, size/XS

#1616 api: return empty array in resources for subresources endpoint
  pkg/virt-api/api.go
Labels: do-not-merge/release-note-label-needed, size/XS

#1624 Updated CI images for fixing test issues with ssh.sh
  cluster/k8s-1.10.4/provider.sh
  cluster/k8s-1.11.0/provider.sh
  cluster/k8s-multus-1.11.1/provider.sh
  cluster/os-3.10.0-crio/provider.sh
  cluster/os-3.10.0-multus/provider.sh
  cluster/os-3.10.0/provider.sh
Labels: release-note-none, size/S

#1630 Fixes Libvirt Lifecycle event callback
  cmd/virt-launcher/virt-launcher.go
Labels: release-note-none, size/S

#1608 Provide ServiceAccount token etc. to VM
  api/openapi-spec/swagger.json
  cmd/virt-launcher/virt-launcher.go
  manifests/generated/vm-resource.yaml
  manifests/generated/vmi-resource.yaml
  manifests/generated/vmirs-resource.yaml
  pkg/api/v1/deepcopy_generated.go
  pkg/api/v1/openapi_generated.go
  pkg/api/v1/schema.go
  pkg/api/v1/schema_swagger_generated.go
  pkg/config/config.go
  pkg/config/service-account.go
  pkg/config/service-account_test.go
  pkg/virt-api/webhooks/validating-webhook/validating-webhook.go
  pkg/virt-api/webhooks/validating-webhook/validating-webhook_test.go
  pkg/virt-controller/services/template.go
  pkg/virt-controller/services/template_test.go
  pkg/virt-launcher/virtwrap/api/converter.go
  pkg/virt-launcher/virtwrap/api/converter_test.go
  pkg/virt-launcher/virtwrap/manager.go
  tests/config_test.go
  tests/utils.go
Labels: kind/api-change, release-note, size/L

#1636 Improved block volume PVC test
  tests/storage_test.go
  tests/utils.go
Labels: release-note-none, size/L

#1614 Ensure that transitive builds work with kubevirt after glog shadowing was introduced
  cmd/fake-qemu-process/fake-qemu.go
  cmd/virt-handler/virt-handler.go
  cmd/virt-launcher/virt-launcher.go
  hack/dep-prune.sh
  pkg/controller/controller.go
  pkg/log/log.go
  pkg/log/log_test.go
  pkg/rest/filter/filter.go
  pkg/service/service.go
  pkg/staging/glog/glog.go
  pkg/virt-controller/leaderelectionconfig/config.go
  pkg/virt-controller/watch/application.go
  pkg/virt-handler/migration-proxy/migration_proxy_suite_test.go
Labels: release-note-none, size/L

#1583 Fix ptp cni plugin test and added tests for ovs cni plugin.
  cluster/k8s-multus-1.11.1/provider.sh
  cluster/os-3.10.0-multus/provider.sh
  tests/vmi_multus_test.go
Labels: kind/api-change, release-note, size/L

#1629 libvirt: DiskSecret - add supported UUID field
  pkg/virt-launcher/virtwrap/api/schema.go
Labels: release-note-none, size/XS

#1604 Pin IOThreads to pCPUs when DedicatedCPUPlacement is enabled
  pkg/virt-launcher/virtwrap/api/converter.go
  pkg/virt-launcher/virtwrap/api/converter_test.go
  pkg/virt-launcher/virtwrap/api/deepcopy_generated.go
  pkg/virt-launcher/virtwrap/api/schema.go
  pkg/virt-launcher/virtwrap/api/schema_test.go
  tests/vmi_configuration_test.go
Labels: release-note-none, size/L

#1606 Add support for virtio-net multiqueue
  api/openapi-spec/swagger.json
  manifests/generated/vm-resource.yaml
  manifests/generated/vmi-resource.yaml
  manifests/generated/vmipreset-resource.yaml
  manifests/generated/vmirs-resource.yaml
  pkg/api/v1/deepcopy_generated.go
  pkg/api/v1/openapi_generated.go
  pkg/api/v1/schema.go
  pkg/api/v1/schema_swagger_generated.go
  pkg/virt-api/webhooks/validating-webhook/validating-webhook.go
  pkg/virt-api/webhooks/validating-webhook/validating-webhook_test.go
  pkg/virt-launcher/virtwrap/api/converter.go
  pkg/virt-launcher/virtwrap/api/converter_test.go
  pkg/virt-launcher/virtwrap/api/deepcopy_generated.go
  pkg/virt-launcher/virtwrap/api/schema.go
  tests/vmi_configuration_test.go
Labels: kind/api-change, release-note-none, size/L

#1641 Add ownerReferences to virt-launcher
  pkg/virt-controller/services/template.go
  pkg/virt-controller/services/template_test.go
Labels: release-note, size/S

#1643 schema doc - new line
  api/openapi-spec/swagger.json
  pkg/api/v1/openapi_generated.go
  pkg/api/v1/schema.go
  pkg/api/v1/schema_swagger_generated.go
Labels: kind/api-change, size/XS

#1648 Fix cpu pinning
  pkg/virt-controller/services/template.go
  tests/vmi_configuration_test.go
Labels: release-note-none, size/M

#1640 Patch/sock connector exec
  cmd/virt-launcher/sock-connector
Labels: release-note-none, size/M

#1649 use new hash for genie image
  cluster/k8s-genie-1.11.1/provider.sh
Labels: release-note-none, size/XS

#1650 Improved console test
  tests/console_test.go
Labels: release-note-none, size/M

#1654 add additional fields to kubectl get vm/vmi
  manifests/generated/vm-resource.yaml
  manifests/generated/vmi-resource.yaml
  tools/crd-generator/crd-generator.go
Labels: release-note, size/M

#1651 Bugfix - disk device cache
  pkg/virt-launcher/virtwrap/api/converter.go
  pkg/virt-launcher/virtwrap/api/converter_test.go
  pkg/virt-launcher/virtwrap/manager.go
  tests/storage_test.go
  tests/utils.go
  tests/vmi_configuration_test.go
Labels: release-note, size/L

#1658 Merge pull request #1651 from mfranczy/bugfix-disk-device-cache
  pkg/virt-launcher/virtwrap/api/converter.go
  pkg/virt-launcher/virtwrap/api/converter_test.go
  pkg/virt-launcher/virtwrap/manager.go
  tests/storage_test.go
  tests/utils.go
  tests/vmi_configuration_test.go
Labels: release-note, size/L

#1656 VMIRS server side printing
  manifests/generated/vmirs-resource.yaml
  tests/replicaset_test.go
  tools/crd-generator/crd-generator.go
Labels: release-note, size/M

#1595 Report mac addresses in vmi status interfaces section
  api/openapi-spec/swagger.json
  pkg/api/v1/openapi_generated.go
  pkg/api/v1/types.go
  pkg/api/v1/types_swagger_generated.go
  pkg/virt-controller/watch/vmi.go
  pkg/virt-controller/watch/vmi_test.go
  pkg/virt-handler/vm.go
  pkg/virt-handler/vm_test.go
  tests/vmi_multus_test.go
Labels: kind/api-change, release-note, size/L

#1660 Fixed virtctl release artifacts
  .travis.yml
Labels: release-note-none, size/XS
