Repository kubevirt/kubevirt, pull requests merged in 2019-08, with the labels that each got.

#2552 Add a new reporter which collects cluster info into files
  hack/functests.sh
  tests/BUILD.bazel
  tests/reporter/BUILD.bazel
  tests/reporter/kubernetes.go
  tests/tests_suite_test.go
  tests/utils.go
Labels: release-note-none, size/L

#2548 Use HCO conditions on KubeVirt CR
  hack/cluster-deploy.sh
  pkg/virt-operator/kubevirt.go
  pkg/virt-operator/kubevirt_test.go
  pkg/virt-operator/util/client.go
  pkg/virt-operator/util/client_test.go
  staging/src/kubevirt.io/client-go/api/v1/types.go
  tests/operator_test.go
Labels: approved, kind/api-change, lgtm, release-note, size/XL

#2546 Enable sriov support by default
  docs/sriov.md
  hack/cluster-deploy.sh
  pkg/virt-api/webhooks/validating-webhook/admitters/vmi-create-admitter.go
  pkg/virt-api/webhooks/validating-webhook/admitters/vmi-create-admitter_test.go
  pkg/virt-config/feature-gates.go
Labels: approved, lgtm, release-note, size/M, topic/network

#2554 Fix annotations not being copied in data volume templates.
  pkg/virt-controller/watch/vm.go
  pkg/virt-controller/watch/vm_test.go
Labels: approved, lgtm, release-note, size/S

#2506 metrics: fix prefix kubevirt_vm -> kubevirt_vmi
  pkg/monitoring/vms/prometheus/prometheus.go
  tests/infra_test.go
Labels: approved, lgtm, release-note, size/M

#2558 [Release 0.13] Docker creds
  .travis.yml
Labels: lgtm, release-note-none, size/XS

#2550 Added a check to VMI validating webhook to not allow non-dns1123 comp…
  pkg/virt-api/webhooks/validating-webhook/admitters/vmi-create-admitter.go
  pkg/virt-api/webhooks/validating-webhook/admitters/vmi-create-admitter_test.go
Labels: approved, lgtm, ok-to-test, release-note-none, size/S

#2541 Change from iptables to nftables 0.17
  pkg/virt-launcher/virtwrap/network/BUILD.bazel
  pkg/virt-launcher/virtwrap/network/common.go
  pkg/virt-launcher/virtwrap/network/generated_mock_common.go
  pkg/virt-launcher/virtwrap/network/podinterface.go
  pkg/virt-launcher/virtwrap/network/podinterface_test.go
  vendor/k8s.io/kube-openapi/pkg/handler/BUILD.bazel
Labels: lgtm, release-note, size/L

#2395 Make containerdisks secure and supportable
  BUILD.bazel
  cmd/chroot/BUILD.bazel
  cmd/chroot/main.go
  cmd/container-disk-v1alpha/BUILD.bazel
  cmd/container-disk-v1alpha/entry-point.sh
  cmd/container-disk-v2alpha/BUILD.bazel
  cmd/container-disk-v2alpha/README.md
  cmd/container-disk-v2alpha/main.go
  cmd/virt-handler/BUILD.bazel
  cmd/virt-handler/virt-handler.go
  cmd/virt-launcher/virt-launcher.go
  docs/container-register-disks.md
  hack/config-default.sh
  manifests/generated/virt-handler.yaml.in
  pkg/container-disk/BUILD.bazel
  pkg/container-disk/container-disk.go
  pkg/container-disk/container-disk_test.go
  pkg/container-disk/validation.go
  pkg/ephemeral-disk/ephemeral-disk.go
  pkg/util/util.go
  pkg/virt-api/rest/subresource_test.go
  pkg/virt-controller/services/template.go
  pkg/virt-controller/services/template_test.go
  pkg/virt-controller/watch/application.go
  pkg/virt-controller/watch/migration_test.go
  pkg/virt-controller/watch/vmi_test.go
  pkg/virt-handler/BUILD.bazel
  pkg/virt-handler/container-disk/BUILD.bazel
  pkg/virt-handler/container-disk/mount.go
  pkg/virt-handler/isolation/BUILD.bazel
  pkg/virt-handler/isolation/generated_mock_isolation.go
  pkg/virt-handler/isolation/isolation.go
  pkg/virt-handler/isolation/validation.go
  pkg/virt-handler/selinux/BUILD.bazel
  pkg/virt-handler/selinux/labels.go
  pkg/virt-handler/selinux/labels_test.go
  pkg/virt-handler/selinux/selinux_suite_test.go
  pkg/virt-handler/vm.go
  pkg/virt-launcher/virtwrap/api/converter.go
  pkg/virt-launcher/virtwrap/api/deepcopy_generated.go
  pkg/virt-launcher/virtwrap/cmd-server/server.go
  pkg/virt-launcher/virtwrap/manager.go
  pkg/virt-operator/creation/components/deployments.go
  tests/BUILD.bazel
  tests/container_disk_test.go
  tests/migration_test.go
  tests/operator_test.go
  tests/utils.go
  vendor/modules.txt
Labels: approved, lgtm, release-note, size/XXL

#2542 Forward all in masquerade 0.17
  pkg/virt-launcher/virtwrap/network/podinterface.go
  tests/vmi_networking_test.go
Labels: lgtm, release-note, size/M

#2551 example for client-go package
  hack/bazel-build.sh
  staging/src/kubevirt.io/client-go/README.md
  staging/src/kubevirt.io/client-go/examples/README.md
  staging/src/kubevirt.io/client-go/examples/listvms/BUILD.bazel
  staging/src/kubevirt.io/client-go/examples/listvms/README.md
  staging/src/kubevirt.io/client-go/examples/listvms/go.mod
  staging/src/kubevirt.io/client-go/examples/listvms/go.sum
  staging/src/kubevirt.io/client-go/examples/listvms/list-vms.go
Labels: lgtm, needs-ok-to-test, release-note-none, size/L

#2565 Corrected duplicate test-id
  tests/vmi_configuration_test.go
Labels: lgtm, release-note-none, size/XS

#2568 Fix virt-handler restart issue
  cmd/virt-handler/virt-handler.go
  pkg/virt-handler/selinux/labels.go
  pkg/virt-handler/selinux/labels_test.go
Labels: approved, lgtm, release-note-none, size/M

#2564 Add wait until migration kick in
  tests/migration_test.go
Labels: approved, lgtm, release-note-none, size/S

#2572 Add test_id for vmi_headless test
  tests/vmi_headless_test.go
Labels: lgtm, release-note-none, size/XS

#2575 typo fixed.
  staging/src/kubevirt.io/client-go/README.md
Labels: lgtm, ok-to-test, release-note-none, size/XS

#2576 Ensure that we can handle transient selinux errors
  cmd/virt-handler/virt-handler.go
Labels: approved, lgtm, release-note-none, size/S

#2519 Remove pod/exec privileges from virt-api
  cmd/virt-handler/BUILD.bazel
  cmd/virt-handler/virt-handler.go
  manifests/generated/operator-csv.yaml.in
  manifests/generated/rbac-kubevirt.authorization.k8s.yaml.in
  manifests/generated/rbac-operator.authorization.k8s.yaml.in
  manifests/generated/virt-api.yaml.in
  manifests/generated/virt-handler.yaml.in
  pkg/virt-api/api.go
  pkg/virt-api/rest/BUILD.bazel
  pkg/virt-api/rest/subresource.go
  pkg/virt-api/rest/subresource_test.go
  pkg/virt-handler/BUILD.bazel
  pkg/virt-handler/isolation/isolation.go
  pkg/virt-handler/rest/BUILD.bazel
  pkg/virt-handler/rest/console.go
  pkg/virt-handler/vm.go
  pkg/virt-handler/vm_test.go
  pkg/virt-operator/creation/components/deployments.go
  pkg/virt-operator/creation/rbac/apiserver.go
  pkg/virt-operator/creation/rbac/operator.go
  staging/src/kubevirt.io/client-go/kubecli/BUILD.bazel
  staging/src/kubevirt.io/client-go/kubecli/handler.go
  staging/src/kubevirt.io/client-go/kubecli/vmi.go
  staging/src/kubevirt.io/client-go/kubecli/websocket.go
  tests/console_test.go
  tests/vnc_test.go
Labels: kind/api-change, lgtm, release-note-none, size/XXL

#2570 Make Fedora VMI small and timeouts the same
  tests/migration_test.go
Labels: approved, lgtm, release-note-none, size/M

#2545 add kubevirt SecurityContextConstraints
  manifests/generated/operator-csv.yaml.in
  manifests/generated/rbac-operator.authorization.k8s.yaml.in
  pkg/virt-operator/application.go
  pkg/virt-operator/creation/components/BUILD.bazel
  pkg/virt-operator/creation/components/scc.go
  pkg/virt-operator/creation/rbac/operator.go
  pkg/virt-operator/install-strategy/create.go
  pkg/virt-operator/install-strategy/delete.go
  pkg/virt-operator/install-strategy/strategy.go
  pkg/virt-operator/kubevirt.go
  pkg/virt-operator/kubevirt_test.go
  pkg/virt-operator/util/types.go
  tests/operator_test.go
Labels: approved, lgtm, release-note, size/L

#2579 Log domain XMLs on test failures
  tests/reporter/BUILD.bazel
  tests/reporter/kubernetes.go
  tests/utils.go
Labels: approved, lgtm, release-note-none, size/M

#2509 clone authorization check in VM webhook
  go.mod
  go.sum
  manifests/generated/operator-csv.yaml.in
  manifests/generated/rbac-kubevirt.authorization.k8s.yaml.in
  manifests/generated/rbac-operator.authorization.k8s.yaml.in
  manifests/testing/cdi-v1.10.1.yaml.in
  pkg/virt-api/api.go
  pkg/virt-api/webhooks/validating-webhook/BUILD.bazel
  pkg/virt-api/webhooks/validating-webhook/admitters/BUILD.bazel
  pkg/virt-api/webhooks/validating-webhook/admitters/vms-admitter.go
  pkg/virt-api/webhooks/validating-webhook/admitters/vms-admitter_test.go
  pkg/virt-api/webhooks/validating-webhook/validating-webhook.go
  pkg/virt-controller/watch/BUILD.bazel
  pkg/virt-controller/watch/vm.go
  pkg/virt-controller/watch/vm_test.go
  pkg/virt-controller/watch/vmi.go
  pkg/virt-operator/creation/rbac/controller.go
  tests/BUILD.bazel
  tests/datavolume_test.go
  tests/utils.go
  vendor/kubevirt.io/containerized-data-importer/pkg/apis/core/v1alpha1/register.go
  vendor/kubevirt.io/containerized-data-importer/pkg/apis/core/v1alpha1/types.go
  vendor/kubevirt.io/containerized-data-importer/pkg/clone/BUILD.bazel
  vendor/kubevirt.io/containerized-data-importer/pkg/clone/auth.go
  vendor/modules.txt
Labels: approved, lgtm, release-note-none, size/XL

#2583 Fixed multiple addition of PodScheduled condition on VMI
  pkg/controller/BUILD.bazel
  pkg/controller/conditions.go
  pkg/controller/conditions_test.go
  pkg/virt-controller/watch/vmi.go
  pkg/virt-controller/watch/vmi_test.go
  tests/storage_test.go
Labels: lgtm, release-note-none, size/L

#2586 Fixed double "replaces: " in CSV
  tools/manifest-templator/manifest-templator.go
Labels: approved, lgtm, release-note-none, size/XS

#2571 libvirt: expose a way to enable the debug logs
  pkg/virt-controller/services/template.go
  pkg/virt-controller/services/template_test.go
  pkg/virt-launcher/virtwrap/util/libvirt_helper.go
  tests/vmi_lifecycle_test.go
Labels: approved, lgtm, release-note, size/M

#2557 Fix handling error in migration wait loop
  tests/migration_test.go
Labels: approved, lgtm, release-note-none, size/S

#2595 Qemu bug
  cmd/virt-launcher/virt-launcher.go
  pkg/virt-handler/rest/console.go
  pkg/virt-launcher/monitor.go
Labels: approved, lgtm, release-note-none, size/M

#2593 tests: bump default CPU to Nehalem
  tests/vmi_lifecycle_test.go
Labels: approved, lgtm, release-note-none, size/XS

#2600 Add ADOPTERS.md
  ADOPTERS.md
Labels: approved, lgtm, release-note, size/XS

#2594 Added feature to specify Chassis info for domain
  api/openapi-spec/swagger.json
  pkg/virt-launcher/virtwrap/api/converter.go
  pkg/virt-launcher/virtwrap/api/converter_test.go
  pkg/virt-launcher/virtwrap/api/deepcopy_generated.go
  pkg/virt-launcher/virtwrap/api/schema.go
  pkg/virt-launcher/virtwrap/api/schema_test.go
  staging/src/kubevirt.io/client-go/api/v1/deepcopy_generated.go
  staging/src/kubevirt.io/client-go/api/v1/openapi_generated.go
  staging/src/kubevirt.io/client-go/api/v1/schema.go
  staging/src/kubevirt.io/client-go/api/v1/schema_swagger_generated.go
  tests/vmi_configuration_test.go
Labels: approved, kind/api-change, lgtm, release-note, size/L

#2598 Remove sock-connector
  cmd/virt-launcher/BUILD.bazel
  cmd/virt-launcher/sock-connector
Labels: approved, lgtm, release-note-none, size/M

#2590 Improve prometheus functional tests
  tests/infra_test.go
Labels: approved, lgtm, release-note-none, size/L

#2602 limit cloudinit network data also to 2K and add info to error
  pkg/virt-api/webhooks/validating-webhook/admitters/vmi-create-admitter.go
Labels: approved, lgtm, ok-to-test, release-note, size/S

#2574 make pvc-size a mandatory param
  pkg/virtctl/imageupload/imageupload.go
  pkg/virtctl/imageupload/imageupload_test.go
Labels: approved, lgtm, ok-to-test, release-note-none, size/XS

#2614 Static go build of containerdisk binary
  hack/build-go.sh
Labels: lgtm, release-note-none, size/S

#2610 Added test_id in the test
  tests/vmi_configuration_test.go
Labels: lgtm, release-note, size/XS

#2592 Fixed release process
  .travis.yml
  hack/publish-staging.sh
Labels: lgtm, release-note-none, size/S

#2613 Add test-id to check kubevirt SCCs created tests
  tests/operator_test.go
Labels: lgtm, release-note-none, size/XS

#2619 Update doc of getting start
  docs/getting-started.md
Labels: lgtm, needs-ok-to-test, release-note-none, size/S

#2599 Add polarion test case ids regarding PDB test cases
  tests/virt_control_plane_test.go
Labels: approved, lgtm, release-note-none, size/L

#2611 Fix polarion test id of multiple VNC consoles test
  pkg/virt-config/feature-gates.go
  tests/networkpolicy_test.go
  tests/vnc_test.go
Labels: lgtm, release-note-none, size/S

#2620 Add test-ids for the regular user and sa user tests
  tests/access_test.go
  tests/vm_test.go
Labels: lgtm, release-note-none, size/S

#2468 Dedicated SELinux profile for virt-launcher
  cmd/virt-handler/BUILD.bazel
  cmd/virt-handler/base_container.cil
  cmd/virt-handler/virt-handler.go
  cmd/virt-handler/virt_launcher.cil
  pkg/virt-controller/services/template.go
  pkg/virt-handler/selinux/labels.go
Labels: approved, do-not-merge/hold, lgtm, release-note-none, size/M

#2563 Added functional test for custom MAC address for SR-IOV
  tests/vmi_multus_test.go
Labels: approved, lgtm, release-note-none, size/M, topic/network

#2629 add mfranczy to approvers
  OWNERS_ALIASES
Labels: approved, lgtm, release-note-none, size/XS

#2472 Add ability to specify SMBIOS details in kubevirt-config
  pkg/handler-launcher-com/cmd/v1/cmd.pb.go
  pkg/handler-launcher-com/cmd/v1/cmd.proto
  pkg/virt-config/BUILD.bazel
  pkg/virt-config/config-map.go
  pkg/virt-config/config_test.go
  pkg/virt-config/virt-config.go
  pkg/virt-handler/BUILD.bazel
  pkg/virt-handler/cmd-client/client.go
  pkg/virt-handler/cmd-client/generated_mock_client.go
  pkg/virt-handler/vm.go
  pkg/virt-handler/vm_test.go
  pkg/virt-launcher/virtwrap/BUILD.bazel
  pkg/virt-launcher/virtwrap/api/BUILD.bazel
  pkg/virt-launcher/virtwrap/api/converter.go
  pkg/virt-launcher/virtwrap/api/converter_test.go
  pkg/virt-launcher/virtwrap/cmd-server/BUILD.bazel
  pkg/virt-launcher/virtwrap/cmd-server/server.go
  pkg/virt-launcher/virtwrap/cmd-server/server_test.go
  pkg/virt-launcher/virtwrap/generated_mock_manager.go
  pkg/virt-launcher/virtwrap/manager.go
  pkg/virt-launcher/virtwrap/manager_test.go
  tests/BUILD.bazel
  tests/vmi_configuration_test.go
Labels: approved, kind/api-change, lgtm, release-note, size/L

#2622 Fix containerdisk doc
  cmd/container-disk-v2alpha/README.md
Labels: approved, lgtm, release-note-none, size/XS

#2634 Fixed virtctl console / vnc for namespaces != kubevirt
  cmd/virt-handler/BUILD.bazel
  cmd/virt-handler/virt-handler.go
  pkg/util/util.go
  pkg/virt-api/BUILD.bazel
  pkg/virt-api/api.go
  pkg/virt-api/rest/BUILD.bazel
  pkg/virt-api/rest/subresource.go
  pkg/virt-api/webhooks/BUILD.bazel
  pkg/virt-api/webhooks/utils.go
  pkg/virt-config/BUILD.bazel
  pkg/virt-config/config-map.go
  pkg/virt-controller/watch/BUILD.bazel
  pkg/virt-controller/watch/application.go
  pkg/virt-operator/BUILD.bazel
  pkg/virt-operator/application.go
  pkg/virt-operator/util/BUILD.bazel
  pkg/virt-operator/util/config.go
  staging/src/kubevirt.io/client-go/kubecli/BUILD.bazel
  staging/src/kubevirt.io/client-go/kubecli/handler.go
  staging/src/kubevirt.io/client-go/util/BUILD.bazel
  staging/src/kubevirt.io/client-go/util/util.go
Labels: approved, lgtm, release-note, size/L

#2631 Update OWNERS_ALIASES
  OWNERS_ALIASES
Labels: approved, lgtm, release-note, size/XS

#2607 change pod+bridge examples to pod+masquerade
  examples/vm-template-windows2012r2.yaml
  examples/vmi-multus-multiple-net.yaml
  examples/vmi-sriov.yaml
  examples/vmi-windows.yaml
  tools/vms-generator/utils/utils.go
Labels: approved, lgtm, ok-to-test, release-note, size/S

#2627 Carry annotations from VM down to the POD
  pkg/virt-controller/services/template.go
  pkg/virt-controller/services/template_test.go
  pkg/virt-controller/watch/vm.go
  tests/vm_test.go
  tests/vmi_lifecycle_test.go
Labels: approved, lgtm, release-note, size/L

#2630 Increase replicas on the csv-generator
  manifests/generated/operator-csv.yaml.in
  tools/csv-generator/csv-generator.go
Labels: approved, lgtm, release-note-none, size/XS

#2635 [release-0.20] Backport of "Fixed virtctl console / vnc for namespaces != kubevirt"
  cmd/virt-handler/BUILD.bazel
  cmd/virt-handler/virt-handler.go
  pkg/util/util.go
  pkg/virt-api/BUILD.bazel
  pkg/virt-api/api.go
  pkg/virt-api/rest/BUILD.bazel
  pkg/virt-api/rest/subresource.go
  pkg/virt-api/webhooks/BUILD.bazel
  pkg/virt-api/webhooks/utils.go
  pkg/virt-config/BUILD.bazel
  pkg/virt-config/config-map.go
  pkg/virt-controller/watch/BUILD.bazel
  pkg/virt-controller/watch/application.go
  pkg/virt-operator/BUILD.bazel
  pkg/virt-operator/application.go
  pkg/virt-operator/util/BUILD.bazel
  pkg/virt-operator/util/config.go
  staging/src/kubevirt.io/client-go/kubecli/BUILD.bazel
  staging/src/kubevirt.io/client-go/kubecli/handler.go
  staging/src/kubevirt.io/client-go/util/BUILD.bazel
  staging/src/kubevirt.io/client-go/util/util.go
Labels: lgtm, release-note-none, size/L

#2638 update OWNERS_ALIASES
  OWNERS_ALIASES
Labels: approved, lgtm, release-note-none, size/XS

#2626 update doc about ssh method usage
  docs/getting-started.md
Labels: approved, lgtm, needs-ok-to-test, release-note-none, size/S

#2617 VM tests with OCS disks
  cluster-up-sha.txt
  cluster-up/cluster/k8s-1.15.1/README.md
  cluster-up/cluster/k8s-1.15.1/provider.sh
  cluster-up/cluster/kind/common.sh
  cluster-up/version.txt
  hack/config-default.sh
  images/cdi-http-import-server/BUILD.bazel
  images/cdi-http-import-server/entrypoint.sh
  pkg/util/types/pvc.go
  pkg/virt-handler/vm.go
  tests/console_test.go
  tests/datavolume_test.go
  tests/migration_test.go
  tests/utils.go
  tests/vm_test.go
Labels: approved, lgtm, release-note, size/XL

#2584 Remove SYS_RESOURCE capability from launcher pod
  cmd/chroot/main.go
  go.mod
  go.sum
  pkg/util/BUILD.bazel
  pkg/util/util.go
  pkg/virt-controller/services/BUILD.bazel
  pkg/virt-controller/services/template.go
  pkg/virt-handler/isolation/BUILD.bazel
  pkg/virt-handler/isolation/generated_mock_isolation.go
  pkg/virt-handler/isolation/isolation.go
  pkg/virt-handler/isolation/isolation_test.go
  pkg/virt-handler/vm.go
  pkg/virt-handler/vm_test.go
  pkg/virt-operator/creation/components/scc.go
  vendor/github.com/mitchellh/go-ps/.gitignore
  vendor/github.com/mitchellh/go-ps/.travis.yml
  vendor/github.com/mitchellh/go-ps/BUILD.bazel
  vendor/github.com/mitchellh/go-ps/LICENSE.md
  vendor/github.com/mitchellh/go-ps/README.md
  vendor/github.com/mitchellh/go-ps/Vagrantfile
  vendor/github.com/mitchellh/go-ps/process.go
  vendor/github.com/mitchellh/go-ps/process_darwin.go
  vendor/github.com/mitchellh/go-ps/process_freebsd.go
  vendor/github.com/mitchellh/go-ps/process_linux.go
  vendor/github.com/mitchellh/go-ps/process_solaris.go
  vendor/github.com/mitchellh/go-ps/process_unix.go
  vendor/github.com/mitchellh/go-ps/process_windows.go
  vendor/modules.txt
Labels: approved, lgtm, release-note, size/XXL

#2642 Link test id to Start VM via CLI test
  tests/windows_test.go
Labels: approved, lgtm, ok-to-test, release-note-none, size/XS
