Repository kubevirt/kubevirt, pull requests merged in 2019-02, with the labels that each got.

#1995 Added test_attributes for vmi_configuration
  tests/vmi_configuration_test.go
Labels: release-note-none, size/M

#1997 [backport] Don't crash on invalid DataVolume URL
  pkg/virt-controller/watch/vm.go
  pkg/virt-controller/watch/vm_test.go
  tests/datavolume_test.go
Labels: release-note-none, size/M

#1972 docs: Add patch level release process
  docs/release.md
Labels: release-note-none, size/M

#1998 Merge pull request #1976 from cynepco3hahue/push_builder_container
  Makefile
  hack/builder/Dockerfile
  hack/builder/build.sh
  hack/builder/entrypoint.sh
  hack/builder/publish.sh
  hack/dockerized
  hack/kubevirt-builder/Dockerfile
  hack/kubevirt-builder/rsyncd.conf
  pkg/api/v1/schema_swagger_generated.go
  pkg/api/v1/schema_test.go
  pkg/api/v1/types_swagger_generated.go
  pkg/controller/expectations_test.go
  pkg/util/openapi/openapi.go
  pkg/virt-controller/services/template_test.go
  pkg/virt-operator/creation/rbac/cluster.go
  tests/vmi_configuration_test.go
Labels: release-note-none, size/L

#1925 Include DNSConfig and DNSPolicy in pod spec.
  api/openapi-spec/swagger.json
  pkg/api/v1/deepcopy_generated.go
  pkg/api/v1/openapi_generated.go
  pkg/api/v1/types.go
  pkg/api/v1/types_swagger_generated.go
  pkg/virt-api/webhooks/validating-webhook/validating-webhook.go
  pkg/virt-api/webhooks/validating-webhook/validating-webhook_test.go
  pkg/virt-controller/services/template.go
  tests/vmi_networking_test.go
Labels: kind/api-change, release-note, size/L

#2003 Double memory and CPU limits
  pkg/container-disk/container-disk.go
  pkg/virt-controller/services/template.go
  pkg/virt-controller/services/template_test.go
  tests/vmi_configuration_test.go
Labels: release-note-none, size/S

#1985 Align libvirt version to 5.0.0
  cmd/virt-launcher/Dockerfile
  glide.lock
  glide.yaml
  vendor/github.com/go-openapi/swag/json.go
  vendor/github.com/go-openapi/swag/post_go19.go
  vendor/github.com/go-openapi/swag/pre_go19.go
  vendor/github.com/go-openapi/swag/util.go
  vendor/github.com/libvirt/libvirt-go/domain.go
  vendor/github.com/libvirt/libvirt-go/domain_compat.h
  vendor/github.com/libvirt/libvirt-go/domain_wrapper.go
  vendor/github.com/libvirt/libvirt-go/domain_wrapper.h
  vendor/github.com/onsi/ginkgo/internal/spec/specs.go
  vendor/github.com/openshift/api/apps/v1/types_swagger_doc_generated.go
  vendor/github.com/openshift/api/authorization/v1/types_swagger_doc_generated.go
  vendor/github.com/openshift/api/build/v1/types_swagger_doc_generated.go
  vendor/github.com/openshift/api/config/v1/generated.pb.go
  vendor/github.com/openshift/api/config/v1/generated.proto
  vendor/github.com/openshift/api/config/v1/types_swagger_doc_generated.go
  vendor/github.com/openshift/api/image/v1/types_swagger_doc_generated.go
  vendor/github.com/openshift/api/network/v1/types_swagger_doc_generated.go
  vendor/github.com/openshift/api/oauth/v1/types_swagger_doc_generated.go
  vendor/github.com/openshift/api/operator/v1alpha1/generated.pb.go
  vendor/github.com/openshift/api/operator/v1alpha1/generated.proto
  vendor/github.com/openshift/api/operator/v1alpha1/types_swagger_doc_generated.go
  vendor/github.com/openshift/api/project/v1/types_swagger_doc_generated.go
  vendor/github.com/openshift/api/quota/v1/types_swagger_doc_generated.go
  vendor/github.com/openshift/api/route/v1/types_swagger_doc_generated.go
  vendor/github.com/openshift/api/security/v1/types_swagger_doc_generated.go
  vendor/github.com/openshift/api/servicecertsigner/v1alpha1/generated.pb.go
  vendor/github.com/openshift/api/servicecertsigner/v1alpha1/generated.proto
  vendor/github.com/openshift/api/servicecertsigner/v1alpha1/types_swagger_doc_generated.go
  vendor/github.com/openshift/api/template/v1/types_swagger_doc_generated.go
  vendor/github.com/openshift/api/user/v1/types_swagger_doc_generated.go
  vendor/github.com/openshift/api/webconsole/v1/generated.pb.go
  vendor/github.com/openshift/api/webconsole/v1/generated.proto
  vendor/github.com/openshift/api/webconsole/v1/types_swagger_doc_generated.go
  vendor/github.com/prometheus/client_model/go.mod
  vendor/github.com/prometheus/client_model/go.sum
  vendor/google.golang.org/appengine/internal/api.go
Labels: release-note, size/XXL

#1999 Minor improvements to architecture documentation
  docs/architecture.md
Labels: release-note-none, size/S

#2000 Fixed "make publish-cache" by ensuring that images were built
  Makefile
Labels: release-note-none, size/XS

#1848 add support for extra DHCP options
  api/openapi-spec/swagger.json
  pkg/api/v1/deepcopy_generated.go
  pkg/api/v1/openapi_generated.go
  pkg/api/v1/schema.go
  pkg/api/v1/schema_swagger_generated.go
  pkg/virt-api/webhooks/validating-webhook/validating-webhook.go
  pkg/virt-api/webhooks/validating-webhook/validating-webhook_test.go
  pkg/virt-launcher/virtwrap/network/dhcp/dhcp.go
  pkg/virt-launcher/virtwrap/network/dhcp/dhcp_test.go
  tests/vmi_networking_test.go
Labels: kind/api-change, release-note, size/L, topic/network

#2004 Fix logic around failed DataVolume retry
  pkg/virt-controller/watch/vm.go
  pkg/virt-controller/watch/vm_test.go
  tests/datavolume_test.go
Labels: release-note, size/M

#2010 Improved test for OpenShift by using the discovery client
  pkg/kubecli/generated_mock_kubevirt.go
  pkg/kubecli/kubecli.go
  pkg/kubecli/kubevirt.go
  pkg/virt-operator/util/client.go
  pkg/virt-operator/util/client_test.go
Labels: release-note-none, size/L

#2009 Improved deploy script
  cluster/deploy.sh
Labels: release-note-none, size/S

#2014 Fix max devices for virt-handler device plugins
  cmd/virt-handler/virt-handler.go
Labels: release-note, size/XS

#1946 Live Migration without tunneling
  api/openapi-spec/swagger.json
  images/cdi-http-import-server/Dockerfile
  images/cdi-http-import-server/entry-point.sh
  pkg/api/v1/deepcopy_generated.go
  pkg/api/v1/types.go
  pkg/api/v1/types_swagger_generated.go
  pkg/virt-controller/watch/migration.go
  pkg/virt-controller/watch/migration_test.go
  pkg/virt-handler/migration-proxy/migration-proxy.go
  pkg/virt-handler/migration-proxy/migration-proxy_test.go
  pkg/virt-handler/vm.go
  pkg/virt-handler/vm_test.go
  pkg/virt-launcher/virtwrap/cli/generated_mock_libvirt.go
  pkg/virt-launcher/virtwrap/cli/libvirt.go
  pkg/virt-launcher/virtwrap/manager.go
  pkg/virt-launcher/virtwrap/manager_test.go
  tests/migration_test.go
  tests/storage_test.go
  tests/utils.go
Labels: kind/api-change, release-note, size/XL

#2005 Tests for invalid MAC
  tests/vmi_multus_test.go
  tests/vmi_networking_test.go
Labels: release-note-none, size/M, topic/network

#2007 Change the network lanes focus and exclude
  automation/test.sh
  tests/utils.go
  tests/vmi_genie_test.go
  tests/vmi_multus_test.go
Labels: release-note, size/M, topic/network

#2018 Minor improvements to getting-started guide
  docs/getting-started.md
Labels: release-note-none, size/XS

#1897 Enable setting serial number for a VM
  api/openapi-spec/swagger.json
  pkg/api/v1/openapi_generated.go
  pkg/api/v1/schema.go
  pkg/api/v1/schema_swagger_generated.go
  pkg/virt-api/webhooks/validating-webhook/validating-webhook.go
  pkg/virt-api/webhooks/validating-webhook/validating-webhook_test.go
  pkg/virt-launcher/virtwrap/api/converter.go
  pkg/virt-launcher/virtwrap/api/converter_test.go
  tests/vmi_configuration_test.go
Labels: kind/api-change, release-note, size/L

#1954 Narrow virt-handler permissions
  manifests/generated/rbac.authorization.k8s.yaml.in
  manifests/generated/virt-handler.yaml.in
  pkg/virt-operator/creation/all.go
  pkg/virt-operator/creation/components/deployments.go
  pkg/virt-operator/creation/rbac/cluster.go
  pkg/virt-operator/creation/rbac/handler.go
  pkg/virt-operator/kubevirt_test.go
  pkg/virt-operator/util/client.go
  tools/resource-generator/resource-generator.go
Labels: kind/api-change, release-note, size/XL

#1981 Bug fix on: virtctl image-upload fails when a trailing slash is added to the upload proxy URL
  pkg/virtctl/imageupload/imageupload.go
  pkg/virtctl/imageupload/imageupload_test.go
Labels: release-note, size/M

#2019 Added a random Go file to project root, for "dep" dependency manager
  doc.go
Labels: release-note-none, size/S

#2022 Use newer gocli which is more robust against pull errors
  cluster/ephemeral-provider-common.sh
Labels: release-note-none, size/XS

#2020 update golang version from 1.11.2 to 1.11.5
  hack/builder/Dockerfile
  hack/kubevirt-builder/Dockerfile
Labels: release-note-none, size/XS

#1840 Vm metrics collector
  cmd/virt-handler/virt-handler.go
  docs/devel/vm-monitoring.md
  pkg/monitoring/vms/prometheus/collector.go
  pkg/monitoring/vms/prometheus/collector_suite_test.go
  pkg/monitoring/vms/prometheus/collector_test.go
  pkg/monitoring/vms/prometheus/prometheus.go
  pkg/monitoring/vms/prometheus/prometheus_test.go
  pkg/virt-handler/cmd-client/client.go
  pkg/virt-handler/cmd-client/generated_mock_client.go
  pkg/virt-launcher/virtwrap/cli/generated_mock_libvirt.go
  pkg/virt-launcher/virtwrap/cli/libvirt.go
  pkg/virt-launcher/virtwrap/cmd-server/server.go
  pkg/virt-launcher/virtwrap/cmd-server/server_test.go
  pkg/virt-launcher/virtwrap/generated_mock_manager.go
  pkg/virt-launcher/virtwrap/manager.go
  pkg/virt-launcher/virtwrap/manager_test.go
  pkg/virt-launcher/virtwrap/stats/types.go
  pkg/virt-launcher/virtwrap/statsconv/converter.go
  pkg/virt-launcher/virtwrap/statsconv/converter_test.go
  pkg/virt-launcher/virtwrap/statsconv/domstats.json
  pkg/virt-launcher/virtwrap/statsconv/domstats_expected.json
  pkg/virt-launcher/virtwrap/statsconv/generated_mock_converter.go
  pkg/virt-launcher/virtwrap/statsconv/stats_suite_test.go
  tests/infra_test.go
Labels: kind/api-change, release-note, size/XXL

#2026 Reintroduce remove-viewer vnc support on windows
  pkg/virtctl/vnc/vnc.go
Labels: do-not-merge/hold, release-note, size/XS

#2006 Autoamted test: Custom MAC on ovs-cni (multus) interface + fixes.
  tests/vmi_multus_test.go
  tests/vmi_networking_test.go
Labels: release-note-none, size/L, topic/network

#1987 add support for tablet device
  api/openapi-spec/swagger.json
  pkg/api/v1/deepcopy_generated.go
  pkg/api/v1/openapi_generated.go
  pkg/api/v1/schema.go
  pkg/api/v1/schema_swagger_generated.go
  pkg/api/v1/schema_test.go
  pkg/virt-api/webhooks/validating-webhook/validating-webhook.go
  pkg/virt-api/webhooks/validating-webhook/validating-webhook_test.go
  pkg/virt-launcher/virtwrap/api/converter.go
  pkg/virt-launcher/virtwrap/api/converter_test.go
  pkg/virt-launcher/virtwrap/api/deepcopy_generated.go
  pkg/virt-launcher/virtwrap/api/defaults.go
  pkg/virt-launcher/virtwrap/api/schema.go
  pkg/virt-launcher/virtwrap/api/schema_test.go
  tests/vmi_configuration_test.go
Labels: kind/api-change, release-note, size/XL

#2030 Automate service expose test
  tests/expose_test.go
Labels: release-note-none, size/L

#2040 Mount .docker directory only when it exists
  hack/dockerized
Labels: release-note-none, size/XS

#2037 Fix swagger spec generation for our subresources
  pkg/virt-api/api.go
  tests/subresource_api_test.go
Labels: release-note-none, size/S

#2041 Revert rename of container disk entrypoint
  cmd/container-disk-v1alpha/BUILD.bazel
  cmd/container-disk-v1alpha/Dockerfile
  cmd/container-disk-v1alpha/entry-point.sh
  pkg/container-disk/container-disk.go
Labels: release-note-none, size/S

#2024 Update k8s-multus and openshift-multus providers
  automation/check-patch.k8s-multus-1.13.3.environment.yaml
  automation/check-patch.k8s-multus-1.13.3.mounts
  automation/check-patch.k8s-multus-1.13.3.packages
  automation/check-patch.k8s-multus-1.13.3.sh
  automation/test.sh
  cluster/k8s-multus-1.13.3/README.md
  cluster/k8s-multus-1.13.3/provider.sh
  cluster/os-3.11.0-multus/provider.sh
  stdci.yaml
Labels: release-note-none, size/S

#2050 Fix race condition when retrieving exit status of virt-launcher
  cmd/virt-launcher/virt-launcher.go
Labels: release-note-none, size/S

#2044 Don't wait for 10 seconds if we can't immediately connect to libvirt
  pkg/virt-launcher/virtwrap/cli/libvirt.go
Labels: do-not-merge/hold, do-not-merge/release-note-label-needed, size/XS

#2035 read node selectors from kubevirt-config configMap
  pkg/virt-controller/services/template.go
  pkg/virt-controller/services/template_test.go
Labels: release-note, size/M

#2051 Fix failing usb function test
  tests/vmi_configuration_test.go
Labels: release-note-none, size/XS

#1978 Support extra CPU flags when starting a VM
  api/openapi-spec/swagger.json
  pkg/api/v1/deepcopy_generated.go
  pkg/api/v1/openapi_generated.go
  pkg/api/v1/schema.go
  pkg/api/v1/schema_swagger_generated.go
  pkg/api/v1/schema_test.go
  pkg/virt-api/webhooks/validating-webhook/validating-webhook.go
  pkg/virt-api/webhooks/validating-webhook/validating-webhook_test.go
  pkg/virt-controller/services/template.go
  pkg/virt-controller/services/template_test.go
  pkg/virt-launcher/virtwrap/api/converter.go
  pkg/virt-launcher/virtwrap/api/converter_test.go
  pkg/virt-launcher/virtwrap/api/deepcopy_generated.go
  pkg/virt-launcher/virtwrap/api/schema.go
  pkg/virt-launcher/virtwrap/api/schema_test.go
  tests/vmi_configuration_test.go
  tests/vmi_lifecycle_test.go
Labels: kind/api-change, release-note, size/XL

#2042 Automate HTTP expose test
  tests/expose_test.go
  tests/utils.go
Labels: release-note-none, size/M

#2055 Fix duplicate check in kubevirt operator controller
  pkg/virt-operator/kubevirt.go
  pkg/virt-operator/kubevirt_test.go
Labels: release-note-none, size/M

#1875 Test attributes for user access tests
  tests/access_test.go
Labels: release-note-none, size/S

#2058 Remove Dockerfiles and all related stuff
  cluster/ephemeral-provider-common.sh
  cmd/container-disk-v1alpha/Dockerfile
  cmd/example-cloudinit-hook-sidecar/Dockerfile
  cmd/example-hook-sidecar/Dockerfile
  cmd/subresource-access-test/Dockerfile
  cmd/virt-api/Dockerfile
  cmd/virt-controller/Dockerfile
  cmd/virt-handler/Dockerfile
  cmd/virt-launcher/Dockerfile
  cmd/virt-operator/Dockerfile
  hack/build-copy-artifacts.sh
  hack/build-docker.sh
  hack/config-default.sh
  images/alpine-container-disk-demo/Dockerfile
  images/cdi-http-import-server/Dockerfile
  images/cirros-container-disk-demo/Dockerfile
  images/disks-images-provider/Dockerfile
  images/fedora-cloud-container-disk-demo/Dockerfile
  images/virtio-container-disk/Dockerfile
  images/vm-killer/Dockerfile
  images/winrmcli/Dockerfile
Labels: release-note-none, size/XL

#2060 increase timeout waiting for virthandler
  tests/vmi_lifecycle_test.go
Labels: release-note-none, size/XS

#2057 reduce image upload memory use
  pkg/virtctl/imageupload/imageupload.go
Labels: release-note-none, size/XS

#1657 Add Ignition Support
  cmd/virt-launcher/BUILD.bazel
  cmd/virt-launcher/virt-launcher.go
  manifests/testing/kubevirt-config.yaml.in
  pkg/api/v1/types.go
  pkg/ignition/BUILD.bazel
  pkg/ignition/ignition.go
  pkg/ignition/ignition_suite_test.go
  pkg/ignition/ignition_test.go
  pkg/virt-api/webhooks/validating-webhook/validating-webhook.go
  pkg/virt-config/feature-gates.go
  pkg/virt-launcher/virtwrap/BUILD.bazel
  pkg/virt-launcher/virtwrap/api/BUILD.bazel
  pkg/virt-launcher/virtwrap/api/converter.go
  pkg/virt-launcher/virtwrap/manager.go
  tests/BUILD.bazel
  tests/vmi_ignition_test.go
Labels: kind/api-change, release-note, size/L

#2061 Fixes flaky vmi lifecycle test
  tests/vmi_lifecycle_test.go
Labels: release-note-none, size/XS

#2033 KubeVirt Updates/Rollbacks Part 1/3 - Install Strategies
  cluster/clean.sh
  pkg/api/v1/types.go
  pkg/controller/BUILD.bazel
  pkg/controller/virtinformers.go
  pkg/virt-operator/BUILD.bazel
  pkg/virt-operator/application.go
  pkg/virt-operator/creation/BUILD.bazel
  pkg/virt-operator/creation/all.go
  pkg/virt-operator/creation/components/crds.go
  pkg/virt-operator/creation/components/deployments.go
  pkg/virt-operator/creation/rbac/apiserver.go
  pkg/virt-operator/creation/rbac/cluster.go
  pkg/virt-operator/creation/rbac/controller.go
  pkg/virt-operator/creation/rbac/handler.go
  pkg/virt-operator/install-strategy/BUILD.bazel
  pkg/virt-operator/install-strategy/install_strategy_suite_test.go
  pkg/virt-operator/install-strategy/strategy.go
  pkg/virt-operator/install-strategy/strategy_test.go
  pkg/virt-operator/kubevirt.go
  pkg/virt-operator/kubevirt_test.go
  pkg/virt-operator/util/types.go
  tests/BUILD.bazel
  tests/operator_test.go
Labels: kind/api-change, release-note, size/XXL
