Repository kubevirt/kubevirt, pull requests merged in 2019-05, with the labels that each got.

#2227 Improve scheduling of libvirt capability test VMIs
  tests/utils.go
  tests/vmi_configuration_test.go
Labels: release-note-none, size/M

#2229 fix migration cancellation that was posted before migration has been started
  pkg/virt-controller/watch/migration.go
  pkg/virt-controller/watch/migration_test.go
  tests/migration_test.go
Labels: release-note-none, size/M

#2234 Use latest requestheader client CA from configMap during TLS andshake
  manifests/generated/rbac-kubevirt.authorization.k8s.yaml.in
  manifests/generated/rbac-operator.authorization.k8s.yaml.in
  pkg/controller/virtinformers.go
  pkg/util/util.go
  pkg/virt-api/BUILD.bazel
  pkg/virt-api/api.go
  pkg/virt-api/api_test.go
  pkg/virt-api/ca-manager.go
  pkg/virt-api/ca-manager_test.go
  pkg/virt-api/filesystem.go
  pkg/virt-api/generated_mock_filesystem.go
  pkg/virt-operator/creation/rbac/apiserver.go
Labels: release-note, size/XL

#2216 Basic secured tls connection for migrations
  cmd/virt-handler/BUILD.bazel
  cmd/virt-handler/virt-handler.go
  manifests/generated/rbac-kubevirt.authorization.k8s.yaml.in
  manifests/generated/rbac-operator.authorization.k8s.yaml.in
  pkg/virt-handler/BUILD.bazel
  pkg/virt-handler/migration-proxy/BUILD.bazel
  pkg/virt-handler/migration-proxy/migration-proxy.go
  pkg/virt-handler/migration-proxy/migration-proxy_test.go
  pkg/virt-handler/vm.go
  pkg/virt-handler/vm_test.go
  pkg/virt-launcher/virtwrap/manager.go
  pkg/virt-operator/creation/rbac/handler.go
  tests/BUILD.bazel
  tests/migration_test.go
  tests/utils.go
Labels: release-note, size/L

#2226 Functional tests verifying VM behavior with deletion --cascade=false
  tests/BUILD.bazel
  tests/datavolume_test.go
  tests/utils.go
Labels: release-note-none, size/L

#2242 Functional tests for enabling/disabling datavolume feature gate
  tests/BUILD.bazel
  tests/datavolume_test.go
  tests/operator_test.go
  tests/utils.go
Labels: release-note-none, size/L

#2238 Fix flaky usb controller test
  tests/vmi_configuration_test.go
Labels: release-note-none, size/XS

#2244 fix virt-launcher panic after migration cancellation on crio
  pkg/virt-launcher/virtwrap/cli/libvirt.go
Labels: release-note-none, size/S

#2239 make all container disks exit after virt-launcher terminates
  cmd/virt-launcher/virt-launcher.go
Labels: release-note-none, size/M

#2246 [Testing] match vm restart tests with polarion
  tests/subresource_api_test.go
Labels: release-note-none, size/XS

#2233 Add missing functional test for VMIs overriding Presets
  tests/vmipreset_test.go
Labels: release-note-none, size/M

#2230 Add okd-4.1.0-rc.0 cluster provider
  automation/test.sh
  cluster/clean.sh
  cluster/deploy.sh
  cluster/ephemeral-provider-common.sh
  cluster/okd-4.1.0-rc.0/README.md
  cluster/okd-4.1.0-rc.0/provider.sh
Labels: release-note, size/L

#2253 [Testing] polarion match for vmi restart tests
  tests/subresource_api_test.go
Labels: release-note-none, size/XS

#2256 Create a fedora 30 container disk
  BUILD.bazel
  WORKSPACE
  cmd/container-disk-v1alpha/BUILD.bazel
Labels: release-note, size/M

#2251 [Testing] polarion match for service account test
  tests/config_test.go
Labels: release-note-none, size/S

#2268 [Testing] improve error handling in operator functional tests
  tests/operator_test.go
Labels: release-note-none, size/M

#2232 [Testing] Add missing test case for VMI Preset lifecycle
  tests/vmipreset_test.go
Labels: release-note-none, size/L

#2266 Add k8s-1.13.3 provider and deprecate k8s-1.10.11 provider
  automation/check-patch.k8s-1.13.3.environment.yaml
  automation/check-patch.k8s-1.13.3.mounts
  automation/check-patch.k8s-1.13.3.packages
  automation/check-patch.k8s-1.13.3.sh
  cluster/clean.sh
  cluster/deploy.sh
  cluster/k8s-1.13.3/README.md
  cluster/k8s-1.13.3/provider.sh
  hack/common.sh
  hack/functests.sh
  stdci.yaml
  tests/migration_test.go
  tests/utils.go
Labels: release-note-none, size/M

#2257 [Testing] add hostdisk test_id
  tests/storage_test.go
Labels: release-note-none, size/XS

#2259 [Testing] Add more tests for ioThreadPolicies
  tests/vmi_iothreads_test.go
Labels: release-note-none, size/L

#2263 [Testing] Add test for multiple vm creation with oc/kubectl
  tests/utils.go
  tests/vm_test.go
Labels: release-note-none, size/M

#2279 [Testing]Add polarion refid for liveness and readiness
  tests/probes_test.go
Labels: release-note-none, size/S

#2274 k8s-multus-1.13.3 image to use cna
  cluster/k8s-multus-1.13.3/provider.sh
Labels: release-note, size/XS

#2261 [Testing] Add missing test for Block MultiQueue
  tests/BUILD.bazel
  tests/vmi_multiqueue_test.go
Labels: release-note-none, size/M

#2283 Update k8s provider default in docs.
  docs/env-providers.md
  docs/getting-started.md
Labels: needs-ok-to-test, release-note-none, size/XS

#2245 Make memory request configurable again
  cmd/virt-handler/virt-handler.go
  pkg/api/v1/defaults.go
  pkg/testutils/BUILD.bazel
  pkg/testutils/matchers.go
  pkg/testutils/mock_config.go
  pkg/virt-api/api.go
  pkg/virt-api/rest/BUILD.bazel
  pkg/virt-api/rest/subresource_test.go
  pkg/virt-api/webhooks/mutating-webhook/BUILD.bazel
  pkg/virt-api/webhooks/mutating-webhook/mutating-webhook.go
  pkg/virt-api/webhooks/mutating-webhook/mutating-webhook_test.go
  pkg/virt-api/webhooks/utils.go
  pkg/virt-api/webhooks/validating-webhook/validating-webhook.go
  pkg/virt-api/webhooks/validating-webhook/validating-webhook_test.go
  pkg/virt-config/BUILD.bazel
  pkg/virt-config/config-map.go
  pkg/virt-config/config_test.go
  pkg/virt-config/feature-gates.go
  pkg/virt-config/virt-properties.go
  pkg/virt-controller/services/BUILD.bazel
  pkg/virt-controller/services/template.go
  pkg/virt-controller/services/template_test.go
  pkg/virt-controller/watch/application.go
  pkg/virt-controller/watch/drain/evacuation/evacuation_test.go
  pkg/virt-controller/watch/migration_test.go
  pkg/virt-controller/watch/vmi.go
  pkg/virt-controller/watch/vmi_test.go
  pkg/virt-handler/vm.go
  pkg/virt-handler/vm_test.go
  pkg/virt-launcher/virtwrap/api/converter_test.go
  tests/storage_test.go
  tools/vms-generator/BUILD.bazel
  tools/vms-generator/vms-generator.go
Labels: kind/api-change, release-note-none, size/XXL

#2285 Replace SCC strategic merge patch with JSON patch.
  pkg/virt-operator/install-strategy/create.go
  pkg/virt-operator/install-strategy/delete.go
  pkg/virt-operator/kubevirt_test.go
Labels: release-note-none, size/M

#2288 [tests] Add test ID for TLS secured migration test
  tests/migration_test.go
Labels: release-note-none, size/XS

#2258 [Testing] Add VMI pod eviction and node drain functional tests
  tests/migration_test.go
  tests/utils.go
Labels: release-note-none, size/L

#2290 [Release-0.17] Replace SCC strategic merge patch with JSON patch.
  pkg/virt-operator/install-strategy/create.go
  pkg/virt-operator/install-strategy/delete.go
  pkg/virt-operator/kubevirt_test.go
Labels: release-note-none, size/M

#2273 [Testing] Test VM creation via command line
  tests/datavolume_test.go
  tests/template_test.go
  tests/utils.go
  tests/vm_test.go
  tests/windows_test.go
Labels: release-note-none, size/L

#2287 Restructure the webhook packages
  pkg/virt-api/webhooks/mutating-webhook/BUILD.bazel
  pkg/virt-api/webhooks/mutating-webhook/mutating-webhook.go
  pkg/virt-api/webhooks/mutating-webhook/mutating-webhook_test.go
  pkg/virt-api/webhooks/mutating-webhook/mutators/BUILD.bazel
  pkg/virt-api/webhooks/mutating-webhook/mutators/migration-create-mutator.go
  pkg/virt-api/webhooks/mutating-webhook/mutators/migration-create-mutator_test.go
  pkg/virt-api/webhooks/mutating-webhook/mutators/mutators_suite_test.go
  pkg/virt-api/webhooks/mutating-webhook/mutators/namespace-limits.go
  pkg/virt-api/webhooks/mutating-webhook/mutators/namespace-limits_test.go
  pkg/virt-api/webhooks/mutating-webhook/mutators/preset.go
  pkg/virt-api/webhooks/mutating-webhook/mutators/preset_test.go
  pkg/virt-api/webhooks/mutating-webhook/mutators/utils.go
  pkg/virt-api/webhooks/mutating-webhook/mutators/vmi-mutator.go
  pkg/virt-api/webhooks/mutating-webhook/mutators/vmi-mutator_test.go
  pkg/virt-api/webhooks/validating-webhook/BUILD.bazel
  pkg/virt-api/webhooks/validating-webhook/admitters/BUILD.bazel
  pkg/virt-api/webhooks/validating-webhook/admitters/admitters_suite_test.go
  pkg/virt-api/webhooks/validating-webhook/admitters/admitters_test.go
  pkg/virt-api/webhooks/validating-webhook/admitters/migration-create-admitter.go
  pkg/virt-api/webhooks/validating-webhook/admitters/migration-create-admitter_test.go
  pkg/virt-api/webhooks/validating-webhook/admitters/migration-update-admitter.go
  pkg/virt-api/webhooks/validating-webhook/admitters/migration-update-admitter_test.go
  pkg/virt-api/webhooks/validating-webhook/admitters/vmi-create-admitter.go
  pkg/virt-api/webhooks/validating-webhook/admitters/vmi-create-admitter_test.go
  pkg/virt-api/webhooks/validating-webhook/admitters/vmi-preset-admitter.go
  pkg/virt-api/webhooks/validating-webhook/admitters/vmi-preset-admitter_test.go
  pkg/virt-api/webhooks/validating-webhook/admitters/vmi-update-admitter.go
  pkg/virt-api/webhooks/validating-webhook/admitters/vmi-update-admitter_test.go
  pkg/virt-api/webhooks/validating-webhook/admitters/vmirs-admitter.go
  pkg/virt-api/webhooks/validating-webhook/admitters/vmirs-admitter_test.go
  pkg/virt-api/webhooks/validating-webhook/admitters/vms-admitter.go
  pkg/virt-api/webhooks/validating-webhook/admitters/vms-admitter_test.go
  pkg/virt-api/webhooks/validating-webhook/validating-webhook.go
  tests/migration_test.go
  tools/vms-generator/BUILD.bazel
  tools/vms-generator/vms-generator.go
Labels: release-note-none, size/XXL

#2247 [Testing] Add test ID's for runStrategy tests
  tests/vm_test.go
Labels: release-note-none, size/M

#2278 [Testing] add test id's for hostDisk and PV initialization tests
  tests/storage_test.go
Labels: release-note-none, size/L

#2291 KubeVirt Update documentation
  docs/updates.md
Labels: release-note-none, size/L

#2315 Fix build errors due to missing RPM packages
  WORKSPACE
Labels: release-note-none, size/S

#2314 docs: remove incorrect suggestion to configure udev rules for sriov vfio
  docs/sriov.md
Labels: release-note, size/S, topic/network

#2319 Log libvirt thread ID
  pkg/log/log.go
  pkg/virt-launcher/virtwrap/util/libvirt_helper_test.go
Labels: release-note-none, size/M

#2306 tests: skip ignition tests if ExperimentalIgnitionSupport is not enabled
  tests/utils.go
  tests/vmi_ignition_test.go
Labels: release-note-none, size/XS

#2299 Fix presetcli
  pkg/kubecli/BUILD.bazel
  pkg/kubecli/generated_mock_kubevirt.go
  pkg/kubecli/kubevirt.go
  pkg/kubecli/kubevirt_test_utils.go
  pkg/kubecli/vmipreset.go
  pkg/kubecli/vmipreset_test.go
Labels: release-note, size/L

#2322 Use Prow env variable to detect if we run under the CI environment
  automation/test.sh
Labels: release-note-none, size/XS

#2281 Openshift 3.11 provider with cluster-network-operator
  cluster/os-3.11.0-multus/provider.sh
Labels: do-not-merge/hold, release-note, size/XS

#2271 Olm improvements
  .travis.yml
  manifests/release/olm/bundle/kubevirt-package.yaml.in
  manifests/release/olm/bundle/kubevirtoperator.vVERSION.clusterserviceversion.yaml.in
  tools/manifest-templator/manifest-templator.go
Labels: release-note-none, size/M

#2301 tests: don't use hardcoded kubevirt namespace
  tests/migration_test.go
  tests/storage_test.go
  tests/vmi_configuration_test.go
  tests/vmi_lifecycle_test.go
Labels: release-note-none, size/M

#2328 Create SECURITY.md
  SECURITY.md
Labels: release-note-none, size/M

#2327 Look for correct package when downloading bundles from Quay
  tools/manifest-templator/manifest-templator.go
  tools/marketplace/helper/bundleHelper.go
  tools/marketplace/main.go
Labels: release-note-none, size/M

#2250 [Testing] Add missing functional test covering matchExpressions of Presets
  tests/vmipreset_test.go
Labels: release-note-none, size/M

#2332 Remove extra err value check
  cmd/virt-handler/virt-handler.go
Labels: ok-to-test, release-note-none, size/XS
