Repository kubevirt/kubevirt, pull requests merged in 2019-06, with the labels that each got.

#2325 Create the ovs br1 on worker nodes for ocp 3.11
  cluster/os-3.11.0-multus/provider.sh
Labels: release-note-none, size/XS, topic/network

#2265 [Testing] Add test to fail when deleting nonexist VM
  tests/vm_test.go
Labels: release-note-none, size/XS

#2337 Pin dependencies to prevent the update
  go.mod
  go.sum
  vendor/github.com/Azure/go-autorest/autorest/adal/config.go
  vendor/github.com/Azure/go-autorest/autorest/adal/token.go
  vendor/github.com/Azure/go-autorest/version/version.go
  vendor/github.com/go-kit/kit/log/README.md
  vendor/kubevirt.io/containerized-data-importer/pkg/apis/core/v1alpha1/types.go
  vendor/modules.txt
Labels: release-note-none, size/M

#2340 Make bazel cache configurable
  automation/test.sh
Labels: release-note-none, size/XS

#2344 Security policy rewording
  SECURITY.md
Labels: release-note-none, size/S

#2342 Fixed Openshift check for tests
  tests/BUILD.bazel
  tests/utils.go
Labels: release-note-none, size/S

#2331 Forward all network traffic in masquerade
  pkg/virt-launcher/virtwrap/network/podinterface.go
  pkg/virt-launcher/virtwrap/network/podinterface_test.go
  tests/vmi_networking_test.go
Labels: release-note, size/M, topic/network

#2341 Fix builder caching under the CI
  hack/build-docker.sh
Labels: release-note-none, size/XS

#2348 Limit bazel to a maximum of 4 parallel jobs
  automation/test.sh
Labels: release-note-none, size/XS

#2302 tests: don't use hardcoded kubevirt namespace (backport for 0.17 series)
  tests/migration_test.go
  tests/storage_test.go
  tests/vmi_configuration_test.go
  tests/vmi_lifecycle_test.go
Labels: release-note-none, size/M

#2280 Add missing functional test for matching multiple VMs via MatchLabel
  tests/vmipreset_test.go
Labels: release-note-none, size/M

#2351 Fix virt-operator condition messaging
  pkg/virt-operator/kubevirt.go
Labels: release-note, size/XS

#2343 Change default interface to masquerade on functional tests
  tests/expose_test.go
  tests/utils.go
  tests/vmi_multus_test.go
  tests/vmi_networking_test.go
  tests/vmi_slirp_interface_test.go
Labels: do-not-merge/hold, release-note-none, size/L, topic/network

#2120 Extend cloud-init interface and support config drive
  api/openapi-spec/swagger.json
  cmd/example-cloudinit-hook-sidecar/BUILD.bazel
  cmd/example-cloudinit-hook-sidecar/cloudinit.go
  pkg/api/v1/deepcopy_generated.go
  pkg/api/v1/openapi_generated.go
  pkg/api/v1/schema.go
  pkg/api/v1/schema_swagger_generated.go
  pkg/cloud-init/BUILD.bazel
  pkg/cloud-init/cloud-init.go
  pkg/cloud-init/cloud-init_test.go
  pkg/hooks/BUILD.bazel
  pkg/hooks/manager.go
  pkg/hooks/v1alpha2/api.pb.go
  pkg/hooks/v1alpha2/api.proto
  pkg/virt-api/webhooks/validating-webhook/admitters/vmi-create-admitter.go
  pkg/virt-handler/BUILD.bazel
  pkg/virt-handler/vm.go
  pkg/virt-launcher/virtwrap/BUILD.bazel
  pkg/virt-launcher/virtwrap/api/converter.go
  pkg/virt-launcher/virtwrap/manager.go
  pkg/virt-launcher/virtwrap/manager_test.go
  tests/utils.go
  tests/vmi_cloudinit_test.go
Labels: kind/api-change, release-note, size/XXL

#2353 Disable ISCSI storage tests for provider v1.13.3
  tests/storage_test.go
Labels: release-note-none, size/XS

#2354 Add utility flags for downstream repo selection
  tests/subresource_api_test.go
  tests/utils.go
  tests/vmi_cloudinit_hook_sidecar_test.go
  tests/vmi_hook_sidecar_test.go
  tests/windows_test.go
Labels: release-note-none, size/S

#2363 Update git ignore file for _ci-configs folder
  .gitignore
Labels: release-note-none, size/XS

#2365 Fix functional test flag parsing
  tests/access_test.go
  tests/config.go
  tests/config_test.go
  tests/console_test.go
  tests/datavolume_test.go
  tests/expose_test.go
  tests/imageupload_test.go
  tests/infra_test.go
  tests/migration_test.go
  tests/networkpolicy_test.go
  tests/operator_test.go
  tests/probes_test.go
  tests/registry_disk_test.go
  tests/replicaset_test.go
  tests/stability_test.go
  tests/storage_test.go
  tests/subresource_api_test.go
  tests/template_test.go
  tests/utils.go
  tests/version_test.go
  tests/vm_test.go
  tests/vmi_cloudinit_hook_sidecar_test.go
  tests/vmi_cloudinit_test.go
  tests/vmi_configuration_test.go
  tests/vmi_genie_test.go
  tests/vmi_hook_sidecar_test.go
  tests/vmi_ignition_test.go
  tests/vmi_iothreads_test.go
  tests/vmi_lifecycle_test.go
  tests/vmi_monitoring_test.go
  tests/vmi_multiqueue_test.go
  tests/vmi_multus_test.go
  tests/vmi_networking_test.go
  tests/vmi_slirp_interface_test.go
  tests/vmidefaults_test.go
  tests/vmipreset_test.go
  tests/vnc_test.go
  tests/windows_test.go
Labels: release-note-none, size/L

#2284 KubeVirt Operator: allow installing in different namespaces
  pkg/virt-api/api.go
  pkg/virt-api/api_test.go
  pkg/virt-operator/application.go
  pkg/virt-operator/install-strategy/BUILD.bazel
  pkg/virt-operator/install-strategy/strategy.go
  pkg/virt-operator/kubevirt.go
  pkg/virt-operator/kubevirt_test.go
  pkg/virt-operator/util/BUILD.bazel
  pkg/virt-operator/util/config.go
  tests/operator_test.go
Labels: release-note, size/L

#2369 Pull in kubevirtci fix for virtctl.sh script
  cluster-up/kubectl.sh
  cluster-up/virtctl.sh
  hack/config-default.sh
Labels: release-note-none, size/XS

#2270 Add Categories `all` to CRDs
  manifests/generated/kv-resource.yaml
  manifests/generated/vm-resource.yaml
  manifests/generated/vmi-resource.yaml
  manifests/generated/vmim-resource.yaml
  manifests/generated/vmipreset-resource.yaml
  manifests/generated/vmirs-resource.yaml
  pkg/virt-operator/creation/components/crds.go
Labels: release-note, size/M

#2364 Port name validation
  pkg/virt-api/webhooks/validating-webhook/admitters/vmi-create-admitter.go
  pkg/virt-api/webhooks/validating-webhook/admitters/vmi-create-admitter_test.go
Labels: ok-to-test, release-note, size/M, topic/network

#2289 [Testing] Add headless VM tests
  tests/BUILD.bazel
  tests/utils.go
  tests/vmi_configuration_test.go
  tests/vmi_headless_test.go
Labels: release-note-none, size/L

#1941 Degrade sriov virt-launcher to unprivileged
  pkg/virt-controller/services/template.go
  pkg/virt-controller/services/template_test.go
Labels: kind/api-change, release-note, size/S, topic/network

#2313 Add a helper tool to register all SR-IOV VFs with vfio
  docs/sriov.md
  tools/util/vfio.sh
Labels: release-note-none, size/S, topic/network

#2355 Removed unused SCC modification for tests
  hack/cluster-clean.sh
  hack/cluster-deploy.sh
  manifests/testing/ocp/ssc-for-ocp.yaml.in
  tests/utils.go
Labels: release-note-none, size/M

#2376 [release-0.17] Removed unused SCC modifications for tests
  cluster/clean.sh
  cluster/deploy.sh
  manifests/testing/ocp/ssc-for-ocp.yaml.in
  tests/utils.go
  vendor/k8s.io/kube-openapi/pkg/handler/BUILD.bazel
Labels: release-note-none, size/M

#2382 Push latest images on make cluster-sync
  cluster-up/cluster/ephemeral-provider-common.sh
  cluster-up/cluster/external/README.md
  cluster-up/cluster/external/provider.sh
  cluster-up/ssh.sh
  hack/cluster-build.sh
  hack/config-default.sh
Labels: release-note-none, size/M

#2383 Add test ids
  tests/windows_test.go
Labels: release-note-none, size/XS

#2371 Added the remaining cpu-pinning tests.
  tests/vmi_configuration_test.go
Labels: release-note-none, size/L

#2387 Fix not working cpu map url
  api/openapi-spec/swagger.json
  pkg/api/v1/openapi_generated.go
  pkg/api/v1/schema.go
  pkg/api/v1/schema_swagger_generated.go
Labels: kind/api-change, release-note-none, size/XS

#2385 Allow setting an imagePullPolicy for containerDisks
  api/openapi-spec/swagger.json
  pkg/api/v1/openapi_generated.go
  pkg/api/v1/schema.go
  pkg/api/v1/schema_swagger_generated.go
  pkg/container-disk/BUILD.bazel
  pkg/container-disk/container-disk.go
  pkg/container-disk/container-disk_test.go
  pkg/virt-api/webhooks/mutating-webhook/mutators/BUILD.bazel
  pkg/virt-api/webhooks/mutating-webhook/mutators/vmi-mutator.go
  pkg/virt-api/webhooks/mutating-webhook/mutators/vmi-mutator_test.go
  tests/registry_disk_test.go
  tests/utils.go
Labels: kind/api-change, release-note, size/L

#2262 hyperv: schema: better docs about parameters
  api/openapi-spec/swagger.json
  pkg/api/v1/openapi_generated.go
  pkg/api/v1/schema.go
  pkg/api/v1/schema_swagger_generated.go
Labels: kind/api-change, release-note-none, size/M

#2384 KubeVirt CR's imagePullPolicy is not respected
  pkg/virt-operator/install-strategy/strategy.go
  pkg/virt-operator/kubevirt.go
  pkg/virt-operator/kubevirt_test.go
  pkg/virt-operator/util/config.go
Labels: release-note, size/S

#2391 Fixed RBAC for non admin users
  manifests/generated/rbac-cluster.authorization.k8s.yaml.in
  manifests/generated/rbac-operator.authorization.k8s.yaml.in
  pkg/virt-api/rest/authorizer.go
  pkg/virt-api/rest/authorizer_test.go
  pkg/virt-operator/creation/rbac/cluster.go
  tests/BUILD.bazel
  tests/access_test.go
Labels: release-note, size/L

#2375 Add regression test for wrong pci address in VM
  tests/vmi_configuration_test.go
Labels: release-note-none, size/S

#2349 Rewording of security policy to be community orientated
  SECURITY.md
Labels: needs-ok-to-test, release-note, size/M

#2388 prometheus: metrics: add VMI info to labels
  cmd/virt-handler/virt-handler.go
  pkg/monitoring/vms/prometheus/BUILD.bazel
  pkg/monitoring/vms/prometheus/collector.go
  pkg/monitoring/vms/prometheus/collector_test.go
  pkg/monitoring/vms/prometheus/prometheus.go
  pkg/monitoring/vms/prometheus/prometheus_suite_test.go
  pkg/monitoring/vms/prometheus/prometheus_test.go
  pkg/util/lookup/BUILD.bazel
  pkg/util/lookup/lookup.go
  pkg/virt-controller/watch/BUILD.bazel
  pkg/virt-controller/watch/node.go
  tests/infra_test.go
Labels: release-note, size/L

#2304 Replace default requested memory with cluster overcommit ratio
  pkg/api/v1/BUILD.bazel
  pkg/api/v1/schema.go
  pkg/api/v1/types.go
  pkg/api/v1/types_test.go
  pkg/api/v1/utils.go
  pkg/virt-api/webhooks/mutating-webhook/mutators/BUILD.bazel
  pkg/virt-api/webhooks/mutating-webhook/mutators/vmi-mutator.go
  pkg/virt-api/webhooks/mutating-webhook/mutators/vmi-mutator_test.go
  pkg/virt-api/webhooks/validating-webhook/admitters/vmi-create-admitter_test.go
  pkg/virt-config/config-map.go
  pkg/virt-config/config_test.go
  pkg/virt-launcher/virtwrap/api/converter.go
  pkg/virt-launcher/virtwrap/manager_test.go
  pkg/virt-launcher/virtwrap/network/BUILD.bazel
  pkg/virt-launcher/virtwrap/network/podinterface_test.go
  tests/migration_test.go
  tests/utils.go
  tests/vmi_configuration_test.go
  tests/vmidefaults_test.go
Labels: kind/api-change, release-note, size/L

#2293 [Testing] add test 'check guest memory different from requested memory'
  tests/vmi_configuration_test.go
Labels: release-note-none, size/M

#2398 Push updated images to all nodes
  hack/cluster-build.sh
Labels: release-note-none, size/XS

#2403 Use sriov network multus name from HCO for VMI example
  examples/vmi-sriov.yaml
  tools/vms-generator/utils/utils.go
Labels: release-note-none, size/XS

#2390 [Testing] polarion id for block pvc test
  tests/storage_test.go
Labels: release-note-none, size/XS

#2347 tests: make sriov suite work with mellanox cards
  tests/migration_test.go
  tests/utils.go
  tests/vmi_multus_test.go
Labels: release-note-none, size/L, topic/network

#2399 Improve logging of memory-request being set according to cluster memory-overcommit
  pkg/virt-api/webhooks/mutating-webhook/mutators/vmi-mutator.go
Labels: kind/api-change, release-note-none, size/XS

#2409 replace Equal(true/false) with BeTrue/BeFalse
  pkg/cloud-init/cloud-init_test.go
  pkg/hooks/hooks_test.go
  pkg/inotify-informer/inotify_test.go
  pkg/util/types/pvc_test.go
  pkg/virt-api/api_test.go
  pkg/virt-api/rest/authorizer_test.go
  pkg/virt-api/webhooks/mutating-webhook/mutators/migration-create-mutator_test.go
  pkg/virt-api/webhooks/mutating-webhook/mutators/vmi-mutator_test.go
  pkg/virt-api/webhooks/validating-webhook/admitters/migration-create-admitter_test.go
  pkg/virt-api/webhooks/validating-webhook/admitters/migration-update-admitter_test.go
  pkg/virt-api/webhooks/validating-webhook/admitters/vmi-create-admitter_test.go
  pkg/virt-api/webhooks/validating-webhook/admitters/vmi-preset-admitter_test.go
  pkg/virt-api/webhooks/validating-webhook/admitters/vmi-update-admitter_test.go
  pkg/virt-api/webhooks/validating-webhook/admitters/vmirs-admitter_test.go
  pkg/virt-api/webhooks/validating-webhook/admitters/vms-admitter_test.go
  pkg/virt-config/config_test.go
  pkg/virt-controller/services/template_test.go
  pkg/virt-handler/cache/cache_test.go
  pkg/virt-launcher/monitor_test.go
  pkg/virt-launcher/notify-client/notify_test.go
  pkg/virt-launcher/virtwrap/api/converter_test.go
  pkg/virt-launcher/virtwrap/cmd-server/server_test.go
  pkg/virt-launcher/virtwrap/network/common_test.go
  pkg/virt-operator/install-strategy/strategy_test.go
  pkg/watchdog/watchdog_test.go
  staging/src/kubevirt.io/client-go/api/v1/defaults_test.go
  tests/migration_test.go
  tests/replicaset_test.go
  tests/storage_test.go
  tests/vmi_lifecycle_test.go
  tests/vmipreset_test.go
Labels: release-note-none, size/L

#2411 Handled the case of external provider in cluster build
  hack/cluster-build.sh
Labels: release-note-none, size/XS

#2413 Increase test timeout for the whole test suite
  hack/functests.sh
Labels: release-note-none, size/XS

#2415 Run make target under the travis
  .travis.yml
  Makefile
  hack/version.sh
Labels: release-note-none, size/XS

#2414 Fix openapi generation
  hack/build-go.sh
  pkg/virt-handler/device-manager/BUILD.bazel
  staging/src/kubevirt.io/client-go/api/v1/openapi_generated.go
  staging/src/kubevirt.io/client-go/api/v1/schema.go
  staging/src/kubevirt.io/client-go/api/v1/types.go
Labels: kind/api-change, release-note-none, size/XL

#2416 Fix documentation of OvercommitGuestOverhead
  api/openapi-spec/swagger.json
  pkg/virt-controller/services/template.go
  staging/src/kubevirt.io/client-go/api/v1/openapi_generated.go
  staging/src/kubevirt.io/client-go/api/v1/schema.go
  staging/src/kubevirt.io/client-go/api/v1/schema_swagger_generated.go
Labels: kind/api-change, release-note-none, size/S

#2418 Rearrange make targets and hack scripts
  .travis.yml
  Makefile
  automation/test.sh
  hack/build-docker.sh
  hack/build-func-tests-container.sh
  hack/build-verify.sh
  hack/builder-cache.sh
  hack/common.sh
  hack/func-tests-image.sh
Labels: release-note-none, size/L

#2422 Rename functest-build-image to functest-image-build
  Makefile
Labels: release-note-none, size/XS

#2420 Fix expectations in disruptionbudget controller
  pkg/virt-controller/watch/drain/disruptionbudget/disruptionbudget.go
  pkg/virt-controller/watch/drain/disruptionbudget/disruptionbudget_test.go
  pkg/virt-controller/watch/vm.go
  tests/migration_test.go
Labels: release-note-none, size/M

#2381 Ensure that QOS class guaranteed is indeed supported like documented
  api/openapi-spec/swagger.json
  pkg/container-disk/BUILD.bazel
  pkg/container-disk/container-disk.go
  pkg/container-disk/container-disk_test.go
  pkg/virt-api/webhooks/mutating-webhook/mutators/vmi-mutator.go
  pkg/virt-api/webhooks/mutating-webhook/mutators/vmi-mutator_test.go
  pkg/virt-api/webhooks/utils.go
  pkg/virt-controller/services/template.go
  pkg/virt-controller/watch/vmi.go
  pkg/virt-controller/watch/vmi_test.go
  staging/src/kubevirt.io/client-go/api/v1/BUILD.bazel
  staging/src/kubevirt.io/client-go/api/v1/deepcopy_generated.go
  staging/src/kubevirt.io/client-go/api/v1/openapi_generated.go
  staging/src/kubevirt.io/client-go/api/v1/types.go
  staging/src/kubevirt.io/client-go/api/v1/types_swagger_generated.go
  staging/src/kubevirt.io/client-go/api/v1/types_test.go
  tests/vmi_configuration_test.go
Labels: kind/api-change, kind/bug, release-note, size/L

#2424 Remove unused dead code from virt-operator
  pkg/virt-operator/creation/components/BUILD.bazel
  pkg/virt-operator/creation/components/crds.go
  pkg/virt-operator/creation/components/deployments.go
  pkg/virt-operator/creation/rbac/BUILD.bazel
  pkg/virt-operator/creation/rbac/apiserver.go
  pkg/virt-operator/creation/rbac/cluster.go
  pkg/virt-operator/creation/rbac/controller.go
  pkg/virt-operator/creation/rbac/handler.go
Labels: release-note-none, size/L

#2421 Make secret lookup of virt-handler and virt-api more robust
  cmd/virt-handler/virt-handler.go
  pkg/virt-api/api.go
  pkg/virt-api/api_test.go
Labels: release-note-none, size/L

#2426 Fix name of build functest image function
  hack/builder-cache.sh
  hack/common.sh
Labels: release-note-none, size/XS

#2316 Move SR-IOV functional tests into a separate suite
  automation/test.sh
  tests/utils.go
  tests/vmi_multus_test.go
Labels: release-note-none, size/L, topic/network

#2407 [Testing] add polarion id for non-existent pvc test
  tests/storage_test.go
Labels: release-note-none, size/XS

#2412 [Test] Adding OverCommit VM memory tests
  tests/vmi_configuration_test.go
Labels: release-note, size/M

#2432 prometheus: network: report packets and error
  pkg/monitoring/vms/prometheus/prometheus.go
  tests/infra_test.go
Labels: release-note-none, size/L

#2405 Don't allow live migration with a bridge interface
  pkg/virt-api/webhooks/mutating-webhook/mutators/vmi-mutator.go
  pkg/virt-api/webhooks/mutating-webhook/mutators/vmi-mutator_test.go
  pkg/virt-api/webhooks/validating-webhook/admitters/vmi-create-admitter.go
  pkg/virt-api/webhooks/validating-webhook/admitters/vmi-create-admitter_test.go
  pkg/virt-config/BUILD.bazel
  pkg/virt-config/config-map.go
  pkg/virt-config/config_test.go
  pkg/virt-handler/vm.go
  pkg/virt-launcher/virtwrap/api/converter_test.go
  pkg/virt-launcher/virtwrap/network/network_test.go
  pkg/virt-launcher/virtwrap/network/podinterface_test.go
  staging/src/kubevirt.io/client-go/api/v1/defaults.go
  staging/src/kubevirt.io/client-go/api/v1/defaults_test.go
  staging/src/kubevirt.io/client-go/api/v1/types.go
  tests/migration_test.go
  tests/utils.go
  tests/vmi_networking_test.go
  tests/vmi_slirp_interface_test.go
  tools/vms-generator/utils/utils.go
  tools/vms-generator/vms-generator.go
Labels: kind/api-change, release-note-none, size/L, topic/network

#2435 Remove duplicate code to delete/create socketPath in virt-launcher
  cmd/virt-launcher/virt-launcher.go
  pkg/util/net/grpc/grpc.go
Labels: ok-to-test, release-note-none, size/S

#2260 [Testing] Add functional test for live migration with NFS storage
  BUILD.bazel
  WORKSPACE
  hack/config-default.sh
  images/disks-images-provider/BUILD.bazel
  images/disks-images-provider/entrypoint.sh
  images/nfs-server/BUILD.bazel
  manifests/testing/disks-images-provider.yaml.in
  pkg/virt-api/rest/subresource.go
  pkg/virt-launcher/virtwrap/util/libvirt_helper.go
  tests/migration_test.go
  tests/utils.go
Labels: do-not-merge/hold, release-note-none, size/L
