Repository kubevirt/kubevirt, pull requests merged in 2019-03, with the labels that each got.

#2065 Fix the issues with 1.10 provider
  automation/check-patch.os-3.11.0-crio.environment.yaml
  automation/check-patch.os-3.11.0-crio.mounts
  automation/check-patch.os-3.11.0-crio.packages
  automation/check-patch.os-3.11.0-crio.sh
  automation/check-patch.os-3.11.0-multus.environment.yaml
  automation/check-patch.os-3.11.0-multus.mounts
  automation/check-patch.os-3.11.0-multus.packages
  automation/check-patch.os-3.11.0-multus.sh
  automation/check-patch.os-3.11.0.environment.yaml
  automation/check-patch.os-3.11.0.mounts
  automation/check-patch.os-3.11.0.packages
  automation/check-patch.os-3.11.0.sh
  automation/test.sh
  cluster/deploy.sh
  cluster/ephemeral-provider-common.sh
  stdci.yaml
Labels: release-note-none, size/M

#2067 Bring cirros images to the sandbox where the test runs
  .gitignore
  .travis.yml
  Makefile
  hack/dockerized
  pkg/virtctl/imageupload/BUILD.bazel
  pkg/virtctl/imageupload/imageupload_test.go
Labels: release-note-none, size/M

#2054 don't depend on hard-coded names for node
  tests/utils.go
  tests/vmi_configuration_test.go
Labels: release-note-none, size/M

#2075 increase timeout waiting for virthandler
  tests/vmi_lifecycle_test.go
Labels: do-not-merge/hold, release-note-none, size/XS

#2066 Update virt-win iso to latest
  WORKSPACE
Labels: release-note-none, size/XS

#1845 Live migration tracking
  api/openapi-spec/swagger.json
  pkg/api/v1/deepcopy_generated.go
  pkg/api/v1/openapi_generated.go
  pkg/api/v1/types.go
  pkg/api/v1/types_swagger_generated.go
  pkg/virt-controller/watch/migration.go
  pkg/virt-controller/watch/migration_test.go
  pkg/virt-launcher/virtwrap/BUILD.bazel
  pkg/virt-launcher/virtwrap/cli/generated_mock_libvirt.go
  pkg/virt-launcher/virtwrap/cli/libvirt.go
  pkg/virt-launcher/virtwrap/manager.go
  pkg/virt-launcher/virtwrap/manager_test.go
  tests/migration_test.go
Labels: kind/api-change, release-note-none, size/L

#2028 add default cluster cpu model
  pkg/virt-api/api.go
  pkg/virt-api/webhooks/mutating-webhook/BUILD.bazel
  pkg/virt-api/webhooks/mutating-webhook/mutating-webhook.go
  pkg/virt-api/webhooks/mutating-webhook/mutating-webhook_test.go
  pkg/virt-api/webhooks/mutating-webhook/preset.go
  pkg/virt-api/webhooks/mutating-webhook/preset_test.go
  pkg/virt-api/webhooks/utils.go
  tests/vmi_lifecycle_test.go
Labels: release-note, size/L

#2073 Reject migration of VMIs with non-migratable condition
  pkg/virt-api/webhooks/validating-webhook/validating-webhook.go
  pkg/virt-api/webhooks/validating-webhook/validating-webhook_test.go
  tests/migration_test.go
  tests/utils.go
Labels: release-note-none, size/M

#2074 Merge pull request #2054 from tareqalayan/fix-issue-2048
  tests/utils.go
  tests/vmi_configuration_test.go
Labels: release-note-none, size/M

#2078 Added more test attributes to expose_test.go, vmi_mulutus_test.go, vmi_networking_test.go
  tests/expose_test.go
  tests/vmi_multus_test.go
  tests/vmi_networking_test.go
Labels: release-note-none, size/XL, topic/network

#2081 Backport: Fixed "make publish-cache" by ensuring that images were built
  Makefile
Labels: do-not-merge/hold, release-note-none, size/XS

#2088 Fix build on platforms with bash not under /bin/
  cluster/build.sh
  cluster/clean.sh
  cluster/cli.sh
  cluster/deploy.sh
  cluster/down.sh
  cluster/ephemeral-provider-common.sh
  cluster/external/provider.sh
  cluster/k8s-1.10.11/provider.sh
  cluster/k8s-1.11.0/provider.sh
  cluster/k8s-genie-1.11.1/provider.sh
  cluster/k8s-multus-1.13.3/provider.sh
  cluster/kubectl.sh
  cluster/local/provider.sh
  cluster/os-3.11.0-crio/provider.sh
  cluster/os-3.11.0-multus/provider.sh
  cluster/os-3.11.0/provider.sh
  cluster/up.sh
  cluster/virtctl.sh
  hack/bazel-generate.sh
  hack/bootstrap-ginkgo.sh
  hack/build-copy-artifacts.sh
  hack/build-docker.sh
  hack/build-func-tests-container.sh
  hack/build-func-tests.sh
  hack/build-go.sh
  hack/build-manifests.sh
  hack/builder/build.sh
  hack/builder/entrypoint.sh
  hack/builder/publish.sh
  hack/check.sh
  hack/common.sh
  hack/coverage.sh
  hack/dep-prune.sh
  hack/dockerized
  hack/functests.sh
  hack/gen-swagger-doc/gen-swagger-docs.sh
  hack/generate.sh
  hack/goveralls.sh
  hack/verify-build.sh
  hack/version.sh
Labels: release-note-none, size/M

#2063 Print MAC and IP at DHCP server start
  pkg/virt-launcher/virtwrap/network/common.go
  pkg/virt-launcher/virtwrap/network/generated_mock_network.go
  pkg/virt-launcher/virtwrap/network/network.go
  pkg/virt-launcher/virtwrap/network/network_test.go
  pkg/virt-launcher/virtwrap/network/podinterface.go
  pkg/virt-launcher/virtwrap/network/podinterface_test.go
Labels: release-note-none, size/M

#2094 tests: replace remaining occurrence of "local" by StorageClassLocal
  tests/imageupload_test.go
  tests/utils.go
Labels: release-note-none, size/XS

#2080 Fix some inconsistencies introduces with the bazel switch
  .gitignore
  .travis.yml
  Makefile
  WORKSPACE
  cluster/ephemeral-provider-common.sh
  cluster/external/provider.sh
  hack/bazel-push-images.sh
Labels: release-note-none, size/M

#2099 Run bazel build server always in the background
  automation/test.sh
  cluster/ephemeral-provider-common.sh
  hack/bazel-server.sh
  hack/dockerized
Labels: release-note-none, size/S

#2071 KubeVirt Updates/Rollbacks Part 2/3 - Decouple Version and Registry Options
  Makefile
  cluster/ephemeral-provider-common.sh
  hack/bazel-push-images.sh
  hack/config-default.sh
  hack/config.sh
  hack/functests.sh
  pkg/api/v1/openapi_generated.go
  pkg/api/v1/types.go
  pkg/api/v1/types_swagger_generated.go
  pkg/controller/virtinformers.go
  pkg/virt-operator/BUILD.bazel
  pkg/virt-operator/creation/BUILD.bazel
  pkg/virt-operator/creation/all.go
  pkg/virt-operator/deletion/BUILD.bazel
  pkg/virt-operator/deletion/all.go
  pkg/virt-operator/install-strategy/BUILD.bazel
  pkg/virt-operator/install-strategy/strategy.go
  pkg/virt-operator/install-strategy/strategy_test.go
  pkg/virt-operator/kubevirt.go
  pkg/virt-operator/kubevirt_test.go
  pkg/virt-operator/util/client.go
  tests/operator_test.go
  tests/utils.go
Labels: kind/api-change, release-note, size/XXL

#2112 Fix virtio hash in WORKSPACE
  WORKSPACE
Labels: release-note-none, size/XS

#2111 Fix some bazel targets and travis push
  Makefile
  hack/dockerized
Labels: release-note-none, size/S

#2105 lookup libvirt version in the all content of log file
  tests/vmi_lifecycle_test.go
Labels: release-note-none, size/XS

#2117 Updated libstdc++ version
  WORKSPACE
Labels: release-note-none, size/XS

#2121 Fix and addition to service expose test.
  tests/expose_test.go
Labels: do-not-merge/release-note-label-needed, size/S

#2119 provider.sh: Call prepare_config in the build funtion.
  cluster/external/provider.sh
Labels: release-note-none, size/XS

#2101 Improve developer experience with bazel
  .travis.yml
  BUILD.bazel
  Makefile
  WORKSPACE
  cluster/ephemeral-provider-common.sh
  cluster/external/provider.sh
  cluster/virtctl.sh
  cmd/virt-operator/virt-operator.go
  docs/getting-started.md
  hack/bazel-build.sh
  hack/bazel-fmt.sh
  hack/bazel-generate.sh
  hack/check.sh
  hack/generate.sh
  nogo_config.json
  pkg/api/v1/types.go
  pkg/hooks/info/api.pb.go
  pkg/hooks/info/info.go
  pkg/hooks/v1alpha1/api.pb.go
  pkg/hooks/v1alpha1/v1alpha1.go
  pkg/hooks/v1alpha2/api.pb.go
  pkg/hooks/v1alpha2/v1alpha2.go
  pkg/ignition/ignition.go
  pkg/kubecli/kubevirt.go
  pkg/kubecli/kv.go
  pkg/kubecli/replicaset.go
  pkg/kubecli/replicaset_test.go
  pkg/util/openapi/openapi.go
  pkg/virt-controller/services/template.go
  pkg/virt-controller/services/template_test.go
  pkg/virt-controller/watch/replicaset_test.go
  pkg/virt-controller/watch/vm_test.go
  pkg/virt-controller/watch/vmi.go
  pkg/virt-operator/application.go
  pkg/virt-operator/install-strategy/strategy.go
  pkg/virt-operator/kubevirt.go
  pkg/virt-operator/kubevirt_test.go
  pkg/virt-operator/util/client_test.go
  pkg/virtctl/imageupload/imageupload_test.go
  tests/replicaset_test.go
  tests/vmi_networking_test.go
  tools/resource-generator/resource-generator.go
  tools/util/marshaller.go
  tools/util/marshaller_test.go
Labels: kind/api-change, release-note-none, size/XL

#2116 tests: read parameters from a config file
  tests/BUILD.bazel
  tests/config.go
  tests/default-config.json
  tests/imageupload_test.go
  tests/utils.go
Labels: release-note, size/L

#2122 update k8s 1.13.3 multus image to fix ovs image pull error
  cluster/k8s-multus-1.13.3/provider.sh
Labels: release-note-none, size/XS

#2123 get logs for cdi pods on functional test failure
  tests/utils.go
Labels: release-note-none, size/XS

#2128 Ensure consistent test package imports
  pkg/config/config_suite_test.go
  pkg/controller/controller_suite_test.go
  pkg/emptydisk/emptydisk_suite_test.go
  pkg/host-disk/host_disk_suite_test.go
  pkg/log/log_suite_test.go
  pkg/monitoring/vms/prometheus/collector_suite_test.go
  pkg/util/net/dns/dns_suite_test.go
  pkg/virt-api/rest/rest_suite_test.go
  pkg/virt-api/webhooks/mutating-webhook/mutating-webhook_suite_test.go
  pkg/virt-api/webhooks/validating-webhook/validating-webhook_suite_test.go
  pkg/virt-controller/services/services_suite_test.go
  pkg/virt-launcher/BUILD.bazel
  pkg/virt-launcher/monitor_test.go
  pkg/virt-launcher/notify-client/client_suite_test.go
  pkg/virt-launcher/virt_launcher_suite_test.go
  pkg/virt-launcher/virtwrap/agent-poller/agent_poller_suite_test.go
  pkg/virt-launcher/virtwrap/cmd-server/cmd_server_suite_test.go
  pkg/virt-launcher/virtwrap/network/dhcp/dhcp_suite_test.go
  pkg/virt-launcher/virtwrap/network/network_suite_test.go
  pkg/virt-launcher/virtwrap/statsconv/BUILD.bazel
  pkg/virt-launcher/virtwrap/statsconv/stats_suite_test.go
  pkg/virt-operator/install-strategy/install_strategy_suite_test.go
  pkg/virt-operator/util/util_suite_test.go
  pkg/virt-operator/virt_operator_suite_test.go
Labels: release-note-none, size/M

#2130 Switch back to go based unit test runs
  Makefile
Labels: release-note-none, size/XS

#2068 Fix various things in the device plugin manager
  pkg/virt-handler/device-manager/device_controller.go
  pkg/virt-handler/device-manager/device_controller_test.go
  pkg/virt-handler/device-manager/generic_device.go
  pkg/virt-handler/device-manager/generic_device_test.go
  tests/BUILD.bazel
  tests/utils.go
  tests/vmi_lifecycle_test.go
Labels: release-note, size/L

#2131 Update goimports bazel dependency, so that `local` is taken into account
  Makefile
  WORKSPACE
  hack/generate.sh
  tests/vmi_lifecycle_test.go
Labels: release-note-none, size/S

#2133 Fix device manager test race
  pkg/virt-handler/device-manager/device_controller_test.go
Labels: release-note-none, size/S

#2047 Add annotaion to the virt-launcher template for istio
  cluster/k8s-multus-1.13.3/provider.sh
  pkg/virt-controller/services/template.go
  pkg/virt-controller/services/template_test.go
  pkg/virt-controller/watch/vmi.go
  pkg/virt-controller/watch/vmi_test.go
Labels: release-note, size/M, topic/network

#2134 fix multus duplicate ip allocation
  cluster/k8s-multus-1.13.3/provider.sh
Labels: release-note-none, size/XS, topic/network

#2141 change the location of error log.
  pkg/virt-launcher/virtwrap/network/common.go
Labels: release-note-none, size/XS

#2140 Make sure nodes to launch VMI are schedulable on any infra setup
  tests/vmi_lifecycle_test.go
Labels: release-note, size/S

#2115 Propagate MAC address to multus via annotations
  pkg/virt-controller/services/template.go
  pkg/virt-controller/services/template_test.go
  pkg/virt-launcher/virtwrap/network/common.go
  tests/vmi_multus_test.go
Labels: release-note, size/L, topic/network

#2146 tests: use GetAllSchedulableNodes() function where possible
  tests/migration_test.go
  tests/utils.go
  tests/vmi_lifecycle_test.go
Labels: release-note-none, size/S

#2059 Cancel live migration
  api/openapi-spec/swagger.json
  pkg/api/v1/deepcopy_generated.go
  pkg/api/v1/openapi_generated.go
  pkg/api/v1/types.go
  pkg/api/v1/types_swagger_generated.go
  pkg/controller/conditions.go
  pkg/virt-api/api.go
  pkg/virt-api/webhooks/mutating-webhook/mutating-webhook.go
  pkg/virt-api/webhooks/mutating-webhook/mutating-webhook_test.go
  pkg/virt-controller/watch/migration.go
  pkg/virt-controller/watch/migration_test.go
  pkg/virt-controller/watch/vmi.go
  pkg/virt-handler/cmd-client/client.go
  pkg/virt-handler/cmd-client/generated_mock_client.go
  pkg/virt-handler/vm.go
  pkg/virt-handler/vm_test.go
  pkg/virt-launcher/virtwrap/api/schema.go
  pkg/virt-launcher/virtwrap/cmd-server/server.go
  pkg/virt-launcher/virtwrap/errors/errors.go
  pkg/virt-launcher/virtwrap/generated_mock_manager.go
  pkg/virt-launcher/virtwrap/manager.go
  pkg/virt-launcher/virtwrap/manager_test.go
  tests/migration_test.go
  tests/utils.go
Labels: kind/api-change, release-note, size/XL

#2149 Add getting-started documentation for macOS
  docs/getting-started.md
Labels: release-note-none, size/S

#1924 Support setting Multus default network via annotations.
  api/openapi-spec/swagger.json
  pkg/api/v1/deepcopy_generated.go
  pkg/api/v1/openapi_generated.go
  pkg/api/v1/schema.go
  pkg/api/v1/schema_swagger_generated.go
  pkg/virt-api/webhooks/validating-webhook/validating-webhook.go
  pkg/virt-api/webhooks/validating-webhook/validating-webhook_test.go
  pkg/virt-controller/services/template.go
  pkg/virt-controller/services/template_test.go
  pkg/virt-controller/watch/vmi_test.go
  pkg/virt-handler/vm_test.go
  pkg/virt-launcher/virtwrap/api/converter.go
  pkg/virt-launcher/virtwrap/api/converter_test.go
  pkg/virt-launcher/virtwrap/network/network.go
  pkg/virt-launcher/virtwrap/network/network_test.go
  tests/vmi_genie_test.go
  tests/vmi_multus_test.go
  tools/vms-generator/utils/utils.go
Labels: kind/api-change, release-note-action-required, size/XL, topic/network

#2153 tests: skip migration tests if LiveMigration is not enabled
  tests/migration_test.go
  tests/utils.go
Labels: release-note-none, size/S

#2077 metrics: prometheus: more storage metrics
  pkg/monitoring/vms/prometheus/prometheus.go
  tests/infra_test.go
  tests/utils.go
Labels: release-note-none, size/L

#2069 Fix version clash in sidecar manager
  cmd/example-hook-sidecar/BUILD.bazel
  cmd/example-hook-sidecar/smbios.go
  pkg/hooks/hooks.go
  pkg/hooks/manager.go
  pkg/virt-controller/services/template.go
  tests/BUILD.bazel
  tests/vmi_hook_sidecar_test.go
Labels: release-note-none, size/L

#2148 Deduplicate bazel hack scripts
  hack/bazel-build-images.sh
  hack/bazel-push-images.sh
Labels: release-note-none, size/S
