Repository kubevirt/kubevirt, pull requests merged in 2019-11, with the labels that each got.

#2821 Bump go-yaml version to cover fixed ddos heuristic
  go.mod
  go.sum
  staging/src/kubevirt.io/client-go/go.mod
  staging/src/kubevirt.io/client-go/go.sum
  vendor/gopkg.in/yaml.v2/decode.go
  vendor/gopkg.in/yaml.v2/resolve.go
  vendor/gopkg.in/yaml.v2/scannerc.go
  vendor/modules.txt
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M

#2814 [release-0.20] tests: bump default CPU to Nehalem
  tests/vmi_lifecycle_test.go
Labels: dco-signoff: yes, release-note-none, size/XS

#2850 Operator test: add test ids
  tests/operator_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M

#2851 vmi configuration: add test ids
  tests/vmi_configuration_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M

#2852 Storage add test ids
  tests/storage_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M

#2853 IOthreads test:Add test ids
  tests/vmi_iothreads_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#2854 vmi hook sidecar test: add test ids
  tests/vmi_hook_sidecar_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#2857 Window vm: add test ids
  tests/windows_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/S

#2858 vm test and cloudInit sidecar hooks: add test ids
  tests/vm_test.go
  tests/vmi_cloudinit_hook_sidecar_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/S

#2859 Subresource test: add test ids
  tests/subresource_api_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/S

#2860 CloudInit userData: add test ids
  tests/vmi_cloudinit_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/S

#2578 Clean up and fix types.go
  api/openapi-spec/swagger.json
  staging/src/kubevirt.io/client-go/api/v1/BUILD.bazel
  staging/src/kubevirt.io/client-go/api/v1/openapi_generated.go
  staging/src/kubevirt.io/client-go/api/v1/register.go
  staging/src/kubevirt.io/client-go/api/v1/types.go
  staging/src/kubevirt.io/client-go/api/v1/types_swagger_generated.go
Labels: approved, dco-signoff: yes, kind/api-change, lgtm, release-note-none, size/L

#2866 bump to latest kubevirtci
  cluster-up-sha.txt
  cluster-up/check.sh
  cluster-up/cluster/ephemeral-provider-common.sh
  cluster-up/cluster/okd-4.1/provider.sh
  cluster-up/version.txt
  hack/config-default.sh
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M

#2803 api: webhooks: add vm mutator to set machine type
  pkg/virt-api/api.go
  pkg/virt-api/webhooks/mutating-webhook/mutating-webhook.go
  pkg/virt-api/webhooks/mutating-webhook/mutators/BUILD.bazel
  pkg/virt-api/webhooks/mutating-webhook/mutators/vm-mutator.go
  pkg/virt-api/webhooks/mutating-webhook/mutators/vm-mutator_test.go
  tests/utils.go
  tests/vm_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/L

#2871 [release-0.20] Backport of #2787: Set IMAGE_PREFIX_ALT for explicitly for tests only, only release versioned virtctl binaries
  .travis.yml
  automation/test.sh
  hack/config-default.sh
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#2869 Skip kubevirt-bot in release announcement
  hack/release-announce.sh
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#2872 Fix straming from websockets to tcp
  staging/src/kubevirt.io/client-go/kubecli/BUILD.bazel
  staging/src/kubevirt.io/client-go/kubecli/vm_test.go
  staging/src/kubevirt.io/client-go/kubecli/websocket.go
  staging/src/kubevirt.io/client-go/kubecli/websocket_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/L

#2868 Set send timeout to the expecter
  tests/utils.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#2876 Remove www from links to kubevirt.io website
  README.md
  manifests/generated/operator-csv.yaml.in
  pkg/virt-operator/creation/csv/csv.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#2878 Add test ids
  tests/access_test.go
  tests/container_disk_test.go
  tests/migration_test.go
  tests/template_test.go
  tests/vmi_lifecycle_test.go
  tests/vmi_multus_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M

#2881 operator test add add test ids
  tests/operator_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#2880 Add the test_id for pausing_test
  tests/pausing_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#2888 [fix] allow virt-launcher to write to sysfs
  cmd/virt-handler/virt_launcher.cil
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#2890 WORKSPACE: Update libvirt container
  WORKSPACE
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#2840 make template VMs to use networkInterfaceMultiqueue
  examples/vm-template-fedora.yaml
  examples/vm-template-rhel7.yaml
  tools/vms-generator/utils/utils.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/S

#2895 Increase timeout for expose tests
  tests/expose_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/S

#2882 K8s 1.16
  cluster-up-sha.txt
  cluster-up/cluster/ephemeral-provider-common.sh
  cluster-up/cluster/k8s-1.16.2/README.md
  cluster-up/cluster/k8s-1.16.2/provider.sh
  cluster-up/cluster/okd-4.3/README.md
  cluster-up/cluster/okd-4.3/provider.sh
  cluster-up/version.txt
  hack/config-default.sh
  hack/functests.sh
  manifests/testing/disks-images-provider.yaml.in
  tests/BUILD.bazel
  tests/operator_test.go
  tests/utils.go
  tests/vmi_lifecycle_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/L

#2907 move mfranczy to emeritus approvers
  OWNERS
  OWNERS_ALIASES
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#2909 Prepare kubevirt for libvirt 5.6.0 without switching
  cmd/virt-launcher/virt-launcher.go
  pkg/cloud-init/BUILD.bazel
  pkg/cloud-init/cloud-init.go
  pkg/cloud-init/cloud-init_test.go
  pkg/cloud-init/cloudinit_suite_test.go
  pkg/config/BUILD.bazel
  pkg/config/config-map.go
  pkg/config/config_suite_test.go
  pkg/config/secret.go
  pkg/config/service-account.go
  pkg/emptydisk/BUILD.bazel
  pkg/emptydisk/emptydisk.go
  pkg/emptydisk/emptydisk_suite_test.go
  pkg/ephemeral-disk-utils/utils.go
  pkg/ephemeral-disk/BUILD.bazel
  pkg/ephemeral-disk/ephemeral-disk.go
  pkg/ephemeral-disk/ephemeral-disk_suite_test.go
  pkg/ephemeral-disk/ephemeral-disk_test.go
  pkg/host-disk/BUILD.bazel
  pkg/host-disk/host-disk.go
  pkg/host-disk/host_disk_suite_test.go
  pkg/virt-launcher/monitor.go
  pkg/virt-launcher/virtwrap/BUILD.bazel
  pkg/virt-launcher/virtwrap/manager_test.go
  tests/vmi_lifecycle_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/L

#2911 [release-0.23] Prepare kubevirt for libvirt 5.6.0 without switching
  cmd/virt-launcher/virt-launcher.go
  pkg/cloud-init/BUILD.bazel
  pkg/cloud-init/cloud-init.go
  pkg/cloud-init/cloud-init_test.go
  pkg/cloud-init/cloudinit_suite_test.go
  pkg/config/BUILD.bazel
  pkg/config/config-map.go
  pkg/config/config_suite_test.go
  pkg/config/secret.go
  pkg/config/service-account.go
  pkg/emptydisk/BUILD.bazel
  pkg/emptydisk/emptydisk.go
  pkg/emptydisk/emptydisk_suite_test.go
  pkg/ephemeral-disk-utils/utils.go
  pkg/ephemeral-disk/BUILD.bazel
  pkg/ephemeral-disk/ephemeral-disk.go
  pkg/ephemeral-disk/ephemeral-disk_suite_test.go
  pkg/ephemeral-disk/ephemeral-disk_test.go
  pkg/host-disk/BUILD.bazel
  pkg/host-disk/host-disk.go
  pkg/host-disk/host_disk_suite_test.go
  pkg/virt-launcher/monitor.go
  pkg/virt-launcher/virtwrap/BUILD.bazel
  pkg/virt-launcher/virtwrap/manager_test.go
  tests/vmi_lifecycle_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/L

#2905 fix wrong use SwapInSet when push Swap Out Metric
  pkg/monitoring/vms/prometheus/prometheus.go
Labels: approved, dco-signoff: yes, lgtm, ok-to-test, release-note-none, size/XS

#2908 Fix flaky test: pausing_test: Set timeout for console connection to 30 secs
  tests/pausing_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#2913 Update workspace libvirt5.6.0
  WORKSPACE
  tests/vmi_slirp_interface_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/XS

#2813 virtctl image-upload should create DataVolumes instead of PVCs
  .gitignore
  BUILD.bazel
  go.mod
  manifests/testing/cdi-v1.10.9.yaml.in
  pkg/virtctl/imageupload/BUILD.bazel
  pkg/virtctl/imageupload/imageupload.go
  pkg/virtctl/imageupload/imageupload_test.go
  tests/imageupload_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/L
