Repository kubevirt/kubevirt, pull requests merged in 2020-07, with the labels that each got.

#3693 Flaky functest - [test_id:1779] fixing race in the Expecter
  tests/vmi_networking_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#3543 tests, vmi: Fix IPv6 configuration through the console
  tests/utils.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M

#3528 Added Paused column to vmi
  pkg/virt-operator/creation/components/crds.go
  tests/kubectl_test.go
Labels: approved, dco-signoff: yes, kind/api-change, kind/build-change, lgtm, release-note-none, size/XS

#3708 WORKSPACE: Update libvirt container
  WORKSPACE
Labels: approved, dco-signoff: yes, lgtm, release-note, size/XS

#3166 Add guestagent virtctl commands
  pkg/virtctl/root.go
  pkg/virtctl/vm/vm.go
  pkg/virtctl/vm/vm_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/L

#3517 Add a FAQ entry with a comparison to Kata containers.
  FAQ.md
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#3684 Write to virt-launcher logs if devices are not present
  pkg/virt-handler/device-manager/generic_device.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/XS

#3725 Make the tests binary an artifact of the release
  .travis.yml
Labels: approved, dco-signoff: yes, lgtm, release-note, size/XS

#3600 [release-0.30] Add test to check kubevirt disk perms
  tests/container_disk_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M

#3719 Moved cleanup of test from AfterEach() hook to test body
  tests/migration_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/S

#3741 Add Content-Length to HTTP probe server
  tests/utils.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#3744 vendor: "Unreplace" prometheus-operator, update packages
  go.mod
  go.sum
  staging/src/kubevirt.io/client-go/generated/prometheus-operator/clientset/versioned/typed/monitoring/v1/BUILD.bazel
  staging/src/kubevirt.io/client-go/generated/prometheus-operator/clientset/versioned/typed/monitoring/v1/fake/BUILD.bazel
  staging/src/kubevirt.io/client-go/generated/prometheus-operator/clientset/versioned/typed/monitoring/v1/fake/fake_monitoring_client.go
  staging/src/kubevirt.io/client-go/generated/prometheus-operator/clientset/versioned/typed/monitoring/v1/fake/fake_podmonitor.go
  staging/src/kubevirt.io/client-go/generated/prometheus-operator/clientset/versioned/typed/monitoring/v1/generated_expansion.go
  staging/src/kubevirt.io/client-go/generated/prometheus-operator/clientset/versioned/typed/monitoring/v1/monitoring_client.go
  staging/src/kubevirt.io/client-go/generated/prometheus-operator/clientset/versioned/typed/monitoring/v1/podmonitor.go
  vendor/github.com/coreos/prometheus-operator/pkg/apis/monitoring/v1/BUILD.bazel
  vendor/github.com/coreos/prometheus-operator/pkg/apis/monitoring/v1/bindata.go
  vendor/github.com/coreos/prometheus-operator/pkg/apis/monitoring/v1/crd_kinds.go
  vendor/github.com/coreos/prometheus-operator/pkg/apis/monitoring/v1/openapi_generated.go
  vendor/github.com/coreos/prometheus-operator/pkg/apis/monitoring/v1/register.go
  vendor/github.com/coreos/prometheus-operator/pkg/apis/monitoring/v1/types.go
  vendor/github.com/coreos/prometheus-operator/pkg/apis/monitoring/v1/zz_generated.deepcopy.go
  vendor/github.com/prometheus/client_golang/prometheus/BUILD.bazel
  vendor/github.com/prometheus/client_golang/prometheus/build_info.go
  vendor/github.com/prometheus/client_golang/prometheus/build_info_pre_1.12.go
  vendor/github.com/prometheus/client_golang/prometheus/doc.go
  vendor/github.com/prometheus/client_golang/prometheus/go_collector.go
  vendor/github.com/prometheus/client_golang/prometheus/http.go
  vendor/github.com/prometheus/client_golang/prometheus/process_collector.go
  vendor/github.com/prometheus/client_golang/prometheus/process_collector_other.go
  vendor/github.com/prometheus/client_golang/prometheus/process_collector_windows.go
  vendor/github.com/prometheus/client_golang/prometheus/promhttp/http.go
  vendor/github.com/prometheus/client_golang/prometheus/registry.go
  vendor/github.com/prometheus/client_golang/prometheus/summary.go
  vendor/github.com/prometheus/client_golang/prometheus/wrap.go
  vendor/github.com/prometheus/common/model/time.go
  vendor/github.com/prometheus/procfs/BUILD.bazel
  vendor/github.com/prometheus/procfs/Makefile
  vendor/github.com/prometheus/procfs/Makefile.common
  vendor/github.com/prometheus/procfs/README.md
  vendor/github.com/prometheus/procfs/buddyinfo.go
  vendor/github.com/prometheus/procfs/fixtures.ttar
  vendor/github.com/prometheus/procfs/fs.go
  vendor/github.com/prometheus/procfs/go.mod
  vendor/github.com/prometheus/procfs/go.sum
  vendor/github.com/prometheus/procfs/internal/fs/fs.go
  vendor/github.com/prometheus/procfs/ipvs.go
  vendor/github.com/prometheus/procfs/mdstat.go
  vendor/github.com/prometheus/procfs/mountinfo.go
  vendor/github.com/prometheus/procfs/mountstats.go
  vendor/github.com/prometheus/procfs/net_dev.go
  vendor/github.com/prometheus/procfs/net_unix.go
  vendor/github.com/prometheus/procfs/proc.go
  vendor/github.com/prometheus/procfs/proc_environ.go
  vendor/github.com/prometheus/procfs/proc_io.go
  vendor/github.com/prometheus/procfs/proc_limits.go
  vendor/github.com/prometheus/procfs/proc_ns.go
  vendor/github.com/prometheus/procfs/proc_psi.go
  vendor/github.com/prometheus/procfs/proc_stat.go
  vendor/github.com/prometheus/procfs/proc_status.go
  vendor/github.com/prometheus/procfs/stat.go
  vendor/github.com/prometheus/procfs/ttar
  vendor/modules.txt
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XXL

#3729 [release-0.30] tests, vmi: Fix IPv6 configuration through the console
  tests/utils.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M

#3713 Use GracefulStop instead of Stop for GRPC server
  pkg/virt-handler/notify-server/server.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/S

#3750 Ensure that selinux context tests wait for configpropagation
  tests/security_features_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M

#3720 Bump kubevirtci: sriov provider fixes
  cluster-up-sha.txt
  cluster-up/cluster/images.sh
  cluster-up/cluster/kind-k8s-sriov-1.17.0/config_sriov.sh
  cluster-up/version.txt
  hack/config-default.sh
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/S

#3601 [release-0.30] Add test related to launcher capabilities
  tests/security_features_test.go
  tests/utils.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M

#3589 make VMs ping each other and not themselves
  tests/vmi_multus_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#3765 Add assertion to domain start/stop test
  tests/vmi_lifecycle_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/S

#3735 Exclude test suites from fetching changed tests
  automation/repeated_test.sh
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#3755 tests, reporter: Collect journal logs from nodes
  tests/reporter/kubernetes.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M

#3599 Add tests related to qemu processes
  tests/security_features_test.go
  tests/utils.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M

#3738 virt-api: validate labels with kubevirt.io prefix upon VMI creation
  pkg/virt-api/webhooks/validating-webhook/admitters/vmi-create-admitter.go
  pkg/virt-api/webhooks/validating-webhook/admitters/vmi-create-admitter_test.go
  pkg/virt-api/webhooks/validating-webhook/admitters/vmi-update-admitter.go
  pkg/virt-api/webhooks/validating-webhook/admitters/vmi-update-admitter_test.go
  pkg/virt-api/webhooks/validating-webhook/admitters/vms-admitter.go
  tools/vms-generator/vms-generator.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/L

#3779 K8s reporter to own a sub dir under $ARTIFACTS
  tests/tests_suite_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#3736 [release-0.30] Enable Secure Boot by default when EFI is enabled
  api/openapi-spec/swagger.json
  examples/vmi-alpine-efi.yaml
  pkg/virt-api/webhooks/validating-webhook/admitters/vmi-create-admitter.go
  pkg/virt-api/webhooks/validating-webhook/admitters/vmi-create-admitter_test.go
  pkg/virt-launcher/virtwrap/api/converter.go
  pkg/virt-launcher/virtwrap/api/converter_test.go
  staging/src/kubevirt.io/client-go/api/v1/openapi_generated.go
  staging/src/kubevirt.io/client-go/api/v1/schema.go
  staging/src/kubevirt.io/client-go/api/v1/schema_swagger_generated.go
  tests/utils.go
  tools/vms-generator/utils/utils.go
Labels: approved, dco-signoff: yes, kind/api-change, lgtm, release-note, size/M

#3692 Get QEMU logs from virtlogd
  cmd/virt-launcher/virt-launcher.go
  pkg/virt-launcher/virtwrap/util/libvirt_helper.go
  pkg/virt-launcher/virtwrap/util/libvirt_helper_test.go
  staging/src/kubevirt.io/client-go/log/log.go
Labels: approved, dco-signoff: yes, lgtm, needs-ok-to-test, release-note, size/L

#3761 [release-0.30] [tests] Wait for config changes to be propagated and reset them implicitly
  api/openapi-spec/swagger.json
  cmd/virt-handler/BUILD.bazel
  cmd/virt-handler/virt-handler.go
  pkg/healthz/BUILD.bazel
  pkg/healthz/healthz.go
  pkg/virt-api/api.go
  pkg/virt-config/config-map.go
  pkg/virt-config/virt-config.go
  pkg/virt-controller/rest/BUILD.bazel
  pkg/virt-controller/rest/rest.go
  pkg/virt-controller/watch/BUILD.bazel
  pkg/virt-controller/watch/application.go
  tests/migration_test.go
  tests/utils.go
  tests/vm_test.go
  tests/vmi_configuration_test.go
  tests/vmi_lifecycle_test.go
Labels: approved, dco-signoff: yes, kind/build-change, lgtm, release-note-none, size/L

#3499 Added Metrics docummentation
  docs/metrics.md
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/L

#3802 Add the KubeVirt resource to the published openapi spec
  api/openapi-spec/swagger.json
  pkg/virt-api/rest/definitions.go
  staging/src/kubevirt.io/client-go/api/v1/openapi_generated.go
  staging/src/kubevirt.io/client-go/api/v1/types.go
  staging/src/kubevirt.io/client-go/apis/snapshot/v1alpha1/openapi_generated.go
Labels: approved, dco-signoff: yes, kind/api-change, lgtm, release-note-none, size/XXL

#3807 tests: Do not create two VMI/s with the same spec
  tests/vmi_configuration_test.go
  tests/vmi_networking_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/S

#2694 Use native go library for selinux and stop labeling host directories
  .bazelrc
  BUILD.bazel
  cmd/virt-chroot/BUILD.bazel
  cmd/virt-chroot/main.go
  cmd/virt-chroot/selinux.go
  cmd/virt-handler/virt-handler.go
  go.mod
  go.sum
  hack/build-go.sh
  pkg/virt-handler/selinux/BUILD.bazel
  pkg/virt-handler/selinux/labels.go
  pkg/virt-handler/selinux/labels_test.go
  vendor/github.com/opencontainers/selinux/LICENSE
  vendor/github.com/opencontainers/selinux/go-selinux/BUILD.bazel
  vendor/github.com/opencontainers/selinux/go-selinux/doc.go
  vendor/github.com/opencontainers/selinux/go-selinux/selinux.go
  vendor/github.com/opencontainers/selinux/go-selinux/selinux_linux.go
  vendor/github.com/opencontainers/selinux/go-selinux/selinux_stub.go
  vendor/github.com/opencontainers/selinux/go-selinux/xattrs.go
  vendor/github.com/opencontainers/selinux/pkg/pwalk/BUILD.bazel
  vendor/github.com/opencontainers/selinux/pkg/pwalk/README.md
  vendor/github.com/opencontainers/selinux/pkg/pwalk/pwalk.go
  vendor/github.com/pkg/errors/.travis.yml
  vendor/github.com/pkg/errors/BUILD.bazel
  vendor/github.com/pkg/errors/Makefile
  vendor/github.com/pkg/errors/README.md
  vendor/github.com/pkg/errors/errors.go
  vendor/github.com/pkg/errors/go113.go
  vendor/github.com/pkg/errors/stack.go
  vendor/github.com/willf/bitset/.gitignore
  vendor/github.com/willf/bitset/.travis.yml
  vendor/github.com/willf/bitset/BUILD.bazel
  vendor/github.com/willf/bitset/LICENSE
  vendor/github.com/willf/bitset/Makefile
  vendor/github.com/willf/bitset/README.md
  vendor/github.com/willf/bitset/azure-pipelines.yml
  vendor/github.com/willf/bitset/bitset.go
  vendor/github.com/willf/bitset/popcnt.go
  vendor/github.com/willf/bitset/popcnt_19.go
  vendor/github.com/willf/bitset/popcnt_amd64.go
  vendor/github.com/willf/bitset/popcnt_amd64.s
  vendor/github.com/willf/bitset/popcnt_generic.go
  vendor/github.com/willf/bitset/trailing_zeros_18.go
  vendor/github.com/willf/bitset/trailing_zeros_19.go
  vendor/modules.txt
Labels: approved, dco-signoff: yes, kind/build-change, lgtm, release-note, size/XXL

#3813 [release-0.30] Add tests related to qemu processes
  tests/security_features_test.go
  tests/utils.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/L

#3803 Rename SMBIOS element
  api/openapi-spec/swagger.json
  staging/src/kubevirt.io/client-go/api/v1/openapi_generated.go
  staging/src/kubevirt.io/client-go/api/v1/types.go
  staging/src/kubevirt.io/client-go/apis/snapshot/v1alpha1/openapi_generated.go
Labels: approved, dco-signoff: yes, kind/api-change, lgtm, release-note, size/XS

#3778 Don't emit event if we fail to sync a final VMI
  pkg/virt-handler/vm.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/XS

#3784 Add build verification targets to the Makefile
  Makefile
  automation/travisci-test.sh
  hack/check-for-binaries.sh
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M

#3812 Add Namespaces logging to kuberentes reporter
  tests/reporter/kubernetes.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/S

#3817 Flaky [test_id:4142]should include the storage metrics for a running VM
  tests/infra_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#3801 Fix some synchronization issues in the static tests
  pkg/testutils/mock_queue.go
  pkg/virt-handler/isolation/isolation_test.go
  pkg/virt-launcher/monitor_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/S

#3830 (take 2) Ensure we're resilient to domain notify server restarts
  pkg/virt-handler/BUILD.bazel
  pkg/virt-handler/notify-server/server.go
  pkg/virt-handler/vm.go
  pkg/virt-handler/vm_test.go
  pkg/virt-launcher/notify-client/client.go
  pkg/virt-launcher/virtwrap/cli/libvirt.go
  tests/migration_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/L

#3825 virtctl: Print response body on error from upload proxy.
  pkg/virtctl/imageupload/imageupload.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/XS

#3786 tests: Parse flags once and do not execute code in the ginkgo containers body
  tests/BUILD.bazel
  tests/access_test.go
  tests/config_test.go
  tests/console_test.go
  tests/container_disk_test.go
  tests/datavolume_test.go
  tests/expose_test.go
  tests/flags.go
  tests/imageupload_test.go
  tests/infra_test.go
  tests/kubectl_test.go
  tests/migration_test.go
  tests/networkpolicy_test.go
  tests/operator_test.go
  tests/pausing_test.go
  tests/probes_test.go
  tests/replicaset_test.go
  tests/security_features_test.go
  tests/snapshot_test.go
  tests/stability_test.go
  tests/storage_test.go
  tests/subresource_api_test.go
  tests/template_test.go
  tests/utils.go
  tests/version_test.go
  tests/virt_control_plane_test.go
  tests/vm_test.go
  tests/vm_watch_test.go
  tests/vmi_cloudinit_hook_sidecar_test.go
  tests/vmi_cloudinit_test.go
  tests/vmi_configuration_test.go
  tests/vmi_gpu_test.go
  tests/vmi_headless_test.go
  tests/vmi_hook_sidecar_test.go
  tests/vmi_ignition_test.go
  tests/vmi_iothreads_test.go
  tests/vmi_lifecycle_test.go
  tests/vmi_monitoring_test.go
  tests/vmi_multiqueue_test.go
  tests/vmi_multus_test.go
  tests/vmi_networking_test.go
  tests/vmi_slirp_interface_test.go
  tests/vmidefaults_test.go
  tests/vmipreset_test.go
  tests/vnc_test.go
  tests/windows_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XXL

#3636 Add k8s metadata labels to VMI metrics
  pkg/monitoring/vms/prometheus/prometheus.go
  pkg/monitoring/vms/prometheus/prometheus_test.go
  tests/infra_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/XXL

#3831 [release-0.30] Ensure we're resilient to domain notify server restarts
  pkg/virt-handler/BUILD.bazel
  pkg/virt-handler/notify-server/server.go
  pkg/virt-handler/vm.go
  pkg/virt-handler/vm_test.go
  pkg/virt-launcher/notify-client/client.go
  pkg/virt-launcher/virtwrap/cli/libvirt.go
  tests/migration_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/L

#3833 Revert make focus
  Makefile
  automation/test.sh
  docs/ci.md
  hack/focus.sh
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M

#3819 Tighten up perm on container/emphemeral disk.
  pkg/ephemeral-disk/ephemeral-disk.go
  pkg/virt-handler/container-disk/mount.go
  tests/container_disk_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/S

#3836 buffer the error channel in the notify pipe logic to avoid blocking
  pkg/virt-handler/vm.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#3767 Fix kubevirtci bumping
  Makefile
  cluster-up-sha.txt
  cluster-up/cluster/kind-k8s-sriov-1.17.0/csrcreator/BUILD.bazel
  hack/generate.sh
  hack/sync-kubevirtci.sh
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M

#3814 virt-launcher: Remove unneeded condition from StartDomainNotifier
  pkg/virt-launcher/notify-client/client.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#3848 virt-handler,test: Fix move vmi to `Failed` on virt-launcher critical error
  pkg/virt-handler/vm_test.go
  pkg/virt-launcher/virtwrap/network/common.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/S

#3852 Look up the pr-creator binary the right way
  hack/autobump-generic.sh
  hack/autobump-kubevirtci.sh
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#3861 Fix a few mistakes in the automatic bump scripts
  hack/autobump-generic.sh
  hack/autobump-kubevirtci.sh
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/S

#3642 Update VMI status with latest Pod network IP
  cmd/virt-handler/virt-handler.go
  pkg/util/util.go
  pkg/virt-controller/watch/vmi.go
  pkg/virt-controller/watch/vmi_test.go
  pkg/virt-handler/BUILD.bazel
  pkg/virt-handler/vm.go
  pkg/virt-handler/vm_test.go
  pkg/virt-launcher/virtwrap/network/BUILD.bazel
  pkg/virt-launcher/virtwrap/network/network.go
  pkg/virt-launcher/virtwrap/network/podinterface.go
  pkg/virt-launcher/virtwrap/network/podinterface_test.go
  tests/migration_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/XL

#3844 Remove unused feature gates
  pkg/virt-config/feature-gates.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/S

#3869 tests: fix possible null pointer dereference
  tests/utils.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/S

#3870 Kubernetes reporter: Dump artifacts at AfterSuite
  tests/reporter/kubernetes.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#3846 tests: Extract ContainerDisk code to containerdisk.go
  tests/BUILD.bazel
  tests/containerdisk.go
  tests/utils.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M

#3794 Add NetworkAttachmentDefinition reporter
  tests/reporter/kubernetes.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M

#3885 Log a message indicating why a domain event failed to send
  pkg/virt-launcher/notify-client/client.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#3868 Kubernetes reporter: Dump Services artifacts
  tests/reporter/BUILD.bazel
  tests/reporter/kubernetes.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M

#3806 virt-launcher: Remove part of the domain event errors
  pkg/virt-launcher/notify-client/client.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#3911 Added test-id for vcpu_wait and vcpu_sec metrics
  tests/infra_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#3855 Clean up root owners file to reflect reality
  OWNERS_ALIASES
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/S
