Repository kubevirt/kubevirt, pull requests merged in 2020-09, with the labels that each got.

#4042 tests, Adapt primary_pod_network and migration tests to be dual stack compatible
  tests/migration_test.go
  tests/network/BUILD.bazel
  tests/network/primary_pod_network.go
  tests/network/validation.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M

#4067 adapt tests for dual-stack cluster: [test_id:4153]VMI with masquerade binding and guest agent should expose Pod IP as its public address
  tests/vmi_configuration_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/S

#4065 Make goveralls verbose, match goveralls settings in Makefile
  Makefile
  hack/goveralls.sh
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#4066 Update kubevirtci to the latest version and fix make generate
  Makefile
  cluster-up-sha.txt
  cluster-up/cluster/local/provider.sh
  cluster-up/version.txt
  hack/config-default.sh
  hack/verify-generate.sh
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M

#4087 tests, skip migration fail test on kind ipv6 provider
  tests/migration_test.go
  tests/utils.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#3871 tests, network: Test connectivity pre/post migration
  tests/BUILD.bazel
  tests/expose_test.go
  tests/job.go
  tests/ping.go
  tests/vmi_networking_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/L

#4031 Prepare kubevirt for sonobuoy conformance testing
  BUILD.bazel
  docs/conformance.md
  hack/bazel-build-images.sh
  hack/bazel-push-images.sh
  hack/config-default.sh
  tests/BUILD.bazel
  tests/conformance-config.json
  tests/conformance/BUILD.bazel
  tests/conformance/conformance.go
  tests/container_disk_test.go
  tests/flags/flags.go
  tests/infra_test.go
  tests/utils.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/L

#4084 virt-operator: on update, roll over daemonsets first, then controllers
  pkg/virt-operator/install-strategy/create.go
  pkg/virt-operator/kubevirt_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/L

#4093 test, masquerade: Add dual stack vmi to vmi ping
  tests/vmi_networking_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M

#4107 Add events for vmi failed render
  pkg/virt-controller/watch/vmi.go
  pkg/virt-controller/watch/vmi_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#4110 Add test-id's for VMI migration and lifecycle testcases
  tests/migration_test.go
  tests/vmi_lifecycle_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#4029 Fix issues that virt-operator cannot extract MonitorNamespace and MonitorServiceAccount from JSON
  pkg/virt-operator/util/config.go
  pkg/virt-operator/util/config_test.go
Labels: approved, dco-signoff: yes, lgtm, ok-to-test, release-note, size/S

#4058 tests, expecter: Move generic expecter code from ping.go to expecter.go
  tests/BUILD.bazel
  tests/expecter.go
  tests/login.go
  tests/ping.go
  tests/utils.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XL

#4045 tests, Fix networkpolicy tests and support them upstream
  tests/networkpolicy_test.go
  tests/utils.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/L

#3612 add patches to virt-controller
  api/openapi-spec/swagger.json
  manifests/generated/kubevirt-cr.yaml.in
  pkg/virt-operator/install-strategy/BUILD.bazel
  pkg/virt-operator/install-strategy/create.go
  pkg/virt-operator/install-strategy/create_test.go
  pkg/virt-operator/install-strategy/patches.go
  pkg/virt-operator/install-strategy/patches_test.go
  pkg/virt-operator/install-strategy/strategy_test.go
  pkg/virt-operator/kubevirt.go
  pkg/virt-operator/kubevirt_test.go
  staging/src/kubevirt.io/client-go/api/v1/deepcopy_generated.go
  staging/src/kubevirt.io/client-go/api/v1/openapi_generated.go
  staging/src/kubevirt.io/client-go/api/v1/types.go
  staging/src/kubevirt.io/client-go/api/v1/types_swagger_generated.go
  staging/src/kubevirt.io/client-go/apis/snapshot/v1alpha1/openapi_generated.go
  tests/operator_test.go
Labels: approved, dco-signoff: yes, kind/api-change, lgtm, release-note, size/XL

#4099 tests, Make network policy tests dual stack compatible
  tests/networkpolicy_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M

#4102 virt-api: introduce a more relaxed admission policy for a VM that is under rename process
  pkg/virt-api/webhooks/validating-webhook/admitters/vms-admitter.go
  pkg/virt-api/webhooks/validating-webhook/admitters/vms-admitter_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/L

#4112 Limit CriticalAddonsOnly taint to a single compute
  tests/infra_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/L

#4027 Set memfd for memorybacking
  pkg/virt-launcher/virtwrap/api/converter.go
  pkg/virt-launcher/virtwrap/api/converter_test.go
  pkg/virt-launcher/virtwrap/api/deepcopy_generated.go
  pkg/virt-launcher/virtwrap/api/schema.go
  staging/src/kubevirt.io/client-go/api/v1/types.go
  tests/vmi_configuration_test.go
Labels: approved, dco-signoff: yes, kind/api-change, lgtm, ok-to-test, release-note, size/L

#4113 Fixes Operator Issues blocking v0.33.0 release
  api/openapi-spec/swagger.json
  pkg/virt-operator/install-strategy/create_test.go
  pkg/virt-operator/kubevirt.go
  pkg/virt-operator/kubevirt_test.go
  staging/src/kubevirt.io/client-go/api/v1/types.go
  tests/operator_test.go
Labels: approved, dco-signoff: yes, kind/api-change, lgtm, release-note-none, size/L

#3289 Add option to run only VNC Proxy in virtctl
  pkg/virtctl/vnc/vnc.go
  tests/BUILD.bazel
  tests/vnc_test.go
  vendor/github.com/mitchellh/go-vnc/BUILD.bazel
  vendor/github.com/mitchellh/go-vnc/LICENSE
  vendor/github.com/mitchellh/go-vnc/README.md
  vendor/github.com/mitchellh/go-vnc/client.go
  vendor/github.com/mitchellh/go-vnc/client_auth.go
  vendor/github.com/mitchellh/go-vnc/color.go
  vendor/github.com/mitchellh/go-vnc/encoding.go
  vendor/github.com/mitchellh/go-vnc/pixel_format.go
  vendor/github.com/mitchellh/go-vnc/pointer.go
  vendor/github.com/mitchellh/go-vnc/server_messages.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/XXL

#4131 Add mhenriks to approvers/reviewers list
  OWNERS_ALIASES
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#4141 tests, net: Post migration connectivity check with dual stack support.
  tests/ping.go
  tests/vmi_networking_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M

#4154 Fixes update service endpoints in place (resolves recent vmi networking test failures)
  api/openapi-spec/swagger.json
  pkg/virt-operator/install-strategy/create.go
  pkg/virt-operator/install-strategy/create_test.go
  pkg/virt-operator/install-strategy/patches.go
  pkg/virt-operator/install-strategy/patches_test.go
  staging/src/kubevirt.io/client-go/api/v1/deepcopy_generated.go
  staging/src/kubevirt.io/client-go/api/v1/openapi_generated.go
  staging/src/kubevirt.io/client-go/api/v1/types.go
  staging/src/kubevirt.io/client-go/api/v1/types_swagger_generated.go
  staging/src/kubevirt.io/client-go/apis/snapshot/v1alpha1/openapi_generated.go
  tests/operator_test.go
Labels: approved, dco-signoff: yes, kind/api-change, lgtm, release-note, size/L

#4165 virt-chroot: use sysfs node for getenforce instead of less-reliable go-selinux
  cmd/virt-chroot/selinux.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/S

#4160 backporting release-0.33 blocker fix
  pkg/virt-operator/install-strategy/create_test.go
  pkg/virt-operator/kubevirt.go
  pkg/virt-operator/kubevirt_test.go
  staging/src/kubevirt.io/client-go/api/v1/types.go
  tests/operator_test.go
Labels: approved, dco-signoff: yes, kind/api-change, lgtm, release-blocker/release-0.33, release-note-none, size/L

#4139 Test dual-stack network configuration unless explicitly told to skip it
  hack/functests.sh
  tests/flags/flags.go
  tests/libnet/BUILD.bazel
  tests/libnet/cluster.go
  tests/network/BUILD.bazel
  tests/network/dual_stack_cluster.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/L

#4155 Fix virtctl image-upload ignoring custom storage class argument
  pkg/virtctl/imageupload/imageupload.go
  pkg/virtctl/imageupload/imageupload_test.go
  tests/imageupload_test.go
Labels: approved, dco-signoff: yes, lgtm, ok-to-test, release-note-none, size/S

#3993 Fix virtctl build for linux-amd64
  hack/bazel-build.sh
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#4175 Fixing colisions in openapi.
  api/openapi-spec/swagger.json
  go.mod
  go.sum
  pkg/util/openapi/openapi.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XXL

#3733 Release Process Revisions
  Makefile
  docs/release.md
  hack/release-announce.sh
  hack/release.sh
Labels: approved, dco-signoff: yes, lgtm, release-note, size/L

#4129 Dual stack probe func tests refactor
  tests/BUILD.bazel
  tests/pod_servers.go
  tests/probes_test.go
  tests/utils.go
  tests/vmi_servers.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/L

#4115 Add conformance automation and manifest publishing
  .travis.yml
  Makefile
  automation/conformance.sh
  docs/conformance.md
  hack/builder/Dockerfile
  hack/conformance.sh
  hack/dockerized
  manifests/release/conformance.yaml.in
Labels: approved, dco-signoff: yes, lgtm, release-note, size/L

#3929 Add support for camel-case spellings of "userdata" and "networkdata"
  pkg/cloud-init/cloud-init.go
  pkg/cloud-init/cloud-init_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/S

#4083 Fix a (potential) copy-paste error and (try to) re-enable the certificate tests
  pkg/virt-operator/creation/components/webhooks.go
  tests/infra_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#3471 Support hiding KVM MSR from guest
  WORKSPACE
  api/openapi-spec/swagger.json
  images/cdi-http-import-server/BUILD.bazel
  images/cdi-http-import-server/entrypoint.sh
  pkg/virt-launcher/virtwrap/api/converter.go
  pkg/virt-launcher/virtwrap/api/converter_test.go
  pkg/virt-launcher/virtwrap/api/deepcopy_generated.go
  pkg/virt-launcher/virtwrap/api/schema.go
  pkg/virt-launcher/virtwrap/api/schema_test.go
  staging/src/kubevirt.io/client-go/api/v1/deepcopy_generated.go
  staging/src/kubevirt.io/client-go/api/v1/openapi_generated.go
  staging/src/kubevirt.io/client-go/api/v1/schema.go
  staging/src/kubevirt.io/client-go/api/v1/schema_swagger_generated.go
  staging/src/kubevirt.io/client-go/api/v1/schema_test.go
  staging/src/kubevirt.io/client-go/apis/snapshot/v1alpha1/openapi_generated.go
  tests/utils.go
  tests/vmi_configuration_test.go
Labels: approved, dco-signoff: yes, kind/api-change, lgtm, ok-to-test, release-note, size/L

#4035 Create network `Service`s module tests + test `Service`s API in dual-stack network configs
  tests/job.go
  tests/libvmi/factory.go
  tests/libvmi/network.go
  tests/network/BUILD.bazel
  tests/network/services.go
  tests/vmi_networking_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/L

#4183 SELinux: merge .cil policies and add a lot of comments
  cmd/virt-handler/BUILD.bazel
  cmd/virt-handler/base_container.cil
  cmd/virt-handler/virt_launcher.cil
  pkg/virt-handler/selinux/labels.go
Labels: approved, dco-signoff: yes, kind/build-change, lgtm, release-note-none, size/M

#4061 tests, networkpolicy: Add some tier1 http tests
  tests/BUILD.bazel
  tests/libvmi/network.go
  tests/login.go
  tests/networkpolicy_test.go
  tests/utils.go
  tests/vmi_servers.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/L

#4149 Bump kubevirtci to start testing k8s-1.19 provider
  cluster-up-sha.txt
  cluster-up/cluster/ephemeral-provider-common.sh
  cluster-up/cluster/images.sh
  cluster-up/cluster/k8s-1.19/README.md
  cluster-up/cluster/k8s-1.19/dev-guide.md
  cluster-up/cluster/k8s-1.19/provider.sh
  cluster-up/version.txt
  hack/config-default.sh
  hack/sync-kubevirtci.sh
  tests/utils.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/L

#4193 add snapshot APIGroup to aggregate cluster rules
  manifests/generated/operator-csv.yaml.in
  manifests/generated/rbac-operator.authorization.k8s.yaml.in
  pkg/virt-operator/creation/rbac/cluster.go
  tests/access_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/L

#3493 Add experimental support for VirtIO-FS
  api/openapi-spec/swagger.json
  cmd/virt-handler/virt_launcher.cil
  pkg/util/util.go
  pkg/virt-api/webhooks/validating-webhook/admitters/vmi-create-admitter.go
  pkg/virt-api/webhooks/validating-webhook/admitters/vmi-create-admitter_test.go
  pkg/virt-config/feature-gates.go
  pkg/virt-controller/services/template.go
  pkg/virt-launcher/virtwrap/api/converter.go
  pkg/virt-launcher/virtwrap/api/deepcopy_generated.go
  pkg/virt-launcher/virtwrap/api/schema.go
  pkg/virt-launcher/virtwrap/util/libvirt_helper.go
  staging/src/kubevirt.io/client-go/api/v1/deepcopy_generated.go
  staging/src/kubevirt.io/client-go/api/v1/openapi_generated.go
  staging/src/kubevirt.io/client-go/api/v1/schema.go
  staging/src/kubevirt.io/client-go/api/v1/schema_swagger_generated.go
  staging/src/kubevirt.io/client-go/apis/snapshot/v1alpha1/openapi_generated.go
  tests/storage_test.go
  tests/utils.go
Labels: approved, dco-signoff: yes, kind/api-change, lgtm, release-note, size/XL

#4046 Fixes for vnc
  pkg/virtctl/vnc/vnc.go
Labels: approved, dco-signoff: yes, kind/api-change, kind/build-change, lgtm, needs-ok-to-test, release-note-none, size/S

#4163 Only set selinux context if selinux is not disabled
  pkg/virt-launcher/virtwrap/network/BUILD.bazel
  pkg/virt-launcher/virtwrap/network/common.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M

#3927 Adds new metric kubevirt_vmi_memory_unused_bytes
  docs/metrics.md
  pkg/monitoring/vms/prometheus/BUILD.bazel
  pkg/monitoring/vms/prometheus/prometheus.go
  pkg/monitoring/vms/prometheus/prometheus_test.go
  tests/infra_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/M

#4092 Incorporate HCO's nodeselectors logic into KubeVirt
  api/openapi-spec/swagger.json
  pkg/virt-operator/install-strategy/create.go
  pkg/virt-operator/install-strategy/create_test.go
  staging/src/kubevirt.io/client-go/api/v1/BUILD.bazel
  staging/src/kubevirt.io/client-go/api/v1/componentconfig.go
  staging/src/kubevirt.io/client-go/api/v1/deepcopy_generated.go
  staging/src/kubevirt.io/client-go/api/v1/openapi_generated.go
  staging/src/kubevirt.io/client-go/api/v1/types.go
  staging/src/kubevirt.io/client-go/api/v1/types_swagger_generated.go
  staging/src/kubevirt.io/client-go/apis/snapshot/v1alpha1/openapi_generated.go
  tests/operator_test.go
Labels: approved, dco-signoff: yes, kind/api-change, lgtm, release-note, size/XL

#4159 Add creation of bazelrc for running unnested in prow
  hack/builder/Dockerfile
  hack/builder/build.sh
  hack/builder/create_bazel_cache_rcs.sh
  hack/builder/entrypoint.sh
  hack/builder/version.sh
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M

#4196 Fix ACPI doc string
  api/openapi-spec/swagger.json
  staging/src/kubevirt.io/client-go/api/v1/openapi_generated.go
  staging/src/kubevirt.io/client-go/api/v1/schema.go
  staging/src/kubevirt.io/client-go/api/v1/schema_swagger_generated.go
  staging/src/kubevirt.io/client-go/apis/snapshot/v1alpha1/openapi_generated.go
Labels: approved, dco-signoff: yes, kind/api-change, lgtm, ok-to-test, release-note-none, size/S

#4200 examples, vmi-masquerade: correct userData script
  examples/vmi-masquerade.yaml
  tools/vms-generator/utils/utils.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#4212 flaky pause test: make long-running process longer and quieter
  tests/pausing_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/S

#4215 Release func tests on every release
  .travis.yml
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#4216 Add missing test ids
  tests/kubectl_test.go
  tests/vnc_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#4069 Cert config option
  cmd/virt-handler/virt-handler.go
  pkg/certificates/bootstrap/cert-manager.go
  pkg/certificates/bootstrap/cert-manager_test.go
  pkg/util/webhooks/ca-manager.go
  pkg/util/webhooks/tls.go
  pkg/util/webhooks/tls_test.go
  pkg/virt-api/api.go
  pkg/virt-controller/watch/application.go
  pkg/virt-operator/application.go
Labels: approved, dco-signoff: yes, lgtm, ok-to-test, release-note-none, size/L

#4162 Calculate vmipod CPUs requests based on the number of guest vCPU and cluster cpu-allocation-ratio
  api/openapi-spec/swagger.json
  pkg/virt-config/config-map.go
  pkg/virt-config/virt-config.go
  pkg/virt-controller/services/template.go
  pkg/virt-controller/services/template_test.go
  staging/src/kubevirt.io/client-go/api/v1/openapi_generated.go
  staging/src/kubevirt.io/client-go/api/v1/types.go
  staging/src/kubevirt.io/client-go/apis/snapshot/v1alpha1/openapi_generated.go
Labels: approved, dco-signoff: yes, kind/api-change, lgtm, release-note, size/L

#4202 Fix sync of generated client-go to master
  hack/publish-staging.sh
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#4220 Keep conformance artifacts on the top level
  automation/conformance.sh
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#4223 only focus on tests that require rook-ceph for rook-ceph lane
  automation/test.sh
  tests/migration_test.go
  tests/restore_test.go
  tests/snapshot_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XL

#4127 introduce retryOnConflict to certificate infra test
  tests/BUILD.bazel
  tests/infra_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/S

#4237 fix typos
  tests/operator_test.go
  tests/vmi_multus_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#4100 Support testing kubevirt on RHCOS
  cluster-up-sha.txt
  cluster-up/cluster/images.sh
  cluster-up/version.txt
  examples/vmi-host-disk.yaml
  hack/config-default.sh
  tools/vms-generator/utils/utils.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/S

#4225 Test IDs for Node Placement tests
  tests/operator_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#4075 Change state label to be human readable
  pkg/monitoring/vms/prometheus/BUILD.bazel
  pkg/monitoring/vms/prometheus/prometheus.go
  pkg/monitoring/vms/prometheus/prometheus_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/L

#4071 Update to bazel 3.4.1
  .bazelversion
  BUILD.bazel
  WORKSPACE
  hack/bazel-generate.sh
  hack/builder/Dockerfile
  hack/builder/version.sh
  hack/dockerized
  pkg/handler-launcher-com/cmd/info/BUILD.bazel
  pkg/handler-launcher-com/cmd/v1/BUILD.bazel
  pkg/handler-launcher-com/notify/info/BUILD.bazel
  pkg/handler-launcher-com/notify/v1/BUILD.bazel
  pkg/hooks/info/BUILD.bazel
  pkg/hooks/v1alpha1/BUILD.bazel
  pkg/hooks/v1alpha2/BUILD.bazel
  pkg/virt-config/config_test.go
  vendor/github.com/gogo/protobuf/proto/BUILD.bazel
  vendor/github.com/golang/protobuf/ptypes/BUILD.bazel
  vendor/github.com/google/uuid/BUILD.bazel
  vendor/github.com/googleapis/gnostic/OpenAPIv2/BUILD.bazel
  vendor/github.com/googleapis/gnostic/compiler/BUILD.bazel
  vendor/github.com/googleapis/gnostic/extensions/BUILD.bazel
  vendor/github.com/mattn/go-runewidth/BUILD.bazel
  vendor/github.com/matttproud/golang_protobuf_extensions/pbutil/BUILD.bazel
  vendor/github.com/onsi/gomega/ghttp/BUILD.bazel
  vendor/github.com/prometheus/client_golang/prometheus/BUILD.bazel
  vendor/github.com/prometheus/client_model/go/BUILD.bazel
  vendor/github.com/prometheus/common/expfmt/BUILD.bazel
  vendor/github.com/vishvananda/netlink/BUILD.bazel
  vendor/golang.org/x/crypto/ssh/terminal/BUILD.bazel
  vendor/golang.org/x/net/internal/socket/BUILD.bazel
  vendor/golang.org/x/net/ipv4/BUILD.bazel
  vendor/golang.org/x/sys/cpu/BUILD.bazel
  vendor/golang.org/x/sys/unix/BUILD.bazel
  vendor/golang.org/x/sys/windows/BUILD.bazel
  vendor/google.golang.org/appengine/BUILD.bazel
  vendor/google.golang.org/appengine/internal/BUILD.bazel
  vendor/google.golang.org/appengine/internal/app_identity/BUILD.bazel
  vendor/google.golang.org/appengine/internal/base/BUILD.bazel
  vendor/google.golang.org/appengine/internal/datastore/BUILD.bazel
  vendor/google.golang.org/appengine/internal/log/BUILD.bazel
  vendor/google.golang.org/appengine/internal/modules/BUILD.bazel
  vendor/google.golang.org/appengine/internal/remote_api/BUILD.bazel
  vendor/google.golang.org/appengine/internal/urlfetch/BUILD.bazel
  vendor/google.golang.org/appengine/urlfetch/BUILD.bazel
  vendor/google.golang.org/genproto/googleapis/rpc/status/BUILD.bazel
  vendor/gopkg.in/cheggaaa/pb.v1/BUILD.bazel
  vendor/k8s.io/client-go/discovery/BUILD.bazel
  vendor/libvirt.org/libvirt-go/BUILD.bazel
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/L

#4247 wait for vmi-killer pod to start before moving on
  tests/vmi_lifecycle_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/S

#4012 Support eviction API for VMIs with eviction strategy
  api/openapi-spec/swagger.json
  manifests/generated/operator-csv.yaml.in
  manifests/generated/rbac-operator.authorization.k8s.yaml.in
  pkg/virt-api/api.go
  pkg/virt-api/webhooks/validating-webhook/admitters/BUILD.bazel
  pkg/virt-api/webhooks/validating-webhook/admitters/pod-eviction-admitter.go
  pkg/virt-api/webhooks/validating-webhook/admitters/pod-eviction-admitter_test.go
  pkg/virt-api/webhooks/validating-webhook/validating-webhook.go
  pkg/virt-controller/watch/drain/evacuation/BUILD.bazel
  pkg/virt-controller/watch/drain/evacuation/evacuation.go
  pkg/virt-controller/watch/drain/evacuation/evacuation_test.go
  pkg/virt-operator/creation/components/webhooks.go
  pkg/virt-operator/creation/rbac/apiserver.go
  staging/src/kubevirt.io/client-go/api/v1/openapi_generated.go
  staging/src/kubevirt.io/client-go/api/v1/types.go
  staging/src/kubevirt.io/client-go/api/v1/types_swagger_generated.go
  staging/src/kubevirt.io/client-go/apis/snapshot/v1alpha1/openapi_generated.go
  tests/BUILD.bazel
  tests/migration_test.go
  tests/utils.go
Labels: approved, dco-signoff: yes, kind/api-change, kind/build-change, lgtm, release-note, size/XL

#4248 selinux: always build KubeVirt with selinux support
  hack/build-go.sh
Labels: approved, dco-signoff: yes, lgtm, release-note, size/XS

#4236 docs: Update for k8s-1.18 as default provider
  docs/getting-started.md
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#4261 Revise DataVolumeTemplate API field
  api/openapi-spec/swagger.json
  examples/vm-alpine-datavolume.yaml
  pkg/virt-api/webhooks/validating-webhook/admitters/vms-admitter_test.go
  pkg/virt-controller/watch/snapshot/BUILD.bazel
  pkg/virt-controller/watch/snapshot/restore.go
  pkg/virt-controller/watch/snapshot/snapshot_test.go
  pkg/virt-controller/watch/vm.go
  pkg/virt-controller/watch/vm_test.go
  staging/src/kubevirt.io/client-go/api/v1/deepcopy_generated.go
  staging/src/kubevirt.io/client-go/api/v1/openapi_generated.go
  staging/src/kubevirt.io/client-go/api/v1/types.go
  staging/src/kubevirt.io/client-go/api/v1/types_swagger_generated.go
  staging/src/kubevirt.io/client-go/apis/snapshot/v1alpha1/openapi_generated.go
  tests/restore_test.go
  tests/utils.go
  tests/vm_test.go
  tools/vms-generator/utils/utils.go
Labels: approved, dco-signoff: yes, kind/api-change, lgtm, release-note-none, size/L

#4263 Add readiness and health probes to virt-handler
  pkg/virt-operator/creation/components/deployments.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/M

#4235 Ensure container disks are pulled before starting virt-launcher
  cmd/container-disk-v2alpha/main.c
  pkg/container-disk/container-disk.go
  pkg/virt-controller/services/template.go
  pkg/virt-controller/services/template_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/M

#4246 tests, utils: Check events watcher type before casting
  tests/BUILD.bazel
  tests/utils.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/S

#4249 wrong apiVersion used for VirtualMachineRestore owner references
  pkg/virt-controller/watch/snapshot/restore.go
  pkg/virt-controller/watch/snapshot/restore_test.go
  tests/restore_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/S

#4016 allow for postcopy migration
  api/openapi-spec/swagger.json
  pkg/virt-config/config-map.go
  pkg/virt-config/config_test.go
  pkg/virt-config/virt-config.go
  pkg/virt-handler/cmd-client/client.go
  pkg/virt-handler/vm.go
  pkg/virt-handler/vm_test.go
  pkg/virt-launcher/virtwrap/BUILD.bazel
  pkg/virt-launcher/virtwrap/api/schema.go
  pkg/virt-launcher/virtwrap/cli/generated_mock_libvirt.go
  pkg/virt-launcher/virtwrap/cli/libvirt.go
  pkg/virt-launcher/virtwrap/manager.go
  pkg/virt-launcher/virtwrap/manager_test.go
  pkg/virt-launcher/virtwrap/postcopy.go
  staging/src/kubevirt.io/client-go/api/v1/deepcopy_generated.go
  staging/src/kubevirt.io/client-go/api/v1/openapi_generated.go
  staging/src/kubevirt.io/client-go/api/v1/types.go
  staging/src/kubevirt.io/client-go/api/v1/types_swagger_generated.go
  staging/src/kubevirt.io/client-go/apis/snapshot/v1alpha1/openapi_generated.go
  tests/migration_test.go
Labels: approved, dco-signoff: yes, kind/api-change, lgtm, release-note, size/L

#4252 Validate network interface name
  pkg/virt-api/webhooks/validating-webhook/admitters/vmi-create-admitter.go
  pkg/virt-api/webhooks/validating-webhook/admitters/vmi-create-admitter_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/M

#4274 Fix Datavolume templates revision
  api/openapi-spec/swagger.json
  staging/src/kubevirt.io/client-go/api/v1/deepcopy_generated.go
  staging/src/kubevirt.io/client-go/api/v1/openapi_generated.go
  staging/src/kubevirt.io/client-go/api/v1/types.go
  staging/src/kubevirt.io/client-go/api/v1/types_swagger_generated.go
  staging/src/kubevirt.io/client-go/apis/snapshot/v1alpha1/openapi_generated.go
  tests/operator_test.go
Labels: approved, dco-signoff: yes, kind/api-change, lgtm, release-note-none, size/L

#4074 Pause permissions
  manifests/generated/operator-csv.yaml.in
  manifests/generated/rbac-operator.authorization.k8s.yaml.in
  pkg/virt-operator/creation/rbac/cluster.go
  tests/access_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/M

#4275 Don't discard bazel platform cache on virtctl cross-compilation
  BUILD.bazel
  cmd/virtctl/BUILD.bazel
  hack/bazel-build.sh
Labels: approved, dco-signoff: yes, kind/build-change, lgtm, release-note-none, size/M

#4253 virt-launcher, Fix Guest Agent updates causing an event handling deadlock
  cmd/virt-launcher/virt-launcher.go
  pkg/virt-launcher/notify-client/client.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M

#3879 run tests with kubevirt CR configuration
  api/openapi-spec/swagger.json
  cmd/virt-handler/virt-handler.go
  manifests/testing/kubevirt-config.yaml.in
  pkg/testutils/mock_config.go
  pkg/virt-api/webhooks/validating-webhook/admitters/BUILD.bazel
  pkg/virt-api/webhooks/validating-webhook/admitters/vmi-create-admitter_test.go
  pkg/virt-config/BUILD.bazel
  pkg/virt-config/config-map.go
  pkg/virt-config/config_test.go
  pkg/virt-config/virt-config.go
  pkg/virt-handler/vm.go
  staging/src/kubevirt.io/client-go/api/v1/deepcopy_generated.go
  staging/src/kubevirt.io/client-go/api/v1/openapi_generated.go
  staging/src/kubevirt.io/client-go/api/v1/types.go
  staging/src/kubevirt.io/client-go/apis/snapshot/v1alpha1/openapi_generated.go
  tests/BUILD.bazel
  tests/kubevirt_configmap_test.go
  tests/migration_test.go
  tests/operator_test.go
  tests/reporter/kubernetes.go
  tests/security_features_test.go
  tests/storage_test.go
  tests/utils.go
  tests/vm_test.go
  tests/vmi_configuration_test.go
  tests/vmi_lifecycle_test.go
  tests/vmi_networking_test.go
  tests/vmi_slirp_interface_test.go
  tests/vmidefaults_test.go
Labels: approved, dco-signoff: yes, kind/api-change, lgtm, release-note, size/XXL
