Repository kubevirt/kubevirt, pull requests merged in 2020-01, with the labels that each got.

#2941 Ensure that qemu has attach_queue permissions on tun_socket
  cmd/virt-handler/virt_launcher.cil
  tests/vmi_multiqueue_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/S

#2955 Add Daniel Belenky to reviewers
  OWNERS_ALIASES
  pkg/virt-launcher/virtwrap/api/deepcopy_generated.go
  pkg/virt-launcher/virtwrap/api/zz_generated.defaults.go
  staging/src/kubevirt.io/client-go/api/v1/deepcopy_generated.go
  staging/src/kubevirt.io/client-go/api/v1/openapi_generated.go
  staging/src/kubevirt.io/client-go/api/v1/zz_generated.defaults.go
Labels: approved, dco-signoff: yes, kind/api-change, lgtm, release-note-none, size/S

#2954 remove @ahadas from code-reviewers
  OWNERS_ALIASES
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#2949 Add bump kubevirtci script
  docs/getting-started.md
  hack/bump-kubevirtci.sh
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#2966 Add Igor Bezukh to reviewers
  OWNERS_ALIASES
Labels: approved, dco-signoff: yes, lgtm, needs-ok-to-test, release-note-none, size/XS

#2958 No namespaced owners on non-namespaces resources
  pkg/virt-operator/install-strategy/create.go
  pkg/virt-operator/kubevirt.go
  tests/BUILD.bazel
  tests/operator_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/M

#2945 virt-operator should honor image prefix from previous version
  go.sum
  pkg/virt-operator/kubevirt.go
  pkg/virt-operator/util/config.go
  pkg/virt-operator/util/config_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/L

#2975 Pull in a rules_go version wich works with ginkgo
  .bazelversion
  Makefile
  WORKSPACE
  hack/bazel-generate.sh
  hack/bazel-test.sh
  hack/builder/version.sh
  hack/kubevirt-builder/Dockerfile
  pkg/virt-handler/cmd-client/BUILD.bazel
  vendor/github.com/google/goexpect/BUILD.bazel
  vendor/google.golang.org/grpc/BUILD.bazel
  vendor/google.golang.org/grpc/balancer/BUILD.bazel
  vendor/google.golang.org/grpc/balancer/base/BUILD.bazel
  vendor/google.golang.org/grpc/balancer/roundrobin/BUILD.bazel
  vendor/google.golang.org/grpc/binarylog/grpc_binarylog_v1/BUILD.bazel
  vendor/google.golang.org/grpc/codes/BUILD.bazel
  vendor/google.golang.org/grpc/connectivity/BUILD.bazel
  vendor/google.golang.org/grpc/credentials/BUILD.bazel
  vendor/google.golang.org/grpc/credentials/internal/BUILD.bazel
  vendor/google.golang.org/grpc/encoding/BUILD.bazel
  vendor/google.golang.org/grpc/encoding/proto/BUILD.bazel
  vendor/google.golang.org/grpc/grpclog/BUILD.bazel
  vendor/google.golang.org/grpc/internal/BUILD.bazel
  vendor/google.golang.org/grpc/internal/backoff/BUILD.bazel
  vendor/google.golang.org/grpc/internal/binarylog/BUILD.bazel
  vendor/google.golang.org/grpc/internal/channelz/BUILD.bazel
  vendor/google.golang.org/grpc/internal/envconfig/BUILD.bazel
  vendor/google.golang.org/grpc/internal/grpcrand/BUILD.bazel
  vendor/google.golang.org/grpc/internal/grpcsync/BUILD.bazel
  vendor/google.golang.org/grpc/internal/syscall/BUILD.bazel
  vendor/google.golang.org/grpc/internal/transport/BUILD.bazel
  vendor/google.golang.org/grpc/keepalive/BUILD.bazel
  vendor/google.golang.org/grpc/metadata/BUILD.bazel
  vendor/google.golang.org/grpc/naming/BUILD.bazel
  vendor/google.golang.org/grpc/peer/BUILD.bazel
  vendor/google.golang.org/grpc/resolver/BUILD.bazel
  vendor/google.golang.org/grpc/resolver/dns/BUILD.bazel
  vendor/google.golang.org/grpc/resolver/passthrough/BUILD.bazel
  vendor/google.golang.org/grpc/stats/BUILD.bazel
  vendor/google.golang.org/grpc/status/BUILD.bazel
  vendor/google.golang.org/grpc/tap/BUILD.bazel
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XL

#2968 Add dhiller to kubevirtci approvers
  OWNERS
  OWNERS_ALIASES
  cluster-up/OWNERS
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/S

#2937 Added test for checking wide output for vm/vmi with kubectl/oc
  tests/BUILD.bazel
  tests/kubectl_test.go
  tests/replicaset_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/M

#2983 Add dbelenky and dhiller to approvers
  OWNERS_ALIASES
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#2952 virt-operator to enforce namespace labels
  manifests/generated/operator-csv.yaml.in
  manifests/generated/rbac-operator.authorization.k8s.yaml.in
  pkg/controller/virtinformers.go
  pkg/virt-operator/application.go
  pkg/virt-operator/creation/rbac/operator.go
  pkg/virt-operator/install-strategy/create.go
  pkg/virt-operator/kubevirt.go
  pkg/virt-operator/kubevirt_test.go
  pkg/virt-operator/util/types.go
  staging/src/kubevirt.io/client-go/go.mod
  staging/src/kubevirt.io/client-go/go.sum
  tests/operator_test.go
Labels: approved, dco-signoff: yes, kind/api-change, lgtm, release-note, size/L

#2992 client-python: fix swagger-cli url
  hack/gen-client-python/generate.sh
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#2990 Fix race in operator test suite
  pkg/virt-operator/kubevirt_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#2997 go build should always use vendor mode
  hack/build-go.sh
  hack/build-manifests.sh
  hack/common.sh
  hack/generate.sh
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/S

#2950 Bump to latest kubevirtci that includes ocp-4.3
  automation/test.sh
  cluster-up-sha.txt
  cluster-up/cluster/ephemeral-provider-common.sh
  cluster-up/cluster/images.sh
  cluster-up/cluster/ocp-4.3/README.md
  cluster-up/cluster/ocp-4.3/provider.sh
  cluster-up/version.txt
  hack/cluster-build.sh
  hack/cluster-deploy.sh
  hack/config-default.sh
  hack/functests.sh
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M

#3003 Move containerdisks to their own BUILD file to not download them when just building
  BUILD.bazel
  cmd/container-disk-v2alpha/BUILD.bazel
  containerimages/BUILD.bazel
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/L

#2780 Add Prometheus alert rules for virt-api
  manifests/generated/operator-csv.yaml.in
  manifests/generated/rbac-operator.authorization.k8s.yaml.in
  pkg/controller/virtinformers.go
  pkg/virt-operator/application.go
  pkg/virt-operator/creation/components/crds.go
  pkg/virt-operator/creation/rbac/operator.go
  pkg/virt-operator/install-strategy/create.go
  pkg/virt-operator/install-strategy/delete.go
  pkg/virt-operator/install-strategy/strategy.go
  pkg/virt-operator/kubevirt.go
  pkg/virt-operator/kubevirt_test.go
  pkg/virt-operator/util/client.go
  pkg/virt-operator/util/types.go
  tests/operator_test.go
  tests/utils.go
Labels: approved, dco-signoff: yes, kind/api-change, lgtm, release-note, size/L

#3015 Update doc
  docs/getting-started.md
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#3012 nit: fix typo in failure message
  tests/utils.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#3019 Fix Prometheus alert rules and add CI for it
  .travis.yml
  Makefile
  hack/prom-rule-ci/BUILD.bazel
  hack/prom-rule-ci/rule-spec-dumper.go
  hack/prom-rule-ci/verify-rules.sh
  pkg/virt-operator/creation/components/crds.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/L

#3011 Fix flaky oc tests
  tests/kubectl_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/S

#3016 Use always correct builder image
  .travis.yml
  Makefile
  automation/test.sh
  hack/builder-cache.sh
  hack/builder/Dockerfile
  hack/builder/rsyncd.conf
  hack/builder/version.sh
  hack/common.sh
  hack/dockerized
  hack/kubevirt-builder/Dockerfile
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/L

#3024 Updating the README.md file to align with project state
  README.md
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/S

#3026 Consume the latest kubevirt-ci fixing the kind lane.
  cluster-up-sha.txt
  cluster-up/cluster/images.sh
  cluster-up/cluster/k8s-1.17.0/dev-guide.md
  cluster-up/cluster/kind-k8s-sriov-1.14.2/config_sriov.sh
  cluster-up/cluster/ocp-4.3/provider.sh
  cluster-up/container.sh
  cluster-up/version.txt
  hack/config-default.sh
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/L

#2923 Virt controller alerts
  pkg/virt-controller/watch/BUILD.bazel
  pkg/virt-controller/watch/application.go
  pkg/virt-operator/creation/components/crds.go
  tests/infra_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/L
