Repository kubevirt/kubevirt, pull requests merged in 2020-03, with the labels that each got.

#2827 Guest agent subresource
  api/openapi-spec/swagger.json
  cmd/virt-handler/virt-handler.go
  cmd/virt-launcher/virt-launcher.go
  pkg/handler-launcher-com/cmd/v1/cmd.pb.go
  pkg/handler-launcher-com/cmd/v1/cmd.proto
  pkg/virt-api/api.go
  pkg/virt-api/rest/subresource.go
  pkg/virt-api/rest/subresource_test.go
  pkg/virt-handler/cmd-client/client.go
  pkg/virt-handler/cmd-client/generated_mock_client.go
  pkg/virt-handler/rest/lifecycle.go
  pkg/virt-launcher/notify-client/client.go
  pkg/virt-launcher/virtwrap/agent-poller/agent_parser.go
  pkg/virt-launcher/virtwrap/agent-poller/agent_poller.go
  pkg/virt-launcher/virtwrap/agent-poller/agent_poller_test.go
  pkg/virt-launcher/virtwrap/api/deepcopy_generated.go
  pkg/virt-launcher/virtwrap/api/schema.go
  pkg/virt-launcher/virtwrap/cmd-server/server.go
  pkg/virt-launcher/virtwrap/generated_mock_manager.go
  pkg/virt-launcher/virtwrap/manager.go
  staging/src/kubevirt.io/client-go/api/v1/deepcopy_generated.go
  staging/src/kubevirt.io/client-go/api/v1/openapi_generated.go
  staging/src/kubevirt.io/client-go/api/v1/types.go
  staging/src/kubevirt.io/client-go/api/v1/types_swagger_generated.go
  staging/src/kubevirt.io/client-go/kubecli/BUILD.bazel
  staging/src/kubevirt.io/client-go/kubecli/generated_mock_kubevirt.go
  staging/src/kubevirt.io/client-go/kubecli/handler.go
  staging/src/kubevirt.io/client-go/kubecli/kubevirt.go
  staging/src/kubevirt.io/client-go/kubecli/vmi.go
  staging/src/kubevirt.io/client-go/kubecli/vmi_test.go
  tests/vmi_configuration_test.go
Labels: approved, dco-signoff: yes, kind/api-change, kind/build-change, lgtm, release-note, size/XXL

#3102 Network Setup Optimization
  pkg/virt-handler/vm.go
  pkg/virt-handler/vm_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M

#3014 Add unit tests to cover the migration blocking for bridge network.
  pkg/virt-handler/vm_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/L

#3082 Add test id to BlockUninstallIfWorkloadsExist test
  tests/operator_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#3115 Priority classes
  api/openapi-spec/swagger.json
  examples/non-preemtible.yaml
  examples/preemtible.yaml
  examples/vm-priorityclass.yaml
  pkg/virt-controller/services/template.go
  pkg/virt-controller/services/template_test.go
  staging/src/kubevirt.io/client-go/api/v1/openapi_generated.go
  staging/src/kubevirt.io/client-go/api/v1/types.go
  staging/src/kubevirt.io/client-go/api/v1/types_swagger_generated.go
  tools/vms-generator/BUILD.bazel
  tools/vms-generator/utils/BUILD.bazel
  tools/vms-generator/utils/utils.go
  tools/vms-generator/vms-generator.go
Labels: approved, dco-signoff: yes, kind/api-change, lgtm, needs-ok-to-test, release-note, size/L

#3036 Added a basic feature to rename a stopped vm
  api/openapi-spec/swagger.json
  pkg/virt-api/api.go
  pkg/virt-api/rest/subresource.go
  pkg/virt-api/rest/subresource_test.go
  pkg/virt-api/webhooks/validating-webhook/admitters/vms-admitter.go
  pkg/virt-api/webhooks/validating-webhook/admitters/vms-admitter_test.go
  pkg/virt-controller/watch/BUILD.bazel
  pkg/virt-controller/watch/vm.go
  pkg/virt-controller/watch/vm_test.go
  pkg/virtctl/root.go
  pkg/virtctl/vm/BUILD.bazel
  pkg/virtctl/vm/vm.go
  pkg/virtctl/vm/vm_test.go
  staging/src/kubevirt.io/client-go/api/v1/deepcopy_generated.go
  staging/src/kubevirt.io/client-go/api/v1/types.go
  staging/src/kubevirt.io/client-go/api/v1/types_swagger_generated.go
  staging/src/kubevirt.io/client-go/kubecli/generated_mock_kubevirt.go
  staging/src/kubevirt.io/client-go/kubecli/kubevirt.go
  staging/src/kubevirt.io/client-go/kubecli/vm.go
  staging/src/kubevirt.io/client-go/kubecli/vm_test.go
  tests/vm_test.go
Labels: approved, dco-signoff: yes, kind/api-change, kind/build-change, lgtm, release-note, size/XXL

#3116 Add test id: security features test
  tests/security_features_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#3123 Add fossa.com configuration file
  .fossa.yml
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M

#3125 Ensure labels on our metrics are not being overwritten
  pkg/virt-operator/creation/components/crds.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/XS

#3113 Allow time for config changes to propagate before running tests
  tests/security_features_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/S

#3107 Reject CD-ROM devices that use the virtio bus
  pkg/virt-api/webhooks/validating-webhook/admitters/vmi-create-admitter.go
  pkg/virt-api/webhooks/validating-webhook/admitters/vmi-create-admitter_test.go
  tests/vmi_configuration_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/M

#3053 Check new tests for flakes by running them repeatedly
  automation/repeated_test.sh
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/L

#3139 Add alert for missing virt-handlers
  pkg/virt-operator/creation/components/crds.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/M

#3039 User filesystem list subresource
  api/openapi-spec/swagger.json
  cmd/virt-handler/virt-handler.go
  pkg/handler-launcher-com/cmd/v1/cmd.pb.go
  pkg/handler-launcher-com/cmd/v1/cmd.proto
  pkg/virt-api/api.go
  pkg/virt-api/rest/subresource.go
  pkg/virt-api/rest/subresource_test.go
  pkg/virt-handler/cmd-client/client.go
  pkg/virt-handler/cmd-client/generated_mock_client.go
  pkg/virt-handler/rest/lifecycle.go
  pkg/virt-launcher/virtwrap/agent-poller/agent_parser.go
  pkg/virt-launcher/virtwrap/agent-poller/agent_poller.go
  pkg/virt-launcher/virtwrap/api/schema.go
  pkg/virt-launcher/virtwrap/cmd-server/server.go
  pkg/virt-launcher/virtwrap/cmd-server/server_test.go
  pkg/virt-launcher/virtwrap/generated_mock_manager.go
  pkg/virt-launcher/virtwrap/manager.go
  staging/src/kubevirt.io/client-go/api/v1/deepcopy_generated.go
  staging/src/kubevirt.io/client-go/api/v1/openapi_generated.go
  staging/src/kubevirt.io/client-go/api/v1/types.go
  staging/src/kubevirt.io/client-go/api/v1/types_swagger_generated.go
  staging/src/kubevirt.io/client-go/kubecli/generated_mock_kubevirt.go
  staging/src/kubevirt.io/client-go/kubecli/handler.go
  staging/src/kubevirt.io/client-go/kubecli/kubevirt.go
  staging/src/kubevirt.io/client-go/kubecli/vmi.go
  staging/src/kubevirt.io/client-go/kubecli/vmi_test.go
  tests/vmi_configuration_test.go
Labels: approved, dco-signoff: yes, kind/api-change, lgtm, release-note, size/XXL

#3151 calculate guest memory overhead base on topology and not just cores
  pkg/virt-controller/services/template.go
  pkg/virt-controller/services/template_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M

#3160 Copy apache license to python-client
  hack/gen-client-python/generate.sh
Labels: approved, dco-signoff: yes, lgtm, release-note, size/XS

#3120 build: remove unused variable in dockerized script
  hack/dockerized
Labels: approved, dco-signoff: yes, lgtm, ok-to-test, release-note-none, size/XS

#3155 Move tolerations annotation to pod specs
  manifests/generated/operator-csv.yaml.in
  manifests/generated/virt-api.yaml.in
  manifests/generated/virt-controller.yaml.in
  manifests/generated/virt-handler.yaml.in
  pkg/virt-operator/creation/components/BUILD.bazel
  pkg/virt-operator/creation/components/deployments.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/M

#3090 Device role tagging - Networking
  api/openapi-spec/swagger.json
  pkg/cloud-init/cloud-init.go
  pkg/cloud-init/cloud-init_test.go
  pkg/virt-launcher/virtwrap/manager.go
  pkg/virt-launcher/virtwrap/manager_test.go
  staging/src/kubevirt.io/client-go/api/v1/openapi_generated.go
  staging/src/kubevirt.io/client-go/api/v1/schema.go
  staging/src/kubevirt.io/client-go/api/v1/schema_swagger_generated.go
  tests/BUILD.bazel
  tests/migration_test.go
  tests/vmi_cloudinit_test.go
Labels: approved, dco-signoff: yes, kind/api-change, lgtm, release-note-none, size/L

#3150 relabel the hostImages directory to container_file_t
  images/disks-images-provider/entrypoint.sh
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#3054 Add annotation to place pci addresses on root bus
  pkg/virt-launcher/virtwrap/api/BUILD.bazel
  pkg/virt-launcher/virtwrap/api/converter.go
  pkg/virt-launcher/virtwrap/api/converter_test.go
  pkg/virt-launcher/virtwrap/api/deepcopy_generated.go
  pkg/virt-launcher/virtwrap/api/defaults.go
  pkg/virt-launcher/virtwrap/api/defaults_test.go
  pkg/virt-launcher/virtwrap/api/doc.go
  pkg/virt-launcher/virtwrap/api/pci-placement.go
  pkg/virt-launcher/virtwrap/api/schema.go
  pkg/virt-launcher/virtwrap/api/schema_test.go
  pkg/virt-launcher/virtwrap/api/zz_generated.defaults.go
  pkg/virt-launcher/virtwrap/manager.go
  pkg/virt-launcher/virtwrap/manager_test.go
  pkg/virt-launcher/virtwrap/network/podinterface_test.go
  staging/src/kubevirt.io/client-go/api/v1/types.go
  tests/console_test.go
  tests/migration_test.go
  tests/utils.go
  tests/vm_test.go
  tests/vmi_configuration_test.go
  tests/vmi_headless_test.go
  tests/vmi_multus_test.go
Labels: approved, dco-signoff: yes, kind/api-change, lgtm, release-note-none, size/XXL

#3146 Fix relabeling rules
  pkg/virt-operator/creation/components/crds.go
  tests/BUILD.bazel
  tests/infra_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/L

#3077 Automate things
  Makefile
  hack/autobump-generic.sh
  hack/autobump-kubevirtci.sh
  hack/bump-kubevirtci.sh
  hack/dep-update.sh
  hack/dockerized
  hack/generate.sh
  hack/sync-kubevirtci.sh
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/L

#3101 Fix Prometheus recording rules
  Makefile
  hack/prom-rule-ci/prom-rules-tests.yaml
  hack/prom-rule-ci/verify-rules.sh
  pkg/virt-operator/creation/components/crds.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/L

#3165 Move fetching new tests into function, correct providers
  automation/repeated_test.sh
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M

#3141 Add additional virtctl commands to kubectl wrapper
  cluster-up-sha.txt
  cluster-up/cluster/images.sh
  cluster-up/cluster/k8s-1.17/README.md
  cluster-up/cluster/k8s-provider-common.sh
  cluster-up/kubectl.sh
  cluster-up/version.txt
  hack/config-default.sh
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M

#3185 Fix SR-IOV 1.17 test lane
  automation/test.sh
  cluster-up-sha.txt
  cluster-up/cluster/external/provider.sh
  cluster-up/cluster/images.sh
  cluster-up/cluster/kind-k8s-sriov-1.14.2/README.md
  cluster-up/cluster/kind-k8s-sriov-1.14.2/TROUBLESHOOTING.md
  cluster-up/cluster/kind-k8s-sriov-1.14.2/config_sriov.sh
  cluster-up/cluster/kind-k8s-sriov-1.14.2/manifests/kube-flannel.yaml
  cluster-up/cluster/kind-k8s-sriov-1.14.2/manifests/multus.yaml
  cluster-up/cluster/kind-k8s-sriov-1.14.2/manifests/network_config_policy.yaml
  cluster-up/cluster/kind-k8s-sriov-1.14.2/provider.sh
  cluster-up/cluster/kind-k8s-sriov-1.14.2/sriovdp_setup.sh
  cluster-up/cluster/kind-k8s-sriov-1.17.0/TROUBLESHOOTING.md
  cluster-up/cluster/kind-k8s-sriov-1.17.0/config_sriov.sh
  cluster-up/cluster/kind-k8s-sriov-1.17.0/provider.sh
  cluster-up/cluster/kind/README.md
  cluster-up/cluster/kind/common.sh
  cluster-up/cluster/kind/manifests/kind.yaml
  cluster-up/version.txt
  hack/config-default.sh
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XXL

#3162 Allow a manual adjustment of guest memory overhead
  pkg/virt-api/webhooks/validating-webhook/admitters/vmi-create-admitter.go
  pkg/virt-api/webhooks/validating-webhook/admitters/vmi-create-admitter_test.go
  pkg/virt-controller/services/template.go
  pkg/virt-controller/services/template_test.go
  tests/vmi_configuration_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/L

#3178 Increase memory overhead for VFIO devices
  pkg/virt-controller/services/template.go
  pkg/virt-controller/services/template_test.go
  tests/vmi_multus_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M

#3192 Add functional test to verify core tolerations
  tests/BUILD.bazel
  tests/infra_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/L

#3170 bugfix: Resolve permission mismatch when system default mask is set more restrictive than 022
  cmd/virt-launcher/virt-launcher.go
Labels: approved, dco-signoff: yes, lgtm, ok-to-test, release-note-none, size/XS

#3186 Fix test assertion that could never fail
  tests/vmi_lifecycle_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#3199 Adjust testing code to take proper URL of the files located at the HTTP import server.
  tests/console_test.go
  tests/datavolume_test.go
  tests/migration_test.go
  tests/operator_test.go
  tests/utils.go
  tests/vm_test.go
  tests/vmi_multus_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/M

#2844 Rewrite container-disk main on C to prevent memory overconsumption
  cmd/container-disk-v2alpha/BUILD.bazel
  cmd/container-disk-v2alpha/container_disk_v2alpha_suite_test.go
  cmd/container-disk-v2alpha/main.c
  cmd/container-disk-v2alpha/main.go
  cmd/container-disk-v2alpha/main_test.go
  hack/bazel-test.sh
  hack/build-go.sh
  hack/builder/Dockerfile
  hack/builder/build.sh
  hack/dockerized
Labels: approved, dco-signoff: yes, lgtm, release-note, size/L

#3131 Adapt automation to run propertly cnao providers.
  automation/test.sh
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#3197 Allow generation of manifests with configurable Kubevirt namespace.
  Makefile
  hack/config-default.sh
Labels: approved, dco-signoff: yes, lgtm, release-note, size/XS

#3201 [release-0.26] Increase memory overhead for VFIO devices
  pkg/virt-controller/services/template.go
  pkg/virt-controller/services/template_test.go
  tests/migration_test.go
  tests/vmi_multus_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M

#3163 Check if new VM name is correct when renaming
  pkg/virt-api/webhooks/validating-webhook/admitters/BUILD.bazel
  pkg/virt-api/webhooks/validating-webhook/admitters/vms-admitter.go
  pkg/virt-api/webhooks/validating-webhook/admitters/vms-admitter_test.go
  tests/vm_test.go
  vendor/k8s.io/apimachinery/pkg/api/validation/BUILD.bazel
  vendor/k8s.io/apimachinery/pkg/api/validation/doc.go
  vendor/k8s.io/apimachinery/pkg/api/validation/generic.go
  vendor/k8s.io/apimachinery/pkg/api/validation/objectmeta.go
  vendor/k8s.io/apimachinery/pkg/apis/meta/v1/validation/BUILD.bazel
  vendor/k8s.io/apimachinery/pkg/apis/meta/v1/validation/validation.go
  vendor/modules.txt
Labels: approved, dco-signoff: yes, kind/api-change, lgtm, needs-ok-to-test, release-note-none, size/XL

#3204 [release-0.26] Rewrite container-disk main on C to prevent memory overconsumption
  .bazelversion
  cmd/container-disk-v2alpha/BUILD.bazel
  cmd/container-disk-v2alpha/container_disk_v2alpha_suite_test.go
  cmd/container-disk-v2alpha/main.c
  cmd/container-disk-v2alpha/main.go
  cmd/container-disk-v2alpha/main_test.go
  hack/bazel-test.sh
  hack/build-go.sh
  hack/builder/Dockerfile
  hack/builder/build.sh
  hack/dockerized
Labels: approved, dco-signoff: yes, lgtm, release-note, size/L

#3205 Open and close /dev/net/tun on virt-handler startup
  cmd/virt-handler/virt-handler.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#3210 Small fix of rename condition on VM
  pkg/virt-controller/watch/vm.go
  staging/src/kubevirt.io/client-go/api/v1/types.go
Labels: approved, dco-signoff: yes, kind/api-change, lgtm, release-note, size/XS

#3217 Allow bazel to have custom CA certs
  hack/common.sh
  hack/dockerized
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/S

#3213 Bump kubevirtci
  cluster-up-sha.txt
  cluster-up/cluster/images.sh
  cluster-up/cluster/kind-k8s-1.17.0-ipv6/provider.sh
  cluster-up/cluster/kind/common.sh
  cluster-up/cluster/kind/manifests/local-volume.yaml
  cluster-up/cluster/ocp-4.4/README.md
  cluster-up/version.txt
  hack/config-default.sh
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/L

#3148 Add test cases cdrom
  tests/vmi_configuration_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS
