Repository kubevirt/kubevirt, pull requests merged in 2020-05, with the labels that each got.

#3363 Fix race condition when reporting migration abort status
  pkg/virt-launcher/virtwrap/manager.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#3307 Added testid's for automatic cert renewal long-term tests
  tests/infra_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/S

#3303 Test fixes - dmidecode file was missing on NGINX DL path of the HTTP CDI import server
  WORKSPACE
  images/cdi-http-import-server/BUILD.bazel
  images/cdi-http-import-server/entrypoint.sh
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/S

#3359 Preserve and report stderr from virsh
  tests/utils.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#3348 Adding @AlonaKaplan to code-reviewers
  OWNERS_ALIASES
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#3361 Print stderr from qemu-img if present
  pkg/virt-handler/isolation/validation.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/XS

#3364 Add skip condition for CPUManager=false
  tests/vmi_configuration_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#3338 Add NET_RAW to virt-launcher template
  pkg/virt-controller/services/template.go
  pkg/virt-controller/services/template_test.go
  pkg/virt-operator/creation/components/scc.go
  tests/vmi_networking_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M

#3328 Make default VM IPv6 CIDR human-friendly
  examples/vmi-masquerade.yaml
  pkg/virt-launcher/virtwrap/api/defaults.go
  pkg/virt-launcher/virtwrap/network/common_test.go
  pkg/virt-launcher/virtwrap/network/podinterface_test.go
  tests/utils.go
  tools/vms-generator/utils/utils.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M

#3342 Add networking dev guide
  docs/devel/networking.md
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/L

#3375 Change Targetdirectmigrationnodeports to map[string]int to have valid openapi
  pkg/virt-handler/migration-proxy/migration-proxy.go
  pkg/virt-handler/vm.go
  pkg/virt-handler/vm_test.go
  staging/src/kubevirt.io/client-go/api/v1/deepcopy_generated.go
  staging/src/kubevirt.io/client-go/api/v1/types.go
  tests/migration_test.go
Labels: approved, dco-signoff: yes, kind/api-change, lgtm, release-note-none, size/M

#3377 Minor corrections to architecture document
  docs/architecture.md
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/S

#3373 fixing broken links pointing to the kubevirt doc about the sriov
  docs/sriov.md
Labels: approved, dco-signoff: yes, lgtm, release-note, size/XS

#3378 Add test_id for vmi test
  tests/vmi_configuration_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#3374 Supply virt-launcher an unique UUID for Kind Ipv6
  tests/BUILD.bazel
  tests/utils.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M

#3380 Add test cases ids
  tests/console_test.go
  tests/infra_test.go
  tests/kubectl_test.go
  tests/migration_test.go
  tests/replicaset_test.go
  tests/vm_test.go
  tests/vmi_configuration_test.go
  tests/vmi_iothreads_test.go
  tests/vmi_lifecycle_test.go
  tests/vmidefaults_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M

#3351 operator - Pass kubernetes service host and port
  pkg/virt-operator/application.go
  pkg/virt-operator/creation/components/deployments.go
  pkg/virt-operator/install-strategy/create_test.go
  pkg/virt-operator/install-strategy/strategy.go
  pkg/virt-operator/kubevirt.go
  pkg/virt-operator/kubevirt_test.go
  pkg/virt-operator/util/BUILD.bazel
  pkg/virt-operator/util/config.go
  pkg/virt-operator/util/config_test.go
Labels: approved, dco-signoff: yes, kind/build-change, lgtm, release-note, size/L

#3320 Remove DataVolume restart logic
  pkg/virt-controller/watch/BUILD.bazel
  pkg/virt-controller/watch/vm.go
  pkg/virt-controller/watch/vm_test.go
  tests/datavolume_test.go
  tests/utils.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/L

#3388 docs: add CAP_NET_RAW to the capability list
  docs/devel/networking.md
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#3391 Add missing cleanup to certificate tests
  tests/infra_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#3371 Fix the virt-launcher custom policy and use it to solve SELinux denials
  cmd/virt-handler/virt-handler.go
  cmd/virt-handler/virt_launcher.cil
  manifests/testing/kubevirt-config.yaml.in
  pkg/virt-controller/services/template.go
  pkg/virt-controller/services/template_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/M

#3372 Update fedora img to fc32
  BUILD.bazel
  WORKSPACE
  containerimages/BUILD.bazel
  pkg/virt-launcher/virtwrap/manager.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/M

#3357 Kube openapi for openapi spec
  api/openapi-spec/swagger.json
  go.mod
  pkg/util/openapi/BUILD.bazel
  pkg/util/openapi/openapi.go
  pkg/virt-api/BUILD.bazel
  pkg/virt-api/api.go
  pkg/virt-api/rest/definitions.go
  pkg/virt-api/webhooks/validating-webhook/admitters/vms-admitter_test.go
  staging/src/kubevirt.io/client-go/api/v1/BUILD.bazel
  staging/src/kubevirt.io/client-go/api/v1/openapi_generated.go
  staging/src/kubevirt.io/client-go/api/v1/schema.go
  staging/src/kubevirt.io/client-go/api/v1/schema_swagger_generated.go
  staging/src/kubevirt.io/client-go/api/v1/types.go
  staging/src/kubevirt.io/client-go/api/v1/types_swagger_generated.go
  vendor/k8s.io/kube-openapi/pkg/builder/BUILD.bazel
  vendor/k8s.io/kube-openapi/pkg/builder/doc.go
  vendor/k8s.io/kube-openapi/pkg/builder/openapi.go
  vendor/k8s.io/kube-openapi/pkg/builder/util.go
  vendor/k8s.io/kube-openapi/pkg/util/BUILD.bazel
  vendor/k8s.io/kube-openapi/pkg/util/trie.go
  vendor/k8s.io/kube-openapi/pkg/util/util.go
  vendor/modules.txt
Labels: approved, dco-signoff: yes, kind/api-change, lgtm, release-note-none, size/XXL

#3249 Ipv6 fix http readiness probe
  tests/probes_test.go
  tests/utils.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M

#3319 Flakey test 3468 fix
  tests/vm_watch_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/L

#3110 Annotation propagation
  pkg/virt-controller/services/template.go
  pkg/virt-controller/services/template_test.go
  pkg/virt-controller/watch/vm.go
  pkg/virt-controller/watch/vm_test.go
  staging/src/kubevirt.io/client-go/api/v1/types.go
  tests/vm_test.go
  tests/vmi_lifecycle_test.go
Labels: approved, dco-signoff: yes, kind/api-change, lgtm, needs-ok-to-test, release-note-none, size/L

#3408 Add omeryahud to code reviewers
  OWNERS_ALIASES
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#3423 Fix edge case in cgroup file parsing
  pkg/virt-handler/isolation/isolation.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#3419 Fix an EnvVar map equivalence test
  pkg/virt-operator/util/config_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#3079 Add secureBoot EFI flag
  api/openapi-spec/swagger.json
  cmd/virt-launcher/virt-launcher.go
  pkg/virt-api/webhooks/validating-webhook/admitters/vmi-create-admitter.go
  pkg/virt-config/config-map.go
  pkg/virt-config/config_test.go
  pkg/virt-config/virt-config.go
  pkg/virt-controller/services/template.go
  pkg/virt-controller/services/template_test.go
  pkg/virt-launcher/virtwrap/api/converter.go
  pkg/virt-launcher/virtwrap/api/converter_test.go
  pkg/virt-launcher/virtwrap/manager.go
  pkg/virt-launcher/virtwrap/manager_test.go
  staging/src/kubevirt.io/client-go/api/v1/deepcopy_generated.go
  staging/src/kubevirt.io/client-go/api/v1/openapi_generated.go
  staging/src/kubevirt.io/client-go/api/v1/schema.go
  staging/src/kubevirt.io/client-go/api/v1/schema_swagger_generated.go
Labels: approved, dco-signoff: yes, kind/api-change, lgtm, release-note, size/L

#3413 travis-ci: Fail on first error in script
  .travis.yml
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#3397 Fixed typo in CONTRIBUTING.md
  CONTRIBUTING.md
Labels: approved, dco-signoff: yes, lgtm, ok-to-test, release-note-none, size/XS

#3418 Disable 2 flaky functional tests
  tests/infra_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#3422 Preparing kubevirt to make the ipv6 lane mandatory
  tests/migration_test.go
  tests/pausing_test.go
  tests/utils.go
  tests/vmi_configuration_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/S

#3286 Cloud-Init network data referenced by NetworkDataSecretRef does not work
  pkg/virt-controller/services/template.go
  pkg/virt-controller/services/template_test.go
  tests/vmi_cloudinit_test.go
Labels: approved, dco-signoff: yes, lgtm, ok-to-test, release-note, size/L

#3387 Remove @dshchedr from the list of test-reviewers
  OWNERS_ALIASES
Labels: approved, dco-signoff: yes, lgtm, needs-ok-to-test, release-note-none, size/XS

#3438 Add missing roles to csv-generator
  manifests/generated/operator-csv.yaml.in
  pkg/virt-operator/creation/csv/csv.go
  pkg/virt-operator/creation/rbac/operator.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M

#3437 virt-operator, tests: Fix equality of slices
  pkg/virt-operator/util/config_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#3441 Minor fixes to documentation
  CONTRIBUTING.md
  docs/getting-started.md
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/S

#3439 Sriov reporter
  automation/test.sh
  tests/reporter/kubernetes.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M

#3427 Add virt-handler flag for kubelet pod path
  cmd/virt-handler/BUILD.bazel
  cmd/virt-handler/virt-handler.go
  pkg/container-disk/container-disk.go
  pkg/util/util.go
Labels: approved, dco-signoff: yes, kind/build-change, lgtm, release-note-none, size/S

#3429 functest: Fix VMI IPv6 configuration
  tests/migration_test.go
  tests/pausing_test.go
  tests/utils.go
  tests/vmi_configuration_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/S

#3447 RFC: automation: use a constant ginkgo seed
  automation/test.sh
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#3414 Fix inconsistency in VM CRD CLI output
  pkg/virt-operator/creation/components/crds.go
  tests/kubectl_test.go
  tests/vm_watch_test.go
Labels: approved, dco-signoff: yes, kind/api-change, lgtm, release-note-none, size/M

#3431 Add prow KUBEVIRT_LANE_FOCUS support
  automation/test.sh
  docs/ci.md
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M

#3392 Fix IPv6 migration
  pkg/virt-handler/migration-proxy/BUILD.bazel
  pkg/virt-handler/migration-proxy/migration-proxy.go
  tests/migration_test.go
  tests/utils.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M

#3344 Explain bridge bind mechanism
  docs/devel/networking.md
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/L

#3462 Revert node-labeller
  cmd/virt-handler/virt-handler.go
  cmd/virt-launcher/BUILD.bazel
  cmd/virt-launcher/node-labeller/node-labeller.sh
  manifests/generated/operator-csv.yaml.in
  manifests/generated/rbac-operator.authorization.k8s.yaml.in
  pkg/virt-handler/BUILD.bazel
  pkg/virt-handler/device-manager/device_controller.go
  pkg/virt-handler/device-manager/device_controller_test.go
  pkg/virt-handler/node-labeller/BUILD.bazel
  pkg/virt-handler/node-labeller/config.go
  pkg/virt-handler/node-labeller/config_test.go
  pkg/virt-handler/node-labeller/cpu_plugin.go
  pkg/virt-handler/node-labeller/cpu_plugin_test.go
  pkg/virt-handler/node-labeller/model.go
  pkg/virt-handler/node-labeller/node_labeller.go
  pkg/virt-handler/node-labeller/node_labeller_suite_test.go
  pkg/virt-handler/node-labeller/node_labeller_test.go
  pkg/virt-handler/node-labeller/test-util.go
  pkg/virt-handler/vm.go
  pkg/virt-handler/vm_test.go
  pkg/virt-operator/creation/components/BUILD.bazel
  pkg/virt-operator/creation/components/config_maps.go
  pkg/virt-operator/creation/components/deployments.go
  pkg/virt-operator/creation/rbac/handler.go
  pkg/virt-operator/creation/rbac/operator.go
  pkg/virt-operator/install-strategy/strategy.go
  pkg/virt-operator/kubevirt.go
  pkg/virt-operator/kubevirt_test.go
  tests/infra_test.go
  tests/utils.go
  tests/vmi_lifecycle_test.go
Labels: approved, dco-signoff: yes, kind/bug, kind/build-change, lgtm, release-note, size/XXL

#3460 Add masquerade ipv4 cidr test + refactor
  tests/vmi_networking_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/L

#3434 Fix tests which are related to cpu model / features
  tests/utils.go
  tests/vmi_configuration_test.go
  tests/vmi_lifecycle_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M

#3456 Use virtio in tests where the disk order matters
  tests/config_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/S

#3465 remove unused const value
  pkg/virt-handler/cmd-client/client.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#3463 Fixing Getting Started Guide since it pointed to an older version of KUBEVIRT_PROVIDER
  docs/getting-started.md
Labels: approved, dco-signoff: yes, lgtm, needs-ok-to-test, release-note-none, size/S

#3459 fix tiny typo
  tests/vmi_slirp_interface_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#3384 Adding @rnetser to the list of test-reviewers
  OWNERS_ALIASES
Labels: approved, dco-signoff: yes, do-not-merge/invalid-owners-file, lgtm, needs-ok-to-test, release-note-none, size/XS

#3412 build: Only build container-disk as a static binary
  hack/build-go.sh
Labels: approved, dco-signoff: yes, lgtm, needs-ok-to-test, release-note-none, size/S

#3228 Add functional tests using NFS as backing store
  tests/migration_test.go
  tests/storage_test.go
  tests/utils.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/L

#3395 Explain masquerade bind mechanism
  docs/devel/networking.md
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/L

#3478 Set proper architecture label in generated container images
  WORKSPACE
  cmd/example-cloudinit-hook-sidecar/BUILD.bazel
  cmd/example-hook-sidecar/BUILD.bazel
  cmd/subresource-access-test/BUILD.bazel
  cmd/virt-api/BUILD.bazel
  cmd/virt-controller/BUILD.bazel
  cmd/virt-handler/BUILD.bazel
  cmd/virt-launcher/BUILD.bazel
  cmd/virt-operator/BUILD.bazel
  containerimages/BUILD.bazel
  images/cdi-http-import-server/BUILD.bazel
  images/disks-images-provider/BUILD.bazel
  images/nfs-server/BUILD.bazel
  images/vm-killer/BUILD.bazel
  images/winrmcli/BUILD.bazel
Labels: approved, dco-signoff: yes, kind/build-change, lgtm, ok-to-test, release-note-none, size/M

#3483 Report IPs list for pod network
  api/openapi-spec/swagger.json
  pkg/virt-controller/watch/vmi.go
  pkg/virt-controller/watch/vmi_test.go
  staging/src/kubevirt.io/client-go/api/v1/openapi_generated.go
  staging/src/kubevirt.io/client-go/api/v1/types.go
  staging/src/kubevirt.io/client-go/api/v1/types_swagger_generated.go
  tests/vmi_networking_test.go
Labels: approved, dco-signoff: yes, kind/api-change, kind/bug, lgtm, release-note, size/M, topic/network

#3452 Improve lane selection for repeated tests
  automation/repeated_test.sh
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M
