Repository kubevirt/kubevirt, pull requests merged in 2020-04, with the labels that each got.

#3216 Do not set an SELinux type on virt-launcher by default
  pkg/virt-controller/services/template.go
  pkg/virt-controller/services/template_test.go
  tests/security_features_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M

#3200 Disable ppc64 builds until we have it under control again
  .travis.yml
Labels: dco-signoff: yes, release-note-none, size/XS

#3232 docs: fix ADD destination in container-register-disks
  docs/container-register-disks.md
Labels: approved, dco-signoff: yes, lgtm, release-note, size/XS

#3240 tests: increase nc idle and wait timeouts
  tests/utils.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#3235 Use the selinux enables k8s-1.17 lane
  cluster-up-sha.txt
  cluster-up/cluster/images.sh
  cluster-up/cluster/k8s-genie-1.11.1/README.md
  cluster-up/cluster/k8s-genie-1.11.1/provider.sh
  cluster-up/cluster/k8s-provider-common.sh
  cluster-up/version.txt
  hack/config-default.sh
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M

#3243 [release-0.26] tests: increase nc idle and wait timeouts
  tests/utils.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#3237 Silence compilation warning on container-disk
  cmd/container-disk-v2alpha/main.c
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#3229 Avoid setting SELinuxOptions on virt-launcher when no type is specified
  pkg/virt-controller/services/template.go
  pkg/virt-controller/services/template_test.go
  tests/security_features_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/S

#3238 Increase the amount of memory used by stress to delay migrations
  tests/migration_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#3236 Set kubevirt priority class on all core components
  hack/generate.sh
  manifests/generated/kubevirt-priority-class.yaml
  manifests/generated/operator-csv.yaml.in
  manifests/generated/virt-api.yaml.in
  manifests/generated/virt-controller.yaml.in
  manifests/generated/virt-handler.yaml.in
  manifests/release/kubevirt-operator.yaml.in
  manifests/release/kubevirt.yaml.in
  manifests/release/olm/kubevirt-csv-preconditions.yaml.in
  pkg/virt-operator/creation/components/BUILD.bazel
  pkg/virt-operator/creation/components/crds.go
  pkg/virt-operator/creation/components/deployments.go
  tools/manifest-templator/manifest-templator.go
  tools/resource-generator/resource-generator.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/M

#3124 Make containerDisk work with different filesystem backends
  pkg/virt-handler/container-disk/mount.go
  pkg/virt-handler/isolation/isolation.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/XS

#3158 Elaborate on VM resource in architecture document
  docs/architecture.md
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/S

#3245 docs: correct the links on the images README
  images/README.md
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#3112 Support ipv6 masquarade
  automation/test.sh
  examples/vmi-masquerade.yaml
  images/cdi-http-import-server/nginx.conf
  pkg/virt-launcher/virtwrap/api/defaults.go
  pkg/virt-launcher/virtwrap/network/BUILD.bazel
  pkg/virt-launcher/virtwrap/network/common.go
  pkg/virt-launcher/virtwrap/network/common_test.go
  pkg/virt-launcher/virtwrap/network/generated_mock_common.go
  pkg/virt-launcher/virtwrap/network/network.go
  pkg/virt-launcher/virtwrap/network/podinterface.go
  pkg/virt-launcher/virtwrap/network/podinterface_test.go
  staging/src/kubevirt.io/client-go/kubecli/BUILD.bazel
  staging/src/kubevirt.io/client-go/kubecli/handler.go
  tests/BUILD.bazel
  tests/config_test.go
  tests/expose_test.go
  tests/imageupload_test.go
  tests/infra_test.go
  tests/migration_test.go
  tests/probes_test.go
  tests/storage_test.go
  tests/utils.go
  tests/vmi_configuration_test.go
  tests/vmi_multus_test.go
  tests/vmi_networking_test.go
  tools/vms-generator/utils/utils.go
  vendor/k8s.io/utils/net/BUILD.bazel
  vendor/k8s.io/utils/net/ipnet.go
  vendor/k8s.io/utils/net/net.go
  vendor/modules.txt
Labels: approved, dco-signoff: yes, lgtm, release-note, size/XXL

#3230 Skip test run for flake lane for too many tests
  automation/repeated_test.sh
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/S

#3250 Bump Kubevirtci to align with Kind ipv6 migration support
  cluster-up-sha.txt
  cluster-up/cluster/kind-k8s-1.17.0-ipv6/provider.sh
  cluster-up/version.txt
  hack/config-default.sh
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/S

#3256 Skip tests requiring CPU manager if feature gate is disabled
  pkg/virt-config/feature-gates.go
  tests/vmi_configuration_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#3252 Migration tests - use proper node drain key
  pkg/virt-config/config-map.go
  tests/migration_test.go
  tests/utils.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M

#3248 Open and close /dev/vhost-net on virt-handler startup
  cmd/virt-handler/virt-handler.go
  pkg/virt-handler/device-manager/device_controller.go
  pkg/virt-handler/device-manager/generic_device.go
  pkg/virt-handler/device-manager/generic_device_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/S

#3261 Cleanup finalized vmi once domain is down.
  pkg/virt-handler/vm.go
  pkg/virt-handler/vm_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/S

#3262 Fix fedora container-disk in template tests
  examples/vm-template-fedora.yaml
  tests/template_test.go
  tools/vms-generator/utils/utils.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M

#3206 Drop support for Genie networks
  api/openapi-spec/swagger.json
  automation/repeated_test.sh
  automation/test.sh
  examples/vmi-genie-multiple-net.yaml
  examples/vmi-genie-ptp.yaml
  pkg/virt-api/webhooks/validating-webhook/admitters/vmi-create-admitter.go
  pkg/virt-api/webhooks/validating-webhook/admitters/vmi-create-admitter_test.go
  pkg/virt-controller/services/template.go
  pkg/virt-controller/services/template_test.go
  pkg/virt-launcher/virtwrap/api/converter.go
  pkg/virt-launcher/virtwrap/api/converter_test.go
  pkg/virt-launcher/virtwrap/network/network.go
  pkg/virt-launcher/virtwrap/network/network_test.go
  staging/src/kubevirt.io/client-go/api/v1/deepcopy_generated.go
  staging/src/kubevirt.io/client-go/api/v1/openapi_generated.go
  staging/src/kubevirt.io/client-go/api/v1/schema.go
  staging/src/kubevirt.io/client-go/api/v1/schema_swagger_generated.go
  tests/BUILD.bazel
  tests/vmi_genie_test.go
  tools/vms-generator/utils/utils.go
  tools/vms-generator/vms-generator.go
Labels: approved, dco-signoff: yes, kind/api-change, lgtm, release-note, size/XL

#3233 Check the backing image file system directIO support
  pkg/virt-launcher/virtwrap/api/converter.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#3271 Fix size checks in storage test
  tests/storage_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/S

#3272 Make kubectl related tests more reliable
  tests/kubectl_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/S

#2842 sync VMI guest time after a successful migration
  pkg/handler-launcher-com/cmd/v1/cmd.pb.go
  pkg/handler-launcher-com/cmd/v1/cmd.proto
  pkg/virt-handler/cmd-client/client.go
  pkg/virt-handler/cmd-client/generated_mock_client.go
  pkg/virt-handler/vm.go
  pkg/virt-handler/vm_test.go
  pkg/virt-launcher/virtwrap/cli/generated_mock_libvirt.go
  pkg/virt-launcher/virtwrap/cli/libvirt.go
  pkg/virt-launcher/virtwrap/cmd-server/server.go
  pkg/virt-launcher/virtwrap/generated_mock_manager.go
  pkg/virt-launcher/virtwrap/manager.go
  pkg/virt-launcher/virtwrap/manager_test.go
  tests/migration_test.go
Labels: approved, dco-signoff: yes, kind/api-change, lgtm, release-note-none, size/L

#3270 Fix an erroneous comparison in CPUManager test
  tests/vmi_configuration_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#3274 Ensure each permissions test uses a random user account
  tests/vm_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#3277 Fix flaky comparison to VM phase
  tests/vm_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/S

#3288 [Release-0.26] Disable ppc64 builds until we have it under control again
  .travis.yml
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#3292 VMI configuration tests - Clear SMBIOS test data from configmap when the test ends
  tests/utils.go
  tests/vmi_configuration_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/S

#3287 [Release-0.26] Migration tests - use proper node drain key
  pkg/virt-config/config-map.go
  tests/migration_test.go
  tests/utils.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M

#3209 Add unsupported GA condition to vmi
  pkg/virt-config/config-map.go
  pkg/virt-config/config_test.go
  pkg/virt-config/virt-config.go
  pkg/virt-handler/vm.go
  pkg/virt-handler/vm_test.go
  staging/src/kubevirt.io/client-go/api/v1/types.go
  tests/vmi_configuration_test.go
Labels: approved, dco-signoff: yes, kind/api-change, lgtm, release-note, size/L

#3294 [release-0.26] Clear KubeVirt configmap after testing custom SMBIOS settings.
  tests/utils.go
  tests/vmi_configuration_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/S

#3265 Remove VMI ready condition when the pod is finalized
  pkg/virt-controller/watch/vmi.go
  pkg/virt-controller/watch/vmi_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/S

#3300 Ensure that tests pick the right VMI pod after migrations
  tests/utils.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/S

#3298 Add Jed to code-reviewers
  OWNERS_ALIASES
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#3283 add configmap iso support for Windows (i.e. sysprep support)
  pkg/config/config.go
Labels: approved, dco-signoff: yes, lgtm, needs-ok-to-test, release-note, size/XS

#3259 Ignore deleted test files when checking for changes in test folder
  automation/repeated_test.sh
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#3258 Support setting custom schedulers on VMIs
  api/openapi-spec/swagger.json
  pkg/virt-controller/services/template.go
  pkg/virt-controller/services/template_test.go
  staging/src/kubevirt.io/client-go/api/v1/defaults_test.go
  staging/src/kubevirt.io/client-go/api/v1/openapi_generated.go
  staging/src/kubevirt.io/client-go/api/v1/schema_test.go
  staging/src/kubevirt.io/client-go/api/v1/types.go
  staging/src/kubevirt.io/client-go/api/v1/types_swagger_generated.go
  tests/vmi_configuration_test.go
Labels: approved, dco-signoff: yes, kind/api-change, lgtm, release-note, size/M

#3297 Make operator readiness probe pass without KubeVirt CR present
  pkg/certificates/bootstrap/BUILD.bazel
  pkg/certificates/bootstrap/cert-manager.go
  pkg/certificates/bootstrap/cert-manager_test.go
  pkg/virt-operator/application.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M

#3301 Allow setting custom volume labels for configmap and secret volumes
  api/openapi-spec/swagger.json
  pkg/config/config-map.go
  pkg/config/config.go
  pkg/config/config_test.go
  pkg/config/secret.go
  pkg/config/service-account.go
  staging/src/kubevirt.io/client-go/api/v1/openapi_generated.go
  staging/src/kubevirt.io/client-go/api/v1/schema.go
  staging/src/kubevirt.io/client-go/api/v1/schema_swagger_generated.go
  tests/config_test.go
  tests/migration_test.go
  tests/utils.go
Labels: approved, dco-signoff: yes, kind/api-change, lgtm, release-note, size/L

#3302 Compile functests with go test -c
  hack/common.sh
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#3305 Skip three flaky tests
  tests/infra_test.go
  tests/migration_test.go
  tests/vm_watch_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#3191 Test sriov ipv6 ping
  tests/vmi_multus_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/S

#3276 Use the dedicated container_file_t tmpfs for tests
  cluster-up-sha.txt
  cluster-up/cluster/images.sh
  cluster-up/cluster/k8s-multus-1.13.3/README.md
  cluster-up/cluster/k8s-multus-1.13.3/provider.sh
  cluster-up/version.txt
  hack/config-default.sh
  tests/storage_test.go
  tests/utils.go
  tests/vmi_configuration_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M

#3143 Change to kubevirt builder
  hack/ci/Dockerfile.ci
  hack/ci/Dockerfile.ci-pr
  hack/ci/build.sh
  hack/ci/test.sh
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M

#3326 Use kubevirt-builder in Dockerfile.ci
  hack/ci/Dockerfile.ci
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/L

#3316 docs: Add virt-api to the architecture diagram
  docs/architecture.png
  docs/architecture.svg
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/L

#3222 Allow developer to 'make push' subset of images
  Makefile
  hack/bazel-push-images.sh
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#3315 Fix tests relying on bearer token behavior
  tests/vm_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M

#3291 Use the correct DNS service name for OKD clusters
  tests/utils.go
Labels: approved, dco-signoff: yes, lgtm, ok-to-test, release-note-none, size/XS

#3335 Fix unsupported agent condition flapping and resolve source of flaky tests.
  pkg/virt-controller/watch/vmi.go
  pkg/virt-handler/vm.go
  pkg/virt-handler/vm_test.go
  tests/migration_test.go
  tests/vm_watch_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M

#3334 Avoid unusable taints in test suite
  tests/migration_test.go
  tests/utils.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/S

#3176 Copy 'Ready' condition from VMI to VM
  pkg/controller/conditions.go
  pkg/controller/conditions_test.go
  pkg/virt-controller/watch/vm.go
  pkg/virt-controller/watch/vm_test.go
  staging/src/kubevirt.io/client-go/api/v1/types.go
  tests/vm_test.go
Labels: approved, dco-signoff: yes, kind/api-change, lgtm, ok-to-test, release-note, size/L

#3133 move node-labeller and cpu plugin from ssp operator into kubevirt
  cmd/virt-handler/virt-handler.go
  cmd/virt-launcher/BUILD.bazel
  cmd/virt-launcher/node-labeller/node-labeller.sh
  manifests/generated/operator-csv.yaml.in
  manifests/generated/rbac-operator.authorization.k8s.yaml.in
  pkg/virt-handler/BUILD.bazel
  pkg/virt-handler/device-manager/device_controller.go
  pkg/virt-handler/device-manager/device_controller_test.go
  pkg/virt-handler/node-labeller/BUILD.bazel
  pkg/virt-handler/node-labeller/config.go
  pkg/virt-handler/node-labeller/config_test.go
  pkg/virt-handler/node-labeller/cpu_plugin.go
  pkg/virt-handler/node-labeller/cpu_plugin_test.go
  pkg/virt-handler/node-labeller/model.go
  pkg/virt-handler/node-labeller/node_labeller.go
  pkg/virt-handler/node-labeller/node_labeller_suite_test.go
  pkg/virt-handler/node-labeller/node_labeller_test.go
  pkg/virt-handler/node-labeller/test-util.go
  pkg/virt-handler/vm.go
  pkg/virt-handler/vm_test.go
  pkg/virt-operator/creation/components/BUILD.bazel
  pkg/virt-operator/creation/components/config_maps.go
  pkg/virt-operator/creation/components/deployments.go
  pkg/virt-operator/creation/rbac/handler.go
  pkg/virt-operator/creation/rbac/operator.go
  pkg/virt-operator/install-strategy/create.go
  pkg/virt-operator/install-strategy/strategy.go
  pkg/virt-operator/install-strategy/strategy_test.go
  pkg/virt-operator/kubevirt.go
  pkg/virt-operator/kubevirt_test.go
  tests/infra_test.go
  tests/utils.go
  tests/vmi_lifecycle_test.go
Labels: approved, dco-signoff: yes, kind/build-change, lgtm, release-note, size/XXL

#3325 Bump to latest kubevirtci with hugepages enabled
  cluster-up-sha.txt
  cluster-up/cluster/images.sh
  cluster-up/version.txt
  hack/config-default.sh
  pkg/virt-api/webhooks/validating-webhook/admitters/vmi-create-admitter.go
  pkg/virt-api/webhooks/validating-webhook/admitters/vmi-create-admitter_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M

#3340 Add a static label to virt-operator job podspec
  pkg/virt-operator/kubevirt.go
  pkg/virt-operator/kubevirt_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/S

#3313 Fix the testid for Should honor custom SELinux type for virt-launcher
  tests/security_features_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#3346 CONTRIBUTING: Spelling fix, propoals -> proposals
  CONTRIBUTING.md
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#3352 Add test ids for SR-IOV tests
  tests/vmi_multus_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#3345 CONTRIBUTING: Add a procedure for joining the organization
  CONTRIBUTING.md
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/S

#3063 virt-handler should only update guest-agent details if interface doesn't have masquerade binding
  pkg/virt-handler/vm.go
  tests/vmi_configuration_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/M
