Repository kubevirt/kubevirt, pull requests merged in 2020-06, with the labels that each got.

#3482 Fix potentially infinite loop in build scripts
  hack/cluster-build.sh
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/S

#3498 Revert node-labeller from master
  cmd/virt-handler/virt-handler.go
  cmd/virt-launcher/BUILD.bazel
  cmd/virt-launcher/node-labeller/node-labeller.sh
  manifests/generated/operator-csv.yaml.in
  manifests/generated/rbac-operator.authorization.k8s.yaml.in
  pkg/virt-handler/BUILD.bazel
  pkg/virt-handler/device-manager/device_controller.go
  pkg/virt-handler/device-manager/device_controller_test.go
  pkg/virt-handler/node-labeller/BUILD.bazel
  pkg/virt-handler/node-labeller/config.go
  pkg/virt-handler/node-labeller/config_test.go
  pkg/virt-handler/node-labeller/cpu_plugin.go
  pkg/virt-handler/node-labeller/cpu_plugin_test.go
  pkg/virt-handler/node-labeller/model.go
  pkg/virt-handler/node-labeller/node_labeller.go
  pkg/virt-handler/node-labeller/node_labeller_suite_test.go
  pkg/virt-handler/node-labeller/node_labeller_test.go
  pkg/virt-handler/node-labeller/test-util.go
  pkg/virt-handler/vm.go
  pkg/virt-handler/vm_test.go
  pkg/virt-operator/creation/components/BUILD.bazel
  pkg/virt-operator/creation/components/config_maps.go
  pkg/virt-operator/creation/components/deployments.go
  pkg/virt-operator/creation/rbac/handler.go
  pkg/virt-operator/creation/rbac/operator.go
  pkg/virt-operator/install-strategy/strategy.go
  pkg/virt-operator/kubevirt.go
  pkg/virt-operator/kubevirt_test.go
  tests/infra_test.go
  tests/utils.go
  tests/vmi_lifecycle_test.go
Labels: approved, dco-signoff: yes, kind/build-change, lgtm, release-note-none, size/XXL

#3497 Collect infra logs from infra containers to debug CI failures
  automation/test.sh
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/S

#3268 Bump libvirt to 6.0.0
  WORKSPACE
  tests/vmi_lifecycle_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/XS

#3399 Add missing SELinux permission for SR-IOV
  cmd/virt-handler/virt_launcher.cil
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#3491 travis-ci: Extract the script to an external file
  .travis.yml
  automation/travisci-test.sh
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M

#3511 revert cpu model / feature tests
  tests/utils.go
  tests/vmi_configuration_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M

#3468 Bump timeouts used in test.
  tests/datavolume_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#3467 [release-0.29] Fix inconsistency in VM CRD CLI output
  pkg/virt-operator/creation/components/crds.go
  tests/kubectl_test.go
  tests/vm_watch_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M

#3487 kubevirtci bump
  cluster-up-sha.txt
  cluster-up/cluster/images.sh
  cluster-up/cluster/k8s-1.18/README.md
  cluster-up/cluster/k8s-1.18/dev-guide.md
  cluster-up/cluster/k8s-1.18/provider.sh
  cluster-up/cluster/kind-k8s-1.17/README.md
  cluster-up/cluster/kind-k8s-1.17/provider.sh
  cluster-up/version.txt
  hack/config-default.sh
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/L

#3514 Build and test vs kubevirt pr
  hack/ci/Dockerfile.ci
  hack/ci/Dockerfile.ci-pr
  hack/ci/build-pr.sh
  hack/ci/build.sh
  hack/ci/resources/docker-registry.yaml
  hack/ci/test-pr.sh
  hack/ci/test.sh
Labels: dco-signoff: yes, lgtm, release-note-none, size/L

#3501 docs: explain masquerade bind mechanism for ipv6
  docs/devel/networking.md
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M

#3314 Create loop devices on kubevirtci test nodes
  hack/cluster-deploy.sh
  manifests/testing/disks-images-provider.yaml.in
  tests/config_test.go
  tests/storage_test.go
  tests/utils.go
  tests/vmi_configuration_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M

#3470 Add a functional test and example VMI for EFI Secure Boot
  BUILD.bazel
  WORKSPACE
  containerimages/BUILD.bazel
  examples/vmi-secureboot.yaml
  tests/utils.go
  tests/vmi_configuration_test.go
  tools/vms-generator/utils/utils.go
  tools/vms-generator/vms-generator.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/L

#3503 Add make focus target to ease lane focusing
  Makefile
  docs/ci.md
  hack/focus.sh
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M

#3516 Cleanup a couple of leftover tmp dirs in tests
  tests/storage_test.go
  tests/vmi_configuration_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#3520 Don't override virt-handler status updates in scheduled state
  pkg/virt-controller/watch/vmi.go
  pkg/virt-controller/watch/vmi_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/S

#3526 Fix flaky pause/unpause test
  tests/pausing_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/S

#3469 Minimize the scope of KUBEVIRT_POSTINBOUND chain
  pkg/virt-launcher/virtwrap/network/podinterface.go
  pkg/virt-launcher/virtwrap/network/podinterface_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#3454 Ipv6 config via cloud init network data
  examples/vmi-masquerade.yaml
  tests/utils.go
  tools/vms-generator/utils/utils.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M

#3455 Use KubeVirt CR to store configuration
  cmd/virt-handler/virt-handler.go
  manifests/generated/kubevirt-cr.yaml.in
  manifests/generated/operator-csv.yaml.in
  manifests/generated/rbac-operator.authorization.k8s.yaml.in
  pkg/testutils/mock_config.go
  pkg/virt-api/api.go
  pkg/virt-api/webhooks/mutating-webhook/mutators/vm-mutator_test.go
  pkg/virt-api/webhooks/mutating-webhook/mutators/vmi-mutator.go
  pkg/virt-api/webhooks/mutating-webhook/mutators/vmi-mutator_test.go
  pkg/virt-api/webhooks/validating-webhook/admitters/migration-create-admitter_test.go
  pkg/virt-api/webhooks/validating-webhook/admitters/migration-update-admitter_test.go
  pkg/virt-api/webhooks/validating-webhook/admitters/vmi-create-admitter_test.go
  pkg/virt-api/webhooks/validating-webhook/admitters/vmirs-admitter_test.go
  pkg/virt-api/webhooks/validating-webhook/admitters/vms-admitter_test.go
  pkg/virt-api/webhooks/validating-webhook/admitters/vmsnapshot-admitter_test.go
  pkg/virt-config/BUILD.bazel
  pkg/virt-config/config-map.go
  pkg/virt-config/config_test.go
  pkg/virt-config/feature-gates.go
  pkg/virt-config/virt-config.go
  pkg/virt-controller/services/template_test.go
  pkg/virt-controller/watch/application.go
  pkg/virt-controller/watch/application_test.go
  pkg/virt-controller/watch/drain/evacuation/evacuation.go
  pkg/virt-controller/watch/drain/evacuation/evacuation_test.go
  pkg/virt-controller/watch/migration.go
  pkg/virt-controller/watch/migration_test.go
  pkg/virt-controller/watch/vmi_test.go
  pkg/virt-handler/vm.go
  pkg/virt-handler/vm_test.go
  pkg/virt-operator/creation/rbac/apiserver.go
  pkg/virt-operator/creation/rbac/handler.go
  staging/src/kubevirt.io/client-go/api/v1/BUILD.bazel
  staging/src/kubevirt.io/client-go/api/v1/deepcopy_generated.go
  staging/src/kubevirt.io/client-go/api/v1/openapi_generated.go
  staging/src/kubevirt.io/client-go/api/v1/types.go
  staging/src/kubevirt.io/client-go/api/v1/types_swagger_generated.go
  staging/src/kubevirt.io/client-go/apis/snapshot/v1alpha1/openapi_generated.go
  tests/vmi_lifecycle_test.go
  tools/vms-generator/vms-generator.go
Labels: approved, dco-signoff: yes, kind/api-change, lgtm, release-note, size/XXL

#3534 automation, travisci-test: Fix misuse of "``"
  automation/travisci-test.sh
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#3546 Fix cascading deletion race condition in some tests
  tests/datavolume_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/S

#3540 Fix flaky test 1625 by removing outdated condition
  tests/vmi_lifecycle_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#3507 Remove modifications on the default privileged SCC.
  pkg/virt-operator/install-strategy/strategy.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/S

#3557 Skip an extremely flakey migration test
  tests/migration_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#3572 Fix typo in docs/graceful-shutdown.md
  docs/graceful-shutdown.md
Labels: approved, dco-signoff: yes, lgtm, ok-to-test, release-note-none, size/S

#3583 Revert "Merge pull request #3314 from maya-r/loopdev"
  hack/cluster-deploy.sh
  manifests/testing/disks-images-provider.yaml.in
  tests/config_test.go
  tests/storage_test.go
  tests/utils.go
  tests/vmi_configuration_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M

#3588 Add Alona as approver
  OWNERS_ALIASES
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#3539 Fix and improve goexpect use in tests and add verbose flag
  tests/BUILD.bazel
  tests/pausing_test.go
  tests/utils.go
  tests/vmi_cloudinit_test.go
  tests/vmi_ignition_test.go
  tests/vmi_networking_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M

#3604 Mirror the which rpm
  WORKSPACE
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#3436 Fix name handling of VMIs in VM templates
  pkg/virt-controller/watch/vm.go
  pkg/virt-controller/watch/vm_test.go
  pkg/virtctl/pause/pause.go
  tests/utils.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M

#3518 Add test to check kubevirt disk perms
  tests/container_disk_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M

#3605 remove use of smbios struct for configuration type
  pkg/virt-config/BUILD.bazel
  pkg/virt-config/config-map.go
  pkg/virt-config/virt-config.go
  pkg/virt-handler/vm.go
  staging/src/kubevirt.io/client-go/api/v1/BUILD.bazel
  staging/src/kubevirt.io/client-go/api/v1/deepcopy_generated.go
  staging/src/kubevirt.io/client-go/api/v1/openapi_generated.go
  staging/src/kubevirt.io/client-go/api/v1/types.go
  staging/src/kubevirt.io/client-go/api/v1/types_swagger_generated.go
  staging/src/kubevirt.io/client-go/apis/snapshot/v1alpha1/openapi_generated.go
Labels: approved, dco-signoff: yes, kind/api-change, lgtm, release-note-none, size/M

#3597 fix wrong json tag name for VirtualMachineSnapshot.Spec.DeletionPolicy
  api/openapi-spec/swagger.json
  staging/src/kubevirt.io/client-go/apis/snapshot/v1alpha1/openapi_generated.go
  staging/src/kubevirt.io/client-go/apis/snapshot/v1alpha1/types.go
  staging/src/kubevirt.io/client-go/apis/snapshot/v1alpha1/types_swagger_generated.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/S

#3582 Increase timeout for virt-handler to return to ready state
  tests/vmi_lifecycle_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#3550 use configMapName parameter in function
  tests/utils.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#3567 Stabilize functest vmi migration stress
  tests/migration_test.go
  tests/utils.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M

#3537 Fix a race condition where we add a role and check for it immediately
  tests/vm_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/S

#3529 Enable Secure Boot by default when EFI is enabled
  api/openapi-spec/swagger.json
  examples/vmi-alpine-efi.yaml
  pkg/virt-api/webhooks/validating-webhook/admitters/vmi-create-admitter.go
  pkg/virt-api/webhooks/validating-webhook/admitters/vmi-create-admitter_test.go
  pkg/virt-launcher/virtwrap/api/converter.go
  pkg/virt-launcher/virtwrap/api/converter_test.go
  staging/src/kubevirt.io/client-go/api/v1/openapi_generated.go
  staging/src/kubevirt.io/client-go/api/v1/schema.go
  staging/src/kubevirt.io/client-go/api/v1/schema_swagger_generated.go
  staging/src/kubevirt.io/client-go/apis/snapshot/v1alpha1/openapi_generated.go
  tests/utils.go
  tools/vms-generator/utils/utils.go
Labels: approved, dco-signoff: yes, kind/api-change, lgtm, release-note, size/M

#3536 Bump to the latest kubevirtci that has the latest Centos kernel
  cluster-up-sha.txt
  cluster-up/cluster/images.sh
  cluster-up/cluster/kind-k8s-1.14.2/README.md
  cluster-up/cluster/kind-k8s-1.14.2/provider.sh
  cluster-up/cluster/kind-k8s-1.17.0-ipv6/README.md
  cluster-up/cluster/kind/README.md
  cluster-up/cluster/kind/common.sh
  cluster-up/cluster/kind/manifests/kube-calico.yaml
  cluster-up/version.txt
  hack/config-default.sh
  pkg/host-disk/host-disk.go
  tests/utils.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/L

#3544 Allow libvirt to relay audit logs (SELinux)
  cmd/virt-handler/virt_launcher.cil
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#3592 English fix: remove `double the` in a few strings
  docs/libvirt-pod-networking.md
  pkg/virt-handler/container-disk/mount_test.go
  pkg/virtctl/imageupload/imageupload.go
  tests/expose_test.go
  tests/subresource_api_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/S

#3480 Fix for checking if an environment has SRIOV enabled before executing the SRIOV functional tests.
  tests/vmi_multus_test.go
Labels: approved, dco-signoff: yes, kind/api-change, kind/build-change, lgtm, release-note-none, size/S

#3566 Tigervnc
  pkg/virtctl/vnc/vnc.go
Labels: approved, dco-signoff: yes, lgtm, needs-ok-to-test, release-note, size/M

#3590 fix disks-images-provider error in ubuntu host
  images/disks-images-provider/entrypoint.sh
Labels: approved, dco-signoff: yes, lgtm, needs-ok-to-test, release-note-none, size/XS

#3555 fix disks-images-provide got error in kind-k8s-1.17 kubevirt cluster
  images/disks-images-provider/entrypoint.sh
  manifests/testing/disks-images-provider.yaml.in
Labels: approved, dco-signoff: yes, lgtm, ok-to-test, release-note-none, size/S

#3618 Add timestamp wrapper to our automation scripts
  Makefile
  hack/timestamps.sh
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/S

#3525 Docs: Masquerade docs correction
  docs/devel/networking.md
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/S

#3406 Handle DataVolume volumes mistakenly used as PVC volumes
  pkg/virt-controller/watch/BUILD.bazel
  pkg/virt-controller/watch/application.go
  pkg/virt-controller/watch/util.go
  pkg/virt-controller/watch/vm.go
  pkg/virt-controller/watch/vm_test.go
  pkg/virt-controller/watch/vmi.go
  pkg/virt-controller/watch/vmi_test.go
  tests/imageupload_test.go
  tests/vm_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/L

#3595 [flakey test] mark parent vmi as failed if associated pod is being deleted
  tests/vmi_lifecycle_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#3488 Update VMI status with latest Pod network IP
  cmd/virt-handler/virt-handler.go
  pkg/util/util.go
  pkg/virt-controller/watch/vmi.go
  pkg/virt-controller/watch/vmi_test.go
  pkg/virt-handler/BUILD.bazel
  pkg/virt-handler/vm.go
  pkg/virt-handler/vm_test.go
  pkg/virt-launcher/virtwrap/network/BUILD.bazel
  pkg/virt-launcher/virtwrap/network/network.go
  pkg/virt-launcher/virtwrap/network/podinterface.go
  pkg/virt-launcher/virtwrap/network/podinterface_test.go
  tests/migration_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/L

#3639 Revert "Add timestamp wrapper to our automation scripts"
  Makefile
  hack/timestamps.sh
Labels: dco-signoff: no, do-not-merge/release-note-label-needed, size/S

#3641 Revert "Update VMI status with latest Pod network IP"
  cmd/virt-handler/virt-handler.go
  pkg/util/util.go
  pkg/virt-controller/watch/vmi.go
  pkg/virt-controller/watch/vmi_test.go
  pkg/virt-handler/BUILD.bazel
  pkg/virt-handler/vm.go
  pkg/virt-handler/vm_test.go
  pkg/virt-launcher/virtwrap/network/BUILD.bazel
  pkg/virt-launcher/virtwrap/network/network.go
  pkg/virt-launcher/virtwrap/network/podinterface.go
  pkg/virt-launcher/virtwrap/network/podinterface_test.go
  tests/migration_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/L

#3614 Don't hot-loop on cert renewals when the ca expiration gets close
  pkg/virt-operator/creation/components/BUILD.bazel
  pkg/virt-operator/creation/components/secrets.go
  pkg/virt-operator/creation/components/secrets_test.go
  pkg/virt-operator/install-strategy/create.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/L

#3632 tests: Increase VMI deletion timeout in the eventual loop
  tests/vmi_configuration_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#3502 Add test related to launcher capabilities
  tests/security_features_test.go
  tests/utils.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M

#3658 Switch to kubevirtci/nfs-ganesha
  WORKSPACE
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#3651 [release-0.30] Don't hot-loop on cert renewals when the ca expiration gets close
  pkg/virt-operator/creation/components/BUILD.bazel
  pkg/virt-operator/creation/components/secrets.go
  pkg/virt-operator/creation/components/secrets_test.go
  pkg/virt-operator/install-strategy/create.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/L

#3571 [flakey test] DataVolume clone permission checking
  manifests/testing/cdi-v1.10.9.yaml.in
  manifests/testing/cdi-v1.18.0.yaml.in
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XL

#3635 Add a feature gate to enable hostDisks
  pkg/virt-api/webhooks/validating-webhook/admitters/vmi-create-admitter.go
  pkg/virt-api/webhooks/validating-webhook/admitters/vmi-create-admitter_test.go
  pkg/virt-api/webhooks/validating-webhook/admitters/vms-admitter_test.go
  pkg/virt-config/feature-gates.go
  tests/storage_test.go
  tests/vmi_configuration_test.go
  tools/vms-generator/vms-generator.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/L

#3649 Fix flaky vmi watch test
  tests/vm_watch_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M

#3652 Fix reference to hardcoded namespace in functional test
  tests/infra_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#3653 Add new maintainers to OWNERS file
  OWNERS_ALIASES
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#3681 Rename chroot to virt-chroot
  cmd/virt-chroot/BUILD.bazel
  cmd/virt-chroot/main.go
  cmd/virt-handler/BUILD.bazel
  pkg/virt-handler/container-disk/mount.go
  pkg/virt-handler/isolation/validation.go
  pkg/virt-handler/selinux/labels.go
Labels: approved, dco-signoff: yes, kind/build-change, lgtm, needs-ok-to-test, release-note-none, size/S

#3598 virt-handler: Remove duplicate socket close
  pkg/virt-handler/notify-server/server.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#3542 [tests] Wait for config changes to be propagated and reset them implicitly
  api/openapi-spec/swagger.json
  cmd/virt-handler/BUILD.bazel
  cmd/virt-handler/virt-handler.go
  pkg/healthz/BUILD.bazel
  pkg/healthz/healthz.go
  pkg/virt-api/api.go
  pkg/virt-config/config-map.go
  pkg/virt-config/virt-config.go
  pkg/virt-controller/rest/BUILD.bazel
  pkg/virt-controller/rest/rest.go
  pkg/virt-controller/watch/BUILD.bazel
  pkg/virt-controller/watch/application.go
  tests/migration_test.go
  tests/utils.go
  tests/vm_test.go
  tests/vmi_configuration_test.go
  tests/vmi_lifecycle_test.go
Labels: approved, dco-signoff: yes, kind/build-change, lgtm, release-note-none, size/L

#3509 Bump kubevirtci: Stabilize SRIOV-lane
  cluster-up-sha.txt
  cluster-up/cluster/kind-k8s-sriov-1.17.0/config_sriov.sh
  cluster-up/version.txt
  hack/config-default.sh
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/L

#3646 label tests of connectivity over masquerade
  tests/expose_test.go
  tests/vmi_networking_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/S

#3628 Avoid virt-handler crash in case of virt-launcher network configuration error
  pkg/virt-handler/vm.go
  pkg/virt-handler/vm_test.go
  pkg/virt-launcher/virtwrap/network/common.go
  pkg/virt-launcher/virtwrap/network/podinterface.go
  pkg/virt-launcher/virtwrap/network/podinterface_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/L

#3716 Add test-id for EFI secure boot test
  tests/vmi_configuration_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#3686 [release-0.30] Add a feature gate to enable hostDisks
  pkg/virt-api/webhooks/validating-webhook/admitters/vmi-create-admitter.go
  pkg/virt-api/webhooks/validating-webhook/admitters/vmi-create-admitter_test.go
  pkg/virt-api/webhooks/validating-webhook/admitters/vms-admitter_test.go
  pkg/virt-config/feature-gates.go
  tests/storage_test.go
  tests/vmi_configuration_test.go
  tools/vms-generator/vms-generator.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/L

#3513 fix test default smbios values
  tests/vmi_configuration_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS
