Repository kubevirt/kubevirt, pull requests merged in 2020-11, with the labels that each got.

#4451 test, waitvmi: Add context mechanism to WaitUntilVMIReadAsync
  tests/networkpolicy_test.go
  tests/storage_test.go
  tests/utils.go
  tests/vmi_lifecycle_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/L

#4447 tests: ensure the virt-handler killer pod has gone after deletion
  tests/migration_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/S

#4470 tests, Fix SRIOV UpdateCDIConfigMap panic
  tests/utils.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#4366 [virt-controller] Remove redundant initcontainer
  pkg/virt-controller/services/template.go
  pkg/virt-controller/services/template_test.go
Labels: approved, dco-signoff: yes, lgtm, ok-to-test, release-note-none, size/M

#4475 tests, sriov: Do not mount /sys/devices/ for SRIOV devices
  pkg/virt-controller/services/template.go
  pkg/virt-controller/services/template_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/S

#4443 Define side effects class on our webhooks
  pkg/virt-api/webhooks/validating-webhook/admitters/pod-eviction-admitter.go
  pkg/virt-api/webhooks/validating-webhook/admitters/pod-eviction-admitter_test.go
  pkg/virt-operator/creation/components/webhooks.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/M

#4460 Fix comment typos
  pkg/config/config.go
  pkg/controller/controller_ref_manager.go
Labels: approved, dco-signoff: yes, lgtm, ok-to-test, release-note-none, size/XS

#4479 Fix permissions tests for VMs
  tests/vm_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/S

#4465 tests: fix LoginToCirros panic
  tests/login.go
Labels: approved, dco-signoff: yes, lgtm, ok-to-test, release-note-none, size/XS

#4484 [release-0.34] Remove 'string' from json tag to preserve type information in our API
  api/openapi-spec/swagger.json
  pkg/virt-config/config-map.go
  pkg/virt-config/virt-config.go
  pkg/virt-controller/services/template.go
  staging/src/kubevirt.io/client-go/api/v1/openapi_generated.go
  staging/src/kubevirt.io/client-go/api/v1/types.go
  staging/src/kubevirt.io/client-go/apis/snapshot/v1alpha1/openapi_generated.go
Labels: approved, dco-signoff: yes, kind/api-change, lgtm, release-note-none, size/L

#4474 tests, sriov: Fix the helper that waits for a vmi to start
  tests/vmi_multus_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#3937 Generalize host devices assignment in KubeVirt
  api/api-rule-violations-known.list
  api/api-rule-violations.list
  api/openapi-spec/swagger.json
  pkg/util/util.go
  pkg/virt-api/webhooks/validating-webhook/admitters/vmi-create-admitter.go
  pkg/virt-api/webhooks/validating-webhook/admitters/vmi-create-admitter_test.go
  pkg/virt-config/config-map.go
  pkg/virt-config/config_test.go
  pkg/virt-config/feature-gates.go
  pkg/virt-config/virt-config.go
  pkg/virt-controller/services/template.go
  pkg/virt-controller/services/template_test.go
  pkg/virt-handler/device-manager/BUILD.bazel
  pkg/virt-handler/device-manager/common.go
  pkg/virt-handler/device-manager/device_controller.go
  pkg/virt-handler/device-manager/device_controller_test.go
  pkg/virt-handler/device-manager/deviceplugin/v1beta1/BUILD.bazel
  pkg/virt-handler/device-manager/deviceplugin/v1beta1/api.pb.go
  pkg/virt-handler/device-manager/deviceplugin/v1beta1/api.proto
  pkg/virt-handler/device-manager/generated_mock_common.go
  pkg/virt-handler/device-manager/generic_device.go
  pkg/virt-handler/device-manager/mediated_device.go
  pkg/virt-handler/device-manager/mediated_device_test.go
  pkg/virt-handler/device-manager/pci_device.go
  pkg/virt-handler/device-manager/pci_device_test.go
  pkg/virt-handler/isolation/isolation.go
  pkg/virt-handler/vm.go
  pkg/virt-launcher/virtwrap/BUILD.bazel
  pkg/virt-launcher/virtwrap/api/converter.go
  pkg/virt-launcher/virtwrap/api/converter_test.go
  pkg/virt-launcher/virtwrap/api/deepcopy_generated.go
  pkg/virt-launcher/virtwrap/api/schema.go
  pkg/virt-launcher/virtwrap/manager.go
  pkg/virt-operator/creation/components/validations_generated.go
  staging/src/kubevirt.io/client-go/api/v1/deepcopy_generated.go
  staging/src/kubevirt.io/client-go/api/v1/openapi_generated.go
  staging/src/kubevirt.io/client-go/api/v1/schema.go
  staging/src/kubevirt.io/client-go/api/v1/schema_swagger_generated.go
  staging/src/kubevirt.io/client-go/api/v1/types.go
  staging/src/kubevirt.io/client-go/api/v1/types_swagger_generated.go
  staging/src/kubevirt.io/client-go/apis/snapshot/v1alpha1/openapi_generated.go
  tests/BUILD.bazel
  tests/vmi_hostdev_test.go
  tests/vmi_lifecycle_test.go
  tools/vms-generator/vms-generator.go
Labels: approved, dco-signoff: yes, kind/api-change, lgtm, release-note, size/XXL

#4472 tests, Fix potential deref of nil ptr at resetToDefaultConfig
  tests/utils.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/S

#4483 Add Igor Bezukh to test approvers
  OWNERS_ALIASES
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#4488 Disable Virtio-FS Metadata Cache
  pkg/virt-launcher/virtwrap/api/converter.go
Labels: approved, dco-signoff: yes, lgtm, needs-ok-to-test, release-note, size/XS

#4494 [release-0.34] Infra test made invalid assumptions about cluster composition
  tests/infra_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/S

#4495 Fix gosec issue: using weak md5 cryptographic module
  pkg/ephemeral-disk-utils/utils.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#4463 Move code for downloads and test execution into kubevirt/kubevirt hack/ci scripts
  hack/ci/Dockerfile.ci
  hack/ci/Dockerfile.ci-pr
  hack/ci/build-pr.sh
  hack/ci/build.sh
  hack/ci/entrypoint.sh
  hack/ci/test-pr.sh
  hack/ci/test.sh
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/L

#4503 virt-config fixes (tests and docs)
  docs/software-emulation.md
  pkg/virt-config/BUILD.bazel
  pkg/virt-config/config_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M

#4505 Add enp0s3 to approvers list
  OWNERS_ALIASES
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#4501 virt-launcher: drop CAP_NET_RAW from compute container
  pkg/virt-controller/services/template.go
  pkg/virt-controller/services/template_test.go
  pkg/virt-launcher/virtwrap/network/dhcp/BUILD.bazel
  pkg/virt-launcher/virtwrap/network/dhcp/dhcp.go
  pkg/virt-launcher/virtwrap/network/dhcp/socket_listener.go
  pkg/virt-operator/creation/components/scc.go
  tests/security_features_test.go
  tests/utils.go
  tests/vmi_networking_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/L

#4471 virt-launcher: remove redundant cidr from dhcp server address
  pkg/virt-launcher/virtwrap/network/common.go
  pkg/virt-launcher/virtwrap/network/generated_mock_common.go
  pkg/virt-launcher/virtwrap/network/podinterface.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/S

#4444 Set leader metric after controller is functional
  pkg/virt-controller/watch/BUILD.bazel
  pkg/virt-controller/watch/application.go
  pkg/virt-controller/watch/application_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/L

#4507 gosec - fix CWE 326
  pkg/ephemeral-disk-utils/utils.go
  pkg/virt-operator/install-strategy/patches.go
  pkg/virt-operator/util/config.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#4362 Reduce to the minimum the helpers that return an expecter
  tests/config_test.go
  tests/console/console.go
  tests/console_test.go
  tests/container_disk_test.go
  tests/datavolume_test.go
  tests/expose_test.go
  tests/infra_test.go
  tests/login.go
  tests/migration_test.go
  tests/network/primary_pod_network.go
  tests/network/services.go
  tests/networkpolicy_test.go
  tests/operator_test.go
  tests/pausing_test.go
  tests/restore_test.go
  tests/security_features_test.go
  tests/storage_test.go
  tests/utils.go
  tests/vm_test.go
  tests/vmi_cloudinit_hook_sidecar_test.go
  tests/vmi_cloudinit_test.go
  tests/vmi_configuration_test.go
  tests/vmi_headless_test.go
  tests/vmi_hostdev_test.go
  tests/vmi_ignition_test.go
  tests/vmi_lifecycle_test.go
  tests/vmi_monitoring_test.go
  tests/vmi_multiqueue_test.go
  tests/vmi_multus_test.go
  tests/vmi_networking_test.go
  tests/vmi_slirp_interface_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XXL

#4506 Remove net admin
  cmd/virt-chroot/main.go
  cmd/virt-chroot/tap-device-maker.go
  pkg/virt-controller/services/template.go
  pkg/virt-controller/services/template_test.go
  pkg/virt-launcher/virtwrap/network/common.go
  pkg/virt-launcher/virtwrap/network/dhcp/dhcp.go
  pkg/virt-launcher/virtwrap/network/generated_mock_common.go
  pkg/virt-launcher/virtwrap/network/podinterface.go
  pkg/virt-launcher/virtwrap/network/podinterface_test.go
  pkg/virt-operator/creation/components/scc.go
  tests/security_features_test.go
  tests/utils.go
  tests/vmi_networking_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/L

#4492 Use "json" annotation instead of "yaml"
  tests/libnet/cloudinit.go
  tests/libvmi/factory.go
  tests/network/primary_pod_network.go
  tests/utils.go
  tests/vmi_networking_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/L

#4513 image-upload: wait up to 5 min for PVC and Pod
  pkg/virtctl/imageupload/imageupload.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#4522 Slow down the certificate and CA rotate intervall in the tests
  pkg/util/webhooks/ca-manager.go
  tests/utils.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M

#4421 Automatically set disk I/O mode to the optimal value (native/threads)
  pkg/virt-launcher/virtwrap/api/converter.go
  pkg/virt-launcher/virtwrap/manager.go
  pkg/virt-launcher/virtwrap/manager_test.go
  tests/vmi_configuration_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/L

#4446 Fix gosec issue: Use of unsafe calls (go pointers)
  pkg/virt-handler/isolation/isolation.go
  pkg/virt-launcher/virtwrap/network/dhcp/ethtool.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#4496 Fix gosec issu: weak sha1 cryptographic module
  pkg/virt-operator/install-strategy/patches.go
  pkg/virt-operator/util/config.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#4547 tests, console: Remove VMIExpecterFactory
  tests/console/console.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#4542 Fix double migration during node drain
  pkg/util/migrations/BUILD.bazel
  pkg/util/migrations/migrations.go
  pkg/virt-api/webhooks/validating-webhook/admitters/pod-eviction-admitter.go
  pkg/virt-controller/watch/drain/evacuation/BUILD.bazel
  pkg/virt-controller/watch/drain/evacuation/evacuation.go
  pkg/virt-handler/BUILD.bazel
  pkg/virt-handler/vm.go
  tests/migration_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/L

#4514 Remove domain label from kubevirt_vmi_memory_unused_bytes
  pkg/monitoring/vms/prometheus/prometheus.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/XS

#4408 WORKSPACE: Update libvirt container
  WORKSPACE
  cmd/virt-launcher/virt-launcher.go
  pkg/virt-launcher/virtwrap/api/converter.go
  pkg/virt-launcher/virtwrap/api/converter_test.go
  tests/migration_test.go
  tests/security_features_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/M

#4511 sriov tests, Fix flakiness due to race between guest agent and test
  tests/vmi_multus_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/S

#4516 tests, multus, sriov: Refactor tests
  tests/vmi_multus_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/S

#4557 Fix double migration during node drain
  pkg/util/migrations/BUILD.bazel
  pkg/util/migrations/migrations.go
  pkg/virt-api/webhooks/validating-webhook/admitters/pod-eviction-admitter.go
  pkg/virt-controller/watch/drain/evacuation/BUILD.bazel
  pkg/virt-controller/watch/drain/evacuation/evacuation.go
  pkg/virt-handler/BUILD.bazel
  pkg/virt-handler/vm.go
  tests/migration_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/L

#4491 tests, multus, sriov: Fix checking for the same network twice
  tests/vmi_multus_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M

#4335 virt-handler, Add missing network name for SRIOV interfaces in case MAC is presented in the VMI spec
  pkg/virt-handler/vm.go
  pkg/virt-handler/vm_test.go
  tests/vmi_multus_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/M

#4435 Fix gosec issue: Deferring unsafe Close() calls
  pkg/ephemeral-disk-utils/BUILD.bazel
  pkg/ephemeral-disk-utils/utils.go
  pkg/host-disk/BUILD.bazel
  pkg/host-disk/host-disk.go
  pkg/util/BUILD.bazel
  pkg/util/os_helper.go
  pkg/virt-handler/cache/BUILD.bazel
  pkg/virt-handler/cache/cache.go
  pkg/virt-handler/isolation/isolation.go
  pkg/virt-launcher/virtwrap/api/converter.go
  pkg/virt-launcher/virtwrap/manager.go
  pkg/virt-launcher/virtwrap/util/BUILD.bazel
  pkg/virt-launcher/virtwrap/util/cpu_utils.go
  pkg/virt-launcher/virtwrap/util/libvirt_helper.go
  pkg/virtctl/imageupload/BUILD.bazel
  pkg/virtctl/imageupload/imageupload.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M

#4462 Fix failing CI test - loosen requirements in a too demanding test
  pkg/virt-controller/watch/application.go
  pkg/virt-controller/watch/application_test.go
  pkg/virt-controller/watch/snapshot/BUILD.bazel
  pkg/virt-controller/watch/snapshot/snapshot.go
  pkg/virt-controller/watch/snapshot/snapshot_base.go
  pkg/virt-controller/watch/snapshot/snapshot_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/L

#4512 virt-launcher, agent-poller: Start poller with short intervals
  pkg/virt-launcher/virtwrap/agent-poller/BUILD.bazel
  pkg/virt-launcher/virtwrap/agent-poller/agent_parser_test.go
  pkg/virt-launcher/virtwrap/agent-poller/agent_poller.go
  pkg/virt-launcher/virtwrap/agent-poller/agent_poller_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XXL

#4561 test, console: Remove tests/login.go
  tests/BUILD.bazel
  tests/config_test.go
  tests/console/BUILD.bazel
  tests/console/login.go
  tests/container_disk_test.go
  tests/datavolume_test.go
  tests/expose_test.go
  tests/infra_test.go
  tests/libnet/BUILD.bazel
  tests/libnet/ipv6.go
  tests/libvmi/BUILD.bazel
  tests/libvmi/status.go
  tests/migration_test.go
  tests/network/BUILD.bazel
  tests/network/primary_pod_network.go
  tests/network/services.go
  tests/networkpolicy_test.go
  tests/operator_test.go
  tests/pausing_test.go
  tests/restore_test.go
  tests/security_features_test.go
  tests/storage_test.go
  tests/utils.go
  tests/vm_test.go
  tests/vmi_cloudinit_hook_sidecar_test.go
  tests/vmi_cloudinit_test.go
  tests/vmi_configuration_test.go
  tests/vmi_gpu_test.go
  tests/vmi_headless_test.go
  tests/vmi_hostdev_test.go
  tests/vmi_lifecycle_test.go
  tests/vmi_monitoring_test.go
  tests/vmi_multiqueue_test.go
  tests/vmi_multus_test.go
  tests/vmi_networking_test.go
  tests/vmi_servers.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XL

#4499 Mirror PVC struct with restricted objectmeta
  api/openapi-spec/swagger.json
  pkg/virt-controller/watch/snapshot/snapshot.go
  pkg/virt-controller/watch/snapshot/snapshot_test.go
  pkg/virt-operator/creation/components/validations_generated.go
  staging/src/kubevirt.io/client-go/apis/snapshot/v1alpha1/deepcopy_generated.go
  staging/src/kubevirt.io/client-go/apis/snapshot/v1alpha1/openapi_generated.go
  staging/src/kubevirt.io/client-go/apis/snapshot/v1alpha1/types.go
  staging/src/kubevirt.io/client-go/apis/snapshot/v1alpha1/types_swagger_generated.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/L

#4577 deployment scripts: Increase CDI deployment timeout
  hack/cluster-deploy.sh
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#4305 Fixed typos and extended the description of the technical overview
  docs/README.md
  docs/components.png
Labels: approved, dco-signoff: yes, lgtm, ok-to-test, release-note-none, size/M

#4559 fix gosec g204: subprocess launched with function call as ar…
  pkg/virt-handler/container-disk/mount.go
  pkg/virt-handler/isolation/validation.go
  pkg/virt-launcher/virtwrap/network/common.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#4554 virt-launcher: Improve libvirtd debug log filters
  pkg/virt-launcher/virtwrap/util/libvirt_helper.go
  tests/vmi_lifecycle_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/S

#4195 Access Credentials API (with dynamic propagation)
  api/openapi-spec/swagger.json
  hack/generate.sh
  pkg/cloud-init/cloud-init.go
  pkg/cloud-init/cloud-init_test.go
  pkg/virt-api/webhooks/validating-webhook/admitters/vmi-create-admitter.go
  pkg/virt-api/webhooks/validating-webhook/admitters/vmi-create-admitter_test.go
  pkg/virt-controller/services/template.go
  pkg/virt-controller/services/template_test.go
  pkg/virt-handler/vm.go
  pkg/virt-handler/vm_test.go
  pkg/virt-launcher/virtwrap/BUILD.bazel
  pkg/virt-launcher/virtwrap/access-credentials/BUILD.bazel
  pkg/virt-launcher/virtwrap/access-credentials/access_credentials.go
  pkg/virt-launcher/virtwrap/access-credentials/access_credentials_suite_test.go
  pkg/virt-launcher/virtwrap/access-credentials/access_credentials_test.go
  pkg/virt-launcher/virtwrap/api/deepcopy_generated.go
  pkg/virt-launcher/virtwrap/api/schema.go
  pkg/virt-launcher/virtwrap/manager.go
  pkg/virt-launcher/virtwrap/util/BUILD.bazel
  pkg/virt-launcher/virtwrap/util/libvirt_helper.go
  pkg/virt-operator/creation/components/validations_generated.go
  staging/src/kubevirt.io/client-go/api/v1/deepcopy_generated.go
  staging/src/kubevirt.io/client-go/api/v1/openapi_generated.go
  staging/src/kubevirt.io/client-go/api/v1/schema.go
  staging/src/kubevirt.io/client-go/api/v1/schema_swagger_generated.go
  staging/src/kubevirt.io/client-go/api/v1/types.go
  staging/src/kubevirt.io/client-go/api/v1/types_swagger_generated.go
  staging/src/kubevirt.io/client-go/apis/snapshot/v1alpha1/openapi_generated.go
  tests/BUILD.bazel
  tests/credentials_test.go
  tests/virt_control_plane_test.go
  tests/vmi_cloudinit_test.go
Labels: approved, dco-signoff: yes, kind/api-change, lgtm, release-note, size/XXL

#4422 Fix misspellings
  CONTRIBUTING.md
  api/openapi-spec/swagger.json
  cmd/virt-handler/virt-handler.go
  pkg/certificates/bootstrap/cert-manager.go
  pkg/ephemeral-disk/ephemeral-disk.go
  pkg/host-disk/host-disk_test.go
  pkg/monitoring/vms/prometheus/prometheus.go
  pkg/util/types/pvc_test.go
  pkg/virt-api/rest/subresource_test.go
  pkg/virt-api/webhooks/mutating-webhook/mutators/vmi-mutator_test.go
  pkg/virt-api/webhooks/validating-webhook/admitters/vmi-create-admitter_test.go
  pkg/virt-config/virt-config.go
  pkg/virt-controller/services/template.go
  pkg/virt-controller/watch/snapshot/snapshot.go
  pkg/virt-controller/watch/vmi.go
  pkg/virt-handler/cache/cache.go
  pkg/virt-handler/cmd-client/client_test.go
  pkg/virt-handler/vm.go
  pkg/virt-handler/vm_test.go
  pkg/virt-launcher/virtwrap/agent-poller/agent_poller.go
  pkg/virt-launcher/virtwrap/api/converter.go
  pkg/virt-launcher/virtwrap/manager.go
  pkg/virt-operator/application.go
  pkg/virt-operator/creation/components/validations_generated.go
  pkg/virt-operator/install-strategy/create.go
  pkg/virt-operator/install-strategy/create_test.go
  pkg/virt-operator/util/config.go
  pkg/virtctl/imageupload/imageupload.go
  pkg/virtctl/root.go
  staging/src/kubevirt.io/client-go/api/v1/defaults_test.go
  staging/src/kubevirt.io/client-go/api/v1/openapi_generated.go
  staging/src/kubevirt.io/client-go/api/v1/schema.go
  staging/src/kubevirt.io/client-go/api/v1/schema_swagger_generated.go
  staging/src/kubevirt.io/client-go/api/v1/types.go
  staging/src/kubevirt.io/client-go/api/v1/types_swagger_generated.go
  staging/src/kubevirt.io/client-go/apis/snapshot/v1alpha1/openapi_generated.go
  tests/console/console.go
  tests/flags/flags.go
  tests/migration_test.go
  tests/operator_test.go
  tests/pausing_test.go
  tests/storage_test.go
  tests/utils.go
  tests/vm_test.go
  tests/vmi_configuration_test.go
  tests/vmi_lifecycle_test.go
  tests/vmi_multus_test.go
  tests/vmi_networking_test.go
  tests/vmidefaults_test.go
  tools/crd-validation-generator/validation-generator.go
Labels: approved, dco-signoff: yes, kind/api-change, lgtm, ok-to-test, release-note-none, size/L

#4576 expose, tests: fix early shutdown of `nc` TCP connections
  tests/job.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#4341 tests, dual stack: split probes tests to test per IP-Family
  tests/probes_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/L

#4569 tests, primary_pod_network: Remove race condition at bridge binding GA test
  tests/network/primary_pod_network.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/S

#4585 Cdi bump 1.26.1
  go.mod
  go.sum
  manifests/testing/cdi-v1.26.1.yaml.in
  staging/src/kubevirt.io/client-go/api/v1/openapi_generated.go
  staging/src/kubevirt.io/client-go/go.mod
  staging/src/kubevirt.io/client-go/go.sum
  vendor/kubevirt.io/containerized-data-importer/pkg/apis/core/v1alpha1/openapi_generated.go
  vendor/kubevirt.io/containerized-data-importer/pkg/apis/core/v1alpha1/types.go
  vendor/kubevirt.io/containerized-data-importer/pkg/apis/core/v1alpha1/types_swagger_generated.go
  vendor/kubevirt.io/containerized-data-importer/pkg/apis/core/v1alpha1/utils.go
  vendor/kubevirt.io/containerized-data-importer/pkg/apis/core/v1alpha1/zz_generated.deepcopy.go
  vendor/modules.txt
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/L

#4588 bump kubevirtci
  cluster-up-sha.txt
  cluster-up/.gitignore
  cluster-up/cluster/k8s-provider-common.sh
  cluster-up/cluster/kind-k8s-sriov-1.17.0/certcreator/certlib/selfsign.go
  cluster-up/cluster/kind-k8s-sriov-1.17.0/certcreator/certsecret.go
  cluster-up/cluster/kind-k8s-sriov-1.17.0/certcreator/go.mod
  cluster-up/cluster/kind-k8s-sriov-1.17.0/certcreator/go.sum
  cluster-up/cluster/kind-k8s-sriov-1.17.0/config_sriov.sh
  cluster-up/cluster/kind-k8s-sriov-1.17.0/csrcreator/certsecret.go
  cluster-up/cluster/kind-k8s-sriov-1.17.0/provider.sh
  cluster-up/cluster/kind/common.sh
  cluster-up/hack/common.sh
  cluster-up/version.txt
  hack/config-default.sh
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XL

#4589 Allow to run subset of rules for gosec
  Makefile
  hack/gosec.sh
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/S

#4217 Extract an IP address from CIDR reported by Qemu guest
  pkg/virt-handler/vm_test.go
  pkg/virt-launcher/virtwrap/agent-poller/agent_parser.go
  pkg/virt-launcher/virtwrap/agent-poller/agent_parser_test.go
  tests/libnet/cloudinit.go
  tests/vmi_multus_test.go
Labels: approved, dco-signoff: yes, kind/api-change, lgtm, release-note, sig/network, size/M

#4448 test, sriov: Configure ip addresses using cloud init network data
  tests/libnet/cloudinit.go
  tests/libvmi/factory.go
  tests/libvmi/network.go
  tests/libvmi/status.go
  tests/vmi_multus_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/L

#4412 macvtap, migration, tests: add a test w/ traffic
  tests/BUILD.bazel
  tests/libvmi/network.go
  tests/vmi_multus_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/L

#4025 Adds a special handling for DataVolumes in WaitForFirstConsumer state.
  pkg/virt-controller/services/template.go
  pkg/virt-controller/watch/BUILD.bazel
  pkg/virt-controller/watch/vm.go
  pkg/virt-controller/watch/vm_test.go
  pkg/virt-controller/watch/vmi.go
  pkg/virt-controller/watch/vmi_test.go
  staging/src/kubevirt.io/client-go/api/v1/types.go
  staging/src/kubevirt.io/client-go/go.mod
  tests/datavolume_test.go
  tests/migration_test.go
  tests/utils.go
Labels: approved, dco-signoff: yes, kind/api-change, lgtm, release-note, size/XL

#4593 Remove sysctl binary dependency
  pkg/util/sysctl/BUILD.bazel
  pkg/util/sysctl/sysctl.go
  pkg/virt-launcher/virtwrap/network/BUILD.bazel
  pkg/virt-launcher/virtwrap/network/common.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M

#4596 tests, network: Remove vmi Status ip normalization
  tests/network/primary_pod_network.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/S

#4579 dev guide, networking: no capabilities are required
  docs/devel/networking.md
Labels: approved, dco-signoff: yes, lgtm, release-note-none, sig/network, size/XS

#4586 Update ADOPTERS.md
  ADOPTERS.md
Labels: dco-signoff: yes, release-note-none, size/XS

#4608 Update ADOPTERS.md
  ADOPTERS.md
Labels: dco-signoff: no, release-note-none
