Repository kubevirt/kubevirt, pull requests merged in 2020-10, with the labels that each got.

#3837 libvirt: disable PXE rom on interfaces with no boot order
  api/openapi-spec/swagger.json
  hack/generate.sh
  pkg/virt-launcher/virtwrap/api/converter.go
  pkg/virt-launcher/virtwrap/api/converter_test.go
  pkg/virt-launcher/virtwrap/api/deepcopy_generated.go
  pkg/virt-launcher/virtwrap/api/schema.go
  staging/src/kubevirt.io/client-go/api/v1/deepcopy_generated.go
  staging/src/kubevirt.io/client-go/api/v1/openapi_generated.go
  staging/src/kubevirt.io/client-go/api/v1/schema.go
  staging/src/kubevirt.io/client-go/api/v1/schema_swagger_generated.go
  staging/src/kubevirt.io/client-go/apis/snapshot/v1alpha1/openapi_generated.go
  tests/expecter.go
  tests/vmi_configuration_test.go
Labels: approved, dco-signoff: yes, kind/api-change, lgtm, release-note, size/L

#4234 vmi, sriov: Enable to set the PCI address on a SRIOV iface
  pkg/virt-launcher/virtwrap/api/converter.go
  pkg/virt-launcher/virtwrap/api/converter_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M

#4266 Mark networking conformance tests
  tests/network/primary_pod_network.go
  tests/network/services.go
  tests/networkpolicy_test.go
  tests/vmi_networking_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/S

#4291 tests, infra-test, Solve CI flakiness due to update conflict
  tests/infra_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/S

#4273 Run Travis CI only on master, tag or release branch
  .travis.yml
Labels: approved, dco-signoff: yes, lgtm, release-note, size/XS

#4265 Fix display of virtctl help text for other usages
  pkg/virtctl/BUILD.bazel
  pkg/virtctl/root.go
  pkg/virtctl/root_suite_test.go
  pkg/virtctl/root_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/M

#4293 Fix flaky rename test
  tests/vm_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#4292 Fix flaky unpause tests
  tests/pausing_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/S

#4124 tests, libnet: Move helpers into libnet
  go.mod
  tests/BUILD.bazel
  tests/libnet/BUILD.bazel
  tests/libnet/cloudinit.go
  tests/libnet/dns.go
  tests/libnet/validation.go
  tests/libvmi/cloudinit.go
  tests/libvmi/factory.go
  tests/migration_test.go
  tests/network/BUILD.bazel
  tests/network/primary_pod_network.go
  tests/utils.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/L

#4297 Restore controller in memory corrution
  pkg/virt-controller/watch/snapshot/restore.go
  pkg/virt-controller/watch/snapshot/restore_base.go
  pkg/virt-controller/watch/snapshot/restore_test.go
  pkg/virt-controller/watch/snapshot/snapshot.go
  pkg/virt-controller/watch/snapshot/snapshot_base.go
  tests/restore_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/L

#4299 Add a nice cluster-overview to the collected test artifacts
  tests/k8s-reporter/1_events.log
  tests/reporter/kubernetes.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/S

#4304 docs: Fix the ginkgo flags usage example
  docs/getting-started.md
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#4277 Allow PVC as volume source with a DV populating the PVC.
  pkg/virt-api/webhooks/validating-webhook/admitters/vms-admitter.go
  pkg/virt-controller/watch/util.go
  pkg/virt-controller/watch/vm.go
  pkg/virt-controller/watch/vmi.go
  pkg/virt-controller/watch/vmi_test.go
  tests/datavolume_test.go
  tests/vm_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/L

#4302 Properly exit if kubevirt does not get ready on cluster-sync
  hack/cluster-deploy.sh
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/S

#4251 Move coverage reports over to bazel
  BUILD.bazel
  Makefile
  go.mod
  go.sum
  hack/bazel-generate.sh
  hack/bazel-goveralls.sh
  hack/coverage.sh
  hack/goveralls.sh
  pkg/virt-handler/cache/cache_test.go
  pkg/virt-handler/vm_test.go
  pkg/virt-launcher/monitor_test.go
  pkg/virt-operator/creation/components/secrets_test.go
  tools/BUILD.bazel
  tools/tools.go
  vendor/github.com/wadey/gocovmerge/BUILD.bazel
  vendor/github.com/wadey/gocovmerge/LICENSE
  vendor/github.com/wadey/gocovmerge/README.md
  vendor/github.com/wadey/gocovmerge/gocovmerge.go
  vendor/golang.org/x/tools/AUTHORS
  vendor/golang.org/x/tools/CONTRIBUTORS
  vendor/golang.org/x/tools/LICENSE
  vendor/golang.org/x/tools/PATENTS
  vendor/golang.org/x/tools/cover/BUILD.bazel
  vendor/golang.org/x/tools/cover/profile.go
  vendor/libvirt.org/libvirt-go/BUILD.bazel
  vendor/modules.txt
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XL

#4316 [release-0.34] Revert test kubevirt cr
  manifests/testing/kubevirt-config.yaml.in
  pkg/virt-config/config-map.go
  tests/BUILD.bazel
  tests/kubevirt_configmap_test.go
  tests/migration_test.go
  tests/operator_test.go
  tests/security_features_test.go
  tests/storage_test.go
  tests/utils.go
  tests/vm_test.go
  tests/vmi_configuration_test.go
  tests/vmi_lifecycle_test.go
  tests/vmi_networking_test.go
  tests/vmi_slirp_interface_test.go
  tests/vmidefaults_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XL

#4319 restore backwards compatiblity with api group/version on DataVolumeTemplates spec
  api/openapi-spec/swagger.json
  staging/src/kubevirt.io/client-go/api/v1/deepcopy_generated.go
  staging/src/kubevirt.io/client-go/api/v1/openapi_generated.go
  staging/src/kubevirt.io/client-go/api/v1/types.go
  staging/src/kubevirt.io/client-go/apis/snapshot/v1alpha1/openapi_generated.go
Labels: approved, dco-signoff: yes, kind/api-change, lgtm, release-note-none, size/M

#4156 tests, dual stack: Adapt tests using NFSTargetPOD to support dual stack
  tests/BUILD.bazel
  tests/libnet/BUILD.bazel
  tests/libnet/ipaddress.go
  tests/libnet/skips.go
  tests/migration_test.go
  tests/probes_test.go
  tests/storage_test.go
  tests/utils.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/L

#4152 virt-operator: remove Kubevirt service accounts from default privileged SCC upon upgrade
  pkg/virt-operator/creation/rbac/operator.go
  pkg/virt-operator/install-strategy/BUILD.bazel
  pkg/virt-operator/install-strategy/create.go
  pkg/virt-operator/install-strategy/create_test.go
  pkg/virt-operator/install-strategy/delete.go
  pkg/virt-operator/install-strategy/strategy.go
  pkg/virt-operator/kubevirt.go
  pkg/virt-operator/kubevirt_test.go
  pkg/virt-operator/util/config.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/L

#3715 Automatic doc gen
  .gitignore
  docs/metrics.md
  hack/generate.sh
  pkg/monitoring/vms/prometheus/BUILD.bazel
  pkg/monitoring/vms/prometheus/fakeCollector.go
  pkg/virt-launcher/virtwrap/statsconv/BUILD.bazel
  pkg/virt-launcher/virtwrap/statsconv/converter_test.go
  pkg/virt-launcher/virtwrap/statsconv/domstats.json
  pkg/virt-launcher/virtwrap/statsconv/domstats_expected.json
  pkg/virt-launcher/virtwrap/statsconv/util/BUILD.bazel
  pkg/virt-launcher/virtwrap/statsconv/util/domstats_utils.go
  tools/doc-generator/BUILD.bazel
  tools/doc-generator/doc-generator.go
Labels: approved, dco-signoff: yes, kind/build-change, lgtm, release-note-none, size/XL

#4224 dual stack, services: provide more explicit info on test execution
  tests/network/BUILD.bazel
  tests/network/services.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/L

#4287 Add test_id for post-copy migration with Guest Agent Test
  tests/migration_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#4289 [masquerade-binding] Set the pod iface mtu on the bridge
  pkg/virt-launcher/virtwrap/network/podinterface.go
  pkg/virt-launcher/virtwrap/network/podinterface_test.go
  tests/libnet/ipaddress.go
  tests/vmi_networking_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/L

#4330 Exclude .git and _ci-configs at bazel's goimports
  BUILD.bazel
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#4260 Cap the maximum number of queues on a tap device
  pkg/virt-launcher/virtwrap/api/converter.go
  pkg/virt-launcher/virtwrap/api/converter_test.go
Labels: approved, dco-signoff: yes, kind/api-change, lgtm, release-note-none, size/S

#4328 Add 2.x QEMU Guest Agents to the list of supported versions
  pkg/virt-config/virt-config.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/XS

#4329 [release-0.34] mtu bug
  pkg/virt-launcher/virtwrap/network/podinterface.go
  pkg/virt-launcher/virtwrap/network/podinterface_test.go
  tests/libnet/BUILD.bazel
  tests/libnet/ipaddress.go
  tests/libnet/skips.go
  tests/vmi_networking_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/L

#4192 Add gosec to project
  Makefile
  hack/builder/Dockerfile
  hack/builder/version.sh
  hack/dockerized
  hack/gosec.sh
  pkg/util/webhooks/tls.go
  pkg/virtctl/imageupload/imageupload.go
  tools/gosec/README.md
Labels: approved, dco-signoff: yes, lgtm, release-note, size/M

#4334 tests, networkpolicy: Wait for VMIs readiness in parallel
  tests/networkpolicy_test.go
  tests/utils.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/S

#4233 Update to fedora 31 as base image.
  WORKSPACE
  images/cdi-http-import-server/BUILD.bazel
  images/cdi-http-import-server/entrypoint.sh
  tests/utils.go
  tests/vmi_multus_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/L

#4351 Lift the e2e parallel test restriction for fedora guests
  automation/test.sh
  tests/README.md
  tests/console_test.go
  tests/pausing_test.go
  tests/vm_test.go
  tests/vmi_cloudinit_test.go
  tests/vmi_configuration_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/S

#4344 [release-0.34] Update to fedora 31 as base image.
  WORKSPACE
  images/cdi-http-import-server/BUILD.bazel
  images/cdi-http-import-server/entrypoint.sh
  tests/utils.go
  tests/vmi_multus_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/L

#4343 Use new tag based release from kubevirtci
  cluster-up-sha.txt
  cluster-up/README.md
  cluster-up/cluster/ephemeral-provider-common.sh
  cluster-up/cluster/images.sh
  cluster-up/cluster/k8s-1.14/README.md
  cluster-up/cluster/k8s-1.14/provider.sh
  cluster-up/cluster/k8s-1.15/README.md
  cluster-up/cluster/k8s-1.15/provider.sh
  cluster-up/cluster/k8s-fedora-1.17.0/README.md
  cluster-up/cluster/k8s-fedora-1.17.0/provider.sh
  cluster-up/cluster/os-3.11.0-crio/README.md
  cluster-up/cluster/os-3.11.0-crio/provider.sh
  cluster-up/cluster/os-3.11.0-multus/README.md
  cluster-up/cluster/os-3.11.0-multus/provider.sh
  cluster-up/cluster/os-3.11.0/README.md
  cluster-up/cluster/os-3.11.0/provider.sh
  cluster-up/hack/common.sh
  cluster-up/kubectl.sh
  cluster-up/oc.sh
  cluster-up/version.txt
  hack/bump-kubevirtci.sh
  hack/config-default.sh
  hack/sync-kubevirtci.sh
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/L

#4355 Fix pull-kubevirt-apidocs lane
  hack/gen-swagger-doc/build.gradle
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#4296 tests: move ping to libnet and move expecter helpers to a new console package
  tests/BUILD.bazel
  tests/config_test.go
  tests/console/BUILD.bazel
  tests/console/console.go
  tests/console_test.go
  tests/container_disk_test.go
  tests/libnet/BUILD.bazel
  tests/libnet/ping.go
  tests/login.go
  tests/networkpolicy_test.go
  tests/pausing_test.go
  tests/restore_test.go
  tests/storage_test.go
  tests/utils.go
  tests/vmi_cloudinit_hook_sidecar_test.go
  tests/vmi_cloudinit_test.go
  tests/vmi_configuration_test.go
  tests/vmi_gpu_test.go
  tests/vmi_ignition_test.go
  tests/vmi_lifecycle_test.go
  tests/vmi_monitoring_test.go
  tests/vmi_multus_test.go
  tests/vmi_networking_test.go
  tests/vmi_servers.go
  tests/vmi_slirp_interface_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, sig/network, size/L

#4353 tests: Render test utils pod in the test namespace
  tests/utils.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#4151 Remove 'IsIPv6Cluster' function
  tests/migration_test.go
  tests/storage_test.go
  tests/utils.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M

#4357 Fix typos and formatting
  docs/getting-started.md
Labels: approved, dco-signoff: yes, lgtm, ok-to-test, release-note-none, size/M

#4288 Support DownwardAPI volum source
  api/openapi-spec/swagger.json
  cmd/virt-launcher/virt-launcher.go
  pkg/config/BUILD.bazel
  pkg/config/config.go
  pkg/config/downwardapi.go
  pkg/config/downwardapi_test.go
  pkg/virt-api/webhooks/validating-webhook/admitters/vmi-create-admitter.go
  pkg/virt-controller/services/template.go
  pkg/virt-launcher/virtwrap/api/converter.go
  pkg/virt-launcher/virtwrap/manager.go
  staging/src/kubevirt.io/client-go/api/v1/deepcopy_generated.go
  staging/src/kubevirt.io/client-go/api/v1/openapi_generated.go
  staging/src/kubevirt.io/client-go/api/v1/schema.go
  staging/src/kubevirt.io/client-go/api/v1/schema_swagger_generated.go
  staging/src/kubevirt.io/client-go/apis/snapshot/v1alpha1/openapi_generated.go
  tests/config_test.go
  tests/migration_test.go
  tests/utils.go
Labels: approved, dco-signoff: yes, kind/api-change, lgtm, release-note, size/XL

#4213 Don't mutate container disk permissions
  containerimages/BUILD.bazel
  pkg/virt-handler/container-disk/mount.go
  tests/container_disk_test.go
Labels: approved, dco-signoff: yes, kind/bug, lgtm, release-note-none, size/S

#4361 tests: Add missing asserts to the vmi-configuration tests
  tests/vmi_configuration_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#4370 Adapt conformance tests to support migration.
  automation/conformance.sh
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#4098 VM status to report whether volumes support snapshots.
  api/openapi-spec/swagger.json
  pkg/virt-controller/watch/snapshot/snapshot.go
  pkg/virt-controller/watch/snapshot/snapshot_base.go
  pkg/virt-controller/watch/snapshot/snapshot_test.go
  staging/src/kubevirt.io/client-go/api/v1/deepcopy_generated.go
  staging/src/kubevirt.io/client-go/api/v1/openapi_generated.go
  staging/src/kubevirt.io/client-go/api/v1/types.go
  staging/src/kubevirt.io/client-go/api/v1/types_swagger_generated.go
  staging/src/kubevirt.io/client-go/apis/snapshot/v1alpha1/openapi_generated.go
  tests/snapshot_test.go
Labels: approved, dco-signoff: yes, kind/api-change, lgtm, release-note-none, size/XL

#4010 Refactor all tests to use safe expect batcher and general prompt expression
  tests/config_test.go
  tests/console/console.go
  tests/container_disk_test.go
  tests/infra_test.go
  tests/login.go
  tests/migration_test.go
  tests/pausing_test.go
  tests/restore_test.go
  tests/storage_test.go
  tests/utils.go
  tests/vm_test.go
  tests/vmi_cloudinit_hook_sidecar_test.go
  tests/vmi_cloudinit_test.go
  tests/vmi_configuration_test.go
  tests/vmi_gpu_test.go
  tests/vmi_ignition_test.go
  tests/vmi_monitoring_test.go
  tests/vmi_multus_test.go
  tests/vmi_networking_test.go
  tests/vmi_slirp_interface_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XL

#4380 Bump kubevirtci to the latest with vIOMMU and sound card enabled
  cluster-up-sha.txt
  cluster-up/cluster/ephemeral-provider-common.sh
  cluster-up/hack/common.sh
  cluster-up/version.txt
  hack/config-default.sh
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/S

#4371 Update stale references in documentation (kubevirt-config ConfigMap, cluster/ scripts)
  docs/README.md
  docs/debugging.md
  docs/devel/storage.md
  docs/env-providers.md
  docs/software-emulation.md
  docs/sriov.md
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M

#4368 automation: remove ipv6 lane
  automation/test.sh
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#4374 Ignore VolumeSnapshot error status
  pkg/virt-controller/watch/snapshot/snapshot.go
  pkg/virt-controller/watch/snapshot/snapshot_test.go
  tests/BUILD.bazel
  tests/snapshot_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/L

#3257 Explain vm/i
  .gitignore
  api/api-rule-violations-known.list
  api/api-rule-violations.list
  api/openapi-spec/swagger.json
  hack/builder/Dockerfile
  hack/builder/version.sh
  hack/dockerized
  hack/generate.sh
  pkg/virt-operator/creation/components/BUILD.bazel
  pkg/virt-operator/creation/components/crds.go
  pkg/virt-operator/creation/components/crds_test.go
  pkg/virt-operator/creation/components/validations_generated.go
  pkg/virt-operator/install-strategy/BUILD.bazel
  pkg/virt-operator/install-strategy/strategy.go
  pkg/virt-operator/install-strategy/strategy_test.go
  pkg/virt-operator/kubevirt_test.go
  staging/src/kubevirt.io/client-go/api/v1/componentconfig.go
  staging/src/kubevirt.io/client-go/api/v1/doc.go
  staging/src/kubevirt.io/client-go/api/v1/openapi_generated.go
  staging/src/kubevirt.io/client-go/api/v1/schema.go
  staging/src/kubevirt.io/client-go/api/v1/schema_swagger_generated.go
  staging/src/kubevirt.io/client-go/api/v1/types.go
  staging/src/kubevirt.io/client-go/api/v1/types_swagger_generated.go
  staging/src/kubevirt.io/client-go/apis/snapshot/v1alpha1/openapi_generated.go
  staging/src/kubevirt.io/client-go/apis/snapshot/v1alpha1/types.go
  staging/src/kubevirt.io/client-go/apis/snapshot/v1alpha1/types_swagger_generated.go
  tests/BUILD.bazel
  tests/infra_test.go
  tests/kubectl_test.go
  tools/crd-validation-generator/BUILD.bazel
  tools/crd-validation-generator/validation-generator.go
  tools/csv-generator/csv-generator.go
  tools/resource-generator/resource-generator.go
Labels: approved, dco-signoff: yes, kind/api-change, kind/build-change, lgtm, ok-to-test, release-note, size/XXL

#4373 Serialize `make cluster-sync` build + deploy steps
  Makefile
  hack/cluster-build.sh
  hack/cluster-clean.sh
  hack/cluster-deploy.sh
Labels: approved, dco-signoff: yes, lgtm, ok-to-test, release-note-none, size/S

#4379 Fix artifacts in gosec target
  Makefile
  hack/dockerized
  hack/gosec.sh
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#4388 CONTRIBUTING: point developers to kubevirt-dev slack
  CONTRIBUTING.md
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#4378 [release-0.30] Fix MTU assignment on the masquerade binding
  pkg/virt-launcher/virtwrap/network/podinterface.go
  pkg/virt-launcher/virtwrap/network/podinterface_test.go
  tests/vmi_networking_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/L

#4132 Fix coexistance of scsi and sata drives
  pkg/virt-launcher/virtwrap/api/converter.go
  tests/storage_test.go
Labels: approved, dco-signoff: yes, lgtm, ok-to-test, release-note, size/M

#4390 tests, restore tests: check on successful commands
  tests/restore_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/S

#4392 DataVolume containerDisk import test.
  hack/cluster-deploy.sh
  manifests/testing/cdi-v1.23.7.yaml.in
  tests/datavolume_test.go
  tests/utils.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M

#2935 add macvtap BindingMechanism
  api/openapi-spec/swagger.json
  automation/test.sh
  examples/vmi-macvtap.yaml
  pkg/virt-api/webhooks/validating-webhook/admitters/vmi-create-admitter.go
  pkg/virt-api/webhooks/validating-webhook/admitters/vmi-create-admitter_test.go
  pkg/virt-config/feature-gates.go
  pkg/virt-launcher/virtwrap/api/converter.go
  pkg/virt-launcher/virtwrap/api/converter_test.go
  pkg/virt-launcher/virtwrap/network/podinterface.go
  pkg/virt-launcher/virtwrap/network/podinterface_test.go
  pkg/virt-operator/creation/components/validations_generated.go
  staging/src/kubevirt.io/client-go/api/v1/deepcopy_generated.go
  staging/src/kubevirt.io/client-go/api/v1/defaults.go
  staging/src/kubevirt.io/client-go/api/v1/openapi_generated.go
  staging/src/kubevirt.io/client-go/api/v1/schema.go
  staging/src/kubevirt.io/client-go/api/v1/schema_swagger_generated.go
  staging/src/kubevirt.io/client-go/apis/snapshot/v1alpha1/openapi_generated.go
  tests/BUILD.bazel
  tests/libvmi/network.go
  tests/migration.go
  tests/migration_test.go
  tests/utils.go
  tests/vmi_multus_test.go
  tools/vms-generator/utils/utils.go
  tools/vms-generator/vms-generator.go
Labels: approved, dco-signoff: yes, kind/api-change, kind/build-change, lgtm, ok-to-test, release-note, size/XL

#4386 Fix gosec issue: week random generator
  pkg/controller/virtinformers.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#4393 Disable service links on virt-launcher Pod
  pkg/virt-controller/services/template.go
Labels: approved, dco-signoff: yes, lgtm, needs-ok-to-test, release-note, size/XS

#4397 [release-0.34] Ignore VolumeSnapshot error status
  pkg/virt-controller/watch/snapshot/snapshot.go
  pkg/virt-controller/watch/snapshot/snapshot_test.go
  tests/BUILD.bazel
  tests/snapshot_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/L

#4399 Fix flaky timezone test
  tests/vmi_configuration_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#4400 Bump kubevirtci and with it runc
  cluster-up-sha.txt
  cluster-up/.gitignore
  cluster-up/hack/common.sh
  cluster-up/version.txt
  hack/config-default.sh
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#4389 tests: refactoring the custom PCI addressing test suite
  tests/vmi_configuration_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/L

#4306 tests, infra-test, Fix wrong error handling that mask real connectivity errors, and add missing vmi deletion.
  tests/infra_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/L

#4407 Remove utils.IsRunningOnKindInfraIPv6
  tests/BUILD.bazel
  tests/migration_test.go
  tests/utils.go
  tests/vmi_configuration_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M

#4417 fix wrong logic in SetDriverCacheMode log message
  pkg/virt-launcher/virtwrap/api/converter.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#4375 Fix infra-test nodes update logic
  tests/infra_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M

#4398 Let VMIRS detect VMIs in unknown state
  pkg/controller/conditions.go
  pkg/virt-controller/watch/BUILD.bazel
  pkg/virt-controller/watch/replicaset.go
  pkg/virt-controller/watch/replicaset_test.go
  pkg/virt-controller/watch/vmi.go
  pkg/virt-controller/watch/vmi_test.go
  staging/src/kubevirt.io/client-go/api/v1/types.go
  tests/replicaset_test.go
  tests/utils.go
Labels: approved, dco-signoff: yes, kind/api-change, lgtm, release-note, size/L

#4416 Test and build containerDisks with 107:107 ownership and 440 file mode
  containerimages/BUILD.bazel
  tests/container_disk_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M

#4419 Fix SRIOV lane: cancel CDI insecure registries check on sriov lane
  hack/cluster-deploy.sh
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M

#4307 tests, infra-test, Adapt infra_test to support dual stack
  tests/infra_test.go
  tests/libnet/ipaddress.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/L

#4424 Fix SRIOV lane: bump kubevirtci
  cluster-up-sha.txt
  cluster-up/cluster/kind/common.sh
  cluster-up/cluster/kind/manifests/kube-calico.diff.in
  cluster-up/cluster/kind/manifests/kube-calico.yaml.in
  cluster-up/cluster/kind/manifests/kube-flannel.yaml
  cluster-up/hack/common.sh
  cluster-up/version.txt
  hack/config-default.sh
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XL

#4437 Reduce the cluster size a little to see if flakiness reduces
  automation/test.sh
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#4439 Bump kubevirtci
  cluster-up-sha.txt
  cluster-up/cluster/kind-k8s-1.17.0-ipv6/README.md
  cluster-up/cluster/kind-k8s-1.17.0-ipv6/provider.sh
  cluster-up/cluster/kind/common.sh
  cluster-up/cluster/kind/manifests/kind-ipv6.yaml
  cluster-up/hack/common.sh
  cluster-up/version.txt
  hack/config-default.sh
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/L

#4415 Remove 'string' from json tag to preserve type information in our API
  api/openapi-spec/swagger.json
  pkg/virt-config/config-map.go
  pkg/virt-config/virt-config.go
  pkg/virt-controller/services/template.go
  pkg/virt-operator/creation/components/validations_generated.go
  staging/src/kubevirt.io/client-go/api/v1/openapi_generated.go
  staging/src/kubevirt.io/client-go/api/v1/types.go
  staging/src/kubevirt.io/client-go/apis/snapshot/v1alpha1/openapi_generated.go
Labels: approved, dco-signoff: yes, kind/api-change, lgtm, release-note-none, size/L

#4394 tests, pausing_test: change long process test
  tests/pausing_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M

#4425 Fix panic when endpoints were empty.
  tests/infra_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/S

#4426 Infra test made invalid assumptions about cluster composition
  tests/infra_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/S

#4001 sriov tests: configure sriov interface's by mac-address
  tests/vmi_multus_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/L

#4272 dual-stack, virtctl: expose ipv6 services
  pkg/virtctl/expose/expose.go
  pkg/virtctl/expose/expose_test.go
  tests/expose_test.go
  tests/job.go
  tests/network/services.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/XL

#4434 Bump cdi version to 1.25
  go.mod
  go.sum
  manifests/testing/cdi-v1.25.0.yaml.in
  staging/src/kubevirt.io/client-go/api/v1/openapi_generated.go
  staging/src/kubevirt.io/client-go/go.mod
  staging/src/kubevirt.io/client-go/go.sum
  tests/BUILD.bazel
  tests/operator_test.go
  vendor/github.com/go-logr/logr/README.md
  vendor/github.com/go-logr/logr/go.mod
  vendor/github.com/go-logr/logr/logr.go
  vendor/k8s.io/klog/v2/README.md
  vendor/k8s.io/klog/v2/go.mod
  vendor/k8s.io/klog/v2/go.sum
  vendor/k8s.io/klog/v2/klog.go
  vendor/k8s.io/klog/v2/klog_file.go
  vendor/kubevirt.io/containerized-data-importer/pkg/apis/core/v1alpha1/BUILD.bazel
  vendor/kubevirt.io/containerized-data-importer/pkg/apis/core/v1alpha1/openapi_generated.go
  vendor/kubevirt.io/containerized-data-importer/pkg/apis/core/v1alpha1/types.go
  vendor/kubevirt.io/containerized-data-importer/pkg/apis/core/v1alpha1/types_swagger_generated.go
  vendor/kubevirt.io/containerized-data-importer/pkg/apis/core/v1alpha1/utils.go
  vendor/kubevirt.io/containerized-data-importer/pkg/apis/core/v1alpha1/zz_generated.deepcopy.go
  vendor/kubevirt.io/containerized-data-importer/pkg/clone/BUILD.bazel
  vendor/kubevirt.io/containerized-data-importer/pkg/clone/auth.go
  vendor/kubevirt.io/controller-lifecycle-operator-sdk/LICENSE
  vendor/kubevirt.io/controller-lifecycle-operator-sdk/pkg/sdk/api/BUILD.bazel
  vendor/kubevirt.io/controller-lifecycle-operator-sdk/pkg/sdk/api/types.go
  vendor/modules.txt
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XXL

#4449 Catch goroutine panic with GinkgoRecover in tests
  tests/utils.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#4438 SRIOV lane: skip flaky tests
  tests/vmi_multus_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#4453 Ensure that we restore the cdi-insecure-registry configmap in tests
  tests/utils.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M

#4409 Improve memory overhead accounting
  pkg/virt-api/webhooks/mutating-webhook/mutators/vmi-mutator.go
  pkg/virt-api/webhooks/mutating-webhook/mutators/vmi-mutator_test.go
  pkg/virt-controller/services/template.go
  pkg/virt-controller/services/template_test.go
  pkg/virt-launcher/virtwrap/api/converter.go
  pkg/virt-launcher/virtwrap/api/converter_test.go
  tests/vmi_configuration_test.go
  tests/vmi_lifecycle_test.go
  tests/vmipreset_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/L
