Repository kubevirt/kubevirt, pull requests merged in 2020-12, with the labels that each got.

#4592 Bump atlassian/bazel-tools
  WORKSPACE
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#4606 Test sriov increase ping retries
  tests/vmi_multus_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/S

#4599 add webhook to validate kubevirt CR updates
  pkg/virt-api/api.go
  pkg/virt-api/webhooks/utils.go
  pkg/virt-api/webhooks/validating-webhook/admitters/BUILD.bazel
  pkg/virt-api/webhooks/validating-webhook/admitters/kubevirt-update-admitter-test.go
  pkg/virt-api/webhooks/validating-webhook/admitters/kubevirt-update-admitter.go
  pkg/virt-api/webhooks/validating-webhook/validating-webhook.go
  pkg/virt-operator/creation/components/webhooks.go
  tests/operator_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/L

#4591 VMI configuration test: fix disk cache modes testing
  tests/vmi_configuration_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/S

#4622 Consume nightly build images from quay
  hack/ci/entrypoint.sh
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#4517 Fix timed domain resync
  pkg/virt-launcher/virtwrap/manager.go
  pkg/virt-launcher/virtwrap/manager_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/L

#4476 tests, gpu: Do not mount /sys/devices/ for SRIOV devices
  cmd/virt-handler/virt_launcher.cil
  pkg/virt-controller/services/template.go
  pkg/virt-controller/services/template_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M

#4582 fix gosec issue: Subprocess launched with variable
  pkg/cloud-init/cloud-init.go
  pkg/config/config.go
  pkg/emptydisk/emptydisk.go
  pkg/ephemeral-disk/ephemeral-disk.go
  pkg/virt-handler/container-disk/mount.go
  pkg/virt-handler/selinux/labels.go
  pkg/virt-launcher/virtwrap/api/converter.go
  pkg/virt-launcher/virtwrap/network/common.go
  pkg/virt-launcher/virtwrap/util/libvirt_helper.go
  pkg/virtctl/vnc/vnc.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/S

#4609 tests, libvmi, vmi: shorten random vm names #2
  tests/libvmi/vmi.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#4396 Explain Kubevirt
  api/api-rule-violations-known.list
  api/api-rule-violations.list
  api/openapi-spec/swagger.json
  manifests/generated/kv-resource.yaml
  pkg/virt-operator/creation/components/crds.go
  pkg/virt-operator/creation/components/crds_test.go
  pkg/virt-operator/creation/components/validations_generated.go
  staging/src/kubevirt.io/client-go/api/v1/openapi_generated.go
  staging/src/kubevirt.io/client-go/api/v1/types.go
  staging/src/kubevirt.io/client-go/api/v1/types_swagger_generated.go
  staging/src/kubevirt.io/client-go/apis/snapshot/v1alpha1/openapi_generated.go
  tests/infra_test.go
  tests/kubectl_test.go
  tests/operator_test.go
Labels: approved, dco-signoff: yes, kind/api-change, lgtm, release-note, size/XXL

#4623 If the fedora login expecter is stuck, retry
  tests/console/login.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/S

#4625 Reject --access-mode ReadOnlyMany when uploading an image.
  pkg/virtctl/imageupload/imageupload.go
  pkg/virtctl/imageupload/imageupload_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/S

#4546 Failure detection and handling when EFI without SB is not available
  pkg/virt-handler/vm.go
  pkg/virt-launcher/virtwrap/api/converter.go
  pkg/virt-launcher/virtwrap/manager.go
  tests/utils.go
  tests/vmi_configuration_test.go
Labels: approved, dco-signoff: yes, lgtm, ok-to-test, release-note, size/L

#4611 tests, Use RandName for creating random VMI names
  tests/libvmi/vmi.go
  tests/utils.go
  tests/vmi_networking_test.go
  tests/vmi_slirp_interface_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/S

#4620 tests, multus: Fix SRIOV link and IP address configuration
  tests/vmi_multus_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M

#4633 Cleanup k8s jobs from test namespaces
  tests/utils.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#4645 Re introduce net admin
  pkg/virt-controller/services/template.go
  pkg/virt-controller/services/template_test.go
  pkg/virt-launcher/virtwrap/network/podinterface.go
  pkg/virt-launcher/virtwrap/network/podinterface_test.go
  pkg/virt-operator/creation/components/scc.go
  tests/security_features_test.go
  tests/utils.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/M

#4617 update listType markers for kubevirt pci host devices
  api/api-rule-violations-known.list
  api/api-rule-violations.list
  api/openapi-spec/swagger.json
  manifests/generated/kv-resource.yaml
  pkg/virt-operator/creation/components/validations_generated.go
  staging/src/kubevirt.io/client-go/api/v1/openapi_generated.go
  staging/src/kubevirt.io/client-go/api/v1/types.go
  staging/src/kubevirt.io/client-go/api/v1/types_swagger_generated.go
  staging/src/kubevirt.io/client-go/apis/snapshot/v1alpha1/openapi_generated.go
Labels: approved, dco-signoff: yes, kind/api-change, lgtm, release-note-none, size/M

#4652 dev guide, networking: Update the doc net_admin is still required
  docs/devel/networking.md
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#3349 KubeVirt v1 GA api
  api/openapi-spec/swagger.json
  examples/migration-job.yaml
  examples/vm-alpine-datavolume.yaml
  examples/vm-alpine-multipvc.yaml
  examples/vm-cirros.yaml
  examples/vm-priorityclass.yaml
  examples/vm-template-fedora.yaml
  examples/vm-template-rhel7.yaml
  examples/vm-template-windows2012r2.yaml
  examples/vmi-alpine-efi.yaml
  examples/vmi-block-pvc.yaml
  examples/vmi-ephemeral.yaml
  examples/vmi-fedora.yaml
  examples/vmi-flavor-small.yaml
  examples/vmi-gpu.yaml
  examples/vmi-host-disk.yaml
  examples/vmi-macvtap.yaml
  examples/vmi-masquerade.yaml
  examples/vmi-migratable.yaml
  examples/vmi-multus-multiple-net.yaml
  examples/vmi-multus-ptp.yaml
  examples/vmi-nocloud.yaml
  examples/vmi-preset-small.yaml
  examples/vmi-pvc.yaml
  examples/vmi-replicaset-cirros.yaml
  examples/vmi-sata.yaml
  examples/vmi-secureboot.yaml
  examples/vmi-slirp.yaml
  examples/vmi-sriov.yaml
  examples/vmi-windows.yaml
  examples/vmi-with-sidecar-hook.yaml
  manifests/generated/kubevirt-cr.yaml.in
  manifests/generated/kv-resource.yaml
  manifests/generated/operator-csv.yaml.in
  pkg/virt-api/api.go
  pkg/virt-api/webhooks/mutating-webhook/mutators/preset_test.go
  pkg/virt-operator/creation/components/BUILD.bazel
  pkg/virt-operator/creation/components/apiservices_test.go
  pkg/virt-operator/creation/components/webhooks.go
  pkg/virt-operator/creation/csv/BUILD.bazel
  pkg/virt-operator/creation/csv/csv.go
  pkg/virt-operator/kubevirt_test.go
  staging/src/kubevirt.io/client-go/api/v1/register.go
  staging/src/kubevirt.io/client-go/api/v1/schema_test.go
  tests/infra_test.go
  tests/operator_test.go
  tests/replicaset_test.go
  tests/vm_test.go
  tests/vmi_lifecycle_test.go
  tests/vmipreset_test.go
Labels: approved, dco-signoff: yes, kind/api-change, lgtm, release-note, size/XXL

#4626 tests, sriov: XFail IPv6 connectivity test
  tests/BUILD.bazel
  tests/assert/BUILD.bazel
  tests/assert/xfail.go
  tests/vmi_multus_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M

#4656 Evacuation controller improvement
  pkg/virt-controller/watch/drain/evacuation/evacuation.go
  pkg/virt-controller/watch/drain/evacuation/evacuation_test.go
  staging/src/kubevirt.io/client-go/api/v1/types.go
Labels: approved, dco-signoff: yes, kind/api-change, lgtm, release-note-none, size/M

#4637 add Kubermatic to adopters list
  ADOPTERS.md
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#4644 move kv update validation webhook to operator validation configuration
  pkg/util/webhooks/validating-webhooks/validating-webhook.go
  pkg/virt-api/api.go
  pkg/virt-api/webhooks/validating-webhook/admitters/BUILD.bazel
  pkg/virt-api/webhooks/validating-webhook/admitters/pod-eviction-admitter.go
  pkg/virt-api/webhooks/validating-webhook/validating-webhook.go
  pkg/virt-operator/application.go
  pkg/virt-operator/creation/components/webhooks.go
  pkg/virt-operator/webhooks/BUILD.bazel
  pkg/virt-operator/webhooks/kubevirt-update-admitter-test.go
  pkg/virt-operator/webhooks/kubevirt-update-admitter.go
  tests/k8s-reporter/1_events.log
  tests/operator_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/L

#4661 windows_test: remove duplicate code
  tests/windows_test.go
Labels: approved, dco-signoff: yes, lgtm, needs-ok-to-test, release-note-none, size/XS

#4653 cloud-init: Allow populate networkData alone
  pkg/cloud-init/cloud-init.go
  pkg/cloud-init/cloud-init_test.go
  pkg/virt-api/webhooks/validating-webhook/admitters/vmi-create-admitter.go
  pkg/virt-api/webhooks/validating-webhook/admitters/vmi-create-admitter_test.go
  tests/vmi_cloudinit_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/L

#4657 virt-launcher, converter: Remove vCPU dependency on queue limits
  pkg/virt-launcher/virtwrap/api/converter.go
  pkg/virt-launcher/virtwrap/network/podinterface.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/S

#4648 update libvirt base container to rhel-av 8.3
  WORKSPACE
  tests/operator_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/M

#4660 Cleanup tempfiles
  pkg/virt-launcher/virtwrap/manager_test.go
  pkg/virt-launcher/virtwrap/network/common_test.go
Labels: approved, dco-signoff: yes, lgtm, needs-ok-to-test, release-note-none, size/S

#4574 Fix gosec issue: Potential file inclusion via variable
  pkg/certificates/bootstrap/cert-manager.go
  pkg/certificates/triple/cert/cert.go
  pkg/cloud-init/cloud-init.go
  pkg/ephemeral-disk-utils/utils.go
  pkg/util/net/ip/ip.go
  pkg/virt-handler/cache/cache.go
  pkg/virt-handler/container-disk/mount.go
  pkg/virt-handler/device-manager/common.go
  pkg/virt-handler/device-manager/mediated_device.go
  pkg/virt-handler/selinux/labels.go
  pkg/virt-handler/vm.go
  pkg/virt-launcher/monitor.go
  pkg/virt-launcher/virtwrap/api/converter.go
  pkg/virt-launcher/virtwrap/util/libvirt_helper.go
  pkg/virtctl/imageupload/imageupload.go
  pkg/watchdog/watchdog.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/L

#4668 Fix eventually and improve watcher
  tests/utils.go
  tests/vm_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/S

#4671 Append rootfs mount to containerdisk base path
  pkg/virt-handler/container-disk/mount.go
Labels: approved, dco-signoff: yes, lgtm, needs-ok-to-test, release-note-none, size/XS

#4504 Fix gosec issue: unhandled errors in delete.go & create.go
  pkg/controller/expectations.go
  pkg/virt-operator/install-strategy/delete.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M

#4674 tests, sriov: XFail IPv4 connectivity test
  tests/vmi_multus_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#4619 [release-0.36] add webhook to validate kubevirt CR updates
  pkg/util/webhooks/validating-webhooks/validating-webhook.go
  pkg/virt-api/webhooks/utils.go
  pkg/virt-api/webhooks/validating-webhook/admitters/BUILD.bazel
  pkg/virt-api/webhooks/validating-webhook/admitters/pod-eviction-admitter.go
  pkg/virt-operator/application.go
  pkg/virt-operator/creation/components/webhooks.go
  pkg/virt-operator/webhooks/BUILD.bazel
  pkg/virt-operator/webhooks/kubevirt-update-admitter-test.go
  pkg/virt-operator/webhooks/kubevirt-update-admitter.go
  tests/k8s-reporter/1_events.log
  tests/operator_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/L

#4695 Generate release manifests using quay images
  .travis.yml
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#4688 Add @maiqueb to code-reviewers list
  OWNERS_ALIASES
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#4680 Fix sidecar example
  cmd/example-hook-sidecar/smbios.go
  examples/vmi-with-sidecar-hook.yaml
  tests/vmi_hook_sidecar_test.go
  tools/vms-generator/utils/utils.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M

#4676 virt-launcher, converter: Set SRIOV device as unmanaged
  pkg/virt-launcher/virtwrap/api/converter.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#4685 virt-launcher, libvirt: Free (all) domain resources (fix leaks)
  pkg/virt-launcher/virtwrap/access-credentials/access_credentials.go
  pkg/virt-launcher/virtwrap/cli/libvirt.go
  pkg/virt-launcher/virtwrap/manager.go
  pkg/virt-launcher/virtwrap/manager_test.go
  pkg/virt-launcher/virtwrap/postcopy.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/L

#4675 only validate status of vm, vmi, and vmi migration objects
  pkg/virt-operator/creation/components/webhooks.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#4697 use placement api for assinging virt-handler pod
  tests/vmi_lifecycle_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M

#4311 Launcher converter vm2domain refactor some network parts
  pkg/virt-launcher/virtwrap/api/converter.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, sig/network, size/L

#3479 Test sriov over vlan
  tests/utils.go
  tests/vmi_multus_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M

#4710 Fix rpm dependency chaos for test images
  .gitignore
  BUILD.bazel
  Makefile
  WORKSPACE
  docs/updating-dependencies.md
  hack/dockerized
  hack/rpm-deps.sh
  images/BUILD.bazel
  images/cdi-http-import-server/BUILD.bazel
  images/disks-images-provider/BUILD.bazel
  images/vm-killer/BUILD.bazel
  repo.yaml
  rpm/BUILD.bazel
  tests/job.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XXL

#4681 Don't overwrite user-provided GOFLAGS
  hack/common.sh
Labels: approved, dco-signoff: yes, lgtm, ok-to-test, release-note-none, size/XS

#4669 add linux nodeSelector to kubevirt-cr
  pkg/virt-operator/install-strategy/create.go
  pkg/virt-operator/install-strategy/create_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/M

#4709 tests, ping: increase default amount of packets
  tests/libnet/ping.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#4704 Add mountinfo unit tests
  pkg/virt-handler/container-disk/mount.go
  pkg/virt-handler/isolation/BUILD.bazel
  pkg/virt-handler/isolation/isolation.go
  pkg/virt-handler/isolation/isolation_test.go
  pkg/virt-handler/isolation/testdata/mountinfo/btrfs_host
  pkg/virt-handler/isolation/testdata/mountinfo/btrfs_launcher
  pkg/virt-handler/isolation/testdata/mountinfo/devicemapper_host
  pkg/virt-handler/isolation/testdata/mountinfo/devicemapper_launcher
  pkg/virt-handler/isolation/testdata/mountinfo/overlay_host
  pkg/virt-handler/isolation/testdata/mountinfo/overlay_launcher
Labels: approved, dco-signoff: yes, lgtm, ok-to-test, release-note-none, size/XL

#4714 add H3C to the list of ADOPTERS
  ADOPTERS.md
Labels: approved, dco-signoff: yes, lgtm, ok-to-test, release-note-none, size/XS

#4724 cloud-init, GenerateLocalData: simplify iso staging
  pkg/cloud-init/cloud-init.go
  pkg/cloud-init/cloud-init_test.go
  pkg/ephemeral-disk-utils/BUILD.bazel
  pkg/ephemeral-disk-utils/utils.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M

#4641 Fix test id for IO driver mode test
  tests/vmi_configuration_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#4727 virtctl, imageupload: improve nosec comment
  pkg/virtctl/imageupload/imageupload.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS
