Repository kubevirt/kubevirt, pull requests merged in 2020-08, with the labels that each got.

#3562 Re-enabling test pointing to #2272
  tests/migration_test.go
  tests/storage_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/S

#3880 virtctl cli error handling
  pkg/virtctl/console/console.go
  pkg/virtctl/expose/expose.go
  pkg/virtctl/expose/expose_test.go
  pkg/virtctl/pause/pause.go
  pkg/virtctl/pause/pause_test.go
  pkg/virtctl/templates/BUILD.bazel
  pkg/virtctl/templates/templates.go
  pkg/virtctl/version/version.go
  pkg/virtctl/vm/vm.go
  pkg/virtctl/vm/vm_test.go
  pkg/virtctl/vnc/vnc.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/L

#3884 [tests] eliminate some false positives
  tests/utils.go
  tests/vmi_configuration_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M

#3893 Domain notify resync period
  cmd/virt-handler/virt-handler.go
  pkg/virt-handler/cache/cache.go
  pkg/virt-handler/cache/cache_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/L

#3905 flaky-finder: fix leading pipe bug
  automation/repeated_test.sh
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#3914 Bump kubevirtci
  cluster-up-sha.txt
  cluster-up/cluster/images.sh
  cluster-up/cluster/ocp-4.3/README.md
  cluster-up/cluster/ocp-4.3/provider.sh
  cluster-up/cluster/ocp-4.4/README.md
  cluster-up/cluster/ocp-4.4/provider.sh
  cluster-up/cluster/okd-4.1/README.md
  cluster-up/cluster/okd-4.1/provider.sh
  cluster-up/cluster/okd-4.2/README.md
  cluster-up/cluster/okd-4.2/provider.sh
  cluster-up/cluster/okd-4.3/README.md
  cluster-up/cluster/okd-4.3/provider.sh
  cluster-up/cluster/openshift-provider-common.sh
  cluster-up/container.sh
  cluster-up/hack/common.sh
  cluster-up/ssh.sh
  cluster-up/version.txt
  hack/config-default.sh
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XL

#3918 Add cluster-up to bazel exclude list
  hack/bazel-generate.sh
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#3921 fix memory units in libvirt xml
  pkg/virt-launcher/virtwrap/api/converter.go
  pkg/virt-launcher/virtwrap/api/converter_test.go
  tests/vmi_configuration_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/M

#3568 Expose guest swap metrics
  api/openapi-spec/swagger.json
  pkg/handler-launcher-com/cmd/v1/cmd.pb.go
  pkg/handler-launcher-com/cmd/v1/cmd.proto
  pkg/virt-config/config-map.go
  pkg/virt-config/config_test.go
  pkg/virt-config/virt-config.go
  pkg/virt-handler/vm.go
  pkg/virt-launcher/virtwrap/api/converter.go
  pkg/virt-launcher/virtwrap/api/converter_test.go
  pkg/virt-launcher/virtwrap/api/deepcopy_generated.go
  pkg/virt-launcher/virtwrap/api/deepcopy_test.go
  pkg/virt-launcher/virtwrap/api/defaults.go
  pkg/virt-launcher/virtwrap/api/pci-placement.go
  pkg/virt-launcher/virtwrap/api/schema.go
  pkg/virt-launcher/virtwrap/api/schema_test.go
  pkg/virt-launcher/virtwrap/manager.go
  pkg/virt-launcher/virtwrap/manager_test.go
  staging/src/kubevirt.io/client-go/api/v1/deepcopy_generated.go
  staging/src/kubevirt.io/client-go/api/v1/openapi_generated.go
  staging/src/kubevirt.io/client-go/api/v1/schema.go
  staging/src/kubevirt.io/client-go/api/v1/schema_swagger_generated.go
  staging/src/kubevirt.io/client-go/api/v1/types.go
  staging/src/kubevirt.io/client-go/apis/snapshot/v1alpha1/openapi_generated.go
  tests/infra_test.go
  tests/vmi_configuration_test.go
  tests/vmidefaults_test.go
Labels: approved, dco-signoff: yes, kind/api-change, lgtm, release-note, size/XL

#3859 tests: Create flags and containerdisk sub-package
  tests/BUILD.bazel
  tests/config.go
  tests/config_test.go
  tests/console_test.go
  tests/container_disk_test.go
  tests/containerdisk/BUILD.bazel
  tests/containerdisk/containerdisk.go
  tests/datavolume_test.go
  tests/expose_test.go
  tests/flags/BUILD.bazel
  tests/flags/flags.go
  tests/imageupload_test.go
  tests/infra_test.go
  tests/migration_test.go
  tests/networkpolicy_test.go
  tests/operator_test.go
  tests/pausing_test.go
  tests/probes_test.go
  tests/replicaset_test.go
  tests/reporter/BUILD.bazel
  tests/reporter/kubernetes.go
  tests/security_features_test.go
  tests/snapshot_test.go
  tests/stability_test.go
  tests/storage_test.go
  tests/subresource_api_test.go
  tests/template_test.go
  tests/utils.go
  tests/virt_control_plane_test.go
  tests/vm_test.go
  tests/vm_watch_test.go
  tests/vmi_cloudinit_hook_sidecar_test.go
  tests/vmi_cloudinit_test.go
  tests/vmi_configuration_test.go
  tests/vmi_gpu_test.go
  tests/vmi_headless_test.go
  tests/vmi_hook_sidecar_test.go
  tests/vmi_ignition_test.go
  tests/vmi_iothreads_test.go
  tests/vmi_lifecycle_test.go
  tests/vmi_multiqueue_test.go
  tests/vmi_multus_test.go
  tests/vmi_networking_test.go
  tests/vmi_slirp_interface_test.go
  tests/vmipreset_test.go
  tests/windows_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XL

#3925 Bump kubevirtci to support dual stack on k8s-1.18
  cluster-up-sha.txt
  cluster-up/cluster/images.sh
  cluster-up/version.txt
  hack/config-default.sh
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#3919 Give the VM rename operation more time to create a new VM
  tests/vm_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#3889 Enable CR status subresource (take 2)
  manifests/generated/kv-resource.yaml
  manifests/generated/operator-csv.yaml.in
  manifests/generated/rbac-operator.authorization.k8s.yaml.in
  pkg/util/status/BUILD.bazel
  pkg/util/status/status.go
  pkg/util/status/status_suite_test.go
  pkg/util/status/status_test.go
  pkg/util/webhooks/BUILD.bazel
  pkg/util/webhooks/webhooks.go
  pkg/virt-api/api.go
  pkg/virt-api/rest/BUILD.bazel
  pkg/virt-api/rest/subresource.go
  pkg/virt-api/rest/subresource_test.go
  pkg/virt-api/webhooks/BUILD.bazel
  pkg/virt-api/webhooks/mutating-webhook/mutators/BUILD.bazel
  pkg/virt-api/webhooks/mutating-webhook/mutators/vmi-mutator.go
  pkg/virt-api/webhooks/mutating-webhook/mutators/vmi-mutator_test.go
  pkg/virt-api/webhooks/utils.go
  pkg/virt-api/webhooks/validating-webhook/admitters/BUILD.bazel
  pkg/virt-api/webhooks/validating-webhook/admitters/status-admitter.go
  pkg/virt-api/webhooks/validating-webhook/admitters/vmi-create-admitter.go
  pkg/virt-api/webhooks/validating-webhook/admitters/vmi-update-admitter.go
  pkg/virt-api/webhooks/validating-webhook/admitters/vms-admitter.go
  pkg/virt-api/webhooks/validating-webhook/validating-webhook.go
  pkg/virt-controller/watch/BUILD.bazel
  pkg/virt-controller/watch/migration.go
  pkg/virt-controller/watch/migration_test.go
  pkg/virt-controller/watch/replicaset.go
  pkg/virt-controller/watch/replicaset_test.go
  pkg/virt-controller/watch/snapshot.go
  pkg/virt-controller/watch/snapshot_test.go
  pkg/virt-controller/watch/vm.go
  pkg/virt-controller/watch/vm_test.go
  pkg/virt-operator/BUILD.bazel
  pkg/virt-operator/creation/components/crds.go
  pkg/virt-operator/creation/components/webhooks.go
  pkg/virt-operator/creation/rbac/apiserver.go
  pkg/virt-operator/install-strategy/BUILD.bazel
  pkg/virt-operator/install-strategy/create.go
  pkg/virt-operator/install-strategy/create_test.go
  pkg/virt-operator/kubevirt.go
  pkg/virt-operator/kubevirt_test.go
  staging/src/kubevirt.io/client-go/kubecli/generated_mock_kubevirt.go
  staging/src/kubevirt.io/client-go/kubecli/kubevirt.go
  staging/src/kubevirt.io/client-go/kubecli/kv.go
  staging/src/kubevirt.io/client-go/kubecli/migration.go
  staging/src/kubevirt.io/client-go/kubecli/replicaset.go
  staging/src/kubevirt.io/client-go/kubecli/vm.go
  tests/vm_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/XXL

#3890 Update the vmiMetrics struct with better attributes
  pkg/monitoring/vms/prometheus/prometheus.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/L

#3882 Safe expect batch
  tests/config_test.go
  tests/container_disk_test.go
  tests/pausing_test.go
  tests/storage_test.go
  tests/utils.go
  tests/vmi_cloudinit_hook_sidecar_test.go
  tests/vmi_cloudinit_test.go
  tests/vmi_configuration_test.go
  tests/vmi_gpu_test.go
  tests/vmi_lifecycle_test.go
  tests/vmi_monitoring_test.go
  tests/vmi_multus_test.go
  tests/vmi_networking_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/L

#3939 Shorten the release job exectuion time on travis
  automation/travisci-test.sh
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/S

#3941 Add openapi validatior unit tests
  pkg/util/openapi/BUILD.bazel
  pkg/util/openapi/openapi_suite_test.go
  pkg/util/openapi/openapi_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M

#3923 Add support to configure vmi disk I/O mode options
  api/openapi-spec/swagger.json
  pkg/virt-api/webhooks/validating-webhook/admitters/vmi-create-admitter.go
  pkg/virt-api/webhooks/validating-webhook/admitters/vmi-create-admitter_test.go
  pkg/virt-launcher/virtwrap/api/converter.go
  pkg/virt-launcher/virtwrap/api/converter_test.go
  staging/src/kubevirt.io/client-go/api/v1/openapi_generated.go
  staging/src/kubevirt.io/client-go/api/v1/schema.go
  staging/src/kubevirt.io/client-go/api/v1/schema_swagger_generated.go
  staging/src/kubevirt.io/client-go/api/v1/types.go
  staging/src/kubevirt.io/client-go/apis/snapshot/v1alpha1/openapi_generated.go
Labels: approved, dco-signoff: yes, kind/api-change, lgtm, release-note, size/M

#3954 tests, Fix test 1780 of vmi_networking_test.go
  tests/vmi_networking_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#3953 tests: avoid line wrap on fedora console
  tests/utils.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#3946 Remove exec readiness probes in kubevirt
  cmd/container-disk-v2alpha/main.c
  cmd/virt-launcher/virt-launcher.go
  pkg/container-disk/container-disk.go
  pkg/container-disk/container-disk_test.go
  pkg/testutils/mock_queue.go
  pkg/virt-controller/services/template.go
  pkg/virt-controller/services/template_test.go
  pkg/virt-controller/watch/vmi.go
  pkg/virt-controller/watch/vmi_test.go
  pkg/virt-handler/BUILD.bazel
  pkg/virt-handler/cmd-client/client.go
  pkg/virt-handler/container-disk/BUILD.bazel
  pkg/virt-handler/container-disk/generated_mock_mount.go
  pkg/virt-handler/container-disk/mount.go
  pkg/virt-handler/container-disk/mount_test.go
  pkg/virt-handler/vm.go
  pkg/virt-handler/vm_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XL

#3961 Add test approvers
  OWNERS_ALIASES
  tests/OWNERS
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#3960 Let prow run make generate instead of travis
  automation/travisci-test.sh
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#3883 tests: Ping from VM console refactoring
  tests/BUILD.bazel
  tests/ping.go
  tests/vmi_multus_test.go
  tests/vmi_networking_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/L

#3966 [cherrypick to release-0.30] QEMU supports 3 disk I/O modes:
  api/openapi-spec/swagger.json
  pkg/virt-api/webhooks/validating-webhook/admitters/vmi-create-admitter.go
  pkg/virt-api/webhooks/validating-webhook/admitters/vmi-create-admitter_test.go
  pkg/virt-launcher/virtwrap/api/converter.go
  pkg/virt-launcher/virtwrap/api/converter_test.go
  staging/src/kubevirt.io/client-go/api/v1/openapi_generated.go
  staging/src/kubevirt.io/client-go/api/v1/schema.go
  staging/src/kubevirt.io/client-go/api/v1/schema_swagger_generated.go
  staging/src/kubevirt.io/client-go/api/v1/types.go
Labels: approved, dco-signoff: yes, kind/api-change, lgtm, release-note, size/M

#3971 [release-0.30] Remove exec readiness probes in kubevirt
  cmd/container-disk-v2alpha/main.c
  cmd/virt-launcher/virt-launcher.go
  pkg/container-disk/container-disk.go
  pkg/container-disk/container-disk_test.go
  pkg/testutils/mock_queue.go
  pkg/virt-controller/services/template.go
  pkg/virt-controller/services/template_test.go
  pkg/virt-controller/watch/vmi.go
  pkg/virt-controller/watch/vmi_test.go
  pkg/virt-handler/BUILD.bazel
  pkg/virt-handler/cmd-client/client.go
  pkg/virt-handler/container-disk/BUILD.bazel
  pkg/virt-handler/container-disk/generated_mock_mount.go
  pkg/virt-handler/container-disk/mount.go
  pkg/virt-handler/container-disk/mount_test.go
  pkg/virt-handler/vm.go
  pkg/virt-handler/vm_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XL

#3947 Improve ExpectBatchWithValidatedSend error handling
  tests/utils.go
  tests/vmi_networking_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/S

#3973 Fix clock timezone
  pkg/virt-launcher/virtwrap/api/converter.go
  pkg/virt-launcher/virtwrap/api/converter_test.go
  pkg/virt-launcher/virtwrap/api/schema.go
  tests/vmi_configuration_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/M

#3952 Avoid local cleanup of vmi until vmi is in a finalized state
  pkg/virt-handler/vm.go
  pkg/virt-handler/vm_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/M

#3938 Kubernetes-reporter: Get all ConfigMaps
  tests/reporter/kubernetes.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#3956 tests: "utils.RetValue" no need to pass prompt
  tests/config_test.go
  tests/container_disk_test.go
  tests/pausing_test.go
  tests/ping.go
  tests/storage_test.go
  tests/utils.go
  tests/vmi_cloudinit_hook_sidecar_test.go
  tests/vmi_cloudinit_test.go
  tests/vmi_configuration_test.go
  tests/vmi_gpu_test.go
  tests/vmi_monitoring_test.go
  tests/vmi_multus_test.go
  tests/vmi_networking_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/L

#3899 Improve expose test
  tests/BUILD.bazel
  tests/expose_test.go
  tests/job.go
  tests/storage_test.go
  tests/utils.go
  tests/vmi_lifecycle_test.go
  tests/vmi_networking_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/L

#3916 Keep network e2e tests in a dedicated module
  OWNERS_ALIASES
  tests/BUILD.bazel
  tests/network/BUILD.bazel
  tests/network/OWNERS
  tests/network/framework.go
  tests/network/primary_pod_network.go
  tests/tests_suite_test.go
  tests/vmi_networking_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/L, topic/network

#3864 Use 'kill' instead of 'killall' for notify connection resilience func test.
  tests/migration_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M

#3982 A low value of timeout in test setup causes failure in Azure.
  tests/vm_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#3940 Add all the missing test-ids
  tests/console_test.go
  tests/imageupload_test.go
  tests/infra_test.go
  tests/operator_test.go
  tests/pausing_test.go
  tests/snapshot_test.go
  tests/storage_test.go
  tests/version_test.go
  tests/vm_test.go
  tests/vmi_cloudinit_test.go
  tests/vmi_configuration_test.go
  tests/vmi_gpu_test.go
  tests/vmi_monitoring_test.go
  tests/vmi_multiqueue_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/L

#3957 Dual stack config iptables
  pkg/virt-launcher/virtwrap/network/BUILD.bazel
  pkg/virt-launcher/virtwrap/network/common.go
  pkg/virt-launcher/virtwrap/network/generated_mock_common.go
  pkg/virt-launcher/virtwrap/network/podinterface.go
  pkg/virt-launcher/virtwrap/network/podinterface_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/M

#3972 tests, console_test: use safe expect batcher
  tests/console_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#3992 Remove hidden `make generate` invocations
  Makefile
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#4007 Fix flaky certificate expiration unit test
  pkg/virt-operator/creation/components/secrets_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#4015 tests: Add phoracek to approvers
  OWNERS_ALIASES
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#4021 Add --security-opt label:disable to bazel server version check
  hack/dockerized
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#4020 Fix tests binary release
  .travis.yml
  Makefile
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/S

#3997 tests, job: Use status condition to detect success/failure and expose arguments
  tests/job.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M

#3791 check for readiness of device manager plugin
  cmd/virt-handler/BUILD.bazel
  cmd/virt-handler/virt-handler.go
  pkg/virt-handler/device-manager/device_controller.go
  pkg/virt-handler/device-manager/device_controller_test.go
  pkg/virt-handler/device-manager/generic_device.go
  pkg/virt-handler/vm.go
  tests/vmi_lifecycle_test.go
Labels: approved, dco-signoff: yes, kind/build-change, lgtm, release-note, size/L

#3875 Add ProductName and Version labels to KubeVirt objects
  api/openapi-spec/swagger.json
  pkg/virt-operator/creation/components/deployments.go
  pkg/virt-operator/install-strategy/create.go
  pkg/virt-operator/install-strategy/create_test.go
  pkg/virt-operator/install-strategy/strategy.go
  pkg/virt-operator/kubevirt_test.go
  pkg/virt-operator/util/config.go
  staging/src/kubevirt.io/client-go/api/v1/openapi_generated.go
  staging/src/kubevirt.io/client-go/api/v1/types.go
  staging/src/kubevirt.io/client-go/api/v1/types_swagger_generated.go
  staging/src/kubevirt.io/client-go/apis/snapshot/v1alpha1/openapi_generated.go
  tests/operator_test.go
Labels: approved, dco-signoff: yes, kind/api-change, lgtm, release-note, size/L

#4022 Allow podman for normal build steps
  hack/dockerized
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M

#4011 Move coverage from travis to prow - change travis, update builder
  Makefile
  WORKSPACE
  automation/travisci-test.sh
  hack/builder/Dockerfile
  hack/builder/vbom_ml.diff
  hack/builder/version.sh
  hack/dockerized
  hack/gen-swagger-doc/build.gradle
  hack/goveralls.sh
Labels: approved, dco-signoff: yes, lgtm, release-note, size/L

#3856 virt-launcher: log the domain XML upon launching
  pkg/hooks/manager.go
  pkg/virt-launcher/virtwrap/manager_test.go
  pkg/virt-launcher/virtwrap/util/libvirt_helper.go
  vendor/modules.txt
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M

#4047 gitignore: ignore files ending with ~
  .gitignore
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#3845 Remove domain label from VMI metrics
  pkg/monitoring/vms/prometheus/prometheus.go
Labels: approved, dco-signoff: yes, lgtm, release-note-action-required, size/M

#3950 UpdateStatus was not sufficient for certain snapshot controller updates
  pkg/virt-controller/watch/snapshot.go
  pkg/virt-controller/watch/snapshot_base.go
  pkg/virt-controller/watch/snapshot_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/L

#4054 Relabel clone device on virt handler
  cmd/virt-chroot/main.go
  cmd/virt-chroot/selinux.go
  cmd/virt-handler/virt-handler.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M

#3834 sriov-lane: dedicated container disk image
  BUILD.bazel
  WORKSPACE
  containerimages/BUILD.bazel
  containerimages/container-disk-images.md
  tests/containerdisk/containerdisk.go
  tests/utils.go
  tests/vmi_multus_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/L

#3958 Support VM scheme multi IPs in case of dual stack
  pkg/virt-handler/vm.go
  pkg/virt-handler/vm_test.go
  pkg/virt-launcher/virtwrap/network/BUILD.bazel
  pkg/virt-launcher/virtwrap/network/common.go
  pkg/virt-launcher/virtwrap/network/generated_mock_common.go
  pkg/virt-launcher/virtwrap/network/network.go
  pkg/virt-launcher/virtwrap/network/podinterface.go
  pkg/virt-launcher/virtwrap/network/podinterface_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/L

#3979 Makefile: Add timestamps to make targets
  Makefile
  automation/test.sh
  automation/travisci-test.sh
  hack/timestamps.sh
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/S

#4043 Fix the test default SMBIOS testcase
  tests/vmi_configuration_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/S

#4056 Check if new api rule violation was added
  api/api-rule-violations-known.list
  api/api-rule-violations.list
  hack/generate.sh
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XL

#3989 tests, vmi networking, make test 1780 dual stack compatible
  tests/vmi_networking_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M

#4072 Fix another flaky ertificate related unit test
  pkg/virt-operator/creation/components/secrets_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#3585 Refactor virtctl image-upload args
  pkg/virtctl/imageupload/imageupload.go
  pkg/virtctl/imageupload/imageupload_test.go
  tests/imageupload_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/L

#3797 sriov-lane: Fix AfterSuite namespaces deletion timeouts
  hack/cluster-deploy.sh
  tests/utils.go
  tests/vmi_multus_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/S

#4048 Migration improvements
  pkg/container-disk/container-disk.go
  pkg/container-disk/container-disk_test.go
  pkg/virt-handler/cache/cache.go
  pkg/virt-handler/cmd-client/client.go
  pkg/virt-handler/container-disk/mount.go
  pkg/virt-handler/vm.go
  pkg/virt-handler/vm_test.go
  tests/migration_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/L

#4057 tests,libvmi: Append passed options
  tests/libvmi/factory.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#4059 Add required dependencies for functest image build
  Makefile
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#4070 Output what the openapi error is when an api violation occurs
  hack/generate.sh
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#3226 Added tests to verify custom pciAddress slots and function
  tests/vmi_configuration_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/L

#4080 Fix openapi-gen
  hack/build-go.sh
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS
