Repository kubevirt/kubevirt, pull requests merged in 2021-09, with the labels that each got.

#6312 Switch kubectl port-forward -> NodePort as an attempt to stabilize 4621 from quarantine
  hack/cluster-deploy.sh
  manifests/testing/uploadproxy-nodeport.yaml.in
  tests/storage/imageupload.go
Labels: size/M, release-note-none, lgtm, approved, dco-signoff: yes

#6293 Remove linux-bridge creation before Multus tests suite starts
  tests/network/BUILD.bazel
  tests/network/vmi_multus.go
Labels: size/L, release-note-none, lgtm, approved, dco-signoff: yes

#6334 [release-0.44] Centralize fedora test tool images in one image
  BUILD.bazel
  WORKSPACE
  containerimages/BUILD.bazel
  examples/vm-template-fedora.yaml
  examples/vmi-fedora.yaml
  examples/vmi-gpu.yaml
  examples/vmi-macvtap.yaml
  examples/vmi-masquerade.yaml
  examples/vmi-multus-multiple-net.yaml
  examples/vmi-multus-ptp.yaml
  examples/vmi-slirp.yaml
  examples/vmi-sriov.yaml
  examples/vmi-with-sidecar-hook.yaml
  images/cdi-http-import-server/BUILD.bazel
  images/cdi-http-import-server/entrypoint.sh
  images/disks-images-provider/BUILD.bazel
  images/disks-images-provider/entrypoint.sh
  tests/config_test.go
  tests/console/login.go
  tests/console_test.go
  tests/containerdisk/containerdisk.go
  tests/credentials_test.go
  tests/infra_test.go
  tests/libvmi/factory.go
  tests/migration_test.go
  tests/network/primary_pod_network.go
  tests/network/vmi_multus.go
  tests/network/vmi_networking.go
  tests/storage/datavolume.go
  tests/storage/restore.go
  tests/storage/snapshot.go
  tests/storage/storage.go
  tests/template_test.go
  tests/utils.go
  tests/vm_test.go
  tests/vmi_cloudinit_test.go
  tests/vmi_configuration_test.go
  tests/vmi_ignition_test.go
  tools/vms-generator/utils/utils.go
Labels: size/L, release-note-none, lgtm, approved, dco-signoff: yes

#6330 whatchanged, Update markdown style of whatchanged script
  hack/whatchanged.sh
Labels: size/XS, release-note-none, lgtm, approved, dco-signoff: yes

#6186 [Sig-scale] Metric for monitoring Request Counts by Resource and Operation
  pkg/monitoring/client/prometheus/BUILD.bazel
  pkg/monitoring/client/prometheus/prometheus.go
  pkg/monitoring/client/prometheus/prometheus_suite_test.go
  pkg/monitoring/client/prometheus/prometheus_test.go
  staging/src/kubevirt.io/client-go/kubecli/kubecli.go
  tools/perfscale-audit/api/api.go
  tools/perfscale-audit/metric-client/metric-client.go
Labels: size/L, release-note, lgtm, approved, dco-signoff: yes

#6308 Fix hostpath hotplug not working when volume on separate device
  images/disks-images-provider/entrypoint.sh
  manifests/testing/disks-images-provider.yaml.in
  pkg/virt-handler/hotplug-disk/findmnt.go
  pkg/virt-handler/hotplug-disk/findmnt_test.go
  pkg/virt-handler/hotplug-disk/mount.go
  tests/config.go
  tests/default-config.json
  tests/storage/hotplug.go
  tests/utils.go
Labels: size/L, release-note, lgtm, approved, dco-signoff: yes

#6338 Fix Typo in PerfScale Load Generator Readme
  tools/perfscale-load-generator/README.md
Labels: size/XS, release-note-none, lgtm, approved, dco-signoff: yes

#6326 Update bazel version and bazel python rules
  .bazelversion
  WORKSPACE
  hack/builder/Dockerfile
  hack/dockerized
Labels: size/S, release-note-none, lgtm, approved, dco-signoff: yes

#6286 Add test_id for vm obey disk verification limits
  tests/container_disk_test.go
Labels: size/XS, release-note-none, lgtm, approved, dco-signoff: yes

#6302 tests: fix skipping of HostDisk tests
  tests/storage/storage.go
Labels: size/XS, release-note-none, lgtm, approved, dco-signoff: yes

#6335 Fix qemu-img segmentation fault error in tests
  tests/container_disk_test.go
Labels: size/XS, release-note-none, lgtm, approved, dco-signoff: yes

#6350 Collect reporter artifacts in a JustAfterEach
  tests/reporter/kubernetes.go
  tests/reporter/outputenricher.go
  tests/tests_suite_test.go
  tests/utils.go
Labels: size/M, release-note-none, lgtm, approved, dco-signoff: yes

#6327 OWNERS_ALIASES: make Ashley an emeritus approver
  OWNERS_ALIASES
Labels: size/XS, release-note-none, lgtm, approved, dco-signoff: yes

#6346 Fix flaky hostpath storage tests
  tests/storage/storage.go
Labels: size/S, release-note-none, lgtm, approved, dco-signoff: yes

#6298 release-0.41: disable extremely flaky test
  tests/migration_test.go
Labels: size/XS, release-note-none, lgtm, approved, dco-signoff: yes

#6184 [release-0.41] Replace dead "stress" binary with new, maintained, "stress-ng" binary
  WORKSPACE
  tests/migration_test.go
Labels: size/XS, release-note-none, lgtm, approved, dco-signoff: yes

#6320 [release-0.41] bug 1982143 -Change volume not supporting snapshot status error
  pkg/virt-controller/watch/snapshot/snapshot.go
  pkg/virt-controller/watch/snapshot/snapshot_test.go
Labels: size/S, release-note-none, lgtm, approved, dco-signoff: yes

#4643 Parallel datavolume tests
  tests/framework/matcher/BUILD.bazel
  tests/framework/matcher/getter.go
  tests/framework/matcher/owner.go
  tests/framework/matcher/owner_test.go
  tests/framework/matcher/phase.go
  tests/storage/datavolume.go
Labels: size/L, release-note-none, lgtm, approved, dco-signoff: yes

#6341 Release 0.44 vm online snapshot
  api/openapi-spec/swagger.json
  manifests/generated/operator-csv.yaml.in
  manifests/generated/rbac-operator.authorization.k8s.yaml.in
  manifests/testing/rook-ceph/common.yaml
  pkg/controller/virtinformers.go
  pkg/virt-controller/watch/BUILD.bazel
  pkg/virt-controller/watch/application.go
  pkg/virt-controller/watch/application_test.go
  pkg/virt-controller/watch/snapshot/BUILD.bazel
  pkg/virt-controller/watch/snapshot/snapshot.go
  pkg/virt-controller/watch/snapshot/snapshot_base.go
  pkg/virt-controller/watch/snapshot/snapshot_test.go
  pkg/virt-controller/watch/snapshot/source.go
  pkg/virt-controller/watch/vm.go
  pkg/virt-controller/watch/vm_test.go
  pkg/virt-operator/resource/generate/components/validations_generated.go
  pkg/virt-operator/resource/generate/rbac/controller.go
  pkg/virt-operator/resource/generate/rbac/operator.go
  staging/src/kubevirt.io/client-go/api/v1/openapi_generated.go
  staging/src/kubevirt.io/client-go/api/v1/types.go
  staging/src/kubevirt.io/client-go/api/v1/types_swagger_generated.go
  staging/src/kubevirt.io/client-go/apis/snapshot/v1alpha1/openapi_generated.go
  tests/storage/restore.go
  tests/storage/snapshot.go
  tests/utils.go
  tests/vm_test.go
Labels: size/XXL, release-note-none, kind/api-change, lgtm, approved, dco-signoff: yes

#6284 Docs: Reviewer guide to avoiding architecture flaws
  docs/reviewer-guide.md
Labels: size/S, release-note-none, lgtm, approved, dco-signoff: yes

#6352 generate, Show git diff in case generate diff exists
  hack/verify-generate.sh
Labels: size/XS, release-note-none, lgtm, approved, dco-signoff: yes

#6045 docs: Add docs for virtctl guestfs command
  docs/guestfs.md
Labels: size/L, release-note-none, lgtm, approved, dco-signoff: yes

#6354 automation, Align sig-operator in automation scripts
  automation/test.sh
Labels: size/XS, release-note-none, lgtm, approved, dco-signoff: yes

#6321 Test fix: Use a pod with virt-launcher image to run dmsetup commands.
  tests/BUILD.bazel
  tests/io_utils.go
Labels: size/M, release-note-none, lgtm, approved, dco-signoff: yes

#6377 Don't fail on relabeling if selinux is permissive
  cmd/virt-handler/virt-handler.go
  pkg/virt-handler/non-root.go
  pkg/virt-handler/selinux/labels.go
Labels: size/M, release-note, lgtm, approved, dco-signoff: yes

#6357 [Release-0.44] Move host-disk to handler
  cmd/virt-launcher/virt-launcher.go
  pkg/host-disk/BUILD.bazel
  pkg/host-disk/host-disk.go
  pkg/host-disk/host-disk_test.go
  pkg/virt-controller/services/template.go
  pkg/virt-controller/services/template_test.go
  pkg/virt-handler/vm.go
  pkg/virt-launcher/virtwrap/BUILD.bazel
  pkg/virt-launcher/virtwrap/manager.go
  pkg/virt-launcher/virtwrap/manager_test.go
  tests/storage/storage.go
Labels: size/L, release-note-none, lgtm, approved, dco-signoff: yes

#6372 Add more advises to the reviewer guide
  docs/reviewer-guide.md
Labels: size/XS, release-note-none, lgtm, approved, dco-signoff: yes

#6378 Ensure that we can migrate a VM multiple times after update
  tests/framework/matcher/getter.go
  tests/operator_test.go
Labels: size/M, release-note-none, lgtm, approved, dco-signoff: yes

#5971 [release-0.41] virt-launcher: fix UEFI-mode without secureboot
  pkg/virt-handler/vm.go
  pkg/virt-launcher/virtwrap/converter/converter.go
  pkg/virt-launcher/virtwrap/converter/converter_test.go
  tests/vmi_configuration_test.go
Labels: size/L, release-note-none, lgtm, approved, dco-signoff: yes

#6355 Remove test 3150 from QUARANTINE
  tests/operator_test.go
Labels: size/XS, release-note-none, lgtm, approved, dco-signoff: yes

#6251 Ensure optimal CPU pinning with dedicated CPUs
  pkg/handler-launcher-com/cmd/v1/cmd.pb.go
  pkg/handler-launcher-com/cmd/v1/cmd.proto
  pkg/util/hardware/hw_utils.go
  pkg/util/hardware/hw_utils_test.go
  pkg/virt-api/webhooks/validating-webhook/admitters/vmi-create-admitter.go
  pkg/virt-api/webhooks/validating-webhook/admitters/vmi-create-admitter_test.go
  pkg/virt-handler/node-labeller/api/BUILD.bazel
  pkg/virt-handler/node-labeller/api/capabilities.go
  pkg/virt-handler/node-labeller/capabilities_test.go
  pkg/virt-handler/node-labeller/testdata/capabilities.xml
  pkg/virt-handler/options.go
  pkg/virt-launcher/virtwrap/converter/BUILD.bazel
  pkg/virt-launcher/virtwrap/converter/converter.go
  pkg/virt-launcher/virtwrap/converter/converter_test.go
  pkg/virt-launcher/virtwrap/converter/network.go
  pkg/virt-launcher/virtwrap/converter/vcpu/BUILD.bazel
  pkg/virt-launcher/virtwrap/converter/vcpu/vcpu.go
  pkg/virt-launcher/virtwrap/converter/vcpu/vcpu_suite_test.go
  pkg/virt-launcher/virtwrap/converter/vcpu/vcpu_test.go
  pkg/virt-launcher/virtwrap/converter/vcpu_placement.go
  pkg/virt-launcher/virtwrap/manager.go
  pkg/virt-launcher/virtwrap/util/cpu_utils.go
  tests/vmi_configuration_test.go
Labels: release-note, size/XXL, lgtm, approved, dco-signoff: yes

#6283 [SIG-scale] Record the VMI deletion time
  pkg/monitoring/perfscale/perfscale_test.go
  pkg/monitoring/perfscale/register.go
  pkg/monitoring/perfscale/vmi-phase-transitions.go
Labels: size/L, release-note, lgtm, approved, dco-signoff: yes

#6342 Fix flaky SR-IOV tests: Schedule VM's on single node on connectivity tests
  tests/network/vmi_multus.go
Labels: size/M, release-note-none, lgtm, approved, dco-signoff: yes

#6390 Ensure that the perf tool binaries are always present
  hack/bazel-build.sh
Labels: size/XS, release-note-none, lgtm, approved, dco-signoff: yes

#6394 Add autolabeling of area/monitoring to PRs which change monitoring code
  pkg/monitoring/OWNERS
  pkg/virt-operator/resource/OWNERS
  pkg/virt-operator/resource/generate/components/BUILD.bazel
  pkg/virt-operator/resource/generate/components/crds.go
  pkg/virt-operator/resource/generate/components/prometheus.go
Labels: size/XXL, release-note-none, lgtm, approved, dco-signoff: yes

#6386 Add online vm snapshot and snapshot deadline documentation
  docs/snapshot-restore.md
Labels: size/S, release-note-none, lgtm, approved, dco-signoff: yes

#6339 CDI, Introduce KUBEVIRT_DEPLOY_CDI flag
  automation/test.sh
  hack/cluster-deploy.sh
Labels: size/M, release-note-none, lgtm, approved, dco-signoff: yes

#6374 Fix the default setting of CPU requests on vmipods
  pkg/virt-api/webhooks/mutating-webhook/mutators/vmi-mutator.go
  pkg/virt-api/webhooks/mutating-webhook/mutators/vmi-mutator_test.go
  pkg/virt-controller/services/template.go
  pkg/virt-controller/services/template_test.go
  tests/vmi_configuration_test.go
Labels: size/M, release-note, lgtm, approved, dco-signoff: yes

#6323 Switch live migration to use unix sockets between instead of TCP
  api/openapi-spec/swagger.json
  pkg/network/infraconfigurators/masquerade.go
  pkg/network/infraconfigurators/masquerade_test.go
  pkg/virt-controller/services/template.go
  pkg/virt-controller/services/template_test.go
  pkg/virt-controller/watch/vmi.go
  pkg/virt-controller/watch/vmi_test.go
  pkg/virt-handler/vm.go
  pkg/virt-handler/vm_test.go
  pkg/virt-launcher/virtwrap/BUILD.bazel
  pkg/virt-launcher/virtwrap/live-migration-source.go
  pkg/virt-launcher/virtwrap/live-migration-target.go
  pkg/virt-operator/resource/generate/components/validations_generated.go
  staging/src/kubevirt.io/client-go/api/v1/openapi_generated.go
  staging/src/kubevirt.io/client-go/api/v1/types.go
  staging/src/kubevirt.io/client-go/api/v1/types_swagger_generated.go
  staging/src/kubevirt.io/client-go/apis/snapshot/v1alpha1/openapi_generated.go
Labels: size/L, release-note, kind/api-change, lgtm, approved, dco-signoff: yes

#6211 [SIG-scale] KubeVirt PProf Profiler tools
  BUILD.bazel
  api/openapi-spec/swagger.json
  cmd/virt-handler/BUILD.bazel
  cmd/virt-handler/virt-handler.go
  hack/bazel-build.sh
  manifests/generated/operator-csv.yaml.in
  pkg/monitoring/profiler/BUILD.bazel
  pkg/monitoring/profiler/process-profiler.go
  pkg/monitoring/profiler/profile-manager.go
  pkg/monitoring/profiler/profile-manager_test.go
  pkg/monitoring/profiler/profiler_suite_test.go
  pkg/virt-api/BUILD.bazel
  pkg/virt-api/api.go
  pkg/virt-api/rest/BUILD.bazel
  pkg/virt-api/rest/authorizer.go
  pkg/virt-api/rest/authorizer_test.go
  pkg/virt-api/rest/profiler.go
  pkg/virt-api/rest/profiler_test.go
  pkg/virt-api/rest/subresource.go
  pkg/virt-config/config_test.go
  pkg/virt-config/feature-gates.go
  pkg/virt-controller/watch/BUILD.bazel
  pkg/virt-controller/watch/application.go
  pkg/virt-operator/BUILD.bazel
  pkg/virt-operator/application.go
  pkg/virt-operator/resource/generate/components/daemonsets.go
  pkg/virt-operator/resource/generate/components/deployments.go
  staging/src/kubevirt.io/client-go/api/v1/deepcopy_generated.go
  staging/src/kubevirt.io/client-go/api/v1/openapi_generated.go
  staging/src/kubevirt.io/client-go/api/v1/types.go
  staging/src/kubevirt.io/client-go/api/v1/types_swagger_generated.go
  staging/src/kubevirt.io/client-go/apis/snapshot/v1alpha1/openapi_generated.go
  staging/src/kubevirt.io/client-go/kubecli/BUILD.bazel
  staging/src/kubevirt.io/client-go/kubecli/generated_mock_kubevirt.go
  staging/src/kubevirt.io/client-go/kubecli/kubevirt.go
  staging/src/kubevirt.io/client-go/kubecli/profiler.go
  tests/infra_test.go
  tools/cluster-profiler/BUILD.bazel
  tools/cluster-profiler/cluster-profiler.go
Labels: release-note, size/XXL, kind/api-change, lgtm, approved, kind/build-change, dco-signoff: yes

#6198 [virt-api]: Add Prometheus records & alerts for bad REST calls
  Makefile
  hack/prom-rule-ci/prom-rules-tests.yaml
  pkg/virt-operator/resource/generate/components/prometheus.go
Labels: size/M, release-note, lgtm, approved, dco-signoff: yes, area/monitoring

#6392 [release-0.44] Ensure optimal CPU pinning with dedicated CPUs
  pkg/handler-launcher-com/cmd/v1/cmd.pb.go
  pkg/handler-launcher-com/cmd/v1/cmd.proto
  pkg/util/hardware/hw_utils.go
  pkg/util/hardware/hw_utils_test.go
  pkg/virt-api/webhooks/validating-webhook/admitters/vmi-create-admitter.go
  pkg/virt-api/webhooks/validating-webhook/admitters/vmi-create-admitter_test.go
  pkg/virt-handler/node-labeller/api/BUILD.bazel
  pkg/virt-handler/node-labeller/api/capabilities.go
  pkg/virt-handler/node-labeller/capabilities_test.go
  pkg/virt-handler/node-labeller/testdata/capabilities.xml
  pkg/virt-handler/options.go
  pkg/virt-launcher/virtwrap/converter/BUILD.bazel
  pkg/virt-launcher/virtwrap/converter/converter.go
  pkg/virt-launcher/virtwrap/converter/converter_test.go
  pkg/virt-launcher/virtwrap/converter/network.go
  pkg/virt-launcher/virtwrap/converter/vcpu/BUILD.bazel
  pkg/virt-launcher/virtwrap/converter/vcpu/vcpu.go
  pkg/virt-launcher/virtwrap/converter/vcpu/vcpu_suite_test.go
  pkg/virt-launcher/virtwrap/converter/vcpu/vcpu_test.go
  pkg/virt-launcher/virtwrap/converter/vcpu_placement.go
  pkg/virt-launcher/virtwrap/manager.go
  pkg/virt-launcher/virtwrap/util/cpu_utils.go
  tests/vmi_configuration_test.go
Labels: release-note, size/XXL, lgtm, approved, dco-signoff: yes

#6401 [release-0.41] Fix RBAC subresource permissions for admin/edit/view roles
  manifests/generated/operator-csv.yaml.in
  manifests/generated/rbac-operator.authorization.k8s.yaml.in
  pkg/virt-operator/resource/generate/rbac/cluster.go
  pkg/virt-operator/resource/generate/rbac/controller.go
  pkg/virt-operator/resource/generate/rbac/operator.go
  tests/BUILD.bazel
  tests/access_test.go
Labels: size/XL, release-note, lgtm, approved, dco-signoff: yes

#6414 Add cluster-profiler to bazel build command
  hack/bazel-build.sh
Labels: size/XS, release-note-none, lgtm, approved, dco-signoff: yes

#6420 Mirror the arm toolchain to our artifacts cache
  third_party/toolchains/toolchains.bzl
Labels: size/XS, release-note-none, lgtm, approved, dco-signoff: yes

#6364 Quarantine flaky sig-compute test
  tests/infra_test.go
Labels: size/XS, release-note-none, lgtm, approved, dco-signoff: yes

#6304 [test] Increase the timeout for node to become scheduleable
  tests/vmi_lifecycle_test.go
Labels: size/XS, release-note-none, lgtm, approved, dco-signoff: yes

#6367 Create volume using defaults provided by CDI
  pkg/virtctl/imageupload/imageupload.go
  pkg/virtctl/imageupload/imageupload_test.go
Labels: size/L, release-note, lgtm, approved, dco-signoff: yes

#6398 migrations: decomplexify XML parsing
  pkg/virt-launcher/virtwrap/live-migration-source.go
Labels: size/M, release-note-none, lgtm, approved, dco-signoff: yes

#6403 Upgrade go-kit to v0.9.0
  go.mod
  go.sum
  pkg/virt-launcher/virtwrap/util/libvirt_helper_test.go
  staging/src/kubevirt.io/client-go/go.mod
  staging/src/kubevirt.io/client-go/go.sum
  staging/src/kubevirt.io/client-go/log/log.go
  vendor/github.com/go-kit/kit/endpoint/BUILD.bazel
  vendor/github.com/go-kit/kit/endpoint/endpoint.go
  vendor/github.com/go-kit/kit/log/BUILD.bazel
  vendor/github.com/go-kit/kit/log/README.md
  vendor/github.com/go-kit/kit/log/doc.go
  vendor/github.com/go-kit/kit/log/json_logger.go
  vendor/github.com/go-kit/kit/log/log.go
  vendor/github.com/go-kit/kit/log/stdlib.go
  vendor/github.com/go-kit/kit/log/sync.go
  vendor/github.com/go-kit/kit/log/value.go
  vendor/modules.txt
Labels: size/L, release-note, lgtm, approved, ok-to-test, dco-signoff: yes

#6416 Continue installing CDI by default
  hack/cluster-deploy.sh
Labels: size/XS, release-note-none, lgtm, approved, dco-signoff: yes

#6400 [release-0.36] Fix RBAC subresource permissions for admin/edit/view roles
  manifests/generated/operator-csv.yaml.in
  manifests/generated/rbac-operator.authorization.k8s.yaml.in
  pkg/virt-operator/creation/rbac/cluster.go
  pkg/virt-operator/creation/rbac/controller.go
  pkg/virt-operator/creation/rbac/operator.go
  tests/access_test.go
Labels: size/XL, release-note, lgtm, approved, dco-signoff: yes

#6406 Double timeouts of storage tests that flake when parallel
  tests/storage/datavolume.go
  tests/storage/storage.go
Labels: size/XS, release-note-none, lgtm, approved, dco-signoff: yes

#6385 Refactor ADOPTERS list
  ADOPTERS.md
Labels: size/S, release-note-none, lgtm, approved, dco-signoff: yes

#6421 Tests: Ensure all virt-handlers are ready before migration
  tests/migration_test.go
Labels: size/XS, release-note-none, lgtm, approved, dco-signoff: yes

#6429 go-test: ignore cmd/container-disk-v2alpha which is not go
  hack/build-go.sh
Labels: size/XS, release-note-none, lgtm, approved, dco-signoff: yes

#6103 [virt-operator] add validation for the infra and workloads placement config in Kubevirt CR
  pkg/virt-operator/webhooks/BUILD.bazel
  pkg/virt-operator/webhooks/kubevirt-update-admitter.go
  tests/operator_test.go
Labels: size/L, release-note-none, lgtm, approved, dco-signoff: yes

#6431 automation: avoid waiting forever that Completed pods become Running
  automation/test.sh
Labels: size/XS, release-note-none, lgtm, approved, dco-signoff: yes

#6435 automation: ignore completed pods when checking for readiness
  automation/test.sh
Labels: size/XS, release-note-none, lgtm, approved, dco-signoff: yes

#6419 Catch the deletion key before type assertion causes a panic
  pkg/virt-controller/watch/vmi.go
Labels: size/S, release-note, lgtm, approved, dco-signoff: yes

#6424 migration: persist XML changes to the target
  pkg/virt-launcher/virtwrap/live-migration-source.go
  tests/migration.go
  tests/migration_test.go
Labels: size/M, release-note-none, lgtm, approved, dco-signoff: yes

#6391 Cleanup obsolete permissions from virt-operator's ClusterRole
  manifests/generated/operator-csv.yaml.in
  manifests/generated/rbac-operator.authorization.k8s.yaml.in
  pkg/virt-operator/resource/generate/rbac/operator.go
Labels: size/M, release-note, lgtm, approved, dco-signoff: yes

#6441 Enable CNAO and CDI for check flakes by default
  automation/repeated_test.sh
Labels: size/XS, release-note-none, lgtm, approved, dco-signoff: yes

#6408 Unquarantine storage tests mistakingly quarantined.
  tests/storage/restore.go
Labels: size/XS, release-note-none, lgtm, approved, dco-signoff: yes

#6285 janitorial: clean cluster-clean.sh
  hack/cluster-clean.sh
Labels: size/M, release-note-none, lgtm, approved, kind/build-change, dco-signoff: yes

#6409 virt-api Webhook Informer Refactor
  pkg/controller/controller.go
  pkg/controller/virtinformers.go
  pkg/util/types/dv.go
  pkg/virt-api/api.go
  pkg/virt-api/webhooks/BUILD.bazel
  pkg/virt-api/webhooks/mutating-webhook/BUILD.bazel
  pkg/virt-api/webhooks/mutating-webhook/mutating-webhook.go
  pkg/virt-api/webhooks/mutating-webhook/mutators/vmi-mutator.go
  pkg/virt-api/webhooks/mutating-webhook/mutators/vmi-mutator_test.go
  pkg/virt-api/webhooks/utils.go
  pkg/virt-api/webhooks/validating-webhook/BUILD.bazel
  pkg/virt-api/webhooks/validating-webhook/admitters/BUILD.bazel
  pkg/virt-api/webhooks/validating-webhook/admitters/admitters_test.go
  pkg/virt-api/webhooks/validating-webhook/admitters/migration-create-admitter.go
  pkg/virt-api/webhooks/validating-webhook/admitters/migration-create-admitter_test.go
  pkg/virt-api/webhooks/validating-webhook/admitters/migration-update-admitter_test.go
  pkg/virt-api/webhooks/validating-webhook/admitters/vmrestore-admitter.go
  pkg/virt-api/webhooks/validating-webhook/admitters/vmrestore-admitter_test.go
  pkg/virt-api/webhooks/validating-webhook/admitters/vms-admitter.go
  pkg/virt-api/webhooks/validating-webhook/admitters/vms-admitter_test.go
  pkg/virt-api/webhooks/validating-webhook/validating-webhook.go
  pkg/virt-config/config-map.go
Labels: size/XL, release-note-none, lgtm, approved, dco-signoff: yes

#6112 Fix non-root lanes
  automation/test.sh
  tests/migration.go
  tests/nonroot_test.go
  tests/storage/storage.go
  tools/manifest-templator/manifest-templator.go
Labels: size/M, release-note-none, lgtm, approved, kind/build-change, dco-signoff: yes

#6415 Document CDI deploy for cluster-sync
  docs/getting-started.md
Labels: size/XS, release-note-none, lgtm, approved, dco-signoff: yes

#6333 [release-0.41] virt-launcher: fix exit pod race condition
  cmd/virt-launcher/virt-launcher.go
Labels: size/S, release-note, lgtm, approved, dco-signoff: yes

#6446 Fix virtctl imageupload on default storageclass
  pkg/virtctl/imageupload/imageupload.go
Labels: size/M, release-note, lgtm, approved, dco-signoff: yes

#6463 [release-0.41] migration: persist XML changes to the target
  pkg/virt-launcher/virtwrap/live-migration-source.go
  tests/migration.go
  tests/migration_test.go
Labels: size/M, release-note-none, lgtm, approved, dco-signoff: yes

#6452 Determine CRI binary to collect debug logs
  automation/test.sh
Labels: size/S, release-note-none, lgtm, approved, dco-signoff: yes

#6458 Fix sriov tagging
  pkg/virt-launcher/virtwrap/manager.go
  tests/network/BUILD.bazel
  tests/network/vmi_multus.go
  tests/utils.go
  tests/vmi_cloudinit_test.go
Labels: size/L, release-note, lgtm, approved, dco-signoff: yes

#6465 Properly process Gateway DHCP Option as IPv4 in DHCP Server
  pkg/network/dhcp/server/server.go
  pkg/network/dhcp/server/server_test.go
Labels: release-note, size/XS, lgtm, approved, ok-to-test, dco-signoff: yes

#6472 Skip test_id:3145 for nonroot lanes
  automation/test.sh
Labels: size/XS, release-note-none, lgtm, approved, dco-signoff: yes

#6464 Resolve hotplug race between kubelet and virt-handler
  pkg/hotplug-disk/hotplug-disk.go
  pkg/hotplug-disk/hotplug-disk_test.go
  pkg/virt-handler/hotplug-disk/mount.go
  pkg/virt-handler/hotplug-disk/mount_test.go
  pkg/virt-launcher/virtwrap/converter/converter.go
  pkg/virt-launcher/virtwrap/converter/converter_test.go
  pkg/virt-launcher/virtwrap/manager_test.go
Labels: size/M, release-note, lgtm, approved, dco-signoff: yes

#6474 tests: Make sure libguestfs appliance is fully unpacked
  tests/storage/guestfs.go
Labels: size/S, release-note-none, lgtm, approved, dco-signoff: yes

#6439 Add more phase transition buckets
  pkg/monitoring/perfscale/vmi-phase-transitions.go
Labels: size/XS, release-note-none, lgtm, approved, dco-signoff: yes, area/monitoring

#6471 Ensure that the BeforeTest function is actually called
  tests/template_test.go
Labels: size/XS, release-note-none, lgtm, approved, dco-signoff: yes

#6311 Specify format of the backing image
  pkg/container-disk/container-disk.go
  pkg/ephemeral-disk/ephemeral-disk.go
  pkg/ephemeral-disk/ephemeral-disk_test.go
  pkg/ephemeral-disk/fake/ephemeral-disk.go
  pkg/handler-launcher-com/cmd/v1/cmd.pb.go
  pkg/handler-launcher-com/cmd/v1/cmd.proto
  pkg/virt-handler/BUILD.bazel
  pkg/virt-handler/cmd-client/client.go
  pkg/virt-handler/cmd-client/generated_mock_client.go
  pkg/virt-handler/container-disk/generated_mock_mount.go
  pkg/virt-handler/container-disk/mount.go
  pkg/virt-handler/options.go
  pkg/virt-handler/vm.go
  pkg/virt-handler/vm_test.go
  pkg/virt-launcher/virtwrap/cmd-server/server.go
  pkg/virt-launcher/virtwrap/converter/converter.go
  pkg/virt-launcher/virtwrap/generated_mock_manager.go
  pkg/virt-launcher/virtwrap/live-migration-target.go
  pkg/virt-launcher/virtwrap/manager.go
  pkg/virt-launcher/virtwrap/manager_test.go
Labels: size/L, release-note-none, lgtm, approved, dco-signoff: yes

#6336 Use smaller writes for fstrim test, improve messaging on failure
  tests/storage/datavolume.go
Labels: size/S, release-note-none, lgtm, approved, dco-signoff: yes

#6470 Remove test VMI IO tests from Quarantine
  tests/storage/storage.go
Labels: size/XS, release-note-none, lgtm, approved, dco-signoff: yes

#6297 Mutate PDBs during a live-migration
  pkg/controller/controller.go
  pkg/util/migrations/migrations.go
  pkg/util/pdbs/BUILD.bazel
  pkg/util/pdbs/pdbs.go
  pkg/virt-controller/watch/BUILD.bazel
  pkg/virt-controller/watch/application.go
  pkg/virt-controller/watch/application_test.go
  pkg/virt-controller/watch/drain/disruptionbudget/BUILD.bazel
  pkg/virt-controller/watch/drain/disruptionbudget/disruptionbudget.go
  pkg/virt-controller/watch/drain/disruptionbudget/disruptionbudget_test.go
  pkg/virt-controller/watch/migration.go
  pkg/virt-controller/watch/migration_test.go
  tests/migration_test.go
Labels: size/XL, release-note, kind/api-change, lgtm, approved, dco-signoff: yes

#6329 add initial tests cases for arm64
  tests/access_test.go
  tests/container_disk_test.go
  tests/network/vmi_lifecycle.go
  tests/storage/storage.go
  tests/utils.go
  tests/vm_watch_test.go
  tests/vmi_lifecycle_test.go
Labels: size/M, release-note-none, lgtm, approved, dco-signoff: yes

#6489 Quarantine flaky sig-compute tests
  tests/infra_test.go
  tests/migration_test.go
Labels: size/XS, release-note-none, lgtm, approved, dco-signoff: yes

#6234 [tests] Remove the cdi-http-image-server test image from the project
  BUILD.bazel
  WORKSPACE
  examples/vm-alpine-datavolume.yaml
  hack/cluster-deploy.sh
  hack/config-default.sh
  hack/rpm-deps.sh
  images/cdi-http-import-server/BUILD.bazel
  images/cdi-http-import-server/entrypoint.sh
  images/cdi-http-import-server/expose-as-iscsi.sh
  images/cdi-http-import-server/nginx.conf
  manifests/testing/disks-images-provider.yaml.in
  pkg/virt-controller/watch/snapshot/snapshot_test.go
  rpm/BUILD.bazel
  tests/console_test.go
  tests/containerdisk/containerdisk.go
  tests/migration_test.go
  tests/operator_test.go
  tests/storage/datavolume.go
  tests/storage/imageupload.go
  tests/storage/restore.go
  tests/storage/snapshot.go
  tests/storage/storage.go
  tests/utils.go
  tests/vm_test.go
  tools/vms-generator/utils/utils.go
Labels: size/XXL, release-note-none, lgtm, approved, dco-signoff: yes

#6467 dns, tests: only accept preferred names syntax
  pkg/network/dhcp/server/BUILD.bazel
  pkg/network/dhcp/server/server_test.go
Labels: size/M, release-note-none, lgtm, approved, dco-signoff: yes
