Repository kubevirt/kubevirt, pull requests merged in 2021-07, with the labels that each got.

#5852 Cherry pick 5269 to release 0.37
  cmd/virt-handler/virt-handler.go
  pkg/monitoring/vms/prometheus/BUILD.bazel
  pkg/monitoring/vms/prometheus/prometheus.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/S

#5616 add CPUArch in kubevirt config
  cmd/virt-handler/virt-handler.go
  pkg/testutils/mock_config.go
  pkg/virt-config/config-map.go
  pkg/virt-config/config_test.go
  pkg/virt-config/virt-config.go
  pkg/virt-operator/resource/generate/components/daemonsets.go
Labels: approved, dco-signoff: yes, kind/api-change, lgtm, release-note-none, size/L

#5959 Use precompiled protoc
  WORKSPACE
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M

#5961 Fix test binary build targets for cross-compiling
  hack/build-func-tests.sh
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/S

#5962 Remove note about one pod per disk hotplug
  docs/hotplug.md
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#5921 [release-0.34] fix pdb controller segfault
  pkg/virt-controller/watch/drain/disruptionbudget/disruptionbudget.go
  pkg/virt-controller/watch/drain/disruptionbudget/disruptionbudget_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/S

#5954 Fix membership guidelines link
  CONTRIBUTING.md
Labels: approved, dco-signoff: yes, lgtm, needs-ok-to-test, release-note-none, size/XS

#5876 Configurable runtimeClassName for virt-launcher
  api/openapi-spec/swagger.json
  manifests/generated/kv-resource.yaml
  pkg/virt-config/virt-config.go
  pkg/virt-controller/services/template.go
  pkg/virt-controller/services/template_test.go
  pkg/virt-operator/resource/generate/components/validations_generated.go
  staging/src/kubevirt.io/client-go/api/v1/openapi_generated.go
  staging/src/kubevirt.io/client-go/api/v1/types.go
  staging/src/kubevirt.io/client-go/apis/snapshot/v1alpha1/openapi_generated.go
  tests/BUILD.bazel
  tests/utils.go
  tests/vmi_configuration_test.go
Labels: approved, dco-signoff: yes, kind/api-change, lgtm, release-note, size/L

#5915 manifests: use rbac.authorization.k8s.io/v1 instead of v1beta1
  manifests/testing/rbac-for-testing.yaml.in
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#5919 [release-0.36] fix pdb controller segfault
  pkg/virt-controller/watch/drain/disruptionbudget/disruptionbudget.go
  pkg/virt-controller/watch/drain/disruptionbudget/disruptionbudget_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/S

#5813 Reconcile RoleBinding and ClusterRoleBinding resources
  pkg/virt-operator/resource/apply/BUILD.bazel
  pkg/virt-operator/resource/apply/rbac.go
  pkg/virt-operator/resource/apply/rbac_test.go
  pkg/virt-operator/resource/apply/rbacbackup.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XL

#4954 docs: Generate manifests after push images
  docs/getting-started.md
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#5872 Detect driver cache mode for cloud-init disk
  pkg/cloud-init/cloud-init.go
  pkg/cloud-init/cloud-init_test.go
  pkg/virt-launcher/virtwrap/converter/BUILD.bazel
  pkg/virt-launcher/virtwrap/converter/converter.go
  pkg/virt-launcher/virtwrap/converter/converter_test.go
  pkg/virt-launcher/virtwrap/converter/generated_mock_converter.go
  pkg/virt-launcher/virtwrap/manager.go
  pkg/virt-launcher/virtwrap/manager_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/L

#5965 make shallow copy of config parameter
  staging/src/kubevirt.io/client-go/kubecli/kubecli.go
Labels: approved, dco-signoff: yes, lgtm, ok-to-test, release-note-none, size/M

#5931 Label remaining tests as rook-ceph to include them in sig-storage
  tests/console_test.go
  tests/migration_test.go
  tests/vm_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/S

#5772 Fix flaky cpu test
  tests/vmi_configuration_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#5936 Move podnic code to podnic go
  pkg/network/dhcp/configurator.go
  pkg/network/infraconfigurators/BUILD.bazel
  pkg/network/infraconfigurators/common.go
  pkg/network/infraconfigurators/generated_mock_common.go
  pkg/virt-launcher/virtwrap/network/BUILD.bazel
  pkg/virt-launcher/virtwrap/network/network.go
  pkg/virt-launcher/virtwrap/network/network_suite_test.go
  pkg/virt-launcher/virtwrap/network/network_test.go
  pkg/virt-launcher/virtwrap/network/podinterface.go
  pkg/virt-launcher/virtwrap/network/podinterface_test.go
  pkg/virt-launcher/virtwrap/network/podnic.go
  pkg/virt-launcher/virtwrap/network/podnic_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XXL

#5963 Wire the client side rate limiter metric
  pkg/monitoring/client/prometheus/prometheus.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/S

#5831 Increase timeouts for operator tests
  tests/operator_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#5953 Update stop vm responses
  pkg/virt-api/rest/subresource.go
  pkg/virt-api/rest/subresource_test.go
  tests/vm_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/M

#5986 Resolve containerdisk after initialization in template tests
  tests/template_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#5990 Generate cloud-init paths without creating directories
  pkg/cloud-init/cloud-init.go
  tests/vmi_cloudinit_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/S

#5987 If the hostDisk feature gate is not enabled, skip tests
  tests/vmi_configuration_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/S

#5824 [automation] fix root owned _out directory issue
  hack/dockerized
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#5944 Refactor UEFI-mode without secureboot
  pkg/virt-handler/vm.go
  pkg/virt-launcher/virtwrap/BUILD.bazel
  pkg/virt-launcher/virtwrap/converter/converter.go
  pkg/virt-launcher/virtwrap/converter/converter_test.go
  pkg/virt-launcher/virtwrap/efi/BUILD.bazel
  pkg/virt-launcher/virtwrap/efi/efi.go
  pkg/virt-launcher/virtwrap/efi/efi_suite_test.go
  pkg/virt-launcher/virtwrap/efi/efi_test.go
  pkg/virt-launcher/virtwrap/manager.go
  staging/src/kubevirt.io/client-go/api/v1/types.go
Labels: approved, dco-signoff: yes, kind/api-change, lgtm, release-note-none, size/L

#5978 hack: add [sig-performance] label as possible asigned test
  hack/check-unassigned-tests.sh
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#5402 Libguestfs integration in Kubevirt
  BUILD.bazel
  WORKSPACE
  api/openapi-spec/swagger.json
  cmd/libguestfs/BUILD.bazel
  cmd/libguestfs/entrypoint.sh
  hack/bazel-build-images.sh
  hack/bazel-push-images.sh
  hack/build-manifests.sh
  hack/cluster-patch.sh
  hack/generate.sh
  hack/parse-shasums.sh
  hack/rpm-deps.sh
  manifests/generated/operator-csv.yaml.in
  pkg/virt-api/BUILD.bazel
  pkg/virt-api/api.go
  pkg/virt-api/rest/authorizer.go
  pkg/virt-config/config-map.go
  pkg/virt-operator/resource/generate/components/deployments.go
  pkg/virt-operator/resource/generate/csv/csv.go
  pkg/virt-operator/util/config.go
  pkg/virtctl/BUILD.bazel
  pkg/virtctl/console/BUILD.bazel
  pkg/virtctl/console/console.go
  pkg/virtctl/guestfs/BUILD.bazel
  pkg/virtctl/guestfs/guestfs.go
  pkg/virtctl/guestfs/guestfs_suite_test.go
  pkg/virtctl/guestfs/guestfs_test.go
  pkg/virtctl/root.go
  pkg/virtctl/utils/BUILD.bazel
  pkg/virtctl/utils/utils.go
  rpm/BUILD.bazel
  staging/src/kubevirt.io/client-go/kubecli/BUILD.bazel
  staging/src/kubevirt.io/client-go/kubecli/generated_mock_kubevirt.go
  staging/src/kubevirt.io/client-go/kubecli/guestfs.go
  staging/src/kubevirt.io/client-go/kubecli/kubevirt.go
  tests/storage/BUILD.bazel
  tests/storage/guestfs.go
  tools/csv-generator/csv-generator.go
  tools/manifest-templator/manifest-templator.go
  vendor/k8s.io/api/admission/v1beta1/BUILD.bazel
  vendor/k8s.io/api/admission/v1beta1/doc.go
  vendor/k8s.io/api/admission/v1beta1/generated.pb.go
  vendor/k8s.io/api/admission/v1beta1/generated.proto
  vendor/k8s.io/api/admission/v1beta1/register.go
  vendor/k8s.io/api/admission/v1beta1/types.go
  vendor/k8s.io/api/admission/v1beta1/types_swagger_doc_generated.go
  vendor/k8s.io/api/admission/v1beta1/zz_generated.deepcopy.go
  vendor/k8s.io/api/admission/v1beta1/zz_generated.prerelease-lifecycle.go
  vendor/k8s.io/apimachinery/pkg/api/validation/BUILD.bazel
  vendor/k8s.io/apimachinery/pkg/api/validation/doc.go
  vendor/k8s.io/apimachinery/pkg/api/validation/generic.go
  vendor/k8s.io/apimachinery/pkg/api/validation/objectmeta.go
Labels: approved, dco-signoff: yes, kind/api-change, lgtm, release-note, size/XXL

#5306 Require net_bind_service capability
  pkg/virt-controller/services/template.go
  pkg/virt-controller/services/template_test.go
  tests/security_features_test.go
  tests/utils.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M

#5979 Update to OWNERS_ALIASES
  OWNERS_ALIASES
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#6013 [Sig-scale] Expose workqueue metrics to Prometheus
  pkg/monitoring/workqueue/prometheus/prometheus.go
  pkg/virt-controller/watch/drain/disruptionbudget/disruptionbudget.go
  pkg/virt-controller/watch/drain/evacuation/evacuation.go
  pkg/virt-controller/watch/migration.go
  pkg/virt-controller/watch/node.go
  pkg/virt-controller/watch/replicaset.go
  pkg/virt-controller/watch/snapshot/restore_base.go
  pkg/virt-controller/watch/snapshot/snapshot_base.go
  pkg/virt-controller/watch/vm.go
  pkg/virt-controller/watch/vmi.go
  pkg/virt-controller/watch/workload-updater/workload-updater.go
  pkg/virt-handler/node-labeller/node_labeller.go
  pkg/virt-handler/vm.go
  pkg/virt-operator/kubevirt.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/L

#5989 migration: only remove migration-specific metadata from libvirt XML
  pkg/virt-launcher/virtwrap/live-migration-source.go
  pkg/virt-launcher/virtwrap/manager_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M

#6000 Fix rounding errors for NUMA memory allocation
  pkg/virt-launcher/virtwrap/converter/numa_placement.go
  pkg/virt-launcher/virtwrap/converter/numa_placement_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M

#6007 Fix the bandwidth limitation option for migrations
  pkg/virt-config/config_test.go
  pkg/virt-config/virt-config.go
  pkg/virt-handler/vm_test.go
  pkg/virt-launcher/virtwrap/converter/converter.go
  pkg/virt-launcher/virtwrap/converter/converter_test.go
  pkg/virt-launcher/virtwrap/live-migration-source.go
  tests/migration_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/L

#6003 [release-0.41] If the hostDisk feature gate is not enabled, skip tests
  tests/vmi_configuration_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/S

#6011 Fix flaky secrets certificate test
  pkg/virt-operator/resource/generate/components/secrets_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#6004 [release-0.35] fix pdb controller segfault
  pkg/virt-controller/watch/drain/disruptionbudget/disruptionbudget.go
  pkg/virt-controller/watch/drain/disruptionbudget/disruptionbudget_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/S

#5925 network, dhcp: Check for empty DHCP Routers and static routes options
  pkg/virt-launcher/virtwrap/network/dhcp/dhcp.go
  pkg/virt-launcher/virtwrap/network/dhcp/dhcp_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/M

#5891 Don't delete temp pods that aren't associated with VMI
  pkg/virt-controller/watch/vmi.go
  pkg/virt-controller/watch/vmi_test.go
  tests/storage/datavolume.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/L

#5982 Reduce VMI Update Collisions
  pkg/virt-controller/watch/vmi.go
  pkg/virt-controller/watch/vmi_test.go
  pkg/virt-handler/vm.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/M

#6008 Remove outdated comments
  pkg/virt-controller/services/template.go
  tests/network/vmi_multus.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#6022 Add kubevirt logo
  README.md
Labels: approved, dco-signoff: yes, lgtm, ok-to-test, release-note-none, size/XS

#5998 Quarantine sig-storage and sig-compute tests
  tests/storage/events.go
  tests/storage/imageupload.go
  tests/storage/restore.go
  tests/vm_watch_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#5985 Take "Should be able to add and remove and re-add multiple volumes out of quarantine"
  tests/storage/hotplug.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M

#6030 Attempt to fix flaky VmWatch test
  tests/vm_watch_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#6027 [tests] remove unused functions from utils.go
  tests/BUILD.bazel
  tests/utils.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M

#5980 Remove fake interface cache factory
  pkg/network/cache/BUILD.bazel
  pkg/network/cache/fake/BUILD.bazel
  pkg/network/cache/fake/infocache.go
  pkg/network/cache/infocache.go
  pkg/network/cache/infocache_test.go
  pkg/network/dhcp/BUILD.bazel
  pkg/network/dhcp/bridge_test.go
  pkg/network/dhcp/configurator_test.go
  pkg/os/fs/BUILD.bazel
  pkg/os/fs/defaultfs.go
  pkg/os/fs/filesystem.go
  pkg/virt-handler/BUILD.bazel
  pkg/virt-handler/vm_test.go
  pkg/virt-launcher/virtwrap/network/BUILD.bazel
  pkg/virt-launcher/virtwrap/network/network_test.go
  pkg/virt-launcher/virtwrap/network/podinterface_test.go
  pkg/virt-launcher/virtwrap/network/podnic_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XL

#6033 remove bad make verify-deps command
  Makefile
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#5864 Ioerror resume
  tests/io_utils.go
  tests/storage/events.go
  tests/storage/storage.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/L

#6038 Add symlink for the ca-certificates
  rpm/BUILD.bazel
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#5977 Use sync.Map for podCacheInterface
  pkg/virt-handler/cache/BUILD.bazel
  pkg/virt-handler/cache/maps.go
  pkg/virt-handler/vm.go
  pkg/virt-handler/vm_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/L

#6006 Set DV priority class if VM priority class is set.
  pkg/virt-controller/watch/vm.go
  pkg/virt-controller/watch/vm_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/M

#6021 Add click example instruction
  README.md
Labels: approved, dco-signoff: yes, lgtm, needs-ok-to-test, release-note-none, size/XS

#5791 Expose VM/VMI readiness via a dedicated CLI column
  pkg/controller/conditions.go
  pkg/controller/conditions_test.go
  pkg/virt-controller/watch/BUILD.bazel
  pkg/virt-controller/watch/vm.go
  pkg/virt-controller/watch/vm_test.go
  pkg/virt-controller/watch/vmi.go
  pkg/virt-controller/watch/vmi_test.go
  pkg/virt-operator/resource/generate/components/crds.go
  staging/src/kubevirt.io/client-go/api/v1/types.go
  tests/kubectl_test.go
  tests/vm_test.go
  tests/vm_watch_test.go
  tests/vmi_configuration_test.go
  tests/vmi_lifecycle_test.go
Labels: approved, dco-signoff: yes, kind/api-change, lgtm, release-note, size/XL

#5835 [SIG-scale] Add density performance tests to evaluate the Kubevirt control plane
  Makefile
  hack/perftests.sh
  tests/BUILD.bazel
  tests/performance/BUILD.bazel
  tests/performance/density.go
  tests/performance/framework.go
  tests/tests_suite_test.go
Labels: approved, dco-signoff: yes, kind/build-change, lgtm, release-note-none, size/L

#6005 virt-config: make containerDisk validation memory usage limit configurable
  api/openapi-spec/swagger.json
  cmd/virt-chroot/main.go
  manifests/generated/kv-resource.yaml
  pkg/virt-config/BUILD.bazel
  pkg/virt-config/config-map.go
  pkg/virt-config/config_test.go
  pkg/virt-config/virt-config.go
  pkg/virt-handler/container-disk/BUILD.bazel
  pkg/virt-handler/container-disk/mount.go
  pkg/virt-handler/isolation/validation.go
  pkg/virt-handler/vm.go
  pkg/virt-operator/resource/generate/components/validations_generated.go
  staging/src/kubevirt.io/client-go/api/v1/deepcopy_generated.go
  staging/src/kubevirt.io/client-go/api/v1/openapi_generated.go
  staging/src/kubevirt.io/client-go/api/v1/types.go
  staging/src/kubevirt.io/client-go/api/v1/types_swagger_generated.go
  staging/src/kubevirt.io/client-go/apis/snapshot/v1alpha1/openapi_generated.go
  tests/container_disk_test.go
Labels: approved, dco-signoff: yes, kind/api-change, lgtm, release-note, size/L

#5946 Add guest-agent based readiness ping probe
  api/openapi-spec/swagger.json
  cmd/virt-probe/virt-probe.go
  docs/probes.md
  pkg/handler-launcher-com/cmd/v1/cmd.pb.go
  pkg/handler-launcher-com/cmd/v1/cmd.proto
  pkg/handler-launcher-com/cmd/v1/generated_mock_cmd.go
  pkg/virt-api/webhooks/validating-webhook/admitters/vmi-create-admitter.go
  pkg/virt-api/webhooks/validating-webhook/admitters/vmi-create-admitter_test.go
  pkg/virt-controller/services/template.go
  pkg/virt-handler/cmd-client/client.go
  pkg/virt-handler/cmd-client/client_test.go
  pkg/virt-handler/cmd-client/generated_mock_client.go
  pkg/virt-launcher/virtwrap/cmd-server/server.go
  pkg/virt-launcher/virtwrap/cmd-server/server_test.go
  pkg/virt-launcher/virtwrap/generated_mock_manager.go
  pkg/virt-launcher/virtwrap/manager.go
  pkg/virt-operator/resource/generate/components/validations_generated.go
  staging/src/kubevirt.io/client-go/api/v1/deepcopy_generated.go
  staging/src/kubevirt.io/client-go/api/v1/openapi_generated.go
  staging/src/kubevirt.io/client-go/api/v1/types.go
  staging/src/kubevirt.io/client-go/api/v1/types_swagger_generated.go
  staging/src/kubevirt.io/client-go/apis/snapshot/v1alpha1/openapi_generated.go
  tests/network/probes.go
Labels: approved, dco-signoff: yes, kind/api-change, lgtm, release-note, size/XL

#6046 Fix test: handler losing connectivity
  tests/virt_control_plane_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/S

#6031 virt-launcher,DHCP: Not passing MAC address to the masquerade DHCP server
  pkg/network/dhcp/configurator.go
  pkg/network/dhcp/configurator_test.go
  pkg/network/dhcp/masquerade.go
  pkg/network/dhcp/masquerade_test.go
  pkg/network/driver/common.go
  pkg/network/driver/generated_mock_common.go
  pkg/virt-launcher/virtwrap/network/dhcp/dhcp.go
  pkg/virt-launcher/virtwrap/network/podinterface_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M

#4089 USB Redirection with usbredir
  api/openapi-spec/swagger.json
  cmd/virt-handler/virt-handler.go
  pkg/monitoring/api/prometheus.go
  pkg/virt-api/api.go
  pkg/virt-api/rest/BUILD.bazel
  pkg/virt-api/rest/usbredir.go
  pkg/virt-handler/rest/console.go
  pkg/virt-launcher/virtwrap/api/deepcopy_generated.go
  pkg/virt-launcher/virtwrap/api/schema.go
  pkg/virt-launcher/virtwrap/converter/converter.go
  pkg/virt-launcher/virtwrap/converter/converter_test.go
  pkg/virt-operator/resource/generate/components/validations_generated.go
  pkg/virtctl/BUILD.bazel
  pkg/virtctl/root.go
  pkg/virtctl/usbredir/BUILD.bazel
  pkg/virtctl/usbredir/usbredir.go
  staging/src/kubevirt.io/client-go/api/v1/deepcopy_generated.go
  staging/src/kubevirt.io/client-go/api/v1/openapi_generated.go
  staging/src/kubevirt.io/client-go/api/v1/schema.go
  staging/src/kubevirt.io/client-go/api/v1/schema_swagger_generated.go
  staging/src/kubevirt.io/client-go/apis/snapshot/v1alpha1/openapi_generated.go
  staging/src/kubevirt.io/client-go/kubecli/generated_mock_kubevirt.go
  staging/src/kubevirt.io/client-go/kubecli/handler.go
  staging/src/kubevirt.io/client-go/kubecli/kubevirt.go
  staging/src/kubevirt.io/client-go/kubecli/vmi.go
  tests/BUILD.bazel
  tests/usbredir_test.go
Labels: approved, dco-signoff: yes, kind/api-change, kind/build-change, lgtm, ok-to-test, release-note, size/XL

#6059 Revert "test: perftest: add sig-performance density test"
  Makefile
  hack/perftests.sh
  tests/BUILD.bazel
  tests/performance/BUILD.bazel
  tests/performance/density.go
  tests/performance/framework.go
  tests/tests_suite_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/L

#6051 network, masquerade: remove dead code
  pkg/network/infraconfigurators/masquerade.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/S

#6062 Replace dead "stress" binary with new, maintained, "stress-ng" binary
  WORKSPACE
  tests/migration_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/XS

#6066 [virt-controller]: Small refactoring to avoid code duplication
  pkg/virt-controller/watch/vm.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M

#6041 Non root vms
  cmd/virt-launcher/BUILD.bazel
  cmd/virt-launcher/qemu.conf
  cmd/virt-launcher/virt-launcher.go
  pkg/container-disk/container-disk.go
  pkg/ephemeral-disk-utils/utils.go
  pkg/network/cache/BUILD.bazel
  pkg/network/cache/infocache.go
  pkg/network/cache/infocache_test.go
  pkg/network/dhcp/BUILD.bazel
  pkg/network/dhcp/bridge_test.go
  pkg/network/infraconfigurators/BUILD.bazel
  pkg/network/infraconfigurators/bridge.go
  pkg/network/infraconfigurators/masquerade.go
  pkg/util/util.go
  pkg/virt-api/webhooks/mutating-webhook/mutators/BUILD.bazel
  pkg/virt-api/webhooks/mutating-webhook/mutators/vmi-mutator.go
  pkg/virt-api/webhooks/mutating-webhook/mutators/vmi-mutator_test.go
  pkg/virt-config/feature-gates.go
  pkg/virt-controller/services/BUILD.bazel
  pkg/virt-controller/services/template.go
  pkg/virt-controller/services/template_test.go
  pkg/virt-controller/watch/application.go
  pkg/virt-handler/BUILD.bazel
  pkg/virt-handler/migration-proxy/BUILD.bazel
  pkg/virt-handler/migration-proxy/migration-proxy.go
  pkg/virt-handler/migration-proxy/migration-proxy_test.go
  pkg/virt-handler/non-root.go
  pkg/virt-handler/vm.go
  pkg/virt-handler/vm_test.go
  pkg/virt-launcher/virtwrap/converter/converter.go
  pkg/virt-launcher/virtwrap/live-migration-source.go
  pkg/virt-launcher/virtwrap/live-migration-target.go
  pkg/virt-launcher/virtwrap/manager.go
  pkg/virt-launcher/virtwrap/manager_test.go
  pkg/virt-launcher/virtwrap/network/BUILD.bazel
  pkg/virt-launcher/virtwrap/network/podinterface_test.go
  pkg/virt-launcher/virtwrap/network/podnic_test.go
  pkg/virt-launcher/virtwrap/util/BUILD.bazel
  pkg/virt-launcher/virtwrap/util/libvirt_helper.go
  staging/src/kubevirt.io/client-go/api/v1/types.go
  tests/BUILD.bazel
  tests/migration_test.go
  tests/network/vmi_multus.go
  tests/nonroot_test.go
  tests/security_features_test.go
  tests/storage/hotplug.go
  tests/storage/storage.go
  tests/utils.go
  tests/vmi_hook_sidecar_test.go
  tests/vmi_lifecycle_test.go
  tests/vmipreset_test.go
Labels: approved, dco-signoff: yes, kind/api-change, kind/build-change, lgtm, release-note, size/XXL

#6049 [tests] allow configuration of e2e tests extra args
  hack/functests.sh
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/S

#6073 k8s reporter, Remove leftover mutex
  tests/reporter/kubernetes.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#6018 Fix url in components doc
  docs/components.md
Labels: approved, dco-signoff: yes, lgtm, ok-to-test, release-note-none, size/XS

#6068 Assert not all tests skipped
  automation/assert-not-all-tests-skipped.sh
  automation/test.sh
Labels: approved, dco-signoff: yes, lgtm, release-note, size/M

#6076 [SIG-scale] Add density performance tests to evaluate the Kubevirt control plane
  Makefile
  tests/BUILD.bazel
  tests/performance/BUILD.bazel
  tests/performance/density.go
  tests/performance/framework.go
  tests/tests_suite_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/L

#6040 Leave virt-launcher container up for failed VMI for improved debuggab…
  cmd/virt-launcher/virt-launcher.go
  pkg/virt-controller/services/template.go
  staging/src/kubevirt.io/client-go/api/v1/types.go
  tests/vm_test.go
Labels: approved, dco-signoff: yes, kind/api-change, lgtm, release-note, size/M

#5475 bazel test failure fix for arm64 and code optimize
  pkg/testutils/mock_config.go
  pkg/virt-config/config-map.go
  pkg/virt-config/virt-config.go
  pkg/virt-controller/services/template.go
  pkg/virt-controller/services/template_test.go
  pkg/virt-controller/watch/application.go
  pkg/virt-controller/watch/application_test.go
  pkg/virt-controller/watch/migration_test.go
  pkg/virt-controller/watch/vmi_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/L

#6019 Improve section titles
  README.md
Labels: approved, dco-signoff: yes, lgtm, ok-to-test, release-note-none, size/S

#5134 Fix pathes for oc and kubectl binaries on openshift ci
  hack/ci/entrypoint.sh
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/S

#5943 Prevent phase1 networking setup to run twice without using libvirt domain interface cache file
  pkg/network/cache/types.go
  pkg/network/infraconfigurators/bridge.go
  pkg/network/infraconfigurators/common.go
  pkg/network/infraconfigurators/generated_mock_common.go
  pkg/network/infraconfigurators/masquerade.go
  pkg/virt-launcher/virtwrap/network/BUILD.bazel
  pkg/virt-launcher/virtwrap/network/podnic.go
  pkg/virt-launcher/virtwrap/network/podnic_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/L

#6077 Reduce libguestfs image size
  WORKSPACE
  hack/rpm-deps.sh
  rpm/BUILD.bazel
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XXL

#5942 Online VM Snapshot with guest agent
  api/openapi-spec/swagger.json
  cmd/virt-handler/virt-handler.go
  manifests/generated/operator-csv.yaml.in
  manifests/generated/rbac-operator.authorization.k8s.yaml.in
  pkg/handler-launcher-com/cmd/v1/cmd.pb.go
  pkg/handler-launcher-com/cmd/v1/cmd.proto
  pkg/handler-launcher-com/cmd/v1/generated_mock_cmd.go
  pkg/virt-api/api.go
  pkg/virt-api/rest/subresource.go
  pkg/virt-api/rest/subresource_test.go
  pkg/virt-controller/watch/application.go
  pkg/virt-controller/watch/snapshot/snapshot.go
  pkg/virt-controller/watch/snapshot/snapshot_test.go
  pkg/virt-controller/watch/snapshot/util.go
  pkg/virt-handler/cmd-client/client.go
  pkg/virt-handler/cmd-client/generated_mock_client.go
  pkg/virt-handler/rest/lifecycle.go
  pkg/virt-launcher/virtwrap/agent-poller/agent_parser.go
  pkg/virt-launcher/virtwrap/agent-poller/agent_parser_test.go
  pkg/virt-launcher/virtwrap/agent-poller/agent_poller.go
  pkg/virt-launcher/virtwrap/api/schema.go
  pkg/virt-launcher/virtwrap/cmd-server/server.go
  pkg/virt-launcher/virtwrap/cmd-server/server_test.go
  pkg/virt-launcher/virtwrap/generated_mock_manager.go
  pkg/virt-launcher/virtwrap/manager.go
  pkg/virt-operator/resource/generate/rbac/controller.go
  staging/src/kubevirt.io/client-go/apis/snapshot/v1alpha1/types.go
  staging/src/kubevirt.io/client-go/kubecli/generated_mock_kubevirt.go
  staging/src/kubevirt.io/client-go/kubecli/handler.go
  staging/src/kubevirt.io/client-go/kubecli/kubevirt.go
  staging/src/kubevirt.io/client-go/kubecli/vmi.go
  staging/src/kubevirt.io/client-go/kubecli/vmi_test.go
  tests/console/login.go
  tests/storage/restore.go
  tests/storage/snapshot.go
  tests/utils.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/XXL

#6094 Quarantine sig-storage tests
  tests/storage/datavolume.go
  tests/storage/restore.go
  tests/storage/storage.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/S

#6075 k8s reporter, Refactor info collectors
  tests/reporter/kubernetes.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/L

#6084 [docs] remove redundant note from README.md
  README.md
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#6109 Allow NET_BIND_SERVICE in the virt-controller SCC
  pkg/virt-operator/resource/generate/components/scc.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/XS

#5728 Enable live migration of VMs with hotplug volumes
  api/openapi-spec/swagger.json
  docs/hotplug.md
  pkg/controller/controller.go
  pkg/host-disk/host-disk.go
  pkg/util/types/pvc.go
  pkg/virt-api/webhooks/validating-webhook/admitters/BUILD.bazel
  pkg/virt-api/webhooks/validating-webhook/admitters/vms-admitter.go
  pkg/virt-api/webhooks/validating-webhook/admitters/vms-admitter_test.go
  pkg/virt-controller/services/template.go
  pkg/virt-controller/watch/BUILD.bazel
  pkg/virt-controller/watch/application.go
  pkg/virt-controller/watch/application_test.go
  pkg/virt-controller/watch/migration.go
  pkg/virt-controller/watch/migration_test.go
  pkg/virt-controller/watch/vmi.go
  pkg/virt-controller/watch/vmi_test.go
  pkg/virt-handler/hotplug-disk/generated_mock_mount.go
  pkg/virt-handler/hotplug-disk/mount.go
  pkg/virt-handler/vm.go
  pkg/virt-handler/vm_test.go
  pkg/virt-operator/resource/generate/components/validations_generated.go
  staging/src/kubevirt.io/client-go/api/v1/openapi_generated.go
  staging/src/kubevirt.io/client-go/api/v1/types.go
  staging/src/kubevirt.io/client-go/api/v1/types_swagger_generated.go
  staging/src/kubevirt.io/client-go/apis/snapshot/v1alpha1/openapi_generated.go
  tests/storage/hotplug.go
Labels: approved, dco-signoff: yes, kind/api-change, lgtm, release-note, size/XL

#6100 network: delete duplicated function getEnvoyLoopbackAddress
  pkg/network/infraconfigurators/masquerade.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#6037 network: Add timeout to istio-proxy termination request
  cmd/virt-launcher/BUILD.bazel
  cmd/virt-launcher/virt-launcher.go
Labels: approved, dco-signoff: yes, kind/build-change, lgtm, release-note-none, size/M

#6001 Take test with id 2666 out of QUARANTINE
  tests/vmi_hook_sidecar_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#5826 Test ipam on secondary networks
  pkg/virt-handler/vm.go
  pkg/virt-handler/vm_test.go
  tests/network/vmi_multus.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/L

#6091 network: remove MTU link validation from the pod links
  pkg/network/infraconfigurators/bridge.go
  pkg/network/infraconfigurators/common.go
  pkg/network/infraconfigurators/masquerade.go
  pkg/virt-launcher/virtwrap/network/podinterface_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M

#6070 live-migration: initiate migration using a unix socket
  pkg/network/infraconfigurators/masquerade.go
  pkg/virt-launcher/virtwrap/live-migration-source.go
  pkg/virt-launcher/virtwrap/manager.go
  tests/network/vmi_networking.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/M

#6039 [release-0.41] Manual cherry pick of #5891
  pkg/virt-controller/watch/vmi.go
  pkg/virt-controller/watch/vmi_test.go
  tests/storage/datavolume.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/L

#5905 VM CrashLoop Detection and Exponential Backoff
  api/openapi-spec/swagger.json
  cmd/virt-launcher/virt-launcher.go
  pkg/virt-api/rest/subresource.go
  pkg/virt-api/rest/subresource_test.go
  pkg/virt-controller/services/template.go
  pkg/virt-controller/services/template_test.go
  pkg/virt-controller/watch/application.go
  pkg/virt-controller/watch/application_test.go
  pkg/virt-controller/watch/vm.go
  pkg/virt-controller/watch/vm_test.go
  pkg/virt-controller/watch/vmi.go
  pkg/virt-controller/watch/vmi_test.go
  pkg/virt-operator/resource/generate/components/validations_generated.go
  staging/src/kubevirt.io/client-go/api/v1/deepcopy_generated.go
  staging/src/kubevirt.io/client-go/api/v1/openapi_generated.go
  staging/src/kubevirt.io/client-go/api/v1/types.go
  staging/src/kubevirt.io/client-go/api/v1/types_swagger_generated.go
  staging/src/kubevirt.io/client-go/apis/snapshot/v1alpha1/openapi_generated.go
  tests/vm_test.go
  tools/util/marshaller.go
Labels: approved, dco-signoff: yes, kind/api-change, lgtm, release-note, size/XXL

#6115 Make docs/metrix.md fully auto-generated
  docs/metrics.md
  hack/generate.sh
  pkg/monitoring/domainstats/prometheus/prometheus.go
  tools/doc-generator/doc-generator.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/L

#6119 Add Zvi Cahana to reviewers
  OWNERS_ALIASES
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#6098 configure virt-handler max-device with kubelet maxPods
  cmd/virt-handler/virt-handler.go
Labels: approved, dco-signoff: yes, kind/build-change, lgtm, release-note-none, size/XS

#6134 Take test_id:4100 out of quarantine
  tests/infra_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#6131 Remove quarantine label
  tests/vmi_configuration_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#6111 network, istio: Introduce pkg/network/istio package
  cmd/virt-launcher/BUILD.bazel
  cmd/virt-launcher/virt-launcher.go
  pkg/network/consts/BUILD.bazel
  pkg/network/consts/annotations.go
  pkg/network/infraconfigurators/BUILD.bazel
  pkg/network/infraconfigurators/masquerade.go
  pkg/network/istio/BUILD.bazel
  pkg/network/istio/annotations.go
  pkg/network/istio/ports.go
  pkg/network/istio/proxy.go
  pkg/virt-controller/services/BUILD.bazel
  pkg/virt-controller/services/template.go
  pkg/virt-controller/services/template_test.go
  pkg/virt-launcher/virtwrap/network/BUILD.bazel
  pkg/virt-launcher/virtwrap/network/podinterface_test.go
  tests/network/BUILD.bazel
  tests/network/vmi_istio.go
Labels: approved, dco-signoff: yes, kind/build-change, lgtm, release-note-none, size/L

#6104 Detect and report a FailedUnschedulable VM status
  pkg/virt-controller/watch/vm.go
  pkg/virt-controller/watch/vm_test.go
  staging/src/kubevirt.io/client-go/api/v1/types.go
  tests/vm_test.go
Labels: approved, dco-signoff: yes, kind/api-change, lgtm, release-note, size/M

#6136 Add numbers to the new snapshot and restore tests
  tests/storage/restore.go
  tests/storage/snapshot.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/S

#6146 fix racy check in test 5257
  tests/storage/restore.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#6139 [Sig-scale] add scripts to build and run performance density tests
  hack/perftests.sh
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M

#6121 k8s reporter, Use virt-chroot in logDMESG
  tests/reporter/kubernetes.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/S

#6096 Increase VM creation timeout in VmWatch test
  tests/vm_watch_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#6158 [release-0.41] Generate cloud-init paths without creating directories
  pkg/cloud-init/cloud-init.go
  tests/vmi_cloudinit_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/S

#6105 allow users to set MaxDevices on KubeVirt CR
  api/openapi-spec/swagger.json
  manifests/generated/kv-resource.yaml
  pkg/virt-operator/resource/apply/BUILD.bazel
  pkg/virt-operator/resource/apply/apps.go
  pkg/virt-operator/resource/apply/apps_test.go
  pkg/virt-operator/resource/apply/reconcile.go
  pkg/virt-operator/resource/generate/components/validations_generated.go
  staging/src/kubevirt.io/client-go/api/v1/deepcopy_generated.go
  staging/src/kubevirt.io/client-go/api/v1/openapi_generated.go
  staging/src/kubevirt.io/client-go/api/v1/types.go
  staging/src/kubevirt.io/client-go/apis/snapshot/v1alpha1/openapi_generated.go
Labels: approved, dco-signoff: yes, kind/api-change, lgtm, release-note, size/L

#6156 reduce further the libguestfs-tools image size
  WORKSPACE
  hack/rpm-deps.sh
  rpm/BUILD.bazel
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XL

#6163 Handle Zombie QEMU Processes
  cmd/virt-launcher/virt-launcher.go
  pkg/virt-launcher/monitor.go
  pkg/virt-launcher/monitor_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/M

#6145 virt-launcher: libvirt and qemu conf cleanup
  cmd/virt-launcher/libvirtd.conf
  pkg/virt-launcher/virtwrap/util/libvirt_helper.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/S

#6155 libvirt_helper: fix typo
  pkg/virt-launcher/virtwrap/util/libvirt_helper.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/S

#6035 [Sig Scale] PerfScale Audit Tool
  BUILD.bazel
  go.mod
  hack/bazel-build.sh
  tools/perfscale-audit/BUILD.bazel
  tools/perfscale-audit/api/BUILD.bazel
  tools/perfscale-audit/api/api.go
  tools/perfscale-audit/metric-client/BUILD.bazel
  tools/perfscale-audit/metric-client/metric-client.go
  tools/perfscale-audit/perfscale-audit.go
  vendor/github.com/prometheus/client_golang/api/BUILD.bazel
  vendor/github.com/prometheus/client_golang/api/client.go
  vendor/github.com/prometheus/client_golang/api/prometheus/v1/BUILD.bazel
  vendor/github.com/prometheus/client_golang/api/prometheus/v1/api.go
  vendor/modules.txt
Labels: approved, dco-signoff: yes, lgtm, release-note, size/XXL

#6143 refactor snapshot controller
  pkg/virt-controller/watch/snapshot/BUILD.bazel
  pkg/virt-controller/watch/snapshot/snapshot.go
  pkg/virt-controller/watch/snapshot/snapshot_base.go
  pkg/virt-controller/watch/snapshot/snapshot_test.go
  pkg/virt-controller/watch/snapshot/source.go
  pkg/virt-controller/watch/snapshot/util.go
  staging/src/kubevirt.io/client-go/apis/snapshot/v1alpha1/types.go
  tests/storage/restore.go
  tests/storage/snapshot.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XXL
