Repository kubevirt/kubevirt, pull requests merged in 2021-11, with the labels that each got.

#6445 [Non-root] Unify DV with PVC handling
  pkg/host-disk/host-disk.go
  tests/framework/storage/BUILD.bazel
  tests/framework/storage/nfs.go
  tests/storage/datavolume.go
  tests/storage/storage.go
  tests/utils.go
Labels: size/L, release-note-none, lgtm, approved, dco-signoff: yes

#6679 net, dns: Move most of the dns subpackage under network
  pkg/network/dns/BUILD.bazel
  pkg/network/dns/dns_suite_test.go
  pkg/network/dns/resolveconf.go
  pkg/network/dns/resolveconf_test.go
  pkg/util/net/dns/BUILD.bazel
  pkg/virt-launcher/virtwrap/converter/BUILD.bazel
  pkg/virt-launcher/virtwrap/converter/network.go
  tests/BUILD.bazel
  tests/windows_test.go
Labels: size/M, sig/network, release-note-none, lgtm, approved, dco-signoff: yes

#6639 Fix added vMI configuration to support ARM
  examples/vmi-arm.yaml
  tools/vms-generator/utils/utils.go
  tools/vms-generator/vms-generator.go
Labels: size/M, release-note-none, lgtm, approved, ok-to-test, dco-signoff: yes

#6683 [release-0.44] Fix issues in up metrics and alerts based on namespace labels
  hack/prom-rule-ci/prom-rules-tests.yaml
  manifests/generated/operator-csv.yaml.in
  pkg/virt-operator/resource/apply/core_test.go
  pkg/virt-operator/resource/generate/components/crds.go
  pkg/virt-operator/resource/generate/components/deployments.go
  pkg/virt-operator/resource/generate/components/webhooks.go
  tests/infra_test.go
Labels: size/L, release-note, lgtm, approved, dco-signoff: yes

#5981 Online resize support: respond to PVC expansion
  api/openapi-spec/swagger.json
  docs/disk-expansion.md
  pkg/container-disk/validation.go
  pkg/controller/virtinformers.go
  pkg/handler-launcher-com/cmd/v1/cmd.pb.go
  pkg/handler-launcher-com/cmd/v1/cmd.proto
  pkg/virt-config/feature-gates.go
  pkg/virt-controller/watch/application.go
  pkg/virt-controller/watch/application_test.go
  pkg/virt-controller/watch/vmi.go
  pkg/virt-controller/watch/vmi_test.go
  pkg/virt-handler/options.go
  pkg/virt-handler/vm.go
  pkg/virt-launcher/virtwrap/api/BUILD.bazel
  pkg/virt-launcher/virtwrap/api/deepcopy_generated.go
  pkg/virt-launcher/virtwrap/api/schema.go
  pkg/virt-launcher/virtwrap/cli/generated_mock_libvirt.go
  pkg/virt-launcher/virtwrap/cli/libvirt.go
  pkg/virt-launcher/virtwrap/converter/converter.go
  pkg/virt-launcher/virtwrap/converter/converter_test.go
  pkg/virt-launcher/virtwrap/manager.go
  pkg/virt-launcher/virtwrap/manager_test.go
  pkg/virt-operator/resource/generate/components/validations_generated.go
  staging/src/kubevirt.io/client-go/apis/core/v1/deepcopy_generated.go
  staging/src/kubevirt.io/client-go/apis/core/v1/openapi_generated.go
  staging/src/kubevirt.io/client-go/apis/core/v1/types.go
  staging/src/kubevirt.io/client-go/apis/core/v1/types_swagger_generated.go
  staging/src/kubevirt.io/client-go/apis/snapshot/v1alpha1/openapi_generated.go
  tests/storage/datavolume.go
  tests/storage/storage.go
  tests/utils.go
Labels: size/XL, release-note, kind/api-change, lgtm, approved, kind/build-change, dco-signoff: yes

#6663 Make the number of replicas for virt- pods configurable
  api/openapi-spec/swagger.json
  manifests/generated/kv-resource.yaml
  pkg/virt-operator/kubevirt_test.go
  pkg/virt-operator/resource/apply/apps.go
  pkg/virt-operator/resource/apply/reconcile.go
  pkg/virt-operator/resource/apply/update.go
  pkg/virt-operator/resource/generate/components/deployments.go
  pkg/virt-operator/resource/generate/components/validations_generated.go
  pkg/virt-operator/webhooks/kubevirt-update-admitter.go
  staging/src/kubevirt.io/client-go/apis/core/v1/componentconfig.go
  staging/src/kubevirt.io/client-go/apis/core/v1/deepcopy_generated.go
  staging/src/kubevirt.io/client-go/apis/core/v1/openapi_generated.go
  staging/src/kubevirt.io/client-go/apis/snapshot/v1alpha1/openapi_generated.go
  tests/operator_test.go
Labels: size/L, release-note, lgtm, approved, dco-signoff: yes

#6506 Remove BeforeAll from Multus tests
  tests/network/vmi_multus.go
Labels: size/XS, release-note-none, lgtm, approved, dco-signoff: yes

#6656 [release-0.44] tests: manual cherry pick of 6302
  tests/storage/storage.go
Labels: size/XS, release-note-none, lgtm, approved, dco-signoff: yes

#6704 Adding ARM to ADOPTERS file
  ADOPTERS.md
Labels: kind/enhancement, size/XS, release-note-none, lgtm, approved, dco-signoff: yes

#6716 [release-0.44] Reference containerDisks and kernel boot images in reproducible format during migrations
  pkg/container-disk/container-disk.go
  pkg/container-disk/container-disk_test.go
  pkg/testutils/matchers.go
  pkg/virt-controller/services/template.go
  pkg/virt-controller/watch/migration.go
  pkg/virt-controller/watch/migration_test.go
  tests/migration_test.go
Labels: size/L, release-note, lgtm, approved, dco-signoff: yes

#6681 Add dry run functionality for stop start restart commands
  api/openapi-spec/swagger.json
  pkg/util/status/BUILD.bazel
  pkg/util/status/status.go
  pkg/util/status/status_test.go
  pkg/virt-api/api.go
  pkg/virt-api/rest/subresource.go
  pkg/virt-api/rest/subresource_test.go
  pkg/virt-controller/watch/workload-updater/workload-updater_test.go
  pkg/virtctl/vm/vm.go
  pkg/virtctl/vm/vm_test.go
  staging/src/kubevirt.io/client-go/apis/core/v1/deepcopy_generated.go
  staging/src/kubevirt.io/client-go/apis/core/v1/openapi_generated.go
  staging/src/kubevirt.io/client-go/apis/core/v1/types.go
  staging/src/kubevirt.io/client-go/apis/core/v1/types_swagger_generated.go
  staging/src/kubevirt.io/client-go/apis/snapshot/v1alpha1/openapi_generated.go
  staging/src/kubevirt.io/client-go/kubecli/generated_mock_kubevirt.go
  staging/src/kubevirt.io/client-go/kubecli/kubevirt.go
  staging/src/kubevirt.io/client-go/kubecli/kv.go
  staging/src/kubevirt.io/client-go/kubecli/kv_test.go
  staging/src/kubevirt.io/client-go/kubecli/vm.go
  staging/src/kubevirt.io/client-go/kubecli/vm_test.go
  tests/operator_test.go
  tests/storage/restore.go
  tests/storage/snapshot.go
  tests/subresource_api_test.go
  tests/utils.go
  tests/vm_test.go
  tests/vm_watch_test.go
Labels: size/XL, release-note, lgtm, approved, ok-to-test, dco-signoff: yes

#6726 [virt-controller]: Use separate REST client with fixed rate limiter for the leader elector
  pkg/virt-controller/watch/application.go
Labels: size/L, release-note-none, lgtm, approved, dco-signoff: yes

#6713 Add a WaitingForVolumeBinding printable status
  pkg/virt-controller/watch/vm.go
  pkg/virt-controller/watch/vm_test.go
  staging/src/kubevirt.io/client-go/apis/core/v1/types.go
Labels: size/L, release-note, lgtm, approved, dco-signoff: yes

#6721 Set default CPU model in VMI spec, even if not defined in KubevirtCR
  pkg/virt-api/webhooks/arm64.go
  pkg/virt-api/webhooks/mutating-webhook/mutators/vmi-mutator.go
  pkg/virt-api/webhooks/mutating-webhook/mutators/vmi-mutator_test.go
  staging/src/kubevirt.io/client-go/apis/core/v1/schema.go
  tests/flavor_test.go
  tests/vmi_lifecycle_test.go
Labels: size/M, release-note, lgtm, approved, dco-signoff: yes

#6723 pdb: reconcile all old pdbs
  pkg/util/pdbs/pdbs.go
  tests/migration_test.go
Labels: size/M, release-note, lgtm, approved, dco-signoff: yes

#6722 Remove obsolete scheduler.alpha.kubernetes.io/critical-pod annotation
  manifests/generated/operator-csv.yaml.in
  pkg/virt-operator/resource/generate/components/deployments.go
Labels: release-note, size/XS, lgtm, approved, dco-signoff: yes

#6746 Fix sig-storage lane flakiness: Adjust output instead of disabling featuregate
  tests/storage/storage.go
Labels: size/XS, release-note-none, lgtm, approved, dco-signoff: yes

#6749 Add release-note NONE to the changelog generation
  hack/whatchanged.sh
Labels: size/XS, release-note-none, lgtm, approved, dco-signoff: yes

#6772 Revert #6565: kubevirt's components managed-by label's value changed to virt-operator
  pkg/virt-operator/resource/apply/apps_test.go
  pkg/virt-operator/resource/apply/reconcile_test.go
  staging/src/kubevirt.io/client-go/apis/core/v1/types.go
Labels: release-note, size/XS, lgtm, approved, dco-signoff: yes

#6745 Fix sig-storage flakiness: Use a smaller image for test
  tests/storage/storage.go
Labels: size/XS, release-note-none, lgtm, approved, dco-signoff: yes

#6162 Always add hint-dedicated kvm feature with dedicated cpus to allow guest optimizations
  pkg/virt-launcher/virtwrap/api/deepcopy_generated.go
  pkg/virt-launcher/virtwrap/api/schema.go
  pkg/virt-launcher/virtwrap/api/schema_test.go
  pkg/virt-launcher/virtwrap/converter/converter.go
  tests/vmi_configuration_test.go
Labels: size/S, release-note, lgtm, approved, dco-signoff: yes

#6758 virt-handler, net: Simplify critical-error handling
  pkg/network/errors/errors.go
  pkg/virt-handler/vm.go
Labels: size/M, sig/network, release-note-none, lgtm, approved, dco-signoff: yes

#6767 Add initial FOSSA documentation
  docs/fossa.md
Labels: size/M, release-note-none, lgtm, approved, dco-signoff: yes

#6741 Fix node_labeller flaky test
  pkg/virt-handler/node-labeller/node_labeller_test.go
Labels: size/S, release-note-none, lgtm, approved, ok-to-test, dco-signoff: yes

#6751 Record VMI phase counts
  tools/perfscale-audit/api/api.go
  tools/perfscale-audit/metric-client/metric-client.go
Labels: size/M, release-note-none, lgtm, approved, dco-signoff: yes

#6710 [virt-launcher]: Stop logging successful shutdown when it isn't true
  cmd/virt-launcher/virt-launcher.go
Labels: release-note, size/XS, lgtm, approved, dco-signoff: yes

#6739 Solve flakiness for libguestfs tests
  cmd/libguestfs/entrypoint.sh
  tests/storage/guestfs.go
  tests/utils.go
Labels: size/M, release-note-none, lgtm, approved, dco-signoff: yes

#6509 Remove BeforeAll from SRIOV tests
  tests/network/vmi_multus.go
Labels: sig/network, size/XL, release-note-none, lgtm, approved, dco-signoff: yes

#6686 examples, cloud-init: use cloud-config instead of bash
  examples/vmi-macvtap.yaml
  examples/vmi-masquerade.yaml
  examples/vmi-multus-multiple-net.yaml
  examples/vmi-multus-ptp.yaml
  examples/vmi-slirp.yaml
  examples/vmi-sriov.yaml
  tools/vms-generator/utils/utils.go
Labels: size/L, release-note-none, lgtm, approved, dco-signoff: yes

#6664 Enable display and ramfb for vGPUs
  api/openapi-spec/swagger.json
  pkg/virt-launcher/virtwrap/api/schema.go
  pkg/virt-launcher/virtwrap/device/hostdevice/BUILD.bazel
  pkg/virt-launcher/virtwrap/device/hostdevice/generic/hostdev.go
  pkg/virt-launcher/virtwrap/device/hostdevice/gpu/hostdev.go
  pkg/virt-launcher/virtwrap/device/hostdevice/gpu/hostdev_test.go
  pkg/virt-launcher/virtwrap/device/hostdevice/hostdev.go
  pkg/virt-launcher/virtwrap/device/hostdevice/hostdev_test.go
  pkg/virt-operator/resource/generate/components/validations_generated.go
  staging/src/kubevirt.io/client-go/apis/core/v1/deepcopy_generated.go
  staging/src/kubevirt.io/client-go/apis/core/v1/openapi_generated.go
  staging/src/kubevirt.io/client-go/apis/core/v1/schema.go
  staging/src/kubevirt.io/client-go/apis/core/v1/schema_swagger_generated.go
  staging/src/kubevirt.io/client-go/apis/core/v1/zz_generated.defaults.go
  staging/src/kubevirt.io/client-go/apis/snapshot/v1alpha1/openapi_generated.go
  tests/mdev_configuration_allocation_test.go
Labels: size/XL, release-note, kind/api-change, lgtm, approved, dco-signoff: yes

#6778 Reduce sig-storage flakiness: Use a smaller image for NFS test
  tests/storage/datavolume.go
Labels: size/XS, release-note-none, lgtm, approved, dco-signoff: yes

#6508 virt-launcher, Add subdomain name to search list
  pkg/network/cache/types.go
  pkg/network/dhcp/bridge.go
  pkg/network/dhcp/configurator.go
  pkg/network/dhcp/configurator_test.go
  pkg/network/dhcp/masquerade.go
  pkg/network/dhcp/server/BUILD.bazel
  pkg/network/dhcp/server/server.go
  pkg/network/dhcp/server/server_test.go
  pkg/network/dns/resolveconf.go
  pkg/network/dns/resolveconf_test.go
  pkg/network/driver/BUILD.bazel
  pkg/network/driver/common.go
  pkg/network/setup/podnic.go
  tests/network/BUILD.bazel
  tests/network/vmi_subdomain.go
  tests/windows_test.go
Labels: size/L, sig/network, release-note, lgtm, approved, dco-signoff: yes

#6750 virt-handler, net: Drop virt-launcher pid usage in cache
  pkg/virt-handler/vm.go
  pkg/virt-handler/vm_test.go
Labels: size/S, sig/network, release-note-none, lgtm, approved, dco-signoff: yes

#6753 Remove handler gets pvc backport #6226
  api/openapi-spec/swagger.json
  manifests/generated/operator-csv.yaml.in
  manifests/generated/rbac-operator.authorization.k8s.yaml.in
  pkg/host-disk/BUILD.bazel
  pkg/host-disk/host-disk.go
  pkg/host-disk/host-disk_test.go
  pkg/util/types/BUILD.bazel
  pkg/util/types/pvc.go
  pkg/util/types/pvc_test.go
  pkg/virt-controller/watch/vmi.go
  pkg/virt-controller/watch/vmi_test.go
  pkg/virt-handler/BUILD.bazel
  pkg/virt-handler/vm.go
  pkg/virt-handler/vm_test.go
  pkg/virt-operator/resource/generate/components/validations_generated.go
  pkg/virt-operator/resource/generate/rbac/handler.go
  staging/src/kubevirt.io/client-go/api/v1/deepcopy_generated.go
  staging/src/kubevirt.io/client-go/api/v1/openapi_generated.go
  staging/src/kubevirt.io/client-go/api/v1/types.go
  staging/src/kubevirt.io/client-go/api/v1/types_swagger_generated.go
  staging/src/kubevirt.io/client-go/apis/snapshot/v1alpha1/openapi_generated.go
Labels: size/XL, release-note-none, kind/api-change, lgtm, approved, dco-signoff: yes

#6787 Quarantine flaky sig-compute test
  tests/infra_test.go
Labels: size/XS, release-note-none, lgtm, approved, dco-signoff: yes

#6641 Fix migration limitation for test_id 5004
  pkg/virt-launcher/virtwrap/live-migration-source.go
  tests/migration_test.go
Labels: size/XS, release-note-none, lgtm, approved, dco-signoff: yes

#6730 change kubevrit cert secret type from Opaque to kubernetes.io/tls
  pkg/virt-operator/resource/generate/components/secrets.go
  tests/infra_test.go
Labels: size/S, release-note, lgtm, approved, ok-to-test, dco-signoff: yes

#6760 virt-handler: Refactor claimDeviceOwnership method
  pkg/virt-handler/vm.go
Labels: size/M, release-note-none, lgtm, approved, dco-signoff: yes

#6774 tests, multus: Add params to createBridgeNetworkAttachmentDefinition
  tests/network/vmi_multus.go
Labels: size/S, release-note-none, lgtm, approved, ok-to-test, dco-signoff: yes

#6734 stabilize [test_id:4746] by extracting libvirt's pid in a different way
  tests/migration_test.go
Labels: size/M, release-note, lgtm, approved, ok-to-test, dco-signoff: yes

#6650 Enable sound devices
  api/openapi-spec/swagger.json
  pkg/virt-api/webhooks/validating-webhook/admitters/vmi-create-admitter.go
  pkg/virt-api/webhooks/validating-webhook/admitters/vmi-create-admitter_test.go
  pkg/virt-launcher/virtwrap/api/deepcopy_generated.go
  pkg/virt-launcher/virtwrap/api/schema.go
  pkg/virt-launcher/virtwrap/converter/converter.go
  pkg/virt-launcher/virtwrap/converter/converter_test.go
  pkg/virt-operator/resource/generate/components/validations_generated.go
  staging/src/kubevirt.io/api/core/v1/deepcopy_generated.go
  staging/src/kubevirt.io/api/core/v1/schema.go
  staging/src/kubevirt.io/api/core/v1/schema_swagger_generated.go
  staging/src/kubevirt.io/client-go/api/openapi_generated.go
  tests/BUILD.bazel
  tests/vmi_sound_test.go
Labels: size/L, release-note, kind/api-change, lgtm, approved, dco-signoff: yes

#6649 Expose component label via the KubeVirt CR
  api/openapi-spec/swagger.json
  manifests/generated/kv-resource.yaml
  pkg/virt-operator/kubevirt_test.go
  pkg/virt-operator/resource/apply/apps_test.go
  pkg/virt-operator/resource/apply/pdb_test.go
  pkg/virt-operator/resource/apply/reconcile.go
  pkg/virt-operator/resource/generate/components/daemonsets.go
  pkg/virt-operator/resource/generate/components/deployments.go
  pkg/virt-operator/resource/generate/components/validations_generated.go
  pkg/virt-operator/resource/generate/install/strategy.go
  pkg/virt-operator/util/config.go
  staging/src/kubevirt.io/api/core/v1/types.go
  staging/src/kubevirt.io/api/core/v1/types_swagger_generated.go
  staging/src/kubevirt.io/client-go/api/openapi_generated.go
  staging/src/kubevirt.io/client-go/apis/core/v1/BUILD.bazel
  staging/src/kubevirt.io/client-go/apis/core/v1/openapi_generated.go
  tests/operator_test.go
Labels: release-note, size/XXL, kind/api-change, lgtm, approved, ok-to-test, dco-signoff: yes

#6724 Fix ServiceMonitor test for new versions of PrometheusOperator
  tests/operator_test.go
Labels: size/S, release-note-none, lgtm, approved, dco-signoff: yes

#6797 tests, network: Add param to libvmi.InterfaceDeviceWithBridgeBinding
  tests/libvmi/network.go
  tests/network/primary_pod_network.go
  tests/network/services.go
  tests/network/vmi_subdomain.go
Labels: size/S, release-note-none, lgtm, approved, ok-to-test, dco-signoff: yes

#6814 Remove non inclusive text
  CONTRIBUTING.md
  docs/devel/networking.md
  docs/devel/olm-integration.md
  docs/devel/storage.md
  docs/env-providers.md
  docs/getting-started.md
  docs/kubernetes-compatibility.md
  docs/localstorage-disks.md
  docs/monitoring-guidelines.md
  docs/quarantine.md
  docs/release-branch-backporting.md
  docs/release.md
  docs/reviewer-guide.md
  docs/sriov.md
  docs/update-go-version.md
  hack/autobump-generic.sh
  hack/autobump-kubevirtci.sh
  hack/builder/Dockerfile
  hack/gen-swagger-doc/deploy.sh
  hack/gen-swagger-doc/gen-swagger-docs.sh
  pkg/virt-handler/hotplug-disk/mount.go
  pkg/virt-handler/hotplug-disk/mount_test.go
  pkg/virt-handler/isolation/detector.go
  pkg/virt-handler/isolation/detector_test.go
  pkg/virt-handler/isolation/generated_mock_detector.go
  tests/credentials_test.go
Labels: size/L, release-note, lgtm, approved, ok-to-test, dco-signoff: yes

#6737 Timeout Unschedulable Migration Target Pods
  pkg/virt-controller/watch/migration.go
  pkg/virt-controller/watch/migration_test.go
  staging/src/kubevirt.io/api/core/v1/types.go
  tests/migration_test.go
Labels: size/L, release-note, lgtm, approved, dco-signoff: yes

#6810 Document client-gen usage for thirt party integration
  staging/src/kubevirt.io/api/README.md
Labels: size/M, release-note-none, lgtm, approved, dco-signoff: yes

#6503 Fix flaky Macvtap test: Increase macvtap interface IP report timeout
  tests/network/vmi_multus.go
Labels: sig/network, size/XS, release-note-none, lgtm, approved, dco-signoff: yes

#6808 [release-0.41] Skip VirtIO-FS tests if the feature gate is disabled
  tests/storage/storage.go
Labels: size/XS, release-note-none, lgtm, approved, dco-signoff: yes

#6766 tests, multus: Add integration test for bridge CNI MAC spoof check
  tests/network/vmi_multus.go
Labels: size/M, release-note-none, lgtm, approved, ok-to-test, dco-signoff: yes

#6725 Add dry run functionality for pause and unpause commands
  api/openapi-spec/swagger.json
  pkg/virt-api/api.go
  pkg/virt-api/rest/subresource.go
  pkg/virt-api/rest/subresource_test.go
  pkg/virtctl/pause/BUILD.bazel
  pkg/virtctl/pause/pause.go
  pkg/virtctl/pause/pause_test.go
  pkg/virtctl/vm/vm.go
  staging/src/kubevirt.io/api/core/v1/deepcopy_generated.go
  staging/src/kubevirt.io/api/core/v1/types.go
  staging/src/kubevirt.io/api/core/v1/types_swagger_generated.go
  staging/src/kubevirt.io/client-go/api/openapi_generated.go
  staging/src/kubevirt.io/client-go/kubecli/generated_mock_kubevirt.go
  staging/src/kubevirt.io/client-go/kubecli/kubevirt.go
  staging/src/kubevirt.io/client-go/kubecli/vmi.go
  staging/src/kubevirt.io/client-go/kubecli/vmi_test.go
  tests/migration_test.go
  tests/pausing_test.go
Labels: size/XL, release-note, lgtm, approved, ok-to-test, dco-signoff: yes

#6812 Fix flaky test [7164] for PR 6040: Leave virt-launcher container up for failed VMI
  tests/vm_test.go
Labels: size/M, release-note-none, lgtm, approved, dco-signoff: yes

#6714 virt-launcher: decrease timeout for http get when detecting Istio
  cmd/virt-launcher/virt-launcher.go
Labels: release-note, size/XS, lgtm, approved, dco-signoff: yes

#6832 Fix DV not being deleted in AfterEach()
  tests/migration_test.go
Labels: size/XS, release-note-none, lgtm, approved, dco-signoff: yes

#6773 alert if migration for VMI with host-model CPU is stuck since no node is suitable
  pkg/virt-controller/watch/migration.go
  pkg/virt-controller/watch/vmi.go
Labels: size/M, release-note, lgtm, approved, dco-signoff: yes

#6827 Fix certificate rotation tests
  tests/infra_test.go
Labels: size/XS, release-note-none, lgtm, approved, dco-signoff: yes

#6790 [release-0.41] Ensure that the BeforeTest function is actually called
  tests/template_test.go
Labels: size/XS, release-note-none, lgtm, approved, dco-signoff: yes

#6780 Fix dry run using stop virctl command with grace-period
  pkg/controller/controller_ref_manager.go
  pkg/virt-api/rest/subresource.go
  pkg/virt-controller/watch/migration.go
  pkg/virt-controller/watch/migration_test.go
  pkg/virt-controller/watch/node.go
  pkg/virt-controller/watch/node_test.go
  pkg/virt-controller/watch/replicaset_test.go
  pkg/virt-controller/watch/vm.go
  pkg/virt-controller/watch/vm_test.go
  pkg/virt-controller/watch/vmi.go
  pkg/virt-controller/watch/vmi_test.go
  staging/src/kubevirt.io/client-go/kubecli/generated_mock_kubevirt.go
  staging/src/kubevirt.io/client-go/kubecli/kubevirt.go
  staging/src/kubevirt.io/client-go/kubecli/vmi.go
  tests/utils.go
  tests/vm_test.go
Labels: size/M, release-note, lgtm, approved, ok-to-test, dco-signoff: yes

#6840 Add test_id for Error status when missing PVC or DV
  tests/vm_test.go
Labels: size/XS, release-note-none, lgtm, approved, dco-signoff: yes

#6805 [release-0.41] Fix [test_id:6978] Should detect a failed migration
  tests/migration.go
  tests/migration_test.go
Labels: size/S, release-note-none, lgtm, approved, dco-signoff: yes

#6804 [test_id:5004]: Update migration configurations correctly
  tests/migration_test.go
Labels: size/L, release-note-none, lgtm, approved, dco-signoff: yes

#6850 Introduce unit test for validation.go
  pkg/container-disk/BUILD.bazel
  pkg/container-disk/validation_test.go
Labels: size/M, release-note-none, lgtm, approved, dco-signoff: yes

#6862 Fix kernel boot description typo
  api/openapi-spec/swagger.json
  pkg/virt-operator/resource/generate/components/validations_generated.go
  staging/src/kubevirt.io/api/core/v1/schema.go
  staging/src/kubevirt.io/api/core/v1/schema_swagger_generated.go
  staging/src/kubevirt.io/client-go/api/openapi_generated.go
Labels: size/S, release-note-none, lgtm, approved, dco-signoff: yes

#6858 [virtctl] Initialize the Headers field for some auth plugins
  staging/src/kubevirt.io/client-go/kubecli/vmi.go
Labels: release-note, size/XS, lgtm, approved, dco-signoff: yes

#6757 Update test (test_id:6981) - Check migration of VM with the default CPU instead of explicitly set 'host-model'
  tests/migration_test.go
Labels: size/XS, release-note-none, lgtm, approved, dco-signoff: yes

#6815 [release-0.41] pdb: reconcile all old pdbs
  pkg/util/pdbs/pdbs.go
  tests/migration_test.go
Labels: size/M, release-note, lgtm, approved, dco-signoff: yes

#6869 Fix kubevirtci download url
  hack/sync-kubevirtci.sh
Labels: size/XS, release-note-none, lgtm, approved, dco-signoff: yes

#6841 Fix null pointer dereference in virt-handler
  pkg/virt-handler/rest/lifecycle.go
Labels: size/S, release-note-none, lgtm, approved, dco-signoff: yes

#6855 Remove now stable tests from quarantine
  tests/infra_test.go
  tests/storage/guestfs.go
Labels: size/XS, release-note-none, lgtm, approved, dco-signoff: yes

#6829 Add name field to sound devices
  api/openapi-spec/swagger.json
  pkg/virt-api/webhooks/validating-webhook/admitters/vmi-create-admitter.go
  pkg/virt-api/webhooks/validating-webhook/admitters/vmi-create-admitter_test.go
  pkg/virt-launcher/virtwrap/api/deepcopy_generated.go
  pkg/virt-launcher/virtwrap/api/schema.go
  pkg/virt-launcher/virtwrap/converter/converter.go
  pkg/virt-launcher/virtwrap/converter/converter_test.go
  pkg/virt-operator/resource/generate/components/validations_generated.go
  staging/src/kubevirt.io/api/core/v1/schema.go
  staging/src/kubevirt.io/api/core/v1/schema_swagger_generated.go
  staging/src/kubevirt.io/client-go/api/openapi_generated.go
  tests/vmi_sound_test.go
Labels: size/M, release-note-none, lgtm, approved, dco-signoff: yes

#6838 tests, multus: Rename NAD format string constants
  tests/network/vmi_multus.go
Labels: size/S, release-note-none, lgtm, approved, ok-to-test, dco-signoff: yes

#6856 Fix typos in virtctl comments
  pkg/virtctl/imageupload/imageupload.go
Labels: size/XS, release-note-none, lgtm, approved, ok-to-test, dco-signoff: yes

#5334 Refactor func processVmShutdown
  pkg/virt-handler/vm.go
Labels: size/M, release-note-none, lgtm, approved, ok-to-test, dco-signoff: yes

#6672 Fix for lun disks
  WORKSPACE
  hack/bootstrap.sh
  hack/rpm-deps.sh
  rpm/BUILD.bazel
  tests/io_utils.go
  tests/storage/storage.go
Labels: size/L, release-note-none, lgtm, approved, dco-signoff: yes

#6533 Mark paused VMs as unready
  manifests/generated/operator-csv.yaml.in
  manifests/generated/rbac-operator.authorization.k8s.yaml.in
  pkg/controller/conditions.go
  pkg/virt-api/rest/subresource.go
  pkg/virt-api/rest/subresource_test.go
  pkg/virt-controller/services/template.go
  pkg/virt-controller/watch/vmi.go
  pkg/virt-controller/watch/vmi_test.go
  pkg/virt-operator/resource/generate/rbac/controller.go
  staging/src/kubevirt.io/api/core/v1/types.go
  tests/pausing_test.go
  tests/vm_test.go
  tests/vm_watch_test.go
Labels: size/L, release-note, kind/api-change, lgtm, approved, dco-signoff: yes

#6799 Add tests ID's
  tests/storage/restore.go
  tests/storage/snapshot.go
  tests/subresource_api_test.go
Labels: size/S, release-note-none, lgtm, approved, ok-to-test, dco-signoff: yes

#6876 Add functional tests ids for dry-run
  tests/dryrun_test.go
Labels: size/M, release-note-none, lgtm, approved, ok-to-test, dco-signoff: yes

#6837 [release-0.36] Backport prow release automation changes from 0.40
  automation/git-askpass.sh
  automation/release.sh
  hack/gen-swagger-doc/deploy.sh
  hack/publish-staging.sh
Labels: size/L, release-note, lgtm, approved, dco-signoff: yes

#6839 vm restore fixes + add snapshots and restore to kubevirt upgrade test
  pkg/virt-api/webhooks/validating-webhook/admitters/vmrestore-admitter.go
  pkg/virt-api/webhooks/validating-webhook/admitters/vmrestore-admitter_test.go
  pkg/virt-api/webhooks/validating-webhook/admitters/vms-admitter.go
  pkg/virt-api/webhooks/validating-webhook/admitters/vms-admitter_test.go
  pkg/virt-controller/watch/snapshot/restore.go
  tests/operator_test.go
  tests/storage/restore.go
Labels: size/L, release-note, lgtm, approved, dco-signoff: yes

#6784 Remove the kubevirt-config configMap
  cmd/virt-handler/virt-handler.go
  pkg/controller/virtinformers.go
  pkg/monitoring/profiler/BUILD.bazel
  pkg/monitoring/profiler/profile-manager_test.go
  pkg/testutils/mock_config.go
  pkg/virt-api/api.go
  pkg/virt-api/rest/profiler_test.go
  pkg/virt-api/rest/subresource_test.go
  pkg/virt-api/webhooks/mutating-webhook/mutators/vm-mutator_test.go
  pkg/virt-api/webhooks/mutating-webhook/mutators/vmi-mutator_test.go
  pkg/virt-api/webhooks/validating-webhook/admitters/migration-create-admitter_test.go
  pkg/virt-api/webhooks/validating-webhook/admitters/migration-update-admitter_test.go
  pkg/virt-api/webhooks/validating-webhook/admitters/pod-eviction-admitter_test.go
  pkg/virt-api/webhooks/validating-webhook/admitters/vmi-create-admitter_test.go
  pkg/virt-api/webhooks/validating-webhook/admitters/vmi-update-admitter_test.go
  pkg/virt-api/webhooks/validating-webhook/admitters/vmirs-admitter_test.go
  pkg/virt-api/webhooks/validating-webhook/admitters/vmrestore-admitter_test.go
  pkg/virt-api/webhooks/validating-webhook/admitters/vms-admitter_test.go
  pkg/virt-api/webhooks/validating-webhook/admitters/vmsnapshot-admitter_test.go
  pkg/virt-config/BUILD.bazel
  pkg/virt-config/config_test.go
  pkg/virt-config/configuration.go
  pkg/virt-controller/services/template_test.go
  pkg/virt-controller/watch/application.go
  pkg/virt-controller/watch/application_test.go
  pkg/virt-controller/watch/drain/evacuation/evacuation_test.go
  pkg/virt-controller/watch/migration_test.go
  pkg/virt-controller/watch/topology/hinter_test.go
  pkg/virt-controller/watch/vmi_test.go
  pkg/virt-controller/watch/workload-updater/workload-updater_test.go
  pkg/virt-handler/device-manager/device_controller_test.go
  pkg/virt-handler/device-manager/mediated_device_test.go
  pkg/virt-handler/device-manager/pci_device_test.go
  pkg/virt-handler/heartbeat/heartbeat_test.go
  pkg/virt-handler/migration-proxy/migration-proxy_test.go
  pkg/virt-handler/node-labeller/cpu_plugin_test.go
  pkg/virt-handler/node-labeller/node_labeller_test.go
  pkg/virt-handler/vm_test.go
  pkg/virt-operator/BUILD.bazel
  pkg/virt-operator/application.go
  pkg/virt-operator/kubevirt.go
  pkg/virt-operator/kubevirt_test.go
  tests/BUILD.bazel
  tests/kubevirt_configmap_test.go
  tests/tests_suite_test.go
  tests/utils.go
  tests/virtoperatorbasic/BUILD.bazel
  tests/virtoperatorbasic/virtoperator_basic.go
  tools/vms-generator/BUILD.bazel
  tools/vms-generator/vms-generator.go
Labels: release-note, size/XXL, lgtm, approved, dco-signoff: yes, area/monitoring
