Repository kubevirt/kubevirt, pull requests merged in 2021-01, with the labels that each got.

#4728 Fix server version: set --stamp as default build flag
  .bazelrc
  hack/bazel-build.sh
  hack/bazel-test.sh
  hack/build-func-tests.sh
  hack/coverage.sh
  tests/version_test.go
Labels: approved, dco-signoff: yes, lgtm, ok-to-test, release-note-none, size/S

#4739 MacvtapPodInterface.setCachedInterface: fix arg name
  pkg/virt-launcher/virtwrap/network/podinterface.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#4666 virt-launcher: Remove unused arg from GetDomainSpecWithRuntimeInfo
  pkg/virt-launcher/notify-client/client.go
  pkg/virt-launcher/virtwrap/manager.go
  pkg/virt-launcher/virtwrap/manager_test.go
  pkg/virt-launcher/virtwrap/util/libvirt_helper.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/S

#4662 Bump kubevirtci
  cluster-up-sha.txt
  cluster-up/cluster/k8s-1.20/README.md
  cluster-up/cluster/k8s-1.20/dev-guide.md
  cluster-up/cluster/k8s-1.20/provider.sh
  cluster-up/cluster/kind-k8s-sriov-1.17.0/certcreator/certsecret.go
  cluster-up/cluster/kind-k8s-sriov-1.17.0/config_sriov.sh
  cluster-up/hack/common.sh
  cluster-up/version.txt
  hack/config-default.sh
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XL

#4730 Support virtio-transitional for old guests
  api/openapi-spec/swagger.json
  pkg/testutils/BUILD.bazel
  pkg/testutils/domain.go
  pkg/virt-launcher/virtwrap/BUILD.bazel
  pkg/virt-launcher/virtwrap/access-credentials/BUILD.bazel
  pkg/virt-launcher/virtwrap/access-credentials/access_credentials_test.go
  pkg/virt-launcher/virtwrap/api/BUILD.bazel
  pkg/virt-launcher/virtwrap/api/deepcopy_generated.go
  pkg/virt-launcher/virtwrap/api/defaults.go
  pkg/virt-launcher/virtwrap/api/schema.go
  pkg/virt-launcher/virtwrap/converter/BUILD.bazel
  pkg/virt-launcher/virtwrap/converter/api_suite_test.go
  pkg/virt-launcher/virtwrap/converter/converter.go
  pkg/virt-launcher/virtwrap/converter/converter_test.go
  pkg/virt-launcher/virtwrap/converter/pci-placement.go
  pkg/virt-launcher/virtwrap/manager.go
  pkg/virt-launcher/virtwrap/manager_test.go
  pkg/virt-launcher/virtwrap/network/BUILD.bazel
  pkg/virt-launcher/virtwrap/network/common.go
  pkg/virt-launcher/virtwrap/network/podinterface.go
  pkg/virt-operator/creation/components/validations_generated.go
  staging/src/kubevirt.io/client-go/api/v1/deepcopy_generated.go
  staging/src/kubevirt.io/client-go/api/v1/openapi_generated.go
  staging/src/kubevirt.io/client-go/api/v1/schema.go
  staging/src/kubevirt.io/client-go/api/v1/schema_swagger_generated.go
  staging/src/kubevirt.io/client-go/apis/snapshot/v1alpha1/openapi_generated.go
  tests/BUILD.bazel
  tests/vmi_configuration_test.go
  tests/vmi_lifecycle_test.go
Labels: approved, dco-signoff: yes, kind/api-change, lgtm, release-note, size/XL

#4376 Don't override the e2e kubevirt config by default in the e2e tests
  hack/functests.sh
  tests/flags/flags.go
  tests/utils.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#4616 Make storage tests work in parallel
  hack/bazel-test.sh
  images/disks-images-provider/entrypoint.sh
  manifests/testing/disks-images-provider.yaml.in
  tests/BUILD.bazel
  tests/framework/cleanup/BUILD.bazel
  tests/framework/cleanup/cleanup.go
  tests/framework/matcher/BUILD.bazel
  tests/framework/matcher/existence.go
  tests/framework/matcher/existence_test.go
  tests/framework/matcher/getter.go
  tests/framework/matcher/matcher_suite_test.go
  tests/framework/matcher/phase.go
  tests/framework/matcher/phase_test.go
  tests/framework/storage/BUILD.bazel
  tests/framework/storage/nfs.go
  tests/migration_test.go
  tests/operator_test.go
  tests/storage_test.go
  tests/template_test.go
  tests/utils.go
  tests/windows_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XXL

#4670 Fix support for camelCase userData and networkData labels in secret-based cloud init volumes
  pkg/cloud-init/cloud-init.go
  pkg/virt-controller/services/template.go
  tests/vmi_cloudinit_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M

#4742 virt-launcher/handler- use VIF cache only for dhcp server
  pkg/virt-launcher/virtwrap/network/common.go
  pkg/virt-launcher/virtwrap/network/common_test.go
  pkg/virt-launcher/virtwrap/network/podinterface.go
  pkg/virt-launcher/virtwrap/network/podinterface_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/L

#4703 Merge kubevirt/libvirt into kubevirt/kubevirt
  BUILD.bazel
  Makefile
  WORKSPACE
  cmd/subresource-access-test/BUILD.bazel
  cmd/virt-api/BUILD.bazel
  cmd/virt-controller/BUILD.bazel
  cmd/virt-handler/BUILD.bazel
  cmd/virt-launcher/BUILD.bazel
  cmd/virt-launcher/libvirtd.conf
  cmd/virt-launcher/qemu.conf
  cmd/virt-operator/BUILD.bazel
  docs/updating-dependencies.md
  hack/rpm-deps.sh
  hack/verify-rpm-deps.sh
  images/README.md
  repo.yaml
  rpm/BUILD.bazel
  tests/vmi_multus_test.go
Labels: approved, dco-signoff: yes, kind/build-change, lgtm, release-note-none, size/XXL

#4759 Reviewers update: Adding EdDev as a code reviewer
  OWNERS_ALIASES
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#4663 Document new kubevirt handling of WaitForFirstConsumer DataVolumes
  docs/localstorage-disks.md
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M

#4763 [release-0.36] Support virtio-transitional for old guests
  api/openapi-spec/swagger.json
  pkg/testutils/BUILD.bazel
  pkg/testutils/domain.go
  pkg/virt-launcher/virtwrap/BUILD.bazel
  pkg/virt-launcher/virtwrap/access-credentials/BUILD.bazel
  pkg/virt-launcher/virtwrap/access-credentials/access_credentials_test.go
  pkg/virt-launcher/virtwrap/api/BUILD.bazel
  pkg/virt-launcher/virtwrap/api/deepcopy_generated.go
  pkg/virt-launcher/virtwrap/api/defaults.go
  pkg/virt-launcher/virtwrap/api/schema.go
  pkg/virt-launcher/virtwrap/converter/BUILD.bazel
  pkg/virt-launcher/virtwrap/converter/api_suite_test.go
  pkg/virt-launcher/virtwrap/converter/converter.go
  pkg/virt-launcher/virtwrap/converter/converter_test.go
  pkg/virt-launcher/virtwrap/converter/pci-placement.go
  pkg/virt-launcher/virtwrap/manager.go
  pkg/virt-launcher/virtwrap/manager_test.go
  pkg/virt-launcher/virtwrap/network/BUILD.bazel
  pkg/virt-launcher/virtwrap/network/common.go
  pkg/virt-launcher/virtwrap/network/podinterface.go
  pkg/virt-operator/creation/components/validations_generated.go
  staging/src/kubevirt.io/client-go/api/v1/deepcopy_generated.go
  staging/src/kubevirt.io/client-go/api/v1/openapi_generated.go
  staging/src/kubevirt.io/client-go/api/v1/schema.go
  staging/src/kubevirt.io/client-go/api/v1/schema_swagger_generated.go
  staging/src/kubevirt.io/client-go/apis/snapshot/v1alpha1/openapi_generated.go
  tests/BUILD.bazel
  tests/vmi_configuration_test.go
  tests/vmi_lifecycle_test.go
Labels: approved, dco-signoff: yes, kind/api-change, lgtm, release-note, size/XL

#4743 tests, xfail: Change XFail API to wrap the expected failure
  tests/assert/xfail.go
  tests/vmi_multus_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M

#4766 Bump bazeldnf to fix rpm verification
  WORKSPACE
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#4750 Drop references to kubevirt-host-device-plugin-config cfgMap
  pkg/virt-api/webhooks/validating-webhook/admitters/vmi-create-admitter.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#4751 gosec G601: Fix memory aliasing in for loop
  pkg/virt-api/webhooks/validating-webhook/admitters/vmi-create-admitter.go
  pkg/virt-api/webhooks/validating-webhook/admitters/vms-admitter.go
  pkg/virt-controller/watch/snapshot/snapshot.go
  pkg/virt-controller/watch/vm.go
  pkg/virt-controller/watch/vmi.go
  pkg/virt-launcher/virtwrap/access-credentials/access_credentials.go
  pkg/virt-launcher/virtwrap/cli/libvirt.go
  pkg/virt-launcher/virtwrap/converter/converter.go
  pkg/virt-launcher/virtwrap/network/network.go
  pkg/virt-launcher/virtwrap/network/podinterface.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M

#4774 add vi-minimal to base packages for containers
  WORKSPACE
  hack/rpm-deps.sh
  rpm/BUILD.bazel
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M

#4770 Fix PCI addr regexp
  pkg/util/BUILD.bazel
  pkg/util/hardware/hw_utils.go
  pkg/util/hardware/hw_utils_test.go
  pkg/util/hw_helper.go
  pkg/virt-api/webhooks/validating-webhook/admitters/BUILD.bazel
  pkg/virt-api/webhooks/validating-webhook/admitters/vmi-create-admitter.go
  pkg/virt-launcher/virtwrap/converter/BUILD.bazel
  pkg/virt-launcher/virtwrap/converter/converter.go
  tests/BUILD.bazel
  tests/vmi_gpu_test.go
Labels: approved, dco-signoff: yes, lgtm, ok-to-test, release-note-none, size/L

#4733 sriov, tests: xfail vlan test
  tests/vmi_multus_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/S

#4784 Update Quay credentials in travis config
  .travis.yml
Labels: dco-signoff: yes, lgtm, release-note-none, size/XS

#4785 Bump bazeldnf to better deal with bad repomd files
  .bazelrc
  .gitignore
  WORKSPACE
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#4755 Fix attachment pod permissions
  pkg/virt-controller/services/template.go
  pkg/virt-operator/creation/components/scc.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/S

#4761 Ensure block devices are allowed, when the volume has not been attached to VM
  pkg/virt-handler/hotplug-disk/mount.go
  tests/storage/hotplug.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M

#4445 fix: change url and label name for "good-first-issue" on CONTRIBUTING.md
  CONTRIBUTING.md
Labels: approved, dco-signoff: yes, lgtm, needs-ok-to-test, release-note-none, size/XS

#4773 tests: make client in hello world job UDP wait for response
  tests/expose_test.go
  tests/job.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M

#4791 Remove DockerHub-related travis jobs and credentials
  .travis.yml
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/S

#4780 Bump kubevirtci
  cluster-up-sha.txt
  cluster-up/cluster/ephemeral-provider-common.sh
  cluster-up/cluster/kind-k8s-sriov-1.17.0/config_sriov.sh
  cluster-up/hack/common.sh
  cluster-up/version.txt
  hack/config-default.sh
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/S

#4794 Fix some typo in docs
  docs/libvirt-pod-networking.md
  docs/release.md
Labels: approved, dco-signoff: yes, lgtm, ok-to-test, release-note-none, size/XS

#4798 Bump bazeldnf to a version with its own ldd implementation
  WORKSPACE
  rpm/BUILD.bazel
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/S

#4775 network: assorted minor cleanups and code removals
  pkg/virt-launcher/virtwrap/network/network.go
  pkg/virt-launcher/virtwrap/network/network_test.go
  pkg/virt-launcher/virtwrap/network/podinterface.go
  pkg/virt-launcher/virtwrap/network/podinterface_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M

#4772 virt-controller: increase the number of VMI controller threads
  pkg/virt-controller/watch/application.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/XS

#4749 ENV VAR for client-go scheme registration version
  staging/src/kubevirt.io/client-go/api/v1/register.go
Labels: approved, dco-signoff: yes, kind/api-change, lgtm, release-note, size/S

#4779 Add error message on virtctl image-upload to WaitForFirstConsumer Dat…
  docs/localstorage-disks.md
  pkg/virtctl/imageupload/imageupload.go
  pkg/virtctl/imageupload/imageupload_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/L

#4806 Make mutating webhooks required
  pkg/virt-operator/creation/components/BUILD.bazel
  pkg/virt-operator/creation/components/webhooks.go
  pkg/virt-operator/creation/components/webhooks_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/M

#4808 Remove travis-ci logic for pushing to quay app registry
  .travis.yml
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#4815 Fix typos in log output
  cluster-up/cluster/kind-k8s-sriov-1.17.0/certcreator/certsecret.go
Labels: approved, dco-signoff: yes, lgtm, ok-to-test, release-note-none, size/XS

#4816 bump bazeldnf
  WORKSPACE
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#4818 docs/devel/networking: unbreak URL
  docs/devel/networking.md
Labels: dco-signoff: yes, lgtm, release-note-none, size/XS

#4826 Revert "Fix typos in log output"
  cluster-up/cluster/kind-k8s-sriov-1.17.0/certcreator/certsecret.go
Labels: dco-signoff: yes, release-note-none, size/XS

#4824 [release-0.36] Add error message on virtctl image-upload to WaitForFirstConsumer DataVolume
  docs/localstorage-disks.md
  pkg/virtctl/imageupload/imageupload.go
  pkg/virtctl/imageupload/imageupload_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/L

#4804 virt-launcher: [masquerade] Stop filtering dhcp reuqests by vm MAC
  pkg/virt-launcher/virtwrap/network/common.go
  pkg/virt-launcher/virtwrap/network/dhcp/dhcp.go
  pkg/virt-launcher/virtwrap/network/generated_mock_common.go
  pkg/virt-launcher/virtwrap/network/podinterface.go
  pkg/virt-launcher/virtwrap/network/podinterface_test.go
  tests/vmi_networking_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M

#4817 Normalize DNS search domains to lower-case
  pkg/util/net/dns/resolveconf.go
  pkg/util/net/dns/resolveconf_test.go
Labels: approved, dco-signoff: yes, lgtm, ok-to-test, release-note-none, size/S

#4788 split sync resources into multiple functions and files
  pkg/virt-operator/install-strategy/BUILD.bazel
  pkg/virt-operator/install-strategy/admissionregistration.go
  pkg/virt-operator/install-strategy/apiservices.go
  pkg/virt-operator/install-strategy/apps.go
  pkg/virt-operator/install-strategy/certificates.go
  pkg/virt-operator/install-strategy/core.go
  pkg/virt-operator/install-strategy/crds.go
  pkg/virt-operator/install-strategy/create.go
  pkg/virt-operator/install-strategy/create_test.go
  pkg/virt-operator/install-strategy/patches.go
  pkg/virt-operator/install-strategy/prometheus.go
  pkg/virt-operator/install-strategy/rbac.go
  pkg/virt-operator/install-strategy/rbacbackup.go
  pkg/virt-operator/install-strategy/ssc.go
  pkg/virt-operator/install-strategy/strategy.go
  pkg/virt-operator/install-strategy/strategy_test.go
  pkg/virt-operator/install-strategy/update.go
  pkg/virt-operator/kubevirt.go
  vendor/modules.txt
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XXL

#4777 rename several network entities
  pkg/virt-launcher/virtwrap/BUILD.bazel
  pkg/virt-launcher/virtwrap/manager.go
  pkg/virt-launcher/virtwrap/manager_test.go
  pkg/virt-launcher/virtwrap/network/common.go
  pkg/virt-launcher/virtwrap/network/generated_mock_network.go
  pkg/virt-launcher/virtwrap/network/network.go
  pkg/virt-launcher/virtwrap/network/network_test.go
  pkg/virt-launcher/virtwrap/network/podinterface.go
  pkg/virt-launcher/virtwrap/network/podinterface_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/L

#4771 Additional hotplug functional tests
  tests/storage/hotplug.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/L

#4838 [virt-operator] load new certificates earlier and prepare for the 0.37.0 release
  hack/ci/entrypoint.sh
  hack/functests.sh
  pkg/certificates/bootstrap/BUILD.bazel
  pkg/certificates/bootstrap/cert-manager.go
  pkg/certificates/bootstrap/cert-manager_test.go
  pkg/virt-operator/application.go
  tests/README.md
  tests/flags/flags.go
  tests/operator_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/L

#4847 [release-0.36] virt-launcher: [masquerade] Stop filtering dhcp reuqests by vm MAC
  pkg/virt-launcher/virtwrap/network/common.go
  pkg/virt-launcher/virtwrap/network/dhcp/dhcp.go
  pkg/virt-launcher/virtwrap/network/generated_mock_common.go
  pkg/virt-launcher/virtwrap/network/podinterface.go
  pkg/virt-launcher/virtwrap/network/podinterface_test.go
  tests/vmi_networking_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M

#4853 Fix detection of previous release version in operator func test
  tests/utils.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#4672 Allow increasing log verbosity for KubeVirt components
  api/openapi-spec/swagger.json
  cmd/virt-handler/virt-handler.go
  cmd/virt-launcher/virt-launcher.go
  manifests/generated/kv-resource.yaml
  pkg/virt-api/api.go
  pkg/virt-config/config-map.go
  pkg/virt-config/config_test.go
  pkg/virt-config/virt-config.go
  pkg/virt-controller/services/template.go
  pkg/virt-controller/watch/application.go
  pkg/virt-operator/creation/components/validations_generated.go
  staging/src/kubevirt.io/client-go/api/v1/deepcopy_generated.go
  staging/src/kubevirt.io/client-go/api/v1/openapi_generated.go
  staging/src/kubevirt.io/client-go/api/v1/types.go
  staging/src/kubevirt.io/client-go/api/v1/types_swagger_generated.go
  staging/src/kubevirt.io/client-go/apis/snapshot/v1alpha1/openapi_generated.go
Labels: approved, dco-signoff: yes, kind/api-change, lgtm, release-note, size/L

#4738 virt-api/webhooks: simplify, rename and test ServiceAccount-matching function
  pkg/virt-api/webhooks/BUILD.bazel
  pkg/virt-api/webhooks/mutating-webhook/mutators/vmi-mutator.go
  pkg/virt-api/webhooks/utils.go
  pkg/virt-api/webhooks/utils_test.go
  pkg/virt-api/webhooks/validating-webhook/admitters/vmi-create-admitter.go
  pkg/virt-api/webhooks/validating-webhook/admitters/vmi-update-admitter.go
  pkg/virt-api/webhooks/validating-webhook/admitters/vms-admitter.go
  pkg/virt-api/webhooks/webhooks_suite_test.go
Labels: approved, dco-signoff: yes, kind/api-change, lgtm, release-note-none, size/L

#4863 removing trello reference as its no longer used
  README.md
Labels: approved, dco-signoff: yes, lgtm, ok-to-test, release-note-none, size/XS

#4862 Support (non-)transitional virtio-balloon
  WORKSPACE
  hack/rpm-deps.sh
  pkg/testutils/domain.go
  pkg/virt-launcher/virtwrap/converter/converter.go
  pkg/virt-launcher/virtwrap/converter/converter_test.go
  repo.yaml
  rpm/BUILD.bazel
  tests/vmidefaults_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/L

#4803 Refactor common code: virt-handler/isolation
  pkg/virt-handler/isolation/isolation.go
  pkg/virt-handler/isolation/isolation_test.go
Labels: approved, dco-signoff: yes, lgtm, ok-to-test, release-note-none, size/L

#4848 Clean error message for not migratable VMI
  pkg/virt-handler/vm.go
  pkg/virt-handler/vm_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#4857 Bump kubevirtci, now hosted on quay.io
  cluster-up-sha.txt
  cluster-up/cluster/ephemeral-provider-common.sh
  cluster-up/cluster/kind-k8s-sriov-1.17.0/OWNERS
  cluster-up/cluster/kind-k8s-sriov-1.17.0/config_sriov.sh
  cluster-up/hack/common.sh
  cluster-up/version.txt
  hack/config-default.sh
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M

#4810 test/utils: fix some issues
  tests/utils.go
Labels: approved, dco-signoff: yes, lgtm, ok-to-test, release-note-none, size/S

#4812 Fix ineffassign issues
  pkg/container-disk/container-disk_test.go
  pkg/virt-handler/device-manager/mediated_device_test.go
  pkg/virt-handler/hotplug-disk/mount_test.go
  pkg/virt-handler/vm_test.go
  pkg/virt-launcher/virtwrap/access-credentials/access_credentials.go
  pkg/virt-launcher/virtwrap/network/common.go
  tests/reporter/kubernetes.go
  tests/restore_test.go
  tests/vm_test.go
  tests/vm_watch_test.go
  tools/util/marshaller.go
Labels: approved, dco-signoff: yes, lgtm, ok-to-test, release-note-none, size/M

#4856 network: podinterface: a bit more variable name consistency
  pkg/virt-launcher/virtwrap/network/podinterface.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/L

#4845 Keepalive function for travis to prevent timeout due to inactivity on stdout
  automation/travisci-test.sh
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/S

#4801 guidelines for using gosec analysis tool
  docs/gosec.md
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M

#4850 Consider scsi controllers in virtio version decisions
  pkg/testutils/domain.go
  pkg/virt-launcher/virtwrap/converter/converter.go
  pkg/virt-launcher/virtwrap/converter/converter_test.go
  tests/vmi_controller_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/S

#4873 fix sonar issue for Define a constant instead of duplicating string
  pkg/controller/virtinformers.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/S

#4859 ipv4, network tests: refactor the masquerade test table
  tests/vmi_networking_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/S

#4889 Document the interface between host devices device plugins and KubeVirt
  docs/devel/host-devices-and-device-plugins.md
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M

#4823 Remove danielBelenky from reviewers
  OWNERS
  OWNERS_ALIASES
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#4792 Add alert for insufficient number of nodes with KVM resources
  hack/prom-rule-ci/prom-rules-tests.yaml
  pkg/virt-operator/creation/components/crds.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M

#4860 [virt-controller] Clean some of SonarCloud's code smell issues
  pkg/virt-controller/watch/migration.go
  pkg/virt-controller/watch/node.go
  pkg/virt-controller/watch/vm.go
  pkg/virt-controller/watch/vmi.go
Labels: approved, dco-signoff: yes, kind/api-change, lgtm, ok-to-test, release-note-none, size/L

#4844 Fix limits/requests to accept int again
  api/openapi-spec/swagger.json
  pkg/util/openapi/openapi.go
  pkg/virt-launcher/virtwrap/converter/converter.go
  pkg/virt-launcher/virtwrap/converter/converter_test.go
  tests/vm_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/M

#4898 Multus func tests remove leftovers
  tests/vmi_multus_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M

#4885 Mitigates a flaky test timing issue
  tests/subresource_api_test.go
Labels: approved, dco-signoff: yes, kind/api-change, lgtm, release-note-none, size/XS

#4884 Add NVIDIA as a KubeVirt ADOPTER
  ADOPTERS.md
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#4906 Bump bazeldnf to v0.0.15
  WORKSPACE
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#4923 multus, tests: assert error does not happen
  tests/vmi_multus_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/S

#4882 Add tar to launcher rpm deps
  WORKSPACE
  hack/rpm-deps.sh
  rpm/BUILD.bazel
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/L

#4659 Remove FSGroup from Pod spec to allow non-root guest usage of Virtio-FS
  pkg/host-disk/host-disk.go
  pkg/virt-controller/services/template.go
  tests/storage_test.go
  tests/vmi_lifecycle_test.go
Labels: approved, dco-signoff: yes, lgtm, ok-to-test, release-note, size/L

#4928 cloudinit.GenerateLocalData: minor refactoring
  pkg/cloud-init/cloud-init.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/S

#4905 Fix ineffassign issues
  pkg/virt-controller/watch/migration.go
  pkg/virt-handler/cache/cache_test.go
  pkg/virt-handler/cmd-client/client_test.go
  pkg/virt-handler/isolation/isolation_test.go
  pkg/virt-handler/migration-proxy/migration-proxy_test.go
  pkg/virt-launcher/virtwrap/access-credentials/access_credentials_test.go
  pkg/virt-launcher/virtwrap/manager_test.go
  pkg/virt-operator/creation/components/secrets_test.go
  tests/config_test.go
  tests/infra_test.go
  tests/replicaset_test.go
  tests/vmi_gpu_test.go
  tests/vmipreset_test.go
  tests/vnc_test.go
  tools/vms-generator/utils/utils.go
Labels: approved, dco-signoff: yes, lgtm, ok-to-test, release-note-none, size/M
