Repository kubevirt/kubevirt, pull requests merged in 2021-04, with the labels that each got.

#5350 device controller: remove all device plugins when permittedHostDevices is deleted
  pkg/virt-config/config-map.go
  pkg/virt-handler/device-manager/device_controller.go
  pkg/virt-handler/device-manager/device_controller_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/M

#5341 virt-launcher, network: Remove unused tapOwner* constants
  pkg/virt-launcher/virtwrap/network/common.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#5359 crds: do not log if crds are up-to-date
  pkg/virt-operator/resource/apply/crds.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#5216 Update KubeVirt to use apiregistration.k8s.io/v1
  pkg/controller/BUILD.bazel
  pkg/controller/virtinformers.go
  pkg/virt-operator/BUILD.bazel
  pkg/virt-operator/application.go
  pkg/virt-operator/kubevirt_test.go
  pkg/virt-operator/resource/apply/BUILD.bazel
  pkg/virt-operator/resource/apply/apiservices.go
  pkg/virt-operator/resource/apply/delete.go
  pkg/virt-operator/resource/apply/reconcile.go
  pkg/virt-operator/resource/generate/components/BUILD.bazel
  pkg/virt-operator/resource/generate/components/apiservices.go
  pkg/virt-operator/resource/generate/install/BUILD.bazel
  pkg/virt-operator/resource/generate/install/generated_mock_strategy.go
  pkg/virt-operator/resource/generate/install/strategy.go
  tests/infra_test.go
  tests/operator_test.go
  tests/reporter/BUILD.bazel
  tests/reporter/kubernetes.go
Labels: approved, dco-signoff: yes, lgtm, ok-to-test, release-note-none, size/M

#5111 move listVmWithLocalData out of diskutils
  pkg/cloud-init/BUILD.bazel
  pkg/cloud-init/cloud-init.go
  pkg/cloud-init/cloud-init_test.go
  pkg/ephemeral-disk-utils/BUILD.bazel
  pkg/ephemeral-disk-utils/utils.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M

#5387 build: Update make-deps-update results
  go.mod
  vendor/modules.txt
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#5356 Quarantine Hotplug test
  tests/storage/hotplug.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#5317 Fix flaky "[ref_id:1182]Probes for readiness should succeed [test_id:1202]with working HTTP probe and http server, no ip family is specified"
  tests/network/probes.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, sig/network, size/S

#5363 Specify consumes and body for add/removevolume in api docs
  api/openapi-spec/swagger.json
  pkg/virt-api/api.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M

#5331 pull out some duplicated code to improve readability
  pkg/virt-operator/resource/apply/apiservices.go
  pkg/virt-operator/resource/apply/apps.go
  pkg/virt-operator/resource/apply/crds.go
  pkg/virt-operator/resource/apply/crds_test.go
  pkg/virt-operator/resource/apply/prometheus.go
  pkg/virt-operator/resource/apply/reconcile.go
  pkg/virt-operator/resource/apply/reconcile_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/L

#5381 virt-launcher, agent-poller, Fix replaceTicker logic
  pkg/virt-launcher/virtwrap/agent-poller/agent_poller.go
  pkg/virt-launcher/virtwrap/agent-poller/agent_poller_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M

#5345 virtwrap: fix unit test flakyness (take 2)
  pkg/virt-launcher/virtwrap/manager.go
  pkg/virt-launcher/virtwrap/manager_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M

#5361 Return error if VMI is in Failed state when console access
  pkg/virt-api/rest/subresource.go
  pkg/virt-api/rest/subresource_test.go
Labels: approved, dco-signoff: yes, lgtm, ok-to-test, release-note-none, size/S

#5332 Bump Kubevirtci 2103261553-31913e9
  cluster-up-sha.txt
  cluster-up/cluster/kind-k8s-sriov-1.17.0/config_sriov.sh
  cluster-up/cluster/kind-k8s-sriov-1.17.0/configure_vfs.sh
  cluster-up/cluster/kind-k8s-sriov-1.17.0/sriov-components/manifests/kustomization.yaml
  cluster-up/cluster/kind-k8s-sriov-1.17.0/sriov-components/manifests/multus.yaml
  cluster-up/cluster/kind-k8s-sriov-1.17.0/sriov-components/manifests/patch-node-selector.yaml.in
  cluster-up/cluster/kind-k8s-sriov-1.17.0/sriov-components/manifests/patch-sriovdp-resource-prefix.yaml.in
  cluster-up/cluster/kind-k8s-sriov-1.17.0/sriov-components/manifests/sriov-cni-daemonset.yaml
  cluster-up/cluster/kind-k8s-sriov-1.17.0/sriov-components/manifests/sriov-ns.yaml
  cluster-up/cluster/kind-k8s-sriov-1.17.0/sriov-components/manifests/sriovdp-config.yaml.in
  cluster-up/cluster/kind-k8s-sriov-1.17.0/sriov-components/manifests/sriovdp-daemonset.yaml
  cluster-up/cluster/kind-k8s-sriov-1.17.0/sriov-components/sriov_components.sh
  cluster-up/cluster/kind-k8s-sriov-1.17.0/sriov_operator.sh
  cluster-up/hack/common.sh
  cluster-up/version.txt
  hack/config-default.sh
  tests/network/vmi_multus.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XXL

#5366 [release-0.34] migration admitter: prevent creation of duplicate migrations by adding a special migration label to be used as a label selector
  pkg/virt-api/api.go
  pkg/virt-api/webhooks/mutating-webhook/mutators/migration-create-mutator.go
  pkg/virt-api/webhooks/mutating-webhook/mutators/migration-create-mutator_test.go
  pkg/virt-api/webhooks/validating-webhook/admitters/migration-create-admitter.go
  pkg/virt-api/webhooks/validating-webhook/admitters/migration-create-admitter_test.go
  pkg/virt-api/webhooks/validating-webhook/admitters/migration-update-admitter.go
  pkg/virt-api/webhooks/validating-webhook/admitters/migration-update-admitter_test.go
  pkg/virt-api/webhooks/validating-webhook/validating-webhook.go
  pkg/virt-controller/watch/migration.go
  staging/src/kubevirt.io/client-go/api/v1/types.go
  tests/migration_test.go
Labels: approved, dco-signoff: yes, kind/api-change, lgtm, release-note, size/L

#5050 alert users if they have an orphaned vmi for more than an hour
  hack/prom-rule-ci/prom-rules-tests.yaml
  pkg/virt-operator/resource/generate/components/crds.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/M

#5224 Reconcile Role and ClusterRole resources
  pkg/virt-operator/resource/apply/BUILD.bazel
  pkg/virt-operator/resource/apply/core.go
  pkg/virt-operator/resource/apply/rbac.go
  pkg/virt-operator/resource/apply/rbacbackup.go
  pkg/virt-operator/resource/apply/reconcile.go
Labels: approved, dco-signoff: yes, kind/api-change, lgtm, release-note-none, size/XL

#5329 update automation test script for new rook/ceph
  automation/test.sh
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#5354 tests, Move VMI lifecycle networking tests to network folder
  tests/network/BUILD.bazel
  tests/network/vmi_lifecycle.go
  tests/vmi_lifecycle_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, sig/network, size/L

#5408 [release-0.34]support extracting metadata for transients domains
  pkg/virt-launcher/notify-client/client.go
  pkg/virt-launcher/notify-client/notify_test.go
  pkg/virt-launcher/virtwrap/cli/generated_mock_libvirt.go
  pkg/virt-launcher/virtwrap/cli/libvirt.go
  pkg/virt-launcher/virtwrap/manager.go
  pkg/virt-launcher/virtwrap/manager_test.go
  pkg/virt-launcher/virtwrap/util/BUILD.bazel
  pkg/virt-launcher/virtwrap/util/libvirt_helper.go
  pkg/virt-launcher/virtwrap/util/libvirt_helper_test.go
  tests/migration_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/L

#5347 docs: add documentation for discard passthrough
  docs/discard-passthrough.md
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M

#5351 Support hotplug with virtctl
  docs/hotplug.md
  pkg/virtctl/root.go
  pkg/virtctl/vm/BUILD.bazel
  pkg/virtctl/vm/vm.go
  pkg/virtctl/vm/vm_test.go
  tests/storage/BUILD.bazel
  tests/storage/hotplug.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/XL

#5389 Fix SRIOV IPv6 pings tests, ping destinations
  tests/network/vmi_multus.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, sig/network, size/S

#5400 virt-launcher: Don't update domain on SyncVMI retries
  pkg/virt-launcher/virtwrap/manager.go
  pkg/virt-launcher/virtwrap/manager_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/S

#5407 Add tests to quarantine
  tests/storage/hotplug.go
  tests/vmi_configuration_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#5020 explicitly skip cd-rom drives during migration
  pkg/virt-launcher/virtwrap/manager.go
  tests/migration_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/S

#5116 pkg, cleanup: Rename (to _) unused parameters
  pkg/config/config_test.go
  pkg/controller/controller_ref_manager_test.go
  pkg/monitoring/vms/prometheus/prometheus.go
  pkg/virt-api/rest/definitions.go
  pkg/virt-config/config-map.go
  pkg/virt-controller/services/template.go
  pkg/virt-controller/watch/drain/disruptionbudget/disruptionbudget.go
  pkg/virt-controller/watch/drain/evacuation/evacuation.go
  pkg/virt-controller/watch/migration.go
  pkg/virt-controller/watch/node.go
  pkg/virt-controller/watch/replicaset.go
  pkg/virt-controller/watch/vm.go
  pkg/virt-controller/watch/vmi.go
  pkg/virt-controller/watch/workload-updater/workload-updater.go
  pkg/virt-handler/cache/cache.go
  pkg/virt-handler/device-manager/device_controller_test.go
  pkg/virt-handler/device-manager/generic_device.go
  pkg/virt-handler/device-manager/mediated_device.go
  pkg/virt-handler/device-manager/pci_device.go
  pkg/virt-handler/hotplug-disk/mount_test.go
  pkg/virt-handler/notify-server/server.go
  pkg/virt-handler/vm.go
  pkg/virt-launcher/virtwrap/cmd-server/server.go
  pkg/virt-launcher/virtwrap/network/dhcp/dhcp.go
  pkg/virt-launcher/virtwrap/network/podinterface.go
  pkg/virt-operator/kubevirt.go
  pkg/virt-operator/resource/apply/reconcile_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/L

#5391 network tests: test MTU on the secondary interface with no dhcp server
  tests/network/vmi_multus.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M

#5147 Update libvirt & drop NET_ADMIN
  WORKSPACE
  go.mod
  go.sum
  hack/rpm-deps.sh
  pkg/virt-controller/services/template.go
  pkg/virt-controller/services/template_test.go
  pkg/virt-launcher/virtwrap/network/podinterface_test.go
  pkg/virt-operator/resource/generate/components/scc.go
  repo.yaml
  rpm/BUILD.bazel
  tests/security_features_test.go
  tests/utils.go
  vendor/libvirt.org/libvirt-go/FAQ.md
  vendor/libvirt.org/libvirt-go/README.rst
  vendor/libvirt.org/libvirt-go/connect.go
  vendor/modules.txt
Labels: approved, dco-signoff: yes, lgtm, release-note, sig/network, size/XXL

#5368 Fix when case when node-labeller doesn't have access to kvm
  cmd/virt-handler/BUILD.bazel
  cmd/virt-handler/virt-handler.go
  pkg/virt-handler/node-labeller/BUILD.bazel
  pkg/virt-handler/node-labeller/cpu_plugin.go
  pkg/virt-handler/node-labeller/kvm-caps-info-plugin.go
  pkg/virt-handler/node-labeller/node_labeller.go
  pkg/virt-handler/node-labeller/node_labeller_test.go
  pkg/virt-handler/node-labeller/util/util.go
Labels: approved, dco-signoff: yes, kind/build-change, lgtm, release-blocker/release-0.40, release-note-none, size/L

#5397 virt-chroot, tap: Retry the creation of the tap device
  cmd/virt-chroot/tap-device-maker.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, sig/network, size/M

#5412 tests: On ExecuteCommandOnPod failure print both err and stderr is exist
  tests/utils.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#5432 Fix docker io pull limits
  hack/dockerized
  hack/prom-rule-ci/verify-rules.sh
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#5144 Reconcile PDBs on generation field
  pkg/virt-operator/BUILD.bazel
  pkg/virt-operator/kubevirt_test.go
  pkg/virt-operator/resource/apply/BUILD.bazel
  pkg/virt-operator/resource/apply/admissionregistration.go
  pkg/virt-operator/resource/apply/apps.go
  pkg/virt-operator/resource/apply/apps_test.go
  pkg/virt-operator/resource/apply/generations.go
  pkg/virt-operator/resource/apply/pdb_test.go
  tests/BUILD.bazel
  tests/operator_test.go
Labels: approved, dco-signoff: yes, kind/api-change, lgtm, release-note-none, size/L

#5415 [release-0.40] Revert changes on metrics that split some existing metrics
  docs/metrics.md
  pkg/monitoring/vms/prometheus/fakeCollector.go
  pkg/monitoring/vms/prometheus/prometheus.go
  pkg/monitoring/vms/prometheus/prometheus_test.go
  pkg/virt-launcher/virtwrap/cli/BUILD.bazel
  pkg/virt-launcher/virtwrap/cli/libvirt.go
  pkg/virt-launcher/virtwrap/stats/types.go
  pkg/virt-launcher/virtwrap/statsconv/converter.go
  pkg/virt-launcher/virtwrap/statsconv/converter_test.go
  pkg/virt-launcher/virtwrap/statsconv/util/domstats_utils.go
  tests/infra_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XL

#5419 Create monitoring-guidelines.md
  docs/monitoring-guidelines.md
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M

#5422 Fix hotplug pvc converter
  pkg/virt-launcher/virtwrap/converter/converter.go
  pkg/virt-launcher/virtwrap/converter/converter_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M

#5057 network, macvtap bind mech: add a MAC parameter to the bind mech
  pkg/virt-launcher/virtwrap/network/podinterface.go
  pkg/virt-launcher/virtwrap/network/podinterface_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, sig/network, size/M

#5369 Fix flaky block storage device tests
  tests/utils.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#5398 Remove test_id:3243 from quarantine.
  tests/migration_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#3383 schema: Introduce an IPv6 CIDR for the vm network
  api/openapi-spec/swagger.json
  pkg/virt-launcher/virtwrap/network/podinterface.go
  pkg/virt-operator/resource/generate/components/validations_generated.go
  staging/src/kubevirt.io/client-go/api/v1/openapi_generated.go
  staging/src/kubevirt.io/client-go/api/v1/schema.go
  staging/src/kubevirt.io/client-go/api/v1/schema_swagger_generated.go
  staging/src/kubevirt.io/client-go/apis/snapshot/v1alpha1/openapi_generated.go
  tests/network/vmi_networking.go
Labels: approved, dco-signoff: yes, kind/api-change, lgtm, release-note, sig/network, size/M

#5384 Paused VMIs should remain paused after migration
  pkg/virt-launcher/virtwrap/manager.go
  pkg/virt-launcher/virtwrap/manager_test.go
  tests/migration_test.go
  tests/utils.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/L

#5427 remove test_id:3194 and test_id:3193 from quarantine
  tests/storage/datavolume.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#5441 rpm: Update rpm-deps
  WORKSPACE
  rpm/BUILD.bazel
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M

#5429 remove need for type casting by using runtime.Object
  pkg/virt-operator/kubevirt_test.go
  pkg/virt-operator/resource/generate/install/BUILD.bazel
  pkg/virt-operator/resource/generate/install/strategy.go
  pkg/virt-operator/resource/generate/rbac/BUILD.bazel
  pkg/virt-operator/resource/generate/rbac/apiserver.go
  pkg/virt-operator/resource/generate/rbac/cluster.go
  pkg/virt-operator/resource/generate/rbac/controller.go
  pkg/virt-operator/resource/generate/rbac/handler.go
  pkg/virt-operator/resource/generate/rbac/servicemonitor.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M

#3310 kubernetes version compatibility commitment doc
  docs/kubernetes-compatibility.md
Labels: approved, dco-signoff: yes, lgtm, release-note, size/M

#5349 Fix stop of VM
  pkg/virt-controller/watch/vm.go
  tests/storage/datavolume.go
  tests/utils.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M

#5430 sig-network, Fix flaky test which pings 8.8.8.8
  tests/libnet/ping.go
  tests/network/vmi_networking.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/S

#5433 Request to be added into Kubevirt code-reviewers
  OWNERS_ALIASES
Labels: approved, dco-signoff: yes, lgtm, needs-ok-to-test, release-note-none, size/XS

#5452 network: remove the unused attr from the startDHCP bind mech method
  pkg/virt-launcher/virtwrap/network/generated_mock_podinterface.go
  pkg/virt-launcher/virtwrap/network/podinterface.go
  pkg/virt-launcher/virtwrap/network/podinterface_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, sig/network, size/M

#5346 Fix verbosity for virt-controller
  pkg/virt-controller/watch/application.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#5056 Bind mech receiver name consistency
  pkg/virt-launcher/virtwrap/network/podinterface.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M

#5456 cross-build for ARM64 on x86
  .bazelrc
  Makefile
  WORKSPACE
  bazel/BUILD
  bazel/platforms/BUILD
  bazel/toolchain/BUILD
  bazel/toolchain/aarch64-none-linux-gnu/BUILD
  bazel/toolchain/aarch64-none-linux-gnu/cc_toolchain_config.bzl
  bazel/toolchain/aarch64-none-linux-gnu/wrappers/aarch64-none-linux-gnu-ar
  bazel/toolchain/aarch64-none-linux-gnu/wrappers/aarch64-none-linux-gnu-cpp
  bazel/toolchain/aarch64-none-linux-gnu/wrappers/aarch64-none-linux-gnu-gcc
  bazel/toolchain/aarch64-none-linux-gnu/wrappers/aarch64-none-linux-gnu-gcov
  bazel/toolchain/aarch64-none-linux-gnu/wrappers/aarch64-none-linux-gnu-ld
  bazel/toolchain/aarch64-none-linux-gnu/wrappers/aarch64-none-linux-gnu-nm
  bazel/toolchain/aarch64-none-linux-gnu/wrappers/aarch64-none-linux-gnu-objdump
  bazel/toolchain/aarch64-none-linux-gnu/wrappers/aarch64-none-linux-gnu-strip
  bazel/toolchain/aarch64-none-linux-gnu/wrappers/wrapper
  bazel/toolchain/toolchain.bzl
  hack/bazel-build.sh
  hack/bazel-fmt.sh
  hack/build-manifests.sh
  hack/common.sh
  hack/rpm-deps.sh
  rpm/BUILD.bazel
  third_party/BUILD
  third_party/deps.bzl
  third_party/toolchains/BUILD
  third_party/toolchains/aarch64-none-linux-gnu.BUILD
  third_party/toolchains/toolchains.bzl
Labels: approved, dco-signoff: yes, lgtm, release-note, size/L

#5463 crds: fix patch formatting
  pkg/virt-operator/resource/apply/crds.go
Labels: approved, dco-signoff: yes, lgtm, release-blocker/release-0.40, release-note, size/XS

#5467 [release-0.40] crds: fix patch formatting
  pkg/virt-operator/resource/apply/crds.go
Labels: approved, dco-signoff: yes, kind/build-change, lgtm, release-note, size/XS

#5226 Add Quarantine doc
  docs/quarantine.md
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/L

#5330 Refactor launcher live migration code
  pkg/virt-handler/migration-proxy/migration-proxy.go
  pkg/virt-handler/migration-proxy/migration-proxy_test.go
  pkg/virt-launcher/virtwrap/BUILD.bazel
  pkg/virt-launcher/virtwrap/live-migration-source.go
  pkg/virt-launcher/virtwrap/live-migration-target.go
  pkg/virt-launcher/virtwrap/manager.go
  pkg/virt-launcher/virtwrap/manager_test.go
  pkg/virt-launcher/virtwrap/postcopy.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XXL

#5241 Change Certificate API to use Duration and RenewBefore
  api/openapi-spec/swagger.json
  manifests/generated/kv-resource.yaml
  pkg/virt-operator/resource/apply/BUILD.bazel
  pkg/virt-operator/resource/apply/certificates.go
  pkg/virt-operator/resource/apply/certificates_test.go
  pkg/virt-operator/resource/apply/core.go
  pkg/virt-operator/resource/generate/components/secrets.go
  pkg/virt-operator/resource/generate/components/secrets_test.go
  pkg/virt-operator/resource/generate/components/validations_generated.go
  pkg/virt-operator/webhooks/BUILD.bazel
  pkg/virt-operator/webhooks/kubevirt-update-admitter.go
  staging/src/kubevirt.io/client-go/api/v1/deepcopy_generated.go
  staging/src/kubevirt.io/client-go/api/v1/openapi_generated.go
  staging/src/kubevirt.io/client-go/api/v1/types.go
  staging/src/kubevirt.io/client-go/api/v1/types_swagger_generated.go
  staging/src/kubevirt.io/client-go/apis/snapshot/v1alpha1/openapi_generated.go
  tests/operator_test.go
  tests/utils.go
Labels: approved, dco-signoff: yes, kind/api-change, lgtm, release-note, size/XL

#5464 Skip GPU tests from compute lane
  automation/test.sh
  tests/access_test.go
  tests/config_test.go
  tests/console_test.go
  tests/credentials_test.go
  tests/infra_test.go
  tests/kubectl_test.go
  tests/kubevirt_configmap_test.go
  tests/migration_test.go
  tests/operator_test.go
  tests/pausing_test.go
  tests/replicaset_test.go
  tests/security_features_test.go
  tests/subresource_api_test.go
  tests/version_test.go
  tests/virt_control_plane_test.go
  tests/vm_test.go
  tests/vm_watch_test.go
  tests/vmi_cloudinit_hook_sidecar_test.go
  tests/vmi_cloudinit_test.go
  tests/vmi_configuration_test.go
  tests/vmi_controller_test.go
  tests/vmi_gpu_test.go
  tests/vmi_headless_test.go
  tests/vmi_hook_sidecar_test.go
  tests/vmi_hostdev_test.go
  tests/vmi_ignition_test.go
  tests/vmi_lifecycle_test.go
  tests/vmi_monitoring_test.go
  tests/vmi_multiqueue_test.go
  tests/vmidefaults_test.go
  tests/vmipreset_test.go
  tests/vnc_test.go
  tests/windows_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M

#5403 Prepend kubevirt_ to recording rules and metrics
  docs/metrics.md
  hack/prom-rule-ci/prom-rules-tests.yaml
  pkg/virt-controller/watch/application.go
  pkg/virt-operator/application.go
  pkg/virt-operator/resource/generate/components/crds.go
  tests/infra_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/M

#5480 [release-0.36] Fix VM restart during eviction when EvictionStrategy=LiveMigrate
  cmd/virt-launcher/virt-launcher.go
  pkg/controller/controller.go
  pkg/handler-launcher-com/cmd/v1/cmd.pb.go
  pkg/handler-launcher-com/cmd/v1/cmd.proto
  pkg/util/migrations/migrations.go
  pkg/virt-controller/services/template.go
  pkg/virt-controller/services/template_test.go
  pkg/virt-controller/watch/application.go
  pkg/virt-controller/watch/application_test.go
  pkg/virt-controller/watch/drain/evacuation/evacuation.go
  pkg/virt-controller/watch/drain/evacuation/evacuation_test.go
  pkg/virt-controller/watch/migration.go
  pkg/virt-controller/watch/migration_test.go
  pkg/virt-handler/cmd-client/client.go
  pkg/virt-handler/cmd-client/generated_mock_client.go
  pkg/virt-handler/vm.go
  pkg/virt-handler/vm_test.go
  pkg/virt-launcher/virtwrap/cmd-server/server.go
  pkg/virt-launcher/virtwrap/manager.go
  staging/src/kubevirt.io/client-go/api/v1/types.go
  tests/migration_test.go
Labels: approved, dco-signoff: yes, kind/api-change, lgtm, release-note, size/XL

#5426 Add missing iptables link in virt-handler
  rpm/BUILD.bazel
Labels: approved, dco-signoff: yes, kind/build-change, lgtm, release-note, size/XS

#5340 add new checks for hyperv evmcs
  pkg/virt-api/webhooks/BUILD.bazel
  pkg/virt-api/webhooks/hyperv.go
  pkg/virt-api/webhooks/mutating-webhook/mutators/BUILD.bazel
  pkg/virt-api/webhooks/mutating-webhook/mutators/vmi-mutator_test.go
  pkg/virt-api/webhooks/validating-webhook/admitters/BUILD.bazel
  pkg/virt-api/webhooks/validating-webhook/admitters/vmi-create-admitter_test.go
  pkg/virt-controller/services/template.go
  pkg/virt-controller/services/template_test.go
  pkg/virt-handler/node-labeller/cpu_plugin.go
  pkg/virt-handler/node-labeller/model.go
  pkg/virt-handler/node-labeller/node_labeller.go
  pkg/virt-handler/node-labeller/util/util.go
  staging/src/kubevirt.io/client-go/api/v1/types.go
  tests/infra_test.go
  tests/vmi_lifecycle_test.go
Labels: approved, dco-signoff: yes, kind/api-change, lgtm, release-note, size/L

#5399 Allow console connection to paused VM
  pkg/virt-api/rest/subresource.go
  pkg/virt-api/rest/subresource_test.go
  pkg/virtctl/console/console.go
  pkg/virtctl/templates/BUILD.bazel
  pkg/virtctl/templates/templates.go
  pkg/virtctl/vnc/vnc.go
  tests/pausing_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M

#5485 Add iptables symlink for arm64 base container
  rpm/BUILD.bazel
Labels: approved, dco-signoff: yes, lgtm, release-note, size/XS

#4682 Fix Guest Agent version compatibility check
  api/openapi-spec/swagger.json
  manifests/generated/kv-resource.yaml
  pkg/virt-config/virt-config.go
  pkg/virt-handler/vm.go
  pkg/virt-handler/vm_test.go
  pkg/virt-launcher/virtwrap/agent-poller/BUILD.bazel
  pkg/virt-launcher/virtwrap/agent-poller/agent_parser.go
  pkg/virt-launcher/virtwrap/agent-poller/agent_parser_test.go
  pkg/virt-launcher/virtwrap/agent-poller/agent_poller.go
  pkg/virt-launcher/virtwrap/agent-poller/agent_poller_test.go
  pkg/virt-launcher/virtwrap/manager.go
  pkg/virt-operator/resource/generate/components/validations_generated.go
  staging/src/kubevirt.io/client-go/api/v1/deepcopy_generated.go
  staging/src/kubevirt.io/client-go/api/v1/openapi_generated.go
  staging/src/kubevirt.io/client-go/api/v1/types.go
  staging/src/kubevirt.io/client-go/api/v1/types_swagger_generated.go
  staging/src/kubevirt.io/client-go/apis/snapshot/v1alpha1/openapi_generated.go
  tests/credentials_test.go
  tests/utils.go
  tests/vmi_configuration_test.go
Labels: approved, dco-signoff: yes, kind/api-change, lgtm, release-note, size/XL

#5482 [release-0.34] Fix VM restart during eviction when EvictionStrategy=LiveMigrate
  cmd/virt-launcher/virt-launcher.go
  pkg/controller/controller.go
  pkg/handler-launcher-com/cmd/v1/cmd.pb.go
  pkg/handler-launcher-com/cmd/v1/cmd.proto
  pkg/util/migrations/migrations.go
  pkg/virt-controller/services/template.go
  pkg/virt-controller/services/template_test.go
  pkg/virt-controller/watch/application.go
  pkg/virt-controller/watch/drain/evacuation/evacuation.go
  pkg/virt-controller/watch/drain/evacuation/evacuation_test.go
  pkg/virt-controller/watch/migration.go
  pkg/virt-controller/watch/migration_test.go
  pkg/virt-handler/cmd-client/client.go
  pkg/virt-handler/cmd-client/generated_mock_client.go
  pkg/virt-handler/vm.go
  pkg/virt-handler/vm_test.go
  pkg/virt-launcher/virtwrap/cmd-server/server.go
  pkg/virt-launcher/virtwrap/manager.go
  staging/src/kubevirt.io/client-go/api/v1/types.go
  tests/migration_test.go
Labels: approved, dco-signoff: yes, kind/api-change, lgtm, release-note, size/XL

#5343 Split storage metrics as read and write
  docs/metrics.md
  pkg/monitoring/vms/prometheus/prometheus.go
  pkg/monitoring/vms/prometheus/prometheus_test.go
  pkg/virt-launcher/virtwrap/cli/libvirt.go
  pkg/virt-launcher/virtwrap/stats/types.go
  pkg/virt-launcher/virtwrap/statsconv/converter.go
  pkg/virt-launcher/virtwrap/statsconv/util/domstats_utils.go
  tests/infra_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/L

#5392 Generate an Event, and a Prometheus based Alert for non evictable VMs
  hack/prom-rule-ci/prom-rules-tests.yaml
  pkg/monitoring/vms/prometheus/BUILD.bazel
  pkg/monitoring/vms/prometheus/prometheus.go
  pkg/monitoring/vms/prometheus/prometheus_test.go
  pkg/virt-handler/vm.go
  pkg/virt-operator/resource/generate/components/crds.go
  tests/infra_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/L

#5484 Fix verbosity for virt-api
  pkg/virt-api/api.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#5442 Add vm snapshot indications
  api/openapi-spec/swagger.json
  pkg/virt-controller/watch/snapshot/snapshot.go
  pkg/virt-controller/watch/snapshot/snapshot_test.go
  pkg/virt-operator/resource/generate/components/validations_generated.go
  staging/src/kubevirt.io/client-go/apis/snapshot/v1alpha1/deepcopy_generated.go
  staging/src/kubevirt.io/client-go/apis/snapshot/v1alpha1/openapi_generated.go
  staging/src/kubevirt.io/client-go/apis/snapshot/v1alpha1/types.go
  staging/src/kubevirt.io/client-go/apis/snapshot/v1alpha1/types_swagger_generated.go
  tests/storage/snapshot.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/L

#5445 Fix offline hotplug test failing
  pkg/virt-api/rest/subresource.go
  tests/storage/hotplug.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/L

#5488 Delete previous folder, ignore error if not exists
  automation/release.sh
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#5493 [release-0.36] Fix Guest Agent version compatibility check
  api/openapi-spec/swagger.json
  pkg/virt-handler/vm.go
  pkg/virt-handler/vm_test.go
  pkg/virt-launcher/virtwrap/agent-poller/BUILD.bazel
  pkg/virt-launcher/virtwrap/agent-poller/agent_parser.go
  pkg/virt-launcher/virtwrap/agent-poller/agent_parser_test.go
  pkg/virt-launcher/virtwrap/agent-poller/agent_poller.go
  pkg/virt-launcher/virtwrap/agent-poller/agent_poller_test.go
  pkg/virt-launcher/virtwrap/manager.go
  staging/src/kubevirt.io/client-go/api/v1/deepcopy_generated.go
  staging/src/kubevirt.io/client-go/api/v1/openapi_generated.go
  staging/src/kubevirt.io/client-go/api/v1/types.go
  staging/src/kubevirt.io/client-go/api/v1/types_swagger_generated.go
  staging/src/kubevirt.io/client-go/apis/snapshot/v1alpha1/openapi_generated.go
  tests/credentials_test.go
  tests/utils.go
  tests/vmi_configuration_test.go
Labels: approved, dco-signoff: yes, kind/api-change, lgtm, release-note, size/XL

#5380 Update our README.md to point to kubevirt-dev slack
  README.md
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#5059 Consolidate bind mechanism api
  pkg/virt-launcher/virtwrap/network/generated_mock_podinterface.go
  pkg/virt-launcher/virtwrap/network/podinterface.go
  pkg/virt-launcher/virtwrap/network/podinterface_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, sig/network, size/L

#5423 set resource requests
  manifests/generated/operator-csv.yaml.in
  pkg/virt-operator/resource/generate/components/BUILD.bazel
  pkg/virt-operator/resource/generate/components/daemonsets.go
  pkg/virt-operator/resource/generate/components/deployments.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/L

#5425 Fix VM restart during eviction when EvictionStrategy=LiveMigrate
  cmd/virt-launcher/virt-launcher.go
  pkg/controller/controller.go
  pkg/handler-launcher-com/cmd/v1/cmd.pb.go
  pkg/handler-launcher-com/cmd/v1/cmd.proto
  pkg/util/migrations/migrations.go
  pkg/virt-controller/services/template.go
  pkg/virt-controller/services/template_test.go
  pkg/virt-controller/watch/application.go
  pkg/virt-controller/watch/application_test.go
  pkg/virt-controller/watch/drain/evacuation/evacuation.go
  pkg/virt-controller/watch/drain/evacuation/evacuation_test.go
  pkg/virt-controller/watch/migration.go
  pkg/virt-controller/watch/migration_test.go
  pkg/virt-handler/cmd-client/client.go
  pkg/virt-handler/cmd-client/generated_mock_client.go
  pkg/virt-handler/vm.go
  pkg/virt-handler/vm_test.go
  pkg/virt-launcher/virtwrap/cmd-server/server.go
  pkg/virt-launcher/virtwrap/live-migration-source.go
  pkg/virt-launcher/virtwrap/live-migration-target.go
  staging/src/kubevirt.io/client-go/api/v1/types.go
  tests/migration_test.go
Labels: approved, dco-signoff: yes, kind/api-change, lgtm, release-note, size/XL

#5453 network, bridge binding: read the pod interface just once
  pkg/virt-launcher/virtwrap/network/podinterface.go
  pkg/virt-launcher/virtwrap/network/podinterface_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, sig/network, size/XS

#5472 Add dedicated functions for virt-chroot execution
  pkg/virt-handler/container-disk/BUILD.bazel
  pkg/virt-handler/container-disk/mount.go
  pkg/virt-handler/hotplug-disk/BUILD.bazel
  pkg/virt-handler/hotplug-disk/mount.go
  pkg/virt-handler/isolation/BUILD.bazel
  pkg/virt-handler/isolation/validation.go
  pkg/virt-handler/selinux/BUILD.bazel
  pkg/virt-handler/selinux/labels.go
  pkg/virt-handler/virt-chroot/BUILD.bazel
  pkg/virt-handler/virt-chroot/virt-chroot.go
  tests/reporter/BUILD.bazel
  tests/reporter/kubernetes.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/L

#5435 Support dual stack service on "virtctl expose"
  pkg/virtctl/expose/expose.go
  pkg/virtctl/expose/expose_test.go
  tests/assert/xfail.go
  tests/network/expose.go
Labels: approved, dco-signoff: yes, lgtm, release-note, sig/network, size/XL

#5494 [release-0.36] explicitly skip cd-rom drives during migration
  pkg/virt-launcher/virtwrap/manager.go
  tests/migration_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/S

#5307 Refactor func hostdisk.Create
  pkg/host-disk/host-disk.go
Labels: approved, dco-signoff: yes, lgtm, ok-to-test, release-note-none, size/L

#5512 network, handler: Use receiver at handler funcs
  pkg/virt-launcher/virtwrap/network/common.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/S

#5376 Reconcile crd
  pkg/virt-operator/kubevirt_test.go
  pkg/virt-operator/resource/apply/crds.go
  pkg/virt-operator/resource/apply/generations.go
  tests/operator_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/L

#5417 Use tap constants
  pkg/virt-launcher/virtwrap/network/common.go
  pkg/virt-launcher/virtwrap/network/podinterface.go
  pkg/virt-launcher/virtwrap/network/podinterface_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, sig/network, size/S

#5476 network, bind mech: remove vmi attr from ensureDHCP
  pkg/virt-launcher/virtwrap/network/podinterface.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, sig/network, size/XS

#5496 Improve migration proxy logging
  pkg/virt-handler/migration-proxy/migration-proxy.go
  pkg/virt-handler/migration-proxy/migration-proxy_test.go
  pkg/virt-handler/vm.go
  pkg/virt-launcher/virtwrap/live-migration-source.go
  pkg/virt-launcher/virtwrap/live-migration-target.go
  staging/src/kubevirt.io/client-go/log/log.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/L

#5498 network, slirp: remove unused attributes from bind mech
  pkg/virt-launcher/virtwrap/network/podinterface.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, sig/network, size/XS

#5505 tests, network, sriov: Post migration, learn interface name
  tests/network/vmi_multus.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/S

#5486 Bump kubevirtci 2104200713-f58c002
  automation/test.sh
  cluster-up-sha.txt
  cluster-up/cluster/kind-k8s-sriov-1.17.0/README.md
  cluster-up/cluster/kind-k8s-sriov-1.17.0/config_sriov.sh
  cluster-up/cluster/kind-k8s-sriov-1.17.0/config_sriov_cluster.sh
  cluster-up/cluster/kind-k8s-sriov-1.17.0/provider.sh
  cluster-up/cluster/kind-k8s-sriov-1.17.0/sriov-node/configure_vfs.sh
  cluster-up/cluster/kind-k8s-sriov-1.17.0/sriov-node/node.sh
  cluster-up/cluster/kind/manifests/product-uuid-podpreset.yaml
  cluster-up/cluster/kind/podpreset.sh
  cluster-up/hack/common.sh
  cluster-up/version.txt
  hack/config-default.sh
Labels: approved, dco-signoff: yes, lgtm, release-note-none, sig/network, size/L

#5525 Fix disappearence of go_containerregistry 0.1.4
  WORKSPACE
Labels: dco-signoff: yes, release-note-none, size/S

#5513 refactor reconcile certificate secret
  pkg/virt-operator/kubevirt_test.go
  pkg/virt-operator/resource/apply/core.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/L

#5519 Fix double free of VirDomain
  pkg/virt-launcher/virtwrap/manager.go
  pkg/virt-launcher/virtwrap/manager_test.go
Labels: approved, dco-signoff: yes, lgtm, size/XS

#5471 Reconcile apiservice
  pkg/virt-operator/kubevirt_test.go
  pkg/virt-operator/resource/apply/BUILD.bazel
  pkg/virt-operator/resource/apply/apiservices.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/L

#5510 Add tests to quarantine
  tests/storage/hotplug.go
  tests/storage/restore.go
  tests/vmi_lifecycle_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#5501 network, unit tests: remove podInterface mocks
  pkg/virt-launcher/virtwrap/network/BUILD.bazel
  pkg/virt-launcher/virtwrap/network/generated_mock_podinterface.go
  pkg/virt-launcher/virtwrap/network/podinterface.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, sig/network, size/L

#5109 Add support and auto-detection of logical and physical block sizes.
  api/openapi-spec/swagger.json
  pkg/virt-api/webhooks/validating-webhook/admitters/vmi-create-admitter.go
  pkg/virt-api/webhooks/validating-webhook/admitters/vmi-create-admitter_test.go
  pkg/virt-launcher/virtwrap/api/deepcopy_generated.go
  pkg/virt-launcher/virtwrap/api/schema.go
  pkg/virt-launcher/virtwrap/converter/BUILD.bazel
  pkg/virt-launcher/virtwrap/converter/converter.go
  pkg/virt-launcher/virtwrap/converter/converter_test.go
  pkg/virt-operator/resource/generate/components/validations_generated.go
  staging/src/kubevirt.io/client-go/api/v1/deepcopy_generated.go
  staging/src/kubevirt.io/client-go/api/v1/openapi_generated.go
  staging/src/kubevirt.io/client-go/api/v1/schema.go
  staging/src/kubevirt.io/client-go/api/v1/schema_swagger_generated.go
  staging/src/kubevirt.io/client-go/api/v1/zz_generated.defaults.go
  staging/src/kubevirt.io/client-go/apis/snapshot/v1alpha1/openapi_generated.go
  tests/vmi_configuration_test.go
Labels: approved, dco-signoff: yes, kind/api-change, lgtm, ok-to-test, release-note, size/XL

#5469 network, driver: remove unused method GenerateRandomMac
  pkg/virt-launcher/virtwrap/network/common.go
  pkg/virt-launcher/virtwrap/network/common_test.go
  pkg/virt-launcher/virtwrap/network/generated_mock_common.go
  pkg/virt-launcher/virtwrap/network/podinterface_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, sig/network, size/M

#5504 take test_id:3201 out of quarantine
  tests/vmi_lifecycle_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#5535 Fix quarantine filtering
  automation/run-quarantined-tests.sh
  automation/test.sh
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/S

#4977 Remove global var Handler from virt-launcher/virtwrap/network
  pkg/virt-launcher/virtwrap/network/common.go
  pkg/virt-launcher/virtwrap/network/network.go
  pkg/virt-launcher/virtwrap/network/network_test.go
  pkg/virt-launcher/virtwrap/network/podinterface.go
  pkg/virt-launcher/virtwrap/network/podinterface_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/L

#5382 Snapshot online vm
  pkg/virt-api/webhooks/validating-webhook/admitters/vmsnapshot-admitter.go
  pkg/virt-api/webhooks/validating-webhook/admitters/vmsnapshot-admitter_test.go
  pkg/virt-controller/watch/snapshot/restore.go
  pkg/virt-controller/watch/snapshot/snapshot.go
  pkg/virt-controller/watch/snapshot/snapshot_test.go
  tests/storage/restore.go
  tests/storage/snapshot.go
  tests/utils.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/L

#5410 reconcile ServiceAccount resources
  pkg/virt-operator/resource/apply/core.go
  pkg/virt-operator/resource/apply/core_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/L

#5428 virt-launcher, Fix flaky VMI report (random missing Guest Agent data)
  pkg/virt-handler/cache/cache_test.go
  pkg/virt-launcher/virtwrap/agent-poller/agent_poller.go
  pkg/virt-launcher/virtwrap/cmd-server/server.go
  pkg/virt-launcher/virtwrap/cmd-server/server_test.go
  pkg/virt-launcher/virtwrap/generated_mock_manager.go
  pkg/virt-launcher/virtwrap/manager.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M

#5515 Add missing dollar signs to max_retry variable
  hack/prefetch-images.sh
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#5323 Let live migration monitor verify the actual status of migration before posting an error from libvirt
  pkg/virt-launcher/virtwrap/live-migration-source.go
  pkg/virt-launcher/virtwrap/manager_test.go
  vendor/libvirt.org/libvirt-go/domain.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/L

#5532 remove test_id: 1678 from quarantine
  tests/vmi_configuration_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#5511 cache `virtIface` as `setupPodNetworking` last operation
  pkg/virt-launcher/virtwrap/network/podinterface.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#5529 tests, jobs: cleanup of a netcat closed issue
  tests/job.go
  tests/network/expose.go
  tests/network/services.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M

#5540 Feature gates for testing
  hack/cluster-build.sh
  tests/utils.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#5549 [release-0.40] Fix double free of VirDomain object
  pkg/virt-launcher/virtwrap/manager.go
  pkg/virt-launcher/virtwrap/manager_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#5457 tests: add test for io events
  tests/BUILD.bazel
  tests/events_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/L

#5533 Bump bazeldnf version to v0.1.0
  WORKSPACE
Labels: approved, dco-signoff: yes, lgtm, release-note, size/XS

#5548 [release-0.39] Fix double free of VirDomain object
  pkg/virt-launcher/virtwrap/manager.go
  pkg/virt-launcher/virtwrap/manager_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#5520 Reconcile configmap
  pkg/virt-operator/resource/apply/core.go
  pkg/virt-operator/resource/apply/reconcile.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/L

#5544 Assign template and container disk tests to sig-compute
  tests/container_disk_test.go
  tests/template_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#5557 Revert "virt-launcher, Fix flaky VMI report"
  pkg/virt-handler/cache/cache_test.go
  pkg/virt-launcher/virtwrap/agent-poller/agent_poller.go
  pkg/virt-launcher/virtwrap/cmd-server/server.go
  pkg/virt-launcher/virtwrap/cmd-server/server_test.go
  pkg/virt-launcher/virtwrap/generated_mock_manager.go
  pkg/virt-launcher/virtwrap/manager.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M

#5459 reconcile service resource
  pkg/virt-operator/kubevirt_test.go
  pkg/virt-operator/resource/apply/BUILD.bazel
  pkg/virt-operator/resource/apply/apps_test.go
  pkg/virt-operator/resource/apply/core.go
  pkg/virt-operator/resource/apply/core_test.go
  pkg/virt-operator/resource/apply/reconcile.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/XL

#5524 [release-0.34] Improve migration debug logging
  pkg/virt-handler/migration-proxy/migration-proxy.go
  pkg/virt-handler/migration-proxy/migration-proxy_test.go
  pkg/virt-handler/vm.go
  pkg/virt-launcher/virtwrap/manager.go
  staging/src/kubevirt.io/client-go/log/log.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/L

#5536 fix log pkg With() function for custom arguments
  pkg/virt-handler/migration-proxy/migration-proxy.go
  staging/src/kubevirt.io/client-go/log/log.go
  staging/src/kubevirt.io/client-go/log/log_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M

#5541 Quarantine operator test
  tests/operator_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#5542 Add VMI start strategy
  api/openapi-spec/swagger.json
  pkg/virt-api/webhooks/validating-webhook/admitters/vmi-create-admitter.go
  pkg/virt-api/webhooks/validating-webhook/admitters/vmi-create-admitter_test.go
  pkg/virt-launcher/virtwrap/cli/generated_mock_libvirt.go
  pkg/virt-launcher/virtwrap/cli/libvirt.go
  pkg/virt-launcher/virtwrap/manager.go
  pkg/virt-launcher/virtwrap/manager_test.go
  pkg/virt-operator/resource/generate/components/validations_generated.go
  staging/src/kubevirt.io/client-go/api/v1/deepcopy_generated.go
  staging/src/kubevirt.io/client-go/api/v1/openapi_generated.go
  staging/src/kubevirt.io/client-go/api/v1/types.go
  staging/src/kubevirt.io/client-go/api/v1/types_swagger_generated.go
  staging/src/kubevirt.io/client-go/apis/snapshot/v1alpha1/openapi_generated.go
  tests/vmi_lifecycle_test.go
Labels: approved, dco-signoff: yes, kind/api-change, lgtm, release-note, size/L
