Repository kubevirt/kubevirt, pull requests merged in 2021-10, with the labels that each got.

#6428 Remove test NFS test from quarantine
  tests/storage/storage.go
Labels: size/XS, release-note-none, lgtm, approved, dco-signoff: yes

#6425 Handle iothreads for hotplugged disks.
  pkg/virt-launcher/virtwrap/api/deepcopy_generated.go
  pkg/virt-launcher/virtwrap/api/schema.go
  pkg/virt-launcher/virtwrap/converter/converter.go
  pkg/virt-launcher/virtwrap/converter/converter_test.go
  tests/storage/hotplug.go
  tests/vmi_configuration_test.go
Labels: size/L, release-note, lgtm, approved, dco-signoff: yes

#6407 Ignore "didn't find PVC associated with DataVolume" spurious warning
  tests/utils.go
Labels: size/XS, release-note-none, lgtm, approved, dco-signoff: yes

#6375 Integrate kubevirtci cdi deployment
  Makefile
  automation/test.sh
  cluster-up-sha.txt
  cluster-up/cluster/ephemeral-provider-common.sh
  cluster-up/cluster/k8s-provider-common.sh
  cluster-up/hack/common.sh
  cluster-up/version.txt
  docs/getting-started.md
  hack/cluster-clean.sh
  hack/cluster-deploy.sh
  hack/cluster-up.sh
  hack/config-default.sh
  manifests/testing/cdi-v1.36.0.yaml.in
Labels: release-note, size/XXL, lgtm, approved, dco-signoff: yes

#6440 Collect DataVolumes info on test failure
  tests/reporter/BUILD.bazel
  tests/reporter/kubernetes.go
Labels: size/L, release-note-none, lgtm, approved, dco-signoff: yes

#6468 Remove test 6225 from Quarantine
  tests/storage/events.go
Labels: size/XS, release-note-none, lgtm, approved, dco-signoff: yes

#6488 sriov, Fix flaky context deadline exceeded tests
  tests/network/vmi_multus.go
  tests/utils.go
Labels: size/S, release-note-none, lgtm, approved, dco-signoff: yes

#6405 Remove test_id:4621 from quarantine (fixed in #6312)
  tests/storage/imageupload.go
Labels: size/XS, release-note-none, lgtm, approved, dco-signoff: yes

#6482 migration: generate empty isos on target for cloud-inits, configmaps, secrets, ...
  api/openapi-spec/swagger.json
  pkg/cloud-init/cloud-init.go
  pkg/cloud-init/cloud-init_test.go
  pkg/config/config-map.go
  pkg/config/config-map_test.go
  pkg/config/config.go
  pkg/config/config_test.go
  pkg/config/downwardapi.go
  pkg/config/downwardapi_test.go
  pkg/config/secret.go
  pkg/config/secret_test.go
  pkg/config/service-account.go
  pkg/config/service-account_test.go
  pkg/config/sysprep.go
  pkg/config/sysprep_test.go
  pkg/virt-handler/BUILD.bazel
  pkg/virt-handler/vm.go
  pkg/virt-launcher/virtwrap/live-migration-target.go
  pkg/virt-launcher/virtwrap/manager.go
  pkg/virt-launcher/virtwrap/manager_test.go
  pkg/virt-operator/resource/generate/components/validations_generated.go
  staging/src/kubevirt.io/client-go/api/v1/openapi_generated.go
  staging/src/kubevirt.io/client-go/api/v1/types.go
  staging/src/kubevirt.io/client-go/api/v1/types_swagger_generated.go
  staging/src/kubevirt.io/client-go/apis/snapshot/v1alpha1/openapi_generated.go
  tests/operator_test.go
Labels: size/L, release-note, kind/api-change, lgtm, approved, dco-signoff: yes

#6437 Fix deprecated use of watch API
  pkg/controller/controller.go
Labels: release-note, size/XS, lgtm, approved, ok-to-test, dco-signoff: yes

#6512 [release-0.36] Fix domain lookup to ensure target pod of migration is cleanup
  cmd/virt-launcher/virt-launcher.go
Labels: size/M, release-note, lgtm, approved, dco-signoff: yes

#6444 Add DryRun functional tests for KubeVirt resources
  tests/BUILD.bazel
  tests/dryrun_test.go
  tests/utils.go
Labels: size/XL, release-note-none, lgtm, approved, dco-signoff: yes

#6171 Detect and report an ErrorPvcNotFound/ErrorDataVolumeNotFound VM status
  pkg/virt-controller/services/template.go
  pkg/virt-controller/services/template_test.go
  pkg/virt-controller/watch/vm.go
  pkg/virt-controller/watch/vm_test.go
  pkg/virt-controller/watch/vmi.go
  pkg/virt-controller/watch/vmi_test.go
  staging/src/kubevirt.io/client-go/api/v1/types.go
  tests/vm_test.go
Labels: size/L, release-note, kind/api-change, lgtm, approved, dco-signoff: yes

#6520 [virt-launcher]: lower the log severity of GA unsupported commands
  staging/src/kubevirt.io/client-go/log/log.go
Labels: size/S, release-note-none, lgtm, approved, dco-signoff: yes

#6703 Fix vmsnapshot upgrade bug
  pkg/virt-controller/watch/snapshot/snapshot.go
  tests/storage/snapshot.go
Labels: size/M, release-note, lgtm, approved, dco-signoff: yes

#6643 Fix [test_id:6978] Should detect a failed migration
  tests/migration.go
  tests/migration_test.go
Labels: size/S, release-note-none, lgtm, approved, dco-signoff: yes
