Repository kubevirt/kubevirt, pull requests merged in 2021-03, with the labels that each got.

#4387 multus-tests, ptp: extract ptp subnet to a const
  tests/vmi_multus_test.go
Labels: approved, dco-signoff: yes, lgtm, ok-to-test, release-note-none, size/S

#5012 tests, Enable watching for vmi errors in case ignoreWarnings is true
  tests/utils.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/S

#4741 virt-launcher, migration: Detach SRIOV devices before migration
  pkg/virt-handler/vm.go
  pkg/virt-handler/vm_test.go
  pkg/virt-launcher/virtwrap/api/deepcopy_generated.go
  pkg/virt-launcher/virtwrap/api/schema.go
  pkg/virt-launcher/virtwrap/cli/BUILD.bazel
  pkg/virt-launcher/virtwrap/cli/event.go
  pkg/virt-launcher/virtwrap/cli/generated_mock_libvirt.go
  pkg/virt-launcher/virtwrap/cli/libvirt.go
  pkg/virt-launcher/virtwrap/device/sriov/hostdev.go
  pkg/virt-launcher/virtwrap/device/sriov/hostdev_test.go
  pkg/virt-launcher/virtwrap/manager.go
  tests/vmi_multus_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/XL

#5086 docs: host devices: resourceName case consistency
  docs/devel/host-devices-and-device-plugins.md
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#5126 Update CDI to v1.31.0
  api/openapi-spec/swagger.json
  go.mod
  go.sum
  manifests/testing/cdi-v1.31.0.yaml.in
  pkg/virt-operator/resource/generate/components/validations_generated.go
  staging/src/kubevirt.io/client-go/api/v1/openapi_generated.go
  staging/src/kubevirt.io/client-go/generated/containerized-data-importer/clientset/versioned/typed/core/v1beta1/BUILD.bazel
  staging/src/kubevirt.io/client-go/generated/containerized-data-importer/clientset/versioned/typed/core/v1beta1/core_client.go
  staging/src/kubevirt.io/client-go/generated/containerized-data-importer/clientset/versioned/typed/core/v1beta1/fake/BUILD.bazel
  staging/src/kubevirt.io/client-go/generated/containerized-data-importer/clientset/versioned/typed/core/v1beta1/fake/fake_core_client.go
  staging/src/kubevirt.io/client-go/generated/containerized-data-importer/clientset/versioned/typed/core/v1beta1/fake/fake_objecttransfer.go
  staging/src/kubevirt.io/client-go/generated/containerized-data-importer/clientset/versioned/typed/core/v1beta1/fake/fake_storageprofile.go
  staging/src/kubevirt.io/client-go/generated/containerized-data-importer/clientset/versioned/typed/core/v1beta1/generated_expansion.go
  staging/src/kubevirt.io/client-go/generated/containerized-data-importer/clientset/versioned/typed/core/v1beta1/objecttransfer.go
  staging/src/kubevirt.io/client-go/generated/containerized-data-importer/clientset/versioned/typed/core/v1beta1/storageprofile.go
  staging/src/kubevirt.io/client-go/go.mod
  staging/src/kubevirt.io/client-go/go.sum
  vendor/github.com/gogo/protobuf/proto/text_parser.go
  vendor/kubevirt.io/containerized-data-importer/pkg/apis/core/v1alpha1/openapi_generated.go
  vendor/kubevirt.io/containerized-data-importer/pkg/apis/core/v1alpha1/types.go
  vendor/kubevirt.io/containerized-data-importer/pkg/apis/core/v1alpha1/types_swagger_generated.go
  vendor/kubevirt.io/containerized-data-importer/pkg/apis/core/v1alpha1/zz_generated.deepcopy.go
  vendor/kubevirt.io/containerized-data-importer/pkg/apis/core/v1beta1/BUILD.bazel
  vendor/kubevirt.io/containerized-data-importer/pkg/apis/core/v1beta1/openapi_generated.go
  vendor/kubevirt.io/containerized-data-importer/pkg/apis/core/v1beta1/register.go
  vendor/kubevirt.io/containerized-data-importer/pkg/apis/core/v1beta1/types.go
  vendor/kubevirt.io/containerized-data-importer/pkg/apis/core/v1beta1/types_swagger_generated.go
  vendor/kubevirt.io/containerized-data-importer/pkg/apis/core/v1beta1/types_transfer.go
  vendor/kubevirt.io/containerized-data-importer/pkg/apis/core/v1beta1/zz_generated.deepcopy.go
  vendor/kubevirt.io/containerized-data-importer/pkg/apis/upload/v1beta1/openapi_generated.go
  vendor/kubevirt.io/containerized-data-importer/pkg/apis/upload/v1beta1/types.go
  vendor/modules.txt
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XXL

#5054 Properly deal with absolute paths in unit tests, part 2
  cmd/virt-handler/BUILD.bazel
  cmd/virt-handler/virt-handler.go
  pkg/virt-handler/BUILD.bazel
  pkg/virt-handler/vm.go
  pkg/virt-handler/vm_test.go
  pkg/virt-launcher/virtwrap/BUILD.bazel
  pkg/virt-launcher/virtwrap/manager.go
  pkg/virt-launcher/virtwrap/manager_test.go
  pkg/virt-launcher/virtwrap/network/BUILD.bazel
  pkg/virt-launcher/virtwrap/network/cache/BUILD.bazel
  pkg/virt-launcher/virtwrap/network/cache/cache_suite_test.go
  pkg/virt-launcher/virtwrap/network/cache/fake/BUILD.bazel
  pkg/virt-launcher/virtwrap/network/cache/fake/infocache.go
  pkg/virt-launcher/virtwrap/network/cache/infocache.go
  pkg/virt-launcher/virtwrap/network/cache/infocache_test.go
  pkg/virt-launcher/virtwrap/network/cache/types.go
  pkg/virt-launcher/virtwrap/network/common_test.go
  pkg/virt-launcher/virtwrap/network/generated_mock_infocache.go
  pkg/virt-launcher/virtwrap/network/infocache.go
  pkg/virt-launcher/virtwrap/network/network.go
  pkg/virt-launcher/virtwrap/network/network_test.go
  pkg/virt-launcher/virtwrap/network/podinterface.go
  pkg/virt-launcher/virtwrap/network/podinterface_test.go
Labels: approved, dco-signoff: yes, kind/build-change, lgtm, release-note-none, size/XL

#5002 sriov, Let SyncVMI DeadlineExceeded warning be non fatal in tests
  tests/storage_test.go
  tests/utils.go
  tests/vmi_configuration_test.go
  tests/vmi_multus_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/L

#5117 pkg, cleanup: Remove unused constants
  pkg/cloud-init/cloud-init.go
  pkg/virt-controller/services/template.go
  pkg/virt-controller/services/template_test.go
  pkg/virt-handler/device-manager/deviceplugin/v1beta1/constants.go
  pkg/virtctl/vm/vm_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#5087 Move kubevirt/builder image to quay.io
  hack/builder/Dockerfile
  hack/builder/build.sh
  hack/builder/publish.sh
  hack/builder/version.sh
  hack/dockerized
Labels: approved, dco-signoff: yes, lgtm, ok-to-test, release-note-none, size/S

#5149 Add support for hyperv stimer direct
  api/openapi-spec/swagger.json
  pkg/virt-api/webhooks/hyperv.go
  pkg/virt-api/webhooks/mutating-webhook/mutators/vmi-mutator_test.go
  pkg/virt-api/webhooks/validating-webhook/admitters/vmi-create-admitter_test.go
  pkg/virt-controller/services/template.go
  pkg/virt-controller/services/template_test.go
  pkg/virt-launcher/virtwrap/api/deepcopy_generated.go
  pkg/virt-launcher/virtwrap/api/schema.go
  pkg/virt-launcher/virtwrap/converter/converter.go
  pkg/virt-launcher/virtwrap/converter/converter_test.go
  pkg/virt-operator/resource/generate/components/validations_generated.go
  staging/src/kubevirt.io/client-go/api/v1/deepcopy_generated.go
  staging/src/kubevirt.io/client-go/api/v1/defaults.go
  staging/src/kubevirt.io/client-go/api/v1/defaults_test.go
  staging/src/kubevirt.io/client-go/api/v1/openapi_generated.go
  staging/src/kubevirt.io/client-go/api/v1/schema.go
  staging/src/kubevirt.io/client-go/api/v1/schema_swagger_generated.go
  staging/src/kubevirt.io/client-go/api/v1/schema_test.go
  staging/src/kubevirt.io/client-go/api/v1/zz_generated.defaults.go
  staging/src/kubevirt.io/client-go/apis/snapshot/v1alpha1/openapi_generated.go
  tests/windows_test.go
Labels: approved, dco-signoff: yes, kind/api-change, lgtm, release-note, size/L

#5158 Fix possible memory leak of libvirt.Domains
  pkg/virt-launcher/virtwrap/cli/libvirt.go
  pkg/virt-launcher/virtwrap/manager.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/S

#5039 tests, Increase default memory of VMIs to 128Mi
  examples/vm-alpine-datavolume.yaml
  examples/vm-alpine-multipvc.yaml
  examples/vm-cirros.yaml
  examples/vm-priorityclass.yaml
  examples/vmi-block-pvc.yaml
  examples/vmi-ephemeral.yaml
  examples/vmi-flavor-small.yaml
  examples/vmi-host-disk.yaml
  examples/vmi-migratable.yaml
  examples/vmi-nocloud.yaml
  examples/vmi-preset-small.yaml
  examples/vmi-pvc.yaml
  examples/vmi-replicaset-cirros.yaml
  examples/vmi-sata.yaml
  tests/libvmi/factory.go
  tests/restore_test.go
  tests/storage_test.go
  tests/utils.go
  tests/vm_test.go
  tests/vmi_configuration_test.go
  tests/vmi_iothreads_test.go
  tests/vmi_networking_test.go
  tests/vmi_slirp_interface_test.go
  tools/vms-generator/utils/utils.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/L

#5061 Lower virt-handler probe intervals to prevent api server calls
  pkg/virt-operator/resource/generate/components/deployments.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#5093 multus_tests, sriov: add vlan=0 to NAD
  tests/vmi_multus_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, sig/network, size/XS

#5161 tests, sriov: Do not configure pod network IPv6 on fedora-login
  tests/vmi_multus_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#5115 pkg, cleanup: Remove unused functions
  pkg/controller/controller.go
  pkg/middleware/middleware.go
  pkg/testutils/BUILD.bazel
  pkg/testutils/matchers.go
  pkg/virt-controller/watch/BUILD.bazel
  pkg/virt-controller/watch/util.go
  pkg/virt-launcher/notify-client/client.go
  pkg/virt-launcher/virtwrap/converter/converter.go
  pkg/virt-operator/kubevirt.go
  pkg/virt-operator/resource/apply/reconcile.go
  pkg/virt-operator/resource/generate/install/strategy.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/L

#5133 Add description to VirtualMachinePreset
  api/openapi-spec/swagger.json
  pkg/virt-operator/resource/generate/components/validations_generated.go
  staging/src/kubevirt.io/client-go/api/v1/openapi_generated.go
  staging/src/kubevirt.io/client-go/api/v1/types.go
  staging/src/kubevirt.io/client-go/api/v1/types_swagger_generated.go
  staging/src/kubevirt.io/client-go/apis/snapshot/v1alpha1/openapi_generated.go
Labels: approved, dco-signoff: yes, kind/api-change, lgtm, release-note-none, size/S

#5141 Fix Typo
  docs/devel/networking.md
Labels: approved, dco-signoff: yes, lgtm, ok-to-test, release-note-none, size/XS

#5156 Quarantine flakiest tests
  automation/run-quarantined-tests.sh
  automation/test.sh
  tests/imageupload_test.go
  tests/operator_test.go
  tests/storage_test.go
  tests/vmi_networking_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M

#4990 network: simpler factory
  pkg/virt-launcher/virtwrap/network/network.go
  pkg/virt-launcher/virtwrap/network/network_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/L

#4991 test_id:713: make failure slightly more legible
  tests/vmi_headless_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#5013 [Bug-fix]: Migration pod becomes "Evicted" since no ephemeral-storage is requested
  pkg/container-disk/container-disk.go
  pkg/container-disk/container-disk_test.go
  pkg/virt-controller/services/template.go
  pkg/virt-controller/services/template_test.go
Labels: approved, dco-signoff: yes, kind/api-change, lgtm, release-note-none, size/L

#5140 handle image upload to data volume with existing pvc name
  pkg/virtctl/imageupload/imageupload.go
  pkg/virtctl/imageupload/imageupload_test.go
Labels: approved, dco-signoff: yes, lgtm, ok-to-test, release-note-none, size/S

#5171 Fix repeated_test.sh on file rename
  automation/repeated_test.sh
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#5048 Functional test for customized XML marshal/unmarshal for user defined…
  tests/migration_test.go
Labels: approved, dco-signoff: yes, lgtm, ok-to-test, release-note-none, size/M

#5176 fix stimer hyperv feature
  pkg/virt-launcher/virtwrap/converter/converter.go
  pkg/virt-launcher/virtwrap/converter/converter_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M

#5088 Hotplug hostpath support
  pkg/virt-controller/services/template.go
  pkg/virt-handler/hotplug-disk/BUILD.bazel
  pkg/virt-handler/hotplug-disk/mount.go
  pkg/virt-handler/hotplug-disk/mount_test.go
  tests/storage/hotplug.go
  tests/utils.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/L

#5120 pkg, cleanup: Remove unused global variables
  pkg/controller/controller_ref_manager_test.go
  pkg/virt-api/webhooks/utils.go
  pkg/virtctl/expose/expose.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#5178 Extend timeout for a flaky imageupload test
  tests/imageupload_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#5096 Add networking metrics
  docs/metrics.md
  pkg/monitoring/vms/prometheus/fakeCollector.go
  pkg/monitoring/vms/prometheus/prometheus.go
  pkg/monitoring/vms/prometheus/prometheus_test.go
  pkg/virt-launcher/virtwrap/cli/BUILD.bazel
  pkg/virt-launcher/virtwrap/cli/libvirt.go
  pkg/virt-launcher/virtwrap/stats/types.go
  pkg/virt-launcher/virtwrap/statsconv/converter.go
  pkg/virt-launcher/virtwrap/statsconv/converter_test.go
  pkg/virt-launcher/virtwrap/statsconv/util/domstats_utils.go
Labels: approved, dco-signoff: yes, lgtm, release-note, sig/network, size/L

#5188 [tests] Fix kubevirt default configuration initialization
  tests/utils.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#5122 tests, cleanup: Various cleanups on the e2e tests.
  tests/config_test.go
  tests/infra_test.go
  tests/migration_test.go
  tests/reporter/kubernetes.go
  tests/utils.go
  tests/virt_control_plane_test.go
  tests/vmi_gpu_test.go
  tests/vmi_hostdev_test.go
  tests/vmi_multus_test.go
  tests/vmi_networking_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M

#5145 Allow to create tap device for any user
  pkg/virt-launcher/virtwrap/network/common.go
  pkg/virt-launcher/virtwrap/network/generated_mock_common.go
  pkg/virt-launcher/virtwrap/network/podinterface.go
  pkg/virt-launcher/virtwrap/network/podinterface_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, sig/network, size/M

#5184 Fix audit logs
  tests/reporter/kubernetes.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#5137 Policy and criteria for backporting to stable release branches
  docs/release-branch-backporting.md
  docs/release.md
Labels: dco-signoff: yes, lgtm, release-note, size/M

#5114 tests, network: XFail IPv6 connectivity check to an external address
  tests/vmi_networking_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/S

#5207 kubevirtci: Bump to 8f48705
  cluster-up-sha.txt
  cluster-up/cluster/ephemeral-provider-common.sh
  cluster-up/hack/common.sh
  cluster-up/version.txt
  hack/config-default.sh
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/S

#5182 Add [release-blocker] test marker for critical tests involved with update path.
  tests/migration_test.go
  tests/operator_test.go
  tests/vm_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/XS

#5218 Increase timeouts in sriov unit tests
  pkg/virt-launcher/virtwrap/device/sriov/hostdev_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#5097 Reduce cognitive complexity
  pkg/config/sysprep.go
Labels: approved, dco-signoff: yes, lgtm, ok-to-test, release-note-none, size/M

#5084 add validationwebhook for KubeVirt.Spec.CustomizeComponents
  manifests/generated/kv-resource.yaml
  pkg/util/webhooks/validating-webhooks/BUILD.bazel
  pkg/util/webhooks/validating-webhooks/validating-webhook.go
  pkg/virt-operator/resource/generate/components/validations_generated.go
  pkg/virt-operator/webhooks/BUILD.bazel
  pkg/virt-operator/webhooks/kubevirt-update-admitter.go
  pkg/virt-operator/webhooks/kubevirt-update-admitter_test.go
  staging/src/kubevirt.io/client-go/api/v1/types.go
  staging/src/kubevirt.io/client-go/api/v1/types_swagger_generated.go
Labels: approved, dco-signoff: yes, kind/api-change, lgtm, release-note, size/L

#5152 virt-launcher, sriov: Update the domain config state on detach
  pkg/virt-launcher/virtwrap/cli/generated_mock_libvirt.go
  pkg/virt-launcher/virtwrap/cli/libvirt.go
  pkg/virt-launcher/virtwrap/device/sriov/BUILD.bazel
  pkg/virt-launcher/virtwrap/device/sriov/hostdev.go
  pkg/virt-launcher/virtwrap/device/sriov/hostdev_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/S

#5170 tests, network: Move test-files to the network subpackage
  tests/BUILD.bazel
  tests/migration_test.go
  tests/network/BUILD.bazel
  tests/network/expose.go
  tests/network/networkpolicy.go
  tests/network/vmi_multus.go
  tests/network/vmi_networking.go
  tests/network/vmi_slirp_interface.go
  tests/utils.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M

#5206 Simplify greps in determination of new tests
  automation/repeated_test.sh
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/S

#5119 pkg, cleanup: Remove redundant blank expression in for-loop
  pkg/container-disk/container-disk.go
  pkg/util/openapi/openapi.go
  pkg/virt-api/webhooks/validating-webhook/admitters/vmi-create-admitter_test.go
  pkg/virt-handler/cmd-client/client.go
  pkg/virt-handler/vm.go
  pkg/virt-operator/kubevirt_test.go
  pkg/virt-operator/resource/apply/admissionregistration.go
  pkg/virt-operator/resource/apply/apps_test.go
  pkg/virt-operator/resource/apply/scc_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M

#5214 Use --remote_download_toplevel for e2e tests and optimize the bazel build for it
  .bazelversion
  BUILD.bazel
  automation/test.sh
  hack/build-func-tests.sh
  hack/builder/Dockerfile
  hack/builder/version.sh
  hack/cluster-build.sh
  hack/dockerized
  tools/manifest-templator/BUILD.bazel
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M

#5128 Modify memory metrics
  docs/metrics.md
  pkg/monitoring/vms/prometheus/fakeCollector.go
  pkg/monitoring/vms/prometheus/prometheus.go
  pkg/monitoring/vms/prometheus/prometheus_test.go
  pkg/virt-launcher/virtwrap/cli/libvirt.go
  pkg/virt-launcher/virtwrap/stats/types.go
  pkg/virt-launcher/virtwrap/statsconv/converter.go
  pkg/virt-launcher/virtwrap/statsconv/converter_test.go
  pkg/virt-launcher/virtwrap/statsconv/util/domstats_utils.go
  tests/infra_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/L

#5136 Do not try to get the labels if selinux is disabled
  pkg/virt-handler/selinux/BUILD.bazel
  pkg/virt-handler/selinux/context_executor.go
  pkg/virt-handler/selinux/context_executor_test.go
  pkg/virt-handler/selinux/executor.go
  pkg/virt-handler/selinux/generated_mock_executor.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/L

#5167 sig-network, Add networking tests to the sig network family
  automation/test.sh
  tests/network/expose.go
  tests/network/networkpolicy.go
  tests/network/vmi_multus.go
  tests/network/vmi_networking.go
  tests/network/vmi_slirp_interface.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/S

#5118 pkg, cleanup: Remove redundant type in composite literal
  pkg/hooks/manager_test.go
  pkg/monitoring/vms/prometheus/prometheus_test.go
  pkg/virt-api/webhooks/validating-webhook/admitters/vmi-create-admitter_test.go
  pkg/virt-controller/services/template.go
  pkg/virt-controller/services/template_test.go
  pkg/virt-controller/watch/node_test.go
  pkg/virt-controller/watch/snapshot/snapshot_base.go
  pkg/virt-controller/watch/vmi_test.go
  pkg/virt-launcher/notify-client/notify_test.go
  pkg/virt-launcher/virtwrap/agent-poller/agent_parser_test.go
  pkg/virt-launcher/virtwrap/api/schema_test.go
  pkg/virt-launcher/virtwrap/cmd-server/server_test.go
  pkg/virt-launcher/virtwrap/converter/converter_test.go
  pkg/virt-launcher/virtwrap/manager_test.go
  pkg/virt-launcher/virtwrap/network/dhcp/dhcp_test.go
  pkg/virt-launcher/virtwrap/network/network_test.go
  pkg/virt-operator/resource/apply/apps_test.go
  pkg/virt-operator/resource/apply/reconcile_test.go
  pkg/virt-operator/resource/generate/components/crds.go
  pkg/virtctl/vm/vm_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/L

#5221 [virt-operator] Remove a webhook check which checks workload placement
  pkg/virt-operator/webhooks/BUILD.bazel
  pkg/virt-operator/webhooks/kubevirt-update-admitter.go
  pkg/virt-operator/webhooks/kubevirt-update-admitter_test.go
  tests/operator_test.go
  tests/vmi_lifecycle_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/L

#5223 Virt Handler Migration logic refactor
  go.mod
  pkg/virt-handler/vm.go
  pkg/virt-handler/vm_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XL

#5237 Bazel can open quite some files, increase ulimits for files inside the build container
  hack/dockerized
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#5239 Improve random seed initialization on the test suite
  tests/utils.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#5229 QUARANTINE the vmi workload update verification logic
  tests/BUILD.bazel
  tests/operator_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#5235 Move tests 2731,3193,3194 into quarantine
  tests/datavolume_test.go
  tests/migration_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#5165 Introduce a VMsize paramter in the runstress function to use custom values for different migration tests.
  tests/migration_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/S

#5091 Move SeaBios debug log to be seen as part of the virt-launcher log
  pkg/virt-launcher/virtwrap/converter/converter.go
  pkg/virt-launcher/virtwrap/util/BUILD.bazel
  pkg/virt-launcher/virtwrap/util/libvirt_helper.go
Labels: approved, dco-signoff: yes, kind/build-change, lgtm, release-note, size/L

#4760 Improve and refactor heartbeats on virt-handler
  pkg/testutils/mock_config.go
  pkg/virt-handler/BUILD.bazel
  pkg/virt-handler/device-manager/device_controller.go
  pkg/virt-handler/heartbeat/BUILD.bazel
  pkg/virt-handler/heartbeat/heartbeat.go
  pkg/virt-handler/heartbeat/heartbeat_suite_test.go
  pkg/virt-handler/heartbeat/heartbeat_test.go
  pkg/virt-handler/heartbeat/testdata/cpu_manager_state_none
  pkg/virt-handler/heartbeat/testdata/cpu_manager_state_static
  pkg/virt-handler/vm.go
  pkg/virt-handler/vm_test.go
Labels: approved, dco-signoff: yes, kind/build-change, lgtm, release-note, size/XL

#5247 Removing unnecessary log file(1_events.log)
  tests/k8s-reporter/1_events.log
Labels: approved, dco-signoff: yes, lgtm, needs-ok-to-test, release-note-none, size/XS

#4892 Add ocs rbd storageClass for downstream testing
  tests/utils.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#5157 Refactor func generateVMVolumeRequestPatch
  pkg/virt-api/rest/subresource.go
Labels: approved, dco-signoff: yes, lgtm, ok-to-test, release-note-none, size/M

#5215 adding code and test code for detecting Intel vGPUs
  pkg/virt-handler/device-manager/BUILD.bazel
  pkg/virt-handler/device-manager/mediated_device.go
  pkg/virt-handler/device-manager/mediated_device_test.go
Labels: approved, dco-signoff: yes, lgtm, ok-to-test, release-note, size/L

#5227 containers: Fix duplicate group name for gid=0
  cmd/virt-handler/BUILD.bazel
  cmd/virt-launcher/BUILD.bazel
  images/BUILD.bazel
Labels: approved, dco-signoff: yes, kind/build-change, lgtm, release-note-none, size/XS

#5198 [release-0.36] support extracting metadata for transients domains
  pkg/virt-launcher/notify-client/client.go
  pkg/virt-launcher/notify-client/notify_test.go
  pkg/virt-launcher/virtwrap/cli/generated_mock_libvirt.go
  pkg/virt-launcher/virtwrap/cli/libvirt.go
  pkg/virt-launcher/virtwrap/manager.go
  pkg/virt-launcher/virtwrap/manager_test.go
  pkg/virt-launcher/virtwrap/util/BUILD.bazel
  pkg/virt-launcher/virtwrap/util/libvirt_helper.go
  pkg/virt-launcher/virtwrap/util/libvirt_helper_test.go
  tests/migration_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/L

#5191 Expose CPU affinity metric
  docs/metrics.md
  pkg/monitoring/vms/prometheus/fakeCollector.go
  pkg/monitoring/vms/prometheus/prometheus.go
  pkg/monitoring/vms/prometheus/prometheus_test.go
  pkg/virt-launcher/virtwrap/cli/libvirt.go
  pkg/virt-launcher/virtwrap/stats/types.go
  pkg/virt-launcher/virtwrap/statsconv/util/domstats_utils.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/M

#5210 Update incorrect doc
  docs/getting-started.md
Labels: approved, dco-signoff: yes, lgtm, ok-to-test, release-note-none, size/XS

#5153 rephrase "No VolumeSnapshotClass" reason
  pkg/virt-controller/watch/snapshot/snapshot.go
  pkg/virt-controller/watch/snapshot/snapshot_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M

#5179 Fix gosec target on prow
  hack/dockerized
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#5222 Allow pre-setting the KUBEVIRT_E2E_FOCUS env var in tests
  automation/test.sh
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M

#5138 Virt handler graceful shutdown for post-copy live migration
  cmd/virt-handler/BUILD.bazel
  cmd/virt-handler/virt-handler.go
  pkg/virt-handler/BUILD.bazel
  pkg/virt-handler/migration-proxy/migration-proxy.go
  pkg/virt-handler/migration-proxy/migration-proxy_test.go
  pkg/virt-handler/vm.go
  pkg/virt-handler/vm_test.go
  pkg/virt-operator/resource/generate/components/deployments.go
Labels: approved, dco-signoff: yes, kind/build-change, lgtm, release-note, size/L

#5082 Extend client-go
  staging/src/kubevirt.io/client-go/api/v1/register.go
  staging/src/kubevirt.io/client-go/api/v1/types.go
  staging/src/kubevirt.io/client-go/api/v1/types_swagger_generated.go
Labels: approved, dco-signoff: yes, kind/api-change, lgtm, release-note-none, size/S

#5261 Fix broken URL link
  docs/devel/networking.md
Labels: approved, dco-signoff: yes, lgtm, needs-ok-to-test, release-note-none, size/XS

#5266 automation, Validate that TARGET is non empty
  automation/test.sh
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#5269 Serve promethus VMI info from informer cache
  cmd/virt-handler/virt-handler.go
  pkg/monitoring/vms/prometheus/BUILD.bazel
  pkg/monitoring/vms/prometheus/prometheus.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/S

#5248 A very simple fix to avoid builder push collisions
  hack/builder/version.sh
  hack/dockerized
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#5270 Give the expecter more time on a e2e test to retrieve info
  tests/vmi_configuration_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#5265 Remove quay login from release shell script
  automation/release.sh
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#5037 Live Migration: attach SRIOV devices after migration is finished
  pkg/handler-launcher-com/cmd/v1/cmd.pb.go
  pkg/handler-launcher-com/cmd/v1/cmd.proto
  pkg/virt-handler/cmd-client/client.go
  pkg/virt-handler/cmd-client/generated_mock_client.go
  pkg/virt-handler/vm.go
  pkg/virt-handler/vm_test.go
  pkg/virt-launcher/virtwrap/cli/generated_mock_libvirt.go
  pkg/virt-launcher/virtwrap/cli/libvirt.go
  pkg/virt-launcher/virtwrap/cmd-server/server.go
  pkg/virt-launcher/virtwrap/cmd-server/server_test.go
  pkg/virt-launcher/virtwrap/device/sriov/BUILD.bazel
  pkg/virt-launcher/virtwrap/device/sriov/hostdev.go
  pkg/virt-launcher/virtwrap/device/sriov/hostdev_test.go
  pkg/virt-launcher/virtwrap/generated_mock_manager.go
  pkg/virt-launcher/virtwrap/manager.go
  tests/network/vmi_multus.go
Labels: approved, dco-signoff: yes, lgtm, release-note, sig/network, size/L

#5257 Fix estimation of number of tests per repeated test run
  automation/repeated_test.sh
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M

#5135 sriov, Fix race condition between LoginToFedora and cloud init
  WORKSPACE
  tests/libvmi/factory.go
  tests/utils.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, sig/network, size/S

#5277 Log warnings to the junit report for failing tests
  tests/reporter/BUILD.bazel
  tests/reporter/outputenricher.go
  tests/tests_suite_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/L

#5001 Fix flaky test: Waiting for vmi
  tests/migration_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#5264 Fix some vmi cleanup issues in vm_networking.go
  tests/migration_test.go
  tests/network/vmi_multus.go
  tests/network/vmi_networking.go
  tests/utils.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M

#5102 [Bugfix]: Fix crypto P-224 curve bug by updating Go version to 1.14.14
  BUILD.bazel
  WORKSPACE
  docs/update-go-version.md
  hack/builder/Dockerfile
  hack/dockerized
  pkg/certificates/BUILD.bazel
  pkg/hooks/BUILD.bazel
  pkg/util/openapi/BUILD.bazel
  pkg/virt-api/webhooks/BUILD.bazel
  pkg/virt-controller/watch/drain/disruptionbudget/BUILD.bazel
  pkg/virt-launcher/virtwrap/device/BUILD.bazel
  pkg/virt-launcher/virtwrap/device/sriov/BUILD.bazel
  pkg/virtctl/BUILD.bazel
  pkg/virtctl/expose/BUILD.bazel
  pkg/virtctl/imageupload/BUILD.bazel
  pkg/virtctl/pause/BUILD.bazel
  pkg/virtctl/vm/BUILD.bazel
  tests/BUILD.bazel
  vendor/github.com/opencontainers/runc/libcontainer/configs/BUILD.bazel
  vendor/github.com/prometheus/client_golang/prometheus/BUILD.bazel
  vendor/github.com/u-root/u-root/pkg/rand/BUILD.bazel
  vendor/github.com/vishvananda/netlink/BUILD.bazel
Labels: approved, dco-signoff: yes, lgtm, release-note, size/L

#5194 Fix issues impacting KubeVirt update test
  pkg/virt-handler/vm.go
  pkg/virt-handler/vm_test.go
  pkg/virt-launcher/notify-client/client.go
  tests/BUILD.bazel
  tests/operator_test.go
Labels: approved, dco-signoff: yes, lgtm, release-blocker/master, release-note-none, size/L

#5287 Revert update Go version to v1.14.14
  BUILD.bazel
  WORKSPACE
  hack/builder/Dockerfile
  hack/dockerized
  pkg/certificates/BUILD.bazel
  pkg/hooks/BUILD.bazel
  pkg/util/openapi/BUILD.bazel
  pkg/virt-api/webhooks/BUILD.bazel
  pkg/virt-controller/watch/drain/disruptionbudget/BUILD.bazel
  pkg/virt-launcher/virtwrap/device/BUILD.bazel
  pkg/virt-launcher/virtwrap/device/sriov/BUILD.bazel
  pkg/virtctl/BUILD.bazel
  pkg/virtctl/expose/BUILD.bazel
  pkg/virtctl/imageupload/BUILD.bazel
  pkg/virtctl/pause/BUILD.bazel
  pkg/virtctl/vm/BUILD.bazel
  tests/BUILD.bazel
  vendor/github.com/opencontainers/runc/libcontainer/configs/BUILD.bazel
  vendor/github.com/prometheus/client_golang/prometheus/BUILD.bazel
  vendor/github.com/u-root/u-root/pkg/rand/BUILD.bazel
  vendor/github.com/vishvananda/netlink/BUILD.bazel
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M

#5166 Check error before logging
  pkg/virt-launcher/virtwrap/cli/libvirt.go
  pkg/virt-launcher/virtwrap/manager.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#5212 Mark storage tests with owner:sig-storage
  automation/test.sh
  tests/BUILD.bazel
  tests/storage/BUILD.bazel
  tests/storage/datavolume.go
  tests/storage/imageupload.go
  tests/storage/restore.go
  tests/storage/snapshot.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M

#5183 Added supported values for v1.Disk cache mode in API document
  api/openapi-spec/swagger.json
  pkg/virt-operator/resource/generate/components/validations_generated.go
  staging/src/kubevirt.io/client-go/api/v1/openapi_generated.go
  staging/src/kubevirt.io/client-go/api/v1/schema.go
  staging/src/kubevirt.io/client-go/api/v1/schema_swagger_generated.go
  staging/src/kubevirt.io/client-go/apis/snapshot/v1alpha1/openapi_generated.go
Labels: approved, dco-signoff: yes, kind/api-change, lgtm, ok-to-test, release-note-none, size/S

#5289 Publish the CA bundle everywhere before rolling out new certificates from a new CA
  pkg/virt-operator/resource/apply/core.go
  pkg/virt-operator/resource/apply/reconcile.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M

#5263 Bazel test args
  Makefile
  hack/bazel-test.sh
  pkg/hooks/manager.go
  pkg/hooks/manager_test.go
  pkg/virt-handler/hotplug-disk/mount_test.go
  pkg/virt-launcher/BUILD.bazel
  pkg/virt-launcher/monitor_test.go
  pkg/virt-launcher/virtwrap/cli/libvirt.go
  pkg/virt-launcher/virtwrap/cli/libvirt_test.go
  pkg/watchdog/watchdog.go
  pkg/watchdog/watchdog_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/L

#5089 Add alert for high memory utilization
  hack/prom-rule-ci/prom-rules-tests.yaml
  pkg/virt-operator/resource/generate/components/crds.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M

#5189 Move test_id:1539 out of quarantine
  tests/network/vmi_networking.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#5121 pkg, cleanup: Remove unused parameters
  pkg/controller/controller_ref_manager.go
  pkg/middleware/BUILD.bazel
  pkg/middleware/middleware.go
  pkg/middleware/middleware_test.go
  pkg/monitoring/vms/prometheus/collector_test.go
  pkg/monitoring/vms/prometheus/prometheus.go
  pkg/util/cluster/cluster.go
  pkg/virt-api/webhooks/validating-webhook/admitters/vmi-create-admitter.go
  pkg/virt-api/webhooks/validating-webhook/admitters/vms-admitter.go
  pkg/virt-controller/watch/drain/disruptionbudget/disruptionbudget_test.go
  pkg/virt-controller/watch/migration.go
  pkg/virt-controller/watch/replicaset.go
  pkg/virt-handler/hotplug-disk/mount.go
  pkg/virt-handler/hotplug-disk/mount_test.go
  pkg/virt-handler/vm.go
  pkg/virt-launcher/virtwrap/converter/converter.go
  pkg/virt-launcher/virtwrap/converter/converter_test.go
  pkg/virt-launcher/virtwrap/converter/network.go
  pkg/virt-operator/kubevirt.go
  pkg/virt-operator/kubevirt_test.go
  pkg/virt-operator/resource/apply/delete.go
  pkg/virt-operator/resource/generate/install/strategy.go
  pkg/virt-operator/resource/generate/rbac/cluster.go
  pkg/virt-operator/resource/generate/rbac/operator.go
  pkg/virtctl/console/console.go
  pkg/virtctl/expose/expose.go
  pkg/virtctl/imageupload/imageupload.go
  pkg/virtctl/pause/pause.go
  pkg/virtctl/version/version.go
  pkg/virtctl/vm/vm.go
  tests/utils.go
  tests/vmi_configuration_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/L

#5305 Require all capabilities for virtioFS
  go.mod
  pkg/virt-controller/services/template.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/S

#5092 Add missing events to hotplug
  pkg/virt-controller/watch/vmi.go
  pkg/virt-controller/watch/vmi_test.go
  pkg/virt-handler/vm.go
  pkg/virt-handler/vm_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/L

#5299 Quarantine flaky tests
  tests/console_test.go
  tests/infra_test.go
  tests/migration_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/S

#5312 Some unit tests appear to be more load sensitive than expected
  hack/bazel-test.sh
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#5308 Increase verbosity at selinux context run
  pkg/virt-handler/selinux/executor.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#5310 reconcile crd to desired state
  pkg/virt-operator/resource/apply/crds.go
  pkg/virt-operator/resource/apply/crds_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/L

#5276 Update VM and VMI in command line to make it more clear
  pkg/virtctl/vm/vm.go
Labels: approved, dco-signoff: yes, lgtm, ok-to-test, release-note-none, size/S

#5236 Add sig-compute owner string to relevant tests
  tests/access_test.go
  tests/config_test.go
  tests/console_test.go
  tests/credentials_test.go
  tests/infra_test.go
  tests/kubectl_test.go
  tests/kubevirt_configmap_test.go
  tests/migration_test.go
  tests/pausing_test.go
  tests/replicaset_test.go
  tests/security_features_test.go
  tests/storage/restore.go
  tests/subresource_api_test.go
  tests/version_test.go
  tests/virt_control_plane_test.go
  tests/vm_test.go
  tests/vm_watch_test.go
  tests/vmi_cloudinit_hook_sidecar_test.go
  tests/vmi_cloudinit_test.go
  tests/vmi_configuration_test.go
  tests/vmi_controller_test.go
  tests/vmi_gpu_test.go
  tests/vmi_headless_test.go
  tests/vmi_hook_sidecar_test.go
  tests/vmi_hostdev_test.go
  tests/vmi_ignition_test.go
  tests/vmi_lifecycle_test.go
  tests/vmi_monitoring_test.go
  tests/vmi_multiqueue_test.go
  tests/vmidefaults_test.go
  tests/vmipreset_test.go
  tests/vnc_test.go
  tests/windows_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M

#5303 Lift quarantine from 4621
  tests/storage/imageupload.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#5268 Move network probes tests to network package
  tests/BUILD.bazel
  tests/network/BUILD.bazel
  tests/network/probes.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#5300 webhooks: fix AdmissionReview responses
  pkg/util/webhooks/validating-webhooks/validating-webhook.go
  pkg/virt-api/webhooks/mutating-webhook/BUILD.bazel
  pkg/virt-api/webhooks/mutating-webhook/mutating-webhook.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/S

#5311 Add default value for the BlockMultiQueue parameter for API docu
  api/openapi-spec/swagger.json
  pkg/virt-operator/resource/generate/components/validations_generated.go
  staging/src/kubevirt.io/client-go/api/v1/openapi_generated.go
  staging/src/kubevirt.io/client-go/api/v1/schema.go
  staging/src/kubevirt.io/client-go/api/v1/schema_swagger_generated.go
  staging/src/kubevirt.io/client-go/apis/snapshot/v1alpha1/openapi_generated.go
Labels: approved, dco-signoff: yes, kind/api-change, lgtm, ok-to-test, release-note-none, size/S

#5022 Operator needs to create services before webhooks
  pkg/virt-operator/resource/apply/reconcile.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/S

#5301 set the mutatingwebhookconfiguration generation after create to avoid…
  pkg/virt-operator/resource/apply/admissionregistration.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#5302 network pacakge: minor cleanup
  pkg/virt-launcher/virtwrap/network/common.go
  pkg/virt-launcher/virtwrap/network/network.go
  pkg/virt-launcher/virtwrap/network/podinterface.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/S

#5321 Removes quarantine label from tests 1015 4643
  tests/storage_test.go
  tests/vm_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#5259 Prefetch cdi images for tests
  hack/cluster-build.sh
  hack/cluster-deploy.sh
  hack/prefetch-images.sh
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/L

#5278 Fix flaky virtiofs test to WFFC with data volume
  tests/storage/datavolume.go
  tests/storage_test.go
  tests/utils.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M

#5322 virtwrap: fix unit test flakyness
  pkg/virt-handler/cmd-client/client.go
  pkg/virt-launcher/virtwrap/manager.go
  pkg/virt-launcher/virtwrap/manager_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/L

#5333 Revert "reconcile crd to desired state"
  pkg/virt-operator/resource/apply/crds.go
  pkg/virt-operator/resource/apply/crds_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/L

#4916 Move node-labeller into kubevirt
  BUILD.bazel
  WORKSPACE
  api/openapi-spec/swagger.json
  cmd/virt-handler/BUILD.bazel
  cmd/virt-handler/virt-handler.go
  cmd/virt-launcher/BUILD.bazel
  cmd/virt-launcher/node-labeller/node-labeller.sh
  manifests/generated/kv-resource.yaml
  manifests/generated/operator-csv.yaml.in
  manifests/generated/rbac-operator.authorization.k8s.yaml.in
  pkg/virt-config/virt-config.go
  pkg/virt-controller/services/template.go
  pkg/virt-handler/device-manager/device_controller.go
  pkg/virt-handler/device-manager/device_controller_test.go
  pkg/virt-handler/node-labeller/BUILD.bazel
  pkg/virt-handler/node-labeller/cpu_plugin.go
  pkg/virt-handler/node-labeller/cpu_plugin_test.go
  pkg/virt-handler/node-labeller/kvm-caps-info-plugin.go
  pkg/virt-handler/node-labeller/model.go
  pkg/virt-handler/node-labeller/node_labeller.go
  pkg/virt-handler/node-labeller/node_labeller_suite_test.go
  pkg/virt-handler/node-labeller/node_labeller_test.go
  pkg/virt-handler/node-labeller/test-util.go
  pkg/virt-handler/node-labeller/util/BUILD.bazel
  pkg/virt-handler/node-labeller/util/util.go
  pkg/virt-operator/kubevirt_test.go
  pkg/virt-operator/resource/generate/components/deployments.go
  pkg/virt-operator/resource/generate/components/validations_generated.go
  pkg/virt-operator/resource/generate/install/strategy.go
  pkg/virt-operator/resource/generate/rbac/handler.go
  staging/src/kubevirt.io/client-go/api/v1/deepcopy_generated.go
  staging/src/kubevirt.io/client-go/api/v1/openapi_generated.go
  staging/src/kubevirt.io/client-go/api/v1/types.go
  staging/src/kubevirt.io/client-go/apis/snapshot/v1alpha1/openapi_generated.go
  tests/BUILD.bazel
  tests/infra_test.go
  tests/utils.go
  tests/vmi_configuration_test.go
  tests/vmi_lifecycle_test.go
Labels: approved, dco-signoff: yes, kind/api-change, kind/build-change, lgtm, release-note, size/XXL

#5315 Get test_id:1589 out of quarantine
  tests/console_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#5337 Revert "virtwrap: fix unit test flakyness"
  pkg/virt-handler/cmd-client/client.go
  pkg/virt-launcher/virtwrap/manager.go
  pkg/virt-launcher/virtwrap/manager_test.go
Labels: approved, dco-signoff: yes, lgtm, release-blocker/master, release-note-none, size/L

#5006 Add discard=unmap option
  pkg/handler-launcher-com/cmd/v1/cmd.pb.go
  pkg/handler-launcher-com/cmd/v1/cmd.proto
  pkg/util/types/pvc.go
  pkg/virt-handler/vm.go
  pkg/virt-launcher/virtwrap/api/schema.go
  pkg/virt-launcher/virtwrap/converter/converter.go
  pkg/virt-launcher/virtwrap/converter/converter_test.go
  pkg/virt-launcher/virtwrap/manager.go
  pkg/virt-launcher/virtwrap/manager_test.go
  tests/storage/datavolume.go
Labels: approved, dco-signoff: yes, lgtm, ok-to-test, release-note, size/L

#5338 Fix flaky secret update on "[test_id:4099] should be rotated when a new CA is created"
  tests/infra_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/S

#5282 tests, sriov: remove xfail
  docs/sriov.md
  tests/network/vmi_multus.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M

#5017 Update CRD API version to apiextensions.k8s.io/v1
  docs/devel/virtual-machine.md
  manifests/generated/kv-resource.yaml
  pkg/controller/BUILD.bazel
  pkg/controller/virtinformers.go
  pkg/testutils/BUILD.bazel
  pkg/testutils/mock_config.go
  pkg/virt-config/BUILD.bazel
  pkg/virt-config/config-map.go
  pkg/virt-controller/watch/BUILD.bazel
  pkg/virt-controller/watch/application_test.go
  pkg/virt-controller/watch/snapshot/BUILD.bazel
  pkg/virt-controller/watch/snapshot/snapshot_base.go
  pkg/virt-controller/watch/snapshot/snapshot_test.go
  pkg/virt-operator/BUILD.bazel
  pkg/virt-operator/kubevirt_test.go
  pkg/virt-operator/resource/apply/BUILD.bazel
  pkg/virt-operator/resource/apply/crds.go
  pkg/virt-operator/resource/apply/crds_test.go
  pkg/virt-operator/resource/apply/delete.go
  pkg/virt-operator/resource/apply/reconcile.go
  pkg/virt-operator/resource/generate/components/BUILD.bazel
  pkg/virt-operator/resource/generate/components/crds.go
  pkg/virt-operator/resource/generate/components/crds_test.go
  pkg/virt-operator/resource/generate/install/BUILD.bazel
  pkg/virt-operator/resource/generate/install/strategy.go
  pkg/virt-operator/resource/generate/install/strategy_test.go
  staging/src/kubevirt.io/client-go/api/v1/BUILD.bazel
  staging/src/kubevirt.io/client-go/api/v1/register.go
  staging/src/kubevirt.io/client-go/api/v1/types.go
  tests/BUILD.bazel
  tests/operator_test.go
  tests/storage/snapshot.go
  tests/utils.go
  tools/marketplace/helper/BUILD.bazel
  tools/marketplace/helper/bundleHelper.go
Labels: approved, dco-signoff: yes, kind/api-change, lgtm, ok-to-test, release-note-none, size/XXL

#5324 Add the possibility to set default feature gates
  Makefile
  hack/build-manifests.sh
  hack/generate.sh
  manifests/generated/kubevirt-cr.yaml.in
  pkg/virt-operator/resource/generate/components/crds.go
  tools/manifest-templator/manifest-templator.go
  tools/resource-generator/resource-generator.go
  tools/util/marshaller.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/M

#4907 Support cgroup v2
  cluster-up-sha.txt
  cluster-up/cluster/ephemeral-provider-common.sh
  cluster-up/cluster/k8s-1.20-cgroupsv2/README.md
  cluster-up/cluster/k8s-1.20-cgroupsv2/provider.sh
  cluster-up/cluster/kind-k8s-1.17/README.md
  cluster-up/cluster/kind-k8s-1.17/provider.sh
  cluster-up/cluster/kind-k8s-sriov-1.17.0/README.md
  cluster-up/cluster/kind-k8s-sriov-1.17.0/config_sriov.sh
  cluster-up/cluster/kind-k8s-sriov-1.17.0/provider.sh
  cluster-up/cluster/kind/common.sh
  cluster-up/hack/common.sh
  cluster-up/version.txt
  cmd/virt-handler/BUILD.bazel
  cmd/virt-handler/virt-handler.go
  hack/config-default.sh
  pkg/util/hardware/hw_utils.go
  pkg/virt-handler/BUILD.bazel
  pkg/virt-handler/cgroup/BUILD.bazel
  pkg/virt-handler/cgroup/cgroup.go
  pkg/virt-handler/cgroup/cgroup_suite_test.go
  pkg/virt-handler/cgroup/cgroup_test.go
  pkg/virt-handler/cgroup/generated_mock_cgroup.go
  pkg/virt-handler/device-manager/device_controller.go
  pkg/virt-handler/device-manager/device_controller_test.go
  pkg/virt-handler/device-manager/generic_device.go
  pkg/virt-handler/device-manager/generic_device_test.go
  pkg/virt-handler/device-manager/mediated_device_test.go
  pkg/virt-handler/device-manager/pci_device_test.go
  pkg/virt-handler/hotplug-disk/BUILD.bazel
  pkg/virt-handler/hotplug-disk/mount.go
  pkg/virt-handler/isolation/BUILD.bazel
  pkg/virt-handler/isolation/isolation.go
  pkg/virt-handler/isolation/isolation_test.go
  pkg/virt-handler/vm.go
  pkg/virt-launcher/virtwrap/util/BUILD.bazel
  pkg/virt-launcher/virtwrap/util/cpu_utils.go
  tests/vmi_configuration_test.go
  vendor/github.com/docker/go-units/BUILD.bazel
  vendor/github.com/docker/go-units/CONTRIBUTING.md
  vendor/github.com/docker/go-units/LICENSE
  vendor/github.com/docker/go-units/MAINTAINERS
  vendor/github.com/docker/go-units/README.md
  vendor/github.com/docker/go-units/circle.yml
  vendor/github.com/docker/go-units/duration.go
  vendor/github.com/docker/go-units/size.go
  vendor/github.com/docker/go-units/ulimit.go
  vendor/github.com/opencontainers/runc/libcontainer/cgroups/BUILD.bazel
  vendor/github.com/opencontainers/runc/libcontainer/cgroups/cgroups.go
  vendor/github.com/opencontainers/runc/libcontainer/cgroups/cgroups_unsupported.go
  vendor/github.com/opencontainers/runc/libcontainer/cgroups/stats.go
  vendor/github.com/opencontainers/runc/libcontainer/cgroups/utils.go
  vendor/github.com/opencontainers/runc/libcontainer/cgroups/v1_utils.go
  vendor/modules.txt
Labels: approved, dco-signoff: yes, kind/build-change, lgtm, release-note, size/XXL

#5230 virt-launcher, migration: Protect the setup using a lock, fix some missing operations and refactor the code
  pkg/virt-launcher/virtwrap/manager.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/L

#5242 migration admitter: prevent creation of duplicate migrations
  pkg/virt-api/api.go
  pkg/virt-api/webhooks/mutating-webhook/mutators/migration-create-mutator.go
  pkg/virt-api/webhooks/mutating-webhook/mutators/migration-create-mutator_test.go
  pkg/virt-api/webhooks/validating-webhook/admitters/migration-create-admitter.go
  pkg/virt-api/webhooks/validating-webhook/admitters/migration-create-admitter_test.go
  pkg/virt-api/webhooks/validating-webhook/admitters/migration-update-admitter.go
  pkg/virt-api/webhooks/validating-webhook/admitters/migration-update-admitter_test.go
  pkg/virt-api/webhooks/validating-webhook/validating-webhook.go
  pkg/virt-controller/watch/migration.go
  staging/src/kubevirt.io/client-go/api/v1/types.go
  tests/migration.go
  tests/migration_test.go
Labels: approved, dco-signoff: yes, kind/api-change, lgtm, release-note, size/L
