Repository kubevirt/kubevirt, pull requests merged in 2021-02, with the labels that each got.

#4571 Extend VMI count metric to include osinfo
  pkg/monitoring/vms/prometheus/prometheus.go
  pkg/monitoring/vms/prometheus/prometheus_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/L

#4722 virt-launcher: Move SRIOV handling to the sriov sub-package
  pkg/virt-launcher/virtwrap/BUILD.bazel
  pkg/virt-launcher/virtwrap/converter/BUILD.bazel
  pkg/virt-launcher/virtwrap/converter/converter.go
  pkg/virt-launcher/virtwrap/converter/converter_test.go
  pkg/virt-launcher/virtwrap/device/BUILD.bazel
  pkg/virt-launcher/virtwrap/device/device_suite_test.go
  pkg/virt-launcher/virtwrap/device/pciaddress.go
  pkg/virt-launcher/virtwrap/device/pciaddress_test.go
  pkg/virt-launcher/virtwrap/device/sriov/BUILD.bazel
  pkg/virt-launcher/virtwrap/device/sriov/hostdev.go
  pkg/virt-launcher/virtwrap/device/sriov/hostdev_test.go
  pkg/virt-launcher/virtwrap/device/sriov/pcipool.go
  pkg/virt-launcher/virtwrap/device/sriov/pcipool_test.go
  pkg/virt-launcher/virtwrap/device/sriov/sriov_suite_test.go
  pkg/virt-launcher/virtwrap/device/sriov/vmispec.go
  pkg/virt-launcher/virtwrap/manager.go
  pkg/virt-launcher/virtwrap/manager_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XXL

#4953 Launcher converter cleanup
  pkg/virt-launcher/virtwrap/converter/BUILD.bazel
  pkg/virt-launcher/virtwrap/converter/converter.go
  pkg/virt-launcher/virtwrap/converter/converter_suite_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M

#4949 [virt-launcher]: Issue an error for disk with DedicatedIOThread and SATA bus
  pkg/virt-api/webhooks/validating-webhook/admitters/vmi-create-admitter.go
  pkg/virt-api/webhooks/validating-webhook/admitters/vmi-create-admitter_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M

#4940 [fix] allow permittedHostDevices to support both upper and lowercase letters in the device ID
  pkg/virt-handler/device-manager/common.go
  pkg/virt-handler/device-manager/device_controller.go
  pkg/virt-handler/device-manager/pci_device_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/S

#4880 snapshot/restore documentation
  docs/snapshot-restore.md
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M

#4937 tests: fix flakyness on timezone test
  tests/vmi_configuration_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#4960 tests: temporarily disabling couple of extremely flaky test
  tests/storage_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#4840 Generate K8s events on IO errors
  cmd/virt-launcher/virt-launcher.go
  pkg/virt-launcher/notify-client/BUILD.bazel
  pkg/virt-launcher/notify-client/client.go
  pkg/virt-launcher/notify-client/notify_test.go
  pkg/virt-launcher/virtwrap/cli/generated_mock_libvirt.go
  pkg/virt-launcher/virtwrap/cli/libvirt.go
  pkg/virt-launcher/virtwrap/converter/converter.go
  pkg/virt-launcher/virtwrap/converter/converter_test.go
  pkg/virt-launcher/virtwrap/manager_test.go
Labels: approved, dco-signoff: yes, lgtm, ok-to-test, release-note, size/L

#4935 Refactor vmi create admitter
  pkg/virt-api/webhooks/validating-webhook/admitters/vmi-create-admitter.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XXL

#4957 Don't retry jobs that are expected to fail
  tests/network/services.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/S

#4920 Fix k8s reporter audit / dmsg log collection
  tests/reporter/kubernetes.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#4967 change the image pull policy for the NFS test pod to IfNotPresent
  tests/framework/storage/nfs.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#4883 Fix bug enabling libvirt debug logs if debugLogs label key exists
  pkg/virt-controller/services/template.go
  pkg/virt-controller/services/template_test.go
  pkg/virt-launcher/virtwrap/util/libvirt_helper.go
Labels: approved, dco-signoff: yes, lgtm, needs-ok-to-test, release-note, size/M

#4740 Refactor network.PodCacheInterface marshalling
  cmd/virt-handler/BUILD.bazel
  cmd/virt-handler/virt-handler.go
  pkg/util/util.go
  pkg/virt-handler/BUILD.bazel
  pkg/virt-handler/vm.go
  pkg/virt-handler/vm_test.go
  pkg/virt-launcher/virtwrap/network/BUILD.bazel
  pkg/virt-launcher/virtwrap/network/common.go
  pkg/virt-launcher/virtwrap/network/common_test.go
  pkg/virt-launcher/virtwrap/network/generated_mock_infocache.go
  pkg/virt-launcher/virtwrap/network/infocache.go
  pkg/virt-launcher/virtwrap/network/network.go
  pkg/virt-launcher/virtwrap/network/podinterface.go
  pkg/virt-launcher/virtwrap/network/podinterface_test.go
Labels: approved, dco-signoff: yes, kind/build-change, lgtm, release-note-none, size/L

#4736 ephemeral-disk-utils: add few harmless tests and rename RemoveFile
  pkg/cloud-init/cloud-init.go
  pkg/ephemeral-disk-utils/BUILD.bazel
  pkg/ephemeral-disk-utils/utils.go
  pkg/ephemeral-disk-utils/utils_suite_test.go
  pkg/ephemeral-disk-utils/utils_test.go
  pkg/virt-handler/vm.go
  pkg/watchdog/watchdog.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/L

#4890 Add CoreWeave to adopters
  ADOPTERS.md
Labels: approved, dco-signoff: no, lgtm, needs-ok-to-test, release-note-none, size/XS

#4552 keep original pod ip on a dummy interface
  pkg/util/sysctl/sysctl.go
  pkg/virt-launcher/virtwrap/network/common.go
  pkg/virt-launcher/virtwrap/network/generated_mock_common.go
  pkg/virt-launcher/virtwrap/network/podinterface.go
  pkg/virt-launcher/virtwrap/network/podinterface_test.go
  tests/utils.go
  tests/vmi_lifecycle_test.go
  tests/vmi_multus_test.go
  tests/vmi_networking_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/L

#4948 automation, Remove unneeded build repetitions
  automation/test.sh
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/S

#4985 Fix gpg download url for fedora keys
  repo.yaml
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#4989 [SonarCloud]: Create constant to avoid string duplication
  pkg/controller/expectations.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/S

#4983 WORKSPACE: update image references to use quay instead of docker hub
  WORKSPACE
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M

#4927 XML marshal/unmarshal for user defined aliases of devices of a domain
  pkg/virt-handler/vm.go
  pkg/virt-handler/vm_test.go
  pkg/virt-launcher/virtwrap/agent-poller/agent_parser.go
  pkg/virt-launcher/virtwrap/agent-poller/agent_parser_test.go
  pkg/virt-launcher/virtwrap/api/deepcopy_generated.go
  pkg/virt-launcher/virtwrap/api/schema.go
  pkg/virt-launcher/virtwrap/api/schema_test.go
  pkg/virt-launcher/virtwrap/converter/converter.go
  pkg/virt-launcher/virtwrap/converter/converter_test.go
  pkg/virt-launcher/virtwrap/manager.go
  pkg/virt-launcher/virtwrap/manager_test.go
  pkg/virt-launcher/virtwrap/network/podinterface.go
  pkg/virt-launcher/virtwrap/network/podinterface_test.go
  tests/vmi_configuration_test.go
  tests/vmi_iothreads_test.go
Labels: approved, dco-signoff: yes, lgtm, ok-to-test, release-note, size/L

#4849 Selinux exec context refactor
  pkg/virt-handler/selinux/BUILD.bazel
  pkg/virt-handler/selinux/context_executor.go
  pkg/virt-launcher/virtwrap/network/BUILD.bazel
  pkg/virt-launcher/virtwrap/network/common.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/L

#5009 [release-0.36] XML marshal/unmarshal for user defined aliases of devices of a domain
  pkg/virt-handler/vm.go
  pkg/virt-handler/vm_test.go
  pkg/virt-launcher/virtwrap/agent-poller/agent_parser.go
  pkg/virt-launcher/virtwrap/agent-poller/agent_parser_test.go
  pkg/virt-launcher/virtwrap/api/deepcopy_generated.go
  pkg/virt-launcher/virtwrap/api/schema.go
  pkg/virt-launcher/virtwrap/api/schema_test.go
  pkg/virt-launcher/virtwrap/converter/converter.go
  pkg/virt-launcher/virtwrap/converter/converter_test.go
  pkg/virt-launcher/virtwrap/manager.go
  pkg/virt-launcher/virtwrap/manager_test.go
  pkg/virt-launcher/virtwrap/network/podinterface.go
  pkg/virt-launcher/virtwrap/network/podinterface_test.go
  tests/vmi_configuration_test.go
  tests/vmi_iothreads_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/L

#4972 allow disabling pvspinlock to support older guests kernels
  api/openapi-spec/swagger.json
  pkg/virt-launcher/virtwrap/api/deepcopy_generated.go
  pkg/virt-launcher/virtwrap/api/schema.go
  pkg/virt-launcher/virtwrap/api/schema_test.go
  pkg/virt-launcher/virtwrap/converter/converter.go
  pkg/virt-launcher/virtwrap/converter/converter_test.go
  pkg/virt-operator/resource/generate/components/validations_generated.go
  staging/src/kubevirt.io/client-go/api/v1/deepcopy_generated.go
  staging/src/kubevirt.io/client-go/api/v1/openapi_generated.go
  staging/src/kubevirt.io/client-go/api/v1/schema.go
  staging/src/kubevirt.io/client-go/api/v1/schema_swagger_generated.go
  staging/src/kubevirt.io/client-go/api/v1/schema_test.go
  staging/src/kubevirt.io/client-go/api/v1/zz_generated.defaults.go
  staging/src/kubevirt.io/client-go/apis/snapshot/v1alpha1/openapi_generated.go
Labels: approved, dco-signoff: yes, kind/api-change, lgtm, release-note, size/L

#4988 [SonarCloud] Create constant to avoid string duplication
  cmd/example-hook-sidecar/smbios.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/S

#4984 Patches generic match
  api/openapi-spec/swagger.json
  manifests/generated/kv-resource.yaml
  pkg/virt-operator/resource/apply/patches.go
  pkg/virt-operator/resource/apply/patches_test.go
  pkg/virt-operator/resource/generate/components/validations_generated.go
  staging/src/kubevirt.io/client-go/api/v1/openapi_generated.go
  staging/src/kubevirt.io/client-go/api/v1/types.go
  staging/src/kubevirt.io/client-go/apis/snapshot/v1alpha1/openapi_generated.go
Labels: approved, dco-signoff: yes, kind/api-change, lgtm, release-note, size/M

#4987 [SonarCloud]: Create constant to avoid string duplication
  pkg/virt-api/api.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M

#4934 Refactor pod selinux context alignment
  pkg/virt-controller/services/template.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M

#4982 Support extracting metadata for transients domains
  pkg/virt-launcher/notify-client/notify_test.go
  pkg/virt-launcher/virtwrap/cli/generated_mock_libvirt.go
  pkg/virt-launcher/virtwrap/cli/libvirt.go
  pkg/virt-launcher/virtwrap/manager_test.go
  pkg/virt-launcher/virtwrap/util/BUILD.bazel
  pkg/virt-launcher/virtwrap/util/libvirt_helper.go
  pkg/virt-launcher/virtwrap/util/libvirt_helper_test.go
  tests/migration_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/L

#5003 rename api.proto files in pkg/hooks to api_*.proto due to protobuf wa…z
  hack/generate.sh
  pkg/hooks/info/BUILD.bazel
  pkg/hooks/info/api_info.pb.go
  pkg/hooks/info/api_info.proto
  pkg/hooks/v1alpha1/BUILD.bazel
  pkg/hooks/v1alpha1/api_v1alpha1.pb.go
  pkg/hooks/v1alpha1/api_v1alpha1.proto
  pkg/hooks/v1alpha2/BUILD.bazel
  pkg/hooks/v1alpha2/api_v1alpha2.pb.go
  pkg/hooks/v1alpha2/api_v1alpha2.proto
Labels: approved, dco-signoff: yes, lgtm, ok-to-test, release-note-none, size/L

#4964 Fix vmi created with pod masq on calico cannot be accessed
  pkg/util/sysctl/sysctl.go
  pkg/virt-launcher/virtwrap/network/common.go
  pkg/virt-launcher/virtwrap/network/generated_mock_common.go
  pkg/virt-launcher/virtwrap/network/podinterface.go
  pkg/virt-launcher/virtwrap/network/podinterface_test.go
Labels: approved, dco-signoff: yes, lgtm, ok-to-test, release-note-none, size/S

#4489 Do not create Host Disks for Virtio-FS PVCs
  pkg/host-disk/host-disk.go
  pkg/host-disk/host-disk_test.go
  tests/storage_test.go
Labels: approved, dco-signoff: yes, lgtm, ok-to-test, release-note, size/M

#4966 Prevent virtctl file double-close on successful upload
  pkg/virtctl/imageupload/imageupload.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/XS

#5018 Increase mem limit on attachmentPod to prevent OOM
  pkg/virt-controller/services/template.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#4947 automation, Use cluster-sync instead its partial targets
  automation/test.sh
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#5014 container disk: log error reason when the disk is not ready
  pkg/virt-handler/container-disk/mount.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#4814 Fix typo
  tests/vmi_multus_test.go
Labels: approved, dco-signoff: yes, lgtm, ok-to-test, release-note-none, size/XS

#4917 Support enabling QEMU SeaBios debug logs virt-launcher log verbosity
  cmd/virt-launcher/virt-launcher.go
  pkg/virt-launcher/virtwrap/access-credentials/access_credentials_test.go
  pkg/virt-launcher/virtwrap/converter/BUILD.bazel
  pkg/virt-launcher/virtwrap/converter/converter.go
  pkg/virt-launcher/virtwrap/converter/converter_test.go
  pkg/virt-launcher/virtwrap/manager.go
  pkg/virt-launcher/virtwrap/manager_test.go
  tests/vmi_lifecycle_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/L

#4874 Add feature-gate for SRIOV Live Migration feature
  pkg/virt-config/config_test.go
  pkg/virt-config/feature-gates.go
  pkg/virt-controller/services/BUILD.bazel
  pkg/virt-controller/services/template.go
  pkg/virt-controller/services/template_test.go
  pkg/virt-handler/vm.go
  pkg/virt-handler/vm_test.go
  pkg/virt-operator/resource/generate/components/scc.go
  tests/vmi_multus_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/L

#5029 Bump kubevirtci
  cluster-up-sha.txt
  cluster-up/cluster/k8s-1.17/dev-guide.md
  cluster-up/cluster/k8s-1.18/dev-guide.md
  cluster-up/cluster/k8s-1.19/dev-guide.md
  cluster-up/cluster/k8s-1.20/dev-guide.md
  cluster-up/cluster/kind-k8s-sriov-1.17.0/README.md
  cluster-up/cluster/kind-k8s-sriov-1.17.0/provider.sh
  cluster-up/cluster/kind/common.sh
  cluster-up/hack/common.sh
  cluster-up/version.txt
  hack/config-default.sh
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/L

#5035 [flakey tests] add eventually to increase the robustness of vmi lifecycle tests
  tests/vmi_lifecycle_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/S

#4921 Add support for Sysprep in the API
  .gitignore
  api/openapi-spec/swagger.json
  cmd/virt-launcher/virt-launcher.go
  pkg/config/BUILD.bazel
  pkg/config/config.go
  pkg/config/sysprep.go
  pkg/config/sysprep_test.go
  pkg/virt-api/webhooks/validating-webhook/admitters/vmi-create-admitter.go
  pkg/virt-api/webhooks/validating-webhook/admitters/vmi-create-admitter_test.go
  pkg/virt-controller/services/template.go
  pkg/virt-controller/services/template_test.go
  pkg/virt-launcher/virtwrap/converter/converter.go
  pkg/virt-launcher/virtwrap/converter/converter_test.go
  pkg/virt-launcher/virtwrap/manager.go
  pkg/virt-operator/resource/generate/components/validations_generated.go
  staging/src/kubevirt.io/client-go/api/v1/deepcopy_generated.go
  staging/src/kubevirt.io/client-go/api/v1/openapi_generated.go
  staging/src/kubevirt.io/client-go/api/v1/schema.go
  staging/src/kubevirt.io/client-go/api/v1/schema_swagger_generated.go
  staging/src/kubevirt.io/client-go/apis/snapshot/v1alpha1/openapi_generated.go
Labels: approved, dco-signoff: yes, kind/api-change, lgtm, release-note, size/XL

#5026 virt-launcher: make nftables as the default
  pkg/virt-launcher/virtwrap/network/BUILD.bazel
  pkg/virt-launcher/virtwrap/network/common.go
  pkg/virt-launcher/virtwrap/network/common_test.go
  pkg/virt-launcher/virtwrap/network/generated_mock_common.go
  pkg/virt-launcher/virtwrap/network/podinterface.go
  pkg/virt-launcher/virtwrap/network/podinterface_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/L

#4886 WFFC support for hotplugging volumes
  pkg/virt-controller/services/template.go
  pkg/virt-controller/watch/vmi.go
  pkg/virt-controller/watch/vmi_test.go
  tests/datavolume_test.go
  tests/storage/hotplug.go
  tests/utils.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/XL

#4965 Refactored vm monitoring code
  docs/metrics.md
  pkg/monitoring/vms/prometheus/prometheus.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/L

#4686 Automated VMI Workload Component Updates
  api/openapi-spec/swagger.json
  docs/metrics.md
  hack/prom-rule-ci/rule-spec-dumper.go
  manifests/generated/kubevirt-cr.yaml.in
  manifests/generated/kv-resource.yaml
  manifests/generated/operator-csv.yaml.in
  manifests/generated/rbac-operator.authorization.k8s.yaml.in
  pkg/controller/controller.go
  pkg/util/migrations/migrations.go
  pkg/util/status/status.go
  pkg/virt-controller/services/template.go
  pkg/virt-controller/watch/BUILD.bazel
  pkg/virt-controller/watch/application.go
  pkg/virt-controller/watch/drain/evacuation/evacuation.go
  pkg/virt-controller/watch/migration.go
  pkg/virt-controller/watch/vmi.go
  pkg/virt-controller/watch/vmi_test.go
  pkg/virt-controller/watch/workload-updater/BUILD.bazel
  pkg/virt-controller/watch/workload-updater/workload-updater.go
  pkg/virt-controller/watch/workload-updater/workload-updater_suite_test.go
  pkg/virt-controller/watch/workload-updater/workload-updater_test.go
  pkg/virt-handler/vm.go
  pkg/virt-operator/kubevirt_test.go
  pkg/virt-operator/resource/generate/components/crds.go
  pkg/virt-operator/resource/generate/components/validations_generated.go
  pkg/virt-operator/resource/generate/install/strategy.go
  pkg/virt-operator/resource/generate/rbac/controller.go
  pkg/virt-operator/util/config.go
  staging/src/kubevirt.io/client-go/api/v1/deepcopy_generated.go
  staging/src/kubevirt.io/client-go/api/v1/openapi_generated.go
  staging/src/kubevirt.io/client-go/api/v1/types.go
  staging/src/kubevirt.io/client-go/api/v1/types_swagger_generated.go
  staging/src/kubevirt.io/client-go/apis/snapshot/v1alpha1/openapi_generated.go
  tests/operator_test.go
Labels: approved, dco-signoff: yes, kind/api-change, lgtm, release-note, size/XXL

#4993 tests: refactor expect in cidrToIP fcn in vmi_multus_test
  tests/vmi_multus_test.go
Labels: approved, dco-signoff: yes, lgtm, ok-to-test, release-note-none, size/M

#5067 [release-0.34] XML marshal/unmarshal for user defined aliases of devices of a domain
  pkg/virt-handler/vm.go
  pkg/virt-handler/vm_test.go
  pkg/virt-launcher/virtwrap/agent-poller/agent_parser.go
  pkg/virt-launcher/virtwrap/agent-poller/agent_poller_test.go
  pkg/virt-launcher/virtwrap/api/converter.go
  pkg/virt-launcher/virtwrap/api/deepcopy_generated.go
  pkg/virt-launcher/virtwrap/api/schema.go
  pkg/virt-launcher/virtwrap/api/schema_test.go
  pkg/virt-launcher/virtwrap/manager.go
  pkg/virt-launcher/virtwrap/network/podinterface.go
  pkg/virt-launcher/virtwrap/network/podinterface_test.go
  tests/vmi_configuration_test.go
  tests/vmi_iothreads_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/L

#4952 add event for virt-handler missing
  manifests/generated/operator-csv.yaml.in
  manifests/generated/rbac-operator.authorization.k8s.yaml.in
  pkg/util/lookup/BUILD.bazel
  pkg/util/lookup/lookup.go
  pkg/util/lookup/lookup_suite_test.go
  pkg/util/lookup/lookup_test.go
  pkg/virt-controller/watch/BUILD.bazel
  pkg/virt-controller/watch/node.go
  pkg/virt-controller/watch/node_test.go
  pkg/virt-operator/resource/generate/rbac/controller.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/XL

#5066 remove crd-rest-coverage package from KubeVirt
  go.mod
  go.sum
  tests/BUILD.bazel
  tests/utils.go
  vendor/github.com/mfranczy/crd-rest-coverage/LICENSE
  vendor/github.com/mfranczy/crd-rest-coverage/pkg/analysis/BUILD.bazel
  vendor/github.com/mfranczy/crd-rest-coverage/pkg/analysis/swagger_analysis.go
  vendor/github.com/mfranczy/crd-rest-coverage/pkg/report/BUILD.bazel
  vendor/github.com/mfranczy/crd-rest-coverage/pkg/report/report.go
  vendor/github.com/mfranczy/crd-rest-coverage/pkg/stats/BUILD.bazel
  vendor/github.com/mfranczy/crd-rest-coverage/pkg/stats/types.go
  vendor/k8s.io/apiserver/LICENSE
  vendor/k8s.io/apiserver/pkg/apis/audit/BUILD.bazel
  vendor/k8s.io/apiserver/pkg/apis/audit/OWNERS
  vendor/k8s.io/apiserver/pkg/apis/audit/doc.go
  vendor/k8s.io/apiserver/pkg/apis/audit/helpers.go
  vendor/k8s.io/apiserver/pkg/apis/audit/register.go
  vendor/k8s.io/apiserver/pkg/apis/audit/types.go
  vendor/k8s.io/apiserver/pkg/apis/audit/v1/BUILD.bazel
  vendor/k8s.io/apiserver/pkg/apis/audit/v1/doc.go
  vendor/k8s.io/apiserver/pkg/apis/audit/v1/generated.pb.go
  vendor/k8s.io/apiserver/pkg/apis/audit/v1/generated.proto
  vendor/k8s.io/apiserver/pkg/apis/audit/v1/register.go
  vendor/k8s.io/apiserver/pkg/apis/audit/v1/types.go
  vendor/k8s.io/apiserver/pkg/apis/audit/v1/zz_generated.conversion.go
  vendor/k8s.io/apiserver/pkg/apis/audit/v1/zz_generated.deepcopy.go
  vendor/k8s.io/apiserver/pkg/apis/audit/v1/zz_generated.defaults.go
  vendor/k8s.io/apiserver/pkg/apis/audit/zz_generated.deepcopy.go
  vendor/modules.txt
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XXL

#5010 Migrate to persistent target domains instead of transient ones
  Makefile
  pkg/virt-launcher/virtwrap/manager.go
  pkg/virt-launcher/virtwrap/manager_test.go
  tests/migration_test.go
  tests/utils.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/L

#4963 Allow kubevirt:edit role to get,list kubevirts
  manifests/generated/operator-csv.yaml.in
  manifests/generated/rbac-operator.authorization.k8s.yaml.in
  pkg/virt-operator/resource/generate/rbac/cluster.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/S

#5060 Virt-handler should only be informed of VMIs scheduled on virt-handler nodes
  cmd/virt-handler/BUILD.bazel
  cmd/virt-handler/virt-handler.go
  pkg/controller/virtinformers.go
  pkg/virt-handler/vm.go
Labels: approved, dco-signoff: yes, kind/build-change, lgtm, release-note-none, size/L

#4936 Refactor template pod annotations
  pkg/virt-controller/services/BUILD.bazel
  pkg/virt-controller/services/multus_annotations.go
  pkg/virt-controller/services/multus_annotations_test.go
  pkg/virt-controller/services/template.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/L

#4802 make `make gosec` output slightly easier to find
  hack/gosec.sh
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/S

#5075 Run service clients as non privileged pods
  tests/migration_test.go
  tests/pod_servers.go
  tests/utils.go
  tests/vmi_lifecycle_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M

#5019 Remove all Fedora Guest RPMs
  BUILD.bazel
  WORKSPACE
  containerimages/BUILD.bazel
  hack/rpm-deps.sh
  images/cdi-http-import-server/entrypoint.sh
  rpm/BUILD.bazel
  tests/containerdisk/containerdisk.go
  tests/credentials_test.go
  tests/framework/storage/nfs.go
  tests/libvmi/factory.go
  tests/migration_test.go
  tests/network/primary_pod_network.go
  tests/storage_test.go
  tests/utils.go
  tests/vmi_configuration_test.go
  tests/vmi_hostdev_test.go
  tests/vmi_multiqueue_test.go
  tests/vmi_multus_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XL

#5078 [release-0.34] Migrate to persistent target domains instead of transient ones
  pkg/virt-launcher/virtwrap/manager.go
  pkg/virt-launcher/virtwrap/manager_test.go
  tests/migration_test.go
  tests/utils.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/L

#5032 Increase wait timeout for VMI deletion in tests/vmi_configuration_test.go
  tests/vmi_configuration_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#5079 docs: Fix links in update-dependencies.md
  docs/updating-dependencies.md
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/S

#5094 Snapshot doc updates from QE review
  docs/snapshot-restore.md
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS
