Repository kubevirt/kubevirt, pull requests merged in 2022-10, with the labels that each got.

#8523 expose,e2e: remove tests checking svc after vm removed
  tests/network/expose.go
Labels: size/M, sig/network, release-note-none, lgtm, approved, dco-signoff: yes

#8552 Test: Use correct namespace in 3188 test
  tests/storage/datavolume.go
Labels: size/XS, release-note-none, lgtm, approved, dco-signoff: yes

#8532 virt-api: Set default machinetype after preference kind
  pkg/virt-api/webhooks/mutating-webhook/mutators/vm-mutator.go
  pkg/virt-api/webhooks/mutating-webhook/mutators/vm-mutator_test.go
Labels: size/M, release-note-none, lgtm, approved, dco-signoff: yes, area/instancetype

#8181 Test: Remove unnecessary error
  tests/libnet/cloudinit.go
  tests/libvmi/network.go
  tests/network/primary_pod_network.go
  tests/network/sriov.go
  tests/network/vmi_istio.go
  tests/network/vmi_networking.go
  tests/utils.go
Labels: size/M, sig/network, release-note-none, lgtm, approved, dco-signoff: yes

#8513 Improve error handling in virtctl image-upload
  pkg/virtctl/imageupload/BUILD.bazel
  pkg/virtctl/imageupload/imageupload.go
  pkg/virtctl/imageupload/imageupload_test.go
  tests/storage/imageupload.go
Labels: size/L, release-note, lgtm, approved, dco-signoff: yes

#8545 [e2e tests]: Address flake in test_id:4643
  tests/storage/datavolume.go
Labels: size/XS, release-note-none, lgtm, approved, dco-signoff: yes

#8509 [flaky] Snapshot test case - improve test reports and cleanup
  tests/reporter/kubernetes.go
  tests/storage/snapshot.go
  tests/testsuite/namespace.go
Labels: size/L, release-note-none, lgtm, approved, dco-signoff: yes

#8402 virt-launcher: use our custom SELinux type only when necessary
  cmd/virt-handler/virt_launcher.cil
  pkg/util/util.go
  pkg/virt-config/virt-config.go
  pkg/virt-controller/services/template.go
  pkg/virt-controller/services/template_test.go
  tests/libvmi/vmi.go
  tests/network/vmi_passt.go
  tests/storage/storage.go
  tests/vmi_configuration_test.go
Labels: size/L, sig/network, release-note, lgtm, approved, dco-signoff: yes

#7772 virt-launcher: SELinux policy: cleanup the rules and add comments
  cmd/virt-handler/virt_launcher.cil
Labels: size/S, release-note, lgtm, approved, dco-signoff: yes

#7918 Add alerts for VMs unhealthy states
  docs/metrics.md
  hack/prom-rule-ci/prom-rules-tests.yaml
  pkg/monitoring/vmstats/BUILD.bazel
  pkg/monitoring/vmstats/collector.go
  pkg/monitoring/vmstats/collector_test.go
  pkg/monitoring/vmstats/vmstats_suite_test.go
  pkg/virt-controller/watch/BUILD.bazel
  pkg/virt-controller/watch/application.go
  pkg/virt-operator/resource/generate/components/prometheus.go
  tests/monitoring/monitoring.go
  tools/doc-generator/BUILD.bazel
  tools/doc-generator/doc-generator.go
  tools/doc-generator/fakeVMCollector.go
Labels: size/XL, release-note, lgtm, approved, dco-signoff: yes, area/monitoring

#8573 [release-0.49] Revert "Set SeccompProfile"
  manifests/generated/operator-csv.yaml.in
  pkg/virt-operator/resource/generate/components/deployments.go
Labels: size/M, release-note-none, lgtm, approved, dco-signoff: yes

#8571 Fix the CPU set migration test case.
  pkg/virt-launcher/virtwrap/manager_test.go
Labels: size/S, release-note-none, lgtm, approved, ok-to-test, dco-signoff: yes

#8568 Fix bug in restore-controller when creating a restore PVC with both dataSource and dataSourceRef
  pkg/storage/snapshot/restore.go
  pkg/storage/snapshot/restore_test.go
  tests/storage/restore.go
Labels: size/L, release-note-none, lgtm, approved, dco-signoff: yes

#8499 Simplify handling of cluster URIs from kubeconfig
  staging/src/kubevirt.io/client-go/kubecli/guestfs.go
  staging/src/kubevirt.io/client-go/kubecli/instancetype.go
  staging/src/kubevirt.io/client-go/kubecli/kv_test.go
  staging/src/kubevirt.io/client-go/kubecli/migration_test.go
  staging/src/kubevirt.io/client-go/kubecli/migrationpolicy_test.go
  staging/src/kubevirt.io/client-go/kubecli/profiler.go
  staging/src/kubevirt.io/client-go/kubecli/replicaset_test.go
  staging/src/kubevirt.io/client-go/kubecli/version.go
  staging/src/kubevirt.io/client-go/kubecli/version_test.go
  staging/src/kubevirt.io/client-go/kubecli/vm.go
  staging/src/kubevirt.io/client-go/kubecli/vm_test.go
  staging/src/kubevirt.io/client-go/kubecli/vmi.go
  staging/src/kubevirt.io/client-go/kubecli/vmi_test.go
  staging/src/kubevirt.io/client-go/kubecli/vmipreset_test.go
Labels: size/XL, release-note-none, lgtm, approved, dco-signoff: yes

#8238 Patching node set kubevirt.io/schedulable to false upon exiting heartbeat
  pkg/virt-handler/heartbeat/heartbeat.go
  pkg/virt-handler/heartbeat/heartbeat_test.go
  pkg/virt-handler/vm.go
Labels: size/M, sig/network, release-note-none, lgtm, approved, kind/build-change, dco-signoff: yes, area/monitoring

#8557 [release-0.49] Bump virtlogd memory requirement to 18Mi
  pkg/virt-controller/services/template.go
  pkg/virt-controller/services/template_test.go
  tests/vmi_configuration_test.go
Labels: size/M, release-note-none, lgtm, approved, dco-signoff: yes

#8535 Update CDI/CDI-API vendoring to get 1.55.0
  go.mod
  go.sum
  hack/dep-update.sh
  pkg/virt-operator/resource/apply/rbac_test.go
  staging/src/kubevirt.io/api/go.mod
  staging/src/kubevirt.io/api/go.sum
  staging/src/kubevirt.io/client-go/api/openapi_generated.go
  staging/src/kubevirt.io/client-go/go.mod
  staging/src/kubevirt.io/client-go/go.sum
  vendor/github.com/cespare/xxhash/v2/.travis.yml
  vendor/github.com/cespare/xxhash/v2/README.md
  vendor/github.com/cespare/xxhash/v2/xxhash.go
  vendor/github.com/cespare/xxhash/v2/xxhash_amd64.s
  vendor/github.com/cespare/xxhash/v2/xxhash_unsafe.go
  vendor/github.com/imdario/mergo/.travis.yml
  vendor/github.com/imdario/mergo/README.md
  vendor/github.com/imdario/mergo/merge.go
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourcemerge/BUILD.bazel
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourcemerge/apiextensions.go
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourcemerge/object_merger.go
  vendor/golang.org/x/oauth2/google/google.go
  vendor/golang.org/x/oauth2/google/internal/externalaccount/basecredentials.go
  vendor/golang.org/x/oauth2/google/internal/externalaccount/impersonate.go
  vendor/gopkg.in/yaml.v3/decode.go
  vendor/kubevirt.io/containerized-data-importer-api/pkg/apis/core/v1beta1/BUILD.bazel
  vendor/kubevirt.io/containerized-data-importer-api/pkg/apis/core/v1beta1/types.go
  vendor/kubevirt.io/containerized-data-importer-api/pkg/apis/core/v1beta1/types_swagger_generated.go
  vendor/kubevirt.io/containerized-data-importer-api/pkg/apis/core/v1beta1/zz_generated.deepcopy.go
  vendor/modules.txt
Labels: size/XXL, release-note-none, lgtm, approved, dco-signoff: yes

#8147 Return certificate chain for export cert
  pkg/certificates/triple/cert/cert.go
  pkg/storage/export/export/export_test.go
  pkg/storage/export/export/links.go
  tests/storage/export.go
Labels: size/L, release-note-none, lgtm, approved, dco-signoff: yes

#8572 Added test_id for probes.go
  tests/network/probes.go
Labels: sig/network, size/XS, release-note-none, lgtm, approved, dco-signoff: yes

#8521 Add TTL field for VMExport objects
  api/openapi-spec/swagger.json
  pkg/storage/export/export/export.go
  pkg/storage/export/export/export_test.go
  pkg/storage/export/export/pvc-source_test.go
  pkg/storage/export/export/vm-source_test.go
  pkg/storage/export/export/vmsnapshot-source_test.go
  pkg/virt-operator/resource/generate/components/validations_generated.go
  pkg/virtctl/vmexport/vmexport.go
  pkg/virtctl/vmexport/vmexport_test.go
  staging/src/kubevirt.io/api/export/v1alpha1/deepcopy_generated.go
  staging/src/kubevirt.io/api/export/v1alpha1/types.go
  staging/src/kubevirt.io/api/export/v1alpha1/types_swagger_generated.go
  staging/src/kubevirt.io/client-go/api/openapi_generated.go
  tests/storage/export.go
Labels: size/L, release-note, lgtm, approved, dco-signoff: yes

#8578 Passt unprivilege low ports release 0.58
  pkg/network/driver/common.go
  pkg/network/driver/generated_mock_common.go
  pkg/network/infraconfigurators/passt.go
  pkg/util/sysctl/sysctl.go
  tests/network/vmi_passt.go
Labels: size/M, sig/network, release-note, lgtm, approved, dco-signoff: yes

#8584 Bump kubevirtci with fix for CDI DV GC tests
  cluster-up-sha.txt
  cluster-up/cluster/kind-1.22-sriov/conformance.json
  cluster-up/cluster/kind-1.23-vgpu/conformance.json
  cluster-up/hack/common.sh
  cluster-up/version.txt
  hack/cluster-deploy.sh
  hack/config-default.sh
  tests/libstorage/datavolume.go
  tests/storage/datavolume.go
  tests/storage/snapshot.go
Labels: size/L, release-note-none, lgtm, approved, dco-signoff: yes

#8592 adding polarion test ids
  tests/infra_test.go
Labels: size/XS, release-note-none, lgtm, approved, ok-to-test, dco-signoff: yes

#8585 Add 0xFelix as reviewer
  OWNERS_ALIASES
Labels: size/XS, release-note-none, lgtm, approved, dco-signoff: yes

#8580 docs: add minimum container-selinux version
  docs/getting-started.md
Labels: size/XS, release-note-none, lgtm, approved, dco-signoff: yes

#8594 Use fgetxattr to get selinux labels
  cmd/virt-chroot/BUILD.bazel
  cmd/virt-chroot/selinux.go
Labels: size/M, release-note, lgtm, approved, ok-to-test, kind/build-change, dco-signoff: yes

#8598 Switch VMs with hugepages to use the container_t SELinux type
  cmd/virt-handler/virt_launcher.cil
  pkg/virt-controller/services/rendervolumes.go
  pkg/virt-controller/services/template.go
  pkg/virt-controller/services/template_test.go
Labels: size/M, release-note, lgtm, approved, dco-signoff: yes

#8029 hot plug disk feature is not working with kubletPodsDir changed.
  cmd/virt-handler/virt-handler.go
  pkg/hotplug-disk/hotplug-disk.go
  pkg/virt-handler/hotplug-disk/mount.go
  pkg/virt-handler/vm.go
  pkg/virt-handler/vm_test.go
Labels: size/S, release-note-none, lgtm, approved, ok-to-test, dco-signoff: yes

#8602 tests: ignore transient PSA warning events
  tests/utils.go
Labels: size/XS, release-note-none, lgtm, approved, dco-signoff: yes

#8596 [flaky] test 6838 should wait for VM to be updated
  tests/storage/snapshot.go
Labels: size/S, release-note-none, lgtm, approved, dco-signoff: yes

#8461 probes: Add liveness qemu-exec test probes IDs.
  tests/network/probes.go
Labels: sig/network, size/XS, release-note-none, lgtm, approved, ok-to-test, dco-signoff: yes

#8590 Fix the pre stop hook for disks-images-provider
  manifests/testing/disks-images-provider.yaml.in
Labels: size/XS, release-note-none, lgtm, approved, dco-signoff: yes

#8588 Point to the design proposal document in the contrib guide
  CONTRIBUTING.md
Labels: size/S, release-note-none, lgtm, approved, dco-signoff: yes

#8225 vmi_ignition_test: shorten and improve
  tests/vmi_ignition_test.go
Labels: size/M, release-note-none, lgtm, approved, dco-signoff: yes, sig/code-quality

#8601 Add lyarwood as reviewer
  OWNERS_ALIASES
Labels: size/XS, release-note-none, lgtm, approved, dco-signoff: yes

#8541 [sig-scale] add deletion percentiles to audit report after sig-scale tests
  tools/perfscale-audit/api/api.go
  tools/perfscale-audit/metric-client/metric-client.go
Labels: size/M, release-note-none, lgtm, approved, ok-to-test, dco-signoff: yes

#8614 Improve error handling when using fsfreeze with paused VMs
  cmd/virt-freezer/BUILD.bazel
  cmd/virt-freezer/main.go
  tests/storage/snapshot.go
Labels: size/M, release-note-none, lgtm, approved, kind/build-change, dco-signoff: yes

#8546 Add Vsock support to KubeVirt
  api/api-rule-violations-known.list
  api/api-rule-violations.list
  api/openapi-spec/swagger.json
  pkg/util/util.go
  pkg/virt-api/webhooks/validating-webhook/admitters/vmi-create-admitter.go
  pkg/virt-api/webhooks/validating-webhook/admitters/vmi-create-admitter_test.go
  pkg/virt-config/feature-gates.go
  pkg/virt-controller/services/BUILD.bazel
  pkg/virt-controller/services/renderresources.go
  pkg/virt-controller/services/template.go
  pkg/virt-controller/services/template_test.go
  pkg/virt-controller/watch/BUILD.bazel
  pkg/virt-controller/watch/vmi.go
  pkg/virt-controller/watch/vmi_test.go
  pkg/virt-controller/watch/vsock.go
  pkg/virt-controller/watch/vsock_test.go
  pkg/virt-handler/device-manager/device_controller.go
  pkg/virt-handler/vm.go
  pkg/virt-launcher/virtwrap/api/deepcopy_generated.go
  pkg/virt-launcher/virtwrap/api/schema.go
  pkg/virt-launcher/virtwrap/api/schema_test.go
  pkg/virt-launcher/virtwrap/converter/converter.go
  pkg/virt-launcher/virtwrap/converter/converter_test.go
  pkg/virt-operator/resource/generate/components/validations_generated.go
  staging/src/kubevirt.io/api/core/v1/deepcopy_generated.go
  staging/src/kubevirt.io/api/core/v1/schema.go
  staging/src/kubevirt.io/api/core/v1/schema_swagger_generated.go
  staging/src/kubevirt.io/api/core/v1/types.go
  staging/src/kubevirt.io/api/core/v1/types_swagger_generated.go
  staging/src/kubevirt.io/client-go/api/openapi_generated.go
  tests/BUILD.bazel
  tests/testsuite/kubevirtresource.go
  tests/vmi_vsock_test.go
Labels: size/XL, release-note, lgtm, approved, ok-to-test, dco-signoff: yes

#8616 fix regex for kind/api-change labels
  staging/src/kubevirt.io/api/OWNERS
Labels: size/XS, release-note-none, lgtm, approved, ok-to-test, dco-signoff: yes

#8543 Change the libdv.WithPVC to work with default values and options
  tests/libdv/BUILD.bazel
  tests/libdv/dv.go
  tests/migration_test.go
  tests/storage/datavolume.go
  tests/storage/export.go
  tests/storage/hotplug.go
  tests/storage/restore.go
  tests/storage/snapshot.go
  tests/storage/storage.go
  tests/utils.go
  tests/vmi_configuration_test.go
Labels: size/L, release-note-none, lgtm, approved, dco-signoff: yes, sig/code-quality

#8219 multi queue: Fix VMI creation in case non virtio interface present and multi vCPU
  pkg/instancetype/instancetype_test.go
  pkg/network/domainspec/domainspec_suite_test.go
  pkg/network/domainspec/generators_test.go
  pkg/network/infraconfigurators/bridge.go
  pkg/network/infraconfigurators/common.go
  pkg/network/infraconfigurators/masquerade.go
  pkg/network/setup/network_suite_test.go
  pkg/testutils/domain.go
  pkg/util/util.go
  pkg/virt-api/webhooks/validating-webhook/admitters/vmi-create-admitter.go
  pkg/virt-launcher/virtwrap/api/BUILD.bazel
  pkg/virt-launcher/virtwrap/api/schema_test.go
  pkg/virt-launcher/virtwrap/converter/converter.go
  pkg/virt-launcher/virtwrap/converter/converter_test.go
  pkg/virt-launcher/virtwrap/converter/network.go
  pkg/virt-launcher/virtwrap/converter/pci-placement.go
  staging/src/kubevirt.io/api/core/v1/schema.go
  staging/src/kubevirt.io/api/core/v1/types.go
  staging/src/kubevirt.io/client-go/api/schema_test.go
  tests/infra_test.go
  tests/instancetype_test.go
  tests/migration_test.go
  tests/vmi_configuration_test.go
  tests/vmi_multiqueue_test.go
  tools/vms-generator/utils/utils.go
Labels: size/L, sig/network, release-note-none, lgtm, approved, dco-signoff: yes

#8627 add gcc library for local build on Arm64
  bazel/toolchain/aarch64-none-linux-gnu/cc_toolchain_config.bzl
Labels: size/XS, release-note-none, lgtm, approved, dco-signoff: yes

#8647 [release-0.58] Backport 8521 'TTL field for VMExport objects'
  api/openapi-spec/swagger.json
  pkg/storage/export/export/export.go
  pkg/storage/export/export/export_test.go
  pkg/storage/export/export/pvc-source_test.go
  pkg/storage/export/export/vm-source_test.go
  pkg/storage/export/export/vmsnapshot-source_test.go
  pkg/virt-operator/resource/generate/components/validations_generated.go
  pkg/virtctl/vmexport/vmexport.go
  pkg/virtctl/vmexport/vmexport_test.go
  staging/src/kubevirt.io/api/export/v1alpha1/deepcopy_generated.go
  staging/src/kubevirt.io/api/export/v1alpha1/types.go
  staging/src/kubevirt.io/api/export/v1alpha1/types_swagger_generated.go
  staging/src/kubevirt.io/client-go/api/openapi_generated.go
  tests/storage/export.go
Labels: size/L, release-note, lgtm, approved, dco-signoff: yes

#8638 Since cachito is running go 1.18 we needed to update
  go.mod
Labels: size/XS, release-note-none, lgtm, approved, ok-to-test, dco-signoff: yes

#8454 test: move execute functions from utils
  tests/BUILD.bazel
  tests/config_test.go
  tests/container_disk_test.go
  tests/exec/BUILD.bazel
  tests/exec/execute.go
  tests/infra_test.go
  tests/io_utils.go
  tests/migration_test.go
  tests/network/BUILD.bazel
  tests/network/expose.go
  tests/network/sriov.go
  tests/network/vmi_multus.go
  tests/network/vmi_networking.go
  tests/network/vmi_slirp_interface.go
  tests/numa/BUILD.bazel
  tests/numa/numa.go
  tests/realtime/BUILD.bazel
  tests/realtime/realtime.go
  tests/reporter/BUILD.bazel
  tests/reporter/kubernetes.go
  tests/security_features_test.go
  tests/storage/BUILD.bazel
  tests/storage/datavolume.go
  tests/storage/export.go
  tests/storage/guestfs.go
  tests/storage/imageupload.go
  tests/storage/memorydump.go
  tests/storage/snapshot.go
  tests/storage/storage.go
  tests/sysprep_test.go
  tests/utils.go
  tests/virt_control_plane_test.go
  tests/vmi_cloudinit_test.go
  tests/vmi_configuration_test.go
  tests/vmi_gpu_test.go
  tests/vmi_lifecycle_test.go
  tests/windows_test.go
Labels: size/L, sig/network, release-note-none, lgtm, approved, dco-signoff: yes, sig/code-quality

#8442 Add Deckhouse to the Adopters list
  ADOPTERS.md
Labels: release-note, size/XS, lgtm, approved, dco-signoff: yes

#8593 docs/ssh.md: Remove SSH documentation from main repo
  docs/ssh.md
Labels: size/L, release-note-none, lgtm, approved, dco-signoff: yes

#8597 e2e expose: Use EndpointSlices instead of Endpoints and remove XFail blocks
  tests/network/BUILD.bazel
  tests/network/expose.go
Labels: size/M, sig/network, release-note-none, lgtm, approved, dco-signoff: yes

#8556 Move tests agnostic to Windows OS from Windows lane
  tests/BUILD.bazel
  tests/hyperv_test.go
  tests/windows_test.go
Labels: size/L, release-note-none, lgtm, approved, dco-signoff: yes

#8620 [Functest] several fixes to default runtime class configuration tests
  tests/BUILD.bazel
  tests/utils.go
  tests/vmi_configuration_test.go
Labels: size/M, release-note-none, lgtm, approved, dco-signoff: yes

#8563 Make nonroot default runtime
  pkg/host-disk/host-disk.go
  pkg/virt-api/webhooks/mutating-webhook/mutators/vmi-mutator.go
  pkg/virt-api/webhooks/mutating-webhook/mutators/vmi-mutator_test.go
  pkg/virt-api/webhooks/validating-webhook/admitters/vmi-create-admitter.go
  pkg/virt-api/webhooks/validating-webhook/admitters/vmi-create-admitter_test.go
  pkg/virt-config/feature-gates.go
  pkg/virt-controller/watch/migration.go
  pkg/virt-controller/watch/migration_test.go
  tests/migration_test.go
  tests/realtime/realtime.go
  tests/security_features_test.go
  tests/utils.go
Labels: size/L, release-note, lgtm, approved, dco-signoff: yes

#8633 Wait for podman to stop rsync container successfully
  hack/dockerized
Labels: size/XS, release-note-none, lgtm, approved, dco-signoff: yes

#8665 [e2e tests]: Avoid deleting default labels when cleaning up namespace
  tests/libnet/BUILD.bazel
  tests/libnet/namespace.go
  tests/testsuite/namespace.go
Labels: size/M, release-note-none, lgtm, approved, dco-signoff: yes

#8671 fix junit-merger build error on Arm64
  hack/bazel-test.sh
Labels: size/XS, release-note-none, lgtm, approved, dco-signoff: yes

#8676 Improve error in "using the local ssh method" test
  tests/virtctl/ssh.go
Labels: size/XS, release-note-none, lgtm, approved, dco-signoff: yes

#8559 Bump virtlogd memory requirement to 20Mi
  pkg/virt-controller/services/template.go
  pkg/virt-controller/services/template_test.go
  tests/vmi_configuration_test.go
Labels: size/M, release-note-none, lgtm, approved, dco-signoff: yes

#8613 Bump memory requests according to values seen in testing
  manifests/generated/operator-csv.yaml.in
  pkg/virt-operator/resource/generate/components/daemonsets.go
  pkg/virt-operator/resource/generate/components/deployments.go
Labels: size/XS, release-note-none, lgtm, approved, dco-signoff: yes

#8668 Fix test_id:7182
  tests/container_disk_test.go
Labels: size/XS, release-note-none, lgtm, approved, dco-signoff: yes

#8682 e2e: restore cluster condition
  tests/migration_test.go
Labels: size/XS, release-note-none, lgtm, approved, dco-signoff: yes

#8404 Switch to CentOS Stream 9
  WORKSPACE
  bazel/toolchain/aarch64-none-linux-gnu/cc_toolchain_config.bzl
  bazel/toolchain/x86_64-none-linux-gnu/cc_toolchain_config.bzl
  go.mod
  go.sum
  hack/bootstrap.sh
  hack/builder/Dockerfile
  hack/builder/build.sh
  hack/dockerized
  hack/rpm-deps.sh
  pkg/network/domainspec/generators.go
  pkg/network/domainspec/generators_test.go
  rpm/BUILD.bazel
  rpm/repo.yaml
  tests/network/expose.go
  tests/network/vmi_istio.go
  tests/vmi_sound_test.go
  third_party/toolchains/toolchains.bzl
  vendor/libvirt.org/go/libvirt/.gitlab-ci.yml
  vendor/libvirt.org/go/libvirt/README.rst
  vendor/libvirt.org/go/libvirt/lxc.go
  vendor/libvirt.org/go/libvirt/lxc_wrapper.go
  vendor/libvirt.org/go/libvirt/qemu.go
  vendor/libvirt.org/go/libvirt/qemu_wrapper.go
  vendor/modules.txt
Labels: sig/network, release-note, size/XXL, lgtm, approved, dco-signoff: yes

#8558 Fix LimitRange namespace bug
  pkg/virt-api/webhooks/mutating-webhook/mutators/namespace-limits.go
  pkg/virt-api/webhooks/mutating-webhook/mutators/namespace-limits_test.go
  pkg/virt-api/webhooks/mutating-webhook/mutators/vmi-mutator.go
  pkg/virt-api/webhooks/mutating-webhook/mutators/vmi-mutator_test.go
  tests/vmi_configuration_test.go
Labels: size/M, release-note, lgtm, approved, dco-signoff: yes

#8617 Return directly when key function executes failed
  pkg/virt-controller/watch/drain/disruptionbudget/disruptionbudget.go
  pkg/virt-controller/watch/drain/evacuation/evacuation.go
  pkg/virt-controller/watch/migration.go
  pkg/virt-controller/watch/node.go
  pkg/virt-controller/watch/pool.go
  pkg/virt-controller/watch/replicaset.go
  pkg/virt-controller/watch/vm.go
  pkg/virt-controller/watch/vmi.go
  pkg/virt-controller/watch/workload-updater/workload-updater.go
  pkg/virt-operator/kubevirt.go
Labels: size/S, release-note-none, lgtm, approved, ok-to-test, dco-signoff: yes

#8628 tests: fix nil point error for kubeClient
  pkg/virtctl/imageupload/imageupload_test.go
Labels: size/XS, release-note-none, lgtm, approved, dco-signoff: yes

#8635 Handle errors in multiple packages
  nogo_config.json
  pkg/container-disk/container-disk_test.go
  pkg/controller/controller.go
  pkg/controller/expectations_test.go
  pkg/downwardmetrics/vhostmd/BUILD.bazel
  pkg/downwardmetrics/vhostmd/disk.go
  pkg/emptydisk/emptydisk_test.go
  pkg/ephemeral-disk/ephemeral-disk_test.go
  pkg/host-disk/host-disk_test.go
  pkg/hotplug-disk/hotplug-disk_test.go
  pkg/watchdog/BUILD.bazel
  pkg/watchdog/watchdog.go
  pkg/watchdog/watchdog_test.go
Labels: size/L, release-note-none, lgtm, approved, dco-signoff: yes, sig/code-quality

#8661 [tests] Use random custom runtime classes to avoid cleanup collisions
  tests/vmi_configuration_test.go
Labels: size/M, release-note-none, lgtm, approved, dco-signoff: yes

#8667 fix stat virt-vnc and virt-serial0 return error
  pkg/virt-handler/rest/console.go
Labels: release-note, size/XS, lgtm, approved, needs-ok-to-test, dco-signoff: yes

#8279 instancetype: Add testids to functional tests
  tests/instancetype_test.go
Labels: size/M, release-note-none, lgtm, approved, dco-signoff: yes, area/instancetype

#8342 Fix vm-cirros-cluster-csmall VirtualMachineClusterInstancetype name value.
  examples/vm-cirros-cluster-csmall.yaml
  tools/vms-generator/utils/utils.go
Labels: size/S, release-note-none, lgtm, approved, ok-to-test, dco-signoff: yes, area/instancetype

#8336 guestfs: flag to set uid and gid
  cmd/libguestfs/BUILD.bazel
  pkg/virtctl/guestfs/BUILD.bazel
  pkg/virtctl/guestfs/guestfs.go
  pkg/virtctl/guestfs/guestfs_test.go
  tests/storage/guestfs.go
Labels: size/L, release-note, lgtm, approved, dco-signoff: yes

#8681 tests: Run mkfs.ext4 with force flag -F
  tests/storage/hotplug.go
  tests/storage/restore.go
  tests/storage/storage.go
Labels: size/XS, release-note-none, lgtm, approved, dco-signoff: yes

#8693 Fix the flaky VSOCK unit test
  pkg/virt-controller/watch/vsock_test.go
Labels: size/XS, release-note-none, lgtm, approved, ok-to-test, dco-signoff: yes

#8670 tests: create PSA compliant pod in `renderContainerSpec()`
  tests/libstorage/BUILD.bazel
  tests/libstorage/pvc.go
  tests/storage/export.go
  tests/utils.go
Labels: size/M, release-note-none, lgtm, approved, dco-signoff: yes

#8658 tests, performance: Add VM and VM with instancetype density tests
  tests/performance/BUILD.bazel
  tests/performance/density.go
Labels: size/L, release-note-none, lgtm, approved, dco-signoff: yes, area/instancetype
