Repository kubevirt/kubevirt, pull requests merged in 2022-01, with the labels that each got.

#7011 virtctl expose: more legible error message
  pkg/virtctl/expose/expose.go
Labels: size/XS, release-note-none, lgtm, approved, dco-signoff: yes

#7016 [Go version update guide]: Remove bullet on project-infra's mirror uploader tool
  docs/update-go-version.md
Labels: size/XS, release-note-none, lgtm, approved, dco-signoff: yes

#6926 netstat: Drop dependencies between status report iterations and simplify the data collection from the pod
  pkg/network/setup/netstat.go
  pkg/network/setup/netstat_test.go
Labels: size/L, sig/network, release-note-none, lgtm, approved, dco-signoff: yes

#7019 Fix small typo: topologyToTopology() to capabilitiesToTopology()
  pkg/virt-handler/options.go
Labels: size/XS, release-note-none, lgtm, approved, dco-signoff: yes

#6942 Stop testing trim with Block DVs
  tests/storage/datavolume.go
Labels: size/M, release-note-none, lgtm, approved, dco-signoff: yes

#6986 Support IPv4 parsing with leading zeros on go 1.17
  go.mod
  go.sum
  staging/src/kubevirt.io/api/core/v1/BUILD.bazel
  staging/src/kubevirt.io/api/core/v1/sanitizers.go
  staging/src/kubevirt.io/api/core/v1/schema.go
  staging/src/kubevirt.io/api/core/v1/types.go
  staging/src/kubevirt.io/api/go.mod
  staging/src/kubevirt.io/api/go.sum
  staging/src/kubevirt.io/client-go/go.mod
  staging/src/kubevirt.io/client-go/go.sum
  tests/network/vmi_networking.go
  vendor/k8s.io/utils/internal/third_party/forked/golang/LICENSE
  vendor/k8s.io/utils/internal/third_party/forked/golang/PATENTS
  vendor/k8s.io/utils/internal/third_party/forked/golang/net/BUILD.bazel
  vendor/k8s.io/utils/internal/third_party/forked/golang/net/ip.go
  vendor/k8s.io/utils/internal/third_party/forked/golang/net/parse.go
  vendor/k8s.io/utils/net/BUILD.bazel
  vendor/k8s.io/utils/net/ipnet.go
  vendor/k8s.io/utils/net/net.go
  vendor/k8s.io/utils/net/parse.go
  vendor/k8s.io/utils/net/port.go
  vendor/k8s.io/utils/pointer/pointer.go
  vendor/k8s.io/utils/trace/trace.go
  vendor/modules.txt
Labels: sig/network, size/XL, release-note-none, lgtm, approved, dco-signoff: yes

#6793 virt-handler, Add infoSource field to vmi status
  api/openapi-spec/swagger.json
  pkg/network/setup/BUILD.bazel
  pkg/network/setup/netstat.go
  pkg/network/setup/netstat_test.go
  pkg/network/vmispec/interface.go
  pkg/virt-launcher/virtwrap/BUILD.bazel
  pkg/virt-launcher/virtwrap/agent-poller/BUILD.bazel
  pkg/virt-launcher/virtwrap/agent-poller/agent_parser.go
  pkg/virt-launcher/virtwrap/agent-poller/agent_parser_test.go
  pkg/virt-launcher/virtwrap/api/schema.go
  pkg/virt-launcher/virtwrap/manager_test.go
  pkg/virt-operator/resource/generate/components/validations_generated.go
  staging/src/kubevirt.io/api/core/v1/types.go
  staging/src/kubevirt.io/api/core/v1/types_swagger_generated.go
  staging/src/kubevirt.io/client-go/api/openapi_generated.go
  tests/libvmi/network.go
  tests/network/BUILD.bazel
  tests/network/vmi_infosource.go
  tests/network/vmi_multus.go
  tests/nonroot_test.go
Labels: size/L, sig/network, release-note, lgtm, approved, dco-signoff: yes

#7028 [release-0.41] virt-handler: use /proc instead of virt-chroot to stat virt-launcher files
  pkg/virt-handler/isolation/validation.go
  pkg/virt-handler/vm.go
Labels: size/M, release-note-none, lgtm, approved, dco-signoff: yes

#6821 Update dedicated CPUs on migration
  api/openapi-spec/swagger.json
  pkg/virt-handler/BUILD.bazel
  pkg/virt-handler/cgroup/cgroup.go
  pkg/virt-handler/vm.go
  pkg/virt-launcher/virtwrap/BUILD.bazel
  pkg/virt-launcher/virtwrap/converter/BUILD.bazel
  pkg/virt-launcher/virtwrap/converter/converter.go
  pkg/virt-launcher/virtwrap/converter/converter_test.go
  pkg/virt-launcher/virtwrap/converter/network.go
  pkg/virt-launcher/virtwrap/converter/numa_placement.go
  pkg/virt-launcher/virtwrap/converter/vcpu/BUILD.bazel
  pkg/virt-launcher/virtwrap/converter/vcpu/numa_placement_test.go
  pkg/virt-launcher/virtwrap/converter/vcpu/vcpu.go
  pkg/virt-launcher/virtwrap/converter/vcpu_placement.go
  pkg/virt-launcher/virtwrap/live-migration-source.go
  pkg/virt-launcher/virtwrap/manager_test.go
  pkg/virt-launcher/virtwrap/util/cpu_utils.go
  pkg/virt-operator/resource/generate/components/validations_generated.go
  staging/src/kubevirt.io/api/core/v1/deepcopy_generated.go
  staging/src/kubevirt.io/api/core/v1/types.go
  staging/src/kubevirt.io/api/core/v1/types_swagger_generated.go
  staging/src/kubevirt.io/client-go/api/openapi_generated.go
  tests/framework/checks/skips.go
  tests/migration.go
  tests/migration_test.go
  tests/operator_test.go
  tests/reporter/kubernetes.go
  tests/utils.go
Labels: release-note, size/XXL, lgtm, approved, dco-signoff: yes

#6973 Fix misleading domain memory metrics
  docs/metrics.md
  hack/prom-rule-ci/prom-rules-tests.yaml
  pkg/monitoring/domainstats/prometheus/prometheus.go
  pkg/monitoring/domainstats/prometheus/prometheus_test.go
  pkg/virt-operator/resource/generate/components/prometheus.go
  tools/doc-generator/doc-generator.go
Labels: size/M, release-note-none, lgtm, approved, dco-signoff: yes, area/monitoring

#6985 network, fqdn: Fix adding subdomain search entry flow
  pkg/network/dns/resolveconf.go
  pkg/network/dns/resolveconf_test.go
  tests/network/vmi_subdomain.go
Labels: size/L, sig/network, release-note-none, lgtm, approved, dco-signoff: yes

#7029 [release-0.44] virt-handler: use /proc instead of virt-chroot to stat virt-launcher files
  pkg/virt-handler/isolation/validation.go
  pkg/virt-handler/vm.go
Labels: size/M, release-note-none, lgtm, approved, dco-signoff: yes

#7030 Add test_id for kernel boot tests
  tests/vmi_kernel_boot_test.go
Labels: size/XS, release-note-none, lgtm, approved, dco-signoff: yes

#6923 Istio: Fix ssh traffic forwarding to VMIs with Istio proxy
  pkg/network/infraconfigurators/masquerade.go
  pkg/network/infraconfigurators/masquerade_test.go
  pkg/network/istio/ports.go
  tests/network/vmi_istio.go
Labels: size/M, release-note, lgtm, approved, dco-signoff: yes

#6936 Improve functests usage of storage
  automation/test.sh
  hack/functests.sh
  tests/config.go
  tests/conformance-config.json
  tests/console_test.go
  tests/default-ceph-config.json
  tests/default-config.json
  tests/migration_test.go
  tests/storage/datavolume.go
  tests/storage/guestfs.go
  tests/storage/hotplug.go
  tests/storage/imageupload.go
  tests/storage/restore.go
  tests/storage/snapshot.go
  tests/storage/storage.go
  tests/utils.go
  tests/vm_test.go
Labels: size/L, release-note-none, lgtm, approved, dco-signoff: yes

#6995 Update OrphanedVirtualMachineImages alert name
  hack/prom-rule-ci/prom-rules-tests.yaml
  pkg/virt-operator/resource/generate/components/prometheus.go
Labels: release-note, size/XS, lgtm, approved, dco-signoff: yes, area/monitoring

#6968 Add support for disk cache writeback
  pkg/virt-api/webhooks/validating-webhook/admitters/vmi-create-admitter.go
  pkg/virt-api/webhooks/validating-webhook/admitters/vmi-create-admitter_test.go
  staging/src/kubevirt.io/api/core/v1/types.go
  tests/migration_test.go
  tests/vmi_configuration_test.go
Labels: size/M, release-note, lgtm, approved, dco-signoff: yes

#7035 [virt-api]: replace UPDATE client method with PATCH in pod eviction admitter
  pkg/virt-api/webhooks/validating-webhook/admitters/pod-eviction-admitter.go
  pkg/virt-api/webhooks/validating-webhook/admitters/pod-eviction-admitter_test.go
Labels: size/M, release-note-none, lgtm, approved, dco-signoff: yes

#6951 netstat: Update VMI interface status report unit tests
  pkg/network/setup/netstat_test.go
Labels: sig/network, size/XL, release-note-none, lgtm, approved, dco-signoff: yes

#7045 tests, console: fix docstring
  tests/console/console.go
Labels: size/S, release-note-none, lgtm, approved, dco-signoff: yes

#7010 Improve functests usage of storage (part 2)
  examples/vmi-block-pvc.yaml
  hack/cluster-deploy.sh
  images/disks-images-provider/BUILD.bazel
  images/disks-images-provider/entrypoint.sh
  manifests/testing/local-block-storage.yaml.in
  tests/config.go
  tests/conformance-config.json
  tests/default-ceph-config.json
  tests/default-config.json
  tests/storage/datavolume.go
  tests/storage/snapshot.go
  tests/storage/storage.go
  tests/utils.go
  tests/vmi_configuration_test.go
  tools/vms-generator/utils/utils.go
  tools/vms-generator/vms-generator.go
Labels: size/L, release-note-none, lgtm, approved, dco-signoff: yes

#7059 Remove leftover file
  staging/src/kubevirt.io/api/go.mod
  staging/src/kubevirt.io/api/migrations/v1alpha1/BUILD.bazel
  staging/src/kubevirt.io/api/migrations/v1alpha1/openapi_generated.go
Labels: size/XXL, release-note-none, lgtm, approved, dco-signoff: yes

#7062 docs: remove `VirtualMachineInstanceConfig`
  docs/config-and-instances.md
Labels: size/L, release-note-none, lgtm, approved, dco-signoff: yes

#6946 Add NUMA information to config driver devices metadata
  api/openapi-spec/swagger.json
  pkg/cloud-init/cloud-init.go
  pkg/cloud-init/cloud-init_test.go
  pkg/util/hardware/BUILD.bazel
  pkg/util/hardware/hw_utils.go
  pkg/virt-launcher/virtwrap/BUILD.bazel
  pkg/virt-launcher/virtwrap/manager.go
  pkg/virt-operator/resource/generate/components/validations_generated.go
  staging/src/kubevirt.io/api/core/v1/schema.go
  staging/src/kubevirt.io/api/core/v1/schema_swagger_generated.go
  staging/src/kubevirt.io/client-go/api/openapi_generated.go
  tests/network/BUILD.bazel
  tests/network/vmi_multus.go
  tests/utils.go
  tests/vmi_cloudinit_test.go
  tests/vmi_configuration_test.go
Labels: size/L, release-note, lgtm, approved, dco-signoff: yes

#6999 Limit ourselves to expanding to min(spec.request, status.capacity)
  api/openapi-spec/swagger.json
  pkg/virt-controller/watch/vmi.go
  pkg/virt-launcher/virtwrap/api/BUILD.bazel
  pkg/virt-launcher/virtwrap/api/deepcopy_generated.go
  pkg/virt-launcher/virtwrap/api/schema.go
  pkg/virt-launcher/virtwrap/converter/converter.go
  pkg/virt-launcher/virtwrap/converter/converter_test.go
  pkg/virt-launcher/virtwrap/manager.go
  pkg/virt-launcher/virtwrap/manager_test.go
  pkg/virt-operator/resource/generate/components/validations_generated.go
  staging/src/kubevirt.io/api/core/v1/deepcopy_generated.go
  staging/src/kubevirt.io/api/core/v1/types.go
  staging/src/kubevirt.io/api/core/v1/types_swagger_generated.go
  staging/src/kubevirt.io/client-go/api/openapi_generated.go
Labels: size/L, release-note, lgtm, approved, dco-signoff: yes

#6988 Pass through docker prefix and tag for vms-generator
  tests/tests_suite_test.go
Labels: size/XS, release-note-none, lgtm, approved, dco-signoff: yes

#7053 network, mac update test: Add assertion of the expected status
  tests/network/vmi_infosource.go
Labels: size/XS, release-note-none, lgtm, approved, dco-signoff: yes

#7057 Trigger audit from inside the performance test
  hack/perftests.sh
  tests/performance/BUILD.bazel
  tests/performance/density.go
Labels: size/M, release-note-none, lgtm, approved, dco-signoff: yes

#6883 Pass the VirtualMachineFlavor Name to cloud-init as instance-type
  pkg/cloud-init/cloud-init.go
  pkg/cloud-init/cloud-init_test.go
  pkg/flavor/BUILD.bazel
  pkg/flavor/flavor.go
  pkg/flavor/flavor_test.go
  pkg/testutils/mock_flavor.go
  pkg/virt-api/webhooks/validating-webhook/admitters/vms-admitter.go
  pkg/virt-api/webhooks/validating-webhook/admitters/vms-admitter_test.go
  pkg/virt-controller/watch/vm.go
  pkg/virt-controller/watch/vm_test.go
  pkg/virt-launcher/virtwrap/manager.go
  staging/src/kubevirt.io/api/core/v1/types.go
  tests/flavor_test.go
  tests/network/vmi_multus.go
  tests/vmi_cloudinit_test.go
Labels: size/L, release-note, lgtm, approved, dco-signoff: yes

#7044 tests: drop redudant UsrBinBash constant
  tests/realtime/realtime.go
  tests/storage/storage.go
  tests/utils.go
Labels: size/S, release-note-none, lgtm, approved, dco-signoff: yes

#6279 Change example video image
  README.md
Labels: size/XS, release-note-none, lgtm, approved, ok-to-test, dco-signoff: yes

#6908 Adjust file names to use parallelnode
  tests/tests_suite_test.go
Labels: size/S, release-note-none, lgtm, approved, dco-signoff: yes

#7005 Adjust some storage tests to respect different environment
  tests/storage/datavolume.go
  tests/storage/imageupload.go
  tests/storage/restore.go
Labels: size/XS, release-note-none, lgtm, approved, dco-signoff: yes

#6735 Virtctl: cancel migrate
  pkg/virtctl/root.go
  pkg/virtctl/vm/vm.go
  pkg/virtctl/vm/vm_test.go
  tests/migration_test.go
Labels: size/L, release-note, lgtm, approved, ok-to-test, dco-signoff: yes

#6972 Improve kubevirt update test
  tests/flags/flags.go
  tests/operator_test.go
Labels: size/M, release-note-none, lgtm, approved, ok-to-test, dco-signoff: yes

#7076 add Marcelo Amaral to reviewers
  OWNERS_ALIASES
Labels: size/XS, release-note-none, lgtm, approved, dco-signoff: yes

#7058 network, netstat: Add tests to cover changes in the guest
  pkg/network/setup/netstat_test.go
Labels: size/M, sig/network, release-note-none, lgtm, approved, dco-signoff: yes

#7089 tests, utils: coalesce datavolume creation functions
  tests/utils.go
Labels: size/M, release-note-none, lgtm, approved, dco-signoff: yes

#6924 virt-handler, hostdevice: Remove legacy support
  pkg/virt-launcher/virtwrap/BUILD.bazel
  pkg/virt-launcher/virtwrap/converter/converter.go
  pkg/virt-launcher/virtwrap/device/hostdevice/legacy/BUILD.bazel
  pkg/virt-launcher/virtwrap/device/hostdevice/legacy/addresspool.go
  pkg/virt-launcher/virtwrap/device/hostdevice/legacy/addresspool_test.go
  pkg/virt-launcher/virtwrap/device/hostdevice/legacy/hostdev.go
  pkg/virt-launcher/virtwrap/device/hostdevice/legacy/hostdev_test.go
  pkg/virt-launcher/virtwrap/device/hostdevice/legacy/legacy_suite_test.go
  pkg/virt-launcher/virtwrap/manager.go
Labels: size/XL, release-note, lgtm, approved, dco-signoff: yes

#7098 [release-0.41] Manual backport of 'tests: fix skipping of HostDisk tests'
  tests/storage/storage.go
Labels: size/XS, release-note-none, lgtm, approved, dco-signoff: yes

#7094 Run guest agent e2e tests in parallel
  tests/vmi_configuration_test.go
Labels: size/XS, release-note-none, lgtm, approved, dco-signoff: yes

#7014 Improve functests usage of storage (part 3)
  tests/config.go
  tests/conformance-config.json
  tests/default-ceph-config.json
  tests/default-config.json
  tests/migration_test.go
  tests/storage/datavolume.go
  tests/storage/hotplug.go
  tests/storage/imageupload.go
  tests/storage/storage.go
  tests/utils.go
Labels: size/L, release-note-none, lgtm, approved, dco-signoff: yes

#7068 Consider Prometheus counters resets in our alerts
  hack/prom-rule-ci/prom-rules-tests.yaml
  pkg/virt-operator/resource/generate/components/BUILD.bazel
  pkg/virt-operator/resource/generate/components/prometheus.go
  pkg/virt-operator/resource/generate/components/util.go
Labels: size/L, release-note-none, lgtm, approved, dco-signoff: yes, area/monitoring

#7092 virt-launcher, hostdevice: Pass only hostdevices to the filter
  pkg/virt-launcher/virtwrap/device/hostdevice/hotplug.go
  pkg/virt-launcher/virtwrap/device/hostdevice/hotplug_test.go
  pkg/virt-launcher/virtwrap/device/hostdevice/sriov/hostdev.go
Labels: size/S, release-note-none, lgtm, approved, dco-signoff: yes

#7100 Add "IO error" functional tests back to quarantine
  tests/storage/storage.go
Labels: size/XS, release-note-none, lgtm, approved, dco-signoff: yes

#7047 tests.reporter.kubernetes minor cleanup
  tests/reporter/kubernetes.go
Labels: size/S, release-note-none, lgtm, approved, dco-signoff: yes

#7081 Fix initialization of the device plugin with different vendor/product id but same resource name
  pkg/virt-handler/device-manager/device_controller.go
  pkg/virt-handler/device-manager/pci_device.go
  pkg/virt-handler/device-manager/pci_device_test.go
  tests/vmi_hostdev_test.go
Labels: size/L, release-note-none, lgtm, approved, dco-signoff: yes

#7116 [release-0.44]Pass through docker prefix and tag for vms-generator
  tests/tests_suite_test.go
Labels: size/XS, release-note-none, lgtm, approved, dco-signoff: yes

#7117 Fix hotplugs volumesnapshot was not created in vmsnapshot
  pkg/virt-controller/watch/snapshot/source.go
  tests/storage/restore.go
  tests/storage/snapshot.go
Labels: size/M, release-note-none, lgtm, approved, dco-signoff: yes

#7118 Run replica set tests in parallel
  tests/replicaset_test.go
Labels: size/XS, release-note-none, lgtm, approved, dco-signoff: yes

#7095 Fix test LimitRange
  pkg/virt-api/webhooks/mutating-webhook/mutators/namespace-limits.go
  tests/vmi_configuration_test.go
Labels: size/M, release-note-none, lgtm, approved, dco-signoff: yes

#6963 Fix flaky dry run functest
  tests/vm_test.go
Labels: size/S, release-note-none, lgtm, approved, ok-to-test, dco-signoff: yes

#7113 Fix typo in cluster-clean.sh: kubectl -> _kubectl
  hack/cluster-clean.sh
Labels: size/XS, release-note-none, lgtm, approved, dco-signoff: yes

#7051 network, netstat: Simplify status update
  pkg/network/setup/netstat.go
  pkg/network/setup/netstat_test.go
  pkg/network/vmispec/interface.go
Labels: size/L, sig/network, release-note-none, lgtm, approved, dco-signoff: yes

#7110 network, setup: tiny cleanup
  pkg/network/setup/network.go
  pkg/network/setup/network_suite_test.go
  pkg/network/setup/network_test.go
  pkg/network/setup/podnic.go
  pkg/network/setup/podnic_test.go
  pkg/network/vmispec/interface.go
Labels: size/M, sig/network, release-note-none, lgtm, approved, dco-signoff: yes

#6581 SR-IOV Migration: Move attach SRIOV devices to virt-handler
  pkg/executor/BUILD.bazel
  pkg/executor/backoff.go
  pkg/executor/backoff_test.go
  pkg/executor/executor.go
  pkg/executor/executor_suite_test.go
  pkg/executor/executor_test.go
  pkg/executor/pool.go
  pkg/executor/pool_test.go
  pkg/handler-launcher-com/cmd/v1/cmd.pb.go
  pkg/handler-launcher-com/cmd/v1/cmd.proto
  pkg/handler-launcher-com/cmd/v1/generated_mock_cmd.go
  pkg/network/vmispec/BUILD.bazel
  pkg/network/vmispec/interface.go
  pkg/network/vmispec/interface_test.go
  pkg/virt-handler/BUILD.bazel
  pkg/virt-handler/cmd-client/client.go
  pkg/virt-handler/cmd-client/generated_mock_client.go
  pkg/virt-handler/vm.go
  pkg/virt-launcher/virtwrap/cmd-server/server.go
  pkg/virt-launcher/virtwrap/generated_mock_manager.go
  pkg/virt-launcher/virtwrap/live-migration-target.go
  pkg/virt-launcher/virtwrap/manager.go
Labels: size/XL, release-note, lgtm, approved, dco-signoff: yes

#7023 network, cache: Refactor the code base
  pkg/network/cache/BUILD.bazel
  pkg/network/cache/cache.go
  pkg/network/cache/cache_suite_test.go
  pkg/network/cache/cache_test.go
  pkg/network/cache/dhcpconfig.go
  pkg/network/cache/dhcpconfig_test.go
  pkg/network/cache/domaininterface.go
  pkg/network/cache/domaininterface_test.go
  pkg/network/cache/infocache.go
  pkg/network/cache/infocache_test.go
  pkg/network/cache/podinterface.go
  pkg/network/cache/podinterface_test.go
  pkg/network/cache/types.go
  pkg/network/dhcp/BUILD.bazel
  pkg/network/dhcp/bridge.go
  pkg/network/dhcp/bridge_test.go
  pkg/network/dhcp/configurator.go
  pkg/network/dhcp/configurator_test.go
  pkg/network/dhcp/dhcp_suite_test.go
  pkg/network/setup/BUILD.bazel
  pkg/network/setup/netconf.go
  pkg/network/setup/netconf_test.go
  pkg/network/setup/netstat.go
  pkg/network/setup/netstat_test.go
  pkg/network/setup/network.go
  pkg/network/setup/network_suite_test.go
  pkg/network/setup/network_test.go
  pkg/network/setup/podnic.go
  pkg/network/setup/podnic_test.go
  pkg/virt-handler/vm.go
  pkg/virt-handler/vm_test.go
  pkg/virt-launcher/virtwrap/manager.go
Labels: sig/network, size/XXL, release-note-none, lgtm, approved, dco-signoff: yes

#7115 [release-0.41] Manual bulk backport of hotplug test fixes
  tests/storage/BUILD.bazel
  tests/storage/hotplug.go
Labels: size/L, release-note-none, lgtm, approved, dco-signoff: yes

#6700 Simplify replacing ticker and fix interval flag default values
  cmd/virt-launcher/virt-launcher.go
  pkg/virt-launcher/virtwrap/agent-poller/agent_poller.go
Labels: size/S, release-note, lgtm, approved, ok-to-test, dco-signoff: yes

#7063 Describe ways to freeze/thaw a VMI
  docs/freeze.md
Labels: size/M, release-note-none, lgtm, approved, dco-signoff: yes

#7088 docs: Fix a broken link in CONTRIBUTING.md
  CONTRIBUTING.md
Labels: size/XS, release-note-none, lgtm, approved, ok-to-test, dco-signoff: yes

#7097 [Bug fix] VMI with kernel boot stuck on "Terminating" status if more disks are defined
  pkg/virt-handler/container-disk/generated_mock_mount.go
  pkg/virt-handler/container-disk/mount.go
  pkg/virt-handler/vm.go
  tests/vmi_kernel_boot_test.go
  tools/vms-generator/utils/utils.go
Labels: size/L, release-note, lgtm, approved, dco-signoff: yes

#7131 Use semantic equality comparison in VMI controller
  pkg/virt-handler/BUILD.bazel
  pkg/virt-handler/vm.go
  pkg/virt-handler/vm_test.go
Labels: size/S, release-note-none, lgtm, approved, dco-signoff: yes

#7036 [cluster-profiler]: fix for flaky test - do not dump data from a pod that is under deletion
  pkg/virt-api/rest/profiler.go
Labels: size/XS, release-note-none, lgtm, approved, dco-signoff: yes

#7127 [release-0.49] Fix hotplugs volumesnapshot was not created in vmsnapshot
  pkg/virt-controller/watch/snapshot/source.go
  tests/storage/restore.go
  tests/storage/snapshot.go
Labels: size/M, release-note-none, lgtm, approved, dco-signoff: yes

#6654 Fix block detection in ReplacePVCByHostDisk
  pkg/host-disk/host-disk.go
  pkg/util/types/pvc.go
Labels: size/S, release-note-none, lgtm, approved, dco-signoff: yes

#7129 tests, utils: Remove unused functions
  tests/utils.go
Labels: size/L, release-note-none, lgtm, approved, dco-signoff: yes

#7017 Take out of quarantine test_id:3145 for nonroot lanes
  automation/test.sh
Labels: size/XS, release-note-none, lgtm, approved, dco-signoff: yes

#7064 Fix CRD removal race condition
  pkg/virt-operator/kubevirt_test.go
  pkg/virt-operator/resource/apply/BUILD.bazel
  pkg/virt-operator/resource/apply/delete.go
  pkg/virt-operator/resource/apply/delete_test.go
  staging/src/kubevirt.io/api/core/v1/types.go
  tests/operator_test.go
Labels: size/L, release-note, lgtm, approved, dco-signoff: yes

#7000 New annotation to customize libvirt log filters + gradually increase libvirt logs according to virt-launcher logVerbosity
  cmd/virt-launcher/virt-launcher.go
  pkg/virt-controller/services/template.go
  pkg/virt-launcher/virtwrap/util/BUILD.bazel
  pkg/virt-launcher/virtwrap/util/libvirt_helper.go
  pkg/virt-launcher/virtwrap/util/libvirt_helper_test.go
  staging/src/kubevirt.io/api/core/v1/types.go
  tests/vmi_lifecycle_test.go
Labels: size/L, release-note, lgtm, approved, dco-signoff: yes

#7136 pkg: Remove unused functions and types
  pkg/certificates/triple/cert/cert.go
  pkg/config/config.go
  pkg/controller/BUILD.bazel
  pkg/controller/expectations.go
  pkg/middleware/BUILD.bazel
  pkg/middleware/middleware.go
  pkg/middleware/middleware_suite_test.go
  pkg/middleware/middleware_test.go
  pkg/monitoring/vmistats/BUILD.bazel
  pkg/monitoring/vmistats/fakecollector.go
  pkg/network/cache/cache.go
  pkg/virt-api/webhooks/utils.go
  pkg/virt-controller/watch/vmi.go
  pkg/virt-handler/cgroup/cgroup.go
  pkg/virt-launcher/virtwrap/access-credentials/access_credentials.go
  pkg/virt-launcher/virtwrap/converter/converter.go
  pkg/virtctl/guestfs/guestfs.go
Labels: size/L, sig/network, release-note-none, lgtm, approved, dco-signoff: yes, area/monitoring

#7052 Fix kubevirt_vm_container_free_memory_bytes
  hack/prom-rule-ci/prom-rules-tests.yaml
  pkg/virt-operator/resource/generate/components/prometheus.go
Labels: size/S, release-note, lgtm, approved, dco-signoff: yes, area/monitoring

#7096 Run openshift permission tests in parallel
  tests/access_test.go
Labels: size/S, release-note-none, lgtm, approved, dco-signoff: yes

#7093 Pathjoin concatenate strings
  cmd/example-cloudinit-hook-sidecar/cloudinit.go
  cmd/example-hook-sidecar/smbios.go
  cmd/virt-launcher/virt-launcher.go
  pkg/config/config.go
  pkg/config/config_test.go
  pkg/container-disk/container-disk_test.go
  pkg/inotify-informer/inotify_test.go
  pkg/virt-api/rest/definitions.go
  pkg/virt-controller/watch/application.go
  pkg/virt-handler/cmd-client/client_test.go
  pkg/virt-handler/isolation/detector_test.go
  pkg/virt-handler/migration-proxy/migration-proxy_test.go
  pkg/virt-handler/selinux/labels.go
  pkg/virt-handler/vm.go
  pkg/virt-launcher/virtwrap/access-credentials/access_credentials_test.go
  pkg/virt-launcher/virtwrap/cmd-server/server_test.go
  pkg/virt-operator/resource/generate/components/deployments.go
  pkg/watchdog/watchdog_test.go
  staging/src/kubevirt.io/client-go/kubecli/kv_test.go
  staging/src/kubevirt.io/client-go/kubecli/migration_test.go
  staging/src/kubevirt.io/client-go/kubecli/migrationpolicy_test.go
  staging/src/kubevirt.io/client-go/kubecli/replicaset_test.go
  staging/src/kubevirt.io/client-go/kubecli/vm_test.go
  staging/src/kubevirt.io/client-go/kubecli/vmi_test.go
  staging/src/kubevirt.io/client-go/kubecli/vmipreset_test.go
  tests/operator_test.go
  tests/utils.go
  tests/vmi_cloudinit_hook_sidecar_test.go
  tests/vmi_cloudinit_test.go
Labels: size/L, release-note-none, lgtm, approved, ok-to-test, dco-signoff: yes, area/monitoring

#7038 Small improvements to VM Flavors
  pkg/controller/BUILD.bazel
  pkg/controller/virtinformers.go
  pkg/flavor/BUILD.bazel
  pkg/flavor/flavor.go
  pkg/virt-api/rest/BUILD.bazel
  pkg/virt-api/rest/definitions.go
  pkg/virt-api/webhooks/validating-webhook/admitters/BUILD.bazel
  pkg/virt-api/webhooks/validating-webhook/admitters/flavor-admitter.go
  pkg/virt-api/webhooks/validating-webhook/admitters/flavor-admitter_test.go
  pkg/virt-operator/resource/generate/components/BUILD.bazel
  pkg/virt-operator/resource/generate/components/crds.go
  pkg/virt-operator/resource/generate/components/webhooks.go
  pkg/virt-operator/resource/generate/rbac/BUILD.bazel
  pkg/virt-operator/resource/generate/rbac/apiserver.go
  pkg/virt-operator/resource/generate/rbac/cluster.go
  pkg/virt-operator/resource/generate/rbac/controller.go
  staging/src/kubevirt.io/api/flavor/register.go
Labels: size/M, release-note-none, lgtm, approved, dco-signoff: yes

#7075 Hardcode range selector to 5m and add a Primer VMI before each test
  tests/performance/density.go
  tools/perfscale-audit/metric-client/metric-client.go
Labels: size/S, release-note-none, lgtm, approved, dco-signoff: yes

#6389 [tests] remove beforeall from a bunch of tests
  pkg/virt-handler/node-labeller/BUILD.bazel
  pkg/virt-handler/node-labeller/cpu_plugin_test.go
  tests/credentials_test.go
  tests/security_features_test.go
  tests/storage/storage.go
  tests/usbredir_test.go
  tests/vmi_cloudinit_test.go
  tests/vmi_configuration_test.go
  tests/vmi_ignition_test.go
  tests/vmi_iothreads_test.go
  tests/vmi_multiqueue_test.go
  tests/vnc_test.go
Labels: size/L, release-note-none, lgtm, approved, dco-signoff: yes

#7128 tests, network: Create VMI/s using libvmi (in vmi_networking)
  tests/libvmi/factory.go
  tests/libvmi/network.go
  tests/network/vmi_networking.go
  tests/utils.go
Labels: size/L, sig/network, release-note-none, lgtm, approved, dco-signoff: yes

#7150 tests, network: Fix typo
  pkg/network/setup/netstat_test.go
Labels: sig/network, size/XS, release-note-none, lgtm, approved, dco-signoff: yes

#7020 Tests: Fix detection of incoming domain
  tests/migration_test.go
Labels: size/XS, release-note-none, lgtm, approved, dco-signoff: yes

#7156 [release-0.49] Improve functests usage of storage (part 3)
  tests/config.go
  tests/conformance-config.json
  tests/default-ceph-config.json
  tests/default-config.json
  tests/migration_test.go
  tests/storage/datavolume.go
  tests/storage/hotplug.go
  tests/storage/imageupload.go
  tests/storage/storage.go
  tests/utils.go
Labels: size/L, release-note-none, lgtm, approved, dco-signoff: yes
