Repository kubevirt/kubevirt, pull requests merged in 2022-08, with the labels that each got.

#8166 tests: re-implement NewRandomVMIWithWatchdog
  tests/utils.go
  tests/vmi_monitoring_test.go
Labels: size/M, release-note-none, lgtm, approved, dco-signoff: yes, sig/code-quality

#8123 Tests mdev: Check periodically for created devices
  tests/mdev_configuration_allocation_test.go
Labels: size/M, release-note-none, lgtm, approved, dco-signoff: yes

#8234 Update libvirt-go to fix memory leak
  go.mod
  go.sum
  vendor/libvirt.org/go/libvirt/.gitlab-ci.yml
  vendor/libvirt.org/go/libvirt/connect.go
  vendor/libvirt.org/go/libvirt/connect_compat.h
  vendor/libvirt.org/go/libvirt/connect_wrapper.go
  vendor/libvirt.org/go/libvirt/connect_wrapper.h
  vendor/libvirt.org/go/libvirt/domain.go
  vendor/libvirt.org/go/libvirt/domain_compat.h
  vendor/libvirt.org/go/libvirt/domain_snapshot.go
  vendor/libvirt.org/go/libvirt/domain_snapshot_compat.h
  vendor/libvirt.org/go/libvirt/domain_wrapper.go
  vendor/libvirt.org/go/libvirt/domain_wrapper.h
  vendor/libvirt.org/go/libvirt/error.go
  vendor/libvirt.org/go/libvirt/events.go
  vendor/libvirt.org/go/libvirt/qemu.go
  vendor/libvirt.org/go/libvirt/qemu_wrapper.go
  vendor/libvirt.org/go/libvirt/qemu_wrapper.h
  vendor/libvirt.org/go/libvirt/typedparams.go
  vendor/modules.txt
Labels: size/L, release-note-none, lgtm, approved, dco-signoff: yes

#8236 [release-0.53]Update libvirt-go to fix memory leak
  go.mod
  go.sum
  vendor/libvirt.org/go/libvirt/.gitlab-ci.yml
  vendor/libvirt.org/go/libvirt/connect.go
  vendor/libvirt.org/go/libvirt/connect_compat.h
  vendor/libvirt.org/go/libvirt/connect_wrapper.go
  vendor/libvirt.org/go/libvirt/connect_wrapper.h
  vendor/libvirt.org/go/libvirt/domain.go
  vendor/libvirt.org/go/libvirt/domain_compat.h
  vendor/libvirt.org/go/libvirt/domain_snapshot.go
  vendor/libvirt.org/go/libvirt/domain_snapshot_compat.h
  vendor/libvirt.org/go/libvirt/domain_wrapper.go
  vendor/libvirt.org/go/libvirt/domain_wrapper.h
  vendor/libvirt.org/go/libvirt/error.go
  vendor/libvirt.org/go/libvirt/events.go
  vendor/libvirt.org/go/libvirt/qemu.go
  vendor/libvirt.org/go/libvirt/qemu_wrapper.go
  vendor/libvirt.org/go/libvirt/qemu_wrapper.h
  vendor/libvirt.org/go/libvirt/typedparams.go
  vendor/modules.txt
Labels: size/L, release-note-none, lgtm, approved, dco-signoff: yes

#8038 Update orphaned vm alert
  hack/prom-rule-ci/prom-rules-tests.yaml
  pkg/virt-operator/resource/generate/components/prometheus.go
Labels: size/M, release-note-none, lgtm, approved, dco-signoff: yes, area/monitoring

#8204 Alter scsi test code to work without the lsscsi binary
  tests/io_utils.go
Labels: size/S, release-note-none, lgtm, approved, dco-signoff: yes

#7549 Add API subresources to get VM with expanded instancetype
  api/openapi-spec/swagger.json
  pkg/util/openapi/BUILD.bazel
  pkg/util/openapi/openapi_test.go
  pkg/util/webhooks/BUILD.bazel
  pkg/util/webhooks/webhooks.go
  pkg/virt-api/BUILD.bazel
  pkg/virt-api/api.go
  pkg/virt-api/definitions/BUILD.bazel
  pkg/virt-api/definitions/definitions.go
  pkg/virt-api/definitions/validator.go
  pkg/virt-api/rest/BUILD.bazel
  pkg/virt-api/rest/dialers.go
  pkg/virt-api/rest/expand.go
  pkg/virt-api/rest/expand_test.go
  pkg/virt-api/rest/streamer.go
  pkg/virt-api/rest/streamer_test.go
  pkg/virt-api/rest/subresource.go
  pkg/virt-api/webhooks/BUILD.bazel
  pkg/virt-api/webhooks/utils.go
  staging/src/kubevirt.io/client-go/kubecli/BUILD.bazel
  staging/src/kubevirt.io/client-go/kubecli/generated_mock_kubevirt.go
  staging/src/kubevirt.io/client-go/kubecli/instancetype.go
  staging/src/kubevirt.io/client-go/kubecli/kubevirt.go
  staging/src/kubevirt.io/client-go/kubecli/vm.go
  tests/subresource_api_test.go
  tools/openapispec/BUILD.bazel
  tools/openapispec/openapispec.go
Labels: release-note, size/XXL, lgtm, approved, dco-signoff: yes

#8071 virt-api: relax networkInterfaceMultiqueue semantics, introduce queueCount
  api/openapi-spec/swagger.json
  pkg/network/setup/netstat.go
  pkg/network/setup/netstat_test.go
  pkg/virt-api/webhooks/validating-webhook/admitters/vmi-create-admitter.go
  pkg/virt-api/webhooks/validating-webhook/admitters/vmi-create-admitter_test.go
  pkg/virt-operator/resource/generate/components/validations_generated.go
  staging/src/kubevirt.io/api/core/v1/types.go
  staging/src/kubevirt.io/api/core/v1/types_swagger_generated.go
  staging/src/kubevirt.io/client-go/api/openapi_generated.go
  tests/network/BUILD.bazel
  tests/network/vmi_infosource.go
  tests/vmi_multiqueue_test.go
Labels: size/L, sig/network, release-note, lgtm, approved, dco-signoff: yes

#8245 passt: updating passt rpm and run `make rpm-deps`
  WORKSPACE
  hack/bootstrap.sh
  rpm/BUILD.bazel
Labels: size/XL, release-note-none, lgtm, approved, dco-signoff: yes

#8215 add validation for spec.affinity
  go.mod
  go.sum
  pkg/virt-api/webhooks/validating-webhook/admitters/BUILD.bazel
  pkg/virt-api/webhooks/validating-webhook/admitters/validate-k8s-utils.go
  pkg/virt-api/webhooks/validating-webhook/admitters/vmi-create-admitter.go
  pkg/virt-api/webhooks/validating-webhook/admitters/vmi-create-admitter_test.go
  staging/src/kubevirt.io/api/go.mod
  staging/src/kubevirt.io/api/go.sum
  staging/src/kubevirt.io/client-go/go.mod
  staging/src/kubevirt.io/client-go/go.sum
  tests/migration_test.go
  tests/storage/storage.go
  vendor/k8s.io/api/policy/v1beta1/generated.proto
  vendor/k8s.io/api/policy/v1beta1/types.go
  vendor/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/deepcopy.go
  vendor/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1/conversion.go
  vendor/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1/deepcopy.go
  vendor/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1/zz_generated.conversion.go
  vendor/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1beta1/deepcopy.go
  vendor/k8s.io/apimachinery/pkg/api/validation/BUILD.bazel
  vendor/k8s.io/apimachinery/pkg/api/validation/doc.go
  vendor/k8s.io/apimachinery/pkg/api/validation/generic.go
  vendor/k8s.io/apimachinery/pkg/api/validation/objectmeta.go
  vendor/k8s.io/apimachinery/pkg/apis/meta/v1/validation/BUILD.bazel
  vendor/k8s.io/apimachinery/pkg/apis/meta/v1/validation/validation.go
  vendor/k8s.io/client-go/tools/pager/pager.go
  vendor/modules.txt
Labels: release-note, size/XXL, lgtm, approved, ok-to-test, dco-signoff: yes

#8209 Corrected issue with external boot which only kernelPath is specified without initrd path
  pkg/virt-handler/container-disk/mount.go
  pkg/virt-handler/isolation/isolation.go
  tests/vmi_kernel_boot_test.go
Labels: size/L, release-note-none, lgtm, approved, ok-to-test, dco-signoff: yes

#7846 Support topology spread constraints for virtual machine instances
  api/openapi-spec/swagger.json
  pkg/virt-controller/services/template.go
  pkg/virt-controller/services/template_test.go
  pkg/virt-operator/resource/generate/components/validations_generated.go
  staging/src/kubevirt.io/api/core/v1/deepcopy_generated.go
  staging/src/kubevirt.io/api/core/v1/types.go
  staging/src/kubevirt.io/api/core/v1/types_swagger_generated.go
  staging/src/kubevirt.io/client-go/api/openapi_generated.go
  tests/vmi_configuration_test.go
  tests/vmi_lifecycle_test.go
Labels: size/XL, release-note, lgtm, approved, ok-to-test, dco-signoff: yes

#8107 Add export of VMSnapshot volumes
  pkg/controller/virtinformers.go
  pkg/virt-api/webhooks/validating-webhook/admitters/vmexport-admitter.go
  pkg/virt-api/webhooks/validating-webhook/admitters/vmexport-admitter_test.go
  pkg/virt-controller/watch/application.go
  pkg/virt-controller/watch/application_test.go
  pkg/virt-controller/watch/export/BUILD.bazel
  pkg/virt-controller/watch/export/export.go
  pkg/virt-controller/watch/export/export_test.go
  pkg/virt-controller/watch/snapshot/restore.go
  staging/src/kubevirt.io/api/export/v1alpha1/types.go
  tests/storage/BUILD.bazel
  tests/storage/export.go
Labels: release-note, size/XXL, lgtm, approved, dco-signoff: yes

#8077 code cleanup: Use libvmi builder pattern instead of NewRandomVMI functions.
  tests/vmi_configuration_test.go
  tests/vmi_lifecycle_test.go
Labels: size/M, release-note-none, lgtm, approved, dco-signoff: yes, sig/code-quality

#8117 Code clean: Use libvmi builder pattern in tests/instancetype_test.go
  tests/instancetype_test.go
Labels: size/S, release-note-none, lgtm, approved, dco-signoff: yes, sig/code-quality

#8084 code cleanup:Using libvmi instead of NewRandomVMI functions in test_id:4643,test_id:4644
  tests/storage/datavolume.go
Labels: size/M, release-note-none, lgtm, approved, dco-signoff: yes, sig/code-quality

#8249 errcheck, network: always handle errors
  nogo_config.json
  pkg/network/cache/cache_test.go
  pkg/network/cache/domaininterface_test.go
  pkg/network/cache/podinterface_test.go
  pkg/network/dhcp/bridge_test.go
  pkg/network/dhcp/configurator.go
  pkg/network/dhcp/configurator_test.go
  pkg/network/dhcp/server/server.go
  pkg/network/dhcp/server/socket_listener.go
  pkg/network/domainspec/generators_test.go
  pkg/network/link/ethtool.go
  pkg/network/setup/netstat_test.go
  pkg/network/setup/network_test.go
  pkg/network/setup/podnic_test.go
Labels: size/L, sig/network, release-note-none, lgtm, approved, dco-signoff: yes, sig/code-quality

#8242 Stop including all [storage-req] tests in lanes
  automation/test.sh
  tests/README.md
  tests/vmi_lifecycle_test.go
Labels: size/S, release-note-none, lgtm, approved, dco-signoff: yes

#8049 guestfs: set the RunAsNonRoot
  pkg/virtctl/guestfs/guestfs.go
Labels: size/S, release-note, lgtm, approved, dco-signoff: yes

#8237 Fix SetDomainSpecStrWithHooks to handle mutating `OnDefineDomain` calls
  pkg/hooks/BUILD.bazel
  pkg/hooks/generated_mock_manager.go
  pkg/hooks/manager.go
  pkg/virt-launcher/virtwrap/util/BUILD.bazel
  pkg/virt-launcher/virtwrap/util/libvirt_helper.go
  pkg/virt-launcher/virtwrap/util/libvirt_helper_test.go
Labels: size/L, release-note-none, lgtm, approved, ok-to-test, dco-signoff: yes

#8231 Tolerate some errors in VM Create()
  tests/storage/restore.go
Labels: size/S, release-note-none, lgtm, approved, dco-signoff: yes

#8244 [release-v0.49] Must clear "cloneRequest" annotation on restore of PVC
  pkg/virt-controller/watch/snapshot/restore.go
  tests/storage/BUILD.bazel
  tests/storage/restore.go
  tests/utils.go
Labels: size/L, release-note-none, lgtm, approved, dco-signoff: yes

#8241 [release-v0.53] Must clear "cloneRequest" annotation on restore of PVC
  pkg/virt-controller/watch/snapshot/restore.go
  tests/libstorage/BUILD.bazel
  tests/libstorage/datavolume.go
  tests/storage/BUILD.bazel
  tests/storage/restore.go
Labels: size/L, release-note-none, lgtm, approved, dco-signoff: yes

#8207 Add OSBuild-Operator to the KubeVirt Adopters list
  ADOPTERS.md
Labels: size/XS, release-note-none, lgtm, approved, ok-to-test, dco-signoff: yes

#8271 libnode, e2e tests, teardown: ignore errors when uncordoning nodes
  tests/libnode/node.go
Labels: size/XS, release-note-none, lgtm, approved, dco-signoff: yes

#8256 libnet: avoid WithCloudInitNoCloudNetworkData's boolean arg
  tests/libvmi/cloudinit.go
  tests/libvmi/network.go
  tests/network/primary_pod_network.go
  tests/network/sriov.go
  tests/network/vmi_istio.go
  tests/network/vmi_multus.go
  tests/network/vmi_networking.go
  tests/utils.go
Labels: size/M, sig/network, release-note-none, lgtm, approved, dco-signoff: yes, sig/code-quality

#8268 Fix containerdisk unmount logic
  pkg/virt-handler/container-disk/mount.go
Labels: size/S, release-note-none, lgtm, approved, dco-signoff: yes

#8273 add validations for spec.topologySpreadConstraints
  pkg/virt-api/webhooks/validating-webhook/admitters/BUILD.bazel
  pkg/virt-api/webhooks/validating-webhook/admitters/validate-k8s-utils.go
  pkg/virt-api/webhooks/validating-webhook/admitters/vmi-create-admitter.go
  pkg/virt-api/webhooks/validating-webhook/admitters/vmi-create-admitter_test.go
Labels: size/L, release-note, lgtm, approved, ok-to-test, dco-signoff: yes

#8157 adding trilio to adopters list
  ADOPTERS.md
Labels: release-note, size/XS, lgtm, approved, ok-to-test, dco-signoff: yes

#7859 network: Primary intefrace should be first in Status.Interfaces list
  pkg/network/setup/netstat.go
  pkg/network/setup/netstat_test.go
  pkg/network/vmispec/interface.go
  pkg/network/vmispec/interface_test.go
  pkg/network/vmispec/network.go
  tests/network/BUILD.bazel
  tests/network/kubectl.go
Labels: size/L, sig/network, release-note, lgtm, approved, ok-to-test, dco-signoff: yes

#8278 Delete test that checks underlying DV's PVC won't trigger VM start
  tests/storage/datavolume.go
Labels: size/S, release-note-none, lgtm, approved, dco-signoff: yes

#8199 Add e2e test for KubeVirtVMIExcessiveMigrations alert
  tests/monitoring/BUILD.bazel
  tests/monitoring/monitoring.go
Labels: size/M, release-note-none, lgtm, approved, dco-signoff: yes

#8277 [e2e tests]: fix flaky test_id 8482 in migration suite
  tests/migration_test.go
Labels: size/M, release-note-none, lgtm, approved, dco-signoff: yes

#8134 Support DV garbage collection
  hack/cluster-deploy.sh
  pkg/virt-controller/services/template.go
  pkg/virt-controller/watch/BUILD.bazel
  pkg/virt-controller/watch/export/export.go
  pkg/virt-controller/watch/export/export_test.go
  pkg/virt-controller/watch/snapshot/restore.go
  pkg/virt-controller/watch/snapshot/restore_base.go
  pkg/virt-controller/watch/snapshot/snapshot.go
  pkg/virt-controller/watch/util/BUILD.bazel
  pkg/virt-controller/watch/util/util.go
  pkg/virt-controller/watch/vm.go
  pkg/virt-controller/watch/vm_test.go
  pkg/virt-controller/watch/vmi.go
  pkg/virt-controller/watch/vmi_test.go
  staging/src/kubevirt.io/api/core/v1/types.go
  tests/libstorage/BUILD.bazel
  tests/libstorage/datavolume.go
  tests/migration_test.go
  tests/pool_test.go
  tests/storage/clone.go
  tests/storage/datavolume.go
  tests/storage/export.go
  tests/storage/hotplug.go
  tests/storage/imageupload.go
  tests/storage/restore.go
  tests/storage/snapshot.go
  tests/storage/storage.go
  tests/utils.go
  tests/vm_test.go
  tests/vmi_configuration_test.go
Labels: size/XL, release-note, lgtm, approved, dco-signoff: yes

#8149 Add a '--cache' flag to virtctl for controlling disk cache mode
  pkg/virtctl/vm/vm.go
  tests/storage/hotplug.go
Labels: size/L, release-note, lgtm, approved, ok-to-test, dco-signoff: yes

#8248 Tests: Handle various names of the qemu binary
  tests/vmi_configuration_test.go
Labels: size/S, release-note-none, lgtm, approved, dco-signoff: yes

#8298 [e2e]: Fix a panic call in BeforeSuite
  tests/testsuite/manifest.go
Labels: size/XS, release-note-none, lgtm, approved, dco-signoff: yes

#8261 e2e tests, libnode: only uncordon node once
  tests/libnode/BUILD.bazel
  tests/libnode/node.go
  tests/migration_test.go
Labels: size/S, release-note-none, lgtm, approved, dco-signoff: yes

#6966 Capture UPDATE/PATCH considerations when working with controllers
  docs/reviewer-guide.md
Labels: size/M, release-note-none, lgtm, approved, dco-signoff: yes

#8309 virt-api: Remove unnecessary goroutine
  pkg/virt-api/rest/profiler.go
Labels: size/M, release-note-none, lgtm, approved, dco-signoff: yes, sig/code-quality

#8301 Vgpu check mdev is present on allocation
  pkg/virt-handler/device-manager/mediated_device.go
Labels: size/S, release-note-none, lgtm, approved, dco-signoff: yes

#8222 Address some parallel testing complications that cause flakes
  tests/libstorage/pvc.go
  tests/reporter/kubernetes.go
  tests/tests_suite_test.go
  tests/testsuite/fixture.go
  tests/testsuite/manifest.go
Labels: size/M, release-note-none, lgtm, approved, dco-signoff: yes

#8305 [release-0.44] Fix `KubeVirtComponentExceedsRequestedMemory` alert on duplicate series
  hack/prom-rule-ci/prom-rules-tests.yaml
  pkg/virt-operator/resource/generate/components/crds.go
Labels: size/XS, release-note-none, lgtm, approved, dco-signoff: yes

#8006 Introduce AutoattachInputDevice to Devices and a PreferredAutoattachInputDevice preference
  api/openapi-spec/swagger.json
  pkg/instancetype/instancetype.go
  pkg/instancetype/instancetype_test.go
  pkg/virt-api/webhooks/mutating-webhook/mutators/vmi-mutator_test.go
  pkg/virt-api/webhooks/validating-webhook/admitters/vmi-create-admitter.go
  pkg/virt-api/webhooks/validating-webhook/admitters/vmi-create-admitter_test.go
  pkg/virt-controller/watch/BUILD.bazel
  pkg/virt-controller/watch/vm.go
  pkg/virt-controller/watch/vm_test.go
  pkg/virt-launcher/virtwrap/api/schema.go
  pkg/virt-launcher/virtwrap/converter/converter.go
  pkg/virt-launcher/virtwrap/converter/converter_test.go
  pkg/virt-operator/resource/generate/components/validations_generated.go
  staging/src/kubevirt.io/api/core/v1/deepcopy_generated.go
  staging/src/kubevirt.io/api/core/v1/defaults.go
  staging/src/kubevirt.io/api/core/v1/schema.go
  staging/src/kubevirt.io/api/core/v1/schema_swagger_generated.go
  staging/src/kubevirt.io/api/instancetype/v1alpha1/deepcopy_generated.go
  staging/src/kubevirt.io/api/instancetype/v1alpha1/types.go
  staging/src/kubevirt.io/api/instancetype/v1alpha1/types_swagger_generated.go
  staging/src/kubevirt.io/client-go/api/openapi_generated.go
  tests/vmidefaults_test.go
Labels: size/XL, release-note, lgtm, approved, dco-signoff: yes, area/instancetype

#8266 paast, e2e, Skip if featureGate is disabled
  tests/network/vmi_istio.go
  tests/network/vmi_passt.go
Labels: size/S, sig/network, release-note-none, lgtm, approved, dco-signoff: yes

#8299 tests: Refactor SR-IOV tests
  tests/network/sriov.go
Labels: sig/network, size/XL, release-note-none, lgtm, approved, dco-signoff: yes, sig/code-quality

#7007 set scsi as default disk bus on Arm64
  pkg/virt-api/webhooks/BUILD.bazel
  pkg/virt-api/webhooks/amd64.go
  pkg/virt-api/webhooks/arm64.go
  pkg/virt-api/webhooks/mutating-webhook/mutators/vmi-mutator.go
  pkg/virt-api/webhooks/mutating-webhook/mutators/vmi-mutator_test.go
  pkg/virt-launcher/virtwrap/converter/BUILD.bazel
  pkg/virt-launcher/virtwrap/converter/converter_test.go
  staging/src/kubevirt.io/api/core/v1/defaults.go
Labels: size/L, release-note-none, lgtm, approved, dco-signoff: yes

#8159 Add support for USB Disks
  api/openapi-spec/swagger.json
  pkg/virt-api/webhooks/validating-webhook/admitters/vmi-create-admitter.go
  pkg/virt-api/webhooks/validating-webhook/admitters/vmi-create-admitter_test.go
  pkg/virt-launcher/virtwrap/converter/converter.go
  pkg/virt-operator/resource/generate/components/validations_generated.go
  staging/src/kubevirt.io/api/core/v1/schema.go
  staging/src/kubevirt.io/api/core/v1/schema_swagger_generated.go
  staging/src/kubevirt.io/client-go/api/openapi_generated.go
  tests/libvmi/storage.go
  tests/migration_test.go
  tests/storage/storage.go
Labels: size/L, release-note, lgtm, approved, dco-signoff: yes

#8324 e2e, istio: Wait for VMI to launch before Logging in
  tests/network/vmi_istio.go
Labels: sig/network, size/XS, release-note-none, lgtm, approved, dco-signoff: yes

#8340 Update kubevirt_vmi_memory_used_bytes type
  docs/metrics.md
  tools/doc-generator/doc-generator.go
Labels: size/XS, release-note-none, lgtm, approved, dco-signoff: yes

#8339 instancetype: Drop PreferredMachineType test assertions
  tests/instancetype_test.go
Labels: size/XS, release-note-none, lgtm, approved, dco-signoff: yes, area/instancetype

#8349 Add a functional test to ensure we catch bogus disk paths
  pkg/virt-api/webhooks/validating-webhook/admitters/vmi-create-admitter.go
  tests/container_disk_test.go
Labels: size/S, release-note-none, lgtm, approved, dco-signoff: yes

#8247 Bump virtlogd memory requirement to 18Mi and libvirtd to 35Mi
  pkg/virt-controller/services/template.go
  pkg/virt-controller/services/template_test.go
  tests/vmi_configuration_test.go
Labels: size/M, release-note-none, lgtm, approved, dco-signoff: yes

#8327 Legacy GAVersion matching did not report a reason for failure
  pkg/virt-handler/vm.go
Labels: size/XS, release-note-none, lgtm, approved, dco-signoff: yes

#8341 Fix VMClone OpenShift owner reference requirement
  manifests/generated/operator-csv.yaml.in
  manifests/generated/rbac-operator.authorization.k8s.yaml.in
  pkg/virt-operator/resource/generate/rbac/controller.go
Labels: size/M, release-note-none, lgtm, approved, dco-signoff: yes

#8325 istio,handler: enable ipv4 route_localnet for k6t-eth0
  pkg/network/driver/common.go
  pkg/network/driver/generated_mock_common.go
  pkg/network/infraconfigurators/masquerade.go
  pkg/network/infraconfigurators/masquerade_test.go
  pkg/util/sysctl/sysctl.go
Labels: size/S, sig/network, release-note, lgtm, approved, dco-signoff: yes

#8326 virtctl: Do not log wrapped ssh command by default
  pkg/virtctl/ssh/wrapped.go
Labels: release-note, size/XS, lgtm, approved, dco-signoff: yes

#8351 Add DV garbage collection tests
  tests/libstorage/datavolume.go
  tests/storage/datavolume.go
  tests/storage/snapshot.go
Labels: size/L, release-note-none, lgtm, approved, dco-signoff: yes

#8075 code cleanup: Use libvmi builder pattern instead of NewRandomVMI function
  tests/usbredir_test.go
  tests/vmi_configuration_test.go
Labels: size/M, release-note-none, lgtm, approved, kind/build-change, dco-signoff: yes, sig/code-quality

#8170 Update recording rules names
  pkg/virt-operator/resource/generate/components/prometheus.go
Labels: size/S, release-note-none, lgtm, approved, ok-to-test, dco-signoff: yes, area/monitoring

#8069 Deprecate VirtualMachineInstancePresets
  api/openapi-spec/swagger.json
  pkg/virt-api/webhooks/mutating-webhook/mutators/vmi-mutator.go
  pkg/virt-api/webhooks/mutating-webhook/mutators/vmi-mutator_test.go
  pkg/virt-operator/resource/generate/components/crds.go
  pkg/virt-operator/resource/generate/components/validations_generated.go
  staging/src/kubevirt.io/api/core/v1/types.go
  staging/src/kubevirt.io/api/core/v1/types_swagger_generated.go
  staging/src/kubevirt.io/client-go/api/openapi_generated.go
Labels: size/M, sig/network, release-note, lgtm, approved, dco-signoff: yes, area/instancetype

#7636 [release-0.49] virt-launcher: adjust overhead calculation for processes
  pkg/virt-controller/services/template.go
  pkg/virt-controller/services/template_test.go
  tests/vmi_configuration_test.go
Labels: size/L, release-note-none, lgtm, approved, dco-signoff: yes

#8259 Errcheck lint virt controller subtree
  nogo_config.json
  pkg/storage/export/export/export.go
  pkg/storage/export/export/export_test.go
  pkg/storage/snapshot/snapshot_base.go
  pkg/virt-controller/watch/BUILD.bazel
  pkg/virt-controller/watch/application.go
  pkg/virt-controller/watch/application_test.go
  pkg/virt-controller/watch/migration_test.go
  pkg/virt-controller/watch/node.go
  pkg/virt-controller/watch/node_test.go
  pkg/virt-controller/watch/pool_test.go
  pkg/virt-controller/watch/vm_test.go
  pkg/virt-controller/watch/vmi.go
  pkg/virt-controller/watch/vmi_test.go
  pkg/virt-controller/watch/workload-updater/workload-updater_test.go
Labels: size/L, sig/network, release-note-none, lgtm, approved, dco-signoff: yes

#8313 code refactor: mount in virt-handler for hotplugged volumes
  pkg/virt-handler/hotplug-disk/mount.go
Labels: size/M, release-note-none, lgtm, approved, dco-signoff: yes

#8217 virt-freezer exit 0 if no guest agent
  cmd/virt-freezer/main.go
  tests/storage/snapshot.go
Labels: size/M, release-note-none, lgtm, approved, dco-signoff: yes

#7990 Remove SRIOVLiveMigration feature-gate
  pkg/virt-config/configuration_test.go
  pkg/virt-config/feature-gates.go
  pkg/virt-handler/vm.go
  pkg/virt-handler/vm_test.go
  tests/network/sriov.go
Labels: size/M, sig/network, release-note, lgtm, approved, dco-signoff: yes

#8367 fix guest memory setting
  pkg/virt-launcher/virtwrap/converter/converter_test.go
  pkg/virt-launcher/virtwrap/converter/vcpu/vcpu.go
  tests/vmi_configuration_test.go
Labels: size/M, release-note, lgtm, approved, dco-signoff: yes

#7645 [release-0.44] virt-launcher: adjust overhead calculation for processes
  pkg/virt-controller/services/template.go
  pkg/virt-controller/services/template_test.go
  tests/vmi_configuration_test.go
Labels: size/L, release-note-none, lgtm, approved, dco-signoff: yes

#8334 [release-0.49] Manual backport of 8222 - parallel testing complications
  tests/reporter/kubernetes.go
  tests/tests_suite_test.go
  tests/utils.go
Labels: size/M, release-note-none, lgtm, approved, dco-signoff: yes

#8333 [release-0.53] Manual backport of 8222 - parallel testing complications
  tests/reporter/kubernetes.go
  tests/tests_suite_test.go
  tests/testsuite/fixture.go
  tests/testsuite/manifest.go
  tests/utils.go
Labels: size/M, release-note-none, lgtm, approved, dco-signoff: yes

#8312 [Clean Code] Tiny changes in storageclass.go
  tests/libstorage/storageclass.go
Labels: size/M, release-note-none, lgtm, approved, dco-signoff: yes, sig/code-quality

#8370 [release-0.49] virt-launcher overhead: bump virtlauncher and virtlogd
  pkg/virt-controller/services/template.go
  pkg/virt-controller/services/template_test.go
  tests/vmi_configuration_test.go
Labels: size/M, release-note-none, lgtm, approved, dco-signoff: yes

#8257 Add vm export vm
  pkg/controller/virtinformers.go
  pkg/storage/export/export/BUILD.bazel
  pkg/storage/export/export/export.go
  pkg/storage/export/export/export_test.go
  pkg/storage/export/export/links.go
  pkg/storage/export/export/pvc-source.go
  pkg/storage/export/export/pvc-source_test.go
  pkg/storage/export/export/vm-source.go
  pkg/storage/export/export/vm-source_test.go
  pkg/storage/export/export/vmsnapshot-source.go
  pkg/storage/export/export/vmsnapshot-source_test.go
  pkg/virt-api/webhooks/validating-webhook/admitters/vmexport-admitter.go
  pkg/virt-api/webhooks/validating-webhook/admitters/vmexport-admitter_test.go
  pkg/virt-controller/watch/application.go
  pkg/virt-controller/watch/application_test.go
  tests/libstorage/datavolume.go
  tests/storage/export.go
  tests/storage/restore.go
Labels: release-note, size/XXL, lgtm, approved, dco-signoff: yes

#8369 builder: Don't set up multiarch support multiple times
  hack/builder/build.sh
Labels: size/XS, release-note-none, lgtm, approved, dco-signoff: yes

#8372 Restore test with deleting source pvc
  tests/storage/restore.go
Labels: size/S, release-note-none, lgtm, approved, dco-signoff: yes

#8307 tests, sriov: Wait for VMI removal at test teardown
  tests/network/sriov.go
  tests/utils.go
Labels: size/M, sig/network, release-note-none, lgtm, approved, dco-signoff: yes

#8337 virtctl: Separate terminal logic for linux and windows
  pkg/virtctl/ssh/BUILD.bazel
  pkg/virtctl/ssh/native.go
  pkg/virtctl/ssh/resize_windows.go
  pkg/virtctl/ssh/terminal_unix.go
  pkg/virtctl/ssh/terminal_windows.go
Labels: size/L, release-note, lgtm, approved, dco-signoff: yes

#8378 [e2e tests]: fix flaky migration test 1862
  tests/migration_test.go
Labels: size/XS, release-note-none, lgtm, approved, dco-signoff: yes

#8373 Fix export restore PVC owner reference
  pkg/storage/export/export/export.go
  pkg/storage/export/export/vmsnapshot-source.go
  pkg/storage/export/export/vmsnapshot-source_test.go
Labels: size/S, release-note-none, lgtm, approved, dco-signoff: yes

#8380 Stop enabling deprecated live migration feature gate as part of functional tests initialization
  tests/testsuite/kubevirtresource.go
Labels: size/XS, release-note-none, lgtm, approved, dco-signoff: yes

#8377 chore: remove duplicate word in comments
  pkg/container-disk/container-disk_test.go
  pkg/virt-controller/watch/vm.go
  tests/libvmi/vmi.go
  tests/network/services.go
  tests/vmi_configuration_test.go
Labels: size/S, sig/network, release-note-none, lgtm, approved, needs-ok-to-test, dco-signoff: yes

#8129 Rancher proxy uris
  staging/src/kubevirt.io/client-go/kubecli/guestfs.go
  staging/src/kubevirt.io/client-go/kubecli/version.go
  staging/src/kubevirt.io/client-go/kubecli/vm.go
  staging/src/kubevirt.io/client-go/kubecli/vmi.go
Labels: size/M, sig/network, release-note, lgtm, approved, ok-to-test, dco-signoff: yes
