Repository kubevirt/kubevirt, pull requests merged in 2022-05, with the labels that each got.

#7353 Refactor VMI lifecycle handler
  pkg/virt-handler/rest/lifecycle.go
Labels: size/L, release-note-none, lgtm, approved, ok-to-test, dco-signoff: yes

#7591 tests, network: Conformance migration test with emulation fix
  tests/network/vmi_networking.go
Labels: size/M, sig/network, release-note-none, lgtm, approved, dco-signoff: yes

#7651 virt-launcher: disable isa-debugcon on Arm64
  pkg/virt-launcher/virtwrap/converter/converter.go
Labels: size/XS, release-note-none, lgtm, approved, dco-signoff: yes

#7657 tests, libvmi: Support Alpine & Cirros VM/s on ARM64
  tests/libvmi/BUILD.bazel
  tests/libvmi/factory.go
Labels: size/S, release-note-none, lgtm, approved, dco-signoff: yes

#7649 [e2e]: improve the virt-handler rate limiter test
  tests/infra_test.go
Labels: size/S, release-note-none, lgtm, approved, dco-signoff: yes

#7667 Quarantine test_id:8482 due to flakiness
  tests/migration_test.go
Labels: size/XS, release-note-none, lgtm, approved, dco-signoff: yes

#7670 OWENERS: Removing a couple of folks who are not active anymore
  OWNERS
  OWNERS_ALIASES
Labels: size/S, release-note-none, lgtm, approved, dco-signoff: yes

#7675 fix rbac for virtualmachineinstances/portforward
  manifests/generated/operator-csv.yaml.in
  manifests/generated/rbac-operator.authorization.k8s.yaml.in
  pkg/virt-operator/resource/generate/rbac/cluster.go
  pkg/virt-operator/resource/generate/rbac/operator.go
  tests/access_test.go
Labels: size/S, release-note-none, lgtm, approved, dco-signoff: yes

#7673 Make names of access tests around test_id:2921 unique
  tests/access_test.go
Labels: size/S, release-note-none, lgtm, approved, dco-signoff: yes

#7677 Virt TMP testcase
  tests/vmi_tpm_test.go
Labels: size/XS, release-note-none, lgtm, approved, ok-to-test, dco-signoff: yes

#7688 [release-0.41] Show migration progress timeout in actual seconds
  pkg/virt-launcher/virtwrap/live-migration-source.go
  pkg/virt-launcher/virtwrap/manager_test.go
Labels: size/M, release-note-none, lgtm, approved, dco-signoff: yes

#7686 [release-0.49] Show migration progress timeout in actual seconds
  pkg/virt-launcher/virtwrap/live-migration-source.go
  pkg/virt-launcher/virtwrap/manager_test.go
Labels: size/M, release-note-none, lgtm, approved, dco-signoff: yes

#7665 use ProductComponent instead of hardcoded kubevirt value in test_id:8235
  tests/operator_test.go
Labels: size/XS, release-note-none, lgtm, approved, dco-signoff: yes

#7349 Remove Get Nodes API calls
  cmd/virt-handler/virt-handler.go
  pkg/virt-handler/node-labeller/cpu_plugin.go
  pkg/virt-handler/node-labeller/cpu_plugin_test.go
  pkg/virt-handler/node-labeller/model.go
  pkg/virt-handler/node-labeller/node_labeller.go
  pkg/virt-handler/vm.go
  pkg/virt-handler/vm_test.go
Labels: size/M, release-note-none, lgtm, approved, dco-signoff: yes

#7678 Add puzl.ee to adopters
  ADOPTERS.md
Labels: size/XS, release-note-none, lgtm, approved, ok-to-test, dco-signoff: yes

#7691 Fix root to nonroot migration
  pkg/virt-controller/watch/migration.go
  tests/migration_test.go
Labels: size/S, release-note-none, lgtm, approved, dco-signoff: yes

#7699 added test_ids
  tests/migration_test.go
Labels: size/XS, release-note-none, lgtm, approved, ok-to-test, dco-signoff: yes

#7696 Initialize properly libvirt.DomainJobInfo struct
  pkg/virt-launcher/virtwrap/live-migration-source.go
  pkg/virt-launcher/virtwrap/manager_test.go
Labels: size/M, release-note-none, lgtm, approved, dco-signoff: yes

#7619 [release-0.50] Add Virtual Machine name label to virt-launcher pod
  pkg/virt-controller/services/BUILD.bazel
  pkg/virt-controller/services/template.go
  pkg/virt-controller/services/template_test.go
  staging/src/kubevirt.io/api/core/v1/types.go
Labels: size/M, release-note, lgtm, approved, dco-signoff: yes

#7617 [release-0.49] Add Virtual Machine name label to virt-launcher pod
  pkg/virt-controller/services/BUILD.bazel
  pkg/virt-controller/services/template.go
  pkg/virt-controller/services/template_test.go
  staging/src/kubevirt.io/api/core/v1/types.go
Labels: size/M, release-note, lgtm, approved, dco-signoff: yes

#7592 Handle virtctl guestfs incorrectly assuming image name, grant access to /guestfs endpoint
  cmd/subresource-access-test/subresource-access-test.go
  manifests/generated/operator-csv.yaml.in
  manifests/generated/rbac-operator.authorization.k8s.yaml.in
  pkg/virt-api/api.go
  pkg/virt-operator/resource/generate/rbac/cluster.go
  pkg/virtctl/guestfs/guestfs.go
  pkg/virtctl/guestfs/guestfs_test.go
  staging/src/kubevirt.io/client-go/kubecli/guestfs.go
  tests/subresource_api_test.go
Labels: size/L, release-note, lgtm, approved, dco-signoff: yes

#7706 k8s reporter: Remove deprecated parts
  tests/reporter/kubernetes.go
Labels: size/M, sig/network, release-note-none, lgtm, approved, dco-signoff: yes

#7465 Add metrics for migrations and respective phases
  pkg/monitoring/migration/BUILD.bazel
  pkg/monitoring/migration/prometheus.go
  pkg/virt-controller/watch/BUILD.bazel
  pkg/virt-controller/watch/application.go
  pkg/virt-controller/watch/migration.go
  pkg/virt-controller/watch/migration_test.go
  vendor/github.com/prometheus/client_golang/prometheus/testutil/BUILD.bazel
  vendor/github.com/prometheus/client_golang/prometheus/testutil/lint.go
  vendor/github.com/prometheus/client_golang/prometheus/testutil/promlint/BUILD.bazel
  vendor/github.com/prometheus/client_golang/prometheus/testutil/promlint/promlint.go
  vendor/github.com/prometheus/client_golang/prometheus/testutil/testutil.go
  vendor/modules.txt
Labels: release-note, size/XXL, lgtm, approved, dco-signoff: yes, area/monitoring

#7543 tests: Don't try to log a paused VMI
  tests/reporter/kubernetes.go
Labels: size/M, release-note-none, lgtm, approved, dco-signoff: yes

#7713 non-root: use /var/run/kubevirt-private for cache and config files
  cmd/virt-launcher/BUILD.bazel
  pkg/virt-controller/services/template.go
  pkg/virt-launcher/virtwrap/util/libvirt_helper.go
Labels: size/S, release-note-none, lgtm, approved, kind/build-change, dco-signoff: yes

#7731 Increase memory in upgrade test
  tests/operator_test.go
Labels: size/XS, release-note-none, lgtm, approved, dco-signoff: yes

#7709 Add test id for vm snapshot metrics functest
  tests/monitoring/monitoring.go
Labels: size/XS, release-note-none, lgtm, approved, dco-signoff: yes

#7719 [release-0.44] Manual backport of 7592
  cmd/subresource-access-test/subresource-access-test.go
  manifests/generated/operator-csv.yaml.in
  manifests/generated/rbac-operator.authorization.k8s.yaml.in
  pkg/virt-api/api.go
  pkg/virt-operator/resource/generate/rbac/cluster.go
  pkg/virtctl/guestfs/guestfs.go
  pkg/virtctl/guestfs/guestfs_test.go
  staging/src/kubevirt.io/client-go/kubecli/guestfs.go
  tests/subresource_api_test.go
Labels: size/L, release-note, lgtm, approved, dco-signoff: yes

#7718 [release-0.49] Manual backport of 7592
  cmd/subresource-access-test/subresource-access-test.go
  manifests/generated/operator-csv.yaml.in
  manifests/generated/rbac-operator.authorization.k8s.yaml.in
  pkg/virt-api/api.go
  pkg/virt-operator/resource/generate/rbac/cluster.go
  pkg/virtctl/guestfs/guestfs.go
  pkg/virtctl/guestfs/guestfs_test.go
  staging/src/kubevirt.io/client-go/kubecli/guestfs.go
  tests/subresource_api_test.go
Labels: size/L, release-note, lgtm, approved, dco-signoff: yes

#7564 Remove assumption in changeOwnershipOfBlockDevices
  pkg/virt-handler/non-root.go
Labels: size/M, release-note-none, lgtm, approved, dco-signoff: yes

#7687 [release-0.44] Show migration progress timeout in actual seconds
  pkg/virt-launcher/virtwrap/live-migration-source.go
  pkg/virt-launcher/virtwrap/manager_test.go
Labels: size/M, release-note-none, lgtm, approved, dco-signoff: yes

#7711 [CI Stabilization]: disableNodeLabeller() - use patch instead of update
  pkg/util/nodes/BUILD.bazel
  pkg/util/nodes/nodes.go
  pkg/virt-controller/watch/topology/BUILD.bazel
  pkg/virt-controller/watch/topology/nodetopologyupdater.go
  tests/libnode/BUILD.bazel
  tests/libnode/node.go
  tests/migration_test.go
Labels: size/L, release-note-none, lgtm, approved, dco-signoff: yes

#7724 fix perf test removing a deprecated parameter
  automation/perfscale-test.sh
  hack/perfscale-tests.sh
Labels: size/XS, release-note-none, lgtm, approved, dco-signoff: yes

#7529 NoReadyVirtController and NoReadyVirtOperator are never triggered
  hack/prom-rule-ci/prom-rules-tests.yaml
  hack/prom-rule-ci/verify-rules.sh
  pkg/virt-operator/resource/generate/components/prometheus.go
Labels: size/M, release-note, lgtm, approved, dco-signoff: yes, area/monitoring

#7640 Improve errors in `PreCloudInitIso` method
  pkg/hooks/manager.go
Labels: size/S, release-note-none, lgtm, approved, ok-to-test, dco-signoff: yes

#7733 builder: Clean up and reduce in size
  hack/builder/Dockerfile
  hack/builder/build.sh
Labels: size/M, release-note-none, lgtm, approved, dco-signoff: yes

#7694 kubectl_test: use the more succinct libvmi.NewCirros
  tests/kubectl_test.go
Labels: size/XS, release-note-none, lgtm, approved, dco-signoff: yes, sig/code-quality

#7712 Use gomega.Equal instead of reflect.DeepEqual
  tests/migration_test.go
Labels: size/XS, release-note-none, lgtm, approved, ok-to-test, dco-signoff: yes, sig/code-quality

#7740 tests: move ContainsCrt into its only user
  tests/infra_test.go
  tests/utils.go
Labels: size/M, release-note-none, lgtm, approved, dco-signoff: yes

#7672 Adding and fixing support for host-model migration in heterogeneous cluster
  pkg/virt-controller/watch/migration.go
  pkg/virt-controller/watch/migration_test.go
  pkg/virt-handler/node-labeller/cpu_plugin.go
  pkg/virt-handler/node-labeller/cpu_plugin_test.go
  tests/migration_test.go
  tests/utils.go
Labels: size/L, release-note-none, lgtm, approved, dco-signoff: yes

#7741 tests: move GenerateRandomMac into the network package
  tests/network/BUILD.bazel
  tests/network/mac.go
  tests/network/macvtap.go
  tests/network/sriov.go
  tests/network/vmi_multus.go
  tests/utils.go
Labels: size/M, sig/network, release-note-none, lgtm, approved, dco-signoff: yes, sig/code-quality

#7539 Simplify methods and functions in `live-migration-source` file
  pkg/virt-launcher/virtwrap/live-migration-source.go
Labels: size/L, release-note-none, lgtm, approved, ok-to-test, dco-signoff: yes

#7734 Fix double free of VirDomain object
  pkg/virt-launcher/virtwrap/cli/libvirt.go
Labels: size/XS, release-note-none, lgtm, approved, dco-signoff: yes

#7689 Update networking section of components overview
  docs/components.md
Labels: size/M, release-note-none, lgtm, approved, dco-signoff: yes

#7345 Fix/Skip tests that are incompatible with single-replica environments
  automation/test.sh
  hack/common.sh
  hack/functests.sh
  manifests/generated/operator-csv.yaml.in
  pkg/virt-operator/resource/generate/components/daemonsets.go
  pkg/virt-operator/resource/generate/components/deployments.go
  tests/canary_upgrade_test.go
  tests/flags/flags.go
  tests/framework/checks/checks.go
  tests/framework/checks/skips.go
  tests/infra_test.go
  tests/kubectl_test.go
  tests/operator_test.go
  tests/swap_test.go
Labels: size/L, release-note-none, lgtm, approved, dco-signoff: yes

#7758 test, Fail on namespace creation failure
  tests/testsuite/namespace.go
Labels: size/XS, release-note-none, lgtm, approved, dco-signoff: yes

#7685 virt-launcher overhead: bump virtlogd and add logs to functest
  pkg/virt-controller/services/template.go
  pkg/virt-controller/services/template_test.go
  tests/vmi_configuration_test.go
Labels: size/M, release-note-none, lgtm, approved, dco-signoff: yes

#7773 [release-0.53] Fix/Skip tests that are incompatible with single-replica environments
  automation/test.sh
  hack/common.sh
  hack/functests.sh
  manifests/generated/operator-csv.yaml.in
  pkg/virt-operator/resource/generate/components/daemonsets.go
  pkg/virt-operator/resource/generate/components/deployments.go
  tests/canary_upgrade_test.go
  tests/flags/flags.go
  tests/framework/checks/checks.go
  tests/framework/checks/skips.go
  tests/infra_test.go
  tests/kubectl_test.go
  tests/operator_test.go
  tests/swap_test.go
Labels: size/L, release-note-none, lgtm, approved, dco-signoff: yes

#7618 Remove VirtualMachineInstance volume disk or filesystem requirement
  examples/vm-cirros-sata.yaml
  examples/vm-template-windows2012r2.yaml
  examples/vmi-sata.yaml
  examples/vmi-windows.yaml
  pkg/virt-api/webhooks/mutating-webhook/mutators/vmi-mutator.go
  pkg/virt-api/webhooks/mutating-webhook/mutators/vmi-mutator_test.go
  pkg/virt-api/webhooks/validating-webhook/admitters/vmi-create-admitter.go
  pkg/virt-api/webhooks/validating-webhook/admitters/vmi-create-admitter_test.go
  pkg/virt-api/webhooks/validating-webhook/admitters/vms-admitter_test.go
  tests/vmi_configuration_test.go
  tests/vmidefaults_test.go
  tools/vms-generator/utils/utils.go
  tools/vms-generator/vms-generator.go
Labels: size/L, release-note, lgtm, approved, dco-signoff: yes

#7739 Allow edit/admin user to create migration via virtctl
  manifests/generated/operator-csv.yaml.in
  manifests/generated/rbac-operator.authorization.k8s.yaml.in
  pkg/virt-operator/resource/generate/rbac/cluster.go
Labels: release-note, size/XS, lgtm, approved, dco-signoff: yes

#7766 Create and delete the kubevirt-density namespace
  automation/perfscale-test.sh
Labels: size/XS, release-note-none, lgtm, approved, dco-signoff: yes

#7748 tests, libnet, cloudinit: Drop redundant slice init
  tests/libnet/cloudinit.go
Labels: size/XS, release-note-none, lgtm, approved, dco-signoff: yes

#7790 Update kubevirt builder image
  hack/dockerized
Labels: size/XS, release-note-none, lgtm, approved, dco-signoff: yes

#7475 Add more descriptive message for failure during live-migration
  pkg/virt-handler/BUILD.bazel
  pkg/virt-handler/vm.go
  pkg/virt-handler/vm_test.go
Labels: size/S, release-note, lgtm, approved, ok-to-test, dco-signoff: yes

#7793 [release-0.41]Post copy 4747 fix
  tests/migration_test.go
Labels: size/XS, release-note-none, lgtm, approved, dco-signoff: yes

#7534 Refactor virt controller template machine container spec
  pkg/virt-controller/services/BUILD.bazel
  pkg/virt-controller/services/rendercontainer.go
  pkg/virt-controller/services/rendercontainer_test.go
  pkg/virt-controller/services/template.go
Labels: size/XL, release-note-none, lgtm, approved, dco-signoff: yes, sig/code-quality

#7498 Find interface by mac sriov helper
  tests/network/sriov.go
Labels: size/M, sig/network, release-note-none, lgtm, approved, dco-signoff: yes, sig/code-quality

#7789 Remove unused `HostDeviceList` struct
  pkg/virt-launcher/virtwrap/converter/converter.go
Labels: size/S, release-note-none, lgtm, approved, ok-to-test, dco-signoff: yes

#7797 Quarantine flaky VMI pause tests
  tests/storage/storage.go
Labels: size/XS, release-note-none, lgtm, approved, dco-signoff: yes

#7801 Fix incorrect `emitempty` tag with `omitempty`
  pkg/virt-launcher/virtwrap/api/schema.go
Labels: size/S, release-note, lgtm, approved, ok-to-test, dco-signoff: yes

#7744 [e2e]: provide more information upon failure in executing commands in pods
  tests/infra_test.go
Labels: size/M, release-note-none, lgtm, approved, dco-signoff: yes

#7770 The host-model cpuModel isn't usually fully supported in the nodes and we should take it into account
  pkg/virt-controller/watch/migration.go
  pkg/virt-controller/watch/migration_test.go
  pkg/virt-handler/node-labeller/cpu_plugin.go
  pkg/virt-handler/node-labeller/cpu_plugin_test.go
  pkg/virt-handler/node-labeller/node_labeller.go
  staging/src/kubevirt.io/api/core/v1/types.go
  tests/infra_test.go
  tests/migration_test.go
  tests/utils.go
Labels: size/L, release-note-none, lgtm, approved, dco-signoff: yes

#7567 Remove incorrect reason when logging
  pkg/virt-launcher/virtwrap/manager.go
Labels: size/XS, release-note-none, lgtm, approved, ok-to-test, dco-signoff: yes

#7809 update asciinema demo for README
  README.md
Labels: size/XS, release-note-none, lgtm, approved, ok-to-test, dco-signoff: yes

#7784 Rename `devises` to `devices`
  pkg/virt-launcher/virtwrap/device/hostdevice/generic/addresspool.go
Labels: size/S, release-note-none, lgtm, approved, needs-ok-to-test, dco-signoff: yes

#7517 Memory dump
  api/openapi-spec/swagger.json
  cmd/virt-launcher/virt-launcher.go
  manifests/generated/operator-csv.yaml.in
  manifests/generated/rbac-operator.authorization.k8s.yaml.in
  pkg/handler-launcher-com/cmd/v1/cmd.pb.go
  pkg/handler-launcher-com/cmd/v1/cmd.proto
  pkg/handler-launcher-com/cmd/v1/generated_mock_cmd.go
  pkg/hotplug-disk/hotplug-disk.go
  pkg/hotplug-disk/hotplug-disk_test.go
  pkg/testutils/mock_config.go
  pkg/util/types/pvc.go
  pkg/virt-api/api.go
  pkg/virt-api/rest/BUILD.bazel
  pkg/virt-api/rest/subresource.go
  pkg/virt-api/rest/subresource_test.go
  pkg/virt-api/webhooks/validating-webhook/admitters/vmi-create-admitter.go
  pkg/virt-api/webhooks/validating-webhook/admitters/vmi-create-admitter_test.go
  pkg/virt-api/webhooks/validating-webhook/admitters/vmi-update-admitter.go
  pkg/virt-api/webhooks/validating-webhook/admitters/vmi-update-admitter_test.go
  pkg/virt-controller/watch/vm.go
  pkg/virt-controller/watch/vm_test.go
  pkg/virt-controller/watch/vmi.go
  pkg/virt-controller/watch/vmi_test.go
  pkg/virt-handler/BUILD.bazel
  pkg/virt-handler/cmd-client/client.go
  pkg/virt-handler/cmd-client/generated_mock_client.go
  pkg/virt-handler/hotplug-disk/mount.go
  pkg/virt-handler/hotplug-disk/mount_test.go
  pkg/virt-handler/vm.go
  pkg/virt-handler/vm_test.go
  pkg/virt-launcher/virtwrap/api/deepcopy_generated.go
  pkg/virt-launcher/virtwrap/api/schema.go
  pkg/virt-launcher/virtwrap/cli/generated_mock_libvirt.go
  pkg/virt-launcher/virtwrap/cli/libvirt.go
  pkg/virt-launcher/virtwrap/cmd-server/server.go
  pkg/virt-launcher/virtwrap/cmd-server/server_test.go
  pkg/virt-launcher/virtwrap/generated_mock_manager.go
  pkg/virt-launcher/virtwrap/manager.go
  pkg/virt-launcher/virtwrap/manager_test.go
  pkg/virt-operator/resource/generate/components/validations_generated.go
  pkg/virt-operator/resource/generate/rbac/apiserver.go
  pkg/virt-operator/resource/generate/rbac/cluster.go
  pkg/virtctl/root.go
  pkg/virtctl/vm/vm.go
  pkg/virtctl/vm/vm_test.go
  staging/src/kubevirt.io/api/core/v1/deepcopy_generated.go
  staging/src/kubevirt.io/api/core/v1/schema.go
  staging/src/kubevirt.io/api/core/v1/schema_swagger_generated.go
  staging/src/kubevirt.io/api/core/v1/types.go
  staging/src/kubevirt.io/api/core/v1/types_swagger_generated.go
  staging/src/kubevirt.io/client-go/api/openapi_generated.go
  staging/src/kubevirt.io/client-go/kubecli/generated_mock_kubevirt.go
  staging/src/kubevirt.io/client-go/kubecli/kubevirt.go
  staging/src/kubevirt.io/client-go/kubecli/vm.go
  tests/storage/BUILD.bazel
  tests/storage/hotplug.go
  tests/storage/memorydump.go
  tests/utils.go
Labels: release-note, size/XXL, lgtm, approved, dco-signoff: yes

#7810 test: move LibvirtDomainIsPersistent from utils
  tests/migration_test.go
  tests/utils.go
Labels: size/M, release-note-none, lgtm, approved, ok-to-test, dco-signoff: yes, sig/code-quality

#7832 OWNERS, network-reviewers: Remove inactive member
  OWNERS_ALIASES
Labels: size/XS, release-note-none, lgtm, approved, dco-signoff: yes

#7804 Makefile: add a lint target
  Makefile
Labels: size/S, release-note-none, lgtm, approved, dco-signoff: yes, sig/code-quality
