Repository kubevirt/kubevirt, pull requests merged in 2022-11, with the labels that each got.

#8678 Use a readiness probe for memory dump test executor
  tests/utils.go
Labels: size/S, release-note-none, lgtm, approved, dco-signoff: yes

#8645 [e2e tests]: Run export test pods as PSA-compliant as well
  tests/storage/export.go
Labels: size/S, release-note-none, lgtm, approved, dco-signoff: yes

#8673 Allow specifying custom images for core components
  pkg/virt-operator/BUILD.bazel
  pkg/virt-operator/application.go
  pkg/virt-operator/kubevirt.go
  pkg/virt-operator/kubevirt_test.go
  pkg/virt-operator/resource/apply/BUILD.bazel
  pkg/virt-operator/resource/apply/apps_test.go
  pkg/virt-operator/resource/apply/pdb_test.go
  pkg/virt-operator/resource/generate/components/daemonsets.go
  pkg/virt-operator/resource/generate/components/deployments.go
  pkg/virt-operator/resource/generate/csv/csv.go
  pkg/virt-operator/resource/generate/install/strategy.go
  pkg/virt-operator/util/BUILD.bazel
  pkg/virt-operator/util/config.go
  pkg/virt-operator/util/config_test.go
  pkg/virt-operator/util/env_var_manager.go
  tests/BUILD.bazel
  tests/operator_test.go
  tests/utils.go
  tools/csv-generator/csv-generator.go
  tools/manifest-templator/manifest-templator.go
Labels: size/XL, release-note, kind/api-change, lgtm, approved, dco-signoff: yes

#8663 Slighlty randomize CI startup to distribute disk usage a little bit
  automation/test.sh
Labels: size/XS, release-note-none, lgtm, approved, dco-signoff: yes

#8717 Fix flakiness of virtctl export tests
  tests/testsuite/namespace.go
Labels: size/XS, release-note-none, lgtm, approved, dco-signoff: yes

#8704 Stabilize slirp outside connectivity test
  tests/network/vmi_slirp_interface.go
Labels: size/S, sig/network, release-note-none, lgtm, approved, dco-signoff: yes

#8721 tests, network: Remove duplicate imports
  tests/network/vmi_networking.go
Labels: size/M, sig/network, release-note-none, lgtm, approved, dco-signoff: yes

#8625 masquerade: remove iptables nat configuration
  WORKSPACE
  docs/devel/networking.md
  hack/bootstrap.sh
  hack/rpm-deps.sh
  pkg/network/driver/common.go
  pkg/network/driver/generated_mock_common.go
  pkg/network/infraconfigurators/masquerade.go
  pkg/network/infraconfigurators/masquerade_test.go
  rpm/BUILD.bazel
Labels: sig/network, size/XL, release-note, lgtm, approved, dco-signoff: yes

#8722 tests, network: Replace run migration function
  tests/network/vmi_networking.go
Labels: size/S, sig/network, release-note-none, lgtm, approved, dco-signoff: yes

#8710 [release-0.53] Manual backport of fix bug in restore-controller when creating a restore PVC with both dataSource and dataSourceRef
  pkg/virt-controller/watch/snapshot/restore.go
  pkg/virt-controller/watch/snapshot/restore_test.go
  tests/storage/restore.go
Labels: size/L, release-note-none, lgtm, approved, dco-signoff: yes

#8696 tests: less echo hello
  tests/security_features_test.go
  tests/storage/snapshot.go
  tests/subresource_api_test.go
  tests/vmi_cloudinit_hook_sidecar_test.go
  tests/vmi_lifecycle_test.go
Labels: size/L, release-note-none, lgtm, approved, dco-signoff: yes

#8712 Re-enable virtio-gpu for aarch64 VMs
  WORKSPACE
  hack/bootstrap.sh
  hack/rpm-deps.sh
  rpm/BUILD.bazel
Labels: size/S, release-note-none, lgtm, approved, dco-signoff: yes

#8725 hostdev: Avoid creating SR-IOV pool when not configured
  pkg/virt-launcher/virtwrap/device/hostdevice/sriov/hostdev.go
Labels: size/XS, release-note-none, lgtm, approved, dco-signoff: yes

#8736 Add more precise rest_client_request_latency_seconds histogram buckets
  pkg/monitoring/client/prometheus/prometheus.go
Labels: release-note, size/XS, lgtm, approved, ok-to-test, dco-signoff: yes, area/monitoring

#8619 virt-launcher: Switch to virtqemud
  cmd/virt-handler/README.md
  cmd/virt-launcher/BUILD.bazel
  cmd/virt-launcher/node-labeller/node-labeller.sh
  cmd/virt-launcher/virt-launcher.go
  cmd/virt-launcher/virtqemud.conf
  pkg/virt-controller/services/renderresources.go
  pkg/virt-controller/services/template.go
  pkg/virt-handler/isolation/detector.go
  pkg/virt-handler/migration-proxy/migration-proxy.go
  pkg/virt-handler/migration-proxy/migration-proxy_test.go
  pkg/virt-handler/vm.go
  pkg/virt-launcher/virtwrap/util/libvirt_helper.go
  tests/migration_test.go
  tests/utils.go
  tests/vmi_configuration_test.go
Labels: size/L, release-note, lgtm, approved, kind/build-change, dco-signoff: yes

#8679 Simplify terminology a bit
  docs/components.md
Labels: size/XS, release-note-none, lgtm, approved, ok-to-test, dco-signoff: yes

#8726 Add GC note to DataVolumeSource api doc
  api/openapi-spec/swagger.json
  pkg/virt-operator/resource/generate/components/validations_generated.go
  staging/src/kubevirt.io/api/core/v1/schema.go
  staging/src/kubevirt.io/api/core/v1/schema_swagger_generated.go
  staging/src/kubevirt.io/client-go/api/openapi_generated.go
Labels: size/M, release-note-none, kind/api-change, lgtm, approved, dco-signoff: yes

#8716 network,passt: consider overhead when binding all ports
  pkg/virt-controller/services/renderresources.go
  tests/network/vmi_istio.go
  tests/network/vmi_passt.go
Labels: size/S, sig/network, release-note, lgtm, approved, dco-signoff: yes

#8739 Log nodes running pods in test namespaces
  tests/reporter/kubernetes.go
Labels: size/M, release-note-none, lgtm, approved, dco-signoff: yes

#8751 Add restricted seccomp profile to controller SCC
  pkg/virt-operator/resource/generate/components/scc.go
Labels: size/XS, release-note-none, lgtm, approved, dco-signoff: yes

#8623 [release-0.53] Rename metrics to follow naming convention
  docs/metrics.md
  pkg/monitoring/domainstats/prometheus/prometheus.go
  pkg/monitoring/domainstats/prometheus/prometheus_test.go
Labels: release-note, size/XS, lgtm, approved, dco-signoff: yes, area/monitoring

#8741 Use a unique pvc/pod name for guestfs test
  tests/storage/guestfs.go
Labels: size/XS, release-note-none, lgtm, approved, dco-signoff: yes

#8724 guest-agent, tests: Increase timeout fetching pod IPs
  tests/network/primary_pod_network.go
Labels: sig/network, size/XS, release-note-none, lgtm, approved, dco-signoff: yes

#8458 [Clone API]: Support snapshot source
  manifests/generated/operator-csv.yaml.in
  manifests/generated/rbac-operator.authorization.k8s.yaml.in
  pkg/controller/BUILD.bazel
  pkg/controller/virtinformers.go
  pkg/storage/snapshot/snapshot.go
  pkg/storage/snapshot/util.go
  pkg/virt-api/webhooks/validating-webhook/admitters/BUILD.bazel
  pkg/virt-api/webhooks/validating-webhook/admitters/vmclone-admitter.go
  pkg/virt-api/webhooks/validating-webhook/admitters/vmclone-admitter_test.go
  pkg/virt-controller/watch/application.go
  pkg/virt-controller/watch/application_test.go
  pkg/virt-controller/watch/clone/clone.go
  pkg/virt-controller/watch/clone/clone_base.go
  pkg/virt-controller/watch/clone/clone_test.go
  pkg/virt-operator/resource/generate/rbac/apiserver.go
  tests/BUILD.bazel
  tests/clone_test.go
  tests/libstorage/storageclass.go
  tests/storage/BUILD.bazel
  tests/storage/datavolume.go
  tests/storage/export.go
  tests/storage/restore.go
  tests/storage/snapshot.go
Labels: release-note, size/XXL, lgtm, approved, dco-signoff: yes

#8728 [scp/ssh tests]: switch fedora to alpine
  WORKSPACE
  tests/network/vmi_istio.go
  tests/virtctl/scp.go
  tests/virtctl/ssh.go
Labels: size/M, sig/network, release-note-none, lgtm, approved, dco-signoff: yes

#8748 tests: avoid opting out from OCP/OKD podSecurityLabelSync
  tests/testsuite/namespace.go
Labels: size/XS, release-note-none, lgtm, approved, dco-signoff: yes

#8600 tests: numa: yet another attempt at unflaking test_id:7299
  tests/numa/numa.go
Labels: size/S, release-note-none, lgtm, approved, dco-signoff: yes

#8694 Remove the virtiofs SELinux rules from our custom policy
  cmd/virt-handler/virt_launcher.cil
  pkg/virt-controller/services/template.go
  pkg/virt-controller/services/template_test.go
  tests/testsuite/kubevirtresource.go
Labels: size/M, release-note-none, lgtm, approved, kind/build-change, dco-signoff: yes

#8720 Rename and authorization for namespaced expand-spec endpoint
  api/openapi-spec/swagger.json
  cmd/subresource-access-test/BUILD.bazel
  cmd/subresource-access-test/subresource-access-test.go
  manifests/generated/operator-csv.yaml.in
  manifests/generated/rbac-operator.authorization.k8s.yaml.in
  pkg/virt-api/api.go
  pkg/virt-api/rest/authorizer.go
  pkg/virt-api/rest/authorizer_test.go
  pkg/virt-api/rest/expand.go
  pkg/virt-api/rest/expand_test.go
  pkg/virt-operator/resource/generate/rbac/cluster.go
  staging/src/kubevirt.io/client-go/kubecli/BUILD.bazel
  staging/src/kubevirt.io/client-go/kubecli/generated_mock_kubevirt.go
  staging/src/kubevirt.io/client-go/kubecli/instancetype.go
  staging/src/kubevirt.io/client-go/kubecli/instancetype_test.go
  staging/src/kubevirt.io/client-go/kubecli/kubevirt.go
  tests/access_test.go
  tests/subresource_api_test.go
  tests/testsuite/serviceaccount.go
Labels: release-note, size/XXL, lgtm, approved, dco-signoff: yes, area/instancetype

#8743 [export tests]: Specify fsGroup so we can write the exported PVC
  tests/storage/export.go
Labels: size/XS, release-note-none, lgtm, approved, dco-signoff: yes

#8530 Use exponential backoff for failing migrations
  pkg/virt-controller/watch/migration.go
  pkg/virt-controller/watch/migration_test.go
  pkg/virt-controller/watch/vmi.go
  staging/src/kubevirt.io/api/core/v1/types.go
  tests/migration_test.go
Labels: size/L, release-note, kind/api-change, lgtm, approved, dco-signoff: yes

#8773 Fix evmcs hyperv feature bug
  pkg/virt-api/webhooks/hyperv.go
  pkg/virt-api/webhooks/mutating-webhook/mutators/vmi-mutator_test.go
  tests/hyperv_test.go
  tests/vmi_lifecycle_test.go
Labels: size/L, release-note-none, lgtm, approved, dco-signoff: yes

#8740 Fix: Align Reenlightenment flows between converter.go and template.go
  pkg/virt-controller/services/BUILD.bazel
  pkg/virt-controller/services/template.go
  pkg/virt-controller/services/template_test.go
  pkg/virt-controller/watch/topology/generated_mock_hinter.go
  pkg/virt-controller/watch/topology/hinter.go
  pkg/virt-controller/watch/topology/hinter_test.go
  pkg/virt-controller/watch/topology/tsc.go
  pkg/virt-controller/watch/topology/tsc_test.go
  pkg/virt-controller/watch/vmi.go
  pkg/virt-controller/watch/vmi_test.go
  pkg/virt-launcher/virtwrap/converter/converter.go
  tests/hyperv_test.go
Labels: size/L, release-note, lgtm, approved, dco-signoff: yes

#8753 guestfs: solve flakiness for guestfs tests
  tests/storage/BUILD.bazel
  tests/storage/guestfs.go
Labels: size/L, release-note-none, lgtm, approved, dco-signoff: yes

#7965 Vmi shouldn't run with obsolete cpu model
  cmd/virt-handler/virt-handler.go
  pkg/virt-controller/services/template.go
  pkg/virt-controller/services/template_test.go
  pkg/virt-handler/node-labeller/BUILD.bazel
  pkg/virt-handler/node-labeller/node_labeller.go
  pkg/virt-handler/node-labeller/node_labeller_test.go
  staging/src/kubevirt.io/api/core/v1/types.go
  tests/infra_test.go
Labels: size/L, release-note-none, kind/api-change, lgtm, approved, dco-signoff: yes

#8793 [release-0.58]Fix evmcs hyperv bug
  pkg/virt-api/webhooks/hyperv.go
  pkg/virt-api/webhooks/mutating-webhook/mutators/vmi-mutator_test.go
  tests/BUILD.bazel
  tests/hyperv_test.go
  tests/vmi_lifecycle_test.go
  tests/windows_test.go
Labels: size/L, release-note-none, lgtm, approved, dco-signoff: yes, area/monitoring

#8466 instancetype, snapshot: Capture and restore instancetype ControllerRevisions
  manifests/generated/operator-csv.yaml.in
  manifests/generated/rbac-operator.authorization.k8s.yaml.in
  pkg/instancetype/BUILD.bazel
  pkg/instancetype/instancetype.go
  pkg/storage/snapshot/BUILD.bazel
  pkg/storage/snapshot/restore.go
  pkg/storage/snapshot/restore_base.go
  pkg/storage/snapshot/restore_test.go
  pkg/storage/snapshot/snapshot_test.go
  pkg/storage/snapshot/source.go
  pkg/util/BUILD.bazel
  pkg/util/util.go
  pkg/virt-controller/watch/application.go
  pkg/virt-operator/resource/generate/rbac/controller.go
  tests/BUILD.bazel
  tests/clone_test.go
  tests/libinstancetype/BUILD.bazel
  tests/libinstancetype/instancetype.go
  tests/storage/BUILD.bazel
  tests/storage/restore.go
Labels: size/XXL, release-note-none, lgtm, approved, dco-signoff: yes, area/instancetype

#8701 [virt-controller]: consider the ParallelOutboundMigrationsPerNode when evicting VMs
  pkg/virt-controller/watch/drain/evacuation/evacuation.go
  pkg/virt-controller/watch/drain/evacuation/evacuation_test.go
Labels: size/L, release-note, lgtm, approved, dco-signoff: yes

#8792 Expose new custom components env vars to csv-generator and manifest-templator
  manifests/generated/operator-csv.yaml.in
  pkg/virt-operator/resource/generate/components/deployments.go
  pkg/virt-operator/resource/generate/csv/csv.go
  pkg/virt-operator/util/config.go
  pkg/virt-operator/util/config_test.go
  tools/csv-generator/csv-generator.go
  tools/manifest-templator/manifest-templator.go
Labels: size/L, release-note, lgtm, approved, dco-signoff: yes

#8797 Improve CleanNodes() function
  tests/libnode/node.go
Labels: size/XS, release-note-none, lgtm, approved, dco-signoff: yes

#8481 Always refresh the mediated devices
  pkg/virt-handler/device-manager/mediated_devices_types.go
  pkg/virt-handler/device-manager/mediated_devices_types_test.go
  tests/mdev_configuration_allocation_test.go
Labels: size/L, release-note-none, lgtm, approved, dco-signoff: yes

#8705 docs: build kubevirt using local files
  docs/local-custom-files.md
Labels: size/M, release-note-none, lgtm, approved, dco-signoff: yes

#8785 [release-0.58] Rename and authorization for namespaced expand-spec endpoint
  api/openapi-spec/swagger.json
  cmd/subresource-access-test/BUILD.bazel
  cmd/subresource-access-test/subresource-access-test.go
  manifests/generated/operator-csv.yaml.in
  manifests/generated/rbac-operator.authorization.k8s.yaml.in
  pkg/virt-api/api.go
  pkg/virt-api/rest/authorizer.go
  pkg/virt-api/rest/authorizer_test.go
  pkg/virt-api/rest/expand.go
  pkg/virt-api/rest/expand_test.go
  pkg/virt-operator/resource/generate/rbac/cluster.go
  staging/src/kubevirt.io/client-go/kubecli/BUILD.bazel
  staging/src/kubevirt.io/client-go/kubecli/generated_mock_kubevirt.go
  staging/src/kubevirt.io/client-go/kubecli/instancetype.go
  staging/src/kubevirt.io/client-go/kubecli/instancetype_test.go
  staging/src/kubevirt.io/client-go/kubecli/kubevirt.go
  tests/access_test.go
  tests/subresource_api_test.go
  tests/testsuite/serviceaccount.go
Labels: release-note, size/XXL, lgtm, approved, dco-signoff: yes, area/instancetype

#8525 Deprecate mediatedDevicesTypes in favor of mediatedDeviceTypes
  api/openapi-spec/swagger.json
  manifests/generated/kv-resource.yaml
  pkg/virt-config/configuration_test.go
  pkg/virt-config/virt-config.go
  pkg/virt-handler/device-manager/device_controller.go
  pkg/virt-handler/device-manager/mediated_devices_types_test.go
  pkg/virt-handler/heartbeat/heartbeat.go
  pkg/virt-handler/heartbeat/heartbeat_test.go
  pkg/virt-operator/resource/generate/components/validations_generated.go
  staging/src/kubevirt.io/api/core/v1/deepcopy_generated.go
  staging/src/kubevirt.io/api/core/v1/types.go
  staging/src/kubevirt.io/api/core/v1/types_swagger_generated.go
  staging/src/kubevirt.io/client-go/api/openapi_generated.go
  tests/mdev_configuration_allocation_test.go
Labels: size/L, release-note, kind/api-change, lgtm, approved, dco-signoff: yes

#8808 migration: apply backoff only for evacuation migrations
  pkg/virt-controller/watch/migration.go
  pkg/virt-controller/watch/migration_test.go
  tests/migration_test.go
Labels: size/M, release-note, kind/api-change, lgtm, approved, dco-signoff: yes

#8344 hotplug-disk container: match SELinux level of virt-launcher
  api/openapi-spec/swagger.json
  pkg/safepath/safepath.go
  pkg/virt-controller/services/template.go
  pkg/virt-controller/watch/migration_test.go
  pkg/virt-controller/watch/vmi.go
  pkg/virt-controller/watch/vmi_test.go
  pkg/virt-handler/BUILD.bazel
  pkg/virt-handler/selinux/BUILD.bazel
  pkg/virt-handler/selinux/labels.go
  pkg/virt-handler/vm.go
  pkg/virt-operator/resource/generate/components/validations_generated.go
  staging/src/kubevirt.io/api/core/v1/types.go
  staging/src/kubevirt.io/api/core/v1/types_swagger_generated.go
  staging/src/kubevirt.io/client-go/api/openapi_generated.go
Labels: size/L, release-note-none, kind/api-change, lgtm, approved, dco-signoff: yes

#8770 Update tests wrt ginkgo 2: Add Serial decorators and change checks for serial run
  tests/README.md
  tests/canary_upgrade_test.go
  tests/clone_test.go
  tests/container_disk_test.go
  tests/dryrun_test.go
  tests/hyperv_test.go
  tests/infra_test.go
  tests/launchsecurity/sev.go
  tests/mdev_configuration_allocation_test.go
  tests/migration_test.go
  tests/monitoring/monitoring.go
  tests/network/framework.go
  tests/network/sriov.go
  tests/network/vmi_istio.go
  tests/network/vmi_lifecycle.go
  tests/network/vmi_multus.go
  tests/network/vmi_networking.go
  tests/network/vmi_passt.go
  tests/network/vmi_slirp_interface.go
  tests/numa/numa.go
  tests/operator_test.go
  tests/performance/framework.go
  tests/pool_test.go
  tests/realtime/realtime.go
  tests/security_features_test.go
  tests/storage/datavolume.go
  tests/storage/events.go
  tests/storage/export.go
  tests/storage/framework.go
  tests/storage/guestfs.go
  tests/storage/hotplug.go
  tests/storage/imageupload.go
  tests/storage/snapshot.go
  tests/storage/storage.go
  tests/swap_test.go
  tests/sysprep_test.go
  tests/template_test.go
  tests/testsuite/kubevirtresource.go
  tests/utils.go
  tests/virt_control_plane_test.go
  tests/vm_test.go
  tests/vmi_configuration_test.go
  tests/vmi_gpu_test.go
  tests/vmi_hook_sidecar_test.go
  tests/vmi_hostdev_test.go
  tests/vmi_lifecycle_test.go
  tests/vmi_vsock_test.go
  tests/vmidefaults_test.go
  tests/windows_test.go
Labels: size/L, sig/network, release-note, lgtm, approved, dco-signoff: yes

#8810 [release-0.58] instancetype, snapshot: Capture and restore instancetype ControllerRevisions
  manifests/generated/operator-csv.yaml.in
  manifests/generated/rbac-operator.authorization.k8s.yaml.in
  pkg/instancetype/BUILD.bazel
  pkg/instancetype/instancetype.go
  pkg/storage/snapshot/BUILD.bazel
  pkg/storage/snapshot/restore.go
  pkg/storage/snapshot/restore_base.go
  pkg/storage/snapshot/restore_test.go
  pkg/storage/snapshot/snapshot_test.go
  pkg/storage/snapshot/source.go
  pkg/util/BUILD.bazel
  pkg/util/util.go
  pkg/virt-controller/watch/application.go
  pkg/virt-operator/resource/generate/rbac/controller.go
  tests/BUILD.bazel
  tests/clone_test.go
  tests/libinstancetype/BUILD.bazel
  tests/libinstancetype/instancetype.go
  tests/libstorage/storageclass.go
  tests/storage/BUILD.bazel
  tests/storage/datavolume.go
  tests/storage/export.go
  tests/storage/restore.go
  tests/storage/snapshot.go
Labels: size/XXL, release-note-none, lgtm, approved, dco-signoff: yes, area/instancetype

#8702 Run quarantined io error test with alpine
  tests/storage/storage.go
Labels: size/XS, release-note-none, lgtm, approved, dco-signoff: yes

#8811 Custom components: support gs
  manifests/generated/operator-csv.yaml.in
  pkg/virt-operator/resource/generate/components/deployments.go
  pkg/virt-operator/resource/generate/csv/csv.go
  pkg/virt-operator/util/config.go
  pkg/virt-operator/util/config_test.go
  tools/csv-generator/csv-generator.go
  tools/manifest-templator/manifest-templator.go
Labels: size/M, release-note, lgtm, approved, ok-to-test, dco-signoff: yes

#8798 [release-0.58]: Fix: Align Reenlightenment flows between converter.go and template.go
  pkg/virt-controller/services/BUILD.bazel
  pkg/virt-controller/services/template.go
  pkg/virt-controller/services/template_test.go
  pkg/virt-controller/watch/topology/generated_mock_hinter.go
  pkg/virt-controller/watch/topology/hinter.go
  pkg/virt-controller/watch/topology/hinter_test.go
  pkg/virt-controller/watch/topology/tsc.go
  pkg/virt-controller/watch/topology/tsc_test.go
  pkg/virt-controller/watch/vmi.go
  pkg/virt-controller/watch/vmi_test.go
  pkg/virt-launcher/virtwrap/converter/converter.go
  tests/hyperv_test.go
Labels: size/L, release-note, lgtm, approved, dco-signoff: yes

#8809 [release-0.58] Always refresh the mediated devices
  pkg/virt-handler/device-manager/mediated_devices_types.go
  pkg/virt-handler/device-manager/mediated_devices_types_test.go
  tests/mdev_configuration_allocation_test.go
Labels: size/L, release-note-none, lgtm, approved, dco-signoff: yes

#8812 Change iholder-redhat username to iholder101 in owners file
  OWNERS_ALIASES
Labels: size/XS, release-note-none, lgtm, approved, ok-to-test, dco-signoff: yes

#8816 [release-0.58] Expose new custom components env vars to csv-generator, manifest-templator and gs
  manifests/generated/operator-csv.yaml.in
  pkg/virt-operator/resource/generate/components/deployments.go
  pkg/virt-operator/resource/generate/csv/csv.go
  pkg/virt-operator/util/config.go
  pkg/virt-operator/util/config_test.go
  tools/csv-generator/csv-generator.go
  tools/manifest-templator/manifest-templator.go
Labels: size/L, release-note, lgtm, approved, dco-signoff: yes

#8794 Nominate Antonio as an approver in the tests directory.
  OWNERS_ALIASES
Labels: size/XS, release-note-none, lgtm, approved, dco-signoff: yes

#8764 Add list of included and excluded volumes in vmSnapshot
  api/openapi-spec/swagger.json
  pkg/storage/snapshot/snapshot.go
  pkg/storage/snapshot/snapshot_test.go
  pkg/storage/snapshot/source.go
  pkg/storage/types/pvc.go
  pkg/virt-operator/resource/generate/components/validations_generated.go
  staging/src/kubevirt.io/api/snapshot/v1alpha1/deepcopy_generated.go
  staging/src/kubevirt.io/api/snapshot/v1alpha1/types.go
  staging/src/kubevirt.io/api/snapshot/v1alpha1/types_swagger_generated.go
  staging/src/kubevirt.io/client-go/api/openapi_generated.go
  tests/clone_test.go
  tests/libstorage/storageclass.go
  tests/storage/snapshot.go
Labels: size/L, release-note, kind/api-change, lgtm, approved, dco-signoff: yes

#8640 Unfreeze VM when all VolumeSnapshots "created" instead of "ready"
  pkg/storage/snapshot/snapshot.go
  pkg/storage/snapshot/snapshot_test.go
Labels: size/M, release-note-none, lgtm, approved, dco-signoff: yes

#8827 HyperV functest fix: don't expect node-labeller to always be stopped
  tests/hyperv_test.go
Labels: size/XS, release-note-none, lgtm, approved, dco-signoff: yes

#8775 virt-launcher: Remove always nil return values from DomainManager
  pkg/virt-launcher/virtwrap/cmd-server/server.go
  pkg/virt-launcher/virtwrap/cmd-server/server_test.go
  pkg/virt-launcher/virtwrap/generated_mock_manager.go
  pkg/virt-launcher/virtwrap/manager.go
  pkg/virt-launcher/virtwrap/manager_test.go
Labels: size/M, release-note-none, lgtm, approved, dco-signoff: yes, sig/code-quality

#8823 Make acardace approver for kubevirt/kubevirt
  OWNERS_ALIASES
Labels: size/XS, release-note-none, lgtm, approved, dco-signoff: yes

#8825 Add virtio-gpu device for aarch64 VMs
  WORKSPACE
  hack/bootstrap.sh
  hack/rpm-deps.sh
  rpm/BUILD.bazel
Labels: size/XL, release-note-none, lgtm, approved, dco-signoff: yes

#8838 Quarantine canary upgrade test
  tests/canary_upgrade_test.go
Labels: size/XS, release-note-none, lgtm, approved, dco-signoff: yes

#8834 tests: Set expected screenshot resolution
  tests/vnc_test.go
Labels: size/S, release-note-none, lgtm, approved, dco-signoff: yes

#8734 Use libguestfs appliance with qcow2 root
  WORKSPACE
  cmd/libguestfs/BUILD.bazel
  cmd/libguestfs/entrypoint.sh
  hack/rpm-deps.sh
  pkg/virtctl/guestfs/guestfs.go
Labels: size/M, release-note, lgtm, approved, dco-signoff: yes

#8768 [virtctl] Express image-upload options deprecation via pflag
  pkg/virtctl/imageupload/imageupload.go
  pkg/virtctl/imageupload/imageupload_test.go
Labels: size/S, release-note-none, lgtm, approved, dco-signoff: yes

#8847 [release-0.53] Rename metrics to follow naming convention
  docs/metrics.md
  pkg/monitoring/domainstats/prometheus/prometheus.go
  pkg/monitoring/domainstats/prometheus/prometheus_test.go
Labels: release-note, size/XS, lgtm, approved, dco-signoff: yes, area/monitoring

#8841 Drop ':z' bind option when using Podman and MacOS
  hack/dockerized
Labels: size/S, release-note-none, lgtm, approved, dco-signoff: yes

#8842 virt-launcher: Drop SYS_PTRACE capability
  cmd/virt-launcher/BUILD.bazel
  pkg/virt-controller/services/rendercontainer.go
  pkg/virt-controller/services/rendercontainer_test.go
  pkg/virt-controller/services/template.go
  pkg/virt-controller/services/template_test.go
  pkg/virt-launcher/virtwrap/util/libvirt_helper.go
  pkg/virt-operator/resource/generate/components/scc.go
  tests/security_features_test.go
Labels: size/M, release-note, lgtm, approved, kind/build-change, dco-signoff: yes

#8840 Fix evmcs hyperv bug
  pkg/virt-controller/services/nodeselectorrenderer.go
  pkg/virt-controller/services/template_test.go
  tests/hyperv_test.go
Labels: size/M, release-note-none, kind/api-change, lgtm, approved, dco-signoff: yes

#8742 device-manager: Drop workarounds
  pkg/virt-handler/device-manager/generic_device.go
  pkg/virt-handler/device-manager/mediated_device.go
  pkg/virt-handler/device-manager/pci_device.go
Labels: size/S, release-note-none, lgtm, approved, dco-signoff: yes

#7922 Pause tests
  tests/credentials_test.go
  tests/framework/matcher/BUILD.bazel
  tests/framework/matcher/conditions.go
  tests/framework/matcher/conditions_test.go
  tests/infra_test.go
  tests/migration.go
  tests/migration_test.go
  tests/network/primary_pod_network.go
  tests/network/probes.go
  tests/network/sriov.go
  tests/network/vmi_infosource.go
  tests/network/vmi_multus.go
  tests/operator_test.go
  tests/pausing_test.go
  tests/pool_test.go
  tests/replicaset_test.go
  tests/softreboot_test.go
  tests/storage/hotplug.go
  tests/storage/restore.go
  tests/storage/snapshot.go
  tests/storage/storage.go
  tests/subresource_api_test.go
  tests/utils.go
  tests/virt_control_plane_test.go
  tests/vm_test.go
  tests/vmi_configuration_test.go
  tests/vmi_lifecycle_test.go
Labels: sig/network, size/XXL, release-note-none, lgtm, approved, dco-signoff: yes, sig/code-quality

#8796 virt-api: Add test for empty namespace in expand_test.go
  pkg/virt-api/rest/expand_test.go
Labels: size/S, release-note-none, lgtm, approved, dco-signoff: yes, area/instancetype

#8846 [exportServer] Add download file logs when read file error
  pkg/storage/export/virt-exportserver/exportserver.go
Labels: size/XS, release-note-none, lgtm, approved, ok-to-test, dco-signoff: yes

#8586 [Functest stabilization]: Properly limit bandwidth with migration policies
  pkg/virt-controller/watch/migration_test.go
  tests/BUILD.bazel
  tests/migration_policy.go
  tests/migration_test.go
  tests/utils.go
Labels: size/L, release-note-none, lgtm, approved, dco-signoff: yes

#8861 [release-0.58]Fix evmcs hyperv vendor bug
  pkg/virt-controller/services/nodeselectorrenderer.go
  pkg/virt-controller/services/template_test.go
  tests/hyperv_test.go
Labels: size/M, release-note-none, lgtm, approved, dco-signoff: yes

#8851 tests, storage/restore: Remove a redundant prompt login
  tests/storage/restore.go
Labels: size/XS, release-note-none, lgtm, approved, dco-signoff: yes

#8845 api: Ensure Timer is omitted when empty from Clock
  pkg/virt-api/webhooks/validating-webhook/admitters/vmi-create-admitter_test.go
  staging/src/kubevirt.io/api/core/v1/schema.go
Labels: size/S, area/api-server, release-note, kind/api-change, lgtm, approved, dco-signoff: yes, area/instancetype

#8850 Run guestfs tests in parallel
  tests/storage/guestfs.go
Labels: size/XS, release-note-none, lgtm, approved, dco-signoff: yes

#8791 release: Update release.md to reflect the schema that we settled on
  docs/release.md
Labels: size/L, release-note-none, lgtm, approved, dco-signoff: yes

#8802 Preferred storage class
  api/openapi-spec/swagger.json
  pkg/virt-api/webhooks/mutating-webhook/mutators/BUILD.bazel
  pkg/virt-api/webhooks/mutating-webhook/mutators/vm-mutator.go
  pkg/virt-api/webhooks/mutating-webhook/mutators/vm-mutator_test.go
  pkg/virt-operator/resource/generate/components/validations_generated.go
  staging/src/kubevirt.io/api/instancetype/v1alpha2/deepcopy_generated.go
  staging/src/kubevirt.io/api/instancetype/v1alpha2/types.go
  staging/src/kubevirt.io/api/instancetype/v1alpha2/types_swagger_generated.go
  staging/src/kubevirt.io/client-go/api/openapi_generated.go
  tests/storage/BUILD.bazel
  tests/storage/datavolume.go
Labels: size/L, release-note, kind/api-change, lgtm, approved, dco-signoff: yes, area/instancetype
