Repository kubevirt/kubevirt, pull requests merged in 2022-06, with the labels that each got.

#7757 Add an alert for excessive migrations on a VMI
  hack/prom-rule-ci/prom-rules-tests.yaml
  pkg/monitoring/vmistats/collector.go
  pkg/virt-handler/cmd-client/client.go
  pkg/virt-handler/vm.go
  pkg/virt-operator/resource/generate/components/prometheus.go
Labels: size/M, release-note, lgtm, approved, dco-signoff: yes, area/monitoring

#7808 Fix vmsnapshot unittests flakiness
  pkg/virt-controller/watch/snapshot/snapshot_test.go
Labels: size/M, release-note-none, lgtm, approved, dco-signoff: yes

#7413 Code cleanup: Improve gomega matchers in `pkg/virt-launcher/virtwrap`
  pkg/virt-launcher/virtwrap/access-credentials/access_credentials_test.go
  pkg/virt-launcher/virtwrap/agent-poller/agent_parser_test.go
  pkg/virt-launcher/virtwrap/api/schema_test.go
  pkg/virt-launcher/virtwrap/cli/libvirt_test.go
  pkg/virt-launcher/virtwrap/cmd-server/server_test.go
  pkg/virt-launcher/virtwrap/converter/converter_test.go
  pkg/virt-launcher/virtwrap/converter/vcpu/numa_placement_test.go
  pkg/virt-launcher/virtwrap/converter/vcpu/vcpu_test.go
  pkg/virt-launcher/virtwrap/device/hostdevice/generic/hostdev_test.go
  pkg/virt-launcher/virtwrap/device/hostdevice/gpu/hostdev_test.go
  pkg/virt-launcher/virtwrap/device/hostdevice/hotplug_test.go
  pkg/virt-launcher/virtwrap/device/hostdevice/sriov/hostdev_test.go
  pkg/virt-launcher/virtwrap/efi/efi_test.go
  pkg/virt-launcher/virtwrap/manager_test.go
  pkg/virt-launcher/virtwrap/statsconv/converter_test.go
  pkg/virt-launcher/virtwrap/util/libvirt_helper_test.go
Labels: size/L, release-note-none, lgtm, approved, dco-signoff: yes, sig/code-quality

#7785 Unify usage of PCI and MDev prefixes
  pkg/virt-handler/device-manager/BUILD.bazel
  pkg/virt-handler/device-manager/mediated_device.go
  pkg/virt-handler/device-manager/pci_device.go
  pkg/virt-handler/vm_test.go
  pkg/virt-launcher/virtwrap/device/hostdevice/generic/addresspool.go
  pkg/virt-launcher/virtwrap/device/hostdevice/generic/addresspool_test.go
  pkg/virt-launcher/virtwrap/device/hostdevice/gpu/addresspool.go
  pkg/virt-launcher/virtwrap/device/hostdevice/gpu/addresspool_test.go
  pkg/virt-launcher/virtwrap/manager.go
  staging/src/kubevirt.io/api/core/v1/types.go
Labels: size/M, release-note-none, lgtm, approved, needs-ok-to-test, dco-signoff: yes

#7683 Improvement of virtctl ssh command
  hack/functests.sh
  pkg/virtctl/ssh/native.go
  pkg/virtctl/ssh/ssh.go
  pkg/virtctl/ssh/wrapped.go
  pkg/virtctl/ssh/wrapped_test.go
  tests/virtctl/BUILD.bazel
  tests/virtctl/key.go
  tests/virtctl/ssh.go
Labels: size/L, release-note, lgtm, approved, dco-signoff: yes

#7494 VM with RunStrategyHalted now accepts manual stop request...
  pkg/virt-api/rest/subresource.go
  pkg/virt-api/rest/subresource_test.go
  pkg/virtctl/vm/vm.go
  tests/vm_test.go
Labels: size/M, sig/network, release-note-none, lgtm, approved, ok-to-test, kind/build-change, dco-signoff: yes, area/monitoring

#7510 [Migration Policies]: Move helper functions out of API package & stop using "LabelSelector"
  api/openapi-spec/swagger.json
  pkg/virt-controller/watch/BUILD.bazel
  pkg/virt-controller/watch/migration.go
  pkg/virt-controller/watch/migration_test.go
  pkg/virt-controller/watch/migrationpolicy.go
  pkg/virt-operator/resource/generate/components/validations_generated.go
  staging/src/kubevirt.io/api/migrations/v1alpha1/BUILD.bazel
  staging/src/kubevirt.io/api/migrations/v1alpha1/deepcopy_generated.go
  staging/src/kubevirt.io/api/migrations/v1alpha1/types.go
  staging/src/kubevirt.io/api/migrations/v1alpha1/types_swagger_generated.go
  staging/src/kubevirt.io/client-go/api/openapi_generated.go
  tests/migration_test.go
  tests/utils.go
Labels: size/L, release-note-none, lgtm, approved, dco-signoff: yes

#7836 Fix KubevirtVmHighMemoryUsage alert
  hack/prom-rule-ci/prom-rules-tests.yaml
  pkg/virt-operator/resource/generate/components/prometheus.go
Labels: size/M, release-note-none, lgtm, approved, dco-signoff: yes, area/monitoring

#7865 [release-v0.53] fix test id 8235
  tests/operator_test.go
Labels: size/S, release-note-none, lgtm, approved, dco-signoff: yes

#7729 migration: log progress in source virt-launcher logs
  pkg/virt-launcher/virtwrap/live-migration-source.go
Labels: size/S, release-note-none, lgtm, approved, dco-signoff: yes

#7850 tests: simplify libvmi and use it to start diskless VM
  tests/infra_test.go
  tests/libvmi/factory.go
  tests/libvmi/vmi.go
  tests/network/vmi_slirp_interface.go
  tests/utils.go
Labels: size/M, sig/network, release-note-none, lgtm, approved, dco-signoff: yes, sig/code-quality

#7642 Reduce nestiness of `OnDefineDomain` method
  pkg/hooks/manager.go
Labels: size/M, release-note-none, lgtm, approved, ok-to-test, dco-signoff: yes

#7834 Update golang.org/x/crypto to v0.0.0-20220525230936
  go.mod
  go.sum
  vendor/golang.org/x/crypto/chacha20/chacha_s390x.go
  vendor/golang.org/x/crypto/curve25519/internal/field/fe_amd64.go
  vendor/golang.org/x/crypto/internal/poly1305/sum_generic.go
  vendor/golang.org/x/crypto/internal/poly1305/sum_s390x.go
  vendor/golang.org/x/crypto/openpgp/armor/armor.go
  vendor/golang.org/x/crypto/openpgp/armor/encode.go
  vendor/golang.org/x/crypto/openpgp/elgamal/elgamal.go
  vendor/golang.org/x/crypto/ssh/agent/client.go
  vendor/golang.org/x/crypto/ssh/certs.go
  vendor/golang.org/x/crypto/ssh/cipher.go
  vendor/golang.org/x/crypto/ssh/doc.go
  vendor/modules.txt
Labels: size/M, release-note-none, lgtm, approved, ok-to-test, dco-signoff: yes

#7848 test: move functions from utils
  tests/BUILD.bazel
  tests/container_disk_test.go
  tests/migration_test.go
  tests/operator_test.go
  tests/security_features_test.go
  tests/storage/datavolume.go
  tests/storage/storage.go
  tests/template_test.go
  tests/utils.go
  tests/virt_control_plane_test.go
  tests/vmi_configuration_test.go
  tests/vmi_ignition_test.go
  tests/windows_test.go
Labels: size/XL, release-note-none, lgtm, approved, dco-signoff: yes, sig/code-quality

#7728 stop considering cpu node discovery feature gate
  pkg/virt-controller/services/template.go
  pkg/virt-controller/services/template_test.go
  tests/vmi_lifecycle_test.go
Labels: size/M, release-note-none, lgtm, approved, dco-signoff: yes

#7811 Add reason to AgentVersionNotSupported condition
  pkg/virt-handler/vm.go
  pkg/virt-handler/vm_test.go
Labels: size/M, release-note, lgtm, approved, ok-to-test, dco-signoff: yes

#7815 k8s-reporter: Stop dumping unreachable container's info
  tests/reporter/BUILD.bazel
  tests/reporter/kubernetes.go
Labels: size/M, release-note-none, lgtm, approved, dco-signoff: yes

#7837 tests, libstorage: relocate some recently introduced PVC utils
  tests/libstorage/BUILD.bazel
  tests/libstorage/pvc.go
  tests/storage/memorydump.go
  tests/utils.go
Labels: size/L, release-note-none, lgtm, approved, dco-signoff: yes, sig/code-quality

#7840 k8s reporter: Fix virt-launcher pid find logic
  tests/reporter/kubernetes.go
Labels: size/XS, release-note-none, lgtm, approved, dco-signoff: yes

#7594 guestfs: run libguestfs container with no-root user
  cmd/libguestfs/BUILD.bazel
  cmd/libguestfs/entrypoint.sh
  pkg/virtctl/guestfs/guestfs.go
  tests/storage/guestfs.go
Labels: size/M, release-note, lgtm, approved, dco-signoff: yes

#7880 Add apiGroup to Template resource
  examples/vm-template-fedora.yaml
  examples/vm-template-rhel7.yaml
  examples/vm-template-windows2012r2.yaml
  tools/vms-generator/utils/utils.go
Labels: size/XS, release-note-none, lgtm, approved, dco-signoff: yes

#7882 tests/utils: a very minor cleanup
  tests/storage/imageupload.go
  tests/utils.go
Labels: size/S, release-note-none, lgtm, approved, dco-signoff: yes

#7732 virt-handler: add protection against migration double-starts
  pkg/virt-handler/vm.go
  pkg/virt-handler/vm_test.go
Labels: size/L, release-note, lgtm, approved, dco-signoff: yes

#7871 Use `math/rand` instead of `crypto/rand` in tests to speed up execution
  pkg/virt-operator/resource/generate/components/secrets_test.go
Labels: size/M, release-note-none, lgtm, approved, ok-to-test, dco-signoff: yes

#7884 tests: empty iso: handle potentially paused target
  tests/migration_test.go
Labels: size/S, release-note-none, lgtm, approved, dco-signoff: yes

#7877 Add sonarcloud badge
  README.md
Labels: size/XS, release-note-none, lgtm, approved, dco-signoff: yes

#7600 Refactor virt controller template machine volumes
  pkg/virt-controller/services/BUILD.bazel
  pkg/virt-controller/services/rendervolumes.go
  pkg/virt-controller/services/rendervolumes_test.go
  pkg/virt-controller/services/template.go
  pkg/virt-controller/services/template_test.go
Labels: size/XXL, release-note-none, lgtm, approved, dco-signoff: yes, sig/code-quality

#7876 tests, login: Fix error printing
  tests/console/login.go
Labels: size/XS, release-note-none, lgtm, approved, dco-signoff: yes

#7861 tests: Move `ObjectEventWatcher` to a separate package
  tests/BUILD.bazel
  tests/migration_test.go
  tests/storage/BUILD.bazel
  tests/storage/storage.go
  tests/utils.go
  tests/vmi_configuration_test.go
  tests/vmi_lifecycle_test.go
  tests/watcher/BUILD.bazel
  tests/watcher/watcher.go
Labels: size/XL, release-note-none, lgtm, approved, dco-signoff: yes, sig/code-quality

#7894 tests, network, primary-pod: Remove VMI deletion on teardown
  tests/network/primary_pod_network.go
Labels: size/M, sig/network, release-note-none, lgtm, approved, dco-signoff: yes

#7528 Remove assumption that infra replicas default to 2
  hack/config-default.sh
  manifests/generated/kubevirt-cr.yaml.in
  pkg/virt-operator/resource/generate/components/crds.go
  pkg/virt-operator/util/config.go
  tools/manifest-templator/manifest-templator.go
  tools/resource-generator/BUILD.bazel
  tools/resource-generator/resource-generator.go
Labels: size/L, release-note-none, lgtm, approved, dco-signoff: yes

#7800 Fixing flacky test_id:3203
  tests/vmi_lifecycle_test.go
Labels: size/M, release-note-none, lgtm, approved, dco-signoff: yes

#7886 tests: console: bootloader expecters: give the VMI enough time to start
  tests/console/console.go
Labels: size/XS, release-note-none, lgtm, approved, dco-signoff: yes

#7903 test: inline unnecessary functions
  tests/migration_test.go
  tests/vmi_ignition_test.go
Labels: size/S, release-note-none, lgtm, approved, dco-signoff: yes, sig/code-quality

#7906 Bump CDI API to v1.50.0
  api/openapi-spec/swagger.json
  go.mod
  go.sum
  staging/src/kubevirt.io/api/go.mod
  staging/src/kubevirt.io/api/go.sum
  staging/src/kubevirt.io/client-go/api/openapi_generated.go
  staging/src/kubevirt.io/client-go/go.mod
  staging/src/kubevirt.io/client-go/go.sum
  tests/BUILD.bazel
  tests/operator_test.go
  vendor/kubevirt.io/containerized-data-importer-api/pkg/apis/core/v1beta1/BUILD.bazel
  vendor/kubevirt.io/containerized-data-importer-api/pkg/apis/core/v1beta1/types.go
  vendor/kubevirt.io/containerized-data-importer-api/pkg/apis/core/v1beta1/types_swagger_generated.go
  vendor/kubevirt.io/containerized-data-importer-api/pkg/apis/core/v1beta1/zz_generated.deepcopy.go
  vendor/kubevirt.io/containerized-data-importer-api/pkg/apis/upload/v1beta1/zz_generated.deepcopy.go
  vendor/kubevirt.io/controller-lifecycle-operator-sdk/api/BUILD.bazel
  vendor/kubevirt.io/controller-lifecycle-operator-sdk/api/LICENSE
  vendor/kubevirt.io/controller-lifecycle-operator-sdk/api/types.go
  vendor/modules.txt
Labels: size/L, release-note-none, lgtm, approved, dco-signoff: yes

#7634 [Flaky] 3188 test - improve reporting to catch a problem
  tests/storage/datavolume.go
Labels: size/M, release-note-none, lgtm, approved, dco-signoff: yes

#7923 virt-api: start subresource: clearer error message
  pkg/virt-api/rest/subresource.go
Labels: size/XS, release-note-none, lgtm, approved, dco-signoff: yes, sig/code-quality

#7870 Fixing host model support heterogeneus cluster [release-0.53]
  pkg/virt-controller/watch/migration.go
  pkg/virt-controller/watch/migration_test.go
  pkg/virt-handler/node-labeller/cpu_plugin.go
  pkg/virt-handler/node-labeller/cpu_plugin_test.go
  pkg/virt-handler/node-labeller/node_labeller.go
  staging/src/kubevirt.io/api/core/v1/types.go
  tests/infra_test.go
  tests/migration_test.go
  tests/utils.go
Labels: size/L, release-note-none, lgtm, approved, dco-signoff: yes

#7868 vmi_networking, Move flaky tests to Cirros
  tests/network/vmi_networking.go
Labels: size/S, sig/network, release-note-none, lgtm, approved, dco-signoff: yes

#7930 ci, reporter, Add step before reporter dump starts
  tests/reporter/kubernetes.go
Labels: size/XS, release-note-none, lgtm, approved, dco-signoff: yes

#7896 [release-0.49] Avoid required uid/gid 0 for libguestfs pod
  cmd/libguestfs/BUILD.bazel
  cmd/libguestfs/entrypoint.sh
  pkg/virtctl/guestfs/guestfs.go
  tests/storage/guestfs.go
Labels: size/M, release-note-none, lgtm, approved, dco-signoff: yes

#7852 test/utils: static file length limit
  Makefile
Labels: size/XS, release-note-none, lgtm, approved, dco-signoff: yes

#7858 tests: libvmi.New: no explicit name
  tests/infra_test.go
  tests/libvmi/factory.go
  tests/libvmi/vmi.go
  tests/utils.go
  tests/vmi_lifecycle_test.go
Labels: size/M, sig/network, release-note-none, lgtm, approved, dco-signoff: yes

#7919 flavors: Apply preferences to any added default network interfaces or missing volume disks
  pkg/util/util.go
  pkg/virt-api/webhooks/mutating-webhook/mutators/vmi-mutator.go
  pkg/virt-config/virt-config.go
  pkg/virt-controller/watch/BUILD.bazel
  pkg/virt-controller/watch/application.go
  pkg/virt-controller/watch/application_test.go
  pkg/virt-controller/watch/vm.go
  pkg/virt-controller/watch/vm_test.go
  tests/flavor_test.go
Labels: size/XL, release-note, lgtm, approved, dco-signoff: yes

#7933 Fix vm restore in case of restore size bigger then PVC requested size
  pkg/virt-controller/watch/application.go
  pkg/virt-controller/watch/snapshot/restore.go
  pkg/virt-controller/watch/snapshot/restore_base.go
  pkg/virt-controller/watch/snapshot/restore_test.go
  pkg/virt-controller/watch/snapshot/snapshot.go
  pkg/virt-controller/watch/snapshot/snapshot_base.go
  tests/storage/restore.go
Labels: size/L, release-note, lgtm, approved, dco-signoff: yes

#7434 Drop recording rule for orphaned VMs alert and fix alert definition
  hack/prom-rule-ci/prom-rules-tests.yaml
  pkg/virt-operator/resource/generate/components/prometheus.go
Labels: size/M, release-note-none, lgtm, approved, dco-signoff: yes, area/monitoring

#7839 Fix the updated version of perfscale load generator, VMIs are not being created
  automation/perfscale-test.sh
  hack/perfscale-tests.sh
  tools/perfscale-load-generator/BUILD.bazel
  tools/perfscale-load-generator/api/api.go
  tools/perfscale-load-generator/burst/BUILD.bazel
  tools/perfscale-load-generator/burst/burst.go
  tools/perfscale-load-generator/config/config.go
  tools/perfscale-load-generator/config/types.go
  tools/perfscale-load-generator/examples/workload/kubevirt-density/kubevirt-steady-state-100.yaml
  tools/perfscale-load-generator/flags/flags.go
  tools/perfscale-load-generator/load-generator.go
  tools/perfscale-load-generator/object/namespace.go
  tools/perfscale-load-generator/object/unstructured.go
  tools/perfscale-load-generator/object/utils.go
  tools/perfscale-load-generator/steady-state/BUILD.bazel
  tools/perfscale-load-generator/steady-state/steady-state.go
  tools/perfscale-load-generator/utils/BUILD.bazel
  tools/perfscale-load-generator/utils/utils.go
  tools/perfscale-load-generator/watcher/watcher.go
Labels: size/XL, release-note-none, lgtm, approved, dco-signoff: yes

#7841 migration: enable migrating from non-root to root
  pkg/virt-controller/watch/migration.go
  tests/migration_test.go
Labels: size/L, release-note, lgtm, approved, dco-signoff: yes

#7901 tests, network, primary pod: use libvmi to create VMI specs
  tests/network/primary_pod_network.go
Labels: size/M, sig/network, release-note-none, lgtm, approved, dco-signoff: yes, sig/code-quality

#7928 [Bugfix] [Node-Labeller]: Properly remove all node-labeller labels
  pkg/virt-handler/node-labeller/cpu_plugin_test.go
  pkg/virt-handler/node-labeller/node_labeller.go
Labels: size/L, release-note, lgtm, approved, dco-signoff: yes

#7752 Optimize libnode's annotation/label modification functions + stabilize & fix migration functests
  tests/infra_test.go
  tests/libnode/BUILD.bazel
  tests/libnode/node.go
  tests/migration_test.go
Labels: size/XL, release-note-none, lgtm, approved, dco-signoff: yes, sig/code-quality

#7902 unit test, isolation: Make test agnostic to virt-launcher process name
  pkg/virt-handler/isolation/detector_test.go
Labels: size/S, release-note-none, lgtm, approved, dco-signoff: yes, sig/code-quality

#7807 cloud-init: make cloud-init 'instance-id' persistent
  pkg/cloud-init/BUILD.bazel
  pkg/cloud-init/cloud-init.go
  pkg/cloud-init/cloud-init_test.go
  pkg/virt-controller/watch/snapshot/restore.go
  pkg/virt-launcher/virtwrap/manager.go
  tests/console/console.go
  tests/libvmi/cloudinit.go
  tests/network/sriov.go
  tests/vmi_cloudinit_test.go
Labels: size/L, sig/network, release-note, lgtm, approved, dco-signoff: yes

#7921 vmi_lifecycle_test: consume less memory
  tests/vmi_lifecycle_test.go
Labels: size/XS, release-note-none, lgtm, approved, dco-signoff: yes, sig/code-quality

#7924 [Code Quality]: Improve & ease patch generation
  pkg/util/types/patch.go
  pkg/virt-api/rest/BUILD.bazel
  pkg/virt-api/rest/subresource.go
  pkg/virt-api/rest/subresource_test.go
  pkg/virt-api/webhooks/mutating-webhook/mutators/migration-create-mutator.go
  pkg/virt-api/webhooks/mutating-webhook/mutators/vm-mutator.go
  pkg/virt-controller/watch/migration.go
  pkg/virt-controller/watch/migration_test.go
  pkg/virt-controller/watch/node.go
  pkg/virt-operator/resource/apply/apps_test.go
Labels: size/L, release-note-none, lgtm, approved, dco-signoff: yes, sig/code-quality

#7765 fixing MinCPUModel's field logic
  pkg/virt-handler/node-labeller/cpu_plugin.go
  pkg/virt-handler/node-labeller/cpu_plugin_test.go
  tests/infra_test.go
Labels: size/M, release-note-none, lgtm, approved, dco-signoff: yes

#7941 [release-0.53] Backport 'Fix vm restore in case of restore size bigger then PVC requested size'
  pkg/virt-controller/watch/application.go
  pkg/virt-controller/watch/snapshot/restore.go
  pkg/virt-controller/watch/snapshot/restore_base.go
  pkg/virt-controller/watch/snapshot/restore_test.go
  pkg/virt-controller/watch/snapshot/snapshot.go
  pkg/virt-controller/watch/snapshot/snapshot_base.go
  tests/storage/restore.go
Labels: size/L, release-note, lgtm, approved, dco-signoff: yes

#7898 tests/storage/restore: less `echo hello`
  tests/storage/restore.go
  tests/utils.go
Labels: size/S, release-note-none, lgtm, approved, dco-signoff: yes, sig/code-quality

#7935 Remove VirtualMachineFlavor and VirtualMachinePreference SharedInformers
  manifests/generated/operator-csv.yaml.in
  manifests/generated/rbac-operator.authorization.k8s.yaml.in
  pkg/controller/BUILD.bazel
  pkg/controller/virtinformers.go
  pkg/flavor/BUILD.bazel
  pkg/flavor/flavor.go
  pkg/flavor/flavor_test.go
  pkg/virt-api/api.go
  pkg/virt-api/webhooks/utils.go
  pkg/virt-api/webhooks/validating-webhook/admitters/vms-admitter.go
  pkg/virt-controller/watch/BUILD.bazel
  pkg/virt-controller/watch/application.go
  pkg/virt-controller/watch/vm_test.go
  pkg/virt-operator/resource/generate/rbac/apiserver.go
  pkg/virt-operator/resource/generate/rbac/controller.go
Labels: size/L, release-note-none, lgtm, approved, dco-signoff: yes

#7946 Improving live migration metrics
  docs/metrics.md
  pkg/monitoring/domainstats/prometheus/prometheus.go
  pkg/monitoring/domainstats/prometheus/prometheus_test.go
  pkg/virt-launcher/virtwrap/live-migration-source.go
  pkg/virt-launcher/virtwrap/stats/types.go
  pkg/virt-launcher/virtwrap/statsconv/converter.go
  pkg/virt-launcher/virtwrap/statsconv/util/domstats_utils.go
  tools/doc-generator/doc-generator.go
Labels: size/M, release-note-none, lgtm, approved, dco-signoff: yes, area/monitoring

#7932 Monitoring VMI Migration Phase Transition Times
  api/openapi-spec/swagger.json
  pkg/controller/controller.go
  pkg/monitoring/migration/BUILD.bazel
  pkg/monitoring/migration/migration_suite_test.go
  pkg/monitoring/migration/migration_test.go
  pkg/monitoring/migration/prometheus.go
  pkg/monitoring/migration/vmi-migration-phase-transitions.go
  pkg/virt-controller/watch/application.go
  pkg/virt-controller/watch/migration.go
  pkg/virt-operator/resource/generate/components/validations_generated.go
  staging/src/kubevirt.io/api/core/v1/deepcopy_generated.go
  staging/src/kubevirt.io/api/core/v1/types.go
  staging/src/kubevirt.io/api/core/v1/types_swagger_generated.go
  staging/src/kubevirt.io/client-go/api/openapi_generated.go
Labels: size/L, release-note, lgtm, approved, dco-signoff: yes, area/monitoring

#7845 Fix CRD validation code generation
  tools/crd-validation-generator/validation-generator.go
Labels: size/M, release-note, lgtm, approved, ok-to-test, dco-signoff: yes

#7945 tests, libvmi: Adjust code to pass linter
  tests/libvmi/cloudinit.go
  tests/libvmi/status.go
  tests/libvmi/storage.go
  tests/libvmi/vmi.go
Labels: size/L, release-note-none, lgtm, approved, dco-signoff: yes, sig/code-quality

#7908 builder, makefile, lint: Introduce golangci-lint
  .golangci.yml
  Makefile
  hack/builder/Dockerfile
  hack/dockerized
Labels: size/L, release-note-none, lgtm, approved, dco-signoff: yes, sig/code-quality

#7984 [release-0.49] Backport 'Fix vm restore in case of restore size bigger then PVC requested size'
  pkg/virt-controller/watch/application.go
  pkg/virt-controller/watch/snapshot/restore.go
  pkg/virt-controller/watch/snapshot/restore_base.go
  pkg/virt-controller/watch/snapshot/restore_test.go
  pkg/virt-controller/watch/snapshot/snapshot.go
  pkg/virt-controller/watch/snapshot/snapshot_base.go
  tests/storage/restore.go
Labels: size/L, release-note, lgtm, approved, dco-signoff: yes

#7985 [release-0.44] Backport 'Fix vm restore in case of restore size bigger then PVC requested size'
  pkg/virt-controller/watch/application.go
  pkg/virt-controller/watch/snapshot/restore.go
  pkg/virt-controller/watch/snapshot/restore_base.go
  pkg/virt-controller/watch/snapshot/restore_test.go
  pkg/virt-controller/watch/snapshot/snapshot.go
  pkg/virt-controller/watch/snapshot/snapshot_base.go
  tests/storage/restore.go
Labels: size/L, release-note, lgtm, approved, dco-signoff: yes

#7960 Nominate alicefr as a reviewer
  OWNERS_ALIASES
Labels: size/XS, release-note-none, lgtm, approved, dco-signoff: yes

#7608 Add functest for critical alerts
  hack/prom-rule-ci/prom-rules-tests.yaml
  pkg/virt-operator/resource/generate/components/prometheus.go
  tests/monitoring/BUILD.bazel
  tests/monitoring/monitoring.go
Labels: size/L, release-note-none, lgtm, approved, dco-signoff: yes, area/monitoring

#7881 Move functionalities from tests/utils + Enable memory dump to be included in VMSnapshot
  pkg/virt-controller/watch/snapshot/restore.go
  pkg/virt-controller/watch/snapshot/restore_test.go
  pkg/virt-controller/watch/snapshot/snapshot.go
  pkg/virt-controller/watch/snapshot/snapshot_test.go
  pkg/virt-controller/watch/snapshot/source.go
  pkg/virt-controller/watch/vm.go
  pkg/virt-controller/watch/vm_test.go
  pkg/virt-handler/vm.go
  pkg/virt-handler/vm_test.go
  staging/src/kubevirt.io/api/core/v1/types.go
  tests/BUILD.bazel
  tests/credentials_test.go
  tests/libstorage/BUILD.bazel
  tests/libstorage/pvc.go
  tests/libstorage/storageclass.go
  tests/libvmi/BUILD.bazel
  tests/libvmi/storage.go
  tests/storage/datavolume.go
  tests/storage/guestfs.go
  tests/storage/hotplug.go
  tests/storage/imageupload.go
  tests/storage/memorydump.go
  tests/storage/restore.go
  tests/storage/snapshot.go
  tests/storage/storage.go
  tests/sysprep_test.go
  tests/template_test.go
  tests/testsuite/BUILD.bazel
  tests/testsuite/namespace.go
  tests/testsuite/serviceaccount.go
  tests/util/BUILD.bazel
  tests/util/labels.go
  tests/utils.go
  tests/vmi_cloudinit_test.go
  tests/vmi_lifecycle_test.go
  tests/windows_test.go
Labels: release-note, size/XXL, lgtm, approved, dco-signoff: yes, sig/code-quality

#7994 lint: Add `tests/libnet` to the linter coverage
  .golangci.yml
  Makefile
  tests/infra_test.go
  tests/libnet/cloudinit.go
  tests/libnet/cluster/cluster.go
  tests/libnet/dns.go
  tests/libnet/ipaddress.go
  tests/libnet/namespace.go
  tests/libnet/ping.go
  tests/libnet/service/service.go
  tests/libnet/skips.go
  tests/network/expose.go
  tests/network/port_forward.go
  tests/network/probes.go
  tests/network/services.go
  tests/network/vmi_istio.go
  tests/network/vmi_lifecycle.go
  tests/network/vmi_networking.go
  tests/storage/storage.go
  tests/windows_test.go
Labels: size/L, sig/network, release-note-none, lgtm, approved, dco-signoff: yes, sig/code-quality

#7943 k8s reporter, sriov: Dump /dev/vfio for kind providers only
  tests/reporter/kubernetes.go
Labels: size/S, release-note-none, lgtm, approved, dco-signoff: yes

#8007 tests: performance: update the expected number of created vmis
  tests/performance/density.go
Labels: size/XS, release-note-none, lgtm, approved, dco-signoff: yes

#7997 lint: Add `tests/console` to the linter coverage
  Makefile
  tests/console/console.go
  tests/console/login.go
Labels: size/L, release-note-none, lgtm, approved, dco-signoff: yes, sig/code-quality

#7987 utils, Expose error when update config fails
  tests/utils.go
Labels: size/XS, release-note-none, lgtm, approved, dco-signoff: yes

#7963 workspace: Bump alpine-with-tooling image
  WORKSPACE
  tests/libnet/ping.go
Labels: release-note, size/XS, lgtm, approved, dco-signoff: yes

#8011 Increase virt-launcher memory overhead
  pkg/virt-controller/services/template.go
  pkg/virt-controller/services/template_test.go
  tests/vmi_configuration_test.go
Labels: size/M, release-note, lgtm, approved, dco-signoff: yes
