Repository kubevirt/kubevirt, pull requests merged in 2022-07, with the labels that each got.

#7947 fix some type on doc
  docs/conformance.md
  docs/container-empty-disks.md
  docs/devel/guest-os-info.md
  docs/devel/olm-integration.md
  docs/devel/virtual-machine.md
  docs/filesystem-pv-disks.md
  docs/getting-started.md
  docs/gosec.md
  docs/guestfs.md
  docs/libvirt-pod-networking.md
  docs/localstorage-disks.md
  docs/release.md
  docs/reviewer-guide.md
  docs/updates.md
Labels: size/M, release-note-none, lgtm, approved, ok-to-test, dco-signoff: yes

#8003 Update to current reviewers list
  OWNERS_ALIASES
Labels: size/XS, release-note-none, lgtm, approved, dco-signoff: yes

#8012 Lint network code domain spec generator
  .golangci.yml
  Makefile
  pkg/network/domainspec/generators.go
  pkg/network/domainspec/generators_test.go
Labels: size/M, sig/network, release-note-none, lgtm, approved, dco-signoff: yes

#8020 gloangci-lint: Fix goimports local-prefixes
  .golangci.yml
  tests/console/login.go
  tests/libnet/cluster/cluster.go
  tests/libnet/dns.go
  tests/libnet/expose_util.go
  tests/libnet/namespace.go
  tests/libnet/ping.go
  tests/libvmi/status.go
Labels: size/XS, release-note-none, lgtm, approved, dco-signoff: yes

#8023 Quarantine 3188 test
  tests/storage/datavolume.go
Labels: size/XS, release-note-none, lgtm, approved, dco-signoff: yes

#7875 flavors: Introduce Flavor and Preference versions
  api/openapi-spec/swagger.json
  manifests/generated/operator-csv.yaml.in
  manifests/generated/rbac-operator.authorization.k8s.yaml.in
  pkg/flavor/BUILD.bazel
  pkg/flavor/flavor.go
  pkg/flavor/flavor_test.go
  pkg/testutils/mock_flavor.go
  pkg/util/types/patch.go
  pkg/virt-controller/watch/vm.go
  pkg/virt-controller/watch/vm_test.go
  pkg/virt-operator/resource/generate/components/validations_generated.go
  pkg/virt-operator/resource/generate/rbac/apiserver.go
  pkg/virt-operator/resource/generate/rbac/controller.go
  staging/src/kubevirt.io/api/core/v1/types.go
  staging/src/kubevirt.io/api/core/v1/types_swagger_generated.go
  staging/src/kubevirt.io/api/flavor/v1alpha1/deepcopy_generated.go
  staging/src/kubevirt.io/api/flavor/v1alpha1/types.go
  staging/src/kubevirt.io/api/flavor/v1alpha1/types_swagger_generated.go
  staging/src/kubevirt.io/client-go/api/openapi_generated.go
  tests/BUILD.bazel
  tests/flavor_test.go
Labels: release-note, size/XXL, lgtm, approved, dco-signoff: yes

#7791 Introduce initial deprecation policy: Deprecating feature gates
  docs/deprecation.md
Labels: size/M, release-note, lgtm, approved, dco-signoff: yes

#8022 Move tests specific functionalities from libvmi to the tests
  tests/libvmi/BUILD.bazel
  tests/libvmi/storage.go
  tests/storage/hotplug.go
  tests/storage/restore.go
  tests/storage/snapshot.go
Labels: size/L, release-note-none, lgtm, approved, dco-signoff: yes

#8028 Add proxy configuration to build system when host behind a firewall
  hack/dockerized
Labels: size/S, release-note-none, lgtm, approved, ok-to-test, dco-signoff: yes

#8030 Let github collapse BUILD.bazel files in certain locations
  .gitattributes
Labels: size/XS, release-note-none, lgtm, approved, dco-signoff: yes

#8036 Remove dead virtio cache link
  WORKSPACE
Labels: size/XS, release-note-none, lgtm, approved, dco-signoff: yes

#7925 tests, sriov: Improve error of finding VMI iface by MAC assert
  tests/network/sriov.go
Labels: sig/network, size/XS, release-note-none, lgtm, approved, dco-signoff: yes

#7966 Remove identity stripping logic leftovers from restore controller
  pkg/virt-controller/watch/snapshot/restore.go
  tests/storage/restore.go
Labels: size/M, release-note-none, lgtm, approved, dco-signoff: yes

#8062 Sync kubevirt dependencies
  vendor/modules.txt
Labels: size/XS, release-note-none, lgtm, approved, dco-signoff: yes

#8068 Set cache mode on hotplugged disks.
  pkg/virt-launcher/virtwrap/manager.go
  pkg/virt-launcher/virtwrap/manager_test.go
Labels: size/S, release-note, lgtm, approved, dco-signoff: yes

#8051 Add ginkgo linter
  BUILD.bazel
  go.mod
  nogo_config.json
  pkg/virt-api/webhooks/validating-webhook/admitters/vmi-create-admitter_test.go
  pkg/virt-controller/watch/export/export_test.go
  pkg/virt-controller/watch/snapshot/restore_test.go
  pkg/virt-handler/device-manager/mediated_devices_types_test.go
  pkg/virt-handler/isolation/isolation_test.go
  staging/src/kubevirt.io/client-go/api/defaults_test.go
  tests/infra_test.go
  tools/analyzers/ginkgolinter/BUILD.bazel
  tools/analyzers/ginkgolinter/README.md
  tools/analyzers/ginkgolinter/ginkgo_linter.go
Labels: size/L, release-note-none, lgtm, approved, dco-signoff: yes

#8065 virt-operator: Remove explicit subresources permissions
  manifests/generated/operator-csv.yaml.in
  manifests/generated/rbac-operator.authorization.k8s.yaml.in
  pkg/virt-operator/resource/generate/rbac/operator.go
Labels: size/M, release-note-none, lgtm, approved, dco-signoff: yes

#7460 Use libvmi consistently in storage tests
  tests/libvmi/storage.go
  tests/storage/storage.go
Labels: size/M, sig/network, release-note-none, lgtm, approved, dco-signoff: yes, sig/code-quality

#7981 flavors: Raise conflict if CPU or Memory resource requests are present when using flavors
  pkg/flavor/BUILD.bazel
  pkg/flavor/flavor.go
  pkg/flavor/flavor_test.go
  pkg/virt-controller/watch/vm_test.go
  tests/flavor_test.go
Labels: size/L, release-note, lgtm, approved, dco-signoff: yes

#8035 virtctl: Add option to wrap local scp client to scp command
  pkg/virtctl/scp/BUILD.bazel
  pkg/virtctl/scp/native.go
  pkg/virtctl/scp/scp.go
  pkg/virtctl/scp/scp_suite_test.go
  pkg/virtctl/scp/wrapped.go
  pkg/virtctl/scp/wrapped_test.go
  pkg/virtctl/ssh/knownhosts.go
  pkg/virtctl/ssh/knownhosts_test.go
  pkg/virtctl/ssh/native.go
  pkg/virtctl/ssh/resize_unix.go
  pkg/virtctl/ssh/ssh.go
  pkg/virtctl/ssh/wrapped.go
  pkg/virtctl/ssh/wrapped_test.go
  tests/virtctl/scp.go
  tests/virtctl/ssh.go
Labels: size/XL, release-note, lgtm, approved, dco-signoff: yes

#8015 [release-0.49] Make names of access tests around test_id:2921 unique
  tests/access_test.go
Labels: size/S, release-note-none, lgtm, approved, dco-signoff: yes

#7976 Add external export urls for VMExport CRD status.
  manifests/generated/operator-csv.yaml.in
  manifests/generated/rbac-operator.authorization.k8s.yaml.in
  pkg/certificates/triple/cert/cert.go
  pkg/controller/BUILD.bazel
  pkg/controller/virtinformers.go
  pkg/virt-controller/watch/BUILD.bazel
  pkg/virt-controller/watch/application.go
  pkg/virt-controller/watch/application_test.go
  pkg/virt-controller/watch/export/BUILD.bazel
  pkg/virt-controller/watch/export/export.go
  pkg/virt-controller/watch/export/export_test.go
  pkg/virt-operator/kubevirt_test.go
  pkg/virt-operator/resource/generate/rbac/controller.go
  tests/operator_test.go
  tests/storage/BUILD.bazel
  tests/storage/export.go
Labels: size/XL, release-note-none, lgtm, approved, dco-signoff: yes

#8013 [release-0.51] Make names of access tests around test_id:2921 unique
  tests/access_test.go
Labels: size/S, release-note-none, lgtm, approved, dco-signoff: yes

#8014 [release-0.50] Make names of access tests around test_id:2921 unique
  tests/access_test.go
Labels: size/S, release-note-none, lgtm, approved, dco-signoff: yes

#8070 tests, libvmi: Do not override dependent spec sub trees
  tests/libvmi/vmi.go
  tests/utils.go
  tests/vmi_configuration_test.go
Labels: size/M, release-note-none, lgtm, approved, dco-signoff: yes, sig/code-quality

#8053 Fix mechanism to fetch filesystem overhead when the CDI resource has a different name
  pkg/virt-controller/watch/vmi.go
  pkg/virt-controller/watch/vmi_test.go
Labels: size/L, release-note, lgtm, approved, dco-signoff: yes

#8010 podman: Support non root user via default root socket
  hack/common.sh
Labels: size/S, release-note-none, lgtm, approved, dco-signoff: yes

#7956 [release-0.45] Fixing host model support heterogeneus cluster
  pkg/virt-controller/watch/migration.go
  pkg/virt-controller/watch/migration_test.go
  pkg/virt-handler/node-labeller/cpu_plugin.go
  pkg/virt-handler/node-labeller/cpu_plugin_test.go
  pkg/virt-handler/node-labeller/node_labeller.go
  staging/src/kubevirt.io/client-go/api/v1/types.go
  tests/infra_test.go
  tests/migration_test.go
  tests/utils.go
Labels: size/L, release-note-none, kind/api-change, lgtm, approved, dco-signoff: yes

#7955 [release-0.46]Fixing host model support heterogeneus cluster
  pkg/virt-controller/watch/migration.go
  pkg/virt-controller/watch/migration_test.go
  pkg/virt-handler/node-labeller/cpu_plugin.go
  pkg/virt-handler/node-labeller/cpu_plugin_test.go
  pkg/virt-handler/node-labeller/node_labeller.go
  staging/src/kubevirt.io/client-go/api/v1/types.go
  tests/infra_test.go
  tests/migration_test.go
  tests/utils.go
Labels: size/L, release-note-none, kind/api-change, lgtm, approved, dco-signoff: yes

#7954 [release-0.47] Fixing host model support heterogeneus cluster
  pkg/virt-controller/watch/migration.go
  pkg/virt-controller/watch/migration_test.go
  pkg/virt-handler/node-labeller/cpu_plugin.go
  pkg/virt-handler/node-labeller/cpu_plugin_test.go
  pkg/virt-handler/node-labeller/node_labeller.go
  staging/src/kubevirt.io/client-go/apis/core/v1/types.go
  tests/infra_test.go
  tests/migration_test.go
  tests/utils.go
Labels: size/L, release-note-none, lgtm, approved, dco-signoff: yes

#8057 trivial: Increase timeout of device controller tests
  pkg/virt-handler/device-manager/device_controller_test.go
Labels: size/XS, release-note-none, lgtm, approved, dco-signoff: yes

#8059 [Clone API]: Fix race between VM and restore readiness
  pkg/virt-controller/watch/clone/BUILD.bazel
  pkg/virt-controller/watch/clone/clone.go
  pkg/virt-controller/watch/snapshot/restore.go
  pkg/virt-controller/watch/snapshot/snapshot.go
  tests/storage/clone.go
Labels: size/M, release-note-none, lgtm, approved, dco-signoff: yes

#7957 [release-0.44]Fixing host model support heterogeneus cluster
  pkg/virt-controller/watch/migration.go
  pkg/virt-controller/watch/migration_test.go
  pkg/virt-handler/node-labeller/cpu_plugin.go
  pkg/virt-handler/node-labeller/cpu_plugin_test.go
  pkg/virt-handler/node-labeller/node_labeller.go
  staging/src/kubevirt.io/client-go/api/v1/types.go
  tests/infra_test.go
  tests/migration_test.go
  tests/utils.go
Labels: size/L, release-note-none, kind/api-change, lgtm, approved, dco-signoff: yes

#8106 Quarantine flaky test for clone of more complicated VM
  tests/storage/clone.go
Labels: size/XS, release-note-none, lgtm, approved, dco-signoff: yes

#8076 tests, multi queue: Use pointer.Bool
  tests/vmi_multiqueue_test.go
Labels: size/S, release-note-none, lgtm, approved, dco-signoff: yes

#7545 e2e, use libvmi factory functions for creating VMIs
  tests/vmi_configuration_test.go
Labels: size/L, release-note-none, lgtm, approved, dco-signoff: yes, sig/code-quality

#7769 Fix --max-devices option
  pkg/virt-operator/resource/apply/apps.go
  pkg/virt-operator/resource/apply/apps_test.go
  tests/operator_test.go
Labels: size/S, release-note-none, lgtm, approved, ok-to-test, dco-signoff: yes

#7983 tests: shorten tests/utils
  Makefile
  tests/subresource_api_test.go
  tests/sysprep_test.go
  tests/template_test.go
  tests/utils.go
  tests/windows_test.go
Labels: size/M, release-note-none, lgtm, approved, dco-signoff: yes, sig/code-quality

#8081 golangci-lint: Increase timeout
  Makefile
Labels: size/XS, release-note-none, lgtm, approved, dco-signoff: yes

#8092 Bump the version of `go-restful` to 2.16.0
  go.mod
  go.sum
  staging/src/kubevirt.io/client-go/go.mod
  staging/src/kubevirt.io/client-go/go.sum
  vendor/github.com/emicklei/go-restful/BUILD.bazel
  vendor/github.com/emicklei/go-restful/CHANGES.md
  vendor/github.com/emicklei/go-restful/cors_filter.go
  vendor/github.com/emicklei/go-restful/parameter.go
  vendor/github.com/emicklei/go-restful/request.go
  vendor/github.com/emicklei/go-restful/response.go
  vendor/github.com/emicklei/go-restful/route.go
  vendor/github.com/emicklei/go-restful/route_reader.go
  vendor/github.com/emicklei/go-restful/web_service.go
  vendor/modules.txt
Labels: size/L, release-note, lgtm, approved, dco-signoff: yes

#7972 Remove redundant IsNotFound calls from `update-` and `patchWithSubresource` functions in utility file `status`
  pkg/util/status/status.go
Labels: size/M, release-note-none, lgtm, approved, ok-to-test, dco-signoff: yes

#8064 tests, storage, snapshot: Retry a flaky VMI Update
  tests/storage/BUILD.bazel
  tests/storage/snapshot.go
Labels: size/S, release-note-none, lgtm, approved, dco-signoff: yes

#7552 code cleanup: Use libvmi in performance and replicaset tests
  tests/libvmi/vmi.go
  tests/performance/BUILD.bazel
  tests/performance/density.go
  tests/performance/realtime.go
  tests/replicaset_test.go
Labels: size/L, release-note-none, lgtm, approved, dco-signoff: yes, sig/code-quality

#8061 [e2e tests]: improve the `config_test.go` suite
  tests/config_test.go
  tests/utils.go
Labels: size/L, release-note-none, lgtm, approved, dco-signoff: yes

#8078 Must clear "cloneRequest" annotation on restore of PVC
  pkg/virt-controller/watch/snapshot/restore.go
  tests/libstorage/BUILD.bazel
  tests/libstorage/datavolume.go
  tests/storage/BUILD.bazel
  tests/storage/restore.go
Labels: size/L, release-note-none, lgtm, approved, dco-signoff: yes

#8112 Fix failing tests on ipv6 only lane
  cluster-up-sha.txt
  cluster-up/hack/common.sh
  cluster-up/version.txt
  hack/config-default.sh
  pkg/virtctl/expose/expose.go
  pkg/virtctl/expose/expose_test.go
  tests/network/probes.go
  tests/pod_servers.go
Labels: size/M, sig/network, release-note, lgtm, approved, dco-signoff: yes

#8086 Fix race of deleting not ready vmsnapshot and freeze of vm
  pkg/virt-controller/watch/snapshot/snapshot.go
Labels: size/S, release-note-none, lgtm, approved, dco-signoff: yes

#8099 Respect the feature gate when exposing SEV device
  pkg/virt-handler/device-manager/device_controller.go
  pkg/virt-handler/device-manager/device_controller_test.go
  pkg/virt-handler/device-manager/mediated_device_test.go
  pkg/virt-handler/device-manager/mediated_devices_types_test.go
  pkg/virt-handler/device-manager/pci_device_test.go
  pkg/virt-handler/vm.go
  tests/launchsecurity/BUILD.bazel
  tests/launchsecurity/sev.go
Labels: size/L, release-note-none, lgtm, approved, dco-signoff: yes

#8083 [e2e tests]: fix test 6987 in operator suite
  tests/operator_test.go
Labels: size/XS, release-note-none, lgtm, approved, dco-signoff: yes

#7991 Virtctl Memory dump with create pvc
  api/openapi-spec/swagger.json
  pkg/util/BUILD.bazel
  pkg/util/types/BUILD.bazel
  pkg/util/types/pvc.go
  pkg/util/util.go
  pkg/virt-api/rest/BUILD.bazel
  pkg/virt-api/rest/subresource.go
  pkg/virt-api/rest/subresource_test.go
  pkg/virt-controller/watch/vm.go
  pkg/virt-controller/watch/vmi.go
  pkg/virt-operator/resource/generate/components/validations_generated.go
  pkg/virtctl/imageupload/BUILD.bazel
  pkg/virtctl/imageupload/imageupload_test.go
  pkg/virtctl/utils/BUILD.bazel
  pkg/virtctl/utils/test_utils.go
  pkg/virtctl/vm/BUILD.bazel
  pkg/virtctl/vm/vm.go
  pkg/virtctl/vm/vm_test.go
  staging/src/kubevirt.io/api/core/v1/types.go
  staging/src/kubevirt.io/api/core/v1/types_swagger_generated.go
  staging/src/kubevirt.io/client-go/api/openapi_generated.go
  tests/storage/memorydump.go
Labels: size/XL, release-note, lgtm, approved, dco-signoff: yes

#8140 Tests: Fix flaky io error
  tests/storage/storage.go
Labels: size/XS, release-note-none, lgtm, approved, dco-signoff: yes

#8120 Get VM clone test out of quarantine
  pkg/virt-controller/watch/snapshot/restore.go
  pkg/virt-controller/watch/snapshot/restore_test.go
  tests/storage/clone.go
Labels: size/L, release-note-none, lgtm, approved, dco-signoff: yes

#8130 [e2e tests]: improve operator test 4744
  tests/operator_test.go
Labels: size/M, release-note-none, lgtm, approved, dco-signoff: yes

#8097 add nodeSelector kubernetes.io/os: linux to virt-operator csv
  manifests/generated/operator-csv.yaml.in
  pkg/virt-operator/resource/generate/components/deployments.go
Labels: release-note, size/XS, lgtm, approved, dco-signoff: yes

#7849 Introducing passt - a new approach to user-mode networking for virtual machines
  WORKSPACE
  api/openapi-spec/swagger.json
  cmd/virt-handler/virt_launcher.cil
  hack/bootstrap.sh
  pkg/network/domainspec/BUILD.bazel
  pkg/network/domainspec/generators.go
  pkg/network/domainspec/generators_test.go
  pkg/network/driver/common.go
  pkg/network/driver/generated_mock_common.go
  pkg/network/infraconfigurators/BUILD.bazel
  pkg/network/infraconfigurators/passt.go
  pkg/network/setup/netstat.go
  pkg/network/setup/podnic.go
  pkg/util/sysctl/sysctl.go
  pkg/virt-api/webhooks/validating-webhook/admitters/vmi-create-admitter.go
  pkg/virt-api/webhooks/validating-webhook/admitters/vmi-create-admitter_test.go
  pkg/virt-config/feature-gates.go
  pkg/virt-controller/watch/migration_test.go
  pkg/virt-controller/watch/vmi.go
  pkg/virt-controller/watch/vmi_test.go
  pkg/virt-launcher/virtwrap/converter/network.go
  pkg/virt-operator/resource/generate/components/validations_generated.go
  rpm/BUILD.bazel
  rpm/repo.yaml
  staging/src/kubevirt.io/api/core/v1/deepcopy_generated.go
  staging/src/kubevirt.io/api/core/v1/schema.go
  staging/src/kubevirt.io/api/core/v1/schema_swagger_generated.go
  staging/src/kubevirt.io/api/core/v1/types.go
  staging/src/kubevirt.io/client-go/api/openapi_generated.go
  tests/job.go
  tests/libvmi/network.go
  tests/network/BUILD.bazel
  tests/network/vmi_istio.go
  tests/network/vmi_passt.go
  tests/testsuite/kubevirtresource.go
  tests/vmi_servers.go
Labels: sig/network, size/XL, release-note, lgtm, approved, dco-signoff: yes

#8087 tests: Windows tests small cleanup
  tests/windows_test.go
Labels: size/L, release-note-none, lgtm, approved, dco-signoff: yes, sig/code-quality

#8135 ADOPTERS: elaborate on ovirt/okd integration
  ADOPTERS.md
Labels: size/XS, release-note-none, lgtm, approved, dco-signoff: yes

#8162 tests: reuse GetComputeContainerOfPod
  tests/migration_test.go
  tests/utils.go
Labels: size/M, release-note-none, lgtm, approved, dco-signoff: yes, sig/code-quality

#8163 slow tests: adding cloud init network data to alpine VM
  tests/network/vmi_istio.go
  tests/network/vmi_passt.go
Labels: size/S, sig/network, release-note-none, lgtm, approved, dco-signoff: yes

#8093 vendor, Bump multus-client to v1.3.0
  go.mod
  go.sum
  vendor/github.com/fsnotify/fsnotify/.mailmap
  vendor/github.com/fsnotify/fsnotify/.travis.yml
  vendor/github.com/fsnotify/fsnotify/AUTHORS
  vendor/github.com/fsnotify/fsnotify/CHANGELOG.md
  vendor/github.com/fsnotify/fsnotify/README.md
  vendor/github.com/fsnotify/fsnotify/fen.go
  vendor/github.com/fsnotify/fsnotify/fsnotify.go
  vendor/github.com/fsnotify/fsnotify/inotify.go
  vendor/github.com/fsnotify/fsnotify/inotify_poller.go
  vendor/github.com/fsnotify/fsnotify/kqueue.go
  vendor/github.com/fsnotify/fsnotify/open_mode_bsd.go
  vendor/github.com/fsnotify/fsnotify/open_mode_darwin.go
  vendor/github.com/fsnotify/fsnotify/windows.go
  vendor/github.com/k8snetworkplumbingwg/network-attachment-definition-client/pkg/apis/k8s.cni.cncf.io/v1/types.go
  vendor/github.com/k8snetworkplumbingwg/network-attachment-definition-client/pkg/apis/k8s.cni.cncf.io/v1/zz_generated.deepcopy.go
  vendor/modules.txt
Labels: size/L, release-note-none, lgtm, approved, dco-signoff: yes

#8109 [release-0.49] back port :Bump the version of go-restful to 2.16.0
  go.mod
  go.sum
  tests/network/vmi_networking.go
  vendor/github.com/emicklei/go-restful/.travis.yml
  vendor/github.com/emicklei/go-restful/BUILD.bazel
  vendor/github.com/emicklei/go-restful/CHANGES.md
  vendor/github.com/emicklei/go-restful/Makefile
  vendor/github.com/emicklei/go-restful/README.md
  vendor/github.com/emicklei/go-restful/container.go
  vendor/github.com/emicklei/go-restful/cors_filter.go
  vendor/github.com/emicklei/go-restful/jsr311.go
  vendor/github.com/emicklei/go-restful/parameter.go
  vendor/github.com/emicklei/go-restful/path_processor.go
  vendor/github.com/emicklei/go-restful/request.go
  vendor/github.com/emicklei/go-restful/response.go
  vendor/github.com/emicklei/go-restful/route.go
  vendor/github.com/emicklei/go-restful/route_builder.go
  vendor/github.com/emicklei/go-restful/route_reader.go
  vendor/github.com/emicklei/go-restful/service_error.go
  vendor/github.com/emicklei/go-restful/web_service.go
  vendor/modules.txt
Labels: size/XL, release-note, lgtm, approved, dco-signoff: yes

#8141 Remove "should pause on IO error" test from quarantine
  tests/storage/storage.go
Labels: size/XS, release-note-none, lgtm, approved, dco-signoff: yes

#8127 e2e test: append `GPUGate` FG to existing ones instead of override them
  tests/mdev_configuration_allocation_test.go
Labels: size/XS, release-note-none, lgtm, approved, dco-signoff: yes

#8161 Use libvmi in tests/realtime/realtime.go
  tests/libvmi/BUILD.bazel
  tests/libvmi/performance.go
  tests/performance/BUILD.bazel
  tests/performance/realtime.go
  tests/realtime/BUILD.bazel
  tests/realtime/realtime.go
Labels: size/L, release-note-none, lgtm, approved, dco-signoff: yes

#8168 slow AlpineWithTestTooling startup
  tests/libvmi/factory.go
  tests/network/vmi_istio.go
  tests/network/vmi_passt.go
Labels: size/M, sig/network, release-note-none, lgtm, approved, dco-signoff: yes

#8173 VM Clone validation - make sure all PVCs snapshot-able
  pkg/virt-api/webhooks/validating-webhook/admitters/BUILD.bazel
  pkg/virt-api/webhooks/validating-webhook/admitters/vmclone-admitter.go
  pkg/virt-api/webhooks/validating-webhook/admitters/vmclone-admitter_test.go
  tests/storage/clone.go
  tests/storage/snapshot.go
Labels: size/L, release-note-none, lgtm, approved, dco-signoff: yes

#7814 Add VMI filesystem usage metrics
  docs/metrics.md
  pkg/monitoring/domainstats/prometheus/prometheus.go
  pkg/monitoring/domainstats/prometheus/prometheus_test.go
  tools/doc-generator/fakeCollector.go
Labels: size/L, release-note, lgtm, approved, dco-signoff: yes, area/monitoring

#7975 Refactor virt controller template resources
  pkg/virt-controller/services/BUILD.bazel
  pkg/virt-controller/services/renderresources.go
  pkg/virt-controller/services/renderresources_test.go
  pkg/virt-controller/services/template.go
Labels: size/XXL, release-note-none, lgtm, approved, dco-signoff: yes, sig/code-quality

#7736 Flaky test: pause on IO error
  tests/io_utils.go
  tests/storage/storage.go
Labels: size/S, release-note-none, lgtm, approved, dco-signoff: yes

#7986 [Bug-fix]: Windows VM HyperV Reenlightenment enabled fails to migrate
  pkg/virt-api/webhooks/hyperv.go
  pkg/virt-controller/watch/topology/BUILD.bazel
  pkg/virt-controller/watch/topology/hinter.go
  pkg/virt-controller/watch/topology/tsc.go
  pkg/virt-controller/watch/topology/tsc_test.go
  pkg/virt-controller/watch/vmi.go
  pkg/virt-controller/watch/vmi_test.go
  pkg/virt-launcher/virtwrap/converter/converter.go
  tests/BUILD.bazel
  tests/libvmi/vmi.go
  tests/migration_test.go
  tests/windows_test.go
Labels: size/L, release-note, lgtm, approved, dco-signoff: yes

#8047 Deprecate live migration feature gate
  pkg/virt-api/webhooks/validating-webhook/admitters/migration-create-admitter.go
  pkg/virt-api/webhooks/validating-webhook/admitters/migration-create-admitter_test.go
  pkg/virt-api/webhooks/validating-webhook/admitters/pod-eviction-admitter.go
  pkg/virt-api/webhooks/validating-webhook/admitters/pod-eviction-admitter_test.go
  pkg/virt-api/webhooks/validating-webhook/admitters/vmi-create-admitter.go
  pkg/virt-api/webhooks/validating-webhook/admitters/vmi-create-admitter_test.go
  pkg/virt-config/configuration_test.go
  pkg/virt-config/feature-gates.go
  pkg/virt-operator/application.go
  pkg/virt-operator/webhooks/BUILD.bazel
  pkg/virt-operator/webhooks/kubevirt-update-admitter.go
  pkg/virt-operator/webhooks/kubevirt-update-admitter_test.go
  tests/framework/checks/skips.go
  tests/operator_test.go
Labels: size/XL, release-note, lgtm, approved, dco-signoff: yes

#8111 podman: Use kubevirtci's KUBEVIRTCI_PODMAN_SOCKET
  hack/common.sh
Labels: size/XS, release-note-none, lgtm, approved, dco-signoff: yes

#8136 Fix cgroups unit tests: mock out underlying runc cgroup manager
  pkg/virt-handler/cgroup/cgroup.go
  pkg/virt-handler/cgroup/cgroup_test.go
  pkg/virt-handler/cgroup/cgroup_v1_manager.go
  pkg/virt-handler/cgroup/cgroup_v2_manager.go
  pkg/virt-handler/cgroup/generated_mock_cgroup.go
Labels: size/L, release-note, lgtm, approved, dco-signoff: yes

#8160 cmd, dump: Publish k8s reporter dump
  automation/release.sh
Labels: size/XS, release-note-none, lgtm, approved, dco-signoff: yes

#8174 Add scale OWNERS
  OWNERS_ALIASES
  hack/OWNERS
  pkg/monitoring/perfscale/OWNERS
  tests/performance/OWNERS
  tools/OWNERS
Labels: size/S, release-note-none, lgtm, approved, dco-signoff: yes, area/monitoring

#8178 [release-0.53] [e2e tests]: improve operator test 4744
  tests/operator_test.go
Labels: size/M, release-note-none, lgtm, approved, dco-signoff: yes

#8027 Add isGarbageCollected to perfscale-load-generator ObjListWatcher
  tools/perfscale-load-generator/watcher/watcher.go
Labels: size/M, release-note, lgtm, approved, ok-to-test, dco-signoff: yes

#8182 De-quarantine simple clone functest
  tests/storage/clone.go
Labels: size/XS, release-note-none, lgtm, approved, dco-signoff: yes

#8201 [release-0.53] [Bug-fix]: Windows VM HyperV Reenlightenment enabled fails to migrate
  pkg/virt-api/webhooks/hyperv.go
  pkg/virt-controller/watch/topology/BUILD.bazel
  pkg/virt-controller/watch/topology/hinter.go
  pkg/virt-controller/watch/topology/tsc.go
  pkg/virt-controller/watch/topology/tsc_test.go
  pkg/virt-controller/watch/vmi.go
  pkg/virt-controller/watch/vmi_test.go
  pkg/virt-launcher/virtwrap/converter/converter.go
  tests/BUILD.bazel
  tests/migration_test.go
Labels: size/L, release-note, lgtm, approved, dco-signoff: yes

#8193 virtctl: Add build tag to allow excluding native SSH
  pkg/virtctl/scp/BUILD.bazel
  pkg/virtctl/scp/native.go
  pkg/virtctl/scp/native_unsupported.go
  pkg/virtctl/ssh/BUILD.bazel
  pkg/virtctl/ssh/knownhosts.go
  pkg/virtctl/ssh/knownhosts_test.go
  pkg/virtctl/ssh/native.go
  pkg/virtctl/ssh/native_unsupported.go
  pkg/virtctl/ssh/resize_unix.go
  pkg/virtctl/ssh/resize_windows.go
  pkg/virtctl/ssh/ssh.go
Labels: size/M, release-note-none, lgtm, approved, dco-signoff: yes

#8203 VMExport: Check the error before emitting events
  pkg/virt-controller/watch/export/export.go
Labels: size/S, release-note-none, lgtm, approved, dco-signoff: yes

#8153 Tests: Clean migration tests (part 1)
  tests/migration_test.go
Labels: size/L, release-note-none, lgtm, approved, dco-signoff: yes

#8206 Resolve flakiness in vmexport feature gate disabled test
  tests/operator_test.go
Labels: size/M, release-note-none, lgtm, approved, dco-signoff: yes

#8180 libvmi: Split performance.go into cpu.go and memory.go
  tests/libvmi/BUILD.bazel
  tests/libvmi/cpu.go
  tests/libvmi/memory.go
Labels: size/M, release-note-none, lgtm, approved, dco-signoff: yes

#8192 build-go.sh: Introduce KUBEVIRT_GO_BUILD_TAGS
  Makefile
  hack/build-go.sh
  hack/common.sh
Labels: size/M, release-note-none, lgtm, approved, dco-signoff: yes

#8213 Run make deps-sync to correct go.mod
  go.mod
Labels: size/XS, release-note-none, lgtm, approved, dco-signoff: yes

#8172 instancetype: Require Guest within MemoryInstancetype
  api/openapi-spec/swagger.json
  pkg/instancetype/instancetype.go
  pkg/instancetype/instancetype_test.go
  pkg/virt-controller/watch/vm_test.go
  pkg/virt-operator/resource/generate/components/validations_generated.go
  staging/src/kubevirt.io/api/instancetype/v1alpha1/deepcopy_generated.go
  staging/src/kubevirt.io/api/instancetype/v1alpha1/types.go
  staging/src/kubevirt.io/client-go/api/openapi_generated.go
  tests/instancetype_test.go
  tools/vms-generator/utils/utils.go
Labels: size/L, release-note-none, lgtm, approved, dco-signoff: yes

#8211 Simplify template service
  pkg/virt-controller/services/template.go
Labels: size/M, release-note-none, lgtm, approved, dco-signoff: yes, sig/code-quality

#8185 [e2e tests] improvements in the VM pool suite
  tests/pool_test.go
Labels: size/XS, release-note-none, lgtm, approved, dco-signoff: yes

#7599 [Live-Migrations / Bugfix]: Allow aborting non-running migrations
  pkg/util/migrations/migrations.go
  pkg/virt-controller/watch/migration.go
  pkg/virt-controller/watch/migration_test.go
  pkg/virt-handler/vm.go
  pkg/virt-launcher/virtwrap/BUILD.bazel
  pkg/virt-launcher/virtwrap/live-migration-source.go
  tests/libnode/BUILD.bazel
  tests/libnode/node.go
  tests/migration_test.go
  tests/utils.go
  tests/virt_control_plane_test.go
Labels: size/L, release-note, lgtm, approved, dco-signoff: yes

#8116 tests: Replace `Update` with `Patch`
  pkg/controller/controller.go
  pkg/util/types/patch.go
  pkg/virt-controller/watch/drain/disruptionbudget/BUILD.bazel
  pkg/virt-controller/watch/drain/disruptionbudget/disruptionbudget.go
  pkg/virt-controller/watch/drain/disruptionbudget/disruptionbudget_test.go
  pkg/virt-controller/watch/migration.go
  tests/BUILD.bazel
  tests/infra_test.go
  tests/instancetype_test.go
  tests/pool_test.go
  tests/replicaset_test.go
  tests/storage/BUILD.bazel
  tests/storage/datavolume.go
  tests/storage/export.go
  tests/storage/restore.go
  tests/storage/snapshot.go
Labels: size/L, release-note-none, lgtm, approved, dco-signoff: yes

#8202 Fixing flacky test_id:3202
  tests/vmi_lifecycle_test.go
Labels: size/S, release-note-none, lgtm, approved, dco-signoff: yes
