Repository kubevirt/kubevirt, pull requests merged in 2022-03, with the labels that each got.

#7296 Update pr-creator in builder image
  hack/builder/Dockerfile
  hack/dockerized
Labels: size/XS, release-note-none, lgtm, approved, dco-signoff: yes

#7250 e2e: enrich phase matcher
  tests/framework/matcher/BUILD.bazel
  tests/framework/matcher/getter.go
  tests/framework/matcher/helper/BUILD.bazel
  tests/framework/matcher/helper/reflect.go
  tests/framework/matcher/owner.go
  tests/framework/matcher/phase.go
  tests/framework/matcher/phase_test.go
Labels: size/L, release-note-none, lgtm, approved, dco-signoff: yes

#7239 pool_test: simplify by using libvmi.NewCirros and tidying newPoolFromVMI up
  tests/BUILD.bazel
  tests/pool_test.go
  tests/utils.go
Labels: size/M, release-note-none, lgtm, approved, dco-signoff: yes

#7292 [e2e]: taking test_id:4744 out of quarantine
  tests/operator_test.go
Labels: size/XS, release-note-none, lgtm, approved, dco-signoff: yes

#7241 sysprep: Allow only unattend.xml to be provided
  pkg/config/BUILD.bazel
  pkg/config/sysprep.go
  pkg/config/sysprep_test.go
Labels: size/M, release-note, lgtm, approved, ok-to-test, dco-signoff: yes

#7237 Add test cases for runbook URLs
  tests/monitoring/monitoring.go
Labels: size/S, release-note-none, lgtm, approved, ok-to-test, dco-signoff: yes

#7252 partial cleanup of network probes tests
  tests/network/probes.go
Labels: size/L, sig/network, release-note-none, lgtm, approved, dco-signoff: yes

#7303 Make "delete a KubeVirt CR" test Serial
  tests/dryrun_test.go
Labels: size/XS, release-note-none, lgtm, approved, dco-signoff: yes

#6709 Enable live migration from root to nonroot
  api/openapi-spec/swagger.json
  pkg/util/util.go
  pkg/virt-api/webhooks/mutating-webhook/mutators/vmi-mutator.go
  pkg/virt-api/webhooks/mutating-webhook/mutators/vmi-mutator_test.go
  pkg/virt-controller/services/template_test.go
  pkg/virt-controller/watch/migration.go
  pkg/virt-operator/resource/generate/components/validations_generated.go
  staging/src/kubevirt.io/api/core/v1/types.go
  staging/src/kubevirt.io/api/core/v1/types_swagger_generated.go
  staging/src/kubevirt.io/client-go/api/openapi_generated.go
  staging/src/kubevirt.io/client-go/api/schema_test.go
  tests/migration_test.go
  tests/nonroot_test.go
  tests/utils.go
  tests/vmipreset_test.go
Labels: size/L, release-note, lgtm, approved, dco-signoff: yes

#7288 Add default container annotation to Pod
  go.mod
  go.sum
  pkg/virt-controller/services/BUILD.bazel
  pkg/virt-controller/services/template.go
  pkg/virt-controller/services/template_test.go
  tests/kubectl_test.go
  vendor/k8s.io/kubectl/LICENSE
  vendor/k8s.io/kubectl/pkg/cmd/util/podcmd/BUILD.bazel
  vendor/k8s.io/kubectl/pkg/cmd/util/podcmd/podcmd.go
  vendor/modules.txt
Labels: size/XL, release-note, lgtm, approved, ok-to-test, dco-signoff: yes

#7225 tests: inline RunVMIAndExpectLaunchWithIgnoreWarningArg
  tests/kubectl_test.go
  tests/migration_test.go
  tests/network/vmi_multus.go
  tests/network/vmi_networking.go
  tests/pausing_test.go
  tests/storage/storage.go
  tests/utils.go
Labels: size/M, sig/network, release-note-none, lgtm, approved, dco-signoff: yes

#7251 clean container_disk_test a bit
  tests/container_disk_test.go
Labels: size/M, release-note-none, lgtm, approved, dco-signoff: yes

#7106 docs, probes: simplify doc
  docs/probes.md
Labels: size/S, release-note-none, lgtm, approved, dco-signoff: yes

#7285 Update KubevirtVmHighMemoryUsage alert
  hack/prom-rule-ci/prom-rules-tests.yaml
  pkg/virt-operator/resource/generate/components/prometheus.go
Labels: size/M, release-note-none, lgtm, approved, dco-signoff: yes, area/monitoring

#7313 Update deprecated function calls
  pkg/util/cluster/cluster.go
  pkg/virt-controller/watch/workload-updater/workload-updater.go
  pkg/virt-operator/application.go
  pkg/virt-operator/util/client.go
  tests/infra_test.go
  tests/migration_test.go
  tests/operator_test.go
  tests/reporter/kubernetes.go
  tests/virt_control_plane_test.go
Labels: size/S, release-note-none, lgtm, approved, dco-signoff: yes

#7227 Remove the VMI informer from virt-api
  pkg/virt-api/api.go
  pkg/virt-api/webhooks/utils.go
  pkg/virt-api/webhooks/validating-webhook/admitters/migration-create-admitter.go
  pkg/virt-api/webhooks/validating-webhook/admitters/migration-create-admitter_test.go
  pkg/virt-api/webhooks/validating-webhook/admitters/vms-admitter.go
  pkg/virt-api/webhooks/validating-webhook/admitters/vms-admitter_test.go
  pkg/virt-api/webhooks/validating-webhook/validating-webhook.go
Labels: size/L, release-note, lgtm, approved, dco-signoff: yes

#7304 Remove the kubevirt.io/client-go/api dependency from kubevirt.io/tests
  tests/BUILD.bazel
  tests/network/BUILD.bazel
  tests/network/vmi_slirp_interface.go
  tests/utils.go
Labels: size/S, sig/network, release-note-none, lgtm, approved, ok-to-test, dco-signoff: yes

#6955 Update deprecated v1beta1 poddisruptionbudget api calls
  pkg/controller/BUILD.bazel
  pkg/controller/virtinformers.go
  pkg/testutils/BUILD.bazel
  pkg/testutils/mock_queue.go
  pkg/util/pdbs/BUILD.bazel
  pkg/util/pdbs/pdbs.go
  pkg/virt-controller/watch/BUILD.bazel
  pkg/virt-controller/watch/application.go
  pkg/virt-controller/watch/application_test.go
  pkg/virt-controller/watch/drain/disruptionbudget/BUILD.bazel
  pkg/virt-controller/watch/drain/disruptionbudget/disruptionbudget.go
  pkg/virt-controller/watch/drain/disruptionbudget/disruptionbudget_test.go
  pkg/virt-controller/watch/drain/evacuation/evacuation_test.go
  pkg/virt-controller/watch/migration.go
  pkg/virt-controller/watch/migration_test.go
  pkg/virt-controller/watch/workload-updater/workload-updater_test.go
  pkg/virt-operator/BUILD.bazel
  pkg/virt-operator/kubevirt_test.go
  pkg/virt-operator/resource/apply/BUILD.bazel
  pkg/virt-operator/resource/apply/apps.go
  pkg/virt-operator/resource/apply/apps_test.go
  pkg/virt-operator/resource/apply/delete.go
  pkg/virt-operator/resource/apply/generations.go
  pkg/virt-operator/resource/apply/pdb_test.go
  pkg/virt-operator/resource/generate/components/BUILD.bazel
  pkg/virt-operator/resource/generate/components/deployments.go
  tests/BUILD.bazel
  tests/migration_test.go
  tests/operator_test.go
  tests/virt_control_plane_test.go
Labels: size/L, release-note-none, lgtm, approved, ok-to-test, dco-signoff: yes, area/monitoring

#7195 Add tests for kubernetes.io/os node label
  pkg/virt-operator/resource/apply/reconcile.go
  tests/BUILD.bazel
  tests/operator_test.go
  tests/vmi_lifecycle_test.go
Labels: size/M, release-note-none, lgtm, approved, dco-signoff: yes

#7302 remove the annoying timeout error from being an error during cluster cleanup
  hack/cluster-clean.sh
Labels: size/XS, release-note-none, lgtm, approved, dco-signoff: yes

#7167 tests: Relocate migration network test
  automation/test.sh
  tests/migration_test.go
  tests/network/vmi_networking.go
Labels: size/M, sig/network, release-note-none, lgtm, approved, dco-signoff: yes

#7269 virt-operator: remove redundant object DeepCopy
  pkg/virt-operator/resource/apply/reconcile.go
  pkg/virt-operator/resource/apply/update.go
Labels: size/XS, release-note-none, lgtm, approved, dco-signoff: yes

#7312 tests/network/vmi_networking: use WaitUntilVMIReady return value
  tests/network/vmi_networking.go
Labels: size/S, sig/network, release-note-none, lgtm, approved, dco-signoff: yes

#7327 tests: make secondary NIC configurable
  hack/config-default.sh
  hack/functests.sh
  tests/flags/flags.go
  tests/migration.go
Labels: size/XS, release-note-none, lgtm, approved, dco-signoff: yes

#7289 tests: remove the VM watch tests
  tests/BUILD.bazel
  tests/vm_watch_test.go
Labels: size/L, release-note-none, lgtm, approved, dco-signoff: yes

#7315 tests/network: drop references to tests.BashHelloScript
  tests/network/vmi_multus.go
  tests/network/vmi_networking.go
Labels: size/M, sig/network, release-note-none, lgtm, approved, dco-signoff: yes

#7340 Avoid to return nil failure message
  pkg/virt-controller/watch/vm.go
Labels: size/XS, release-note-none, lgtm, approved, ok-to-test, dco-signoff: yes

#7287 Remove fstrim tests from quarantine.
  tests/storage/datavolume.go
Labels: size/XS, release-note-none, lgtm, approved, dco-signoff: yes

#7158 Support single stack IPv6
  hack/functests.sh
  pkg/network/dhcp/masquerade.go
  pkg/network/dhcp/masquerade_test.go
  pkg/network/driver/common.go
  pkg/network/driver/generated_mock_common.go
  pkg/network/infraconfigurators/masquerade.go
  pkg/network/infraconfigurators/masquerade_test.go
  tests/console/BUILD.bazel
  tests/console/login.go
  tests/infra_test.go
  tests/libnet/BUILD.bazel
  tests/libnet/cluster/BUILD.bazel
  tests/libnet/cluster/cluster.go
  tests/libnet/ipaddress.go
  tests/libnet/ipv6.go
  tests/libnet/skips.go
  tests/network/BUILD.bazel
  tests/network/dual_stack_cluster.go
  tests/network/expose.go
  tests/network/port_forward.go
  tests/network/primary_pod_network.go
  tests/network/probes.go
  tests/network/services.go
  tests/network/vmi_istio.go
  tests/network/vmi_lifecycle.go
  tests/network/vmi_networking.go
  tests/network/vmi_slirp_interface.go
  tests/network/vmi_subdomain.go
  tests/storage/storage.go
  tests/vmi_servers.go
Labels: sig/network, size/XL, release-note, lgtm, approved, dco-signoff: yes

#7233 Fix migration abort
  pkg/virt-launcher/virtwrap/BUILD.bazel
  pkg/virt-launcher/virtwrap/live-migration-source.go
  pkg/virt-launcher/virtwrap/manager_test.go
Labels: size/L, release-note, lgtm, approved, dco-signoff: yes

#7275 [virt-operator] Add observedGeneration to Kubevirt CR status
  api/openapi-spec/swagger.json
  manifests/generated/kv-resource.yaml
  pkg/virt-operator/BUILD.bazel
  pkg/virt-operator/kubevirt.go
  pkg/virt-operator/kubevirt_test.go
  pkg/virt-operator/resource/generate/components/validations_generated.go
  staging/src/kubevirt.io/api/core/v1/deepcopy_generated.go
  staging/src/kubevirt.io/api/core/v1/types.go
  staging/src/kubevirt.io/client-go/api/openapi_generated.go
  tests/operator_test.go
Labels: size/M, release-note, lgtm, approved, dco-signoff: yes

#7255 Added ability to specify VNC proxy listening address
  pkg/virtctl/vnc/vnc.go
Labels: size/S, sig/network, release-note, lgtm, approved, ok-to-test, dco-signoff: yes

#7333 tests/numa: use libvmi.NewCirros()
  tests/numa/BUILD.bazel
  tests/numa/numa.go
Labels: size/S, release-note-none, lgtm, approved, dco-signoff: yes

#7335 Add `make format` to Makefile
  Makefile
Labels: size/XS, release-note-none, lgtm, approved, dco-signoff: yes

#7355 tests/network: avoid Expect(len())
  tests/network/expose.go
  tests/network/vmi_multus.go
Labels: size/S, sig/network, release-note-none, lgtm, approved, dco-signoff: yes

#7362 tests/utils: do not expose ApiServerCloseConnectionError
  tests/utils.go
Labels: size/S, release-note-none, lgtm, approved, dco-signoff: yes

#7358 tests/storage: avoid Expect(len())
  tests/storage/hotplug.go
  tests/storage/restore.go
Labels: size/XS, release-note-none, lgtm, approved, dco-signoff: yes

#7351 Move Zvi to emeritus approvers
  OWNERS_ALIASES
Labels: size/XS, release-note-none, lgtm, approved, dco-signoff: yes

#7342 tests/network: drop remaining NewRandomVMIWithEphemeralDiskAndUserdata
  tests/libvmi/cloudinit.go
  tests/network/vmi_lifecycle.go
  tests/network/vmi_multus.go
  tests/network/vmi_networking.go
Labels: size/M, sig/network, release-note-none, lgtm, approved, dco-signoff: yes

#7366 k8s reporter: Limit node info collection
  tests/reporter/kubernetes.go
Labels: size/S, release-note-none, lgtm, approved, dco-signoff: yes

#7394 Remove Zvi from the list of reviewers
  OWNERS_ALIASES
Labels: size/XS, release-note-none, lgtm, approved, dco-signoff: yes

#7369 [e2e]: consolidate operator tests under single suite
  tests/BUILD.bazel
  tests/operator_test.go
  tests/tests_suite_test.go
  tests/virtoperatorbasic/BUILD.bazel
  tests/virtoperatorbasic/virtoperator_basic.go
Labels: size/L, release-note-none, lgtm, approved, dco-signoff: yes

#7383 network, e2e tests: use libvmi to create CirrOS VMs with slirp network
  tests/libvmi/network.go
  tests/network/vmi_slirp_interface.go
  tests/utils.go
Labels: size/S, sig/network, release-note-none, lgtm, approved, dco-signoff: yes

#7375 network, unit tests: avoid Expect(len())...
  pkg/network/dhcp/serverv6/serverv6_test.go
  pkg/network/domainspec/generators_test.go
Labels: size/S, sig/network, release-note-none, lgtm, approved, dco-signoff: yes

#7361 Preserve path for cluster server endpoints (fixes virtctl with Rancher)
  staging/src/kubevirt.io/client-go/kubecli/vmi.go
Labels: release-note, size/XS, lgtm, approved, ok-to-test, dco-signoff: yes

#7387 [Code Cleaning]: Use "HaveLen()" instead of "len(...).To(Equal(..)" in vmi test
  pkg/virt-controller/watch/vmi_test.go
Labels: size/S, release-note-none, lgtm, approved, dco-signoff: yes

#7400 conditions, test: replace `Expect(len(..).To(Equal(..))` with `Expect(..).To(HaveLen(..))`
  pkg/controller/conditions_test.go
Labels: size/XS, release-note-none, lgtm, approved, dco-signoff: yes

#7395 cloud-init, test: replace `Expect(len(..).To(Equal(..))` with `Expect(..).To(HaveLen(..))`
  pkg/cloud-init/cloud-init_test.go
Labels: size/XS, release-note-none, lgtm, approved, dco-signoff: yes

#7388 [Code Cleaning]: Use "HaveLen()" instead of "len(...).To(Equal(..)" in cache test
  pkg/virt-handler/cache/cache_test.go
Labels: size/XS, release-note-none, lgtm, approved, dco-signoff: yes

#7384 [Code Cleaning]: Use "HaveLen()" instead of "len(...).To(Equal(..)" in pool test
  pkg/virt-controller/watch/pool_test.go
Labels: size/S, release-note-none, lgtm, approved, dco-signoff: yes

#7376 [Code Cleaning]: Use "HaveLen()" instead of "len(...).To(Equal(..)" in vmi preset admitter test
  pkg/virt-api/webhooks/validating-webhook/admitters/vmi-preset-admitter_test.go
Labels: size/XS, release-note-none, lgtm, approved, dco-signoff: yes

#7392 [Code Cleaning]: Use "HaveLen()" instead of "len(...).To(Equal(..)" in mediated device types test
  pkg/virt-handler/device-manager/mediated_devices_types_test.go
Labels: size/XS, release-note-none, lgtm, approved, dco-signoff: yes

#7377 [Code Cleaning]: Use "HaveLen()" instead of "len(...).To(Equal(..)" in vmi update admitter test
  pkg/virt-operator/webhooks/kubevirt-update-admitter_test.go
Labels: size/XS, release-note-none, lgtm, approved, dco-signoff: yes

#7381 [Code Cleaning]: Use "HaveLen()" instead of "len(...).To(Equal(..)" in template test
  pkg/virt-controller/services/template_test.go
Labels: size/M, release-note-none, lgtm, approved, dco-signoff: yes

#7382 [Code Cleaning]: Use "HaveLen()" instead of "len(...).To(Equal(..)" in template test
  pkg/virt-controller/watch/migration_test.go
Labels: size/S, release-note-none, lgtm, approved, dco-signoff: yes

#7389 [Code Cleaning]: Use "HaveLen()" instead of "len(...).To(Equal(..)" in client test
  pkg/virt-handler/cmd-client/client_test.go
Labels: size/XS, release-note-none, lgtm, approved, dco-signoff: yes

#7374 [Code Cleaning]: Use "HaveLen()" instead of "len(...).To(Equal(..)" in vmi create admitter test
  pkg/virt-api/webhooks/validating-webhook/admitters/vmi-create-admitter_test.go
Labels: size/L, sig/network, release-note-none, lgtm, approved, dco-signoff: yes

#7386 [Code Cleaning]: Use "HaveLen()" instead of "len(...).To(Equal(..)" in vm test
  pkg/virt-controller/watch/vm_test.go
Labels: size/S, release-note-none, lgtm, approved, dco-signoff: yes

#7390 [Code Cleaning]: Use "HaveLen()" instead of "len(...).To(Equal(..)" in mount test
  pkg/virt-handler/container-disk/mount_test.go
Labels: size/XS, release-note-none, lgtm, approved, dco-signoff: yes

#7391 [Code Cleaning]: Use "HaveLen()" instead of "len(...).To(Equal(..)" in mediated device test
  pkg/virt-handler/device-manager/mediated_device_test.go
Labels: size/S, release-note-none, lgtm, approved, dco-signoff: yes

#7393 [Code Cleaning]: Use "HaveLen()" instead of "len(...).To(Equal(..)" in pci device test
  pkg/virt-handler/device-manager/pci_device_test.go
Labels: size/S, release-note-none, lgtm, approved, dco-signoff: yes

#7404 replace gomega `Equal(nil)` matchers, with `BeNil()`
  pkg/virt-launcher/virtwrap/cmd-server/server_test.go
  pkg/virt-launcher/virtwrap/converter/converter_test.go
  pkg/virt-launcher/virtwrap/manager_test.go
  tests/network/vmi_slirp_interface.go
Labels: size/S, sig/network, release-note-none, lgtm, approved, dco-signoff: yes

#7378 [Code Cleaning]: Use "HaveLen()" instead of "len(...).To(Equal(..)" in vmrestore admitter test
  pkg/virt-api/webhooks/validating-webhook/admitters/vmrestore-admitter_test.go
Labels: size/S, release-note-none, lgtm, approved, dco-signoff: yes

#7379 [Code Cleaning]: Use "HaveLen()" instead of "len(...).To(Equal(..)" in vms admitter test
  pkg/virt-api/webhooks/validating-webhook/admitters/vms-admitter_test.go
Labels: size/M, release-note-none, lgtm, approved, dco-signoff: yes

#7337 [release-0.49] Bump kubevirtci
  automation/test.sh
  cluster-up-sha.txt
  cluster-up/cluster/K8S_DEV_GUIDE.md
  cluster-up/cluster/ephemeral-provider-common.sh
  cluster-up/cluster/k8s-1.20/provider.sh
  cluster-up/cluster/kind-1.23-vgpu/README.md
  cluster-up/cluster/kind-1.23-vgpu/config_vgpu_cluster.sh
  cluster-up/cluster/kind-1.23-vgpu/provider.sh
  cluster-up/cluster/kind-1.23-vgpu/vgpu-node/node.sh
  cluster-up/hack/common.sh
  cluster-up/version.txt
  hack/config-default.sh
Labels: size/L, release-note-none, lgtm, approved, dco-signoff: yes

#7385 [Code Cleaning]: Use "HaveLen()" instead of "len(...).To(Equal(..)" in snapshot test
  pkg/virt-controller/watch/snapshot/snapshot_test.go
Labels: size/S, release-note-none, lgtm, approved, dco-signoff: yes

#7380 [Code Cleaning]: Use "HaveLen()" instead of "len(...).To(Equal(..)" in vmsnapshot admitter test
  pkg/virt-api/webhooks/validating-webhook/admitters/vmsnapshot-admitter_test.go
Labels: size/S, release-note-none, lgtm, approved, dco-signoff: yes

#7416 docs: add issue templates
  .github/ISSUE_TEMPLATE.md
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/docs_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: size/L, release-note-none, lgtm, approved, ok-to-test, dco-signoff: yes

#7218 Manage ownership of hotplug dev&disk
  pkg/ephemeral-disk-utils/BUILD.bazel
  pkg/ephemeral-disk-utils/generated_mock_utils.go
  pkg/ephemeral-disk-utils/utils.go
  pkg/virt-handler/hotplug-disk/BUILD.bazel
  pkg/virt-handler/hotplug-disk/mount.go
  pkg/virt-handler/hotplug-disk/mount_test.go
Labels: size/M, release-note-none, lgtm, approved, dco-signoff: yes

#7321 [Migration Policies]: Precedence to VMI labels over Namespace labels
  pkg/virt-controller/watch/migration_test.go
  staging/src/kubevirt.io/api/migrations/v1alpha1/types.go
  staging/src/kubevirt.io/api/migrations/v1alpha1/types_swagger_generated.go
Labels: size/M, release-note, lgtm, approved, dco-signoff: yes

#7267 Always show applied migration configuration in VMI status
  pkg/virt-controller/watch/migration.go
  pkg/virt-controller/watch/migration_test.go
  pkg/virt-handler/vm.go
  tests/migration_test.go
Labels: size/M, release-note, lgtm, approved, dco-signoff: yes

#7410 [tests] Ensure that virt-handler watcher can reach the apiserver after outage
  tests/utils.go
  tests/virt_control_plane_test.go
Labels: size/M, release-note-none, lgtm, approved, dco-signoff: yes

#6854 [virtctl] Bump crypto ssh to make the preauth authentiation for some newer ssh server configurations work
  go.mod
  go.sum
  staging/src/kubevirt.io/client-go/go.mod
  staging/src/kubevirt.io/client-go/go.sum
  vendor/golang.org/x/crypto/ed25519/BUILD.bazel
  vendor/golang.org/x/crypto/ed25519/ed25519.go
  vendor/golang.org/x/crypto/ed25519/ed25519_go113.go
  vendor/golang.org/x/crypto/ed25519/internal/edwards25519/BUILD.bazel
  vendor/golang.org/x/crypto/ed25519/internal/edwards25519/const.go
  vendor/golang.org/x/crypto/ed25519/internal/edwards25519/edwards25519.go
  vendor/golang.org/x/crypto/ssh/agent/client.go
  vendor/golang.org/x/crypto/ssh/agent/keyring.go
  vendor/golang.org/x/crypto/ssh/certs.go
  vendor/golang.org/x/crypto/ssh/client.go
  vendor/golang.org/x/crypto/ssh/client_auth.go
  vendor/golang.org/x/crypto/ssh/common.go
  vendor/golang.org/x/crypto/ssh/handshake.go
  vendor/golang.org/x/crypto/ssh/kex.go
  vendor/golang.org/x/crypto/ssh/keys.go
  vendor/golang.org/x/crypto/ssh/messages.go
  vendor/golang.org/x/crypto/ssh/server.go
  vendor/golang.org/x/crypto/ssh/session.go
  vendor/golang.org/x/crypto/ssh/transport.go
  vendor/golang.org/x/term/codereview.cfg
  vendor/golang.org/x/term/term.go
  vendor/modules.txt
Labels: release-note, size/XXL, lgtm, approved, dco-signoff: yes

#7408 tests: Avoid Expect(len())
  tests/migration_test.go
  tests/operator_test.go
  tests/performance/realtime.go
  tests/pool_test.go
  tests/realtime/realtime.go
  tests/replicaset_test.go
  tests/security_features_test.go
  tests/usbredir_test.go
  tests/vm_test.go
  tests/vmi_configuration_test.go
  tests/vmi_gpu_test.go
  tests/vmi_iothreads_test.go
  tests/vmi_sound_test.go
  tests/vmipreset_test.go
Labels: size/M, release-note-none, lgtm, approved, dco-signoff: yes

#7412 [Code Cleaning]: Change HaveLen(0) to BeEmpty()
  pkg/flavor/flavor_test.go
  pkg/virt-controller/watch/replicaset_test.go
  pkg/virt-controller/watch/vmi_test.go
  tests/migration_test.go
  tests/network/vmi_multus.go
  tests/operator_test.go
  tests/storage/restore.go
  tests/vmi_configuration_test.go
  tests/vmi_lifecycle_test.go
Labels: size/M, sig/network, release-note-none, lgtm, approved, dco-signoff: yes

#7421 Properly manage knownhosts files
  pkg/virtctl/ssh/BUILD.bazel
  pkg/virtctl/ssh/knownhosts.go
  pkg/virtctl/ssh/knownhosts_test.go
  pkg/virtctl/ssh/ssh.go
Labels: size/M, release-note, lgtm, approved, dco-signoff: yes

#7436 [release-0.49]Update poddisruptionbudget api from v1beta1 to v1
  pkg/controller/BUILD.bazel
  pkg/controller/virtinformers.go
  pkg/testutils/BUILD.bazel
  pkg/testutils/mock_queue.go
  pkg/util/pdbs/BUILD.bazel
  pkg/util/pdbs/pdbs.go
  pkg/virt-controller/watch/BUILD.bazel
  pkg/virt-controller/watch/application.go
  pkg/virt-controller/watch/application_test.go
  pkg/virt-controller/watch/drain/disruptionbudget/BUILD.bazel
  pkg/virt-controller/watch/drain/disruptionbudget/disruptionbudget.go
  pkg/virt-controller/watch/drain/disruptionbudget/disruptionbudget_test.go
  pkg/virt-controller/watch/drain/evacuation/evacuation_test.go
  pkg/virt-controller/watch/migration.go
  pkg/virt-controller/watch/migration_test.go
  pkg/virt-controller/watch/workload-updater/workload-updater_test.go
  pkg/virt-operator/BUILD.bazel
  pkg/virt-operator/kubevirt_test.go
  pkg/virt-operator/resource/apply/BUILD.bazel
  pkg/virt-operator/resource/apply/apps.go
  pkg/virt-operator/resource/apply/apps_test.go
  pkg/virt-operator/resource/apply/delete.go
  pkg/virt-operator/resource/apply/generations.go
  pkg/virt-operator/resource/apply/pdb_test.go
  pkg/virt-operator/resource/generate/components/BUILD.bazel
  pkg/virt-operator/resource/generate/components/deployments.go
  tests/BUILD.bazel
  tests/migration_test.go
  tests/operator_test.go
  tests/virt_control_plane_test.go
Labels: size/L, release-note-none, lgtm, approved, dco-signoff: yes

#7422 virt-launcher, hostdevice: Respect SR-IOV guest pciAddress and bootOrder
  pkg/virt-launcher/virtwrap/device/hostdevice/sriov/BUILD.bazel
  pkg/virt-launcher/virtwrap/device/hostdevice/sriov/hostdev.go
  pkg/virt-launcher/virtwrap/device/hostdevice/sriov/hostdev_test.go
Labels: size/L, release-note, lgtm, approved, dco-signoff: yes

#7424 api, network: provide interface binding types descriptions
  api/openapi-spec/swagger.json
  pkg/virt-operator/resource/generate/components/validations_generated.go
  staging/src/kubevirt.io/api/core/v1/schema.go
  staging/src/kubevirt.io/api/core/v1/schema_swagger_generated.go
  staging/src/kubevirt.io/client-go/api/openapi_generated.go
Labels: size/L, release-note, lgtm, approved, dco-signoff: yes

#7450 Tests: Fix migration on non-root
  tests/migration_test.go
Labels: size/XS, release-note-none, lgtm, approved, dco-signoff: yes

#7427 Enable test 6978
  tests/migration_test.go
Labels: size/XS, release-note-none, lgtm, approved, dco-signoff: yes

#7447 Use HaveLen gomega matcher
  pkg/virt-handler/hotplug-disk/findmnt_test.go
  pkg/virt-handler/hotplug-disk/mount_test.go
  pkg/virt-handler/node-labeller/cpu_plugin_test.go
  pkg/virt-handler/vm_test.go
Labels: size/S, release-note-none, lgtm, approved, dco-signoff: yes

#7402 tests/utils: drop public constant TempDirPrefix
  tests/operator_test.go
  tests/storage/datavolume.go
  tests/template_test.go
  tests/utils.go
  tests/vm_test.go
  tests/windows_test.go
Labels: size/M, release-note-none, lgtm, approved, dco-signoff: yes

#7419 tests: replace To(Equal(...)) to To(HaveLen(...))
  pkg/util/hardware/hw_utils_test.go
  pkg/util/lookup/lookup_test.go
Labels: size/XS, release-note-none, lgtm, approved, ok-to-test, dco-signoff: yes

#7428 tests libvmi: factory cleanup
  tests/infra_test.go
  tests/launchsecurity/sev.go
  tests/libvmi/factory.go
  tests/migration_test.go
  tests/network/primary_pod_network.go
  tests/network/vmi_multus.go
  tests/network/vmi_networking.go
  tests/softreboot_test.go
  tests/utils.go
  tests/vmi_configuration_test.go
Labels: size/M, sig/network, release-note-none, lgtm, approved, dco-signoff: yes

#7425 Update builder image to latest version
  hack/dockerized
Labels: size/XS, release-note-none, lgtm, approved, dco-signoff: yes

#7418 tests: Various helpers cleanups
  tests/BUILD.bazel
  tests/network/vmi_istio.go
  tests/network/vmi_lifecycle.go
  tests/test.go
  tests/utils.go
Labels: size/M, sig/network, release-note-none, lgtm, approved, dco-signoff: yes

#7454 vmi_lifecycle_test: import kubevirt.io/kubevirt/tests/util only once
  tests/vmi_lifecycle_test.go
Labels: size/XS, release-note-none, lgtm, approved, dco-signoff: yes

#7420 tests: use HaveLen(...) and BeEmpty()
  pkg/monitoring/domainstats/collector_test.go
  pkg/monitoring/domainstats/downwardmetrics/hostmetrics_test.go
  pkg/monitoring/vmistats/collector_test.go
Labels: size/S, release-note-none, lgtm, approved, ok-to-test, dco-signoff: yes, area/monitoring

#7426 Add warning for manually determining core kubevirt infra component replica count
  api/openapi-spec/swagger.json
  manifests/generated/kv-resource.yaml
  pkg/virt-operator/resource/apply/apps.go
  pkg/virt-operator/resource/generate/components/validations_generated.go
  staging/src/kubevirt.io/api/core/v1/componentconfig.go
  staging/src/kubevirt.io/client-go/api/openapi_generated.go
Labels: size/M, release-note, lgtm, approved, dco-signoff: yes

#7455 Attempt to fix error disk flakes by looping over path
  tests/io_utils.go
Labels: size/M, release-note-none, lgtm, approved, dco-signoff: yes

#7443 [release 0.50] Bump kubevirtci and align test.sh file
  automation/test.sh
  cluster-up-sha.txt
  cluster-up/cluster/k8s-1.20/provider.sh
  cluster-up/cluster/kind-1.23-vgpu/README.md
  cluster-up/cluster/kind-1.23-vgpu/config_vgpu_cluster.sh
  cluster-up/cluster/kind-1.23-vgpu/provider.sh
  cluster-up/cluster/kind-1.23-vgpu/vgpu-node/node.sh
  cluster-up/hack/common.sh
  cluster-up/version.txt
  hack/config-default.sh
  tests/network/BUILD.bazel
  tests/network/port_forward.go
Labels: size/L, sig/network, release-note-none, lgtm, approved, dco-signoff: yes

#7372 Fix `KubeVirtComponentExceedsRequestedMemory` alert on duplicate series
  hack/prom-rule-ci/prom-rules-tests.yaml
  pkg/virt-operator/resource/generate/components/prometheus.go
Labels: release-note, size/XS, lgtm, approved, ok-to-test, dco-signoff: yes, area/monitoring
