Repository kubevirt/kubevirt, pull requests merged in 2022-04, with the labels that each got.

#7423 docs, Fix typo in quarantine.md
  docs/quarantine.md
Labels: size/XS, release-note-none, lgtm, approved, dco-signoff: yes

#7429 virt-launcher: import kubevirt.io/kubevirt/pkg/util only once
  pkg/virt-launcher/virtwrap/manager.go
Labels: size/XS, release-note-none, lgtm, approved, dco-signoff: yes

#7456 Code Cleanup: Improve gomega matchers in several packages
  pkg/virt-operator/kubevirt_test.go
  pkg/virt-operator/resource/apply/apps_test.go
  pkg/virt-operator/resource/apply/core_test.go
  pkg/virt-operator/resource/apply/delete_test.go
  pkg/virt-operator/resource/apply/patches_test.go
  pkg/virt-operator/resource/apply/prometheus_test.go
  pkg/virt-operator/resource/apply/reconcile_test.go
  pkg/virt-operator/util/client_test.go
  pkg/watchdog/watchdog_test.go
  staging/src/kubevirt.io/client-go/api/defaults_test.go
  staging/src/kubevirt.io/client-go/api/types_test.go
Labels: size/L, release-note-none, lgtm, approved, dco-signoff: yes, area/monitoring

#7415 workload-updater, test: remove `time.Sleep(1)`
  pkg/virt-controller/watch/workload-updater/workload-updater_test.go
Labels: size/M, release-note-none, lgtm, approved, dco-signoff: yes

#7486 Fix stable.txt location
  automation/release.sh
Labels: release-note, size/XS, lgtm, approved, dco-signoff: yes

#7024 [virtctl] Warning message for client and server versions not aligned
  cmd/virt-chroot/main.go
  pkg/virtctl/BUILD.bazel
  pkg/virtctl/root.go
  pkg/virtctl/version/BUILD.bazel
  pkg/virtctl/version/version.go
  pkg/virtctl/version/version_suite_test.go
  pkg/virtctl/version/version_test.go
  staging/src/kubevirt.io/client-go/kubecli/generated_mock_kubevirt.go
  staging/src/kubevirt.io/client-go/kubecli/kubevirt.go
  staging/src/kubevirt.io/client-go/kubecli/version.go
  tests/utils.go
Labels: size/L, release-note, lgtm, approved, ok-to-test, dco-signoff: yes

#6958 tests: Use fedora-with-test-tooling based on Fedora 35
  BUILD.bazel
  WORKSPACE
  containerimages/BUILD.bazel
  examples/vmi-secureboot.yaml
  tests/console/login.go
  tests/containerdisk/containerdisk.go
  tests/migration_test.go
  tests/storage/datavolume.go
  tests/utils.go
  tests/vmi_configuration_test.go
  tools/vms-generator/utils/utils.go
Labels: size/M, release-note-none, lgtm, approved, dco-signoff: yes

#7502 virtctl/ssh: Fix missing check when parsing a private key
  pkg/virtctl/ssh/native.go
Labels: size/XS, release-note-none, lgtm, approved, dco-signoff: yes

#7451 [virt-launcher] Reduce memory consumption
  cmd/virt-launcher-monitor/BUILD.bazel
  cmd/virt-launcher-monitor/virt-launcher-monitor.go
  cmd/virt-launcher/BUILD.bazel
  cmd/virt-launcher/virt-launcher.go
  pkg/virt-controller/services/template.go
  pkg/virt-controller/services/template_test.go
Labels: size/XL, lgtm, approved, kind/build-change, dco-signoff: yes

#7505 Removing myself from automated review assignment
  OWNERS_ALIASES
Labels: size/XS, release-note-none, lgtm, approved, dco-signoff: yes

#7461 Code Cleanup: Improve gomega matchers in pkg/virt-api/webhooks
  pkg/virt-api/webhooks/mutating-webhook/mutators/preset_test.go
  pkg/virt-api/webhooks/validating-webhook/admitters/migration-create-admitter_test.go
Labels: size/M, release-note-none, lgtm, approved, dco-signoff: yes

#7469 Add NonRoot feature gate
  pkg/virt-config/feature-gates.go
Labels: release-note, size/XS, lgtm, approved, dco-signoff: yes

#7328 append identity file with local-ssh
  pkg/virtctl/ssh/wrapped.go
Labels: release-note, size/XS, lgtm, approved, ok-to-test, dco-signoff: yes

#6180 Fix links in monitoring-guidelines
  docs/monitoring-guidelines.md
Labels: size/XS, release-note-none, lgtm, approved, dco-signoff: yes

#7500 Set RBAC for VM/addvolume and VM/removevolume
  manifests/generated/operator-csv.yaml.in
  manifests/generated/rbac-operator.authorization.k8s.yaml.in
  pkg/virt-operator/resource/generate/rbac/cluster.go
Labels: size/S, release-note, lgtm, approved, dco-signoff: yes

#7359 tests: extend virt-handler canary upgrade test timeout
  tests/canary_upgrade_test.go
Labels: size/S, release-note-none, lgtm, approved, dco-signoff: yes

#7446 tests: Move service-account helpers to a separate file
  tests/BUILD.bazel
  tests/serviceaccount.go
  tests/utils.go
Labels: size/L, sig/network, release-note-none, lgtm, approved, dco-signoff: yes

#7171 Addition of functional tests exercising migration of VM using swap memory
  tests/BUILD.bazel
  tests/operator_test.go
  tests/swap_test.go
  tests/utils.go
Labels: size/L, sig/network, release-note-none, lgtm, approved, dco-signoff: yes

#7439 tests: Move code from `utils` to `clientcmd`
  pkg/virtctl/expose/BUILD.bazel
  pkg/virtctl/expose/expose_test.go
  pkg/virtctl/guestfs/BUILD.bazel
  pkg/virtctl/guestfs/guestfs_test.go
  pkg/virtctl/imageupload/BUILD.bazel
  pkg/virtctl/imageupload/imageupload_test.go
  pkg/virtctl/pause/BUILD.bazel
  pkg/virtctl/pause/pause_test.go
  pkg/virtctl/softreboot/BUILD.bazel
  pkg/virtctl/softreboot/softreboot_test.go
  pkg/virtctl/vm/BUILD.bazel
  pkg/virtctl/vm/vm_test.go
  tests/BUILD.bazel
  tests/access_test.go
  tests/clientcmd/BUILD.bazel
  tests/clientcmd/command.go
  tests/clientcmd/virtctl.go
  tests/kubectl_test.go
  tests/migration_test.go
  tests/monitoring/BUILD.bazel
  tests/monitoring/prometheus_utils.go
  tests/network/BUILD.bazel
  tests/network/expose.go
  tests/network/port_forward.go
  tests/operator_test.go
  tests/pausing_test.go
  tests/replicaset_test.go
  tests/reporter/BUILD.bazel
  tests/reporter/kubernetes.go
  tests/softreboot_test.go
  tests/storage/BUILD.bazel
  tests/storage/datavolume.go
  tests/storage/guestfs.go
  tests/storage/hotplug.go
  tests/storage/imageupload.go
  tests/template_test.go
  tests/utils.go
  tests/vm_test.go
  tests/vmi_hook_sidecar_test.go
  tests/vmi_lifecycle_test.go
  tests/vnc_test.go
  tests/windows_test.go
Labels: sig/network, size/XXL, release-note-none, lgtm, approved, dco-signoff: yes

#7399 container-disk, test: replace `Expect(len(..).To(Equal(..))` with `Expect(..).To(HaveLen(..))`
  pkg/container-disk/container-disk_test.go
Labels: size/XS, release-note-none, lgtm, approved, dco-signoff: yes

#7507 Remove redundant parameter from pod template capabilities
  pkg/virt-controller/services/template.go
Labels: sig/network, size/XS, release-note-none, lgtm, approved, dco-signoff: yes

#7401 Scale virt-api deployment replicas according to number of nodes
  pkg/virt-operator/kubevirt_test.go
  pkg/virt-operator/resource/apply/BUILD.bazel
  pkg/virt-operator/resource/apply/apps.go
  tests/BUILD.bazel
  tests/scale/BUILD.bazel
  tests/scale/virt-api.go
  tests/tests_suite_test.go
Labels: size/L, release-note, lgtm, approved, dco-signoff: yes

#7496 tests, network: Split the multus test file
  tests/libnet/ipaddress.go
  tests/network/BUILD.bazel
  tests/network/macvtap.go
  tests/network/sriov.go
  tests/network/vmi_multus.go
Labels: sig/network, size/XXL, release-note-none, lgtm, approved, dco-signoff: yes

#7130 Add field to kubevirtCR to set Prometheus ServiceMonitor object's namespace
  api/openapi-spec/swagger.json
  manifests/generated/kv-resource.yaml
  pkg/virt-operator/kubevirt_test.go
  pkg/virt-operator/resource/apply/reconcile.go
  pkg/virt-operator/resource/generate/components/validations_generated.go
  pkg/virt-operator/resource/generate/install/strategy.go
  pkg/virt-operator/util/config.go
  pkg/virt-operator/util/config_test.go
  staging/src/kubevirt.io/api/core/v1/types.go
  staging/src/kubevirt.io/api/core/v1/types_swagger_generated.go
  staging/src/kubevirt.io/client-go/api/openapi_generated.go
Labels: size/L, release-note, lgtm, approved, dco-signoff: yes, area/monitoring

#7509 ephemeral-disk_test: shorten with GinkgoT.TempDir()
  pkg/ephemeral-disk/ephemeral-disk_test.go
Labels: size/S, release-note-none, lgtm, approved, dco-signoff: yes

#7103 Add TPM 2.0 emulated device option to VMIs
  WORKSPACE
  api/openapi-spec/swagger.json
  cmd/virt-launcher/BUILD.bazel
  cmd/virt-launcher/virt-launcher.go
  examples/vm-template-windows2012r2.yaml
  examples/vmi-windows.yaml
  pkg/virt-api/webhooks/validating-webhook/admitters/vmi-create-admitter.go
  pkg/virt-controller/services/template.go
  pkg/virt-launcher/virtwrap/api/deepcopy_generated.go
  pkg/virt-launcher/virtwrap/api/schema.go
  pkg/virt-launcher/virtwrap/converter/converter.go
  pkg/virt-launcher/virtwrap/util/libvirt_helper.go
  pkg/virt-operator/resource/generate/components/scc.go
  pkg/virt-operator/resource/generate/components/validations_generated.go
  staging/src/kubevirt.io/api/core/v1/deepcopy_generated.go
  staging/src/kubevirt.io/api/core/v1/schema.go
  staging/src/kubevirt.io/api/core/v1/schema_swagger_generated.go
  staging/src/kubevirt.io/client-go/api/openapi_generated.go
  tests/BUILD.bazel
  tests/security_features_test.go
  tests/utils.go
  tests/vmi_tpm_test.go
  tools/vms-generator/utils/utils.go
Labels: size/L, release-note, lgtm, approved, kind/build-change, dco-signoff: yes

#7324 Adjust tests to be able to run on any supplied RWX Filesystem storage
  automation/test.sh
  tests/BUILD.bazel
  tests/default-ceph-config.json
  tests/migration_test.go
  tests/storage/datavolume.go
  tests/utils.go
Labels: size/L, release-note-none, lgtm, approved, dco-signoff: yes

#7396 Add Killercoda.com to Adopters
  ADOPTERS.md
Labels: size/XS, release-note-none, lgtm, approved, ok-to-test, dco-signoff: yes

#7519 Test flakiness - longer time wait
  tests/storage/datavolume.go
Labels: size/XS, release-note-none, lgtm, approved, dco-signoff: yes

#7262 code change: Improve code around flavors
  pkg/flavor/BUILD.bazel
  pkg/flavor/flavor.go
  pkg/flavor/flavor_test.go
  pkg/testutils/mock_flavor.go
  pkg/virt-api/webhooks/validating-webhook/admitters/vms-admitter.go
  pkg/virt-api/webhooks/validating-webhook/admitters/vms-admitter_test.go
  pkg/virt-controller/watch/BUILD.bazel
  pkg/virt-controller/watch/vm.go
  pkg/virt-controller/watch/vm_test.go
Labels: size/L, lgtm, approved, dco-signoff: yes

#7406 virt-operator, webhooks: add validation for WorkloadUpdateMethods
  pkg/virt-operator/webhooks/BUILD.bazel
  pkg/virt-operator/webhooks/kubevirt-update-admitter.go
  pkg/virt-operator/webhooks/kubevirt-update-admitter_test.go
Labels: size/L, release-note, lgtm, approved, dco-signoff: yes

#7476 [release-0.51] virt-launcher, hostdevice: Respect SR-IOV guest pciAddress and bootOrder
  pkg/virt-launcher/virtwrap/device/hostdevice/sriov/BUILD.bazel
  pkg/virt-launcher/virtwrap/device/hostdevice/sriov/hostdev.go
  pkg/virt-launcher/virtwrap/device/hostdevice/sriov/hostdev_test.go
  tests/network/vmi_multus.go
Labels: size/L, sig/network, release-note, lgtm, approved, dco-signoff: yes

#7477 [release-0.50] virt-launcher, hostdevice: Respect SR-IOV guest pciAddress and bootOrder
  pkg/virt-launcher/virtwrap/device/hostdevice/sriov/BUILD.bazel
  pkg/virt-launcher/virtwrap/device/hostdevice/sriov/hostdev.go
  pkg/virt-launcher/virtwrap/device/hostdevice/sriov/hostdev_test.go
  tests/network/vmi_multus.go
Labels: size/L, sig/network, release-note, lgtm, approved, dco-signoff: yes

#7478 [release-0.49] virt-launcher, hostdevice: Respect SR-IOV guest pciAddress and bootOrder
  pkg/virt-launcher/virtwrap/device/hostdevice/sriov/BUILD.bazel
  pkg/virt-launcher/virtwrap/device/hostdevice/sriov/hostdev.go
  pkg/virt-launcher/virtwrap/device/hostdevice/sriov/hostdev_test.go
  tests/network/vmi_multus.go
Labels: size/L, sig/network, release-note, lgtm, approved, dco-signoff: yes

#7440 tests: Extract node related helpers to a dedicated package
  tests/BUILD.bazel
  tests/infra_test.go
  tests/libnode/BUILD.bazel
  tests/libnode/node.go
  tests/mdev_configuration_allocation_test.go
  tests/migration_test.go
  tests/storage/BUILD.bazel
  tests/storage/hotplug.go
  tests/swap_test.go
  tests/utils.go
Labels: size/L, sig/network, release-note-none, lgtm, approved, dco-signoff: yes

#7497 Better matcher usage have len be empty
  tests/network/vmi_multus.go
Labels: size/S, sig/network, release-note-none, lgtm, approved, dco-signoff: yes

#7548 update prometheus/client-go to 1.11.1
  go.mod
  go.sum
  vendor/github.com/prometheus/client_golang/prometheus/promhttp/BUILD.bazel
  vendor/github.com/prometheus/client_golang/prometheus/promhttp/instrument_client.go
  vendor/github.com/prometheus/client_golang/prometheus/promhttp/instrument_server.go
  vendor/github.com/prometheus/client_golang/prometheus/promhttp/option.go
  vendor/modules.txt
Labels: size/L, release-note-none, lgtm, approved, dco-signoff: yes

#7535 Nominate xpivarc as an approver
  OWNERS_ALIASES
Labels: size/XS, release-note-none, lgtm, approved, dco-signoff: yes

#7435 Replace Cirros with Alpine
  tests/config_test.go
  tests/console/BUILD.bazel
  tests/console/login.go
  tests/libnet/BUILD.bazel
  tests/libnet/alpine.go
  tests/libnet/ipv6.go
  tests/migration_test.go
  tests/network/expose.go
  tests/network/macvtap.go
  tests/network/networkpolicy.go
  tests/network/port_forward.go
  tests/network/probes.go
  tests/network/services.go
  tests/network/vmi_istio.go
  tests/network/vmi_multus.go
  tests/network/vmi_networking.go
  tests/network/vmi_slirp_interface.go
  tests/operator_test.go
  tests/pausing_test.go
  tests/storage/restore.go
  tests/storage/snapshot.go
  tests/storage/storage.go
  tests/utils.go
  tests/vm_test.go
  tests/vmi_cloudinit_hook_sidecar_test.go
  tests/vmi_cloudinit_test.go
  tests/vmi_configuration_test.go
  tests/vmi_lifecycle_test.go
  tests/vmi_multiqueue_test.go
  tests/vmi_servers.go
  tests/vmi_sound_test.go
Labels: sig/network, size/XL, release-note-none, lgtm, approved, dco-signoff: yes

#7555 Nominate vasiliy-ul as reviewer
  OWNERS_ALIASES
Labels: size/XS, release-note-none, lgtm, approved, dco-signoff: yes

#7561 [e2e]: quarantine a few flaky mdev tests
  tests/mdev_configuration_allocation_test.go
Labels: size/XS, release-note-none, lgtm, approved, dco-signoff: yes

#7550 Remove IO error storage tests from quarantine
  tests/storage/storage.go
Labels: size/XS, release-note-none, lgtm, approved, dco-signoff: yes

#7458 tests: Introduce the `libstorage` sub-package, moving there storage helpers (from utils)
  tests/BUILD.bazel
  tests/libstorage/BUILD.bazel
  tests/libstorage/config.go
  tests/libstorage/datavolume.go
  tests/libstorage/storageclass.go
  tests/migration_test.go
  tests/operator_test.go
  tests/storage/BUILD.bazel
  tests/storage/datavolume.go
  tests/storage/hotplug.go
  tests/storage/imageupload.go
  tests/storage/snapshot.go
  tests/storage/storage.go
  tests/sysprep_test.go
  tests/template_test.go
  tests/utils.go
  tests/vm_test.go
  tests/vmi_configuration_test.go
  tests/windows_test.go
Labels: size/XL, release-note-none, lgtm, approved, dco-signoff: yes

#7563 Switch VolumeSnapshot from v1beta1 to v1
  go.mod
  go.sum
  hack/generate.sh
  pkg/controller/BUILD.bazel
  pkg/controller/virtinformers.go
  pkg/virt-controller/watch/BUILD.bazel
  pkg/virt-controller/watch/application.go
  pkg/virt-controller/watch/snapshot/BUILD.bazel
  pkg/virt-controller/watch/snapshot/restore.go
  pkg/virt-controller/watch/snapshot/snapshot.go
  pkg/virt-controller/watch/snapshot/snapshot_base.go
  pkg/virt-controller/watch/snapshot/snapshot_test.go
  staging/src/kubevirt.io/client-go/generated/external-snapshotter/clientset/versioned/BUILD.bazel
  staging/src/kubevirt.io/client-go/generated/external-snapshotter/clientset/versioned/clientset.go
  staging/src/kubevirt.io/client-go/generated/external-snapshotter/clientset/versioned/fake/BUILD.bazel
  staging/src/kubevirt.io/client-go/generated/external-snapshotter/clientset/versioned/fake/clientset_generated.go
  staging/src/kubevirt.io/client-go/generated/external-snapshotter/clientset/versioned/fake/register.go
  staging/src/kubevirt.io/client-go/generated/external-snapshotter/clientset/versioned/scheme/BUILD.bazel
  staging/src/kubevirt.io/client-go/generated/external-snapshotter/clientset/versioned/scheme/register.go
  staging/src/kubevirt.io/client-go/generated/external-snapshotter/clientset/versioned/typed/volumesnapshot/v1/BUILD.bazel
  staging/src/kubevirt.io/client-go/generated/external-snapshotter/clientset/versioned/typed/volumesnapshot/v1/doc.go
  staging/src/kubevirt.io/client-go/generated/external-snapshotter/clientset/versioned/typed/volumesnapshot/v1/fake/BUILD.bazel
  staging/src/kubevirt.io/client-go/generated/external-snapshotter/clientset/versioned/typed/volumesnapshot/v1/fake/doc.go
  staging/src/kubevirt.io/client-go/generated/external-snapshotter/clientset/versioned/typed/volumesnapshot/v1/fake/fake_volumesnapshot.go
  staging/src/kubevirt.io/client-go/generated/external-snapshotter/clientset/versioned/typed/volumesnapshot/v1/fake/fake_volumesnapshot_client.go
  staging/src/kubevirt.io/client-go/generated/external-snapshotter/clientset/versioned/typed/volumesnapshot/v1/fake/fake_volumesnapshotclass.go
  staging/src/kubevirt.io/client-go/generated/external-snapshotter/clientset/versioned/typed/volumesnapshot/v1/fake/fake_volumesnapshotcontent.go
  staging/src/kubevirt.io/client-go/generated/external-snapshotter/clientset/versioned/typed/volumesnapshot/v1/generated_expansion.go
  staging/src/kubevirt.io/client-go/generated/external-snapshotter/clientset/versioned/typed/volumesnapshot/v1/volumesnapshot.go
  staging/src/kubevirt.io/client-go/generated/external-snapshotter/clientset/versioned/typed/volumesnapshot/v1/volumesnapshot_client.go
  staging/src/kubevirt.io/client-go/generated/external-snapshotter/clientset/versioned/typed/volumesnapshot/v1/volumesnapshotclass.go
  staging/src/kubevirt.io/client-go/generated/external-snapshotter/clientset/versioned/typed/volumesnapshot/v1/volumesnapshotcontent.go
  staging/src/kubevirt.io/client-go/go.mod
  staging/src/kubevirt.io/client-go/go.sum
  tests/storage/BUILD.bazel
  tests/storage/snapshot.go
  vendor/github.com/kubernetes-csi/external-snapshotter/client/v4/LICENSE
  vendor/github.com/kubernetes-csi/external-snapshotter/client/v4/apis/volumesnapshot/v1/BUILD.bazel
  vendor/github.com/kubernetes-csi/external-snapshotter/client/v4/apis/volumesnapshot/v1/doc.go
  vendor/github.com/kubernetes-csi/external-snapshotter/client/v4/apis/volumesnapshot/v1/register.go
  vendor/github.com/kubernetes-csi/external-snapshotter/client/v4/apis/volumesnapshot/v1/types.go
  vendor/github.com/kubernetes-csi/external-snapshotter/client/v4/apis/volumesnapshot/v1/zz_generated.deepcopy.go
  vendor/modules.txt
Labels: size/XL, release-note, lgtm, approved, dco-signoff: yes

#7493 EvictionStrategy: "External"
  pkg/virt-api/webhooks/validating-webhook/admitters/pod-eviction-admitter.go
  pkg/virt-api/webhooks/validating-webhook/admitters/pod-eviction-admitter_test.go
  pkg/virt-api/webhooks/validating-webhook/admitters/vmi-create-admitter.go
  pkg/virt-api/webhooks/validating-webhook/admitters/vmi-create-admitter_test.go
  pkg/virt-controller/watch/drain/disruptionbudget/disruptionbudget.go
  pkg/virt-controller/watch/drain/disruptionbudget/disruptionbudget_test.go
  staging/src/kubevirt.io/api/core/v1/types.go
  tests/vmi_lifecycle_test.go
Labels: size/L, release-note, lgtm, approved, dco-signoff: yes

#7556 Updating OKD link in adopters file, previously linked to minikube site
  ADOPTERS.md
Labels: size/XS, release-note-none, lgtm, approved, needs-ok-to-test, dco-signoff: yes

#7566 e2e: fix CPU pinning test
  tests/vmi_configuration_test.go
Labels: size/XS, release-note-none, lgtm, approved, dco-signoff: yes

#7530 [External Kernel Boot]: Disallow kernel args without providing custom kernel
  pkg/virt-api/webhooks/validating-webhook/admitters/BUILD.bazel
  pkg/virt-api/webhooks/validating-webhook/admitters/vmi-create-admitter.go
  pkg/virt-api/webhooks/validating-webhook/admitters/vmi-create-admitter_test.go
Labels: size/M, release-note, lgtm, approved, dco-signoff: yes

#7536 Nominate iholder-redhat as reviewer
  OWNERS_ALIASES
Labels: size/XS, release-note-none, lgtm, approved, dco-signoff: yes

#7540 tests reporter: log KubeVirt daemonsets
  tests/reporter/kubernetes.go
Labels: size/S, release-note-none, lgtm, approved, dco-signoff: yes

#7565 Add test_id for low level hypervisor logs testing
  tests/vmi_lifecycle_test.go
Labels: size/XS, release-note-none, lgtm, approved, ok-to-test, dco-signoff: yes

#7546 Update virtio-win image to 0.1.217-1
  WORKSPACE
Labels: release-note, size/XS, lgtm, approved, dco-signoff: yes

#7531 AutoPort should be all lowercase for xml
  pkg/virt-launcher/virtwrap/api/schema.go
Labels: size/XS, release-note-none, lgtm, approved, needs-ok-to-test, dco-signoff: yes

#7414 Get rid of libmacouflage library
  go.mod
  go.sum
  pkg/network/driver/BUILD.bazel
  pkg/network/driver/common.go
  pkg/network/driver/generated_mock_common.go
  pkg/network/infraconfigurators/bridge.go
  pkg/network/infraconfigurators/bridge_test.go
  vendor/github.com/subgraph/libmacouflage/.gitignore
  vendor/github.com/subgraph/libmacouflage/BUILD.bazel
  vendor/github.com/subgraph/libmacouflage/README.md
  vendor/github.com/subgraph/libmacouflage/libmacouflage.go
  vendor/github.com/subgraph/libmacouflage/ouis_bindata.go
  vendor/modules.txt
Labels: sig/network, release-note, size/XXL, lgtm, approved, ok-to-test, dco-signoff: yes

#7586 Fix typo in permissions, was missing (s) in virtualmachines
  manifests/generated/operator-csv.yaml.in
  manifests/generated/rbac-operator.authorization.k8s.yaml.in
  pkg/virt-operator/resource/generate/rbac/cluster.go
Labels: size/S, release-note-none, lgtm, approved, dco-signoff: yes

#7553 flavors: Make ShortNames for flavors shorter
  pkg/virt-operator/resource/generate/components/crds.go
Labels: size/XS, release-note-none, lgtm, approved, dco-signoff: yes

#7270 VM mutating webhook fails on error
  pkg/virt-api/webhooks/mutating-webhook/mutators/vm-mutator.go
  pkg/virt-api/webhooks/mutating-webhook/mutators/vm-mutator_test.go
Labels: size/M, release-note-none, lgtm, approved, dco-signoff: yes

#7581 Pre-create directories for non-root TPM state
  cmd/virt-launcher/BUILD.bazel
Labels: size/XS, release-note-none, lgtm, approved, kind/build-change, dco-signoff: yes

#7582 virt-controller: fix false failed migrations
  pkg/virt-controller/watch/migration.go
  pkg/virt-controller/watch/migration_test.go
  tests/migration_test.go
Labels: size/M, release-note, lgtm, approved, dco-signoff: yes

#7544 Upgrade go to 1.17.8
  WORKSPACE
  hack/builder/Dockerfile
  hack/dockerized
Labels: release-note, size/XS, lgtm, approved, dco-signoff: yes

#7597 Introduce a DiskBus type and associated constants
  pkg/testutils/domain.go
  pkg/virt-api/webhooks/mutating-webhook/mutators/preset_test.go
  pkg/virt-api/webhooks/validating-webhook/admitters/vmi-create-admitter.go
  pkg/virt-api/webhooks/validating-webhook/admitters/vmi-create-admitter_test.go
  pkg/virt-controller/services/template_test.go
  pkg/virt-controller/watch/snapshot/snapshot_test.go
  pkg/virt-controller/watch/vmi_test.go
  pkg/virt-handler/vm_test.go
  pkg/virt-launcher/virtwrap/api/schema.go
  pkg/virt-launcher/virtwrap/converter/converter.go
  pkg/virt-launcher/virtwrap/converter/pci-placement.go
  pkg/virt-launcher/virtwrap/manager_test.go
  staging/src/kubevirt.io/api/core/v1/defaults.go
  staging/src/kubevirt.io/api/core/v1/schema.go
  tests/container_disk_test.go
  tests/libstorage/datavolume.go
  tests/libvmi/cloudinit.go
  tests/libvmi/storage.go
  tests/migration_test.go
  tests/network/vmi_slirp_interface.go
  tests/storage/datavolume.go
  tests/storage/hotplug.go
  tests/storage/restore.go
  tests/storage/snapshot.go
  tests/storage/storage.go
  tests/sysprep_test.go
  tests/utils.go
  tests/vmi_configuration_test.go
  tests/vmi_iothreads_test.go
  tests/vmi_lifecycle_test.go
  tests/vmi_multiqueue_test.go
  tests/windows_test.go
  tools/vms-generator/utils/utils.go
Labels: size/L, sig/network, release-note-none, lgtm, approved, dco-signoff: yes

#7265 Refactor the Load Generator and Support SteadyState Types
  hack/perfscale-tests.sh
  tools/perfscale-load-generator/BUILD.bazel
  tools/perfscale-load-generator/README.md
  tools/perfscale-load-generator/api/BUILD.bazel
  tools/perfscale-load-generator/api/api.go
  tools/perfscale-load-generator/burst/BUILD.bazel
  tools/perfscale-load-generator/burst/burst.go
  tools/perfscale-load-generator/config/BUILD.bazel
  tools/perfscale-load-generator/config/config.go
  tools/perfscale-load-generator/config/types.go
  tools/perfscale-load-generator/examples/burst-test.yaml
  tools/perfscale-load-generator/examples/steady-state-test.yaml
  tools/perfscale-load-generator/examples/vmi-ephemeral.yaml
  tools/perfscale-load-generator/examples/workload/kubevirt-density/kubevirt-burst-100.yaml
  tools/perfscale-load-generator/examples/workload/kubevirt-density/kubevirt-burst-200.yaml
  tools/perfscale-load-generator/examples/workload/kubevirt-density/kubevirt-burst-400.yaml
  tools/perfscale-load-generator/examples/workload/kubevirt-density/kubevirt-burst-600.yaml
  tools/perfscale-load-generator/examples/workload/kubevirt-density/kubevirt-density-scale.yaml
  tools/perfscale-load-generator/examples/workload/kubevirt-density/kubevirt-density-warmup.yaml
  tools/perfscale-load-generator/examples/workload/kubevirt-density/kubevirt-density.yaml
  tools/perfscale-load-generator/examples/workload/kubevirt-density/kubevirt-primer.yaml
  tools/perfscale-load-generator/examples/workload/kubevirt-density/kubevirt-steady-state-100.yaml
  tools/perfscale-load-generator/executor/executor.go
  tools/perfscale-load-generator/flags/flags.go
  tools/perfscale-load-generator/load-generator.go
  tools/perfscale-load-generator/object/BUILD.bazel
  tools/perfscale-load-generator/object/template.go
  tools/perfscale-load-generator/object/unstructured.go
  tools/perfscale-load-generator/steady-state/BUILD.bazel
  tools/perfscale-load-generator/steady-state/steady-state.go
  tools/perfscale-load-generator/utils/BUILD.bazel
  tools/perfscale-load-generator/utils/utils.go
  tools/perfscale-load-generator/watcher/watcher.go
Labels: sig/network, release-note, size/XXL, lgtm, approved, dco-signoff: yes

#7503 Simplify e2e probes tests remove boolean input parameters
  tests/network/probes.go
Labels: size/L, sig/network, release-note-none, lgtm, approved, dco-signoff: yes, sig/code-quality

#7610 [release-0.49] virt-controller: fix false failed migrations
  pkg/virt-controller/watch/migration.go
  pkg/virt-controller/watch/migration_test.go
  tests/migration_test.go
Labels: size/M, release-note, lgtm, approved, dco-signoff: yes

#7612 [release-0.51] virt-controller: fix false failed migrations
  pkg/virt-controller/watch/migration.go
  pkg/virt-controller/watch/migration_test.go
  tests/migration_test.go
Labels: size/M, release-note, lgtm, approved, dco-signoff: yes

#7264 virt-launcher: adjust overhead calculation for processes
  pkg/virt-controller/services/template.go
  pkg/virt-controller/services/template_test.go
  tests/vmi_configuration_test.go
Labels: size/L, lgtm, approved, dco-signoff: yes

#7611 [release-0.50] virt-controller: fix false failed migrations
  pkg/virt-controller/watch/migration.go
  pkg/virt-controller/watch/migration_test.go
  tests/migration_test.go
Labels: size/M, release-note, lgtm, approved, dco-signoff: yes

#7596 Fix verify-nonroot test
  hack/manifests.sh
  tests/nonroot_test.go
  tools/manifest-templator/manifest-templator.go
Labels: size/M, release-note-none, lgtm, approved, dco-signoff: yes

#7615 Code cleanup: avoid Expect(len(X))...
  pkg/host-disk/host-disk_test.go
  pkg/virt-api/webhooks/validating-webhook/admitters/vmi-create-admitter_test.go
  pkg/virt-launcher/notify-client/notify_test.go
Labels: size/S, release-note-none, lgtm, approved, dco-signoff: yes

#7441 [virtctl] Add a scp subcommand to virtctl
  go.mod
  go.sum
  pkg/virtctl/BUILD.bazel
  pkg/virtctl/root.go
  pkg/virtctl/scp/BUILD.bazel
  pkg/virtctl/scp/scp.go
  pkg/virtctl/ssh/BUILD.bazel
  pkg/virtctl/ssh/native.go
  pkg/virtctl/ssh/ssh.go
  pkg/virtctl/templates/target.go
  pkg/virtctl/templates/target_test.go
  tests/BUILD.bazel
  tests/tests_suite_test.go
  tests/virtctl/BUILD.bazel
  tests/virtctl/key.go
  tests/virtctl/scp.go
  vendor/github.com/povsister/scp/.gitignore
  vendor/github.com/povsister/scp/BUILD.bazel
  vendor/github.com/povsister/scp/LICENSE
  vendor/github.com/povsister/scp/README.md
  vendor/github.com/povsister/scp/client.go
  vendor/github.com/povsister/scp/config.go
  vendor/github.com/povsister/scp/doc.go
  vendor/github.com/povsister/scp/protocol.go
  vendor/github.com/povsister/scp/transfer.go
  vendor/modules.txt
Labels: release-note, size/XXL, lgtm, approved, dco-signoff: yes

#7583 tests: Continue moving helpers that are node related to libnode.
  tests/framework/checks/BUILD.bazel
  tests/framework/checks/skips.go
  tests/infra_test.go
  tests/libnode/node.go
  tests/mdev_configuration_allocation_test.go
  tests/migration_test.go
  tests/network/BUILD.bazel
  tests/network/macvtap.go
  tests/network/sriov.go
  tests/network/vmi_multus.go
  tests/storage/hotplug.go
  tests/swap_test.go
  tests/util/BUILD.bazel
  tests/util/util.go
  tests/utils.go
  tests/virt_control_plane_test.go
  tests/vm_test.go
  tests/vmi_configuration_test.go
  tests/vmi_iothreads_test.go
  tests/vmi_lifecycle_test.go
  tests/vmi_multiqueue_test.go
Labels: size/L, sig/network, release-note-none, lgtm, approved, dco-signoff: yes, sig/code-quality

#7474 [Prometheus]: Add metrics to help monitor live migration
  docs/metrics.md
  pkg/monitoring/domainstats/prometheus/prometheus.go
  pkg/monitoring/domainstats/prometheus/prometheus_test.go
  pkg/virt-launcher/virtwrap/BUILD.bazel
  pkg/virt-launcher/virtwrap/cli/generated_mock_libvirt.go
  pkg/virt-launcher/virtwrap/cli/libvirt.go
  pkg/virt-launcher/virtwrap/live-migration-source.go
  pkg/virt-launcher/virtwrap/manager.go
  pkg/virt-launcher/virtwrap/manager_test.go
  pkg/virt-launcher/virtwrap/stats/types.go
  pkg/virt-launcher/virtwrap/statsconv/converter.go
  pkg/virt-launcher/virtwrap/statsconv/converter_test.go
  pkg/virt-launcher/virtwrap/statsconv/util/domstats_utils.go
  tests/infra_test.go
  tests/migration_test.go
  tests/utils.go
  tools/doc-generator/doc-generator.go
  tools/doc-generator/fakeCollector.go
Labels: size/L, release-note, lgtm, approved, dco-signoff: yes, area/monitoring

#7629 Always require capabilites which we set on binary
  pkg/virt-controller/services/template.go
  pkg/virt-controller/services/template_test.go
Labels: size/M, release-note-none, lgtm, approved, dco-signoff: yes

#7622 [Code cleaning]: Replace "raw" pointers by using "pointer" library
  pkg/virt-api/rest/BUILD.bazel
  pkg/virt-api/rest/subresource_test.go
  pkg/virt-api/webhooks/mutating-webhook/mutators/BUILD.bazel
  pkg/virt-api/webhooks/mutating-webhook/mutators/vmi-mutator_test.go
  pkg/virt-api/webhooks/validating-webhook/admitters/vmi-create-admitter_test.go
  pkg/virt-operator/resource/generate/csv/BUILD.bazel
  pkg/virt-operator/resource/generate/csv/csv.go
  pkg/virtctl/vm/BUILD.bazel
  pkg/virtctl/vm/vm_test.go
Labels: size/L, release-note-none, lgtm, approved, dco-signoff: yes, sig/code-quality

#7623 [Code cleaning]: Delete empty scheduling doc
  docs/devel/scheduling.md
Labels: size/XS, release-note-none, lgtm, approved, dco-signoff: yes, sig/code-quality

#7431 docs, network: update the required capabilities for networking
  docs/devel/networking.md
Labels: size/XS, release-note-none, lgtm, approved, dco-signoff: yes

#7569 Add metrics types to kubevirt metrics description
  docs/metrics.md
  tools/doc-generator/doc-generator.go
Labels: size/L, release-note-none, lgtm, approved, ok-to-test, dco-signoff: yes

#7318 [VM Restore]: Support restoring to a target VM different than the source
  api/openapi-spec/swagger.json
  pkg/virt-api/webhooks/validating-webhook/admitters/vmrestore-admitter.go
  pkg/virt-api/webhooks/validating-webhook/admitters/vmrestore-admitter_test.go
  pkg/virt-controller/watch/snapshot/BUILD.bazel
  pkg/virt-controller/watch/snapshot/restore.go
  pkg/virt-controller/watch/snapshot/restore_test.go
  pkg/virt-controller/watch/snapshot/snapshot_test.go
  pkg/virt-operator/resource/generate/components/validations_generated.go
  staging/src/kubevirt.io/api/snapshot/v1alpha1/deepcopy_generated.go
  staging/src/kubevirt.io/api/snapshot/v1alpha1/types.go
  staging/src/kubevirt.io/api/snapshot/v1alpha1/types_swagger_generated.go
  staging/src/kubevirt.io/client-go/api/openapi_generated.go
  tests/flavor_test.go
  tests/storage/restore.go
  tests/utils.go
Labels: release-note, size/XXL, lgtm, approved, dco-signoff: yes

#7572 Fix 'make generate' to not keep unused client autogenerated files
  hack/dockerized
  staging/src/kubevirt.io/client-go/generated/containerized-data-importer/clientset/versioned/typed/core/v1alpha1/BUILD.bazel
  staging/src/kubevirt.io/client-go/generated/containerized-data-importer/clientset/versioned/typed/core/v1alpha1/fake/BUILD.bazel
  staging/src/kubevirt.io/client-go/generated/containerized-data-importer/clientset/versioned/typed/upload/v1alpha1/BUILD.bazel
  staging/src/kubevirt.io/client-go/generated/containerized-data-importer/clientset/versioned/typed/upload/v1alpha1/fake/BUILD.bazel
Labels: size/XS, release-note-none, lgtm, approved, dco-signoff: yes

#7625 tests: Introduce the testsuite sub-package
  tests/BUILD.bazel
  tests/access_test.go
  tests/credentials_test.go
  tests/libstorage/datavolume.go
  tests/migration_test.go
  tests/network/BUILD.bazel
  tests/network/networkpolicy.go
  tests/network/sriov.go
  tests/network/vmi_multus.go
  tests/operator_test.go
  tests/reporter/BUILD.bazel
  tests/reporter/kubernetes.go
  tests/storage/BUILD.bazel
  tests/storage/datavolume.go
  tests/storage/storage.go
  tests/subresource_api_test.go
  tests/tests_suite_test.go
  tests/testsuite/BUILD.bazel
  tests/testsuite/fixture.go
  tests/testsuite/kubevirtresource.go
  tests/testsuite/label.go
  tests/testsuite/manifest.go
  tests/testsuite/namespace.go
  tests/testsuite/serviceaccount.go
  tests/utils.go
  tests/virt_control_plane_test.go
  tests/vmi_cloudinit_test.go
  tests/vmi_configuration_test.go
  tests/vmi_lifecycle_test.go
Labels: sig/network, size/XXL, release-note-none, lgtm, approved, dco-signoff: yes, sig/code-quality

#7538 Propagate 'ephemeralDiskDir' from flag
  cmd/virt-launcher/virt-launcher.go
  pkg/virt-launcher/virtwrap/live-migration-source.go
  pkg/virt-launcher/virtwrap/manager.go
  pkg/virt-launcher/virtwrap/manager_test.go
Labels: size/L, release-note-none, lgtm, approved, ok-to-test, dco-signoff: yes

#7601 Run chcon on local storage path in disks-images-provider
  images/disks-images-provider/entrypoint.sh
Labels: size/XS, release-note-none, lgtm, approved, dco-signoff: yes

#7616 vmi-create-admitter: Remove duplicate disk and volume length checks
  pkg/virt-api/webhooks/validating-webhook/admitters/vmi-create-admitter.go
  pkg/virt-api/webhooks/validating-webhook/admitters/vmi-create-admitter_test.go
  pkg/virt-api/webhooks/validating-webhook/admitters/vms-admitter_test.go
Labels: size/M, release-note-none, lgtm, approved, dco-signoff: yes

#7632 virt-controller/watch/vmi_test: use HaveLen matcher
  pkg/virt-controller/watch/vmi_test.go
Labels: size/S, release-note-none, lgtm, approved, dco-signoff: yes, sig/code-quality

#7637 virt-launcher monitor: read the qemu pid file instead of grepping /proc
  cmd/fake-qemu-process/fake-qemu.go
  cmd/virt-launcher/virt-launcher.go
  pkg/virt-launcher/monitor.go
  pkg/virt-launcher/monitor_test.go
Labels: size/L, release-note-none, lgtm, approved, dco-signoff: yes

#7639 kubectl_test: use more meaningful expecter
  tests/kubectl_test.go
Labels: size/XS, release-note-none, lgtm, approved, dco-signoff: yes, sig/code-quality

#7643 virt-handler/device-manager tests: use HaveLen and BeEmpty
  pkg/virt-handler/device-manager/mediated_device_test.go
  pkg/virt-handler/device-manager/pci_device_test.go
Labels: size/S, release-note-none, lgtm, approved, dco-signoff: yes

#7520 Using Alpine extended image
  BUILD.bazel
  WORKSPACE
  containerimages/BUILD.bazel
  tests/console/login.go
  tests/containerdisk/containerdisk.go
  tests/libnet/BUILD.bazel
  tests/libnet/alpine.go
  tests/libvmi/BUILD.bazel
  tests/libvmi/factory.go
  tests/libvmi/network.go
  tests/migration_test.go
  tests/network/expose.go
  tests/network/macvtap.go
  tests/network/networkpolicy.go
  tests/network/probes.go
  tests/network/services.go
  tests/network/vmi_multus.go
  tests/network/vmi_networking.go
  tests/storage/storage.go
Labels: size/L, sig/network, release-note-none, lgtm, approved, dco-signoff: yes

#7656 test utils: address various code smells
  tests/utils.go
Labels: size/M, release-note-none, lgtm, approved, dco-signoff: yes

#7533 Add several VM snapshot metrics
  api/openapi-spec/swagger.json
  pkg/virt-controller/watch/snapshot/restore.go
  pkg/virt-controller/watch/snapshot/snapshot.go
  pkg/virt-controller/watch/snapshot/snapshot_test.go
  pkg/virt-controller/watch/snapshot/source.go
  pkg/virt-controller/watch/snapshot/util.go
  pkg/virt-operator/resource/generate/components/prometheus.go
  pkg/virt-operator/resource/generate/components/validations_generated.go
  staging/src/kubevirt.io/api/snapshot/v1alpha1/deepcopy_generated.go
  staging/src/kubevirt.io/api/snapshot/v1alpha1/types.go
  staging/src/kubevirt.io/api/snapshot/v1alpha1/types_swagger_generated.go
  staging/src/kubevirt.io/client-go/api/openapi_generated.go
  tests/monitoring/BUILD.bazel
  tests/monitoring/monitoring.go
  tests/monitoring/prometheus_utils.go
  tests/storage/restore.go
  tests/storage/snapshot.go
Labels: size/L, release-note, lgtm, approved, dco-signoff: yes, area/monitoring

#7660 tests: few more HaveLen
  pkg/virt-api/webhooks/validating-webhook/admitters/vmi-update-admitter_test.go
  pkg/virt-controller/services/template_test.go
  tests/util/util.go
  tests/virt_control_plane_test.go
Labels: size/S, release-note-none, lgtm, approved, dco-signoff: yes

#7654 Show migration progress timeout in actual seconds
  pkg/virt-launcher/virtwrap/live-migration-source.go
  pkg/virt-launcher/virtwrap/manager_test.go
Labels: size/M, release-note-none, lgtm, approved, dco-signoff: yes

#7512 Fix a wrong unit test
  pkg/virt-operator/resource/apply/core_test.go
Labels: size/XS, release-note-none, lgtm, approved, dco-signoff: yes

#7398 tests: Use DefaultInterfaceName const instead of "default" literal
  tests/libvmi/network.go
Labels: size/XS, release-note-none, lgtm, approved, dco-signoff: yes

#7554 flavors: Introduce Virtualmachineflavorspec
  api/openapi-spec/swagger.json
  pkg/flavor/BUILD.bazel
  pkg/flavor/flavor.go
  pkg/flavor/flavor_test.go
  pkg/testutils/mock_flavor.go
  pkg/virt-api/webhooks/validating-webhook/admitters/flavor-admitter.go
  pkg/virt-api/webhooks/validating-webhook/admitters/flavor-admitter_test.go
  pkg/virt-api/webhooks/validating-webhook/admitters/vms-admitter.go
  pkg/virt-api/webhooks/validating-webhook/admitters/vms-admitter_test.go
  pkg/virt-controller/watch/vm.go
  pkg/virt-controller/watch/vm_test.go
  pkg/virt-operator/resource/generate/components/validations_generated.go
  staging/src/kubevirt.io/api/core/v1/types.go
  staging/src/kubevirt.io/api/core/v1/types_swagger_generated.go
  staging/src/kubevirt.io/api/flavor/v1alpha1/deepcopy_generated.go
  staging/src/kubevirt.io/api/flavor/v1alpha1/types.go
  staging/src/kubevirt.io/api/flavor/v1alpha1/types_swagger_generated.go
  staging/src/kubevirt.io/client-go/api/openapi_generated.go
  tests/flavor_test.go
Labels: size/XXL, release-note-none, lgtm, approved, dco-signoff: yes
