Repository kubevirt/kubevirt, pull requests merged in 2023-09, with the labels that each got.

#10371 fix flaky archive upload test
  pkg/virtctl/imageupload/imageupload.go
Labels: size/XS, release-note-none, lgtm, approved, dco-signoff: yes

#10377 fix typos.
  docs/filesystem-pv-disks.md
  docs/reviewer-guide.md
  docs/vm-configuration.md
Labels: size/XS, release-note-none, lgtm, approved, ok-to-test, dco-signoff: yes

#10348 PR Template: Small rewording (no scope change)
  .github/PULL_REQUEST_TEMPLATE.md
Labels: size/XS, release-note-none, lgtm, approved, dco-signoff: yes

#10334 tests: add ignore preference disk bus test
  pkg/instancetype/instancetype_test.go
Labels: size/S, release-note-none, lgtm, approved, ok-to-test, dco-signoff: yes, area/instancetype

#10381 [release-1.0] SCC: Re-introduce CAP_SYS_PTRACE
  pkg/virt-operator/resource/generate/components/scc.go
  pkg/virt-operator/resource/generate/components/scc_test.go
Labels: size/XS, release-note-none, lgtm, approved, dco-signoff: yes

#10167 virtctl: Apply --namespace to created manifests
  pkg/virtctl/create/BUILD.bazel
  pkg/virtctl/create/clone/BUILD.bazel
  pkg/virtctl/create/clone/clone.go
  pkg/virtctl/create/clone/clone_test.go
  pkg/virtctl/create/create.go
  pkg/virtctl/create/instancetype/BUILD.bazel
  pkg/virtctl/create/instancetype/instancetype.go
  pkg/virtctl/create/instancetype/instancetype_test.go
  pkg/virtctl/create/preference/BUILD.bazel
  pkg/virtctl/create/preference/preference.go
  pkg/virtctl/create/preference/preference_test.go
  pkg/virtctl/create/vm/BUILD.bazel
  pkg/virtctl/create/vm/vm.go
  pkg/virtctl/create/vm/vm_test.go
  pkg/virtctl/root.go
Labels: size/L, release-note, lgtm, approved, dco-signoff: yes, area/instancetype

#10366 Delegate Slirp network configuration to hook sidecar using Slirp network binding plugin
  pkg/network/domainspec/domainspec_suite_test.go
  pkg/network/domainspec/generators.go
  pkg/network/domainspec/generators_test.go
  pkg/network/setup/network.go
  pkg/network/setup/podnic.go
  pkg/virt-controller/services/net_binding.go
  pkg/virt-controller/services/net_binding_test.go
  pkg/virt-controller/services/template.go
  pkg/virt-controller/services/template_test.go
  pkg/virt-launcher/virtwrap/converter/converter_test.go
  pkg/virt-launcher/virtwrap/converter/network.go
Labels: size/L, sig/network, release-note, lgtm, approved, dco-signoff: yes

#10380 Allow image-upload to recover from PendingPopulation phase
  pkg/virtctl/imageupload/imageupload.go
  pkg/virtctl/imageupload/imageupload_test.go
  tests/storage/imageupload.go
Labels: size/L, release-note, lgtm, approved, dco-signoff: yes

#10390 docs: Replace deprecated ginkgo regexScansFilePath flag with -focus-file
  docs/getting-started.md
Labels: size/XS, release-note-none, lgtm, approved, dco-signoff: yes

#10386 update ADOPTERS.md to add KubeSphere as an adopter for KubeVirt
  ADOPTERS.md
Labels: release-note, size/XS, lgtm, approved, needs-ok-to-test, dco-signoff: yes

#10337 misc fixes: go:embed (2), docs (1) and minor refactor
  api/openapi-spec/swagger.json
  manifests/generated/kv-resource.yaml
  pkg/virt-launcher/virtwrap/api/BUILD.bazel
  pkg/virt-launcher/virtwrap/api/schema_test.go
  pkg/virt-launcher/virtwrap/api/testdata/cpu_pinning.xml
  pkg/virt-launcher/virtwrap/api/testdata/domain_numa_topology.xml
  pkg/virt-launcher/virtwrap/converter/converter.go
  pkg/virt-operator/resource/generate/components/validations_generated.go
  staging/src/kubevirt.io/api/core/v1/types.go
  staging/src/kubevirt.io/api/core/v1/types_swagger_generated.go
  staging/src/kubevirt.io/client-go/api/openapi_generated.go
Labels: size/L, release-note-none, kind/api-change, lgtm, approved, dco-signoff: yes

#10382 [release-0.59] SCC: Re-introduce CAP_SYS_PTRACE
  pkg/virt-operator/resource/generate/components/scc.go
  pkg/virt-operator/resource/generate/components/scc_test.go
Labels: size/XS, release-note-none, lgtm, approved, dco-signoff: yes

#10398 [e2e] Extract eviction strategy migration tests in their own file
  tests/libnode/node.go
  tests/libvmi/vmi.go
  tests/migration/BUILD.bazel
  tests/migration/eviction_strategy.go
  tests/migration/migration.go
Labels: size/XXL, release-note-none, lgtm, approved, dco-signoff: yes, sig/code-quality

#10391 Allow setting of requests/limits on VMExport pod
  pkg/storage/export/export/export_test.go
  pkg/virt-controller/services/renderresources.go
  pkg/virt-controller/services/template.go
  staging/src/kubevirt.io/api/core/v1/types.go
  tests/storage/export.go
Labels: size/L, release-note, kind/api-change, lgtm, approved, dco-signoff: yes

#10370 Add PITS Global Data Recovery Services to the list of adopters
  ADOPTERS.md
Labels: release-note, size/XS, lgtm, approved, ok-to-test, dco-signoff: yes

#10405 Revert kubevirtci to previous published version
  cluster-up-sha.txt
  cluster-up/hack/common.sh
  cluster-up/version.txt
  hack/config-default.sh
Labels: size/XS, release-note-none, lgtm, approved, dco-signoff: yes

#10406 Flaky test: Ensure VMI has updated migration status
  tests/hotplug/cpu.go
  tests/utils.go
Labels: size/XS, release-note-none, lgtm, approved, dco-signoff: yes

#10417 Fix flaky node labeller test
  tests/infrastructure/node-labeller.go
Labels: size/XS, release-note-none, lgtm, approved, dco-signoff: yes

#10421 [release-0.59] Add request and limits to vm export pod
  pkg/storage/export/export/export_test.go
  pkg/virt-controller/services/renderresources.go
  pkg/virt-controller/services/template.go
  staging/src/kubevirt.io/api/core/v1/deepcopy_generated.go
  staging/src/kubevirt.io/api/core/v1/types.go
  staging/src/kubevirt.io/api/core/v1/types_swagger_generated.go
  staging/src/kubevirt.io/client-go/api/openapi_generated.go
  tests/storage/export.go
Labels: size/L, release-note-none, kind/api-change, lgtm, approved, dco-signoff: yes

#10050 rpm-deps: use qemu 8.0.0 and libvirt 9.5.0 plus fixes
  WORKSPACE
  hack/bootstrap.sh
  hack/rpm-deps.sh
  rpm/BUILD.bazel
Labels: release-note, size/XXL, lgtm, approved, dco-signoff: yes

#10394 [e2e] Simplify creation of VMIs in infra tests by using libvmi
  tests/infrastructure/BUILD.bazel
  tests/infrastructure/certificates.go
  tests/infrastructure/prometheus.go
  tests/infrastructure/virt-controller-leader-election.go
Labels: size/M, release-note-none, lgtm, approved, dco-signoff: yes

#10414 Filter out Nodes which are marked as unschedulable in GetAllSchedulableNodes
  tests/libnode/BUILD.bazel
  tests/libnode/node.go
Labels: size/S, release-note-none, lgtm, approved, dco-signoff: yes

#10416 fix syntax errors
  docs/README.md
  docs/container-empty-disks.md
Labels: size/XS, release-note-none, lgtm, approved, ok-to-test, dco-signoff: yes

#10086 Allow live updating VM node affinity
  api/openapi-spec/swagger.json
  pkg/virt-controller/watch/vm.go
  pkg/virt-operator/resource/generate/components/validations_generated.go
  staging/src/kubevirt.io/api/core/v1/deepcopy_generated.go
  staging/src/kubevirt.io/api/core/v1/types.go
  staging/src/kubevirt.io/api/core/v1/types_swagger_generated.go
  staging/src/kubevirt.io/client-go/api/openapi_generated.go
  tests/hotplug/BUILD.bazel
  tests/hotplug/affinity.go
Labels: size/L, release-note, kind/api-change, lgtm, approved, dco-signoff: yes

#10429 fix typos.
  hack/bazel-fmt.sh
  hack/bazel-generate.sh
  hack/cluster-build.sh
  hack/generate.sh
Labels: size/XS, release-note-none, lgtm, approved, ok-to-test, dco-signoff: yes

#9673 Expose DownwardMetrics through virtio-serial channel
  api/openapi-spec/swagger.json
  cmd/virt-handler/BUILD.bazel
  cmd/virt-handler/virt-handler.go
  cmd/virt-launcher/BUILD.bazel
  cmd/virt-launcher/virt-launcher.go
  pkg/downwardmetrics/BUILD.bazel
  pkg/downwardmetrics/downwardmetrics.go
  pkg/downwardmetrics/virtio-serial/BUILD.bazel
  pkg/downwardmetrics/virtio-serial/server.go
  pkg/downwardmetrics/virtio-serial/server_suite_test.go
  pkg/downwardmetrics/virtio-serial/server_test.go
  pkg/monitoring/domainstats/downwardmetrics/scraper.go
  pkg/virt-api/webhooks/validating-webhook/admitters/BUILD.bazel
  pkg/virt-api/webhooks/validating-webhook/admitters/vmi-create-admitter.go
  pkg/virt-api/webhooks/validating-webhook/admitters/vmi-create-admitter_test.go
  pkg/virt-handler/dmetrics-manager/BUILD.bazel
  pkg/virt-handler/dmetrics-manager/dmetrics-manager.go
  pkg/virt-handler/vm.go
  pkg/virt-handler/vm_test.go
  pkg/virt-launcher/virtwrap/converter/BUILD.bazel
  pkg/virt-launcher/virtwrap/converter/converter.go
  pkg/virt-launcher/virtwrap/converter/converter_test.go
  pkg/virt-launcher/virtwrap/converter/downwardmetrics.go
  pkg/virt-operator/resource/generate/components/validations_generated.go
  staging/src/kubevirt.io/api/core/v1/deepcopy_generated.go
  staging/src/kubevirt.io/api/core/v1/schema.go
  staging/src/kubevirt.io/api/core/v1/schema_swagger_generated.go
  staging/src/kubevirt.io/client-go/api/openapi_generated.go
  tests/infrastructure/downward-metrics.go
  tests/libinfra/metrics.go
  tests/libvmi/vmi.go
  tests/migration/migration.go
  tests/utils.go
Labels: release-note, size/XXL, kind/api-change, lgtm, approved, ok-to-test, kind/build-change, dco-signoff: yes, area/monitoring

#10433 [release-1.0] Stop considering nodes without `kubevirt.io/schedulable` label when finding lowest TSC frequency on the cluster
  pkg/virt-controller/watch/topology/filter.go
  pkg/virt-controller/watch/topology/filter_test.go
  pkg/virt-controller/watch/topology/hinter.go
Labels: size/M, release-note, lgtm, approved, dco-signoff: yes

#10445 [release-1.0] Replace/sanitize `ps` calls in isolated emulator thread tests
  tests/utils.go
  tests/vmi_configuration_test.go
Labels: size/M, release-note-none, lgtm, approved, dco-signoff: yes

#10451 Fix flaky test in k8s-1.26-sig-storage
  tests/storage/storage.go
Labels: size/S, release-note-none, lgtm, approved, dco-signoff: yes

#10400 Allow specifying download format in vmexport
  pkg/virtctl/memorydump/memorydump.go
  pkg/virtctl/memorydump/memorydump_test.go
  pkg/virtctl/vmexport/vmexport.go
  pkg/virtctl/vmexport/vmexport_test.go
Labels: size/L, release-note, lgtm, approved, dco-signoff: yes

#10453 Quarantine flaky cpu hotplug test in compute-migration lane
  tests/hotplug/cpu.go
Labels: size/XS, release-note-none, lgtm, approved, dco-signoff: yes

#10472 Small cleanups in virtctl
  pkg/virtctl/create/vm/vm.go
  tests/virtctl/create_vm.go
Labels: size/XS, release-note-none, lgtm, approved, dco-signoff: yes

#10231 Propogate public-keys to cloud-init NoCloud meta-data
  api/openapi-spec/swagger.json
  pkg/cloud-init/cloud-init.go
  pkg/cloud-init/cloud-init_test.go
  pkg/virt-api/webhooks/validating-webhook/admitters/vmi-create-admitter.go
  pkg/virt-api/webhooks/validating-webhook/admitters/vmi-create-admitter_test.go
  pkg/virt-operator/resource/generate/components/validations_generated.go
  staging/src/kubevirt.io/api/core/v1/deepcopy_generated.go
  staging/src/kubevirt.io/api/core/v1/schema.go
  staging/src/kubevirt.io/api/core/v1/schema_swagger_generated.go
  staging/src/kubevirt.io/client-go/api/openapi_generated.go
  tests/credentials_test.go
Labels: size/L, release-note, kind/api-change, lgtm, approved, dco-signoff: yes

#10476 Revert: Filter out Nodes which are marked as unschedulable
  tests/libnode/BUILD.bazel
  tests/libnode/node.go
Labels: size/XS, release-note-none, lgtm, approved, dco-signoff: yes

#10473 virt-launcher: fix enabled cpu num
  pkg/virt-launcher/virtwrap/converter/converter.go
  pkg/virt-launcher/virtwrap/converter/converter_test.go
Labels: size/M, release-note-none, lgtm, approved, ok-to-test, dco-signoff: yes

#10253 [virt-controller] Fix warning about ephemeral dir creation
  pkg/container-disk/container-disk.go
  pkg/virt-controller/watch/application.go
Labels: size/S, release-note, lgtm, approved, dco-signoff: yes

#10455 tests: migration: remove redundant VMI deletions
  tests/migration/migration.go
Labels: size/L, release-note-none, lgtm, approved, dco-signoff: yes

#10428 virt-launcher: Fix host-device metadata key calculation
  pkg/virt-launcher/virtwrap/manager.go
Labels: size/XS, release-note-none, lgtm, approved, dco-signoff: yes

#10480 Revert "Quarantine flaky cpu hotplug test in compute-migration lane"
  tests/hotplug/cpu.go
Labels: size/XS, release-note-none, lgtm, approved, dco-signoff: yes

#10447 Set memory limits if there is a resource quota with limits.
  pkg/storage/export/export/export_test.go
  pkg/storage/export/export/pvc-source_test.go
  pkg/storage/export/export/vm-source_test.go
  pkg/storage/export/export/vmsnapshot-source_test.go
  pkg/virt-config/feature-gates.go
  pkg/virt-controller/services/renderresources.go
  pkg/virt-controller/services/renderresources_test.go
  pkg/virt-controller/services/template.go
  pkg/virt-controller/services/template_test.go
  pkg/virt-controller/watch/application.go
  pkg/virt-controller/watch/application_test.go
  pkg/virt-controller/watch/migration_test.go
  pkg/virt-controller/watch/vmi_test.go
  staging/src/kubevirt.io/api/core/v1/types.go
  tests/testsuite/kubevirtresource.go
  tests/vmi_configuration_test.go
Labels: size/XL, release-note, kind/api-change, lgtm, approved, dco-signoff: yes

#10484 e2e: Add VMLiveUpdateFeaturesGate label to hotplug affinity tests
  tests/hotplug/affinity.go
Labels: size/XS, release-note-none, lgtm, approved, dco-signoff: yes

#10339 Add required and preferred annotations
  api/openapi-spec/swagger.json
  pkg/instancetype/instancetype.go
  pkg/instancetype/instancetype_test.go
  pkg/storage/export/export/export.go
  pkg/testutils/mock_instancetype.go
  pkg/virt-api/rest/expand.go
  pkg/virt-api/rest/expand_test.go
  pkg/virt-api/webhooks/validating-webhook/admitters/vms-admitter.go
  pkg/virt-api/webhooks/validating-webhook/admitters/vms-admitter_test.go
  pkg/virt-controller/watch/vm.go
  pkg/virt-operator/resource/generate/components/validations_generated.go
  staging/src/kubevirt.io/api/instancetype/v1alpha1/conversion_generated.go
  staging/src/kubevirt.io/api/instancetype/v1alpha2/conversion_generated.go
  staging/src/kubevirt.io/api/instancetype/v1beta1/deepcopy_generated.go
  staging/src/kubevirt.io/api/instancetype/v1beta1/types.go
  staging/src/kubevirt.io/api/instancetype/v1beta1/types_swagger_generated.go
  staging/src/kubevirt.io/client-go/api/openapi_generated.go
  tests/instancetype_test.go
Labels: size/L, kind/api-change, lgtm, approved, dco-signoff: yes, area/instancetype

#10450 virtctl: Enable inference in create vm by default
  pkg/virtctl/create/vm/vm.go
  pkg/virtctl/create/vm/vm_test.go
  tests/virtctl/create_vm.go
Labels: size/XL, release-note, lgtm, approved, dco-signoff: yes, area/instancetype

#10396 net, setup: Refactor the discovery (and store) step
  pkg/network/cache/dhcpconfig.go
  pkg/network/cache/dhcpconfig_test.go
  pkg/network/driver/nmstate/status.go
  pkg/network/infraconfigurators/BUILD.bazel
  pkg/network/infraconfigurators/bridge.go
  pkg/network/infraconfigurators/bridge_test.go
  pkg/network/infraconfigurators/generated_mock_common.go
  pkg/network/infraconfigurators/infraconfigurators_suite_test.go
  pkg/network/infraconfigurators/masquerade.go
  pkg/network/infraconfigurators/masquerade_test.go
  pkg/network/infraconfigurators/passt.go
  pkg/network/setup/BUILD.bazel
  pkg/network/setup/configstate.go
  pkg/network/setup/configstate_test.go
  pkg/network/setup/netconf.go
  pkg/network/setup/netpod/BUILD.bazel
  pkg/network/setup/netpod/discover.go
  pkg/network/setup/netpod/discoverbridge.go
  pkg/network/setup/netpod/masquerade/BUILD.bazel
  pkg/network/setup/netpod/masquerade/masquerade.go
  pkg/network/setup/netpod/masquerade/masquerade_suite_test.go
  pkg/network/setup/netpod/masquerade/masquerade_test.go
  pkg/network/setup/netpod/netpod.go
  pkg/network/setup/netpod/netpod_suite_test.go
  pkg/network/setup/netpod/netpod_test.go
  pkg/network/setup/network.go
  pkg/network/setup/network_suite_test.go
  pkg/network/setup/network_test.go
  pkg/network/setup/podnic.go
Labels: sig/network, size/XXL, release-note-none, lgtm, approved, dco-signoff: yes

#10489 build, controller: remove list and watch verbs from RBAC
  manifests/generated/operator-csv.yaml.in
  manifests/generated/rbac-operator.authorization.k8s.yaml.in
  pkg/virt-operator/resource/generate/rbac/controller.go
Labels: release-note, size/XS, lgtm, approved, dco-signoff: yes

#10478 pod template, network: use network-selection-elements structs
  pkg/virt-controller/services/multus_annotations.go
  pkg/virt-controller/services/multus_annotations_test.go
  pkg/virt-controller/services/template_test.go
  pkg/virt-controller/watch/vmi_test.go
Labels: size/M, release-note-none, lgtm, approved, dco-signoff: yes

#10488 e2e: Introduce QUARANTINE label
  automation/repeated_test.sh
  automation/test.sh
  docs/quarantine.md
  tests/decorators/decorators.go
  tests/operator/operator.go
Labels: size/S, release-note-none, lgtm, approved, dco-signoff: yes

#10044 Add operator-observability package
  go.mod
  go.sum
  pkg/monitoring/virt-controller/metrics/BUILD.bazel
  pkg/monitoring/virt-controller/metrics/component_metrics.go
  pkg/monitoring/virt-controller/metrics/metrics.go
  pkg/virt-controller/watch/BUILD.bazel
  pkg/virt-controller/watch/application.go
  pkg/virt-controller/watch/application_test.go
  vendor/github.com/go-openapi/jsonreference/.golangci.yml
  vendor/github.com/go-openapi/jsonreference/.travis.yml
  vendor/github.com/go-openapi/jsonreference/internal/normalize_url.go
  vendor/github.com/machadovilaca/operator-observability/LICENSE
  vendor/github.com/machadovilaca/operator-observability/pkg/operatormetrics/BUILD.bazel
  vendor/github.com/machadovilaca/operator-observability/pkg/operatormetrics/collector.go
  vendor/github.com/machadovilaca/operator-observability/pkg/operatormetrics/counter.go
  vendor/github.com/machadovilaca/operator-observability/pkg/operatormetrics/counter_vec.go
  vendor/github.com/machadovilaca/operator-observability/pkg/operatormetrics/gauge.go
  vendor/github.com/machadovilaca/operator-observability/pkg/operatormetrics/gauge_vec.go
  vendor/github.com/machadovilaca/operator-observability/pkg/operatormetrics/histogram.go
  vendor/github.com/machadovilaca/operator-observability/pkg/operatormetrics/histogram_vec.go
  vendor/github.com/machadovilaca/operator-observability/pkg/operatormetrics/metric.go
  vendor/github.com/machadovilaca/operator-observability/pkg/operatormetrics/registry.go
  vendor/github.com/machadovilaca/operator-observability/pkg/operatormetrics/summary.go
  vendor/github.com/machadovilaca/operator-observability/pkg/operatormetrics/summary_vec.go
  vendor/github.com/machadovilaca/operator-observability/pkg/operatormetrics/wrapper_registry.go
  vendor/golang.org/x/time/AUTHORS
  vendor/golang.org/x/time/CONTRIBUTORS
  vendor/golang.org/x/time/rate/BUILD.bazel
  vendor/golang.org/x/time/rate/rate.go
  vendor/golang.org/x/time/rate/sometimes.go
  vendor/modules.txt
Labels: release-note, size/XXL, lgtm, approved, dco-signoff: yes, area/monitoring

#10184 Add memory hotplug using virtio-mem
  api/openapi-spec/swagger.json
  manifests/generated/kv-resource.yaml
  pkg/controller/controller.go
  pkg/handler-launcher-com/cmd/v1/cmd.pb.go
  pkg/handler-launcher-com/cmd/v1/cmd.proto
  pkg/handler-launcher-com/cmd/v1/generated_mock_cmd.go
  pkg/virt-api/webhooks/defaults.go
  pkg/virt-api/webhooks/mutating-webhook/mutators/vmi-mutator_test.go
  pkg/virt-api/webhooks/validating-webhook/admitters/BUILD.bazel
  pkg/virt-api/webhooks/validating-webhook/admitters/vmi-update-admitter.go
  pkg/virt-api/webhooks/validating-webhook/admitters/vmi-update-admitter_test.go
  pkg/virt-api/webhooks/validating-webhook/admitters/vms-admitter.go
  pkg/virt-api/webhooks/validating-webhook/admitters/vms-admitter_test.go
  pkg/virt-config/configuration.go
  pkg/virt-config/configuration_test.go
  pkg/virt-config/virt-config.go
  pkg/virt-controller/services/renderresources.go
  pkg/virt-controller/watch/migration.go
  pkg/virt-controller/watch/migration_test.go
  pkg/virt-controller/watch/vm.go
  pkg/virt-controller/watch/vm_test.go
  pkg/virt-controller/watch/vmi.go
  pkg/virt-controller/watch/vmi_test.go
  pkg/virt-controller/watch/workload-updater/BUILD.bazel
  pkg/virt-controller/watch/workload-updater/workload-updater.go
  pkg/virt-controller/watch/workload-updater/workload-updater_test.go
  pkg/virt-handler/BUILD.bazel
  pkg/virt-handler/cmd-client/client.go
  pkg/virt-handler/cmd-client/generated_mock_client.go
  pkg/virt-handler/vm.go
  pkg/virt-handler/vm_test.go
  pkg/virt-launcher/notify-client/client.go
  pkg/virt-launcher/virtwrap/api/deepcopy_generated.go
  pkg/virt-launcher/virtwrap/api/schema.go
  pkg/virt-launcher/virtwrap/cli/generated_mock_libvirt.go
  pkg/virt-launcher/virtwrap/cli/libvirt.go
  pkg/virt-launcher/virtwrap/cmd-server/server.go
  pkg/virt-launcher/virtwrap/cmd-server/server_test.go
  pkg/virt-launcher/virtwrap/converter/converter.go
  pkg/virt-launcher/virtwrap/converter/converter_test.go
  pkg/virt-launcher/virtwrap/generated_mock_manager.go
  pkg/virt-launcher/virtwrap/manager.go
  pkg/virt-launcher/virtwrap/manager_test.go
  pkg/virt-operator/resource/generate/components/validations_generated.go
  staging/src/kubevirt.io/api/core/v1/deepcopy_generated.go
  staging/src/kubevirt.io/api/core/v1/schema.go
  staging/src/kubevirt.io/api/core/v1/schema_swagger_generated.go
  staging/src/kubevirt.io/api/core/v1/types.go
  staging/src/kubevirt.io/api/core/v1/types_swagger_generated.go
  staging/src/kubevirt.io/client-go/api/openapi_generated.go
  tests/hotplug/BUILD.bazel
  tests/hotplug/memory.go
Labels: release-note, size/XXL, kind/api-change, lgtm, approved, dco-signoff: yes

#10404 Raise event in case using default Slirp binding plugin image
  pkg/virt-controller/services/BUILD.bazel
  pkg/virt-controller/services/net_binding.go
  pkg/virt-controller/services/net_binding_test.go
  pkg/virt-controller/services/template.go
  pkg/virt-controller/services/template_test.go
  pkg/virt-controller/watch/application.go
  tests/network/BUILD.bazel
  tests/network/vmi_networking.go
Labels: size/L, sig/network, release-note-none, lgtm, approved, dco-signoff: yes

#10326 network, passt: Run passt through Libvirt API
  cmd/virt-launcher-monitor/virt-launcher-monitor.go
  pkg/network/domainspec/BUILD.bazel
  pkg/network/domainspec/generators.go
  pkg/network/domainspec/generators_test.go
  pkg/network/domainspec/interface.go
  pkg/network/istio/ports.go
  pkg/network/setup/netpod/masquerade/masquerade.go
  pkg/network/setup/netstat.go
  pkg/network/setup/podnic.go
  pkg/virt-launcher/virtwrap/api/deepcopy_generated.go
  pkg/virt-launcher/virtwrap/api/schema.go
  pkg/virt-launcher/virtwrap/converter/network.go
  tests/reporter/kubernetes.go
Labels: sig/network, size/XL, release-note-none, lgtm, approved, kind/build-change, dco-signoff: yes

#10454 Add PreferSpread option to PreferredCPUTopology
  api/openapi-spec/swagger.json
  pkg/instancetype/instancetype.go
  pkg/instancetype/instancetype_test.go
  pkg/testutils/mock_instancetype.go
  pkg/virt-api/webhooks/validating-webhook/admitters/vms-admitter.go
  pkg/virt-api/webhooks/validating-webhook/admitters/vms-admitter_test.go
  pkg/virt-operator/resource/generate/components/validations_generated.go
  staging/src/kubevirt.io/api/instancetype/v1alpha1/conversion_generated.go
  staging/src/kubevirt.io/api/instancetype/v1alpha2/conversion_generated.go
  staging/src/kubevirt.io/api/instancetype/v1beta1/types.go
  staging/src/kubevirt.io/api/instancetype/v1beta1/types_swagger_generated.go
  staging/src/kubevirt.io/client-go/api/openapi_generated.go
Labels: size/L, release-note-none, kind/api-change, lgtm, approved, dco-signoff: yes, area/instancetype

#10487 e2e: Fix not cleaned global err variable causing flakyness
  tests/vmi_configuration_test.go
Labels: size/L, release-note-none, lgtm, approved, dco-signoff: yes

#10015 USB host pass through
  WORKSPACE
  api/openapi-spec/swagger.json
  examples/vmi-usb.yaml
  hack/bootstrap.sh
  hack/rpm-deps.sh
  manifests/generated/kv-resource.yaml
  pkg/virt-controller/services/renderresources.go
  pkg/virt-handler/device-manager/BUILD.bazel
  pkg/virt-handler/device-manager/device_controller.go
  pkg/virt-handler/device-manager/device_controller_test.go
  pkg/virt-handler/device-manager/generic_device.go
  pkg/virt-handler/device-manager/mediated_device.go
  pkg/virt-handler/device-manager/pci_device.go
  pkg/virt-handler/device-manager/socket_device.go
  pkg/virt-handler/device-manager/usb_device.go
  pkg/virt-handler/device-manager/usb_device_test.go
  pkg/virt-launcher/virtwrap/api/schema.go
  pkg/virt-launcher/virtwrap/converter/converter.go
  pkg/virt-launcher/virtwrap/device/BUILD.bazel
  pkg/virt-launcher/virtwrap/device/hostdevice/generic/addresspool.go
  pkg/virt-launcher/virtwrap/device/hostdevice/generic/hostdev.go
  pkg/virt-launcher/virtwrap/device/hostdevice/generic/hostdev_test.go
  pkg/virt-launcher/virtwrap/device/hostdevice/hostdev.go
  pkg/virt-launcher/virtwrap/device/usbaddress.go
  pkg/virt-operator/resource/generate/components/validations_generated.go
  rpm/BUILD.bazel
  staging/src/kubevirt.io/api/core/v1/deepcopy_generated.go
  staging/src/kubevirt.io/api/core/v1/types.go
  staging/src/kubevirt.io/api/core/v1/types_swagger_generated.go
  staging/src/kubevirt.io/client-go/api/openapi_generated.go
  tests/BUILD.bazel
  tests/decorators/decorators.go
  tests/tests_suite_test.go
  tests/usb/BUILD.bazel
  tests/usb/usb.go
  tools/vms-generator/utils/utils.go
  tools/vms-generator/vms-generator.go
Labels: release-note, size/XXL, kind/api-change, lgtm, approved, dco-signoff: yes

#10497 Add autoResourceLimit label decorator
  tests/decorators/decorators.go
  tests/vmi_configuration_test.go
Labels: size/XS, release-note-none, lgtm, approved, dco-signoff: yes
