Repository kubevirt/kubevirt, pull requests merged in 2023-02, with the labels that each got.

#9112 Fix network test to make it 'restricted' PSA compliant
  tests/network/vmi_networking.go
Labels: size/S, sig/network, release-note-none, lgtm, approved, dco-signoff: yes

#9119 tests, network: Fix guest PCI address check
  tests/network/vmi_networking.go
Labels: sig/network, size/XS, release-note-none, lgtm, approved, dco-signoff: yes

#9118 [release-0.58] e2e tests: Fix mismatch between By sentence and code
  tests/migration_test.go
Labels: size/XS, release-note-none, lgtm, approved, dco-signoff: yes

#8774 Add Virtual machines CPU metrics
  WORKSPACE
  docs/metrics.md
  hack/bootstrap.sh
  hack/rpm-deps.sh
  pkg/monitoring/domainstats/prometheus/prometheus.go
  pkg/monitoring/domainstats/prometheus/prometheus_test.go
  rpm/BUILD.bazel
  tests/monitoring/monitoring.go
  tools/doc-generator/fakeDomainCollector.go
Labels: release-note, size/XXL, kind/api-change, lgtm, approved, ok-to-test, dco-signoff: yes, area/monitoring

#9116 vm/vmi, api, interfaces: Expose the ACPI Index parameter
  api/openapi-spec/swagger.json
  pkg/virt-launcher/virtwrap/api/deepcopy_generated.go
  pkg/virt-launcher/virtwrap/api/schema.go
  pkg/virt-launcher/virtwrap/converter/network.go
  pkg/virt-operator/resource/generate/components/validations_generated.go
  staging/src/kubevirt.io/api/core/v1/schema.go
  staging/src/kubevirt.io/api/core/v1/schema_swagger_generated.go
  staging/src/kubevirt.io/client-go/api/openapi_generated.go
  tests/network/vmi_networking.go
Labels: size/L, sig/network, release-note, kind/api-change, lgtm, approved, dco-signoff: yes

#9076 Return entire CA PEM if unable to match host/domain for export
  pkg/storage/export/export/export_test.go
  pkg/storage/export/export/links.go
Labels: size/M, release-note-none, lgtm, approved, dco-signoff: yes

#9121 Fix guestfs test failure with PSA enabled
  tests/storage/guestfs.go
Labels: size/M, release-note-none, lgtm, approved, dco-signoff: yes

#9120 Fix access to portforwarding on VMs/VMIs with the cluster roles kubevirt.io:[admin|edit]
  manifests/generated/operator-csv.yaml.in
  manifests/generated/rbac-operator.authorization.k8s.yaml.in
  pkg/virt-operator/resource/generate/rbac/cluster.go
  tests/access_test.go
Labels: size/S, release-note, lgtm, approved, dco-signoff: yes

#9137 Remove PSASeccompAllowsUserfaultfd
  pkg/virt-api/webhooks/validating-webhook/admitters/BUILD.bazel
  pkg/virt-api/webhooks/validating-webhook/admitters/migrationpolicy-admitter.go
  pkg/virt-api/webhooks/validating-webhook/admitters/migrationpolicy-admitter_test.go
  pkg/virt-config/feature-gates.go
  pkg/virt-controller/services/template.go
  pkg/virt-controller/services/template_test.go
  pkg/virt-controller/watch/BUILD.bazel
  pkg/virt-controller/watch/migration.go
  pkg/virt-controller/watch/migration_test.go
  pkg/virt-controller/watch/vmi.go
  tests/testsuite/kubevirtresource.go
Labels: size/L, release-note-none, lgtm, approved, dco-signoff: yes

#9135 Upgrade tests split
  automation/test.sh
  tests/BUILD.bazel
  tests/decorators/decorators.go
  tests/operator/BUILD.bazel
  tests/operator/operator.go
  tests/storage/datavolume.go
  tests/tests_suite_test.go
Labels: size/L, release-note-none, lgtm, approved, dco-signoff: yes

#9072 Add virtctl expand command
  pkg/virtctl/root.go
  pkg/virtctl/vm/BUILD.bazel
  pkg/virtctl/vm/vm.go
  pkg/virtctl/vm/vm_test.go
  tests/vm_test.go
Labels: size/L, release-note, lgtm, approved, dco-signoff: yes, area/instancetype

#9152 [release-0.53] Fix access to portforwarding on VMs/VMIs with the cluster roles kubevirt.io:[admin|edit]
  manifests/generated/operator-csv.yaml.in
  manifests/generated/rbac-operator.authorization.k8s.yaml.in
  pkg/virt-operator/resource/generate/rbac/cluster.go
  tests/access_test.go
Labels: size/M, release-note, lgtm, approved, dco-signoff: yes

#9047 Deprecate VM stuck in status alerts
  hack/prom-rule-ci/prom-rules-tests.yaml
  pkg/virt-operator/resource/generate/components/prometheus.go
  tests/monitoring/monitoring.go
Labels: size/L, release-note, lgtm, approved, dco-signoff: yes, area/monitoring

#9103 virt-api: Refactor, share and use `VirtualMachineInstanceSpec` defaulting code from VM validation webhook
  pkg/util/util.go
  pkg/virt-api/webhooks/BUILD.bazel
  pkg/virt-api/webhooks/amd64.go
  pkg/virt-api/webhooks/arm64.go
  pkg/virt-api/webhooks/defaults.go
  pkg/virt-api/webhooks/hyperv.go
  pkg/virt-api/webhooks/mutating-webhook/mutators/BUILD.bazel
  pkg/virt-api/webhooks/mutating-webhook/mutators/vmi-mutator.go
  pkg/virt-api/webhooks/mutating-webhook/mutators/vmi-mutator_test.go
  pkg/virt-api/webhooks/validating-webhook/admitters/vms-admitter.go
  pkg/virt-api/webhooks/validating-webhook/admitters/vms-admitter_test.go
  pkg/virt-config/virt-config.go
  pkg/virt-controller/watch/vm.go
  pkg/virt-launcher/virtwrap/converter/converter_test.go
Labels: size/XL, release-note-none, lgtm, approved, dco-signoff: yes, area/instancetype

#9133 Fix addvolume removevolume bugs
  pkg/virt-api/rest/subresource.go
  pkg/virt-api/rest/subresource_test.go
  tests/storage/hotplug.go
Labels: size/L, release-note, lgtm, approved, dco-signoff: yes

#9155 Add missing ports to istio reseved ports list
  pkg/network/domainspec/generators_test.go
  pkg/network/istio/ports.go
Labels: sig/network, size/XS, release-note-none, lgtm, approved, dco-signoff: yes

#9138 [e2e]: treat kubevirt CR conditions when preparing the environment
  tests/testsuite/BUILD.bazel
  tests/testsuite/fixture.go
  tests/utils.go
Labels: size/M, release-note-none, lgtm, approved, dco-signoff: yes

#8937 Add VirtualMachine foreground finalizer
  pkg/virt-api/webhooks/validating-webhook/admitters/vms-admitter.go
  pkg/virt-api/webhooks/validating-webhook/admitters/vms-admitter_test.go
  pkg/virt-controller/watch/vm.go
  pkg/virt-controller/watch/vm_test.go
  tests/storage/snapshot.go
  tests/vm_test.go
Labels: size/L, release-note, lgtm, approved, dco-signoff: yes

#9130 Fix check for Serial run
  tests/infra_test.go
Labels: size/XS, release-note-none, lgtm, approved, dco-signoff: yes

#9145 Show VM name in export status
  api/openapi-spec/swagger.json
  pkg/storage/export/export/vm-source.go
  pkg/storage/export/export/vmsnapshot-source.go
  pkg/virt-operator/resource/generate/components/validations_generated.go
  staging/src/kubevirt.io/api/export/v1alpha1/deepcopy_generated.go
  staging/src/kubevirt.io/api/export/v1alpha1/types.go
  staging/src/kubevirt.io/api/export/v1alpha1/types_swagger_generated.go
  staging/src/kubevirt.io/client-go/api/openapi_generated.go
  tests/storage/export.go
Labels: size/M, release-note, kind/api-change, lgtm, approved, dco-signoff: yes

#9142 Update performance automation to point to new prometheus svc
  automation/perfscale-test.sh
Labels: size/XS, release-note-none, lgtm, approved, dco-signoff: yes

#9164 Fix operator target
  automation/test.sh
Labels: size/XS, release-note-none, lgtm, approved, dco-signoff: yes

#9136 Fix export datavolume tests duplicate mac
  tests/storage/export.go
Labels: size/S, release-note-none, lgtm, approved, dco-signoff: yes

#9174 [release-0.58] RT fixes
  examples/vmi-fedora-isolated.yaml
  pkg/virt-handler/BUILD.bazel
  pkg/virt-handler/cgroup/cgroup.go
  pkg/virt-handler/cgroup/cgroup_v1_manager.go
  pkg/virt-handler/cgroup/cgroup_v2_manager.go
  pkg/virt-handler/cgroup/generated_mock_cgroup.go
  pkg/virt-handler/cgroup/util.go
  pkg/virt-handler/isolation/detector.go
  pkg/virt-handler/isolation/generated_mock_isolation.go
  pkg/virt-handler/isolation/isolation.go
  pkg/virt-handler/realtime.go
  pkg/virt-handler/realtime_test.go
  pkg/virt-handler/setsched.go
  pkg/virt-handler/vm.go
  pkg/virt-launcher/virtwrap/api/deepcopy_generated.go
  pkg/virt-launcher/virtwrap/api/schema.go
  pkg/virt-launcher/virtwrap/converter/converter.go
  pkg/virt-launcher/virtwrap/converter/converter_test.go
  pkg/virt-launcher/virtwrap/converter/vcpu/vcpu.go
  pkg/virt-launcher/virtwrap/manager.go
  staging/src/kubevirt.io/api/core/v1/types.go
  tests/realtime/realtime.go
  tests/utils.go
  tests/vmi_configuration_test.go
  tools/vms-generator/utils/utils.go
  tools/vms-generator/vms-generator.go
Labels: size/XL, release-note-none, lgtm, approved, dco-signoff: yes

#8868 Document backup partner integration touchpoints
  docs/backup-graph.png
  docs/backup-restore-integration.md
Labels: size/L, release-note-none, lgtm, approved, dco-signoff: yes

#9141 e2e test: Fix imagePullSecrets check
  tests/operator/operator.go
Labels: size/S, release-note-none, lgtm, approved, dco-signoff: yes

#9148 fix a typo
  pkg/virt-launcher/virtwrap/converter/converter.go
Labels: size/XS, release-note-none, lgtm, approved, ok-to-test, dco-signoff: yes

#9179 [release-0.49] Hotplug cache none
  pkg/virt-launcher/virtwrap/manager.go
  pkg/virt-launcher/virtwrap/manager_test.go
Labels: size/M, release-note-none, lgtm, approved, dco-signoff: yes

#9188 RBAC for export and clone virtual machine
  manifests/generated/operator-csv.yaml.in
  manifests/generated/rbac-operator.authorization.k8s.yaml.in
  pkg/virt-operator/resource/generate/rbac/cluster.go
Labels: size/L, release-note, lgtm, approved, dco-signoff: yes

#8989 Multi Arch Image Build
  Makefile
  hack/bazel-build-images.sh
  hack/bazel-push-images.sh
  hack/cluster-build.sh
  hack/common.sh
  hack/multi-arch.sh
  hack/parse-shasums.sh
  hack/push-container-manifest.sh
Labels: size/L, release-note, lgtm, approved, dco-signoff: yes

#9066 Update FOSSA to 3.6.11
  .fossa.yml
  Makefile
  hack/fossa.sh
Labels: size/L, release-note-none, lgtm, approved, dco-signoff: yes

#9019 remove optional option from secret secretName
  staging/src/kubevirt.io/api/core/v1/schema.go
  staging/src/kubevirt.io/api/core/v1/schema_swagger_generated.go
Labels: size/XS, release-note-none, kind/api-change, lgtm, approved, dco-signoff: yes

#9123 Fix inconsistency between export-server and vmexport status links
  pkg/storage/export/export/export.go
  pkg/storage/export/export/links.go
  pkg/storage/export/export/pvc-source.go
  pkg/storage/export/export/vm-source.go
  pkg/storage/export/export/vmsnapshot-source.go
  pkg/storage/export/export/vmsnapshot-source_test.go
  tests/storage/export.go
Labels: size/M, release-note-none, lgtm, approved, dco-signoff: yes

#9187 Revert "Run the migration finalizing code only when the migration is complete"
  pkg/virt-handler/BUILD.bazel
  pkg/virt-handler/vm.go
  pkg/virt-handler/vm_test.go
  staging/src/kubevirt.io/api/core/v1/types.go
Labels: size/L, release-note-none, kind/api-change, lgtm, approved, dco-signoff: yes, release-blocker/release-0.59

#9134 Disable the use of the custom SELinux policy on Centos 9 providers
  automation/test.sh
  cmd/virt-handler/virt_launcher.cil
  hack/functests.sh
  tests/decorators/decorators.go
  tests/flags/flags.go
  tests/security_features_test.go
  tests/testsuite/kubevirtresource.go
Labels: size/M, release-note-none, lgtm, approved, dco-signoff: yes

#9186 Tests: Fix seccomp on psa enabled clusters
  tests/operator/BUILD.bazel
  tests/operator/operator.go
Labels: size/M, release-note-none, lgtm, approved, dco-signoff: yes

#9203 [release-0.58] virt-launcher: use our custom SELinux type only when necessary
  cmd/virt-handler/virt_launcher.cil
  pkg/util/util.go
  pkg/virt-config/virt-config.go
  pkg/virt-controller/services/template.go
  pkg/virt-controller/services/template_test.go
  tests/network/vmi_passt.go
  tests/storage/storage.go
  tests/vmi_configuration_test.go
Labels: size/L, sig/network, release-note, lgtm, approved, dco-signoff: yes

#9170 Improve handling of clone DataVolumes without source PVC
  pkg/storage/types/dv.go
  pkg/virt-controller/watch/vm.go
  pkg/virt-controller/watch/vm_test.go
  tests/storage/datavolume.go
Labels: size/L, release-note-none, lgtm, approved, dco-signoff: yes

#9157 Label Istio test and allow disabling them with TARGET envvar
  automation/test.sh
  tests/decorators/decorators.go
  tests/network/vmi_istio.go
Labels: size/S, sig/network, release-note-none, lgtm, approved, dco-signoff: yes

#9160 Force to use the virtio non-transitional for VSOCK device.
  pkg/virt-launcher/virtwrap/converter/converter.go
  pkg/virt-launcher/virtwrap/converter/converter_test.go
  tests/vmi_vsock_test.go
Labels: size/M, release-note-none, lgtm, approved, ok-to-test, dco-signoff: yes

#9209 Fix SCC for Seccomp
  pkg/virt-operator/resource/generate/components/BUILD.bazel
  pkg/virt-operator/resource/generate/components/scc.go
  pkg/virt-operator/resource/generate/components/scc_test.go
Labels: size/M, release-note-none, lgtm, approved, dco-signoff: yes

#9211 Tests: Fix seccomp test typo
  tests/operator/operator.go
Labels: size/XS, release-note-none, lgtm, approved, dco-signoff: yes

#9215 [e2e-tests]Should remove and restore labeler only from workers
  tests/hyperv_test.go
Labels: size/S, release-note-none, lgtm, approved, dco-signoff: yes

#9216 [e2e-tests]If Reenlightenment is enabled Freq must be exposed
  pkg/virt-controller/watch/BUILD.bazel
  pkg/virt-controller/watch/vmi_test.go
  tests/decorators/decorators.go
  tests/hyperv_test.go
  tests/migration_test.go
  tests/vmi_configuration_test.go
Labels: size/S, release-note-none, lgtm, approved, dco-signoff: yes

#9222 [release-0.49] tests: libvmi.New: no explicit name
  tests/libvmi/factory.go
  tests/libvmi/vmi.go
Labels: size/S, release-note-none, lgtm, approved, dco-signoff: yes

#9221 Replace `HaveLen(0)` with `BeEmpty()`
  pkg/instancetype/instancetype_test.go
  pkg/storage/export/virt-exportserver/exportserver_test.go
  pkg/virt-api/webhooks/validating-webhook/admitters/vmi-create-admitter_test.go
  tests/vm_test.go
Labels: size/M, release-note-none, lgtm, approved, dco-signoff: yes

#9196 [release-0.58] [e2e] Fix flaky tls test
  tests/migration_test.go
Labels: size/S, release-note-none, lgtm, approved, dco-signoff: yes

#9110 api: Correct default `PreferredCPUTopology` referenced in docs
  staging/src/kubevirt.io/api/instancetype/v1alpha1/types.go
  staging/src/kubevirt.io/api/instancetype/v1alpha1/types_swagger_generated.go
  staging/src/kubevirt.io/client-go/api/openapi_generated.go
Labels: size/XS, release-note-none, kind/api-change, lgtm, approved, dco-signoff: yes, area/instancetype

#9169 Revert "Add checks of dedicatedCPUPlacement to validation webhook"
  pkg/virt-api/webhooks/validating-webhook/admitters/instancetype-admitter.go
  pkg/virt-api/webhooks/validating-webhook/admitters/instancetype-admitter_test.go
  tests/instancetype_test.go
Labels: size/L, release-note, lgtm, approved, dco-signoff: yes, area/instancetype

#9173 [e2e]: improve vmpool tests
  tests/pool_test.go
  tests/reporter/kubernetes.go
Labels: size/S, release-note-none, lgtm, approved, dco-signoff: yes

#9210 [release-0.59]Revert "Run the migration finalizing code only when the migration is …
  pkg/virt-handler/BUILD.bazel
  pkg/virt-handler/vm.go
  pkg/virt-handler/vm_test.go
  staging/src/kubevirt.io/api/core/v1/types.go
Labels: size/L, release-note-none, kind/api-change, lgtm, approved, dco-signoff: yes

#9182 [release-0.49] [Bug-fix]: Windows VM HyperV Reenlightenment enabled fails to migrate
  pkg/virt-api/webhooks/hyperv.go
  pkg/virt-controller/watch/topology/BUILD.bazel
  pkg/virt-controller/watch/topology/hinter.go
  pkg/virt-controller/watch/topology/tsc.go
  pkg/virt-controller/watch/topology/tsc_test.go
  pkg/virt-controller/watch/vmi.go
  pkg/virt-controller/watch/vmi_test.go
  pkg/virt-launcher/virtwrap/converter/converter.go
  tests/BUILD.bazel
  tests/migration_test.go
Labels: size/L, release-note, lgtm, approved, dco-signoff: yes

#9162 [Vulnerability mitigation] limit operator secrets permission
  manifests/generated/operator-csv.yaml.in
  manifests/generated/rbac-operator.authorization.k8s.yaml.in
  pkg/virt-api/webhooks/BUILD.bazel
  pkg/virt-api/webhooks/mutating-webhook/mutators/BUILD.bazel
  pkg/virt-api/webhooks/mutating-webhook/mutators/vmi-mutator_test.go
  pkg/virt-api/webhooks/utils.go
  pkg/virt-api/webhooks/validating-webhook/admitters/BUILD.bazel
  pkg/virt-api/webhooks/validating-webhook/admitters/vmi-create-admitter_test.go
  pkg/virt-api/webhooks/validating-webhook/admitters/vmi-update-admitter_test.go
  pkg/virt-operator/resource/generate/components/BUILD.bazel
  pkg/virt-operator/resource/generate/components/daemonsets.go
  pkg/virt-operator/resource/generate/components/deployments.go
  pkg/virt-operator/resource/generate/components/serviceaccountnames.go
  pkg/virt-operator/resource/generate/rbac/BUILD.bazel
  pkg/virt-operator/resource/generate/rbac/apiserver.go
  pkg/virt-operator/resource/generate/rbac/controller.go
  pkg/virt-operator/resource/generate/rbac/handler.go
  pkg/virt-operator/resource/generate/rbac/operator.go
  pkg/virt-operator/resource/generate/rbac/operator_test.go
Labels: size/L, release-note, lgtm, approved, ok-to-test, dco-signoff: yes

#9205 [e2e] Add "labels" parameter to CreateFSPVC helper function
  tests/libstorage/pvc.go
  tests/storage/memorydump.go
  tests/virtctl/create_vm.go
Labels: size/S, release-note-none, lgtm, approved, dco-signoff: yes

#9226 [release-0.59] Fix inconsistency between export-server and vmexport status links
  pkg/storage/export/export/export.go
  pkg/storage/export/export/links.go
  pkg/storage/export/export/pvc-source.go
  pkg/storage/export/export/vm-source.go
  pkg/storage/export/export/vmsnapshot-source.go
  pkg/storage/export/export/vmsnapshot-source_test.go
  tests/storage/export.go
Labels: size/M, release-note-none, lgtm, approved, dco-signoff: yes

#9228 Fix OOM virtiofs container limit
  pkg/virt-controller/services/virtiofs.go
Labels: release-note, size/XS, lgtm, approved, ok-to-test, dco-signoff: yes

#9248 tests, network: xfail mac-spoof-check
  tests/network/BUILD.bazel
  tests/network/vmi_multus.go
Labels: size/M, sig/network, release-note-none, lgtm, approved, dco-signoff: yes

#9230 [release-0.58] Fix addvolume removevolume bugs
  pkg/virt-api/rest/subresource.go
  pkg/virt-api/rest/subresource_test.go
  tests/storage/hotplug.go
Labels: size/L, release-note, lgtm, approved, dco-signoff: yes

#9144 Sync VMI dynamic labels to pod after live migration
  pkg/virt-controller/watch/vmi.go
  pkg/virt-controller/watch/vmi_test.go
Labels: size/L, release-note-none, lgtm, approved, dco-signoff: yes

#9251 Test: Seccomp increase timeout
  tests/operator/operator.go
Labels: size/XS, release-note-none, lgtm, approved, dco-signoff: yes

#9247 [release-0.59] Backport operator tests split
  automation/test.sh
  tests/operator/BUILD.bazel
  tests/operator/operator.go
Labels: size/M, release-note-none, lgtm, approved, dco-signoff: yes

#9255 add test id
  tests/storage/snapshot.go
Labels: size/XS, release-note-none, lgtm, approved, ok-to-test, dco-signoff: yes

#9125 virt-*: bump memory requests above highest values seen in testing
  manifests/generated/operator-csv.yaml.in
  pkg/virt-operator/resource/generate/components/daemonsets.go
  pkg/virt-operator/resource/generate/components/deployments.go
Labels: size/S, release-note-none, lgtm, approved, dco-signoff: yes

#9241 Respect GS_IMAGE in virtctl guestfs
  pkg/virt-api/api.go
  pkg/virtctl/guestfs/guestfs.go
  pkg/virtctl/guestfs/guestfs_test.go
  staging/src/kubevirt.io/client-go/kubecli/guestfs.go
Labels: size/M, release-note, lgtm, approved, dco-signoff: yes

#9265 Quarantine flaky vgpu test that overrides default mdev config
  tests/mdev_configuration_allocation_test.go
Labels: size/XS, release-note-none, lgtm, approved, dco-signoff: yes

#9259 Fix vm deletion with --cascade=orphan
  pkg/virt-controller/watch/vm.go
  tests/storage/datavolume.go
Labels: size/S, release-note-none, lgtm, approved, dco-signoff: yes

#9067 instancetype: Follow ups from #8537
  pkg/instancetype/instancetype.go
  pkg/instancetype/instancetype_test.go
  pkg/storage/export/export/export.go
  pkg/virt-api/rest/subresource.go
  pkg/virt-api/webhooks/mutating-webhook/mutating-webhook.go
  pkg/virt-api/webhooks/mutating-webhook/mutators/vm-mutator_test.go
  pkg/virt-api/webhooks/validating-webhook/admitters/vms-admitter.go
  pkg/virt-controller/watch/application.go
  pkg/virt-controller/watch/vm_test.go
Labels: size/L, release-note-none, lgtm, approved, dco-signoff: yes, area/instancetype

#9260 Fix bug of possible re-trigger of memory dump
  pkg/virt-launcher/virtwrap/manager.go
  pkg/virt-launcher/virtwrap/manager_test.go
Labels: size/M, release-note, lgtm, approved, dco-signoff: yes

#9281 Add chroot capability to rsync container in hack/dockerized
  hack/dockerized
Labels: size/XS, release-note-none, lgtm, approved, dco-signoff: yes

#9193 virt-handler: Add live-migration bridge pod net annotation
  pkg/network/vmispec/interface.go
  pkg/virt-handler/vm.go
  pkg/virt-handler/vm_test.go
  staging/src/kubevirt.io/api/core/v1/types.go
Labels: size/M, sig/network, release-note, kind/api-change, lgtm, approved, dco-signoff: yes

#9240 Test: Fix PSA issue on OKD
  tests/testsuite/namespace.go
Labels: size/XS, release-note-none, lgtm, approved, dco-signoff: yes

#9201 [release-0.49] Fix Live Migration for reenlightenment VMIs
  cmd/virt-handler/virt-handler.go
  pkg/virt-handler/BUILD.bazel
  pkg/virt-handler/vm.go
  pkg/virt-handler/vm_test.go
Labels: size/M, release-note, lgtm, approved, dco-signoff: yes

#9143 Quarantine fstrim tests so sig-storage-centos9 can be enabled
  tests/storage/datavolume.go
Labels: size/XS, release-note-none, lgtm, approved, dco-signoff: yes

#9242 [e2e]: improve cloud-init user-data specs
  tests/vmi_cloudinit_test.go
Labels: size/L, release-note-none, lgtm, approved, dco-signoff: yes

#9250 device manager: externally provided mediated devices should not be removed
  pkg/virt-config/feature-gates.go
  pkg/virt-handler/device-manager/device_controller.go
  pkg/virt-handler/device-manager/mediated_devices_types.go
  pkg/virt-handler/device-manager/mediated_devices_types_test.go
  pkg/virt-handler/heartbeat/heartbeat.go
  tests/mdev_configuration_allocation_test.go
Labels: size/L, release-note, lgtm, approved, dco-signoff: yes

#9256 Improve error message when virt-freezer fails on paused VM
  cmd/virt-freezer/main.go
  tests/storage/snapshot.go
Labels: size/XS, release-note-none, lgtm, approved, dco-signoff: yes

#9294 virtctl, image-upload: Fix a typo in an error message
  pkg/virtctl/imageupload/imageupload.go
  pkg/virtctl/imageupload/imageupload_test.go
Labels: size/XS, release-note-none, lgtm, approved, dco-signoff: yes

#9163 bug: fix the requests/limits CPU number mismatch for VMs with isolatedEmulatorThread
  pkg/virt-controller/services/renderresources.go
  pkg/virt-controller/services/renderresources_test.go
  tests/vmi_configuration_test.go
Labels: size/M, release-note, lgtm, approved, dco-signoff: yes

#9280 Fail fsfreeze of VMI in case it is during migration
  pkg/virt-launcher/virtwrap/manager.go
  pkg/virt-launcher/virtwrap/manager_test.go
Labels: size/S, release-note-none, lgtm, approved, dco-signoff: yes

#9298 [e2e] Increase timeout for agentConnected condition
  tests/vmi_headless_test.go
Labels: size/XS, release-note-none, lgtm, approved, dco-signoff: yes

#9296 Move existing files from create folder into subfolders
  pkg/virtctl/create/BUILD.bazel
  pkg/virtctl/create/create.go
  pkg/virtctl/create/params/BUILD.bazel
  pkg/virtctl/create/params/params.go
  pkg/virtctl/create/vm/BUILD.bazel
  pkg/virtctl/create/vm/vm.go
  pkg/virtctl/create/vm/vm_suite_test.go
  pkg/virtctl/create/vm/vm_test.go
  tests/virtctl/BUILD.bazel
  tests/virtctl/create_vm.go
Labels: size/L, release-note-none, lgtm, approved, dco-signoff: yes

#9276 [release-0.59] Add VirtualMachine foreground finalizer
  pkg/virt-api/webhooks/validating-webhook/admitters/vms-admitter.go
  pkg/virt-api/webhooks/validating-webhook/admitters/vms-admitter_test.go
  pkg/virt-controller/watch/vm.go
  pkg/virt-controller/watch/vm_test.go
  tests/storage/datavolume.go
  tests/storage/snapshot.go
  tests/vm_test.go
Labels: size/L, release-note, lgtm, approved, dco-signoff: yes

#9308 Bump golang golang.org/x/text to v0.3.8
  go.mod
  go.sum
  vendor/golang.org/x/text/AUTHORS
  vendor/golang.org/x/text/CONTRIBUTORS
  vendor/golang.org/x/text/encoding/htmlindex/tables.go
  vendor/golang.org/x/text/encoding/internal/identifier/mib.go
  vendor/golang.org/x/text/encoding/simplifiedchinese/gbk.go
  vendor/golang.org/x/text/internal/language/compact/tables.go
  vendor/golang.org/x/text/internal/language/lookup.go
  vendor/golang.org/x/text/internal/language/parse.go
  vendor/golang.org/x/text/internal/language/tables.go
  vendor/golang.org/x/text/internal/utf8internal/utf8internal.go
  vendor/golang.org/x/text/language/doc.go
  vendor/golang.org/x/text/language/match.go
  vendor/golang.org/x/text/language/parse.go
  vendor/golang.org/x/text/language/tables.go
  vendor/golang.org/x/text/unicode/bidi/core.go
  vendor/golang.org/x/text/unicode/norm/forminfo.go
  vendor/golang.org/x/text/unicode/norm/normalize.go
  vendor/golang.org/x/text/unicode/norm/tables13.0.0.go
  vendor/golang.org/x/text/width/tables10.0.0.go
  vendor/golang.org/x/text/width/tables11.0.0.go
  vendor/golang.org/x/text/width/tables12.0.0.go
  vendor/golang.org/x/text/width/tables13.0.0.go
  vendor/golang.org/x/text/width/tables9.0.0.go
  vendor/golang.org/x/tools/AUTHORS
  vendor/golang.org/x/tools/CONTRIBUTORS
  vendor/golang.org/x/tools/go/gcexportdata/gcexportdata.go
  vendor/golang.org/x/tools/go/gcexportdata/importer.go
  vendor/golang.org/x/tools/go/internal/gcimporter/BUILD.bazel
  vendor/golang.org/x/tools/go/internal/gcimporter/gcimporter.go
  vendor/golang.org/x/tools/go/internal/gcimporter/iimport.go
  vendor/golang.org/x/tools/go/internal/gcimporter/unified_no.go
  vendor/golang.org/x/tools/go/internal/gcimporter/unified_yes.go
  vendor/golang.org/x/tools/go/internal/gcimporter/ureader_no.go
  vendor/golang.org/x/tools/go/internal/gcimporter/ureader_yes.go
  vendor/golang.org/x/tools/go/internal/pkgbits/BUILD.bazel
  vendor/golang.org/x/tools/go/internal/pkgbits/codes.go
  vendor/golang.org/x/tools/go/internal/pkgbits/decoder.go
  vendor/golang.org/x/tools/go/internal/pkgbits/doc.go
  vendor/golang.org/x/tools/go/internal/pkgbits/encoder.go
  vendor/golang.org/x/tools/go/internal/pkgbits/flags.go
  vendor/golang.org/x/tools/go/internal/pkgbits/frames_go1.go
  vendor/golang.org/x/tools/go/internal/pkgbits/frames_go17.go
  vendor/golang.org/x/tools/go/internal/pkgbits/reloc.go
  vendor/golang.org/x/tools/go/internal/pkgbits/support.go
  vendor/golang.org/x/tools/go/internal/pkgbits/sync.go
  vendor/golang.org/x/tools/go/internal/pkgbits/syncmarker_string.go
  vendor/golang.org/x/tools/go/packages/golist.go
  vendor/golang.org/x/tools/internal/analysisinternal/BUILD.bazel
  vendor/golang.org/x/tools/internal/analysisinternal/analysis.go
  vendor/golang.org/x/tools/internal/lsp/fuzzy/BUILD.bazel
  vendor/golang.org/x/tools/internal/lsp/fuzzy/input.go
  vendor/golang.org/x/tools/internal/lsp/fuzzy/matcher.go
  vendor/golang.org/x/tools/internal/lsp/fuzzy/symbol.go
  vendor/modules.txt
Labels: size/XXL, release-note-none, lgtm, approved, dco-signoff: yes

#9207 Remove "default" from supported disk IO modes
  pkg/instancetype/instancetype_test.go
  pkg/virt-api/webhooks/validating-webhook/admitters/vmi-create-admitter.go
  staging/src/kubevirt.io/api/core/v1/types.go
Labels: size/S, release-note-none, kind/api-change, lgtm, approved, dco-signoff: yes

#9310 [e2e] Fine-tuning of the pausing test
  tests/pausing_test.go
Labels: size/S, release-note-none, lgtm, approved, dco-signoff: yes
