Repository kubevirt/kubevirt, pull requests merged in 2023-07, with the labels that each got.

#9999 Only enable expandDisksEnabled on PVC volumes
  pkg/virt-launcher/virtwrap/converter/converter.go
Labels: release-note, size/XS, lgtm, approved, ok-to-test, dco-signoff: yes

#10016 [e2e] Share KubeVirtDefaultConfig between all ginkgo nodes
  tests/testsuite/fixture.go
  tests/testsuite/runconfiguration.go
Labels: size/S, release-note-none, lgtm, approved, dco-signoff: yes

#9979 virt-controller, vm: Avoid unplugging interfaces on older running VMs
  pkg/controller/controller.go
  pkg/virt-controller/watch/application.go
  pkg/virt-controller/watch/application_test.go
  pkg/virt-controller/watch/network.go
  pkg/virt-controller/watch/network_test.go
  pkg/virt-controller/watch/vm.go
  pkg/virt-controller/watch/vm_test.go
  pkg/virt-controller/watch/vmi.go
Labels: size/L, release-note-none, lgtm, approved, dco-signoff: yes

#7708 Add `nodeSelector` and `schedulerName` options to instancetype
  api/openapi-spec/swagger.json
  pkg/instancetype/instancetype.go
  pkg/instancetype/instancetype_test.go
  pkg/virt-operator/resource/generate/components/validations_generated.go
  staging/src/kubevirt.io/api/instancetype/v1alpha1/conversion.go
  staging/src/kubevirt.io/api/instancetype/v1alpha1/conversion_generated.go
  staging/src/kubevirt.io/api/instancetype/v1alpha2/conversion.go
  staging/src/kubevirt.io/api/instancetype/v1alpha2/conversion_generated.go
  staging/src/kubevirt.io/api/instancetype/v1beta1/deepcopy_generated.go
  staging/src/kubevirt.io/api/instancetype/v1beta1/types.go
  staging/src/kubevirt.io/api/instancetype/v1beta1/types_swagger_generated.go
  staging/src/kubevirt.io/client-go/api/openapi_generated.go
Labels: size/L, release-note, kind/api-change, lgtm, approved, ok-to-test, dco-signoff: yes, area/instancetype

#9988 [virt-operator]: always deploy the outdated VMI workload alert
  hack/prom-rule-ci/rule-spec-dumper.go
  pkg/virt-operator/kubevirt_test.go
  pkg/virt-operator/resource/apply/prometheus_test.go
  pkg/virt-operator/resource/generate/components/prometheus.go
  pkg/virt-operator/resource/generate/components/prometheus_test.go
  pkg/virt-operator/resource/generate/install/strategy.go
  pkg/virt-operator/util/config.go
  tests/operator/operator.go
Labels: size/M, release-note, lgtm, approved, dco-signoff: yes, area/monitoring

#9840 Increase probability of flake check to reveal flakes
  automation/repeated_test.sh
  hack/functests.sh
Labels: size/M, release-note, lgtm, approved, dco-signoff: yes

#9896 virt-controller, VMController: Patch VMI interfaces mac address
  pkg/virt-controller/watch/network.go
  pkg/virt-controller/watch/network_test.go
  pkg/virt-controller/watch/vm.go
  tests/network/hotplug.go
Labels: size/L, sig/network, release-note, kind/api-change, lgtm, approved, dco-signoff: yes

#9962 Upgrade the golangci linter manager and removes unsupported linters
  .golangci.yml
  hack/builder/Dockerfile
  hack/dockerized
  pkg/network/namescheme/networknamescheme_test.go
  pkg/network/sriov/sriov_test.go
Labels: size/M, sig/network, release-note-none, lgtm, approved, dco-signoff: yes

#10026 Fix flaky SEV test
  tests/launchsecurity/sev.go
Labels: size/S, release-note-none, lgtm, approved, dco-signoff: yes

#10040 Add note to consider draft PR to pull request template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: size/XS, release-note-none, lgtm, approved, dco-signoff: yes

#10001 Fix kubevirt_vmi_phase_count not being created
  pkg/monitoring/vmistats/collector.go
  pkg/monitoring/vmistats/collector_test.go
Labels: size/M, release-note, lgtm, approved, dco-signoff: yes, area/monitoring

#9989 sig-scale: add perf and scale benchmarks documentation
  docs/release-v1-perf-scale-benchmarks.md
  docs/v1-perf-scale-data/vm/vm-p50-Creation-to-Running.png
  docs/v1-perf-scale-data/vm/vm-p95-Creation-to-Running.png
  docs/v1-perf-scale-data/vm/vm-patch-nodes-count.png
  docs/v1-perf-scale-data/vm/vm-patch-pods-count.png
  docs/v1-perf-scale-data/vm/vm-patch-vmis-count.png
  docs/v1-perf-scale-data/vm/vm-update-vmis-count.png
  docs/v1-perf-scale-data/vmi/vmi-p50-Creation-to-Running.png
  docs/v1-perf-scale-data/vmi/vmi-p95-Creation-to-Running.png
  docs/v1-perf-scale-data/vmi/vmi-patch-nodes-count.png
  docs/v1-perf-scale-data/vmi/vmi-patch-pods-count.png
  docs/v1-perf-scale-data/vmi/vmi-patch-vmis-count.png
  docs/v1-perf-scale-data/vmi/vmi-update-vmis-count.png
Labels: size/M, release-note, lgtm, approved, dco-signoff: yes

#10036 Fix qemu-system-* process lookup
  pkg/virt-handler/isolation/detector.go
  pkg/virt-handler/isolation/detector_test.go
  pkg/virt-handler/isolation/process.go
  pkg/virt-handler/isolation/process_test.go
  tests/realtime/BUILD.bazel
  tests/realtime/realtime.go
  tests/security_features_test.go
  tests/utils.go
  tests/vmi_configuration_test.go
Labels: size/L, release-note-none, lgtm, approved, dco-signoff: yes

#10069 Remove mediated devices from quarantine
  tests/mdev_configuration_allocation_test.go
Labels: size/XS, release-note-none, lgtm, approved, dco-signoff: yes

#10027 Fix patch api conflict
  pkg/virt-operator/resource/apply/apps.go
  tests/scale/BUILD.bazel
  tests/scale/virt-api.go
Labels: size/L, release-note-none, lgtm, approved, dco-signoff: yes

#10054 instancetype: Apply defaults before checking preference requirements
  pkg/virt-api/webhooks/validating-webhook/admitters/vms-admitter.go
  tests/instancetype_test.go
Labels: size/M, release-note-none, lgtm, approved, dco-signoff: yes, area/instancetype

#10067 Bug fix: `virtctl create clone` marshalling and replacement of `kubectl` with `kubectl virt`
  pkg/virtctl/create/clone/BUILD.bazel
  pkg/virtctl/create/clone/clone.go
  pkg/virtctl/root.go
Labels: size/S, release-note, lgtm, approved, dco-signoff: yes

#10090 [release-1.0] Fix flaky SEV test
  tests/launchsecurity/sev.go
Labels: size/S, release-note-none, lgtm, approved, dco-signoff: yes

#9967 Fix VMSnapshot + Manual RunStrategy
  pkg/storage/snapshot/snapshot.go
  pkg/storage/snapshot/snapshot_test.go
  tests/storage/snapshot.go
Labels: size/M, release-note-none, lgtm, approved, dco-signoff: yes

#10087 [Release-0.58] Fix patch api conflict
  pkg/virt-operator/resource/apply/apps.go
  tests/scale/BUILD.bazel
  tests/scale/virt-api.go
Labels: size/L, release-note-none, lgtm, approved, dco-signoff: yes

#10093 Manual bump kubevirtci with CDI 1.57
  cluster-up-sha.txt
  cluster-up/hack/common.sh
  cluster-up/version.txt
  hack/config-default.sh
  tests/storage/export.go
  tests/storage/restore.go
Labels: size/M, release-note-none, lgtm, approved, dco-signoff: yes

#9573 Cloud init: remove unused function
  pkg/cloud-init/cloud-init.go
  pkg/cloud-init/cloud-init_test.go
Labels: size/S, release-note-none, lgtm, approved, dco-signoff: yes

#10081 chore: replace `github.com/ghodss/yaml` with `sigs.k8s.io/yaml`
  go.mod
  go.sum
  pkg/virt-operator/resource/apply/BUILD.bazel
  pkg/virt-operator/resource/apply/admissionregistration_test.go
  pkg/virt-operator/resource/generate/install/BUILD.bazel
  pkg/virt-operator/resource/generate/install/strategy.go
  pkg/virt-operator/resource/generate/install/strategy_test.go
  tools/crd-validation-generator/BUILD.bazel
  tools/crd-validation-generator/validation-generator.go
  tools/perfscale-load-generator/config/BUILD.bazel
  tools/perfscale-load-generator/config/config.go
  tools/util/BUILD.bazel
  tools/util/marshaller.go
  vendor/github.com/ghodss/yaml/.gitignore
  vendor/github.com/ghodss/yaml/.travis.yml
  vendor/github.com/ghodss/yaml/BUILD.bazel
  vendor/github.com/ghodss/yaml/LICENSE
  vendor/github.com/ghodss/yaml/README.md
  vendor/github.com/ghodss/yaml/fields.go
  vendor/github.com/ghodss/yaml/yaml.go
  vendor/modules.txt
Labels: size/XXL, release-note-none, lgtm, approved, ok-to-test, dco-signoff: yes

#9902 tests: move topics from `tests/infra_test.go` into dedicated files
  nogo_config.json
  tests/BUILD.bazel
  tests/infra_test.go
  tests/infrastructure/BUILD.bazel
  tests/infrastructure/certificates.go
  tests/infrastructure/cluster-profiler.go
  tests/infrastructure/crds.go
  tests/infrastructure/downward-metrics.go
  tests/infrastructure/infrastructure.go
  tests/infrastructure/k8s-client-changes.go
  tests/infrastructure/node-labeller.go
  tests/infrastructure/prometheus.go
  tests/infrastructure/taints-and-tolerations.go
  tests/infrastructure/tls-configuration.go
  tests/infrastructure/virt-controller-leader-election.go
  tests/infrastructure/virt-handler.go
  tests/libinfra/BUILD.bazel
  tests/libinfra/certificates.go
  tests/libinfra/http.go
  tests/libinfra/leader.go
  tests/libinfra/metrics.go
  tests/libinfra/network.go
  tests/libinfra/node-labeller.go
  tests/migration_test.go
  tests/tests_suite_test.go
Labels: size/XXL, release-note-none, lgtm, approved, dco-signoff: yes, sig/code-quality

#10004 Remove request queue
  api/openapi-spec/swagger.json
  manifests/generated/operator-csv.yaml.in
  manifests/generated/rbac-operator.authorization.k8s.yaml.in
  pkg/controller/BUILD.bazel
  pkg/controller/controller.go
  pkg/virt-api/api.go
  pkg/virt-api/rest/BUILD.bazel
  pkg/virt-api/rest/interfacehotplug.go
  pkg/virt-api/rest/interfacehotplug_test.go
  pkg/virt-controller/watch/network.go
  pkg/virt-controller/watch/network_test.go
  pkg/virt-controller/watch/vm.go
  pkg/virt-controller/watch/vmi_test.go
  pkg/virt-operator/resource/generate/components/validations_generated.go
  pkg/virt-operator/resource/generate/rbac/cluster.go
  pkg/virtctl/BUILD.bazel
  pkg/virtctl/network/BUILD.bazel
  pkg/virtctl/network/dynamicifaces.go
  pkg/virtctl/network/dynamicifaces_suite_test.go
  pkg/virtctl/network/dynamicifaces_test.go
  pkg/virtctl/root.go
  staging/src/kubevirt.io/api/core/v1/deepcopy_generated.go
  staging/src/kubevirt.io/api/core/v1/types.go
  staging/src/kubevirt.io/api/core/v1/types_swagger_generated.go
  staging/src/kubevirt.io/client-go/api/openapi_generated.go
  staging/src/kubevirt.io/client-go/kubecli/generated_mock_kubevirt.go
  staging/src/kubevirt.io/client-go/kubecli/kubevirt.go
  staging/src/kubevirt.io/client-go/kubecli/vm.go
  tests/network/BUILD.bazel
  tests/network/hotplug.go
Labels: sig/network, release-note, size/XXL, kind/api-change, lgtm, approved, dco-signoff: yes

#10058 Configure error policy for disks on IO errors
  api/openapi-spec/swagger.json
  pkg/virt-api/webhooks/validating-webhook/admitters/vmi-create-admitter.go
  pkg/virt-api/webhooks/validating-webhook/admitters/vmi-create-admitter_test.go
  pkg/virt-launcher/virtwrap/api/schema.go
  pkg/virt-launcher/virtwrap/converter/BUILD.bazel
  pkg/virt-launcher/virtwrap/converter/converter.go
  pkg/virt-launcher/virtwrap/converter/converter_test.go
  pkg/virt-operator/resource/generate/components/validations_generated.go
  staging/src/kubevirt.io/api/core/v1/deepcopy_generated.go
  staging/src/kubevirt.io/api/core/v1/schema.go
  staging/src/kubevirt.io/api/core/v1/schema_swagger_generated.go
  staging/src/kubevirt.io/client-go/api/openapi_generated.go
  tests/storage/BUILD.bazel
  tests/storage/storage.go
  tests/utils.go
Labels: size/L, release-note, kind/api-change, lgtm, approved, dco-signoff: yes

#10095 [release-1.0] Backport kubevirtci bump for CDI 1.57
  cluster-up-sha.txt
  cluster-up/cluster/README_VGPU.md
  cluster-up/cluster/k3d-1.25-sriov/OWNERS
  cluster-up/cluster/k3d-1.25-sriov/README.md
  cluster-up/cluster/k3d-1.25-sriov/TROUBLESHOOTING.md
  cluster-up/cluster/k3d-1.25-sriov/config_sriov_cluster.sh
  cluster-up/cluster/k3d-1.25-sriov/provider.sh
  cluster-up/cluster/k3d-1.25-sriov/sriov-components/manifests/kustomization.yaml
  cluster-up/cluster/k3d-1.25-sriov/sriov-components/manifests/multus/kustomization.yaml
  cluster-up/cluster/k3d-1.25-sriov/sriov-components/manifests/multus/multus.yaml
  cluster-up/cluster/k3d-1.25-sriov/sriov-components/manifests/multus/patch-args.yaml
  cluster-up/cluster/k3d-1.25-sriov/sriov-components/manifests/patch-node-selector.yaml.in
  cluster-up/cluster/k3d-1.25-sriov/sriov-components/manifests/patch-sriovdp-resource-prefix.yaml.in
  cluster-up/cluster/k3d-1.25-sriov/sriov-components/manifests/sriov-cni-daemonset.yaml
  cluster-up/cluster/k3d-1.25-sriov/sriov-components/manifests/sriov-ns.yaml
  cluster-up/cluster/k3d-1.25-sriov/sriov-components/manifests/sriovdp-config.yaml.in
  cluster-up/cluster/k3d-1.25-sriov/sriov-components/manifests/sriovdp-daemonset.yaml
  cluster-up/cluster/k3d-1.25-sriov/sriov-components/sriov_components.sh
  cluster-up/cluster/k3d-1.25-sriov/sriov-node/configure_vfs.sh
  cluster-up/cluster/k3d-1.25-sriov/sriov-node/node.sh
  cluster-up/cluster/k3d-1.25-sriov/sriovdp_setup.sh
  cluster-up/cluster/k3d/check-cluster-up.sh
  cluster-up/cluster/k3d/common.sh
  cluster-up/cluster/k3d/manifests/calico.yaml
  cluster-up/cluster/k8s-provider-common.sh
  cluster-up/cluster/kind-1.27-vgpu/config_vgpu_cluster.sh
  cluster-up/cluster/kind-1.27-vgpu/conformance.json
  cluster-up/cluster/kind-1.27-vgpu/provider.sh
  cluster-up/cluster/kind-1.27-vgpu/vgpu-node/node.sh
  cluster-up/cluster/kind-1.27/README.md
  cluster-up/cluster/kind-1.27/provider.sh
  cluster-up/hack/common.sh
  cluster-up/version.txt
  hack/cluster-deploy.sh
  hack/config-default.sh
  tests/storage/export.go
  tests/storage/restore.go
Labels: size/XXL, release-note-none, lgtm, approved, dco-signoff: yes

#10102 Export create populator compatible datavolumes from VM
  pkg/storage/export/export/export.go
  pkg/storage/export/export/export_test.go
Labels: size/XS, release-note-none, lgtm, approved, dco-signoff: yes

#10100 Adapt DV GC test to disabled by default
  hack/cluster-deploy.sh
  tests/libstorage/datavolume.go
Labels: size/XS, release-note-none, lgtm, approved, dco-signoff: yes

#10106 Add BootMenu wait when starting a VM as paused
  pkg/virt-launcher/virtwrap/api/schema.go
  pkg/virt-launcher/virtwrap/converter/converter.go
  pkg/virt-launcher/virtwrap/converter/converter_test.go
Labels: size/M, release-note, lgtm, approved, dco-signoff: yes

#10091 Remove config-map warning
  pkg/virt-operator/BUILD.bazel
  pkg/virt-operator/application.go
  pkg/virt-operator/kubevirt.go
  pkg/virt-operator/kubevirt_test.go
  tests/operator/BUILD.bazel
  tests/operator/operator.go
Labels: size/L, release-note-none, lgtm, approved, dco-signoff: yes

#10108 add Oracle to the Adopters list
  ADOPTERS.md
Labels: size/XS, release-note-none, lgtm, approved, ok-to-test, dco-signoff: yes

#10063 virt-handler, VMI iface status: Fix detached interfaces status reporting
  pkg/network/setup/netstat.go
  pkg/network/setup/netstat_test.go
  pkg/network/vmispec/interface.go
  pkg/network/vmispec/interface_test.go
  pkg/virt-handler/vm.go
  pkg/virt-launcher/virtwrap/nichotplug.go
  pkg/virt-launcher/virtwrap/nichotplug_test.go
Labels: size/L, sig/network, release-note-none, lgtm, approved, dco-signoff: yes

#10097 [Kernel Boot]: Tiny fixes - typo fix, unique name for test VMIs
  pkg/virt-controller/services/template_test.go
  pkg/virt-handler/container-disk/mount.go
  tests/migration_test.go
  tests/vm_test.go
  tests/vmi_kernel_boot_test.go
  tools/vms-generator/utils/BUILD.bazel
  tools/vms-generator/utils/utils.go
Labels: size/M, release-note-none, lgtm, approved, dco-signoff: yes

#9995 [e2e]: CPU hotplug e2e fixes
  tests/hotplug/cpu.go
Labels: size/S, release-note-none, lgtm, approved, dco-signoff: yes

#10118 Change exportserver default UID to play nicer with CDI standalone PVCs
  cmd/virt-exportserver/BUILD.bazel
Labels: release-note, size/XS, lgtm, approved, kind/build-change, dco-signoff: yes

#10104 Remove leftover package PSA
  pkg/psa/BUILD.bazel
  pkg/psa/psa.go
  pkg/psa/psa_test.go
Labels: size/L, release-note-none, lgtm, approved, dco-signoff: yes

#9875 Duplicate kubelet restart test in sig-compute
  tests/network/vmi_lifecycle.go
Labels: size/M, sig/network, release-note-none, lgtm, approved, dco-signoff: yes

#9982 release: Overhaul
  docs/release-procedure.md
  docs/release.md
Labels: kind/enhancement, size/XL, release-note, lgtm, approved, dco-signoff: yes

#10076 repeated_test: Remove tests_suite_test.go from focus-file set
  automation/repeated_test.sh
Labels: size/M, release-note-none, lgtm, approved, dco-signoff: yes

#10105 Fix not reporting vcpu wait metric when value is less than 1 second
  pkg/monitoring/domainstats/prometheus/prometheus.go
Labels: size/XS, release-note-none, lgtm, approved, ok-to-test, dco-signoff: yes, area/monitoring

#10111 controller: Remove VirtualMachineInstanceTemplateSpec check
  pkg/virt-controller/watch/vm.go
Labels: size/XS, release-note-none, lgtm, approved, dco-signoff: yes

#9393 converter: Hint at the type of serial console
  api/openapi-spec/swagger.json
  pkg/virt-operator/resource/generate/components/validations_generated.go
  staging/src/kubevirt.io/api/core/v1/schema.go
  staging/src/kubevirt.io/api/core/v1/schema_swagger_generated.go
  staging/src/kubevirt.io/client-go/api/openapi_generated.go
Labels: size/M, release-note-none, kind/api-change, lgtm, approved, dco-signoff: yes

#10008 Tests instancetype: add subdomain and termination grace period
  tests/instancetype_test.go
Labels: size/XS, release-note-none, lgtm, approved, ok-to-test, dco-signoff: yes, area/instancetype

#10140 Updating link for release notes labels to new file
  docs/reviewer-guide.md
Labels: size/XS, release-note-none, lgtm, approved, dco-signoff: yes

#10116 Clear absent ifaces
  pkg/virt-controller/watch/network.go
  pkg/virt-controller/watch/network_test.go
  pkg/virt-controller/watch/vm.go
  tests/libnet/interface.go
  tests/network/hotplug.go
Labels: size/L, sig/network, release-note, lgtm, approved, dco-signoff: yes

#10141 Cleanup VMExports after tests
  tests/testsuite/namespace.go
Labels: size/XS, release-note-none, lgtm, approved, dco-signoff: yes

#10006 [follow-up] Reduce code for metrics linter
  Makefile
  go.mod
  go.sum
  pkg/monitoring/domainstats/prometheus/BUILD.bazel
  pkg/monitoring/domainstats/prometheus/prometheus_test.go
  tools/prom-metrics-collector/BUILD.bazel
  tools/prom-metrics-collector/metrics_collector.go
  vendor/github.com/kubevirt/monitoring/pkg/metrics/parser/BUILD.bazel
  vendor/github.com/kubevirt/monitoring/pkg/metrics/parser/metrics_parser.go
  vendor/github.com/prometheus/client_model/go/BUILD.bazel
  vendor/github.com/prometheus/client_model/go/metrics.pb.go
  vendor/google.golang.org/protobuf/encoding/protojson/doc.go
  vendor/google.golang.org/protobuf/encoding/protojson/well_known_types.go
  vendor/google.golang.org/protobuf/encoding/protowire/wire.go
  vendor/google.golang.org/protobuf/internal/encoding/json/decode.go
  vendor/google.golang.org/protobuf/internal/encoding/text/decode.go
  vendor/google.golang.org/protobuf/internal/encoding/text/decode_number.go
  vendor/google.golang.org/protobuf/internal/genid/descriptor_gen.go
  vendor/google.golang.org/protobuf/internal/impl/convert.go
  vendor/google.golang.org/protobuf/internal/strs/strings_unsafe.go
  vendor/google.golang.org/protobuf/internal/version/version.go
  vendor/google.golang.org/protobuf/proto/doc.go
  vendor/google.golang.org/protobuf/proto/equal.go
  vendor/google.golang.org/protobuf/reflect/protoreflect/BUILD.bazel
  vendor/google.golang.org/protobuf/reflect/protoreflect/source_gen.go
  vendor/google.golang.org/protobuf/reflect/protoreflect/value.go
  vendor/google.golang.org/protobuf/reflect/protoreflect/value_equal.go
  vendor/google.golang.org/protobuf/reflect/protoreflect/value_union.go
  vendor/google.golang.org/protobuf/reflect/protoregistry/registry.go
  vendor/google.golang.org/protobuf/types/descriptorpb/descriptor.pb.go
  vendor/google.golang.org/protobuf/types/known/anypb/any.pb.go
  vendor/google.golang.org/protobuf/types/known/durationpb/duration.pb.go
  vendor/google.golang.org/protobuf/types/known/timestamppb/timestamp.pb.go
  vendor/modules.txt
Labels: sig/network, size/XXL, release-note-none, kind/api-change, lgtm, approved, ok-to-test, kind/build-change, dco-signoff: yes, area/monitoring

#10109 ksm: Access sysfs from the host filesystem
  pkg/virt-handler/node-labeller/node_labeller.go
Labels: size/XS, release-note-none, lgtm, approved, dco-signoff: yes

#10142 [release-0.59]logs: Do not set verbosity for higher log levels
  pkg/virt-launcher/virtwrap/manager.go
Labels: size/XS, release-note-none, lgtm, approved, dco-signoff: yes

#10143 [release-1.0] Clear absent ifaces
  pkg/virt-controller/watch/network.go
  pkg/virt-controller/watch/network_test.go
  pkg/virt-controller/watch/vm.go
  tests/libnet/interface.go
  tests/network/hotplug.go
Labels: size/L, sig/network, release-note, lgtm, approved, dco-signoff: yes

#10039 fix guaranteed qos of virt-launcher pod broken when use virtiofs
  pkg/virt-controller/services/template_test.go
  pkg/virt-controller/services/virtiofs.go
Labels: size/M, release-note, lgtm, approved, ok-to-test, dco-signoff: yes

#10113 Clean up storage tests to reduce flakiness
  tests/reporter/kubernetes.go
  tests/storage/BUILD.bazel
  tests/storage/export.go
  tests/storage/snapshot.go
Labels: size/L, release-note-none, lgtm, approved, dco-signoff: yes

#9785 Add help text to the phase transition time metrics
  pkg/monitoring/perfscale/vmi-phase-transitions.go
Labels: size/XS, release-note-none, lgtm, approved, dco-signoff: yes, area/monitoring

#9932 instancetype: Label ControllerRevisions with stored object metadata
  pkg/instancetype/instancetype.go
  pkg/instancetype/instancetype_test.go
  pkg/storage/snapshot/restore.go
  pkg/storage/snapshot/snapshot_test.go
  pkg/storage/snapshot/source.go
  staging/src/kubevirt.io/api/instancetype/register.go
Labels: size/M, release-note, kind/api-change, lgtm, approved, dco-signoff: yes, area/instancetype

#10052 instancetype: Apply PreferredStorageClassName to StorageSpec if provided
  pkg/virt-api/webhooks/mutating-webhook/mutators/vm-mutator.go
  pkg/virt-api/webhooks/mutating-webhook/mutators/vm-mutator_test.go
Labels: size/M, release-note-none, lgtm, approved, dco-signoff: yes, area/instancetype

#9927 instancetype: Fix default PreferredCPUTopology value in API docs
  api/openapi-spec/swagger.json
  pkg/virt-operator/resource/generate/components/validations_generated.go
  staging/src/kubevirt.io/api/instancetype/v1alpha2/types.go
  staging/src/kubevirt.io/api/instancetype/v1alpha2/types_swagger_generated.go
  staging/src/kubevirt.io/api/instancetype/v1beta1/types.go
  staging/src/kubevirt.io/api/instancetype/v1beta1/types_swagger_generated.go
  staging/src/kubevirt.io/client-go/api/openapi_generated.go
Labels: size/S, release-note-none, kind/api-change, lgtm, approved, dco-signoff: yes, area/instancetype

#10149 [e2e] Fix FPR tests, supporting several cluster config
  tests/migration_test.go
  tests/vmidefaults_test.go
Labels: size/S, release-note-none, lgtm, approved, dco-signoff: yes

#9878 EFI: add an option to persist the nvram
  api/openapi-spec/swagger.json
  automation/repeated_test.sh
  pkg/storage/backend-storage/backend-storage.go
  pkg/virt-api/webhooks/validating-webhook/admitters/vmi-create-admitter.go
  pkg/virt-api/webhooks/validating-webhook/admitters/vmi-create-admitter_test.go
  pkg/virt-controller/services/rendervolumes.go
  pkg/virt-controller/services/template.go
  pkg/virt-launcher/virtwrap/converter/converter.go
  pkg/virt-launcher/virtwrap/converter/converter_test.go
  pkg/virt-launcher/virtwrap/manager.go
  pkg/virt-launcher/virtwrap/manager_test.go
  pkg/virt-operator/resource/generate/components/validations_generated.go
  staging/src/kubevirt.io/api/core/v1/deepcopy_generated.go
  staging/src/kubevirt.io/api/core/v1/schema.go
  staging/src/kubevirt.io/api/core/v1/schema_swagger_generated.go
  staging/src/kubevirt.io/client-go/api/openapi_generated.go
  tests/BUILD.bazel
  tests/console/console.go
  tests/console/login.go
  tests/libvmi/factory.go
  tests/testsuite/kubevirtresource.go
  tests/vm_state_test.go
  tests/vmi_tpm_test.go
Labels: size/XL, release-note, kind/api-change, lgtm, approved, dco-signoff: yes

#10160 isolation: close file when exits
  pkg/virt-handler/isolation/detector.go
Labels: size/XS, release-note-none, lgtm, approved, ok-to-test, dco-signoff: yes

#10165 Fix volume detach on hotplug attachment pod delete
  pkg/virt-controller/watch/vmi.go
  pkg/virt-launcher/virtwrap/converter/converter.go
  tests/storage/hotplug.go
Labels: size/L, release-note, lgtm, approved, dco-signoff: yes

#10169 Stop considering master nodes when finding lowest TSC frequency on the cluster
  pkg/virt-controller/watch/topology/filter.go
  pkg/virt-controller/watch/topology/filter_test.go
  pkg/virt-controller/watch/topology/hinter.go
Labels: size/M, release-note-none, lgtm, approved, dco-signoff: yes

#10070 Remove affinities label from kubevirt_vmi_cpu_affinity and use sum as value
  docs/metrics.md
  pkg/monitoring/domainstats/prometheus/prometheus.go
  pkg/monitoring/domainstats/prometheus/prometheus_test.go
  tools/prom-metrics-collector/metrics_collector.go
Labels: size/M, release-note, lgtm, approved, dco-signoff: yes, area/monitoring

#9802 instancetype: Refactor and fix inferFromVolume functional tests
  tests/instancetype_test.go
Labels: size/L, release-note-none, lgtm, approved, dco-signoff: yes, area/instancetype

#10056 Switch to bochs display for EFI VMs
  pkg/handler-launcher-com/cmd/v1/cmd.pb.go
  pkg/handler-launcher-com/cmd/v1/cmd.proto
  pkg/util/util.go
  pkg/virt-config/feature-gates.go
  pkg/virt-handler/options.go
  pkg/virt-launcher/virtwrap/converter/converter.go
  pkg/virt-launcher/virtwrap/converter/converter_test.go
  pkg/virt-launcher/virtwrap/manager.go
Labels: size/L, release-note, lgtm, approved, dco-signoff: yes

#10099 Bugfix: target virt-launcher pod hangs when migration is cancelled
  pkg/virt-launcher/BUILD.bazel
  pkg/virt-launcher/monitor.go
  tests/migration_test.go
Labels: size/M, release-note, lgtm, approved, dco-signoff: yes

#10107 Expose kubevirt_vmi_vcpu_delay_seconds_total metric.
  docs/metrics.md
  pkg/monitoring/domainstats/prometheus/prometheus.go
  pkg/monitoring/domainstats/prometheus/prometheus_test.go
  pkg/virt-launcher/virtwrap/stats/types.go
  pkg/virt-launcher/virtwrap/statsconv/converter.go
  pkg/virt-launcher/virtwrap/statsconv/util/domstats_utils.go
Labels: size/M, release-note, lgtm, approved, ok-to-test, dco-signoff: yes, area/monitoring

#10112 virt-launcher: access-credentials: Trim newlines from SSH keys in secret
  pkg/virt-launcher/virtwrap/access-credentials/access_credentials.go
  pkg/virt-launcher/virtwrap/access-credentials/access_credentials_test.go
Labels: size/M, release-note-none, lgtm, approved, dco-signoff: yes

#10020 Use CDI API for clone authorization
  go.mod
  go.sum
  manifests/generated/operator-csv.yaml.in
  manifests/generated/rbac-operator.authorization.k8s.yaml.in
  pkg/storage/types/dv.go
  pkg/storage/types/dv_test.go
  pkg/virt-api/api.go
  pkg/virt-api/webhooks/utils.go
  pkg/virt-api/webhooks/validating-webhook/admitters/BUILD.bazel
  pkg/virt-api/webhooks/validating-webhook/admitters/vms-admitter.go
  pkg/virt-api/webhooks/validating-webhook/admitters/vms-admitter_test.go
  pkg/virt-controller/watch/BUILD.bazel
  pkg/virt-controller/watch/application.go
  pkg/virt-controller/watch/application_test.go
  pkg/virt-controller/watch/vm.go
  pkg/virt-controller/watch/vm_test.go
  pkg/virt-operator/resource/generate/rbac/apiserver.go
  tests/libstorage/BUILD.bazel
  tests/libstorage/storageclass.go
  tests/libstorage/volumesnapshot.go
  tests/storage/datavolume.go
  vendor/kubevirt.io/containerized-data-importer/LICENSE
  vendor/kubevirt.io/containerized-data-importer/pkg/clone/BUILD.bazel
  vendor/kubevirt.io/containerized-data-importer/pkg/clone/auth.go
  vendor/modules.txt
Labels: release-note, size/XXL, lgtm, approved, dco-signoff: yes

#10188 bridge hotunplug, e2e flake: test may miss the stage when VMI interface Absent
  tests/network/hotplug.go
Labels: sig/network, size/XS, release-note-none, lgtm, approved, dco-signoff: yes

#10101 Fix and deprecate `machineType` in KubeVirt CR Config
  api/openapi-spec/swagger.json
  manifests/generated/kv-resource.yaml
  pkg/virt-config/configuration.go
  pkg/virt-config/configuration_test.go
  pkg/virt-config/virt-config.go
  pkg/virt-operator/resource/generate/components/validations_generated.go
  staging/src/kubevirt.io/api/core/v1/types.go
  staging/src/kubevirt.io/api/core/v1/types_swagger_generated.go
  staging/src/kubevirt.io/client-go/api/openapi_generated.go
  tests/vmi_configuration_test.go
Labels: size/M, release-note, kind/api-change, lgtm, approved, dco-signoff: yes

#10174 instancetype: Improve `PreferredInterfaceMasquerade` application
  pkg/instancetype/instancetype.go
  pkg/instancetype/instancetype_test.go
Labels: size/M, release-note-none, lgtm, approved, dco-signoff: yes, area/instancetype

#10192 [release-1.0] bridge hotunplug, e2e flake: test may miss the stage when VMI interface Absent
  tests/network/hotplug.go
Labels: sig/network, size/XS, release-note-none, lgtm, approved, dco-signoff: yes

#10197 [release-0.58] Bugfix: target virt-launcher pod hangs when migration is cancelled
  pkg/virt-launcher/BUILD.bazel
  pkg/virt-launcher/monitor.go
  tests/migration_test.go
Labels: size/M, release-note, lgtm, approved, dco-signoff: yes
