Repository kubevirt/kubevirt, pull requests merged in 2023-08, with the labels that each got.

#10133 adopters: Small hint of how to add yourself.
  ADOPTERS.md
Labels: size/XS, release-note-none, lgtm, approved, dco-signoff: yes

#10173 Move coordination/lease RBAC permissions to Roles
  manifests/generated/operator-csv.yaml.in
  manifests/generated/rbac-operator.authorization.k8s.yaml.in
  pkg/virt-operator/resource/generate/rbac/controller.go
  pkg/virt-operator/resource/generate/rbac/operator.go
Labels: size/L, release-note, lgtm, approved, dco-signoff: yes

#10198 fix ticker leak
  cmd/virt-launcher/virt-launcher.go
Labels: size/S, release-note-none, lgtm, approved, ok-to-test, dco-signoff: yes

#10137 Fix for libvirt >= 9.1.0: Support multiple watchdogs in the domain schema
  pkg/virt-launcher/virtwrap/api/deepcopy_generated.go
  pkg/virt-launcher/virtwrap/api/schema.go
  pkg/virt-launcher/virtwrap/api/schema_test.go
  pkg/virt-launcher/virtwrap/converter/converter.go
  pkg/virt-launcher/virtwrap/converter/pci-placement.go
  tests/libvmi/vmi.go
  tests/operator/operator.go
  tests/utils.go
  tests/vmi_configuration_test.go
  tests/vmi_monitoring_test.go
Labels: size/M, release-note-none, lgtm, approved, dco-signoff: yes

#10196 [e2e] Decorate hotplug tests with VMLiveUpdateFeaturesGate decorator.
  tests/decorators/decorators.go
  tests/hotplug/cpu.go
Labels: size/XS, release-note-none, lgtm, approved, dco-signoff: yes

#10138 Change kubevirt_vmi_*_usage_seconds from Gauges to Counters
  docs/metrics.md
  pkg/monitoring/domainstats/prometheus/prometheus.go
  pkg/monitoring/domainstats/prometheus/prometheus_test.go
  tests/monitoring/prometheus_utils.go
  tests/monitoring/vm_monitoring.go
Labels: size/M, release-note, lgtm, approved, dco-signoff: yes, area/monitoring

#10127 Address sig-storage flakes with in memory etcd
  pkg/storage/snapshot/snapshot_base.go
  tests/storage/snapshot.go
Labels: size/M, release-note-none, lgtm, approved, dco-signoff: yes

#10182 Stop considering nodes without `kubevirt.io/schedulable` label when finding lowest TSC frequency on the cluster
  pkg/virt-controller/watch/topology/filter.go
  pkg/virt-controller/watch/topology/filter_test.go
  pkg/virt-controller/watch/topology/hinter.go
Labels: size/L, release-note, lgtm, approved, dco-signoff: yes

#10201 [release-1.0] e2e, hotplug ifaces: Assert absent ifaces removed from spec of stopped VMs
  tests/network/hotplug.go
Labels: size/S, sig/network, release-note-none, lgtm, approved, dco-signoff: yes

#10215 [release-1.0][e2e] Decorate hotplug tests with VMLiveUpdateFeaturesGate decorator
  tests/decorators/decorators.go
  tests/hotplug/cpu.go
Labels: size/XS, release-note-none, lgtm, approved, dco-signoff: yes

#10214 fix ticker leak
  pkg/monitoring/domainstats/downwardmetrics/scraper.go
  pkg/virt-handler/retry_manager.go
  pkg/virt-launcher/monitor.go
  pkg/virt-launcher/virtwrap/agent-poller/agent_poller.go
Labels: size/XS, release-note-none, lgtm, approved, ok-to-test, dco-signoff: yes, area/monitoring

#10177 virt-operator: Remove virt-api compat code when removing resources
  pkg/virt-operator/resource/apply/reconcile.go
Labels: size/S, release-note-none, lgtm, approved, dco-signoff: yes

#10189 bazel: Move to rules_pkg extracted version of pkg_tar
  BUILD.bazel
  cmd/libguestfs/BUILD.bazel
  cmd/pr-helper/BUILD.bazel
  cmd/virt-exportserver/BUILD.bazel
  cmd/virt-handler/BUILD.bazel
  containerimages/BUILD.bazel
  images/BUILD.bazel
  images/disks-images-provider/BUILD.bazel
Labels: size/S, release-note-none, lgtm, approved, kind/build-change, dco-signoff: yes

#10187 virt-operator: Remove flavor.kubevirt.io RBAC
  manifests/generated/operator-csv.yaml.in
  manifests/generated/rbac-operator.authorization.k8s.yaml.in
  pkg/virt-operator/resource/generate/rbac/operator.go
Labels: size/M, release-note-none, lgtm, approved, dco-signoff: yes, area/instancetype

#10216 Cleanup unused code (hotplug disks)
  pkg/hotplug-disk/hotplug-disk.go
  pkg/hotplug-disk/hotplug-disk_test.go
  pkg/virt-handler/hotplug-disk/mount.go
  pkg/virt-handler/hotplug-disk/mount_test.go
Labels: size/M, release-note-none, lgtm, approved, dco-signoff: yes

#10205 [release-1.0] hotplug interface: Fixing VM with default interface bug
  pkg/controller/controller.go
  pkg/virt-controller/watch/network.go
  pkg/virt-controller/watch/network_test.go
  pkg/virt-controller/watch/vm.go
Labels: size/L, release-note, lgtm, approved, dco-signoff: yes

#10186 Fix pr leftover mount
  cmd/virt-chroot/BUILD.bazel
  cmd/virt-chroot/selinux.go
  cmd/virt-handler/virt-handler.go
  pkg/storage/reservation/pr.go
  pkg/util/util.go
  pkg/virt-handler/device-manager/socket_device.go
  pkg/virt-operator/resource/generate/components/BUILD.bazel
  pkg/virt-operator/resource/generate/components/daemonsets.go
  tests/storage/BUILD.bazel
  tests/storage/reservation.go
Labels: size/L, release-note-none, lgtm, approved, kind/build-change, dco-signoff: yes

#10235 Replace/sanitize `ps` calls in isolated emulator thread tests
  tests/utils.go
  tests/vmi_configuration_test.go
Labels: size/M, release-note-none, lgtm, approved, dco-signoff: yes

#10221 [release-0.59] Bump to go 1.19.12
  WORKSPACE
  hack/builder/Dockerfile
  hack/dockerized
Labels: size/XS, release-note-none, lgtm, approved, dco-signoff: yes

#10227 [release-1.0] infra: Bump Go to 1.19.12
  WORKSPACE
  hack/builder/Dockerfile
  hack/dockerized
Labels: size/XS, release-note-none, lgtm, approved, dco-signoff: yes

#10185 SRIOV migration based hotplug
  pkg/network/sriov/sriov.go
  pkg/network/sriov/sriov_test.go
  pkg/network/vmispec/hotplug.go
  pkg/virt-controller/watch/network.go
  pkg/virt-controller/watch/network_test.go
  pkg/virt-controller/watch/vmi.go
  pkg/virt-controller/watch/vmi_test.go
  pkg/virt-handler/vm.go
  tests/network/BUILD.bazel
  tests/network/hotplug.go
  tests/network/hotplug_bridge.go
  tests/network/hotplug_sriov.go
Labels: sig/network, release-note, size/XXL, lgtm, approved, dco-signoff: yes

#10234 tests: Run helper pod as qemu (107) user
  tests/libstorage/pvc.go
Labels: sig/storage, size/XS, release-note-none, lgtm, approved, dco-signoff: yes

#10252 [release-1.0] Fix pr leftover mount
  cmd/virt-chroot/BUILD.bazel
  cmd/virt-chroot/selinux.go
  cmd/virt-handler/virt-handler.go
  pkg/storage/reservation/pr.go
  pkg/util/util.go
  pkg/virt-handler/device-manager/socket_device.go
  pkg/virt-operator/resource/generate/components/BUILD.bazel
  pkg/virt-operator/resource/generate/components/daemonsets.go
  tests/storage/BUILD.bazel
  tests/storage/reservation.go
Labels: size/L, release-note-none, lgtm, approved, kind/build-change, dco-signoff: yes

#10241 reservation: fix user
  cmd/virt-handler/BUILD.bazel
  cmd/virt-handler/virt-handler.go
  pkg/virt-handler/device-manager/socket_device.go
  pkg/virt-operator/resource/generate/components/daemonsets.go
Labels: size/S, sig/storage, release-note-none, lgtm, approved, kind/build-change, dco-signoff: yes

#10248 Make `examples/vmi-fedora.yaml` migratable
  examples/vmi-fedora.yaml
  tools/vms-generator/utils/utils.go
Labels: size/S, release-note-none, lgtm, approved, dco-signoff: yes

#10247 Doc to enable feature gate in dev cluster and correct path
  cmd/example-hook-sidecar/README.md
  docs/getting-started.md
Labels: size/S, release-note-none, lgtm, approved, ok-to-test, dco-signoff: yes

#10124 [e2e tests]: Decorate vTPM tests with RWX FS storage requirement
  tests/decorators/decorators.go
  tests/vm_state_test.go
  tests/vmi_tpm_test.go
Labels: size/M, release-note-none, lgtm, approved, dco-signoff: yes

#10238 [e2e] Relax prometheus cr operator test
  tests/operator/operator.go
Labels: size/XS, release-note-none, lgtm, approved, dco-signoff: yes

#10254 [virt-operator] cope with misscheduled virt-handler pods
  pkg/virt-operator/util/readycheck.go
Labels: release-note, size/XS, lgtm, approved, dco-signoff: yes

#10268 Provide client-gen install instructions
  staging/src/kubevirt.io/api/README.md
Labels: size/XS, release-note-none, lgtm, approved, needs-ok-to-test, dco-signoff: yes

#10270 Fix recurring heartbeat error logs when no mdev devices are present
  pkg/virt-handler/device-manager/mediated_devices_types.go
Labels: size/XS, release-note-none, lgtm, approved, dco-signoff: yes

#10266 [release-1.0] Remove affinities label from kubevirt_vmi_cpu_affinity and use sum as value
  docs/metrics.md
  pkg/monitoring/domainstats/prometheus/prometheus.go
  pkg/monitoring/domainstats/prometheus/prometheus_test.go
  tools/prom-metrics-collector/metrics_collector.go
Labels: size/M, release-note, lgtm, approved, dco-signoff: yes, area/monitoring

#10255 virt-controller: always store evictionStrategy in Spec
  pkg/testutils/mock_config.go
  pkg/virt-api/webhooks/defaults.go
  pkg/virt-api/webhooks/mutating-webhook/mutators/vmi-mutator_test.go
  pkg/virt-config/configuration.go
Labels: size/M, release-note-none, kind/api-change, lgtm, approved, dco-signoff: yes

#10239 virt-launcher: log migration info in MB and Mbps
  pkg/virt-launcher/virtwrap/live-migration-source.go
Labels: size/S, release-note-none, lgtm, approved, dco-signoff: yes

#10274 tests: unset MachineType
  tests/vm_test.go
Labels: size/XS, release-note-none, lgtm, approved, dco-signoff: yes

#10265 [release-1.0] Fix Aggregated Discovery
  go.mod
  go.sum
  staging/src/kubevirt.io/client-go/go.mod
  staging/src/kubevirt.io/client-go/go.sum
  vendor/k8s.io/client-go/discovery/aggregated_discovery.go
  vendor/k8s.io/client-go/tools/cache/controller.go
  vendor/k8s.io/client-go/tools/cache/delta_fifo.go
  vendor/k8s.io/client-go/tools/cache/shared_informer.go
  vendor/modules.txt
Labels: size/L, release-note-none, lgtm, approved, dco-signoff: yes

#10251 Force runbooks names to equal alerts names
  tests/monitoring/monitoring.go
Labels: size/S, release-note-none, lgtm, approved, dco-signoff: yes

#10264 Fix Aggregated Discovery
  go.mod
  go.sum
  staging/src/kubevirt.io/client-go/go.mod
  staging/src/kubevirt.io/client-go/go.sum
  vendor/k8s.io/client-go/discovery/aggregated_discovery.go
  vendor/k8s.io/client-go/tools/cache/controller.go
  vendor/k8s.io/client-go/tools/cache/delta_fifo.go
  vendor/k8s.io/client-go/tools/cache/shared_informer.go
  vendor/modules.txt
Labels: size/L, release-note-none, lgtm, approved, dco-signoff: yes

#9064 network, setup: Refactor the pod networking configuration to use a declerative API (nmstate)
  Makefile
  hack/integration-test.sh
  pkg/network/driver/BUILD.bazel
  pkg/network/driver/common.go
  pkg/network/driver/ethtool/BUILD.bazel
  pkg/network/driver/ethtool/ethtool.go
  pkg/network/driver/generated_mock_common.go
  pkg/network/driver/netlink/BUILD.bazel
  pkg/network/driver/netlink/fake/BUILD.bazel
  pkg/network/driver/netlink/fake/fake.go
  pkg/network/driver/netlink/ip.go
  pkg/network/driver/netlink/link.go
  pkg/network/driver/netlink/netlink.go
  pkg/network/driver/nft/BUILD.bazel
  pkg/network/driver/nft/nft.go
  pkg/network/driver/nmstate/BUILD.bazel
  pkg/network/driver/nmstate/integration_test.go
  pkg/network/driver/nmstate/nmstate_suite_test.go
  pkg/network/driver/nmstate/spec.go
  pkg/network/driver/nmstate/spec_test.go
  pkg/network/driver/nmstate/status.go
  pkg/network/driver/nmstate/status_test.go
  pkg/network/driver/nmstate/types.go
  pkg/network/driver/procsys/BUILD.bazel
  pkg/network/driver/procsys/fake/BUILD.bazel
  pkg/network/driver/procsys/fake/fake.go
  pkg/network/driver/procsys/netip.go
  pkg/network/driver/procsys/types.go
  pkg/network/driver/virtchroot/BUILD.bazel
  pkg/network/driver/virtchroot/tap.go
  pkg/network/infraconfigurators/BUILD.bazel
  pkg/network/infraconfigurators/bridge.go
  pkg/network/infraconfigurators/bridge_test.go
  pkg/network/infraconfigurators/common.go
  pkg/network/infraconfigurators/generated_mock_common.go
  pkg/network/infraconfigurators/masquerade.go
  pkg/network/infraconfigurators/masquerade_test.go
  pkg/network/infraconfigurators/passt.go
  pkg/network/link/BUILD.bazel
  pkg/network/link/address.go
  pkg/network/netmachinery/BUILD.bazel
  pkg/network/netmachinery/ip.go
  pkg/network/setup/BUILD.bazel
  pkg/network/setup/configstate.go
  pkg/network/setup/configstate_test.go
  pkg/network/setup/masquerade/BUILD.bazel
  pkg/network/setup/masquerade/masquerade.go
  pkg/network/setup/masquerade/masquerade_suite_test.go
  pkg/network/setup/masquerade/masquerade_test.go
  pkg/network/setup/netconf.go
  pkg/network/setup/netpod.go
  pkg/network/setup/netpod_test.go
  pkg/network/setup/network.go
  pkg/network/setup/network_suite_test.go
  pkg/network/setup/network_test.go
  pkg/network/vmispec/network.go
  pkg/util/sysctl/sysctl.go
  pkg/virt-launcher/virtwrap/converter/network.go
  pkg/virt-launcher/virtwrap/manager.go
Labels: sig/network, size/XXL, release-note-none, lgtm, approved, dco-signoff: yes

#10269 [release-1.0] Backport 'Decorate vTPM tests with RWX FS storage requirement'
  tests/decorators/decorators.go
  tests/vmi_tpm_test.go
Labels: size/M, release-note-none, lgtm, approved, dco-signoff: yes

#10275 Wait for new hotplug attachment pod to be ready
  pkg/virt-controller/watch/vmi.go
  pkg/virt-controller/watch/vmi_test.go
  pkg/virt-handler/hotplug-disk/mount.go
  tests/storage/hotplug.go
Labels: size/L, release-note, lgtm, approved, dco-signoff: yes

#10271 flake-check: use stable kubevirtci provider, set 3 nodes if required
  automation/repeated_test.sh
Labels: size/L, release-note-none, lgtm, approved, dco-signoff: yes

#10287 [Release-1.0] Relax prometheus cr operator test
  tests/operator/operator.go
Labels: size/XS, release-note-none, lgtm, approved, dco-signoff: yes

#10217 [e2e] Fix migration bandwidth
  tests/migration_test.go
Labels: size/XS, release-note-none, lgtm, approved, dco-signoff: yes

#10212 Fix filter component pod in profiler
  pkg/virt-api/rest/BUILD.bazel
  pkg/virt-api/rest/profiler.go
  pkg/virt-api/rest/profiler_test.go
Labels: size/M, release-note-none, lgtm, approved, dco-signoff: yes

#10276 [release-0.59] Change kubevirt_vmi_*_usage_seconds from Gauges to Counters
  docs/metrics.md
  pkg/monitoring/domainstats/prometheus/prometheus.go
  pkg/monitoring/domainstats/prometheus/prometheus_test.go
  tests/monitoring/monitoring.go
Labels: size/M, release-note, lgtm, approved, dco-signoff: yes, area/monitoring

#10263 Using go:embed
  pkg/virt-launcher/virtwrap/BUILD.bazel
  pkg/virt-launcher/virtwrap/api/BUILD.bazel
  pkg/virt-launcher/virtwrap/api/schema_test.go
  pkg/virt-launcher/virtwrap/api/testdata/domain_arm64.xml.tmpl
  pkg/virt-launcher/virtwrap/api/testdata/domain_ppc64le.xml.tmpl
  pkg/virt-launcher/virtwrap/api/testdata/domain_x86_64.xml.tmpl
  pkg/virt-launcher/virtwrap/converter/BUILD.bazel
  pkg/virt-launcher/virtwrap/converter/converter_test.go
  pkg/virt-launcher/virtwrap/converter/testdata/domain_arm64.xml.tmpl
  pkg/virt-launcher/virtwrap/converter/testdata/domain_ppc64le.xml.tmpl
  pkg/virt-launcher/virtwrap/converter/testdata/domain_x86_64.xml.tmpl
  pkg/virt-launcher/virtwrap/converter/testdata/domain_x86_64_root.xml.tmpl
  pkg/virt-launcher/virtwrap/manager_test.go
  pkg/virt-launcher/virtwrap/testdata/migration_domain.xml
Labels: size/XXL, release-note-none, lgtm, approved, dco-signoff: yes

#10273 [release-1.0] Change kubevirt_vmi_*_usage_seconds from Gauges to Counters
  docs/metrics.md
  pkg/monitoring/domainstats/prometheus/prometheus.go
  pkg/monitoring/domainstats/prometheus/prometheus_test.go
  tests/monitoring/prometheus_utils.go
  tests/monitoring/vm_monitoring.go
Labels: size/M, release-note, lgtm, approved, dco-signoff: yes, area/monitoring

#10284 Binding plugin API
  api/openapi-spec/swagger.json
  manifests/generated/kv-resource.yaml
  pkg/instancetype/instancetype.go
  pkg/network/setup/netpod.go
  pkg/network/setup/network.go
  pkg/virt-api/webhooks/validating-webhook/admitters/network.go
  pkg/virt-api/webhooks/validating-webhook/admitters/network_test.go
  pkg/virt-api/webhooks/validating-webhook/admitters/vmi-create-admitter.go
  pkg/virt-config/feature-gates.go
  pkg/virt-controller/services/BUILD.bazel
  pkg/virt-controller/services/net_binding.go
  pkg/virt-controller/services/net_binding_test.go
  pkg/virt-controller/services/template.go
  pkg/virt-launcher/virtwrap/converter/network.go
  pkg/virt-operator/resource/generate/components/validations_generated.go
  staging/src/kubevirt.io/api/core/v1/deepcopy_generated.go
  staging/src/kubevirt.io/api/core/v1/schema.go
  staging/src/kubevirt.io/api/core/v1/schema_swagger_generated.go
  staging/src/kubevirt.io/api/core/v1/types.go
  staging/src/kubevirt.io/api/core/v1/types_swagger_generated.go
  staging/src/kubevirt.io/client-go/api/openapi_generated.go
Labels: sig/network, size/XL, release-note, kind/api-change, lgtm, approved, dco-signoff: yes

#10272 Slirp hook sidecar
  BUILD.bazel
  cmd/network-slirp-binding/BUILD.bazel
  cmd/network-slirp-binding/README.md
  cmd/network-slirp-binding/callback/BUILD.bazel
  cmd/network-slirp-binding/callback/callback.go
  cmd/network-slirp-binding/callback/callback_suite_test.go
  cmd/network-slirp-binding/callback/callback_test.go
  cmd/network-slirp-binding/dns/BUILD.bazel
  cmd/network-slirp-binding/dns/resolvconf.go
  cmd/network-slirp-binding/domain/BUILD.bazel
  cmd/network-slirp-binding/domain/domain.go
  cmd/network-slirp-binding/domain/domain_suite_test.go
  cmd/network-slirp-binding/domain/domain_test.go
  cmd/network-slirp-binding/main.go
  cmd/network-slirp-binding/server/BUILD.bazel
  cmd/network-slirp-binding/server/server.go
  hack/bazel-push-images.sh
Labels: sig/network, size/XL, release-note, kind/api-change, lgtm, approved, dco-signoff: yes

#9821 Update metric names to fit metrics naming conventions
  docs/metrics.md
  hack/prom-rule-ci/prom-rules-tests.yaml
  pkg/monitoring/domainstats/prometheus/prometheus.go
  pkg/monitoring/domainstats/prometheus/prometheus_test.go
  pkg/monitoring/migrationstats/collector.go
  pkg/virt-controller/watch/application.go
  pkg/virt-controller/watch/workload-updater/workload-updater.go
  pkg/virt-operator/application.go
  pkg/virt-operator/resource/generate/components/prometheus.go
  tests/infrastructure/prometheus.go
  tests/monitoring/vm_monitoring.go
  tools/doc-generator/doc-generator.go
  tools/prom-metrics-collector/metrics_collector.go
Labels: size/L, release-note, lgtm, approved, dco-signoff: yes, area/monitoring

#10148 Add port-forward functionalities to virtctl vmexport
  pkg/virtctl/memorydump/memorydump.go
  pkg/virtctl/memorydump/memorydump_test.go
  pkg/virtctl/utils/test_utils.go
  pkg/virtctl/vmexport/BUILD.bazel
  pkg/virtctl/vmexport/vmexport.go
  pkg/virtctl/vmexport/vmexport_test.go
  tests/storage/BUILD.bazel
  tests/storage/export.go
  tests/storage/memorydump.go
  vendor/k8s.io/kubectl/pkg/util/BUILD.bazel
  vendor/k8s.io/kubectl/pkg/util/apply.go
  vendor/k8s.io/kubectl/pkg/util/pod_port.go
  vendor/k8s.io/kubectl/pkg/util/service_port.go
  vendor/k8s.io/kubectl/pkg/util/umask.go
  vendor/k8s.io/kubectl/pkg/util/umask_windows.go
  vendor/k8s.io/kubectl/pkg/util/util.go
  vendor/modules.txt
Labels: release-note, size/XXL, lgtm, approved, dco-signoff: yes

#10307 Replacing kubevirt logo from cncf branding with kubevirt community
  README.md
Labels: size/XS, release-note-none, lgtm, approved, dco-signoff: yes

#10298 net, e2e: Skip SR-IOV hotplug if FG is disabled
  tests/network/hotplug_sriov.go
Labels: sig/network, size/XS, release-note-none, lgtm, approved, dco-signoff: yes

#10209 network: Cleaning up `vmispec`
  pkg/network/setup/netstat.go
  pkg/network/vmispec/hotplug.go
  pkg/network/vmispec/hotplug_test.go
  pkg/network/vmispec/interface.go
  pkg/virt-controller/watch/network.go
  pkg/virt-controller/watch/network_test.go
  pkg/virt-controller/watch/vm.go
  pkg/virt-handler/vm.go
  pkg/virt-launcher/virtwrap/nichotplug.go
Labels: size/L, sig/network, release-note-none, lgtm, approved, dco-signoff: yes

#10315 tests: add meaningful logs to access failures
  tests/access_test.go
Labels: size/XS, release-note-none, lgtm, approved, dco-signoff: yes

#10135 (code cleanup) Simplify validate functions in virt-api VMs admitter
  pkg/virt-api/webhooks/validating-webhook/admitters/vms-admitter.go
Labels: size/M, release-note-none, lgtm, approved, dco-signoff: yes

#10314 instancetype: Fix `PreferredUse{BiosSerial,SecureBoot}`
  pkg/instancetype/instancetype.go
  pkg/instancetype/instancetype_test.go
Labels: size/M, release-note-none, lgtm, approved, dco-signoff: yes, area/instancetype

#10017 code cleanup: Simplify virtctl VM command files
  pkg/virtctl/vm/add_volume.go
  pkg/virtctl/vm/common.go
  pkg/virtctl/vm/migrate.go
  pkg/virtctl/vm/remove_volume.go
  pkg/virtctl/vm/restart.go
  pkg/virtctl/vm/start.go
  pkg/virtctl/vm/stop.go
  pkg/virtctl/vm/vm_test.go
Labels: size/L, release-note-none, lgtm, approved, dco-signoff: yes, sig/code-quality

#10327 ADOPTERS.md: Fix OKD documentation link
  ADOPTERS.md
Labels: size/XS, release-note-none, lgtm, approved, dco-signoff: yes

#10335 PR Template: Add a (non-enforcing) checklist of items to consider for…
  .github/PULL_REQUEST_TEMPLATE.md
Labels: size/S, release-note-none, lgtm, approved, dco-signoff: yes

#10322 [bug-fix] Reference changed without changing the definition
  docs/metrics.md
  pkg/virt-controller/watch/application.go
Labels: release-note, size/XS, lgtm, approved, ok-to-test, dco-signoff: yes

#10161 Removing myself as code reviewer
  OWNERS_ALIASES
Labels: size/XS, release-note-none, lgtm, approved, dco-signoff: yes

#10246 [functest 4747]: Stabilize and parallelize post-copy related functional tests
  pkg/virt-controller/watch/migration_test.go
  tests/BUILD.bazel
  tests/migration_policy.go
  tests/migration_test.go
Labels: size/L, release-note-none, lgtm, approved, dco-signoff: yes

#10310 tests: Delete VMI prior to NFS server pod
  images/nfs-server/BUILD.bazel
  images/nfs-server/entrypoint.sh
  tests/storage/storage.go
Labels: size/M, release-note-none, lgtm, approved, dco-signoff: yes

#10336 Slirp network binding plugin: Do not duplicate slirp iface QEMU cmd args
  cmd/network-slirp-binding/domain/domain.go
  cmd/network-slirp-binding/domain/domain_test.go
Labels: size/M, release-note-none, lgtm, approved, dco-signoff: yes

#10233 fix SetGroupVersionKind function not work in kv,vm,vmi etc list inter…
  staging/src/kubevirt.io/client-go/kubecli/kv.go
  staging/src/kubevirt.io/client-go/kubecli/kv_test.go
  staging/src/kubevirt.io/client-go/kubecli/migration.go
  staging/src/kubevirt.io/client-go/kubecli/migration_test.go
  staging/src/kubevirt.io/client-go/kubecli/replicaset.go
  staging/src/kubevirt.io/client-go/kubecli/replicaset_test.go
  staging/src/kubevirt.io/client-go/kubecli/vm.go
  staging/src/kubevirt.io/client-go/kubecli/vm_test.go
  staging/src/kubevirt.io/client-go/kubecli/vmi.go
  staging/src/kubevirt.io/client-go/kubecli/vmi_test.go
  staging/src/kubevirt.io/client-go/kubecli/vmipreset.go
  staging/src/kubevirt.io/client-go/kubecli/vmipreset_test.go
Labels: size/M, release-note-none, lgtm, approved, ok-to-test, dco-signoff: yes

#10349 [virt-controller] don't count pending migrations when validating the allowed migrations limit
  pkg/util/migrations/migrations.go
  pkg/virt-controller/watch/drain/evacuation/evacuation.go
  pkg/virt-controller/watch/drain/evacuation/evacuation_test.go
  pkg/virt-controller/watch/workload-updater/workload-updater.go
  pkg/virt-controller/watch/workload-updater/workload-updater_test.go
  tests/BUILD.bazel
  tests/migration_test.go
Labels: size/M, release-note-none, lgtm, approved, dco-signoff: yes

#10357 virt-controller: fix double `time.Second` multiplication in rate limiter
  pkg/virt-controller/watch/application.go
  pkg/virt-controller/watch/migration.go
  pkg/virt-controller/watch/workload-updater/workload-updater.go
Labels: size/M, release-note-none, lgtm, approved, dco-signoff: yes
