Repository kubevirt/kubevirt, pull requests merged in 2023-05, with the labels that each got.

#9677 Fix OWNERS_ALIASES formatting
  OWNERS_ALIASES
Labels: size/L, release-note-none, do-not-merge/hold, dco-signoff: yes

#9659 Update OrphanedVirtualMachineInstances alert
  pkg/virt-operator/resource/generate/components/prometheus.go
Labels: size/XS, release-note-none, lgtm, approved, ok-to-test, dco-signoff: yes, area/monitoring

#9055 network, setup: Iterate over all networks per each step
  pkg/network/setup/BUILD.bazel
  pkg/network/setup/configstate.go
  pkg/network/setup/configstate_test.go
  pkg/network/setup/network.go
  pkg/network/setup/network_test.go
  pkg/network/setup/podnic.go
  pkg/network/setup/podnic_test.go
Labels: size/L, sig/network, release-note-none, lgtm, approved, dco-signoff: yes

#9584 instancetype: Handle VirtualMachineInstancetypeSpecRevision without APIVersion
  pkg/instancetype/BUILD.bazel
  pkg/instancetype/compatibility.go
  pkg/instancetype/compatibility_test.go
  pkg/instancetype/instancetype_test.go
Labels: size/L, release-note-none, lgtm, approved, dco-signoff: yes, area/instancetype

#8944 Add e2e tests for KubeVirtComponentExceedsRequestedCPU and KubeVirtComponentExceedsRequestedMemory alerts
  hack/prom-rule-ci/prom-rules-tests.yaml
  pkg/virt-operator/resource/generate/components/prometheus.go
  tests/monitoring/BUILD.bazel
  tests/monitoring/component_monitoring.go
  tests/monitoring/monitoring.go
  tests/monitoring/prometheus_utils.go
  tests/monitoring/scaling_utils.go
Labels: size/XL, release-note-none, lgtm, approved, dco-signoff: yes, area/monitoring

#9631 feat(virtctl): Allow to infer from specified volume in create vm
  pkg/virtctl/create/vm/vm.go
  pkg/virtctl/create/vm/vm_test.go
  tests/virtctl/create_vm.go
Labels: size/L, release-note, lgtm, approved, dco-signoff: yes

#8361 use variable to select packages to test for unit tests
  Makefile
  hack/bazel-test.sh
Labels: size/XS, release-note-none, lifecycle/rotten, lgtm, approved, dco-signoff: yes

#9684 tests/vm_test.go: Add missing matcher to Eventually
  tests/vm_test.go
Labels: size/XS, release-note-none, lgtm, approved, dco-signoff: yes

#9683 tests/vm_test.go: Set NS in virtctl expand tests
  tests/vm_test.go
Labels: size/XS, release-note-none, lgtm, approved, dco-signoff: yes

#9692 virt-controller: Remove empty util.go file
  pkg/virt-controller/watch/BUILD.bazel
  pkg/virt-controller/watch/util.go
Labels: size/S, release-note-none, lgtm, approved, dco-signoff: yes

#9335 instancetype: Add package to lint Makefile target and fix *some* issues
  Makefile
  pkg/instancetype/compatibility.go
  pkg/instancetype/compatibility_test.go
  pkg/instancetype/instancetype.go
  pkg/instancetype/instancetype_test.go
Labels: size/M, release-note-none, lgtm, approved, dco-signoff: yes, sig/code-quality, area/instancetype

#9601 Run test Custom PCI Addresses configuration in serial & disable disk expansion
  tests/vmi_configuration_test.go
Labels: size/XS, release-note-none, lgtm, approved, dco-signoff: yes

#9613 affine kvm-pit kernel thread to vcpu-0 cpumask
  pkg/virt-handler/isolation/generated_mock_isolation.go
  pkg/virt-handler/isolation/isolation.go
  pkg/virt-handler/vm.go
  tests/utils.go
  tests/vmi_configuration_test.go
Labels: size/L, release-note-none, lgtm, approved, ok-to-test, dco-signoff: yes

#9679 virt-controller, VMI: Remove unused fields
  pkg/virt-controller/watch/application.go
  pkg/virt-controller/watch/application_test.go
  pkg/virt-controller/watch/vmi.go
  pkg/virt-controller/watch/vmi_test.go
Labels: size/S, release-note-none, lgtm, approved, dco-signoff: yes

#9686 macvtap: fix ownership change of the tap interface
  pkg/virt-handler/BUILD.bazel
  pkg/virt-handler/non-root.go
Labels: size/S, release-note, lgtm, approved, dco-signoff: yes

#8293 Add KubeVirt support for Multi-Architecture Clusters
  api/openapi-spec/swagger.json
  cmd/virt-launcher/node-labeller/node-labeller.sh
  manifests/generated/kv-resource.yaml
  pkg/testutils/mock_config.go
  pkg/virt-api/webhooks/defaults.go
  pkg/virt-api/webhooks/mutating-webhook/mutators/vm-mutator.go
  pkg/virt-api/webhooks/mutating-webhook/mutators/vm-mutator_test.go
  pkg/virt-api/webhooks/mutating-webhook/mutators/vmi-mutator_test.go
  pkg/virt-api/webhooks/utils.go
  pkg/virt-api/webhooks/validating-webhook/admitters/vmi-create-admitter.go
  pkg/virt-api/webhooks/validating-webhook/admitters/vmi-create-admitter_test.go
  pkg/virt-config/configuration.go
  pkg/virt-config/configuration_test.go
  pkg/virt-config/feature-gates.go
  pkg/virt-config/virt-config.go
  pkg/virt-controller/services/nodeselectorrenderer.go
  pkg/virt-controller/services/nodeselectorrenderer_test.go
  pkg/virt-controller/services/template.go
  pkg/virt-controller/services/template_test.go
  pkg/virt-controller/watch/application.go
  pkg/virt-controller/watch/application_test.go
  pkg/virt-controller/watch/topology/hinter.go
  pkg/virt-controller/watch/topology/hinter_test.go
  pkg/virt-controller/watch/vmi_test.go
  pkg/virt-operator/kubevirt.go
  pkg/virt-operator/resource/generate/components/validations_generated.go
  pkg/virt-operator/util/config.go
  staging/src/kubevirt.io/api/core/v1/deepcopy_generated.go
  staging/src/kubevirt.io/api/core/v1/types.go
  staging/src/kubevirt.io/api/core/v1/types_swagger_generated.go
  staging/src/kubevirt.io/client-go/api/openapi_generated.go
  tests/vm_test.go
  tests/vmi_configuration_test.go
Labels: size/XL, release-note, kind/api-change, lgtm, approved, ok-to-test, dco-signoff: yes

#9706 [release-0.59] instancetype: Handle VirtualMachineInstancetypeSpecRevision without APIVersion
  pkg/instancetype/BUILD.bazel
  pkg/instancetype/compatibility.go
  pkg/instancetype/compatibility_test.go
  pkg/instancetype/instancetype_test.go
Labels: size/L, release-note-none, lgtm, approved, dco-signoff: yes

#9680 virtiofs: Remove feature gate for config volumes
  pkg/virt-api/webhooks/validating-webhook/admitters/BUILD.bazel
  pkg/virt-api/webhooks/validating-webhook/admitters/vmi-create-admitter.go
  pkg/virt-api/webhooks/validating-webhook/admitters/vmi-create-admitter_test.go
  pkg/virt-controller/services/virtiofs.go
  pkg/virtiofs/BUILD.bazel
  pkg/virtiofs/virtiofs.go
  tests/virtiofs/BUILD.bazel
  tests/virtiofs/datavolume.go
  tests/virtiofs/feature_gate.go
Labels: size/L, release-note-none, lgtm, approved, ok-to-test, dco-signoff: yes

#9705 prom-rule-ci: Relabel bind mounted test files
  hack/prom-rule-ci/verify-rules.sh
Labels: size/XS, release-note-none, lgtm, approved, dco-signoff: yes

#9676 virt-handler, net: Use ConfigState before entring virt-launcher's network namespace
  pkg/network/setup/BUILD.bazel
  pkg/network/setup/configstate.go
  pkg/network/setup/configstate_test.go
  pkg/network/setup/configstatecache.go
  pkg/network/setup/configstatecache_test.go
  pkg/network/setup/netconf.go
  pkg/network/setup/netconf_test.go
  pkg/network/setup/network.go
  pkg/network/setup/network_suite_test.go
  pkg/network/setup/network_test.go
  pkg/virt-handler/vm.go
  pkg/virt-handler/vm_test.go
Labels: sig/network, size/XL, release-note-none, lgtm, approved, dco-signoff: yes

#9719 Take tests out of quarantine
  tests/canary_upgrade_test.go
  tests/infra_test.go
Labels: size/XS, release-note-none, lgtm, approved, dco-signoff: yes

#9628 api: Move the core API storage version to `v1` and deprecate `v1alpha3`
  cmd/container-disk-v2alpha/README.md
  docs/updates.md
  manifests/generated/kv-resource.yaml
  manifests/release/demo-content.yaml.in
  staging/src/kubevirt.io/api/core/v1/BUILD.bazel
  staging/src/kubevirt.io/api/core/v1/doc.go
  staging/src/kubevirt.io/api/core/v1/register.go
  staging/src/kubevirt.io/client-go/kubecli/kv_test.go
  staging/src/kubevirt.io/client-go/kubecli/migration_test.go
  staging/src/kubevirt.io/client-go/kubecli/replicaset_test.go
  staging/src/kubevirt.io/client-go/kubecli/vm_test.go
  staging/src/kubevirt.io/client-go/kubecli/vmi_test.go
  staging/src/kubevirt.io/client-go/kubecli/vmipreset_test.go
Labels: size/M, release-note, kind/api-change, lgtm, approved, dco-signoff: yes, area/monitoring

#8874 tests: Tolerate DV being missing warning
  tests/utils.go
Labels: size/XS, release-note-none, lgtm, approved, dco-signoff: yes

#9720 Add missing env variable forwarding in Makefile
  Makefile
Labels: size/XS, release-note-none, lgtm, approved, dco-signoff: yes

#9690 [release-0.58] device manager: externally provided mediated devices should not be removed
  api/openapi-spec/swagger.json
  manifests/generated/kv-resource.yaml
  pkg/virt-config/configuration_test.go
  pkg/virt-config/feature-gates.go
  pkg/virt-config/virt-config.go
  pkg/virt-handler/device-manager/device_controller.go
  pkg/virt-handler/device-manager/mediated_devices_types.go
  pkg/virt-handler/device-manager/mediated_devices_types_test.go
  pkg/virt-handler/heartbeat/heartbeat.go
  pkg/virt-handler/heartbeat/heartbeat_test.go
  pkg/virt-operator/resource/generate/components/validations_generated.go
  staging/src/kubevirt.io/api/core/v1/deepcopy_generated.go
  staging/src/kubevirt.io/api/core/v1/types.go
  staging/src/kubevirt.io/api/core/v1/types_swagger_generated.go
  staging/src/kubevirt.io/client-go/api/openapi_generated.go
  tests/mdev_configuration_allocation_test.go
Labels: size/L, release-note-none, lgtm, approved, dco-signoff: yes

#9269 virt-controller: render hp-volume- pod should respect blockdevices
  pkg/virt-controller/services/template.go
  pkg/virt-controller/services/template_test.go
Labels: size/L, release-note, lgtm, approved, ok-to-test, dco-signoff: yes

#9721 Make build basesystem configurable
  Makefile
  docs/custom-rpms.md
  hack/rpm-deps.sh
Labels: size/M, release-note-none, lgtm, approved, dco-signoff: yes

#8914 Detect to ServiceMonitor and PrometheusRule CRD
  pkg/testutils/mock_config.go
  pkg/virt-config/configuration.go
  pkg/virt-operator/BUILD.bazel
  pkg/virt-operator/application.go
  pkg/virt-operator/application_test.go
Labels: size/L, release-note-none, lgtm, approved, ok-to-test, dco-signoff: yes

#9614 sig-scale: export the audit tool result to files in artifacts directory
  tests/performance/density.go
Labels: size/M, release-note-none, lgtm, approved, ok-to-test, dco-signoff: yes

#9729 Add /apis as unAuth enpoint
  pkg/virt-api/rest/authorizer.go
  pkg/virt-api/rest/authorizer_test.go
Labels: size/XS, release-note-none, lgtm, approved, dco-signoff: yes

#9691 [node-labeller] Labeling of nodes with ksm enabled
  pkg/virt-handler/node-labeller/BUILD.bazel
  pkg/virt-handler/node-labeller/model.go
  pkg/virt-handler/node-labeller/node_labeller.go
  pkg/virt-handler/node-labeller/node_labeller_test.go
  staging/src/kubevirt.io/api/core/v1/types.go
Labels: size/M, release-note, kind/api-change, lgtm, approved, dco-signoff: yes

#9637 virtctl create clone: minor improvements
  pkg/virtctl/create/clone/clone.go
  pkg/virtctl/create/clone/clone_test.go
  pkg/virtctl/create/instancetype/instancetype.go
Labels: size/M, release-note-none, lgtm, approved, dco-signoff: yes

#9652 Add kubevirt_number_of_vms recording rule
  docs/metrics.md
  pkg/virt-operator/resource/generate/components/BUILD.bazel
  pkg/virt-operator/resource/generate/components/prometheus.go
  tests/monitoring/prometheus_utils.go
  tests/monitoring/vm_monitoring.go
  tools/doc-generator/BUILD.bazel
  tools/doc-generator/doc-generator.go
Labels: release-note, size/XXL, lgtm, approved, dco-signoff: yes, area/monitoring

#9746 api, virt-launcher: Reserve domain resources for network interfaces
  pkg/apimachinery/resource/BUILD.bazel
  pkg/apimachinery/resource/extend.go
  pkg/virt-api/webhooks/validating-webhook/admitters/BUILD.bazel
  pkg/virt-api/webhooks/validating-webhook/admitters/network.go
  pkg/virt-api/webhooks/validating-webhook/admitters/network_test.go
  pkg/virt-api/webhooks/validating-webhook/admitters/vmi-create-admitter.go
  pkg/virt-controller/services/BUILD.bazel
  pkg/virt-controller/services/renderresources.go
  pkg/virt-controller/services/renderresources_test.go
  pkg/virt-controller/services/template.go
  pkg/virt-launcher/virtwrap/BUILD.bazel
  pkg/virt-launcher/virtwrap/manager.go
  pkg/virt-launcher/virtwrap/nichotplug.go
  pkg/virt-launcher/virtwrap/nichotplug_test.go
  tests/libvmi/BUILD.bazel
  tests/libvmi/network.go
  tests/network/hotplug.go
Labels: size/L, sig/network, release-note, lgtm, approved, dco-signoff: yes

#9694 Fix flaky VM snapshot test
  pkg/storage/snapshot/snapshot_test.go
Labels: size/S, release-note-none, lgtm, approved, dco-signoff: yes

#9662 Make createHostDevices logs more compact
  pkg/virt-launcher/virtwrap/device/hostdevice/hostdev.go
Labels: size/S, release-note-none, lgtm, approved, ok-to-test, dco-signoff: yes

#9667 persistent reservation address left comments
  pkg/virt-handler/device-manager/BUILD.bazel
  pkg/virt-handler/device-manager/socket_device.go
  pkg/virt-handler/device-manager/socket_device_test.go
  tests/storage/reservation.go
Labels: size/L, release-note-none, lgtm, approved, dco-signoff: yes

#9763 network/setup: Use the logical network name for configstate cache keys
  pkg/network/cache/podinterface.go
  pkg/network/setup/BUILD.bazel
  pkg/network/setup/configstate.go
  pkg/network/setup/configstate_test.go
  pkg/network/setup/configstatecache.go
  pkg/network/setup/netconf.go
  pkg/network/setup/podnic.go
Labels: size/L, sig/network, release-note-none, lgtm, approved, dco-signoff: yes

#9772 Follow up on PR#9746 comments
  pkg/virt-api/webhooks/validating-webhook/admitters/network.go
  pkg/virt-api/webhooks/validating-webhook/admitters/network_test.go
  pkg/virt-launcher/virtwrap/converter/converter.go
  pkg/virt-launcher/virtwrap/converter/converter_test.go
  pkg/virt-launcher/virtwrap/converter/network.go
  pkg/virt-launcher/virtwrap/nichotplug.go
  pkg/virt-launcher/virtwrap/nichotplug_test.go
  tests/libvmi/network.go
Labels: size/M, release-note-none, lgtm, approved, dco-signoff: yes

#9268 Non-ordinal pod network interfaces name scheme
  pkg/network/infraconfigurators/bridge.go
  pkg/network/infraconfigurators/bridge_test.go
  pkg/network/infraconfigurators/masquerade.go
  pkg/network/infraconfigurators/masquerade_test.go
  pkg/network/link/BUILD.bazel
  pkg/network/link/discovery.go
  pkg/network/link/discovery_test.go
  pkg/network/link/names.go
  pkg/network/link/names_test.go
  pkg/network/namescheme/BUILD.bazel
  pkg/network/namescheme/networknamescheme.go
  pkg/network/namescheme/networknamescheme_test.go
  pkg/network/setup/BUILD.bazel
  pkg/network/setup/netconf.go
  pkg/network/setup/network.go
  pkg/network/setup/network_test.go
  pkg/network/setup/podnic.go
  pkg/network/setup/podnic_test.go
  pkg/network/sriov/sriov.go
  pkg/network/sriov/sriov_test.go
  pkg/virt-controller/services/multus_annotations.go
  pkg/virt-controller/services/template.go
  pkg/virt-controller/services/template_test.go
  pkg/virt-controller/watch/vmi.go
  pkg/virt-controller/watch/vmi_test.go
  pkg/virt-handler/BUILD.bazel
  pkg/virt-handler/non-root.go
  pkg/virt-handler/non-root_test.go
  tests/network/vmi_multus.go
Labels: sig/network, release-note, size/XXL, lgtm, approved, dco-signoff: yes

#9747 docs: Add upgrade note regarding v1 storage version migration
  docs/updates.md
Labels: size/S, release-note-action-required, lgtm, approved, dco-signoff: yes

#9752 Avoid "resourceVersion too old" warnings in fstrim tests
  tests/storage/datavolume.go
Labels: size/XS, release-note-none, lgtm, approved, dco-signoff: yes

#9782 builder: Workaround podman bug during manifest push
  hack/builder/publish.sh
Labels: size/XS, release-note-none, lgtm, approved, dco-signoff: yes

#9781 [release-0.58] affine kvm-pit kernel thread to vcpu-0 cpumask
  pkg/virt-handler/isolation/generated_mock_isolation.go
  pkg/virt-handler/isolation/isolation.go
  pkg/virt-handler/vm.go
  tests/utils.go
  tests/vmi_configuration_test.go
Labels: size/L, release-note-none, lgtm, approved, dco-signoff: yes

#9786 e2e: Remove events in the namespace after each test
  tests/testsuite/namespace.go
Labels: size/XS, release-note-none, lgtm, approved, dco-signoff: yes

#9724 monitoring: Add KubeVirtDeprecatedAPIsRequested alert
  docs/metrics.md
  hack/prom-rule-ci/prom-rules-tests.yaml
  hack/prom-rule-ci/verify-rules.sh
  pkg/virt-operator/resource/generate/components/prometheus.go
  tests/monitoring/monitoring.go
  tests/monitoring/prometheus_utils.go
Labels: size/M, release-note, lgtm, approved, dco-signoff: yes, area/monitoring

#9674 Add VirtualMachineOptions to KV configuration
  api/openapi-spec/swagger.json
  manifests/generated/kv-resource.yaml
  pkg/handler-launcher-com/cmd/v1/cmd.pb.go
  pkg/handler-launcher-com/cmd/v1/cmd.proto
  pkg/virt-config/configuration_test.go
  pkg/virt-config/virt-config.go
  pkg/virt-handler/options.go
  pkg/virt-handler/vm.go
  pkg/virt-launcher/virtwrap/BUILD.bazel
  pkg/virt-launcher/virtwrap/converter/converter_test.go
  pkg/virt-launcher/virtwrap/manager.go
  pkg/virt-launcher/virtwrap/manager_test.go
  pkg/virt-operator/resource/generate/components/validations_generated.go
  staging/src/kubevirt.io/api/core/v1/deepcopy_generated.go
  staging/src/kubevirt.io/api/core/v1/types.go
  staging/src/kubevirt.io/api/core/v1/types_swagger_generated.go
  staging/src/kubevirt.io/client-go/api/openapi_generated.go
  tests/migration_test.go
Labels: size/XL, release-note, kind/api-change, lgtm, approved, dco-signoff: yes

#9793 virt-controller, migration: Remove unused fields
  pkg/virt-controller/watch/application.go
  pkg/virt-controller/watch/application_test.go
  pkg/virt-controller/watch/migration.go
  pkg/virt-controller/watch/migration_test.go
Labels: size/S, release-note-none, lgtm, approved, dco-signoff: yes

#9695 Chore: Remove unused functions in unit test
  pkg/virt-operator/webhooks/kubevirt-update-admitter_test.go
Labels: size/S, release-note-none, lgtm, approved, dco-signoff: yes

#9767 Positional changes around the Kubevirt logo in the README.md file
  README.md
Labels: size/S, release-note-none, lgtm, approved, ok-to-test, dco-signoff: yes

#9789 builder: Create KubeVirt source directory and mark it as safe for git
  hack/builder/Dockerfile
Labels: size/XS, release-note-none, lgtm, approved, dco-signoff: yes

#9813 dockerized: Update builder image
  hack/dockerized
Labels: size/XS, release-note-none, lgtm, approved, dco-signoff: yes

#9730 Add vmi cached memory metric
  docs/metrics.md
  pkg/monitoring/domainstats/prometheus/prometheus.go
  pkg/monitoring/domainstats/prometheus/prometheus_test.go
  pkg/virt-launcher/virtwrap/stats/types.go
  pkg/virt-launcher/virtwrap/statsconv/converter.go
  pkg/virt-launcher/virtwrap/statsconv/util/domstats_utils.go
  tools/doc-generator/fakeDomainCollector.go
Labels: size/M, release-note, lgtm, approved, dco-signoff: yes, area/monitoring

#9738 [Migration-Controller]Indicate resource quota rejection
  manifests/generated/operator-csv.yaml.in
  manifests/generated/rbac-operator.authorization.k8s.yaml.in
  pkg/controller/virtinformers.go
  pkg/virt-controller/watch/application.go
  pkg/virt-controller/watch/application_test.go
  pkg/virt-controller/watch/migration.go
  pkg/virt-controller/watch/migration_test.go
  pkg/virt-operator/resource/generate/rbac/controller.go
  staging/src/kubevirt.io/api/core/v1/types.go
  tests/migration_test.go
  tests/testsuite/namespace.go
Labels: size/L, sig/network, release-note, kind/api-change, lgtm, approved, dco-signoff: yes

#9817 [release-0.58] [virt-controller] fix out-of-bound slice index in evacuation controller
  pkg/virt-controller/watch/drain/evacuation/evacuation.go
  pkg/virt-controller/watch/drain/evacuation/evacuation_test.go
Labels: size/M, release-note, lgtm, approved, dco-signoff: yes

#9803 Quarantine test [Serial][sig-operator]Operator Obsolete ConfigMap sho…
  tests/operator/operator.go
Labels: size/XS, release-note-none, lgtm, approved, dco-signoff: yes

#9023 Virt-api, Arm64: Add error message for watchdog and sound device on Arm64
  pkg/virt-api/webhooks/arm64.go
  pkg/virt-api/webhooks/validating-webhook/admitters/vmi-create-admitter_test.go
Labels: size/L, release-note-none, lgtm, approved, dco-signoff: yes

#9753 virtctl: Add default instance type support on image-upload
  pkg/virtctl/imageupload/BUILD.bazel
  pkg/virtctl/imageupload/imageupload.go
  pkg/virtctl/imageupload/imageupload_test.go
Labels: size/L, release-note, lgtm, approved, dco-signoff: yes, area/instancetype

#9764 Add ksmConfiguration to enable ksm in the nodes
  api/openapi-spec/swagger.json
  manifests/generated/kv-resource.yaml
  pkg/virt-config/virt-config.go
  pkg/virt-handler/node-labeller/BUILD.bazel
  pkg/virt-handler/node-labeller/model.go
  pkg/virt-handler/node-labeller/node_labeller.go
  pkg/virt-handler/node-labeller/node_labeller_test.go
  pkg/virt-operator/resource/generate/components/validations_generated.go
  staging/src/kubevirt.io/api/core/v1/deepcopy_generated.go
  staging/src/kubevirt.io/api/core/v1/types.go
  staging/src/kubevirt.io/api/core/v1/types_swagger_generated.go
  staging/src/kubevirt.io/client-go/api/openapi_generated.go
  tests/decorators/decorators.go
  tests/infra_test.go
Labels: size/XL, release-note, kind/api-change, lgtm, approved, kind/build-change, dco-signoff: yes

#9807 Quarantine test_id:4023 VirtualMachineInstance with CPU pinning with cpu pinning enabled should start a vmi with dedicated cpus and isolated emulator thread with explicit resources set
  tests/vmi_configuration_test.go
Labels: size/XS, release-note-none, lgtm, approved, dco-signoff: yes

#9798 Add LiveMigrateIfPossible eviction strategy
  pkg/util/migrations/migrations.go
  pkg/virt-api/webhooks/validating-webhook/admitters/pod-eviction-admitter.go
  pkg/virt-api/webhooks/validating-webhook/admitters/pod-eviction-admitter_test.go
  pkg/virt-api/webhooks/validating-webhook/admitters/vmi-create-admitter.go
  pkg/virt-api/webhooks/validating-webhook/admitters/vmi-create-admitter_test.go
  pkg/virt-controller/watch/drain/disruptionbudget/disruptionbudget.go
  pkg/virt-controller/watch/drain/disruptionbudget/disruptionbudget_test.go
  staging/src/kubevirt.io/api/core/v1/types.go
  tests/framework/matcher/BUILD.bazel
  tests/framework/matcher/getter.go
  tests/migration_test.go
  tests/vmi_lifecycle_test.go
Labels: size/L, release-note, kind/api-change, lgtm, approved, dco-signoff: yes

#9723 instancetype: Move PreferredCPUTopology to a string pointer
  pkg/instancetype/compatibility_test.go
  pkg/instancetype/instancetype.go
  pkg/instancetype/instancetype_test.go
  pkg/storage/snapshot/snapshot_test.go
  pkg/virtctl/create/preference/preference.go
  pkg/virtctl/create/preference/preference_test.go
  staging/src/kubevirt.io/api/instancetype/v1alpha1/conversion.go
  staging/src/kubevirt.io/api/instancetype/v1alpha1/conversion_generated.go
  staging/src/kubevirt.io/api/instancetype/v1alpha2/BUILD.bazel
  staging/src/kubevirt.io/api/instancetype/v1alpha2/conversion.go
  staging/src/kubevirt.io/api/instancetype/v1alpha2/conversion_generated.go
  staging/src/kubevirt.io/api/instancetype/v1beta1/deepcopy_generated.go
  staging/src/kubevirt.io/api/instancetype/v1beta1/types.go
  tests/clone_test.go
  tests/instancetype_test.go
  tests/storage/restore.go
  tests/virtctl/create_preference.go
  tests/virtctl/create_vm.go
  tools/vms-generator/utils/utils.go
Labels: size/L, release-note-none, kind/api-change, lgtm, approved, dco-signoff: yes, area/monitoring, area/instancetype
