Repository kubevirt/kubevirt, pull requests merged in 2023-04, with the labels that each got.

#9290 Indication of when target pod hosts active qemu instance during live migration
  api/openapi-spec/swagger.json
  pkg/virt-controller/watch/migration.go
  pkg/virt-controller/watch/migration_test.go
  pkg/virt-handler/vm.go
  pkg/virt-handler/vm_test.go
  pkg/virt-launcher/notify-client/client.go
  pkg/virt-operator/resource/generate/components/validations_generated.go
  staging/src/kubevirt.io/api/core/v1/deepcopy_generated.go
  staging/src/kubevirt.io/api/core/v1/types.go
  staging/src/kubevirt.io/api/core/v1/types_swagger_generated.go
  staging/src/kubevirt.io/client-go/api/openapi_generated.go
  tests/migration.go
Labels: size/L, release-note-none, kind/api-change, lgtm, approved, dco-signoff: yes

#9556 [release-0.57] tests, console: Prevent NewExpecter negative timeout scenario
  tests/console/console.go
Labels: size/S, release-note-none, lgtm, approved, dco-signoff: yes

#9534 [release-0.59] webhooks: Return early when VirtualMachine is being deleted
  pkg/instancetype/instancetype_test.go
  pkg/storage/export/virt-exportserver/exportserver_test.go
  pkg/virt-api/webhooks/mutating-webhook/mutators/vm-mutator.go
  pkg/virt-api/webhooks/mutating-webhook/mutators/vm-mutator_test.go
  pkg/virt-api/webhooks/validating-webhook/admitters/vmi-create-admitter_test.go
  pkg/virt-api/webhooks/validating-webhook/admitters/vms-admitter.go
  pkg/virt-api/webhooks/validating-webhook/admitters/vms-admitter_test.go
  tests/vm_test.go
Labels: size/L, release-note-none, kind/api-change, lgtm, approved, dco-signoff: yes, area/instancetype

#9560 [release-0.53] tests, console: Prevent NewExpecter negative timeout scenario
  tests/console/console.go
Labels: size/S, release-note-none, lgtm, approved, dco-signoff: yes

#9407 Use env `RUNBOOK_URL_TEMPLATE` for the runbooks URL template
  hack/build-manifests.sh
  hack/manifests.sh
  hack/prom-rule-ci/prom-rules-tests.yaml
  pkg/virt-operator/resource/generate/components/BUILD.bazel
  pkg/virt-operator/resource/generate/components/deployments.go
  pkg/virt-operator/resource/generate/components/prometheus.go
  pkg/virt-operator/resource/generate/components/prometheus_test.go
  pkg/virt-operator/resource/generate/csv/csv.go
  pkg/virt-operator/util/config.go
  tests/monitoring/monitoring.go
  tools/csv-generator/csv-generator.go
  tools/manifest-templator/manifest-templator.go
Labels: size/L, release-note, lgtm, approved, ok-to-test, dco-signoff: yes, area/monitoring

#9470 Enable libvirt GetDomainStats on paused VMs
  pkg/virt-launcher/virtwrap/manager.go
  pkg/virt-launcher/virtwrap/manager_test.go
  tests/monitoring/BUILD.bazel
  tests/monitoring/monitoring.go
  tests/monitoring/prometheus_utils.go
  tests/monitoring/vm_monitoring.go
Labels: size/L, release-note, lgtm, approved, dco-signoff: yes

#9177 SCSI persistent reservation with device plugin
  BUILD.bazel
  WORKSPACE
  api/openapi-spec/swagger.json
  cmd/pr-helper/BUILD.bazel
  cmd/pr-helper/multipath.conf
  cmd/virt-handler/BUILD.bazel
  cmd/virt-handler/virt-handler.go
  hack/bazel-build-images.sh
  hack/bazel-push-images.sh
  hack/bootstrap.sh
  hack/build-manifests.sh
  hack/cluster-patch.sh
  hack/generate.sh
  hack/parse-shasums.sh
  hack/rpm-deps.sh
  manifests/generated/operator-csv.yaml.in
  pkg/storage/reservation/BUILD.bazel
  pkg/storage/reservation/pr.go
  pkg/testutils/mock_config.go
  pkg/virt-api/webhooks/validating-webhook/admitters/BUILD.bazel
  pkg/virt-api/webhooks/validating-webhook/admitters/vmi-create-admitter.go
  pkg/virt-api/webhooks/validating-webhook/admitters/vmi-create-admitter_test.go
  pkg/virt-config/feature-gates.go
  pkg/virt-controller/services/BUILD.bazel
  pkg/virt-controller/services/renderresources.go
  pkg/virt-controller/services/template.go
  pkg/virt-handler/BUILD.bazel
  pkg/virt-handler/device-manager/BUILD.bazel
  pkg/virt-handler/device-manager/device_controller.go
  pkg/virt-handler/device-manager/socket_device.go
  pkg/virt-handler/vm.go
  pkg/virt-handler/vm_test.go
  pkg/virt-launcher/virtwrap/api/deepcopy_generated.go
  pkg/virt-launcher/virtwrap/api/schema.go
  pkg/virt-launcher/virtwrap/converter/BUILD.bazel
  pkg/virt-launcher/virtwrap/converter/converter.go
  pkg/virt-launcher/virtwrap/converter/converter_test.go
  pkg/virt-operator/resource/generate/components/BUILD.bazel
  pkg/virt-operator/resource/generate/components/daemonsets.go
  pkg/virt-operator/resource/generate/components/deployments.go
  pkg/virt-operator/resource/generate/components/validations_generated.go
  pkg/virt-operator/resource/generate/csv/csv.go
  pkg/virt-operator/resource/generate/install/strategy.go
  pkg/virt-operator/util/BUILD.bazel
  pkg/virt-operator/util/config.go
  rpm/BUILD.bazel
  staging/src/kubevirt.io/api/core/v1/schema.go
  staging/src/kubevirt.io/api/core/v1/schema_swagger_generated.go
  staging/src/kubevirt.io/api/core/v1/types.go
  staging/src/kubevirt.io/client-go/api/openapi_generated.go
  tests/framework/checks/checks.go
  tests/libvmi/storage.go
  tests/storage/BUILD.bazel
  tests/storage/reservation.go
  tests/utils.go
  tools/csv-generator/csv-generator.go
  tools/manifest-templator/manifest-templator.go
  tools/util/marshaller_test.go
Labels: release-note, size/XXL, kind/api-change, lgtm, approved, kind/build-change, dco-signoff: yes

#9547 Add e2e tests for low count alerts
  automation/test.sh
  tests/decorators/decorators.go
  tests/monitoring/monitoring.go
Labels: size/M, release-note-none, lgtm, approved, dco-signoff: yes

#9432 Sharing all config volumes using virtiofs
  pkg/virt-controller/services/rendervolumes.go
  pkg/virt-controller/services/rendervolumes_test.go
  pkg/virt-controller/services/template.go
  pkg/virt-controller/services/virtiofs.go
  pkg/virt-handler/BUILD.bazel
  pkg/virt-handler/vm.go
  pkg/virt-launcher/virtwrap/converter/BUILD.bazel
  pkg/virt-launcher/virtwrap/converter/virtiofs.go
  tests/BUILD.bazel
  tests/config_test.go
  tests/libvmi/BUILD.bazel
  tests/libvmi/config.go
  tests/libvmi/storage.go
  tests/storage/storage.go
  tests/tests_suite_test.go
  tests/virtiofs/BUILD.bazel
  tests/virtiofs/config.go
  tests/virtiofs/datavolume.go
Labels: size/XXL, release-note-none, lgtm, approved, ok-to-test, dco-signoff: yes

#9176 [export tests]: Increase timeout for bound PVC
  tests/storage/export.go
Labels: size/XS, release-note-none, lgtm, approved, dco-signoff: yes

#9536 Remove "all" category from virtualmachineclusterinstancetypes/preferences
  pkg/virt-operator/resource/generate/components/crds.go
Labels: release-note, size/XS, lgtm, approved, dco-signoff: yes, area/instancetype

#9564 [virt-operator]: fix kubevirt version parsing
  pkg/virt-operator/util/config.go
  pkg/virt-operator/util/config_test.go
Labels: size/M, release-note-none, lgtm, approved, dco-signoff: yes

#9422 Look up request/limits for cpu/mem from kubevirt CR for supporting containers
  api/openapi-spec/swagger.json
  manifests/generated/kv-resource.yaml
  pkg/container-disk/BUILD.bazel
  pkg/container-disk/container-disk.go
  pkg/container-disk/container-disk_test.go
  pkg/virt-config/virt-config.go
  pkg/virt-controller/services/renderresources.go
  pkg/virt-controller/services/renderresources_test.go
  pkg/virt-controller/services/template.go
  pkg/virt-controller/services/template_test.go
  pkg/virt-controller/services/virtiofs.go
  pkg/virt-operator/resource/generate/components/validations_generated.go
  staging/src/kubevirt.io/api/core/v1/deepcopy_generated.go
  staging/src/kubevirt.io/api/core/v1/types.go
  staging/src/kubevirt.io/api/core/v1/types_swagger_generated.go
  staging/src/kubevirt.io/client-go/api/openapi_generated.go
  tests/storage/hotplug.go
  tests/storage/storage.go
  tests/vmi_hook_sidecar_test.go
Labels: release-note, size/XXL, kind/api-change, lgtm, approved, dco-signoff: yes

#9583 [release-0.59] virt-operator: fix kubevirt version parsing
  pkg/virt-operator/util/config.go
  pkg/virt-operator/util/config_test.go
Labels: size/M, release-note-none, lgtm, approved, dco-signoff: yes

#9596 Add "virtctl create clone" command
  pkg/virtctl/create/BUILD.bazel
  pkg/virtctl/create/clone/BUILD.bazel
  pkg/virtctl/create/clone/clone.go
  pkg/virtctl/create/clone/clone_suite_test.go
  pkg/virtctl/create/clone/clone_test.go
  pkg/virtctl/create/create.go
  pkg/virtctl/create/instancetype/instancetype.go
  pkg/virtctl/create/params/params.go
  pkg/virtctl/create/vm/vm.go
Labels: size/XL, release-note, lgtm, approved, dco-signoff: yes

#9548 [release-0.53] Remove hostname limitation for migrations
  pkg/virt-controller/watch/migration.go
  tests/BUILD.bazel
  tests/migration_test.go
Labels: size/M, release-note, lgtm, approved, dco-signoff: yes

#9546 [release-0.58] Remove hostname limitation for migrations
  pkg/virt-controller/watch/migration.go
  tests/BUILD.bazel
  tests/migration_test.go
Labels: size/M, release-note, lgtm, approved, dco-signoff: yes

#9599 [Refactor] Use ambient capabilities for the virt-launcher binary
  cmd/virt-launcher-monitor/BUILD.bazel
  cmd/virt-launcher-monitor/virt-launcher-monitor.go
  cmd/virt-launcher/BUILD.bazel
Labels: size/XS, release-note-none, lgtm, approved, ok-to-test, kind/build-change, dco-signoff: yes

#9591 Improve mountinfo filtering for hotplugging NFS disks
  pkg/virt-handler/hotplug-disk/mount.go
  pkg/virt-handler/isolation/isolation.go
  pkg/virt-handler/isolation/isolation_test.go
Labels: size/L, release-note, lgtm, approved, dco-signoff: yes

#9603 node-labeller: Remove pipefail to fix non kvm envs
  cmd/virt-launcher/node-labeller/node-labeller.sh
Labels: kind/bug, release-note, size/XS, lgtm, approved, dco-signoff: yes

#9229 Move away from fedora 31 and use distroless/base instead
  WORKSPACE
  cmd/example-cloudinit-hook-sidecar/BUILD.bazel
  cmd/example-disk-mutation-hook-sidecar/BUILD.bazel
  cmd/example-hook-sidecar/BUILD.bazel
  images/winrmcli/BUILD.bazel
  tests/BUILD.bazel
Labels: size/M, release-note-none, lgtm, approved, dco-signoff: yes

#8575 QEMU-level migration parallelism (a.k.a. multifd) + Upgrade QEMU to 7.2.0-14.el9
  WORKSPACE
  hack/bootstrap.sh
  hack/rpm-deps.sh
  pkg/virt-api/webhooks/validating-webhook/admitters/BUILD.bazel
  pkg/virt-api/webhooks/validating-webhook/admitters/vmi-create-admitter.go
  pkg/virt-api/webhooks/validating-webhook/admitters/vmi-create-admitter_test.go
  pkg/virt-handler/BUILD.bazel
  pkg/virt-handler/cmd-client/client.go
  pkg/virt-handler/vm.go
  pkg/virt-handler/vm_test.go
  pkg/virt-launcher/virtwrap/live-migration-source.go
  pkg/virt-launcher/virtwrap/manager_test.go
  rpm/BUILD.bazel
  tests/BUILD.bazel
  tests/migration_test.go
Labels: release-note, size/XXL, kind/api-change, lgtm, approved, dco-signoff: yes

#8990 Add e2e tests for REST errors high alerts
  tests/monitoring/monitoring.go
Labels: size/M, release-note-none, lgtm, approved, dco-signoff: yes

#9526 [release-0.59] instancetype: Handle DataVolumeSourceRef without namespace when inferring defaults
  pkg/instancetype/instancetype.go
  pkg/virt-api/webhooks/mutating-webhook/mutators/vm-mutator_test.go
  tests/instancetype_test.go
Labels: size/L, release-note-none, lgtm, approved, dco-signoff: yes, area/instancetype

#9619 [LimitRange tests]: Fix cleanup of LimitRange
  tests/storage/hotplug.go
  tests/storage/imageupload.go
Labels: size/M, release-note-none, lgtm, approved, dco-signoff: yes

#8574 virt-api: Cleanup API and improve authentication required checks
  api/openapi-spec/swagger.json
  pkg/virt-api/api.go
  pkg/virt-api/api_test.go
  pkg/virt-api/rest/authorizer.go
  pkg/virt-api/rest/authorizer_test.go
Labels: size/L, release-note-none, lgtm, approved, dco-signoff: yes, sig/code-quality

#9606 Add: Kasten by Veeam - K10 to Integrations
  ADOPTERS.md
Labels: size/XS, release-note-none, lgtm, approved, ok-to-test, dco-signoff: yes

#9604 builder: Build and publish image using shared version
  hack/builder/arch.sh
  hack/builder/build.sh
  hack/builder/publish.sh
  hack/builder/version.sh
Labels: size/S, release-note-none, lgtm, approved, dco-signoff: yes

#9627 [release-0.53] Manual backport - Fix cleanup of LimitRange
  tests/storage/hotplug.go
Labels: size/XS, release-note-none, lgtm, approved, dco-signoff: yes

#8156 Add VMI backend storage and persistent TPM support
  api/openapi-spec/swagger.json
  manifests/generated/kv-resource.yaml
  pkg/storage/backend-storage/BUILD.bazel
  pkg/storage/backend-storage/backend-storage.go
  pkg/virt-api/webhooks/validating-webhook/admitters/BUILD.bazel
  pkg/virt-api/webhooks/validating-webhook/admitters/vmi-create-admitter.go
  pkg/virt-api/webhooks/validating-webhook/admitters/vmi-create-admitter_test.go
  pkg/virt-api/webhooks/validating-webhook/admitters/vmsnapshot-admitter.go
  pkg/virt-api/webhooks/validating-webhook/admitters/vmsnapshot-admitter_test.go
  pkg/virt-config/feature-gates.go
  pkg/virt-config/virt-config.go
  pkg/virt-controller/services/BUILD.bazel
  pkg/virt-controller/services/rendervolumes.go
  pkg/virt-controller/services/template.go
  pkg/virt-controller/services/template_test.go
  pkg/virt-controller/watch/BUILD.bazel
  pkg/virt-controller/watch/vmi.go
  pkg/virt-launcher/virtwrap/api/schema.go
  pkg/virt-launcher/virtwrap/converter/converter.go
  pkg/virt-operator/resource/generate/components/validations_generated.go
  staging/src/kubevirt.io/api/core/v1/deepcopy_generated.go
  staging/src/kubevirt.io/api/core/v1/schema.go
  staging/src/kubevirt.io/api/core/v1/schema_swagger_generated.go
  staging/src/kubevirt.io/api/core/v1/types.go
  staging/src/kubevirt.io/api/core/v1/types_swagger_generated.go
  staging/src/kubevirt.io/api/instancetype/v1alpha1/deepcopy_generated.go
  staging/src/kubevirt.io/api/instancetype/v1alpha2/deepcopy_generated.go
  staging/src/kubevirt.io/client-go/api/openapi_generated.go
  tests/BUILD.bazel
  tests/testsuite/kubevirtresource.go
  tests/vmi_tpm_test.go
Labels: size/XL, release-note, kind/api-change, lgtm, approved, dco-signoff: yes

#9626 [release-0.58] Manual backport - Fix cleanup of LimitRange
  tests/storage/hotplug.go
Labels: size/XS, release-note-none, lgtm, approved, dco-signoff: yes

#9622 test(virtctl): Add ids to create cmd related tests
  tests/virtctl/create_instancetype.go
  tests/virtctl/create_preference.go
  tests/virtctl/create_vm.go
Labels: size/S, release-note-none, lgtm, approved, dco-signoff: yes

#9496 [e2e tests]: foreground delete testing manifests
  tests/testsuite/manifest.go
Labels: size/XS, release-note-none, lgtm, approved, dco-signoff: yes

#9435 Check for PVC and DataVolume existence in a central place
  pkg/virt-controller/watch/vmi.go
  pkg/virt-controller/watch/vmi_test.go
  tests/storage/storage.go
Labels: size/M, release-note, lgtm, approved, dco-signoff: yes

#9572 Enable freePageReporting at vmi level
  pkg/virt-launcher/virtwrap/api/schema.go
  pkg/virt-launcher/virtwrap/converter/converter.go
  pkg/virt-launcher/virtwrap/converter/converter_test.go
  pkg/virt-launcher/virtwrap/manager.go
  pkg/virt-launcher/virtwrap/manager_test.go
  staging/src/kubevirt.io/api/core/v1/types.go
  tests/vmidefaults_test.go
Labels: size/L, release-note, kind/api-change, lgtm, approved, dco-signoff: yes

#9638 [virt-operator]: Fix kubevirt version parsing when custom operator image name provided
  pkg/virt-operator/util/config.go
  pkg/virt-operator/util/config_test.go
Labels: size/M, release-note-none, lgtm, approved, dco-signoff: yes

#9632 add genesiscloud to adopters
  ADOPTERS.md
Labels: release-note, size/XS, lgtm, approved, ok-to-test, dco-signoff: yes

#8497 tests/vm_test.go: Use libvmi and refactor
  tests/vm_test.go
Labels: size/XXL, release-note-none, lgtm, approved, dco-signoff: yes, sig/code-quality

#9629 feat(virtctl): Add boot order support to create vm
  pkg/virtctl/create/params/params.go
  pkg/virtctl/create/vm/vm.go
  pkg/virtctl/create/vm/vm_test.go
  tests/virtctl/create_vm.go
Labels: size/L, release-note, lgtm, approved, dco-signoff: yes

#9649 tests: Support the output from recent kubectl
  tests/kubectl_test.go
Labels: size/S, release-note-none, lgtm, approved, dco-signoff: yes

#9017 Migrate vmi with two ifaces after cluster upgrade
  automation/test.sh
  tests/libnet/BUILD.bazel
  tests/libnet/plumbing.go
  tests/network/vmi_infosource.go
  tests/operator/BUILD.bazel
  tests/operator/operator.go
Labels: size/L, sig/network, release-note-none, lgtm, approved, dco-signoff: yes

#9640 TSC frequencies: add 250PPM tolerance
  pkg/virt-controller/watch/topology/filter.go
  pkg/virt-controller/watch/topology/tsc.go
  pkg/virt-controller/watch/topology/tsc_test.go
Labels: size/M, release-note, lgtm, approved, dco-signoff: yes

#9651 feat(virtctl): Add memory flag to create vm
  pkg/virtctl/create/vm/vm.go
  pkg/virtctl/create/vm/vm_test.go
  tests/virtctl/create_vm.go
Labels: size/L, release-note, lgtm, approved, dco-signoff: yes

#9609 Run the virtiofsd container as non-root for config volumes
  pkg/virt-controller/services/virtiofs.go
  tests/virtiofs/config.go
Labels: size/M, release-note, lgtm, approved, ok-to-test, dco-signoff: yes

#9650 When a DataVolume is created, it is not clear when a PVC will appear
  pkg/virt-controller/watch/vmi.go
Labels: size/XS, release-note-none, lgtm, approved, dco-signoff: yes

#9453 Extend SIGs
  OWNERS_ALIASES
Labels: size/M, release-note-none, lgtm, approved, dco-signoff: yes

#8815 [release-0.58] hotplug-disk container: match SELinux level of virt-launcher
  api/openapi-spec/swagger.json
  pkg/safepath/safepath.go
  pkg/virt-controller/services/template.go
  pkg/virt-controller/services/template_test.go
  pkg/virt-controller/watch/migration_test.go
  pkg/virt-controller/watch/vmi.go
  pkg/virt-controller/watch/vmi_test.go
  pkg/virt-handler/BUILD.bazel
  pkg/virt-handler/selinux/BUILD.bazel
  pkg/virt-handler/selinux/labels.go
  pkg/virt-handler/vm.go
  pkg/virt-operator/resource/generate/components/validations_generated.go
  staging/src/kubevirt.io/api/core/v1/types.go
  staging/src/kubevirt.io/api/core/v1/types_swagger_generated.go
  staging/src/kubevirt.io/client-go/api/openapi_generated.go
Labels: size/L, release-note-none, lgtm, approved, dco-signoff: yes

#9608 cleanup(virtctl): Remove dryRun options
  pkg/virtctl/create/preference/preference.go
  tests/instancetype_test.go
  tests/testsuite/namespace.go
  tests/virtctl/create_preference.go
Labels: size/M, release-note-none, lgtm, approved, dco-signoff: yes

#9663 Bump bazeldnf to 0.5.6
  WORKSPACE
Labels: size/S, release-note-none, lgtm, approved, dco-signoff: yes

#9654 Fix version detection for builder build script
  hack/builder/build.sh
Labels: size/XS, release-note-none, lgtm, approved, dco-signoff: yes

#9655 [release-0.59] SELinux policy: ensure it never gets installed if the feature gate is set
  cmd/virt-handler/virt-handler.go
  tests/framework/checks/checks.go
  tests/security_features_test.go
Labels: size/S, release-note-none, lgtm, approved, dco-signoff: yes
