Repository kubevirt/kubevirt, pull requests merged in 2023-10, with the labels that each got.

#10493 [release-1.0] Set memory limits if there is a resource quota with limits
  pkg/storage/export/export/export_test.go
  pkg/storage/export/export/pvc-source_test.go
  pkg/storage/export/export/vm-source_test.go
  pkg/storage/export/export/vmsnapshot-source_test.go
  pkg/virt-config/feature-gates.go
  pkg/virt-controller/services/renderresources.go
  pkg/virt-controller/services/renderresources_test.go
  pkg/virt-controller/services/template.go
  pkg/virt-controller/services/template_test.go
  pkg/virt-controller/watch/application.go
  pkg/virt-controller/watch/application_test.go
  pkg/virt-controller/watch/migration_test.go
  pkg/virt-controller/watch/vmi_test.go
  staging/src/kubevirt.io/api/core/v1/types.go
  tests/decorators/decorators.go
  tests/testsuite/kubevirtresource.go
  tests/vmi_configuration_test.go
Labels: size/XL, release-note, kind/api-change, lgtm, approved, dco-signoff: yes

#10461 vendor: Update libvirt.org/go/libvirt
  go.mod
  go.sum
  vendor/libvirt.org/go/libvirt/.gitlab-ci.yml
  vendor/libvirt.org/go/libvirt/README.rst
  vendor/libvirt.org/go/libvirt/domain.go
  vendor/libvirt.org/go/libvirt/libvirt_generated_enums.h
  vendor/libvirt.org/go/libvirt/libvirt_generated_macros.h
  vendor/modules.txt
Labels: size/M, release-note-none, lgtm, approved, dco-signoff: yes

#10477 Enable and configure KSM according to memory pressure
  pkg/testutils/BUILD.bazel
  pkg/testutils/node.go
  pkg/virt-handler/heartbeat/BUILD.bazel
  pkg/virt-handler/heartbeat/heartbeat.go
  pkg/virt-handler/heartbeat/ksm.go
  pkg/virt-handler/heartbeat/ksm_test.go
  pkg/virt-handler/node-labeller/BUILD.bazel
  pkg/virt-handler/node-labeller/model.go
  pkg/virt-handler/node-labeller/node_labeller.go
  pkg/virt-handler/node-labeller/node_labeller_test.go
  staging/src/kubevirt.io/api/core/v1/types.go
  tests/infrastructure/infrastructure.go
  tests/infrastructure/virt-handler.go
Labels: size/XL, release-note, kind/api-change, lgtm, approved, dco-signoff: yes

#10438 rbac: Add instancetype.kubevirt.io:view ClusterRole
  manifests/generated/operator-csv.yaml.in
  manifests/generated/rbac-operator.authorization.k8s.yaml.in
  pkg/virt-operator/kubevirt_test.go
  pkg/virt-operator/resource/generate/rbac/cluster.go
  tests/access_test.go
  tests/testsuite/serviceaccount.go
Labels: size/L, release-note, lgtm, approved, dco-signoff: yes, area/instancetype

#10486 Rename VMI migration metrics
  docs/metrics.md
  hack/prom-rule-ci/prom-rules-tests.yaml
  pkg/monitoring/domainstats/prometheus/prometheus.go
  pkg/monitoring/migrationstats/collector.go
  pkg/monitoring/migrationstats/collector_test.go
  pkg/virt-operator/resource/generate/components/prometheus.go
  tests/libmigration/migration.go
  tests/monitoring/vm_monitoring.go
Labels: size/L, release-note, lgtm, approved, dco-signoff: yes, area/monitoring

#10511 Prevent creation of another Kubevirt
  pkg/virt-operator/application.go
  pkg/virt-operator/resource/generate/components/webhooks.go
  pkg/virt-operator/webhooks/BUILD.bazel
  pkg/virt-operator/webhooks/kubevirt-create-admitter.go
  pkg/virt-operator/webhooks/kubevirt-create-admitter_test.go
  tests/dryrun_test.go
  tests/operator/operator.go
Labels: size/L, release-note-none, lgtm, approved, dco-signoff: yes

#10512 [release-1.0] Prevent creation of another Kubevirt
  pkg/virt-operator/application.go
  pkg/virt-operator/resource/generate/components/webhooks.go
  pkg/virt-operator/webhooks/BUILD.bazel
  pkg/virt-operator/webhooks/kubevirt-create-admitter.go
  pkg/virt-operator/webhooks/kubevirt-create-admitter_test.go
  tests/dryrun_test.go
  tests/operator/operator.go
Labels: size/L, release-note-none, lgtm, approved, dco-signoff: yes

#10500 Adding backup mechanism to report vulnerabilities in security.md
  SECURITY.md
Labels: size/XS, release-note-none, lgtm, approved, dco-signoff: yes

#10514 Delete repeating log without value
  pkg/container-disk/BUILD.bazel
  pkg/container-disk/container-disk.go
Labels: size/XS, release-note-none, lgtm, approved, dco-signoff: yes

#10320 Use sidecar-shim base image with other sidecars and move them under cmd/sidecars
  BUILD.bazel
  cmd/example-cloudinit-hook-sidecar/cloudinit.go
  cmd/example-disk-mutation-hook-sidecar/diskimage.go
  cmd/sidecars/BUILD.bazel
  cmd/sidecars/README.md
  cmd/sidecars/cloudinit/BUILD.bazel
  cmd/sidecars/cloudinit/cloudinit.go
  cmd/sidecars/disk-mutation/BUILD.bazel
  cmd/sidecars/disk-mutation/README.md
  cmd/sidecars/disk-mutation/diskimage.go
  cmd/sidecars/network-slirp-binding/BUILD.bazel
  cmd/sidecars/network-slirp-binding/README.md
  cmd/sidecars/network-slirp-binding/callback/BUILD.bazel
  cmd/sidecars/network-slirp-binding/callback/callback.go
  cmd/sidecars/network-slirp-binding/callback/callback_suite_test.go
  cmd/sidecars/network-slirp-binding/callback/callback_test.go
  cmd/sidecars/network-slirp-binding/dns/BUILD.bazel
  cmd/sidecars/network-slirp-binding/dns/resolvconf.go
  cmd/sidecars/network-slirp-binding/domain/BUILD.bazel
  cmd/sidecars/network-slirp-binding/domain/domain.go
  cmd/sidecars/network-slirp-binding/domain/domain_suite_test.go
  cmd/sidecars/network-slirp-binding/domain/domain_test.go
  cmd/sidecars/network-slirp-binding/main.go
  cmd/sidecars/network-slirp-binding/server/BUILD.bazel
  cmd/sidecars/network-slirp-binding/server/server.go
  cmd/sidecars/sidecar_shim.go
  cmd/sidecars/smbios/BUILD.bazel
  cmd/sidecars/smbios/README.md
  cmd/sidecars/smbios/smbios.go
  hack/bazel-push-images.sh
  hack/config-default.sh
  tests/storage/hotplug.go
  tests/vmi_cloudinit_hook_sidecar_test.go
Labels: size/XL, release-note, lgtm, approved, dco-signoff: yes

#10510 instancetype: Improve admission conflict message
  pkg/instancetype/instancetype.go
  pkg/virt-api/webhooks/validating-webhook/admitters/vms-admitter.go
  tests/BUILD.bazel
  tests/instancetype_test.go
Labels: size/S, release-note-none, lgtm, approved, dco-signoff: yes, area/instancetype

#10423 virt-controller, net: Refactor netbinding sidecar compose
  pkg/network/netbinding/BUILD.bazel
  pkg/network/netbinding/netbinding.go
  pkg/network/netbinding/netbinding_suite_test.go
  pkg/network/netbinding/netbinding_test.go
  pkg/virt-controller/services/BUILD.bazel
  pkg/virt-controller/services/sidecar.go
  pkg/virt-controller/services/template.go
  pkg/virt-controller/services/template_test.go
  pkg/virt-controller/watch/BUILD.bazel
  pkg/virt-controller/watch/application.go
  tests/network/BUILD.bazel
  tests/network/vmi_networking.go
Labels: size/L, sig/network, release-note-none, lgtm, approved, dco-signoff: yes

#10515 Stop copying VMI spec to VM during snapshots
  pkg/storage/snapshot/source.go
  tests/BUILD.bazel
  tests/clone_test.go
  tests/storage/restore.go
  tests/storage/snapshot.go
  tests/utils.go
Labels: size/M, release-note, lgtm, approved, dco-signoff: yes, area/instancetype

#10523 tests: avoid a global constant
  tests/network/macvtap.go
  tests/network/vmi_istio.go
  tests/utils.go
Labels: size/M, sig/network, release-note-none, lgtm, approved, dco-signoff: yes

#10534 Improve error handling when attempting to upload an already succeeded DataVolume
  pkg/virtctl/imageupload/imageupload.go
  pkg/virtctl/imageupload/imageupload_test.go
Labels: size/M, release-note-none, lgtm, approved, dco-signoff: yes

#10439 CI: Workaround Fedora login issue
  tests/console/login.go
Labels: size/XS, release-note-none, lgtm, approved, dco-signoff: yes

#10532 Add --volume-mode flag in image-upload to allow specifying volume mode
  pkg/virtctl/imageupload/imageupload.go
  pkg/virtctl/imageupload/imageupload_test.go
Labels: size/M, release-note, lgtm, approved, dco-signoff: yes

#10538 [guest-console-log] initialize log file if rootful
  cmd/virt-launcher/virt-launcher.go
  pkg/virt-launcher/monitor.go
Labels: size/S, release-note-none, lgtm, approved, dco-signoff: yes

#10440 Credentials tests
  tests/BUILD.bazel
  tests/compute/BUILD.bazel
  tests/compute/credentials_test.go
  tests/compute/framework.go
  tests/credentials_test.go
  tests/tests_suite_test.go
Labels: size/XL, release-note-none, lgtm, approved, dco-signoff: yes

#9590 fix stamp for virt-operator
  cmd/virt-operator/BUILD.bazel
Labels: release-note, size/XS, lgtm, approved, ok-to-test, kind/build-change, dco-signoff: yes

#10537 [e2e tests] Fix sig-storage-root periodic by not hardcoding default ns
  tests/clone_test.go
Labels: size/M, release-note-none, lgtm, approved, dco-signoff: yes

#10550 build: update github.com/opencontainers/runc version
  go.mod
  go.sum
  vendor/github.com/opencontainers/runc/libcontainer/cgroups/ebpf/ebpf_linux.go
  vendor/github.com/opencontainers/runc/libcontainer/cgroups/fs/fs.go
  vendor/github.com/opencontainers/runc/libcontainer/cgroups/fs2/memory.go
  vendor/github.com/opencontainers/runc/libcontainer/cgroups/utils.go
  vendor/github.com/opencontainers/runc/libcontainer/user/user.go
  vendor/modules.txt
Labels: size/M, release-note-none, lgtm, approved, dco-signoff: yes

#10542 virt-launcher, converter: Remove redundent check for '/dev/vhost-net' presense
  pkg/virt-launcher/virtwrap/converter/converter.go
  pkg/virt-launcher/virtwrap/converter/network.go
Labels: size/S, release-note-none, lgtm, approved, dco-signoff: yes

#10539 Add external resource provider to USB Host Pass through device
  api/openapi-spec/swagger.json
  manifests/generated/kv-resource.yaml
  pkg/virt-handler/device-manager/usb_device.go
  pkg/virt-handler/device-manager/usb_device_test.go
  pkg/virt-operator/resource/generate/components/validations_generated.go
  staging/src/kubevirt.io/api/core/v1/types.go
  staging/src/kubevirt.io/api/core/v1/types_swagger_generated.go
  staging/src/kubevirt.io/client-go/api/openapi_generated.go
  tests/usb/usb.go
Labels: size/M, release-note-none, kind/api-change, lgtm, approved, dco-signoff: yes

#10564 multiple bridge interfaces hotplug bug fix
  pkg/network/setup/netpod/netpod.go
Labels: sig/network, size/XS, release-note-none, lgtm, approved, dco-signoff: yes

#10569 VMI Create admitter: Remove unused `nonroot` param
  pkg/virt-api/webhooks/validating-webhook/admitters/vmi-create-admitter.go
Labels: size/XS, release-note-none, lgtm, approved, dco-signoff: yes

#10509 Make builder image and registry name configurable
  hack/builder/arch.sh
  hack/builder/build.sh
  hack/builder/common.sh
  hack/builder/publish.sh
  hack/dockerized
Labels: size/M, release-note-none, lgtm, approved, dco-signoff: yes

#10543 instancetypes: Clear VM guest memory when ignoring inference failures
  pkg/instancetype/instancetype.go
  pkg/testutils/mock_instancetype.go
  pkg/virt-api/webhooks/mutating-webhook/mutators/vm-mutator.go
  pkg/virt-api/webhooks/mutating-webhook/mutators/vm-mutator_test.go
  tests/instancetype_test.go
Labels: size/L, release-note, lgtm, approved, dco-signoff: yes, area/instancetype

#10309 virt-operator: Deploy common-instancetypes
  Makefile
  hack/bump-common-instancetypes.sh
  hack/config-default.sh
  hack/sync-common-instancetypes.sh
  pkg/virt-config/feature-gates.go
  pkg/virt-operator/BUILD.bazel
  pkg/virt-operator/kubevirt_test.go
  pkg/virt-operator/resource/apply/BUILD.bazel
  pkg/virt-operator/resource/apply/instancetype_test.go
  pkg/virt-operator/resource/apply/instancetypes.go
  pkg/virt-operator/resource/apply/reconcile.go
  pkg/virt-operator/resource/generate/components/BUILD.bazel
  pkg/virt-operator/resource/generate/components/data/common-clusterinstancetypes-bundle.yaml
  pkg/virt-operator/resource/generate/components/data/common-clusterpreferences-bundle.yaml
  pkg/virt-operator/resource/generate/components/instancetypes.go
  pkg/virt-operator/resource/generate/components/instancetypes_test.go
  pkg/virt-operator/resource/generate/install/BUILD.bazel
  pkg/virt-operator/resource/generate/install/strategy.go
  tests/operator/BUILD.bazel
  tests/operator/operator.go
Labels: release-note, size/XXL, kind/api-change, lgtm, approved, kind/build-change, dco-signoff: yes, area/instancetype

#10496 Set cpu limits if there is a resource quota with limits
  pkg/virt-controller/services/BUILD.bazel
  pkg/virt-controller/services/template.go
  pkg/virt-controller/services/template_test.go
  tests/vmi_configuration_test.go
Labels: release-note, size/XXL, lgtm, approved, dco-signoff: yes

#10568 Network plugin binding API: Support CNI plugins
  api/openapi-spec/swagger.json
  manifests/generated/kv-resource.yaml
  pkg/network/netbinding/netbinding.go
  pkg/virt-controller/services/BUILD.bazel
  pkg/virt-controller/services/multus_annotations.go
  pkg/virt-controller/services/multus_annotations_test.go
  pkg/virt-controller/services/template.go
  pkg/virt-controller/watch/vmi.go
  pkg/virt-controller/watch/vmi_test.go
  pkg/virt-operator/resource/generate/components/validations_generated.go
  staging/src/kubevirt.io/api/core/v1/types.go
  staging/src/kubevirt.io/api/core/v1/types_swagger_generated.go
  staging/src/kubevirt.io/client-go/api/openapi_generated.go
Labels: size/L, sig/network, release-note, kind/api-change, lgtm, approved, dco-signoff: yes

#10544 virtctl: Do not clear memory when implicitly inferring instancetype
  pkg/virtctl/create/vm/vm.go
  pkg/virtctl/create/vm/vm_test.go
  tests/virtctl/create_vm.go
Labels: size/M, release-note-none, lgtm, approved, dco-signoff: yes

#10547 Add PreferAny option to CPU preferences
  pkg/instancetype/instancetype.go
  pkg/instancetype/instancetype_test.go
  staging/src/kubevirt.io/api/instancetype/v1beta1/types.go
  tests/instancetype_test.go
Labels: size/L, release-note-none, kind/api-change, lgtm, approved, dco-signoff: yes, area/instancetype

#10566 Add 100Mi of overhead for guaranteed vmis
  pkg/virt-controller/services/BUILD.bazel
  pkg/virt-controller/services/renderresources.go
  pkg/virt-controller/services/renderresources_test.go
Labels: size/L, release-note-none, lgtm, approved, dco-signoff: yes

#10581 images, rpms: Bump images
  WORKSPACE
  hack/bootstrap.sh
  rpm/BUILD.bazel
Labels: size/XL, release-note-none, lgtm, approved, dco-signoff: yes

#10518 net, setup: Replace `configstate` for the plug/hotplug flow
  pkg/network/setup/BUILD.bazel
  pkg/network/setup/configstate.go
  pkg/network/setup/configstate_test.go
  pkg/network/setup/netconf.go
  pkg/network/setup/netconf_test.go
  pkg/network/setup/netpod/BUILD.bazel
  pkg/network/setup/netpod/netpod.go
  pkg/network/setup/netpod/netpod_test.go
  pkg/network/setup/netpod/state.go
  pkg/network/setup/netpod/state_test.go
  pkg/network/setup/network.go
  pkg/network/setup/network_suite_test.go
  pkg/network/setup/network_test.go
Labels: sig/network, size/XL, release-note-none, lgtm, approved, dco-signoff: yes

#10479 Enables using scripts to modify VMI definition
  cmd/sidecars/BUILD.bazel
  cmd/sidecars/README.md
  examples/vmi-with-sidecar-hook-configmap.yaml
  hack/bootstrap.sh
  pkg/hooks/hooks.go
  pkg/virt-controller/services/BUILD.bazel
  pkg/virt-controller/services/template.go
  pkg/virt-controller/services/template_test.go
  rpm/BUILD.bazel
  tools/vms-generator/utils/utils.go
  tools/vms-generator/vms-generator.go
Labels: size/XL, release-note, lgtm, approved, ok-to-test, dco-signoff: yes

#10425 Introduce Passt network binding plugin
  BUILD.bazel
  cmd/sidecars/network-passt-binding/BUILD.bazel
  cmd/sidecars/network-passt-binding/README.md
  cmd/sidecars/network-passt-binding/callback/BUILD.bazel
  cmd/sidecars/network-passt-binding/callback/callback.go
  cmd/sidecars/network-passt-binding/callback/callback_suite_test.go
  cmd/sidecars/network-passt-binding/callback/callback_test.go
  cmd/sidecars/network-passt-binding/domain/BUILD.bazel
  cmd/sidecars/network-passt-binding/domain/configurator.go
  cmd/sidecars/network-passt-binding/domain/configurator_test.go
  cmd/sidecars/network-passt-binding/domain/domain_suite_test.go
  cmd/sidecars/network-passt-binding/main.go
  cmd/sidecars/network-passt-binding/server/BUILD.bazel
  cmd/sidecars/network-passt-binding/server/server.go
  hack/bazel-push-images.sh
Labels: sig/network, release-note, size/XXL, lgtm, approved, dco-signoff: yes

#10573 Fix no-op unit tests
  pkg/virt-handler/heartbeat/BUILD.bazel
  pkg/virt-handler/heartbeat/ksm_test.go
Labels: size/M, release-note-none, lgtm, approved, dco-signoff: yes

#10589 [release-0.59] Add 100Mi of overhead for guaranteed vmis
  pkg/virt-controller/services/BUILD.bazel
  pkg/virt-controller/services/renderresources.go
  pkg/virt-controller/services/renderresources_test.go
Labels: size/L, release-note, lgtm, approved, dco-signoff: yes

#10570 Fix LowKVMNodesCount not firing
  docs/metrics.md
  pkg/virt-operator/resource/generate/components/prometheus.go
Labels: release-note, size/XS, lgtm, approved, dco-signoff: yes, area/monitoring

#10596 Disable HTTP/2
  cmd/virt-exportproxy/virt-exportproxy.go
  cmd/virt-handler/virt-handler.go
  pkg/storage/export/virt-exportserver/exportserver.go
  pkg/virt-api/api.go
  pkg/virt-controller/watch/application.go
  pkg/virt-operator/application.go
Labels: size/S, release-note, lgtm, approved, dco-signoff: yes

#10595 virt-launcher monitor, dumpLogFile: Dont log file-not-found errors
  cmd/virt-launcher-monitor/virt-launcher-monitor.go
Labels: size/XS, release-note-none, lgtm, approved, dco-signoff: yes

#10599 Fix sidecar shim rpm generation
  hack/bootstrap.sh
  hack/rpm-deps.sh
  rpm/BUILD.bazel
Labels: size/M, release-note-none, lgtm, approved, dco-signoff: yes

#10582 Remove leftover NonRootExperimental feature gate
  pkg/virt-api/webhooks/fuzz/fuzz_test.go
  pkg/virt-config/feature-gates.go
Labels: release-note, size/XS, lgtm, approved, dco-signoff: yes

#10594 Remove usage BeforeSuite
  pkg/virt-handler/node-labeller/cpu_plugin_test.go
Labels: size/M, release-note-none, lgtm, approved, dco-signoff: yes

#10620 network binding plugin API: Fix logic network name CNI arg format
  pkg/virt-controller/services/multus_annotations.go
  pkg/virt-controller/services/multus_annotations_test.go
Labels: size/XS, release-note-none, lgtm, approved, dco-signoff: yes

#10612 [release-1.0] Fix LowKVMNodesCount not firing
  docs/metrics.md
  pkg/virt-operator/resource/generate/components/prometheus.go
Labels: release-note, size/XS, lgtm, approved, dco-signoff: yes, area/monitoring

#10625 kubevirt.io/client-go: Update golang.org/x/net to v0.17.0
  staging/src/kubevirt.io/api/go.mod
  staging/src/kubevirt.io/api/go.sum
  staging/src/kubevirt.io/client-go/go.mod
  staging/src/kubevirt.io/client-go/go.sum
Labels: size/M, release-note-none, lgtm, approved, dco-signoff: yes

#8799 [e2e-tests]: Don't run all storage-req tests in sig-storage jobs
  automation/test.sh
Labels: size/XS, release-note-none, lgtm, approved, dco-signoff: yes

#10529 Allow LUN disks to be hotplugged
  pkg/virt-api/webhooks/validating-webhook/admitters/vmi-update-admitter.go
  pkg/virt-api/webhooks/validating-webhook/admitters/vmi-update-admitter_test.go
  pkg/virt-api/webhooks/validating-webhook/admitters/vms-admitter.go
  pkg/virt-api/webhooks/validating-webhook/admitters/vms-admitter_test.go
  pkg/virt-launcher/virtwrap/converter/converter.go
  pkg/virt-launcher/virtwrap/converter/converter_test.go
  pkg/virtctl/vm/add_volume.go
  pkg/virtctl/vm/add_volume_test.go
  tests/storage/hotplug.go
Labels: size/L, release-note, lgtm, approved, dco-signoff: yes

#10383 virt-controller set TerminationGracePeriod of VMI to DeletionGracePeriod of VM when deleting VM with kubectl
  pkg/virt-controller/watch/vm.go
  pkg/virt-controller/watch/vm_test.go
  tests/vm_test.go
Labels: size/M, release-note-none, kind/api-change, lgtm, approved, dco-signoff: yes

#10614 e2e, passt: Extend test to cover explicit MAC and PCI addresses setting
  tests/network/vmi_passt.go
Labels: size/S, sig/network, release-note-none, lgtm, approved, dco-signoff: yes

#10611 Improve cpu hotplug test
  tests/hotplug/cpu.go
  tests/utils.go
Labels: size/M, release-note-none, lgtm, approved, dco-signoff: yes

#10638 ksm: fix bug on checking annotation value and move 2 functional tests to unit tests
  pkg/virt-handler/heartbeat/ksm.go
  pkg/virt-handler/heartbeat/ksm_test.go
  tests/infrastructure/virt-handler.go
Labels: size/M, release-note-none, lgtm, approved, dco-signoff: yes

#10557 net, setup: Integrate the unplug flow through netpod (and nmstate)
  pkg/network/setup/BUILD.bazel
  pkg/network/setup/configstate.go
  pkg/network/setup/configstate_test.go
  pkg/network/setup/netconf.go
  pkg/network/setup/netconf_test.go
  pkg/network/setup/netpod/BUILD.bazel
  pkg/network/setup/netpod/discover.go
  pkg/network/setup/netpod/netpod.go
  pkg/network/setup/netpod/netpod_test.go
  pkg/network/setup/netpod/state.go
  pkg/network/setup/netpod/state_test.go
  pkg/network/setup/network.go
  pkg/network/setup/network_suite_test.go
  pkg/network/setup/network_test.go
  pkg/network/setup/unpluggedpodnic.go
  pkg/network/setup/unpluggedpodnic_test.go
  pkg/network/vmispec/interface.go
Labels: sig/network, size/XXL, release-note-none, lgtm, approved, dco-signoff: yes

#10627 fix virtctl create vm volume-import flag
  pkg/virtctl/create/vm/vm.go
  pkg/virtctl/create/vm/vm_test.go
  tests/virtctl/create_vm.go
Labels: size/L, release-note-none, lgtm, approved, dco-signoff: yes

#10650 [e2e] Fix flipped set control plane node schedulability
  tests/migration/eviction_strategy.go
Labels: size/XS, release-note-none, lgtm, approved, dco-signoff: yes

#10303 Arm64, conformance test: initial enablement for conformance tests on Arm64
  Makefile
  WORKSPACE
  automation/conformance.sh
  docs/conformance.md
  hack/conformance.sh
  tests/console/login.go
  tests/framework/checks/checks.go
  tests/framework/checks/skips.go
  tests/network/networkpolicy.go
  tests/network/services.go
  tests/reporter/BUILD.bazel
  tests/reporter/kubernetes.go
  tests/storage/storage.go
  tests/utils.go
  tests/vmi_configuration_test.go
Labels: size/M, sig/network, release-note-none, lgtm, approved, dco-signoff: yes

#10655 [test] Prefer GetLogs in guestlog func tests
  tests/guestlog/BUILD.bazel
  tests/guestlog/guestlog.go
Labels: size/M, release-note-none, lgtm, approved, dco-signoff: yes
