Repository kubevirt/kubevirt, pull requests merged in 2024-06, with the labels that each got.

#12022 net, admitter: Extract the mac-address validation for reuse
  pkg/network/admitter/netiface.go
  pkg/network/admitter/netiface_test.go
  pkg/network/link/BUILD.bazel
  pkg/network/link/mac.go
Labels: size/M, sig/network, release-note-none, lgtm, approved, dco-signoff: yes, sig/buildsystem

#12034 [release-1.2] Allow to set cpu reqs/limits when doing cpu hotplug
  pkg/virt-api/webhooks/validating-webhook/admitters/vms-admitter.go
  pkg/virt-api/webhooks/validating-webhook/admitters/vms-admitter_test.go
  pkg/virt-controller/watch/vm.go
  pkg/virt-controller/watch/vm_test.go
Labels: size/L, release-note, lgtm, approved, dco-signoff: yes

#12024 OWNERS: Allow test, compute and network SIGs to own `.golangci.yml`
  OWNERS
Labels: size/XS, release-note-none, lgtm, approved, dco-signoff: yes, sig/code-quality

#12016 ctrl: fix starting VM with Manual RunStrategy
  pkg/virt-controller/watch/vm.go
  pkg/virt-controller/watch/vm_test.go
Labels: size/L, release-note, lgtm, approved, dco-signoff: yes

#12056 [release-1.2] ctrl: fix starting VM with Manual RunStrategy
  pkg/virt-controller/watch/vm.go
  pkg/virt-controller/watch/vm_test.go
Labels: size/L, release-note, lgtm, approved, dco-signoff: yes

#11992 tests/compute/vmidefaults.go: Remove use of RunVMAndExpectLaunchWithRunStrategy func
  tests/compute/vmidefaults.go
Labels: size/XS, release-note-none, lgtm, approved, dco-signoff: yes, sig/code-quality

#12039 migration controller: replace hardcoded patch operations
  pkg/virt-controller/watch/migration.go
Labels: size/M, release-note-none, lgtm, approved, dco-signoff: yes

#11915 network: Discontinue (and remove) the passt network core binding
  api/api-rule-violations-known.list
  api/api-rule-violations.list
  api/openapi-spec/swagger.json
  pkg/network/admitter/binding.go
  pkg/network/admitter/passt.go
  pkg/network/admitter/passt_test.go
  pkg/network/domainspec/BUILD.bazel
  pkg/network/domainspec/generators.go
  pkg/network/domainspec/generators_test.go
  pkg/network/setup/netpod/discover.go
  pkg/network/setup/netpod/netpod.go
  pkg/network/setup/netpod/netpod_test.go
  pkg/network/setup/podnic.go
  pkg/util/util.go
  pkg/virt-api/webhooks/validating-webhook/admitters/vmi-create-admitter_test.go
  pkg/virt-api/webhooks/validating-webhook/admitters/vms-admitter_test.go
  pkg/virt-config/deprecation/BUILD.bazel
  pkg/virt-config/deprecation/feature-gates.go
  pkg/virt-config/deprecation/feature-gates_test.go
  pkg/virt-config/deprecation/passt.go
  pkg/virt-config/deprecation/validator_test.go
  pkg/virt-controller/services/renderresources.go
  pkg/virt-controller/services/renderresources_test.go
  pkg/virt-controller/services/template_test.go
  pkg/virt-operator/resource/generate/components/validations_generated.go
  pkg/virt-operator/webhooks/kubevirt-update-admitter_test.go
  staging/src/kubevirt.io/api/core/v1/deepcopy_generated.go
  staging/src/kubevirt.io/api/core/v1/schema.go
  staging/src/kubevirt.io/api/core/v1/schema_swagger_generated.go
  staging/src/kubevirt.io/api/core/v1/types.go
  staging/src/kubevirt.io/client-go/api/openapi_generated.go
  tests/network/BUILD.bazel
  tests/network/vmi_passt.go
Labels: sig/network, size/XL, release-note, kind/api-change, lgtm, approved, dco-signoff: yes, sig/buildsystem

#11768 lint: Enable linter for "pkg/virtcl/credentials" package
  Makefile
  hack/gofumpt.sh
  pkg/virtctl/credentials/BUILD.bazel
  pkg/virtctl/credentials/addkey/BUILD.bazel
  pkg/virtctl/credentials/addkey/addkey.go
  pkg/virtctl/credentials/addkey/addkey_suite_test.go
  pkg/virtctl/credentials/addkey/addkey_test.go
  pkg/virtctl/credentials/common/common.go
  pkg/virtctl/credentials/credentials.go
  pkg/virtctl/credentials/password/BUILD.bazel
  pkg/virtctl/credentials/password/password.go
  pkg/virtctl/credentials/password/password_suite_test.go
  pkg/virtctl/credentials/password/password_test.go
  pkg/virtctl/credentials/removekey/BUILD.bazel
  pkg/virtctl/credentials/removekey/removekey.go
  pkg/virtctl/credentials/removekey/removekey_suite_test.go
  pkg/virtctl/credentials/removekey/removekey_test.go
Labels: size/L, area/virtctl, release-note-none, lgtm, approved, dco-signoff: yes, sig/code-quality, sig/buildsystem

#12000 Create kubevirt_vmi_launcher_memory_overhead_bytes metric
  docs/metrics.md
  pkg/monitoring/metrics/virt-controller/BUILD.bazel
  pkg/monitoring/metrics/virt-controller/vmi_metrics.go
  pkg/monitoring/metrics/virt-controller/vmi_metrics_test.go
  pkg/monitoring/metrics/virt-handler/BUILD.bazel
  pkg/monitoring/metrics/virt-handler/virt_handler_suite_test.go
  pkg/virt-controller/services/BUILD.bazel
  pkg/virt-controller/services/template.go
Labels: size/L, release-note, lgtm, approved, dco-signoff: yes, sig/compute, sig/buildsystem, sig/observability

#12003 virt-operator: [BUGFIX] Retain Kubernetes revision annotation
  pkg/virt-operator/resource/apply/apps.go
  pkg/virt-operator/resource/apply/apps_test.go
Labels: size/M, release-note-none, lgtm, approved, dco-signoff: yes

#12014 Allow infra components to be scheduled to master nodes
  pkg/virt-operator/resource/apply/reconcile.go
  pkg/virt-operator/resource/apply/reconcile_test.go
Labels: size/S, release-note-none, lgtm, approved, dco-signoff: yes

#12018 tests, network: Move helper function from the network tests to `libnet`
  .golangci.yml
  tests/libnet/BUILD.bazel
  tests/libnet/hotplug.go
  tests/libnet/mac.go
  tests/network/BUILD.bazel
  tests/network/bindingplugin.go
  tests/network/bindingplugin_macvtap.go
  tests/network/hotplug_bridge.go
  tests/network/hotplug_sriov.go
  tests/network/sriov.go
  tests/network/vmi_multus.go
Labels: size/L, sig/network, release-note-none, lgtm, approved, dco-signoff: yes, sig/code-quality, sig/buildsystem

#12026 [release-1.2][BUGFIX] Fix restore panic in case of volumesnapshot missing
  pkg/storage/export/export/vmsnapshot-source.go
  pkg/storage/snapshot/restore.go
  pkg/storage/snapshot/restore_test.go
Labels: size/M, sig/storage, release-note, lgtm, approved, dco-signoff: yes

#12054 Use restartRequired condition when volumes cannot be updated
  pkg/virt-controller/watch/vm.go
  pkg/virt-controller/watch/vm_test.go
  pkg/virt-controller/watch/volume-migration/volume-migration_test.go
  staging/src/kubevirt.io/api/core/v1/types.go
Labels: size/L, release-note-none, kind/api-change, lgtm, approved, dco-signoff: yes

#12055 Fix flaky connection metric test
  tests/monitoring/vm_monitoring.go
Labels: size/S, release-note-none, lgtm, approved, dco-signoff: yes, sig/observability

#11898 docs: Update handling eviction requests
  docs/handling-eviction-requests.md
Labels: size/M, release-note-none, lgtm, approved, dco-signoff: yes

#12051 tests, net, hotplug: Drop reset-after-hotplug test
  tests/network/hotplug_bridge.go
Labels: size/M, sig/network, release-note-none, lgtm, approved, dco-signoff: yes, sig/buildsystem

#12057 tests, net, kubectl: Drop status interface order test
  tests/network/BUILD.bazel
  tests/network/hotplug_bridge.go
  tests/network/kubectl.go
Labels: size/L, sig/network, release-note-none, lgtm, approved, dco-signoff: yes, sig/buildsystem

#12038 Add the VMI namespace to migration succeeded/failed metrics
  pkg/monitoring/metrics/virt-controller/migrationstats_collector.go
  tests/monitoring/vm_monitoring.go
Labels: size/S, release-note-none, lgtm, approved, dco-signoff: yes, sig/observability

#11455 instancetype: Support Live Updates
  api/openapi-spec/swagger.json
  pkg/instancetype/instancetype.go
  pkg/instancetype/instancetype_test.go
  pkg/testutils/mock_instancetype.go
  pkg/virt-api/webhooks/defaults.go
  pkg/virt-api/webhooks/mutating-webhook/mutators/vmi-mutator_test.go
  pkg/virt-controller/watch/BUILD.bazel
  pkg/virt-controller/watch/vm.go
  pkg/virt-controller/watch/vm_test.go
  pkg/virt-operator/resource/generate/components/validations_generated.go
  staging/src/kubevirt.io/api/instancetype/v1alpha1/conversion.go
  staging/src/kubevirt.io/api/instancetype/v1alpha1/conversion_generated.go
  staging/src/kubevirt.io/api/instancetype/v1alpha2/conversion.go
  staging/src/kubevirt.io/api/instancetype/v1alpha2/conversion_generated.go
  staging/src/kubevirt.io/api/instancetype/v1beta1/deepcopy_generated.go
  staging/src/kubevirt.io/api/instancetype/v1beta1/types.go
  staging/src/kubevirt.io/api/instancetype/v1beta1/types_swagger_generated.go
  staging/src/kubevirt.io/client-go/api/openapi_generated.go
  tests/guestlog/guestlog.go
  tests/hotplug/BUILD.bazel
  tests/hotplug/instancetype.go
Labels: release-note, size/XXL, kind/api-change, lgtm, approved, dco-signoff: yes, area/instancetype, sig/buildsystem

#12076 Nominate machadovilaca as sig/observability approver
  OWNERS_ALIASES
Labels: size/XS, release-note-none, lgtm, approved, dco-signoff: yes

#12079 net, hotplug: Mark network hotplug feature as Beta
  pkg/virt-config/feature-gates.go
Labels: sig/network, release-note, size/XS, lgtm, approved, dco-signoff: yes

#12027 [release-1.1][BUGFIX] Fix restore panic in case of volumesnapshot missing
  pkg/storage/export/export/vmsnapshot-source.go
  pkg/storage/snapshot/restore.go
  pkg/storage/snapshot/restore_test.go
Labels: size/M, release-note, lgtm, approved, dco-signoff: yes

#11820 Start dropping lambdas from operator.go
  tests/operator/operator.go
Labels: size/XL, release-note-none, lgtm, approved, dco-signoff: yes, sig/code-quality

#12030 [release-1.0][BUGFIX] Fix restore panic in case of volumesnapshot missing
  pkg/storage/export/export/vmsnapshot-source.go
  pkg/storage/snapshot/restore.go
  pkg/storage/snapshot/restore_test.go
Labels: size/M, release-note, lgtm, approved, dco-signoff: yes

#11824 clone_test.go: Remove use of RunVMAndExpectLaunchWithRunStrategy func
  tests/clone_test.go
Labels: size/S, release-note-none, lgtm, approved, dco-signoff: yes, sig/code-quality

#12075 Use libstorage to create FS PVC in guestfs tests
  tests/storage/guestfs.go
Labels: size/M, sig/storage, release-note-none, lgtm, approved, dco-signoff: yes

#12043 VM unit tests, remove informers
  pkg/testutils/BUILD.bazel
  pkg/testutils/mock_queue.go
  pkg/virt-controller/watch/BUILD.bazel
  pkg/virt-controller/watch/vm_test.go
Labels: size/L, release-note-none, lgtm, approved, dco-signoff: yes, sig/buildsystem

#12073 [release-1.2] ctrl: fix MaxSockets calculation
  pkg/virt-controller/watch/vm.go
Labels: size/XS, release-note-none, lgtm, approved, dco-signoff: yes

#12064 Fix non-graceful termination of domain when deleting VM object
  pkg/virt-controller/watch/vm.go
  pkg/virt-controller/watch/vm_test.go
  tests/vm_test.go
Labels: size/L, release-note, lgtm, approved, dco-signoff: yes

#12070 Replace golang/glog with kubevirt/client-go/log in virtctl
  pkg/virtctl/BUILD.bazel
  pkg/virtctl/log.go
  pkg/virtctl/portforward/BUILD.bazel
  pkg/virtctl/portforward/portforward.go
  pkg/virtctl/portforward/portforwarder.go
  pkg/virtctl/portforward/tcp.go
  pkg/virtctl/portforward/udp.go
  pkg/virtctl/root.go
  pkg/virtctl/ssh/BUILD.bazel
  pkg/virtctl/ssh/native.go
  pkg/virtctl/ssh/ssh.go
  pkg/virtctl/ssh/wrapped.go
  pkg/virtctl/vnc/BUILD.bazel
  pkg/virtctl/vnc/vnc.go
Labels: size/L, area/virtctl, release-note-none, lgtm, approved, dco-signoff: yes, sig/buildsystem

#12047 Virt-config simplify
  pkg/storage/backend-storage/backend-storage_test.go
  pkg/testutils/mock_config.go
  pkg/util/tls/tls_test.go
  pkg/virt-api/rest/profiler_test.go
  pkg/virt-api/rest/subresource_test.go
  pkg/virt-api/webhooks/mutating-webhook/mutators/vm-mutator_test.go
  pkg/virt-api/webhooks/mutating-webhook/mutators/vmi-mutator_test.go
  pkg/virt-api/webhooks/validating-webhook/admitters/migration-create-admitter_test.go
  pkg/virt-api/webhooks/validating-webhook/admitters/migration-update-admitter_test.go
  pkg/virt-api/webhooks/validating-webhook/admitters/vmclone-admitter_test.go
  pkg/virt-api/webhooks/validating-webhook/admitters/vmexport-admitter_test.go
  pkg/virt-api/webhooks/validating-webhook/admitters/vmi-create-admitter_test.go
  pkg/virt-api/webhooks/validating-webhook/admitters/vmi-update-admitter_test.go
  pkg/virt-api/webhooks/validating-webhook/admitters/vmrestore-admitter_test.go
  pkg/virt-api/webhooks/validating-webhook/admitters/vms-admitter_test.go
  pkg/virt-api/webhooks/validating-webhook/admitters/vmsnapshot-admitter_test.go
  pkg/virt-config/configuration.go
  pkg/virt-config/configuration_test.go
  pkg/virt-controller/services/template_test.go
  pkg/virt-controller/services/virtiofs_test.go
  pkg/virt-controller/watch/vm_test.go
  pkg/virt-controller/watch/vmi_test.go
  pkg/virt-handler/device-manager/mediated_device_test.go
  pkg/virt-handler/device-manager/mediated_devices_types_test.go
  pkg/virt-handler/device-manager/pci_device_test.go
Labels: size/L, sig/storage, release-note-none, lgtm, approved, dco-signoff: yes, sig/compute

#12081 virt-launcher: Remove VirDomain.GetMetadata
  pkg/virt-launcher/virtwrap/cli/generated_mock_libvirt.go
  pkg/virt-launcher/virtwrap/cli/libvirt.go
  pkg/virt-launcher/virtwrap/manager_test.go
Labels: size/S, release-note-none, lgtm, approved, dco-signoff: yes, sig/code-quality

#12089 Collect component Role rules under operator Role instead of ClusterRole
  manifests/generated/operator-csv.yaml.in
  manifests/generated/rbac-operator.authorization.k8s.yaml.in
  pkg/virt-operator/resource/generate/rbac/operator.go
  pkg/virt-operator/resource/generate/rbac/operator_test.go
Labels: size/L, release-note, lgtm, approved, dco-signoff: yes

#11652 virt-launcher: Fix SSH propagation command check for AgentVersionNotSupported condition
  pkg/virt-handler/vm.go
  pkg/virt-handler/vm_test.go
  pkg/virt-launcher/virtwrap/access-credentials/BUILD.bazel
  pkg/virt-launcher/virtwrap/access-credentials/access_credentials.go
  pkg/virt-launcher/virtwrap/access-credentials/access_credentials_test.go
  tests/compute/credentials.go
Labels: size/L, release-note-none, lgtm, approved, dco-signoff: yes, sig/compute, sig/buildsystem

#11848 tests/node_labeller.go: Fix test_id: 6247
  tests/infrastructure/node-labeller.go
Labels: size/S, release-note-none, lgtm, approved, dco-signoff: yes

#11975 vm: replace hardcoded patch operations
  pkg/virt-controller/watch/vm.go
Labels: size/L, release-note-none, lgtm, approved, dco-signoff: yes

#12044 add testID for kubevirt_vmi_info correctly configured with guest OS labels
  tests/monitoring/vm_monitoring.go
Labels: size/XS, release-note-none, lgtm, approved, dco-signoff: yes, sig/observability

#12060 Refactor validateDisks function to improve readability
  pkg/virt-api/webhooks/validating-webhook/admitters/vmi-create-admitter.go
Labels: size/L, sig/network, release-note-none, kind/api-change, lgtm, approved, dco-signoff: yes, sig/buildsystem

#12084 virt-api: replace hardcoded patch operations with patchset
  pkg/virt-api/rest/BUILD.bazel
  pkg/virt-api/rest/subresource.go
  pkg/virt-api/rest/subresource_test.go
  pkg/virt-api/webhooks/mutating-webhook/mutators/clone-create-mutator.go
  pkg/virt-api/webhooks/mutating-webhook/mutators/vmi-mutator.go
  pkg/virt-api/webhooks/mutating-webhook/mutators/vmi-mutator_test.go
  pkg/virt-api/webhooks/validating-webhook/admitters/BUILD.bazel
  pkg/virt-api/webhooks/validating-webhook/admitters/pod-eviction-admitter.go
  pkg/virt-api/webhooks/validating-webhook/admitters/pod-eviction-admitter_test.go
  pkg/virt-api/webhooks/validating-webhook/admitters/vmrestore-admitter_test.go
Labels: size/XL, release-note-none, kind/api-change, lgtm, approved, dco-signoff: yes, area/instancetype, sig/buildsystem, sig/observability

#12004 chore: fix some function names
  pkg/virt-api/webhooks/arm64.go
Labels: size/XS, release-note-none, lgtm, approved, dco-signoff: yes

#12025 Add descheduler annotations support
  pkg/controller/BUILD.bazel
  pkg/controller/controller.go
  pkg/controller/controller_test.go
  pkg/virt-controller/services/BUILD.bazel
  pkg/virt-controller/services/template.go
  pkg/virt-controller/services/template_test.go
  pkg/virt-controller/watch/BUILD.bazel
  pkg/virt-controller/watch/descheduler/BUILD.bazel
  pkg/virt-controller/watch/descheduler/descheduler.go
  pkg/virt-controller/watch/migration.go
  pkg/virt-controller/watch/migration_test.go
  pkg/virt-controller/watch/pool_test.go
  pkg/virt-controller/watch/replicaset_test.go
  pkg/virt-controller/watch/vm.go
  pkg/virt-controller/watch/vm_test.go
  pkg/virt-controller/watch/vmi.go
  pkg/virt-controller/watch/vmi_test.go
  tests/migration/BUILD.bazel
  tests/migration/migration.go
Labels: release-note, size/XXL, lgtm, approved, dco-signoff: yes, sig/compute, sig/buildsystem

#11681 feature-gates: Retrospectively document CommonInstancetypesDeploymentGate as Beta from 1.2.0
  pkg/virt-config/feature-gates.go
Labels: release-note, size/XS, lgtm, approved, dco-signoff: yes, area/instancetype, sig/api

#12106 virt-api: fix panic in setupMemoryHotplug()
  pkg/virt-api/webhooks/defaults.go
  pkg/virt-api/webhooks/validating-webhook/admitters/vms-admitter_test.go
  pkg/virt-controller/watch/vm.go
Labels: size/M, release-note-none, lgtm, approved, dco-signoff: yes

#12009 Node Restriction
  automation/test.sh
  pkg/virt-api/webhooks/utils.go
  pkg/virt-api/webhooks/validating-webhook/admitters/BUILD.bazel
  pkg/virt-api/webhooks/validating-webhook/admitters/vmi-update-admitter.go
  pkg/virt-api/webhooks/validating-webhook/admitters/vmi-update-admitter_test.go
  pkg/virt-config/feature-gates.go
  tests/decorators/decorators.go
  tests/infrastructure/BUILD.bazel
  tests/infrastructure/security.go
Labels: size/L, release-note, lgtm, approved, dco-signoff: yes, sig/buildsystem

#12109 Support Memory Hotplug with Hugepages
  pkg/virt-api/webhooks/validating-webhook/admitters/vms-admitter.go
  pkg/virt-api/webhooks/validating-webhook/admitters/vms-admitter_test.go
  pkg/virt-launcher/virtwrap/converter/converter.go
  pkg/virt-launcher/virtwrap/converter/converter_test.go
Labels: size/M, release-note, lgtm, approved, dco-signoff: yes

#12107 [release-1.2] virt-api: fix panic in setupMemoryHotplug()
  pkg/virt-controller/watch/vm.go
Labels: size/S, release-note-none, lgtm, approved, dco-signoff: yes

#12098 moved replicaset_test.go to use libvmi
  tests/replicaset_test.go
Labels: size/XS, release-note-none, lgtm, approved, dco-signoff: yes

#12119 virt-api: fix panic
  pkg/virt-api/webhooks/validating-webhook/admitters/vms-admitter.go
Labels: release-note, size/XS, lgtm, approved, dco-signoff: yes

#11965 Clean up storage functions in tests/utils.go
  pkg/virtctl/imageupload/BUILD.bazel
  pkg/virtctl/imageupload/imageupload_test.go
  tests/BUILD.bazel
  tests/clone_test.go
  tests/libstorage/BUILD.bazel
  tests/libstorage/datavolume.go
  tests/libstorage/image.go
  tests/migration/BUILD.bazel
  tests/migration/migration.go
  tests/storage/datavolume.go
  tests/storage/export.go
  tests/storage/hotplug.go
  tests/storage/imageupload.go
  tests/storage/memorydump.go
  tests/storage/restore.go
  tests/storage/snapshot.go
  tests/storage/storage.go
  tests/utils.go
  tests/virtiofs/datavolume.go
  tests/vm_test.go
Labels: sig/network, sig/storage, area/virtctl, size/XL, release-note-none, lgtm, approved, dco-signoff: yes, sig/buildsystem

#11982 virt-handler: Restrict node access
  manifests/generated/operator-csv.yaml.in
  manifests/generated/rbac-operator.authorization.k8s.yaml.in
  pkg/controller/virtinformers.go
  pkg/virt-operator/application.go
  pkg/virt-operator/kubevirt.go
  pkg/virt-operator/kubevirt_test.go
  pkg/virt-operator/resource/apply/admissionregistration.go
  pkg/virt-operator/resource/apply/delete.go
  pkg/virt-operator/resource/apply/reconcile.go
  pkg/virt-operator/resource/generate/components/BUILD.bazel
  pkg/virt-operator/resource/generate/components/validatingadmissionpolicy.go
  pkg/virt-operator/resource/generate/components/validatingadmissionpolicy_test.go
  pkg/virt-operator/resource/generate/install/strategy.go
  pkg/virt-operator/resource/generate/rbac/operator.go
  pkg/virt-operator/util/BUILD.bazel
  pkg/virt-operator/util/client.go
  pkg/virt-operator/util/types.go
  tests/BUILD.bazel
  tests/tests_suite_test.go
  tests/validatingadmissionpolicy/BUILD.bazel
  tests/validatingadmissionpolicy/noderestrictions.go
Labels: sig/network, sig/storage, area/virtctl, release-note, size/XXL, lgtm, approved, dco-signoff: yes, sig/buildsystem, sig/scale, sig/observability

#12131 [release-1.2] Deprecate cpu and memory exceeds alerts
  hack/prom-rule-ci/prom-rules-tests.yaml
  pkg/monitoring/rules/alerts/system.go
  tests/monitoring/component_monitoring.go
Labels: size/L, release-note, lgtm, approved, dco-signoff: yes, sig/buildsystem, sig/observability

#12133 tests/storage: Replace hardcoded patch operations with patchset
  tests/storage/datavolume.go
  tests/storage/export.go
  tests/storage/restore.go
  tests/storage/snapshot.go
Labels: size/M, sig/storage, release-note-none, lgtm, approved, dco-signoff: yes, sig/code-quality

#12080 tests: Simplify waiting for VM to become ready
  tests/monitoring/metrics.go
  tests/storage/hotplug.go
  tests/utils.go
Labels: size/M, sig/storage, release-note-none, lgtm, approved, dco-signoff: yes, sig/code-quality, sig/observability

#11911 Implement retries in vmexport download when server returns unexpected status
  pkg/storage/export/export/BUILD.bazel
  pkg/storage/export/export/export.go
  pkg/storage/export/export/export_test.go
  pkg/storage/export/virt-exportserver/exportserver.go
  pkg/virtctl/memorydump/memorydump.go
  pkg/virtctl/vmexport/vmexport.go
  pkg/virtctl/vmexport/vmexport_test.go
Labels: size/L, sig/storage, area/virtctl, release-note, lgtm, approved, dco-signoff: yes, sig/buildsystem

#12141 [release-1.2] virt-launcher: Fix SSH propagation command check for AgentVersionNotSupported condition
  pkg/virt-handler/vm.go
  pkg/virt-handler/vm_test.go
  pkg/virt-launcher/virtwrap/access-credentials/BUILD.bazel
  pkg/virt-launcher/virtwrap/access-credentials/access_credentials.go
  pkg/virt-launcher/virtwrap/access-credentials/access_credentials_test.go
  tests/compute/credentials.go
Labels: size/L, release-note-none, lgtm, approved, dco-signoff: yes, sig/buildsystem

#12128 Memory Hotplug fixes and stabilization
  pkg/libvmi/cpu.go
  pkg/libvmi/memory.go
  pkg/liveupdate/memory/BUILD.bazel
  pkg/liveupdate/memory/memory.go
  pkg/liveupdate/memory/memory_suite_test.go
  pkg/liveupdate/memory/memory_test.go
  pkg/virt-api/webhooks/BUILD.bazel
  pkg/virt-api/webhooks/defaults.go
  pkg/virt-api/webhooks/mutating-webhook/mutators/BUILD.bazel
  pkg/virt-api/webhooks/mutating-webhook/mutators/vmi-mutator_test.go
  pkg/virt-api/webhooks/validating-webhook/admitters/BUILD.bazel
  pkg/virt-api/webhooks/validating-webhook/admitters/vms-admitter.go
  pkg/virt-api/webhooks/validating-webhook/admitters/vms-admitter_test.go
  pkg/virt-controller/watch/BUILD.bazel
  pkg/virt-controller/watch/migration.go
  pkg/virt-controller/watch/migration_test.go
  pkg/virt-controller/watch/vm.go
  pkg/virt-controller/watch/vm_test.go
  pkg/virt-controller/watch/workload-updater/workload-updater.go
  pkg/virt-handler/vm.go
  pkg/virt-handler/vm_test.go
  pkg/virt-launcher/virtwrap/BUILD.bazel
  pkg/virt-launcher/virtwrap/cmd-server/server.go
  pkg/virt-launcher/virtwrap/converter/converter.go
  pkg/virt-launcher/virtwrap/converter/converter_test.go
  pkg/virt-launcher/virtwrap/manager.go
  pkg/virt-launcher/virtwrap/manager_test.go
  staging/src/kubevirt.io/api/core/v1/types.go
  tests/hotplug/memory.go
  tests/vmi_configuration_test.go
Labels: kind/bug, release-note, size/XXL, lgtm, approved, dco-signoff: yes, sig/compute

#12125 chore: bump virtio-win image version to 0.1.248
  WORKSPACE
Labels: release-note, size/XS, lgtm, approved, dco-signoff: yes, sig/buildsystem

#12148 Use ginkgo's contexts - update the coding-conventions
  docs/coding-conventions.md
Labels: size/M, release-note-none, lgtm, approved, dco-signoff: yes

#12127 virt-handler: Use patchset for patch operations
  pkg/virt-handler/node-labeller/node_labeller.go
Labels: size/M, release-note-none, lgtm, approved, dco-signoff: yes, sig/compute

#12152 [release-1.2] Memory Hotplug fixes and stabilization
  pkg/liveupdate/memory/BUILD.bazel
  pkg/liveupdate/memory/memory.go
  pkg/liveupdate/memory/memory_suite_test.go
  pkg/liveupdate/memory/memory_test.go
  pkg/virt-api/webhooks/defaults.go
  pkg/virt-api/webhooks/mutating-webhook/mutators/vmi-mutator_test.go
  pkg/virt-api/webhooks/validating-webhook/admitters/BUILD.bazel
  pkg/virt-api/webhooks/validating-webhook/admitters/vms-admitter.go
  pkg/virt-api/webhooks/validating-webhook/admitters/vms-admitter_test.go
  pkg/virt-controller/watch/BUILD.bazel
  pkg/virt-controller/watch/migration.go
  pkg/virt-controller/watch/migration_test.go
  pkg/virt-controller/watch/vm.go
  pkg/virt-controller/watch/vm_test.go
  pkg/virt-controller/watch/workload-updater/workload-updater.go
  pkg/virt-handler/vm.go
  pkg/virt-handler/vm_test.go
  pkg/virt-launcher/virtwrap/BUILD.bazel
  pkg/virt-launcher/virtwrap/cmd-server/server.go
  pkg/virt-launcher/virtwrap/converter/converter.go
  pkg/virt-launcher/virtwrap/converter/converter_test.go
  pkg/virt-launcher/virtwrap/manager.go
  pkg/virt-launcher/virtwrap/manager_test.go
  staging/src/kubevirt.io/api/core/v1/types.go
  tests/hotplug/memory.go
  tests/vmi_configuration_test.go
Labels: kind/bug, release-note, size/XXL, lgtm, approved, dco-signoff: yes, sig/compute

#12167 Revert "Use ginkgo's contexts - update the coding-conventions"
  docs/coding-conventions.md
Labels: size/M, release-note-none, lgtm, approved, dco-signoff: yes

#12147 api, defaults: Remove SetDefaults_NetworkInterface
  staging/src/kubevirt.io/api/core/v1/defaults.go
  staging/src/kubevirt.io/client-go/api/defaults_test.go
  tests/network/vmi_lifecycle.go
Labels: size/L, sig/network, release-note-none, kind/api-change, lgtm, approved, dco-signoff: yes, sig/code-quality

#12169 preference: Only apply PreferredDiskDedicatedIoThread to virtio disks
  api/openapi-spec/swagger.json
  pkg/instancetype/instancetype.go
  pkg/instancetype/instancetype_test.go
  pkg/virt-operator/resource/generate/components/validations_generated.go
  staging/src/kubevirt.io/api/instancetype/v1beta1/types.go
  staging/src/kubevirt.io/api/instancetype/v1beta1/types_swagger_generated.go
  staging/src/kubevirt.io/client-go/api/openapi_generated.go
Labels: size/M, release-note, kind/api-change, lgtm, approved, dco-signoff: yes, area/instancetype

#12159 [release-1.2] controller: Setup CurrentCPUTopology after applying instance types
  pkg/virt-controller/watch/vm.go
  pkg/virt-controller/watch/vm_test.go
Labels: kind/bug, size/L, release-note-none, lgtm, approved, dco-signoff: yes, area/instancetype, sig/compute

#12168 mem-hotplug: fix target pod requests calculation with hugepages
  automation/test.sh
  pkg/virt-controller/watch/migration.go
  pkg/virt-controller/watch/migration_test.go
  tests/decorators/decorators.go
  tests/hotplug/memory.go
Labels: size/M, release-note-none, lgtm, approved, dco-signoff: yes, sig/compute, sig/buildsystem

#12113 converter: fix IO policy overwrite
  pkg/virt-launcher/virtwrap/converter/converter.go
  pkg/virt-launcher/virtwrap/converter/converter_test.go
Labels: size/S, release-note-none, lgtm, approved, dco-signoff: yes

#12104 [release-1.0] Collect component Role rules under operator Role instead of ClusterRole
  manifests/generated/operator-csv.yaml.in
  manifests/generated/rbac-operator.authorization.k8s.yaml.in
  pkg/virt-operator/resource/generate/rbac/operator.go
  pkg/virt-operator/resource/generate/rbac/operator_test.go
Labels: size/L, release-note, lgtm, approved, dco-signoff: yes

#12173 [release-1.2] mem-hotplug: fix target pod requests calculation with hugepages
  automation/test.sh
  pkg/virt-controller/watch/migration.go
  pkg/virt-controller/watch/migration_test.go
  tests/decorators/decorators.go
  tests/hotplug/memory.go
Labels: kind/bug, size/M, release-note-none, lgtm, approved, dco-signoff: yes, sig/compute

#12135 libvmi.WithMasqueradeNetworking(): return a single option instead of a slice
  tests/hotplug/affinity.go
  tests/hotplug/cpu.go
  tests/hotplug/instancetype.go
  tests/hotplug/memory.go
  tests/hyperv_test.go
  tests/libnet/vmibuilder.go
  tests/mdev_configuration_allocation_test.go
  tests/migration/eviction_strategy.go
  tests/migration/migration.go
  tests/migration/postcopy.go
  tests/monitoring/monitoring.go
  tests/monitoring/vm_monitoring.go
  tests/network/expose.go
  tests/network/hotplug_bridge.go
  tests/network/networkpolicy.go
  tests/network/probes.go
  tests/network/services.go
  tests/network/vmi_networking.go
  tests/portforward_test.go
  tests/security_features_test.go
  tests/storage/backendstorage.go
  tests/storage/restore.go
  tests/storage/snapshot.go
  tests/storage/storage.go
  tests/subresource_api_test.go
  tests/swap_test.go
  tests/vm_state_test.go
  tests/vmi_configuration_test.go
  tests/vmi_headless_test.go
  tests/vmi_hostdev_test.go
  tests/vmi_multiqueue_test.go
  tests/vmi_tpm_test.go
  tests/vmi_vsock_test.go
  tests/windows_test.go
Labels: size/L, sig/network, sig/storage, release-note-none, lgtm, approved, dco-signoff: yes, sig/code-quality, sig/observability

#12118 tests/operator: Use patch package in operator
  tests/operator/BUILD.bazel
  tests/operator/operator.go
Labels: size/L, sig/storage, area/virtctl, release-note-none, lgtm, approved, dco-signoff: yes, sig/code-quality, sig/buildsystem

#12143 vmi and pool controller: Use patchset for patch operations
  pkg/virt-controller/watch/pool.go
  pkg/virt-controller/watch/vmi.go
Labels: size/L, release-note-none, lgtm, approved, dco-signoff: yes

#12144 tests: unskip some storage-related tests by moving them to sig-storage
  tests/vmi_configuration_test.go
Labels: size/S, release-note-none, lgtm, approved, dco-signoff: yes

#12189 [release-1.2] fix: Add restart condition when network interface multiqueue is enabled
  pkg/virt-controller/watch/vm.go
  pkg/virt-controller/watch/vm_test.go
Labels: kind/bug, size/M, release-note, lgtm, approved, dco-signoff: yes

#12179 tests, utils: Move the echo-response constant to the `console` package
  tests/console/console.go
  tests/network/bindingplugin_passt.go
  tests/network/expose.go
  tests/network/vmi_multus.go
  tests/network/vmi_networking.go
  tests/storage/hotplug.go
  tests/storage/restore.go
  tests/storage/snapshot.go
  tests/storage/storage.go
  tests/utils.go
  tests/vmi_vsock_test.go
Labels: size/M, sig/network, sig/storage, release-note-none, lgtm, approved, dco-signoff: yes, sig/code-quality

#12161 [release-1.0] Manual backport of implement retries in export server
  cmd/virt-exportserver/BUILD.bazel
  pkg/storage/export/export/BUILD.bazel
  pkg/storage/export/export/export.go
  pkg/storage/export/export/export_test.go
  pkg/storage/export/virt-exportserver/BUILD.bazel
  pkg/storage/export/virt-exportserver/exportserver.go
Labels: size/M, release-note, lgtm, approved, kind/build-change, dco-signoff: yes

#12153 mem-hotplug: fix flaky test and small issues
  pkg/virt-controller/watch/vm.go
  pkg/virt-controller/watch/vm_test.go
  tests/hotplug/memory.go
Labels: size/L, release-note-none, lgtm, approved, dco-signoff: yes

#12170 Fix flaky cache unit test
  pkg/virt-handler/cache/cache_test.go
Labels: size/S, release-note-none, lgtm, approved, dco-signoff: yes, sig/compute

#12160 [release-1.1] Manual backport of implement retries in export server
  pkg/storage/export/export/BUILD.bazel
  pkg/storage/export/export/export.go
  pkg/storage/export/export/export_test.go
  pkg/storage/export/virt-exportserver/BUILD.bazel
  pkg/storage/export/virt-exportserver/exportserver.go
Labels: size/M, release-note, lgtm, approved, dco-signoff: yes

#12019 Remove cdi dependecy from virtwrap API schema
  pkg/storage/types/cdi.go
  pkg/virt-api/rest/subresource_test.go
  pkg/virt-controller/watch/vmi.go
  pkg/virt-controller/watch/vmi_test.go
  pkg/virt-launcher/virtwrap/BUILD.bazel
  pkg/virt-launcher/virtwrap/api/BUILD.bazel
  pkg/virt-launcher/virtwrap/api/deepcopy_generated.go
  pkg/virt-launcher/virtwrap/api/schema.go
  pkg/virt-launcher/virtwrap/manager.go
  pkg/virt-launcher/virtwrap/manager_test.go
  pkg/virtctl/memorydump/BUILD.bazel
  pkg/virtctl/memorydump/memorydump.go
  staging/src/kubevirt.io/api/core/v1/deepcopy_generated.go
  staging/src/kubevirt.io/api/core/v1/types.go
Labels: size/L, sig/storage, area/virtctl, release-note-none, kind/api-change, lgtm, approved, dco-signoff: yes, sig/buildsystem

#12156 [release-1.2] Manual backport of implement retries in export server
  pkg/storage/export/export/BUILD.bazel
  pkg/storage/export/export/export.go
  pkg/storage/export/export/export_test.go
  pkg/storage/export/virt-exportserver/BUILD.bazel
  pkg/storage/export/virt-exportserver/exportserver.go
  pkg/virtctl/memorydump/memorydump.go
  pkg/virtctl/vmexport/vmexport.go
  pkg/virtctl/vmexport/vmexport_test.go
Labels: size/L, sig/storage, release-note, lgtm, approved, dco-signoff: yes, sig/buildsystem

#12149 Simplify IsoGuestVolumePath
  pkg/virt-handler/vm.go
  tests/migration/migration.go
Labels: size/M, release-note-none, lgtm, approved, dco-signoff: yes, sig/compute

#12126 virt-exportproxy: use stores instead of informers
  cmd/virt-exportproxy/virt-exportproxy.go
  pkg/storage/backend-storage/backend-storage_test.go
  pkg/testutils/mock_config.go
  pkg/util/tls/tls.go
  pkg/util/tls/tls_test.go
  pkg/virt-api/rest/profiler_test.go
  pkg/virt-api/rest/subresource_test.go
  pkg/virt-api/webhooks/mutating-webhook/mutators/vm-mutator_test.go
  pkg/virt-api/webhooks/mutating-webhook/mutators/vmi-mutator_test.go
  pkg/virt-api/webhooks/validating-webhook/admitters/migration-create-admitter_test.go
  pkg/virt-api/webhooks/validating-webhook/admitters/migration-update-admitter_test.go
  pkg/virt-api/webhooks/validating-webhook/admitters/vmclone-admitter_test.go
  pkg/virt-api/webhooks/validating-webhook/admitters/vmexport-admitter_test.go
  pkg/virt-api/webhooks/validating-webhook/admitters/vmi-create-admitter_test.go
  pkg/virt-api/webhooks/validating-webhook/admitters/vmi-update-admitter_test.go
  pkg/virt-api/webhooks/validating-webhook/admitters/vmrestore-admitter_test.go
  pkg/virt-api/webhooks/validating-webhook/admitters/vms-admitter_test.go
  pkg/virt-api/webhooks/validating-webhook/admitters/vmsnapshot-admitter_test.go
  pkg/virt-config/configuration_test.go
  pkg/virt-controller/services/template_test.go
  pkg/virt-controller/services/virtiofs_test.go
  pkg/virt-controller/watch/vm_test.go
  pkg/virt-controller/watch/vmi_test.go
  pkg/virt-handler/device-manager/mediated_device_test.go
  pkg/virt-handler/device-manager/mediated_devices_types_test.go
  pkg/virt-handler/device-manager/pci_device_test.go
Labels: sig/storage, size/XL, release-note-none, lgtm, approved, dco-signoff: yes, sig/compute

#12193 vm: fix RerunOnFailure stuck in Provisioning
  pkg/virt-controller/watch/vm.go
  pkg/virt-controller/watch/vm_test.go
Labels: kind/bug, size/M, release-note, lgtm, approved, dco-signoff: yes

#12202 [release-1.2] vm: fix RerunOnFailure stuck in Provisioning
  pkg/virt-controller/watch/vm.go
  pkg/virt-controller/watch/vm_test.go
Labels: size/M, release-note, lgtm, approved, dco-signoff: yes

#12053 [BugFix] Configure a single vGPU display with ramfb
  pkg/virt-api/webhooks/validating-webhook/admitters/vmi-create-admitter.go
  pkg/virt-api/webhooks/validating-webhook/admitters/vmi-create-admitter_test.go
  pkg/virt-launcher/virtwrap/device/hostdevice/BUILD.bazel
  pkg/virt-launcher/virtwrap/device/hostdevice/hostdev.go
  pkg/virt-launcher/virtwrap/device/hostdevice/hostdev_test.go
Labels: size/L, release-note, lgtm, approved, dco-signoff: yes, sig/buildsystem

#12205 [release-1.1] Remove redundant DeepCopy calls
  pkg/virt-controller/watch/vm.go
  pkg/virt-controller/watch/vm_test.go
Labels: size/M, release-note-none, lgtm, approved, dco-signoff: yes

#12177 tests/usbredir: Disable test for s390x
  tests/BUILD.bazel
  tests/usbredir_test.go
Labels: size/M, release-note-none, lgtm, approved, dco-signoff: yes, sig/buildsystem

#10837 Remove watchdog file & legacy socket handling
  cmd/virt-handler/BUILD.bazel
  cmd/virt-handler/virt-handler.go
  cmd/virt-launcher/virt-launcher.go
  pkg/virt-handler/BUILD.bazel
  pkg/virt-handler/cache/BUILD.bazel
  pkg/virt-handler/cache/cache.go
  pkg/virt-handler/cache/cache_test.go
  pkg/virt-handler/cmd-client/client.go
  pkg/virt-handler/cmd-client/client_test.go
  pkg/virt-handler/isolation/detector_test.go
  pkg/virt-handler/vm.go
  pkg/virt-handler/vm_test.go
  pkg/watchdog/BUILD.bazel
  pkg/watchdog/watchdog.go
  pkg/watchdog/watchdog_suite_test.go
  pkg/watchdog/watchdog_test.go
Labels: size/XL, release-note-none, lgtm, approved, kind/build-change, dco-signoff: yes, sig/compute, sig/buildsystem

#12197 Remove several lambda functions from tests/operator
  tests/operator/operator.go
Labels: size/L, release-note-none, lgtm, approved, dco-signoff: yes, sig/code-quality

#12213 sig-buildsystem: remove ownership for BUILD.bazel changes
  OWNERS
Labels: size/XS, release-note-none, lgtm, approved, dco-signoff: yes

#11859 VMIRS cleanup: use fakeclient and remove informers
  go.mod
  go.sum
  pkg/virt-controller/watch/BUILD.bazel
  pkg/virt-controller/watch/replicaset.go
  pkg/virt-controller/watch/replicaset_test.go
  pkg/virt-controller/watch/vm_test.go
  staging/src/kubevirt.io/client-go/generated/kubevirt/clientset/versioned/typed/core/v1/fake/BUILD.bazel
  staging/src/kubevirt.io/client-go/generated/kubevirt/clientset/versioned/typed/core/v1/fake/fake_virtualmachine_expansion.go
  staging/src/kubevirt.io/client-go/generated/kubevirt/clientset/versioned/typed/core/v1/fake/fake_virtualmachineinstance_expansion.go
  staging/src/kubevirt.io/client-go/generated/kubevirt/clientset/versioned/typed/core/v1/fake/fake_virtualmachineinstancereplicaset_expansion.go
  staging/src/kubevirt.io/client-go/go.mod
  staging/src/kubevirt.io/client-go/go.sum
  staging/src/kubevirt.io/client-go/kubecli/fake/BUILD.bazel
  staging/src/kubevirt.io/client-go/testing/BUILD.bazel
  staging/src/kubevirt.io/client-go/testing/actions.go
  staging/src/kubevirt.io/client-go/testing/fake.go
  vendor/k8s.io/apiserver/LICENSE
  vendor/k8s.io/apiserver/pkg/storage/names/BUILD.bazel
  vendor/k8s.io/apiserver/pkg/storage/names/generate.go
  vendor/modules.txt
Labels: size/XXL, release-note-none, lgtm, approved, dco-signoff: yes, sig/buildsystem

#12216 e2e,compute: Remove hugepages-2mi test from quarantine
  tests/vmi_configuration_test.go
Labels: size/XS, release-note-none, lgtm, approved, dco-signoff: yes

#12217 [release-1.2] mem-hotplug: enable only for VMs with memory >= 1Gi
  WORKSPACE
  pkg/liveupdate/memory/memory.go
  pkg/liveupdate/memory/memory_test.go
  pkg/virt-api/webhooks/validating-webhook/admitters/vms-admitter_test.go
  pkg/virt-controller/watch/vm_test.go
  tests/hotplug/memory.go
  tests/vmi_configuration_test.go
Labels: kind/bug, size/L, release-note, lgtm, approved, dco-signoff: yes, sig/buildsystem

#12195 Ensure virt-export route has redirect policy
  pkg/virt-operator/resource/generate/components/BUILD.bazel
  pkg/virt-operator/resource/generate/components/routes.go
  pkg/virt-operator/resource/generate/components/routes_test.go
Labels: size/M, release-note, lgtm, approved, dco-signoff: yes, sig/buildsystem

#12116 Add memory/cpu utilization of components to kubevirt benchmarks
  tools/perfscale-audit/api/api.go
  tools/perfscale-audit/metric-client/metric-client.go
Labels: size/M, release-note, lgtm, approved, dco-signoff: yes, sig/scale

#12211 Remove informer usages from virt-handler
  cmd/virt-handler/virt-handler.go
  pkg/virt-handler/rest/common.go
  pkg/virt-handler/rest/console.go
  pkg/virt-handler/rest/lifecycle.go
  pkg/virt-handler/vm.go
  pkg/virt-handler/vm_test.go
Labels: size/L, release-note-none, lgtm, approved, dco-signoff: yes, sig/compute

#11856 Add unit tests to check for API backward compatibility
  Makefile
  hack/bazel-test.sh
  hack/update-generated-api-testdata.sh
  staging/src/kubevirt.io/api/apitesting/BUILD.bazel
  staging/src/kubevirt.io/api/apitesting/roundtrip/BUILD.bazel
  staging/src/kubevirt.io/api/apitesting/roundtrip/compatibility.go
  staging/src/kubevirt.io/api/apitesting/roundtrip/construct.go
  staging/src/kubevirt.io/api/apitesting/roundtrip_test.go
  staging/src/kubevirt.io/api/apitesting/testdata/HEAD/kubevirt.io.v1.KubeVirt.json
  staging/src/kubevirt.io/api/apitesting/testdata/HEAD/kubevirt.io.v1.KubeVirt.yaml
  staging/src/kubevirt.io/api/apitesting/testdata/HEAD/kubevirt.io.v1.VirtualMachine.json
  staging/src/kubevirt.io/api/apitesting/testdata/HEAD/kubevirt.io.v1.VirtualMachine.yaml
  staging/src/kubevirt.io/api/apitesting/testdata/HEAD/kubevirt.io.v1.VirtualMachineInstance.json
  staging/src/kubevirt.io/api/apitesting/testdata/HEAD/kubevirt.io.v1.VirtualMachineInstance.yaml
  staging/src/kubevirt.io/api/apitesting/testdata/README.md
  staging/src/kubevirt.io/api/apitesting/testdata/release-1.0/kubevirt.io.v1.KubeVirt.json
  staging/src/kubevirt.io/api/apitesting/testdata/release-1.0/kubevirt.io.v1.KubeVirt.yaml
  staging/src/kubevirt.io/api/apitesting/testdata/release-1.0/kubevirt.io.v1.VirtualMachine.json
  staging/src/kubevirt.io/api/apitesting/testdata/release-1.0/kubevirt.io.v1.VirtualMachine.yaml
  staging/src/kubevirt.io/api/apitesting/testdata/release-1.0/kubevirt.io.v1.VirtualMachineInstance.json
  staging/src/kubevirt.io/api/apitesting/testdata/release-1.0/kubevirt.io.v1.VirtualMachineInstance.yaml
  staging/src/kubevirt.io/api/apitesting/testdata/release-1.1/kubevirt.io.v1.KubeVirt.json
  staging/src/kubevirt.io/api/apitesting/testdata/release-1.1/kubevirt.io.v1.KubeVirt.yaml
  staging/src/kubevirt.io/api/apitesting/testdata/release-1.1/kubevirt.io.v1.VirtualMachine.json
  staging/src/kubevirt.io/api/apitesting/testdata/release-1.1/kubevirt.io.v1.VirtualMachine.yaml
  staging/src/kubevirt.io/api/apitesting/testdata/release-1.1/kubevirt.io.v1.VirtualMachineInstance.json
  staging/src/kubevirt.io/api/apitesting/testdata/release-1.1/kubevirt.io.v1.VirtualMachineInstance.yaml
  staging/src/kubevirt.io/api/apitesting/testdata/release-1.2/kubevirt.io.v1.KubeVirt.json
  staging/src/kubevirt.io/api/apitesting/testdata/release-1.2/kubevirt.io.v1.KubeVirt.yaml
  staging/src/kubevirt.io/api/apitesting/testdata/release-1.2/kubevirt.io.v1.VirtualMachine.json
  staging/src/kubevirt.io/api/apitesting/testdata/release-1.2/kubevirt.io.v1.VirtualMachine.yaml
  staging/src/kubevirt.io/api/apitesting/testdata/release-1.2/kubevirt.io.v1.VirtualMachineInstance.json
  staging/src/kubevirt.io/api/apitesting/testdata/release-1.2/kubevirt.io.v1.VirtualMachineInstance.yaml
  staging/src/kubevirt.io/api/go.mod
Labels: sig/network, sig/storage, area/virtctl, release-note, size/XXL, kind/api-change, lgtm, approved, kind/build-change, dco-signoff: yes, area/instancetype, sig/compute, sig/buildsystem, sig/scale, sig/observability

#12145 libvmi: Refactor cloudinit buiders
  pkg/libvmi/BUILD.bazel
  pkg/libvmi/cloudinit.go
  pkg/libvmi/cloudinit/BUILD.bazel
  pkg/libvmi/cloudinit/cloudinit.go
  pkg/virt-api/webhooks/validating-webhook/admitters/BUILD.bazel
  pkg/virt-api/webhooks/validating-webhook/admitters/vmi-create-admitter_test.go
  tests/BUILD.bazel
  tests/compute/BUILD.bazel
  tests/compute/credentials.go
  tests/libnet/BUILD.bazel
  tests/libnet/vmibuilder.go
  tests/libvmifact/BUILD.bazel
  tests/libvmifact/factory.go
  tests/migration/BUILD.bazel
  tests/migration/migration.go
  tests/migration/postcopy.go
  tests/network/BUILD.bazel
  tests/network/bindingplugin_passt.go
  tests/network/hotplug_bridge.go
  tests/network/primary_pod_network.go
  tests/network/sriov.go
  tests/network/vmi_infosource.go
  tests/network/vmi_istio.go
  tests/network/vmi_multus.go
  tests/network/vmi_networking.go
  tests/performance/BUILD.bazel
  tests/performance/realtime.go
  tests/realtime/BUILD.bazel
  tests/realtime/realtime.go
  tests/storage/BUILD.bazel
  tests/storage/datavolume.go
  tests/storage/export.go
  tests/storage/hotplug.go
  tests/storage/migration.go
  tests/storage/restore.go
  tests/storage/snapshot.go
  tests/storage/storage.go
  tests/virtctl/BUILD.bazel
  tests/virtctl/scp.go
  tests/virtctl/ssh.go
  tests/virtiofs/BUILD.bazel
  tests/virtiofs/datavolume.go
  tests/vm_state_test.go
  tests/vm_test.go
  tests/vmi_cloudinit_test.go
  tests/vmi_configuration_test.go
  tests/vmi_vsock_test.go
Labels: size/L, sig/network, sig/storage, release-note-none, lgtm, approved, dco-signoff: yes, sig/code-quality, sig/buildsystem, sig/scale

#12093 virt-config: Extract pod network attachment logic
  pkg/libvmi/network.go
  pkg/network/vmispec/BUILD.bazel
  pkg/network/vmispec/defaults.go
  pkg/network/vmispec/defaults_test.go
  pkg/virt-api/webhooks/BUILD.bazel
  pkg/virt-api/webhooks/defaults.go
  pkg/virt-config/virt-config.go
  pkg/virt-controller/watch/vm.go
  tests/network/vmi_networking.go
Labels: size/L, sig/network, release-note-none, lgtm, approved, dco-signoff: yes, sig/code-quality, sig/buildsystem

#12182 [release-1.2] preference: Only apply PreferredDiskDedicatedIoThread to virtio disks
  api/openapi-spec/swagger.json
  pkg/instancetype/BUILD.bazel
  pkg/instancetype/instancetype.go
  pkg/instancetype/instancetype_test.go
  pkg/virt-operator/resource/generate/components/validations_generated.go
  staging/src/kubevirt.io/api/instancetype/v1beta1/types.go
  staging/src/kubevirt.io/api/instancetype/v1beta1/types_swagger_generated.go
  staging/src/kubevirt.io/client-go/api/openapi_generated.go
Labels: size/M, release-note, kind/api-change, lgtm, approved, dco-signoff: yes, sig/buildsystem

#12231 [release-1.3] mem-hotplug: fix flaky test and small issues
  pkg/virt-controller/watch/vm.go
  pkg/virt-controller/watch/vm_test.go
  tests/hotplug/memory.go
Labels: size/L, release-note-none, lgtm, approved, dco-signoff: yes

#12237 [release-1.3] Configure a single vGPU display with ramfb
  pkg/virt-api/webhooks/validating-webhook/admitters/vmi-create-admitter.go
  pkg/virt-api/webhooks/validating-webhook/admitters/vmi-create-admitter_test.go
  pkg/virt-launcher/virtwrap/device/hostdevice/BUILD.bazel
  pkg/virt-launcher/virtwrap/device/hostdevice/hostdev.go
  pkg/virt-launcher/virtwrap/device/hostdevice/hostdev_test.go
Labels: size/L, release-note, lgtm, approved, dco-signoff: yes, sig/buildsystem

#12096 Fix missing performance metrics for VMI resources
  cmd/virt-handler/BUILD.bazel
  cmd/virt-handler/virt-handler.go
  pkg/monitoring/metrics/common/client/client_test.go
  pkg/monitoring/metrics/common/client/metrics.go
  pkg/virt-api/BUILD.bazel
  pkg/virt-api/api.go
  pkg/virt-controller/watch/BUILD.bazel
  pkg/virt-controller/watch/application.go
  pkg/virt-operator/BUILD.bazel
  pkg/virt-operator/application.go
  tests/monitoring/metrics.go
Labels: size/S, release-note, lgtm, approved, kind/build-change, dco-signoff: yes, sig/buildsystem, sig/observability, release-blocker/release-1.3

#12225 tests: add helper for finding target volume path inside guest
  tests/libstorage/BUILD.bazel
  tests/libstorage/datavolume.go
  tests/libstorage/vmi.go
  tests/storage/hotplug.go
  tests/storage/snapshot.go
  tests/storage/storage.go
Labels: size/L, sig/storage, release-note-none, lgtm, approved, dco-signoff: yes, sig/buildsystem

#12083 tests: Move cert functions
  tests/BUILD.bazel
  tests/infrastructure/certificates.go
  tests/libinfra/BUILD.bazel
  tests/libinfra/certificates.go
  tests/operator/BUILD.bazel
  tests/operator/operator.go
  tests/utils.go
Labels: size/L, release-note-none, lgtm, approved, dco-signoff: yes, sig/code-quality, sig/buildsystem

#12139 tests, libvmi: move adjust and delete cloudinit function from tests/utils to libvmi
  pkg/libvmi/cloudinit/cloudinit.go
  tests/BUILD.bazel
  tests/migration/migration.go
  tests/network/sriov.go
  tests/storage/hotplug.go
  tests/utils.go
Labels: size/L, sig/network, sig/storage, release-note-none, lgtm, approved, dco-signoff: yes, sig/code-quality, sig/buildsystem, sig/scale
