Repository kubevirt/kubevirt, pull requests merged in 2024-05, with the labels that each got.

#11763 tests: Hide GetPodsCertIfSynced
  tests/infrastructure/certificates.go
  tests/utils.go
Labels: size/M, release-note-none, lgtm, approved, dco-signoff: yes, sig/code-quality

#11796 Adding Eddy as a sig-network approver
  OWNERS_ALIASES
Labels: size/XS, release-note-none, lgtm, approved, dco-signoff: yes

#11822 Fix hotplug tests by updating the VMI variable after waiting for it to run
  tests/hotplug/affinity.go
  tests/hotplug/cpu.go
  tests/hotplug/memory.go
Labels: size/S, release-note-none, lgtm, approved, dco-signoff: yes

#11713 Seprate network interfaces unit test
  pkg/virt-api/webhooks/mutating-webhook/mutators/vmi-mutator_test.go
Labels: size/S, release-note-none, lgtm, approved, dco-signoff: yes, sig/code-quality

#11740 e2e,compute: Add sig-compute-serial e2e target
  automation/test.sh
Labels: size/S, release-note-none, lgtm, approved, dco-signoff: yes, sig/buildsystem

#11829 tests: Fix changes detection to support rehearsals
  automation/test.sh
Labels: size/XS, release-note-none, lgtm, approved, dco-signoff: yes, sig/buildsystem

#11682 VMClone create mutator: Don't mutate when there is no need
  pkg/virt-api/webhooks/mutating-webhook/mutators/clone-create-mutator.go
  pkg/virt-api/webhooks/mutating-webhook/mutators/clone-create-mutator_test.go
Labels: size/M, release-note-none, lgtm, approved, dco-signoff: yes

#11751 VMI controller - move unit tests to fake client (VirtualMachineInstanceInterface)
  pkg/virt-controller/watch/vmi_test.go
Labels: area/virtctl, size/XXL, release-note-none, lgtm, approved, dco-signoff: yes, sig/compute, sig/buildsystem

#11770 Fix live updates for the volumes
  pkg/storage/types/pvc.go
  pkg/virt-controller/watch/vm.go
  pkg/virt-controller/watch/vm_test.go
Labels: size/L, sig/storage, release-note, lgtm, approved, dco-signoff: yes

#11837 Clean vm.go
  pkg/virt-controller/watch/vm.go
Labels: size/L, release-note-none, lgtm, approved, dco-signoff: yes

#11710 Remove utils' GetVmiPod() function and replace it with libpod functions
  tests/hotplug/cpu.go
  tests/hotplug/memory.go
  tests/libpod/container.go
  tests/utils.go
Labels: size/M, release-note-none, lgtm, approved, dco-signoff: yes, sig/code-quality

#11641 workload-update: cancel a workload update migration
  pkg/util/migrations/migrations.go
  pkg/virt-controller/watch/workload-updater/workload-updater.go
  pkg/virt-controller/watch/workload-updater/workload-updater_test.go
  staging/src/kubevirt.io/api/core/v1/types.go
  tests/hotplug/BUILD.bazel
  tests/hotplug/cpu.go
Labels: size/L, release-note, kind/api-change, lgtm, approved, dco-signoff: yes, sig/compute, sig/buildsystem

#11821 Move GetFedoraToolsGuestAgentBlacklistUserData
  tests/compute/BUILD.bazel
  tests/compute/credentials.go
  tests/libnet/cloudinit/cloudinit.go
  tests/utils.go
  tests/vmi_configuration_test.go
Labels: size/S, sig/network, release-note-none, lgtm, approved, dco-signoff: yes, sig/code-quality, sig/buildsystem

#11260 refactor: simplification and clean-up of vmi-create-admitter.go
  pkg/virt-api/webhooks/validating-webhook/admitters/vmi-create-admitter.go
Labels: size/XL, release-note-none, lgtm, approved, dco-signoff: yes, sig/code-quality

#11850 test/utils: Remove NotDeleted() and NotDeletedVMs()
  tests/libreplicaset/BUILD.bazel
  tests/libreplicaset/replicaset.go
  tests/pool_test.go
  tests/replicaset_test.go
  tests/utils.go
Labels: size/M, release-note-none, lgtm, approved, dco-signoff: yes, sig/code-quality, sig/buildsystem

#11847 [release-1.0] Improve the handling of ordinal pod interface name for upgrade
  pkg/network/namescheme/networknamescheme.go
  pkg/network/namescheme/networknamescheme_test.go
Labels: size/M, sig/network, release-note, lgtm, approved, dco-signoff: yes

#11482 build: Bump go to version 1.22.2
  WORKSPACE
  go.mod
  hack/builder/Dockerfile
  hack/dockerized
  manifests/generated/kv-resource.yaml
  pkg/virt-operator/resource/generate/components/validations_generated.go
Labels: release-note, size/XXL, lgtm, approved, dco-signoff: yes, sig/buildsystem

#11853 [release-1.2] Have the Fakeclient implement the resources interfaces and SEV fixes
  hack/generate.sh
  pkg/virt-api/rest/BUILD.bazel
  pkg/virt-api/rest/dialers.go
  pkg/virt-api/rest/streamer.go
  pkg/virt-api/rest/vnc.go
  pkg/virt-handler/rest/BUILD.bazel
  pkg/virt-handler/rest/console.go
  pkg/virtctl/console/BUILD.bazel
  pkg/virtctl/console/console.go
  pkg/virtctl/portforward/BUILD.bazel
  pkg/virtctl/portforward/portforward.go
  pkg/virtctl/portforward/portforwarder.go
  pkg/virtctl/ssh/BUILD.bazel
  pkg/virtctl/ssh/native.go
  pkg/virtctl/usbredir/BUILD.bazel
  pkg/virtctl/usbredir/usbredir.go
  pkg/virtctl/vnc/BUILD.bazel
  pkg/virtctl/vnc/vnc.go
  staging/src/kubevirt.io/client-go/generated/kubevirt/clientset/versioned/typed/core/v1/BUILD.bazel
  staging/src/kubevirt.io/client-go/generated/kubevirt/clientset/versioned/typed/core/v1/async.go
  staging/src/kubevirt.io/client-go/generated/kubevirt/clientset/versioned/typed/core/v1/fake/BUILD.bazel
  staging/src/kubevirt.io/client-go/generated/kubevirt/clientset/versioned/typed/core/v1/fake/fake_kubevirt_expansion.go
  staging/src/kubevirt.io/client-go/generated/kubevirt/clientset/versioned/typed/core/v1/fake/fake_virtualmachine_expansion.go
  staging/src/kubevirt.io/client-go/generated/kubevirt/clientset/versioned/typed/core/v1/fake/fake_virtualmachineinstance_expansion.go
  staging/src/kubevirt.io/client-go/generated/kubevirt/clientset/versioned/typed/core/v1/fake/fake_virtualmachineinstancemigration_expansion.go
  staging/src/kubevirt.io/client-go/generated/kubevirt/clientset/versioned/typed/core/v1/fake/fake_virtualmachineinstancereplicaset_expansion.go
  staging/src/kubevirt.io/client-go/generated/kubevirt/clientset/versioned/typed/core/v1/generated_expansion.go
  staging/src/kubevirt.io/client-go/generated/kubevirt/clientset/versioned/typed/core/v1/kubevirt_expansion.go
  staging/src/kubevirt.io/client-go/generated/kubevirt/clientset/versioned/typed/core/v1/streamer.go
  staging/src/kubevirt.io/client-go/generated/kubevirt/clientset/versioned/typed/core/v1/virtualmachine_expansion.go
  staging/src/kubevirt.io/client-go/generated/kubevirt/clientset/versioned/typed/core/v1/virtualmachineinstance_expansion.go
  staging/src/kubevirt.io/client-go/generated/kubevirt/clientset/versioned/typed/core/v1/virtualmachineinstancemigration_expansion.go
  staging/src/kubevirt.io/client-go/generated/kubevirt/clientset/versioned/typed/core/v1/virtualmachineinstancereplicaset_expansion.go
  staging/src/kubevirt.io/client-go/generated/kubevirt/clientset/versioned/typed/core/v1/websocket.go
  staging/src/kubevirt.io/client-go/generated/kubevirt/clientset/versioned/typed/core/v1/websocket_test.go
  staging/src/kubevirt.io/client-go/go.mod
  staging/src/kubevirt.io/client-go/go.sum
  staging/src/kubevirt.io/client-go/kubecli/BUILD.bazel
  staging/src/kubevirt.io/client-go/kubecli/async.go
  staging/src/kubevirt.io/client-go/kubecli/fake/BUILD.bazel
  staging/src/kubevirt.io/client-go/kubecli/fake/actions.go
  staging/src/kubevirt.io/client-go/kubecli/generated_mock_kubevirt.go
  staging/src/kubevirt.io/client-go/kubecli/kubevirt.go
  staging/src/kubevirt.io/client-go/kubecli/vm.go
  staging/src/kubevirt.io/client-go/kubecli/vmi.go
  staging/src/kubevirt.io/client-go/kubecli/vmi_test.go
  tests/BUILD.bazel
  tests/compute/BUILD.bazel
  tests/compute/console.go
  tests/console/BUILD.bazel
  tests/console/console.go
  tests/launchsecurity/sev.go
  tests/pausing_test.go
  tests/portforward_test.go
  tests/usbredir_test.go
  tests/vmi_headless_test.go
  tests/vmi_vsock_test.go
  tests/vnc_test.go
  vendor/modules.txt
Labels: sig/network, sig/storage, release-note, size/XXL, lgtm, approved, dco-signoff: yes, sig/buildsystem, sig/observability

#11814 [release-1.2] Wait until backend storage PVC is ready before starting VMIs
  pkg/storage/backend-storage/BUILD.bazel
  pkg/storage/backend-storage/backend-storage.go
  pkg/virt-controller/watch/BUILD.bazel
  pkg/virt-controller/watch/application.go
  pkg/virt-controller/watch/application_test.go
  pkg/virt-controller/watch/vmi.go
  pkg/virt-controller/watch/vmi_test.go
Labels: size/L, sig/storage, release-note-none, lgtm, approved, dco-signoff: yes, sig/buildsystem

#11256 rpm: Update virtualization packages
  WORKSPACE
  go.mod
  go.sum
  hack/bootstrap.sh
  hack/rpm-deps.sh
  rpm/BUILD.bazel
  tests/hotplug/memory.go
  tests/network/vmi_istio.go
  vendor/libvirt.org/go/libvirt/connect.go
  vendor/libvirt.org/go/libvirt/doc.go
  vendor/libvirt.org/go/libvirt/domain.go
  vendor/libvirt.org/go/libvirt/error.go
  vendor/libvirt.org/go/libvirt/libvirt_generated_callbacks.h
  vendor/libvirt.org/go/libvirt/libvirt_generated_enums.h
  vendor/libvirt.org/go/libvirt/libvirt_generated_functions.h
  vendor/libvirt.org/go/libvirt/libvirt_generated_functions_dlopen_network.go
  vendor/libvirt.org/go/libvirt/libvirt_generated_functions_static_network.go
  vendor/libvirt.org/go/libvirt/libvirt_generated_macros.h
  vendor/libvirt.org/go/libvirt/libvirt_generated_typedefs.h
  vendor/libvirt.org/go/libvirt/network.go
  vendor/libvirt.org/go/libvirt/network_events.go
  vendor/libvirt.org/go/libvirt/network_events_helper.go
  vendor/libvirt.org/go/libvirt/network_events_helper.h
  vendor/libvirt.org/go/libvirt/typedparams.go
  vendor/libvirt.org/go/libvirtxml/domain.go
  vendor/libvirt.org/go/libvirtxml/network.go
  vendor/modules.txt
Labels: sig/network, release-note, size/XXL, lgtm, approved, dco-signoff: yes, sig/buildsystem

#11286 Docs: Document handling eviction requests
  docs/handling-eviction-requests.md
Labels: size/M, release-note-none, lgtm, approved, dco-signoff: yes

#11456 docs: Add coding-conventions.md
  docs/coding-conventions.md
Labels: size/L, release-note-none, lgtm, approved, dco-signoff: yes, sig/code-quality

#11700 Introduce the update volume strategy field
  api/openapi-spec/swagger.json
  pkg/virt-api/webhooks/validating-webhook/admitters/vms-admitter.go
  pkg/virt-api/webhooks/validating-webhook/admitters/vms-admitter_test.go
  pkg/virt-config/feature-gates.go
  pkg/virt-controller/watch/vm.go
  pkg/virt-controller/watch/vm_test.go
  pkg/virt-operator/resource/generate/components/validations_generated.go
  staging/src/kubevirt.io/api/core/v1/deepcopy_generated.go
  staging/src/kubevirt.io/api/core/v1/types.go
  staging/src/kubevirt.io/api/core/v1/types_swagger_generated.go
  staging/src/kubevirt.io/client-go/api/openapi_generated.go
Labels: size/L, release-note, kind/api-change, lgtm, approved, dco-signoff: yes

#11823 tests: Extract GetCertsForPods (and related functions) from utils
  tests/BUILD.bazel
  tests/infrastructure/BUILD.bazel
  tests/infrastructure/certificates.go
  tests/infrastructure/tls-configuration.go
  tests/libpod/BUILD.bazel
  tests/libpod/certs.go
  tests/migration/migration.go
  tests/operator/operator.go
  tests/utils.go
Labels: size/L, release-note-none, lgtm, approved, dco-signoff: yes, sig/code-quality, sig/buildsystem

#11841 test/utils: move 'ExecuteCommandOnNodeThroughVirtHandler' to libnode
  tests/libnode/BUILD.bazel
  tests/libnode/node.go
  tests/mdev_configuration_allocation_test.go
  tests/swap_test.go
  tests/utils.go
  tests/vmi_headless_test.go
Labels: size/S, release-note-none, lgtm, approved, dco-signoff: yes, sig/code-quality, sig/buildsystem

#11624 Replace NewRandomVirtualMachineInstanceWithFileDisk inside vm_test.go
  tests/containerdisk/containerdisk.go
  tests/utils.go
  tests/vm_test.go
Labels: size/M, release-note-none, lgtm, approved, dco-signoff: yes, sig/code-quality

#11854 tests, libsecret: Generalize data used for secret
  tests/libsecret/secret.go
  tests/vmi_cloudinit_test.go
Labels: size/M, release-note-none, lgtm, approved, dco-signoff: yes, sig/code-quality

#11788 SR-IOV binding: Use network-info to map between the network and PCI address
  pkg/network/deviceinfo/BUILD.bazel
  pkg/network/deviceinfo/deviceinfo.go
  pkg/network/deviceinfo/deviceinfo_test.go
  pkg/network/deviceinfo/sriov.go
  pkg/network/deviceinfo/sriov_test.go
  pkg/network/vmispec/interface.go
  pkg/network/vmispec/interface_test.go
  pkg/virt-controller/network/BUILD.bazel
  pkg/virt-controller/network/pod_annotations.go
  pkg/virt-controller/network/pod_annotations_test.go
  pkg/virt-controller/services/BUILD.bazel
  pkg/virt-controller/services/rendervolumes.go
  pkg/virt-controller/services/template.go
  pkg/virt-controller/services/template_test.go
  pkg/virt-controller/watch/BUILD.bazel
  pkg/virt-controller/watch/vmi_test.go
  pkg/virt-launcher/virtwrap/device/hostdevice/sriov/hostdev.go
  pkg/virt-launcher/virtwrap/device/hostdevice/sriov/pcipool_netstatus.go
  pkg/virt-launcher/virtwrap/device/hostdevice/sriov/pcipool_netstatus_test.go
Labels: sig/network, size/XL, release-note, lgtm, approved, dco-signoff: yes, sig/buildsystem

#11869 rpm: Add qemu-kvm-device-usb-redirect on aarch64
  WORKSPACE
  hack/bootstrap.sh
  hack/rpm-deps.sh
  rpm/BUILD.bazel
Labels: size/S, release-note-none, lgtm, approved, dco-signoff: yes, sig/buildsystem

#11873 controller: Increase syncCache timeout in VM tests
  pkg/virt-controller/watch/vm_test.go
Labels: size/XS, release-note-none, lgtm, approved, dco-signoff: yes, kind/flake

#11532 Eviction admitter: Deny when triggering VMI evacuation
  pkg/virt-api/webhooks/validating-webhook/admitters/pod-eviction-admitter.go
  pkg/virt-api/webhooks/validating-webhook/admitters/pod-eviction-admitter_test.go
Labels: size/M, release-note-none, lgtm, approved, dco-signoff: yes, sig/buildsystem

#11884 [release-1.2] VM controller - move unit tests to fake client (VirtualMachineInterface)
  pkg/virt-controller/watch/BUILD.bazel
  pkg/virt-controller/watch/patchreactor_test.go
  pkg/virt-controller/watch/updatereactor_test.go
  pkg/virt-controller/watch/vm_test.go
  pkg/virt-controller/watch/vmi_test.go
Labels: size/XXL, release-note-none, lgtm, approved, dco-signoff: yes, sig/buildsystem

#11524 e2e: Double number of e2e parallel nodes from 3 to 6
  automation/test.sh
  hack/functests.sh
  images/disks-images-provider/entrypoint.sh
Labels: size/S, release-note-none, lgtm, approved, dco-signoff: yes, sig/buildsystem

#11846 Prefer libvirtxml over schema.go in smbios sidecar example
  cmd/sidecars/smbios/BUILD.bazel
  cmd/sidecars/smbios/smbios.go
Labels: size/M, release-note, lgtm, approved, dco-signoff: yes, sig/buildsystem

#11885 Fix typo: VirutalMachineInstance => VirtualMachineInstance
  pkg/virtctl/pause/pause.go
Labels: area/virtctl, size/XS, release-note-none, lgtm, approved, dco-signoff: yes

#11773 backend storage: add logic to improve usability
  pkg/controller/virtinformers.go
  pkg/storage/backend-storage/BUILD.bazel
  pkg/storage/backend-storage/backend-storage.go
  pkg/storage/backend-storage/backend-storage_suite_test.go
  pkg/storage/backend-storage/backend-storage_test.go
  pkg/virt-controller/watch/application.go
  pkg/virt-controller/watch/application_test.go
  pkg/virt-controller/watch/vmi.go
  pkg/virt-controller/watch/vmi_test.go
  pkg/virt-handler/BUILD.bazel
  pkg/virt-handler/vm.go
  tests/storage/BUILD.bazel
  tests/storage/backendstorage.go
Labels: sig/storage, size/XL, release-note, kind/api-change, lgtm, approved, dco-signoff: yes, sig/compute, sig/buildsystem

#11701 network, binding: Declare the SLIRP core binding as deprecated and remove it
  api/api-rule-violations-known.list
  api/api-rule-violations.list
  api/openapi-spec/swagger.json
  cmd/sidecars/network-slirp-binding/domain/domain.go
  cmd/sidecars/network-slirp-binding/domain/domain_test.go
  examples/vmi-slirp.yaml
  manifests/generated/kv-resource.yaml
  pkg/libvmi/network.go
  pkg/network/admitter/binding.go
  pkg/network/admitter/slirp.go
  pkg/network/admitter/slirp_test.go
  pkg/network/admitter/validator.go
  pkg/network/netbinding/BUILD.bazel
  pkg/network/netbinding/netbinding.go
  pkg/network/netbinding/netbinding_test.go
  pkg/network/setup/netpod/discover.go
  pkg/network/setup/netpod/netpod.go
  pkg/network/setup/netpod/netpod_test.go
  pkg/network/setup/network.go
  pkg/virt-api/webhooks/mutating-webhook/mutators/vmi-mutator_test.go
  pkg/virt-api/webhooks/validating-webhook/admitters/vmi-create-admitter.go
  pkg/virt-api/webhooks/validating-webhook/admitters/vms-admitter.go
  pkg/virt-config/configuration.go
  pkg/virt-config/configuration_test.go
  pkg/virt-config/virt-config.go
  pkg/virt-controller/services/template_test.go
  pkg/virt-controller/watch/BUILD.bazel
  pkg/virt-controller/watch/application.go
  pkg/virt-controller/watch/vm.go
  pkg/virt-controller/watch/vm_test.go
  pkg/virt-controller/watch/vmi.go
  pkg/virt-launcher/virtwrap/converter/network.go
  pkg/virt-operator/resource/generate/components/validations_generated.go
  staging/src/kubevirt.io/api/core/v1/deepcopy_generated.go
  staging/src/kubevirt.io/api/core/v1/defaults.go
  staging/src/kubevirt.io/api/core/v1/schema.go
  staging/src/kubevirt.io/api/core/v1/schema_swagger_generated.go
  staging/src/kubevirt.io/api/core/v1/types.go
  staging/src/kubevirt.io/api/core/v1/types_swagger_generated.go
  staging/src/kubevirt.io/client-go/api/deepcopy_test.go
  staging/src/kubevirt.io/client-go/api/openapi_generated.go
  staging/src/kubevirt.io/client-go/api/schema_test.go
  tests/testsuite/kubevirtresource.go
  tools/vms-generator/utils/utils.go
  tools/vms-generator/vms-generator.go
Labels: sig/network, size/XL, release-note, kind/api-change, lgtm, approved, dco-signoff: yes, sig/buildsystem, sig/scale

#11826 stop calling NewRandomVMIWithEphemeralDisk in tests/vmipreset_test.go
  tests/vmipreset_test.go
Labels: size/L, release-note-none, lgtm, approved, dco-signoff: yes, sig/code-quality

#11828 Remove call to NewRandomVMIWithEphemeralDisk
  tests/pausing_test.go
  tests/security_features_test.go
  tests/vmi_headless_test.go
  tests/vmi_hook_sidecar_test.go
  tests/vmi_iothreads_test.go
  tests/vmi_kernel_boot_test.go
  tests/vmi_multiqueue_test.go
Labels: size/M, release-note-none, lgtm, approved, dco-signoff: yes, sig/code-quality

#11655 Allow to set cpu reqs/limits when doing cpu hotplug
  pkg/virt-api/webhooks/validating-webhook/admitters/vms-admitter.go
  pkg/virt-api/webhooks/validating-webhook/admitters/vms-admitter_test.go
  pkg/virt-controller/watch/vm.go
  pkg/virt-controller/watch/vm_test.go
Labels: size/L, release-note, lgtm, approved, dco-signoff: yes

#11844 VMIM controller - move unit tests to fake client
  pkg/virt-controller/watch/BUILD.bazel
  pkg/virt-controller/watch/migration_test.go
Labels: size/XXL, release-note-none, lgtm, approved, dco-signoff: yes, sig/buildsystem

#11889 [release-1.2] VM controller - move unit tests to fake client (VirtualMachineInstanceInterface)
  pkg/virt-controller/watch/BUILD.bazel
  pkg/virt-controller/watch/vm_test.go
Labels: size/XXL, release-note-none, lgtm, approved, dco-signoff: yes, sig/buildsystem

#11745 Add rpms for s390x
  WORKSPACE
  hack/bootstrap.sh
  hack/rpm-deps.sh
  rpm/BUILD.bazel
  rpm/repo.yaml
Labels: size/XXL, release-note-none, lgtm, approved, dco-signoff: yes, sig/buildsystem

#11797 e2e suite: slight improvement to developer experience
  tests/clone_test.go
  tests/console/console.go
  tests/console/login.go
  tests/migration/migration.go
  tests/reporter/kubernetes.go
  tests/softreboot_test.go
Labels: size/M, release-note-none, lgtm, approved, dco-signoff: yes

#11908 sidecar-shim: include hook's stderr logs
  cmd/sidecars/sidecar_shim.go
Labels: size/S, release-note, lgtm, approved, dco-signoff: yes

#11910 e2e,compute: Quarantine flaky force restart e2e test
  tests/vm_test.go
Labels: size/XS, release-note-none, lgtm, approved, dco-signoff: yes

#11547 tests: Make use of tests/libsecret
  tests/compute/BUILD.bazel
  tests/compute/credentials.go
  tests/storage/BUILD.bazel
  tests/storage/export.go
  tests/virtctl/BUILD.bazel
  tests/virtctl/credentials.go
  tests/vmi_configuration_test.go
  tests/vmi_lifecycle_test.go
Labels: size/L, sig/storage, release-note-none, lgtm, approved, dco-signoff: yes, sig/code-quality, sig/buildsystem

#11776 tests/utils: Move function RunPodAndExpectCompletion
  tests/storage/hotplug.go
  tests/storage/storage.go
  tests/utils.go
  tests/virtiofs/datavolume.go
Labels: size/M, sig/storage, release-note-none, lgtm, approved, dco-signoff: yes, sig/code-quality

#11894 Launcher, CreateDomainInterfaces: Remove unused param
  pkg/virt-launcher/virtwrap/converter/converter.go
  pkg/virt-launcher/virtwrap/converter/network.go
Labels: sig/network, size/XS, release-note-none, lgtm, approved, dco-signoff: yes, sig/code-quality

#11919 test/utils: Move GenerateHelloWorldServer() to tests/network
  tests/network/bindingplugin_slirp.go
  tests/network/expose.go
  tests/utils.go
Labels: size/M, sig/network, release-note-none, lgtm, approved, dco-signoff: yes, sig/code-quality

#11914 docs: Move network docs under a network folder
  docs/network/OWNERS
  docs/network/libvirt-pod-networking.md
  docs/network/network-binding-plugin.md
  docs/network/sriov.md
Labels: size/XS, release-note-none, lgtm, approved, dco-signoff: yes

#11863 [release-1.2] VMI controller - move unit tests to fake client (VirtualMachineInstanceInterface)
  pkg/virt-controller/watch/vmi_test.go
Labels: size/XXL, release-note-none, lgtm, approved, dco-signoff: yes

#11759 linter: Introduce a stricter formatter `gofumpt`
  .golangci.yml
  Makefile
  hack/builder/Dockerfile
  hack/dockerized
  hack/gofumpt.sh
  pkg/instancetype/compatibility_test.go
  pkg/instancetype/instancetype.go
  pkg/instancetype/instancetype_test.go
  pkg/libvmi/selector.go
  pkg/libvmi/storage.go
  pkg/libvmi/vmi.go
  pkg/network/admitter/admit_test.go
  pkg/network/admitter/binding.go
  pkg/network/admitter/binding_test.go
  pkg/network/admitter/macvtap.go
  pkg/network/admitter/netiface_test.go
  pkg/network/admitter/netsource_test.go
  pkg/network/admitter/passt.go
  pkg/network/admitter/slirp.go
  pkg/network/deviceinfo/deviceinfo_test.go
  pkg/network/domainspec/generators_test.go
  pkg/network/domainspec/interface.go
  tests/console/console.go
  tests/console/login.go
  tests/libnet/cloudinit/cloudinit.go
  tests/libnet/cluster/cluster.go
  tests/libnet/job/job.go
  tests/libnode/node.go
  tests/libpod/certs.go
  tests/libpod/render.go
Labels: size/L, sig/network, release-note-none, lgtm, approved, dco-signoff: yes, sig/code-quality, sig/buildsystem

#11918 Add test IDs for tests
  tests/hotplug/affinity.go
  tests/hotplug/rolloutstrategy.go
Labels: size/XS, release-note-none, lgtm, approved, dco-signoff: yes

#11870 docs, network-binding-plugin: Document migration support
  docs/network/network-binding-plugin.md
Labels: size/S, sig/network, release-note-none, lgtm, approved, dco-signoff: yes

#11932 Add ShellyKa13 to sig-storage reviewers
  OWNERS_ALIASES
Labels: size/XS, release-note-none, lgtm, approved, dco-signoff: yes

#11922 Fix VM manifest rendering in export-controller
  pkg/storage/export/export/BUILD.bazel
  pkg/storage/export/export/export.go
  pkg/storage/export/export/export_test.go
Labels: size/M, sig/storage, release-note, lgtm, approved, dco-signoff: yes, sig/buildsystem

#10545 instancetype: Upgrade `ControllerRevisions` on resync
  Makefile
  go.mod
  hack/gofumpt.sh
  pkg/instancetype/BUILD.bazel
  pkg/instancetype/OWNERS
  pkg/instancetype/compatibility.go
  pkg/instancetype/instancetype.go
  pkg/instancetype/upgrade.go
  pkg/instancetype/upgrade_test.go
  pkg/libvmi/BUILD.bazel
  pkg/libvmi/vm.go
  pkg/storage/snapshot/restore.go
  pkg/testutils/mock_instancetype.go
  pkg/virt-controller/watch/vm.go
  pkg/virt-controller/watch/vm_test.go
  pkg/virt-operator/resource/generate/components/data/OWNERS
  staging/src/kubevirt.io/api/instancetype/register.go
  tests/BUILD.bazel
  tests/instancetype/BUILD.bazel
  tests/instancetype/OWNERS
  tests/instancetype/instancetype.go
  tests/instancetype/upgrade.go
  tests/libinstancetype/OWNERS
  tests/libinstancetype/builder/BUILD.bazel
  tests/libinstancetype/builder/builder.go
  tests/libinstancetype/builder/v1alpha1/BUILD.bazel
  tests/libinstancetype/builder/v1alpha1/builder.go
  tests/libinstancetype/builder/v1alpha2/BUILD.bazel
  tests/libinstancetype/builder/v1alpha2/builder.go
  tests/libinstancetype/instancetype.go
  tests/subresource_api_test.go
  tests/tests_suite_test.go
Labels: sig/storage, release-note, size/XXL, kind/api-change, lgtm, approved, dco-signoff: yes, area/instancetype, sig/buildsystem

#11935 controller: fix bug when limits are used with CPU hotplug
  pkg/virt-controller/watch/vm.go
  pkg/virt-controller/watch/vm_test.go
Labels: size/M, release-note-none, lgtm, approved, dco-signoff: yes

#11945 tests: PIT flaky virt-handler component monitoring test
  tests/monitoring/component_monitoring.go
Labels: size/XS, release-note-none, lgtm, approved, dco-signoff: yes, sig/observability

#11944 Simplify range expression
  pkg/virt-config/virt-config.go
  pkg/virt-controller/watch/migration_test.go
  pkg/virt-controller/watch/pool.go
  pkg/virt-controller/watch/topology/nodetopologyupdater_test.go
  pkg/virt-handler/node-labeller/cpu_plugin_test.go
  pkg/virt-handler/vm.go
  pkg/virt-launcher/virtwrap/converter/converter_test.go
  pkg/virt-launcher/virtwrap/device/hostdevice/generic/addresspool.go
  pkg/virt-launcher/virtwrap/device/hostdevice/gpu/addresspool.go
  tests/framework/checks/checks.go
  tests/hyperv_test.go
  tests/libmigration/migration.go
  tests/windows_test.go
Labels: size/M, release-note-none, lgtm, approved, dco-signoff: yes, sig/compute

#11659 Require scheduling infra components onto control-plane nodes
  pkg/virt-operator/resource/apply/apps.go
  pkg/virt-operator/resource/apply/apps_test.go
  pkg/virt-operator/resource/apply/reconcile.go
  pkg/virt-operator/resource/apply/reconcile_test.go
  pkg/virt-operator/strategy_job.go
Labels: size/L, sig/network, release-note, lgtm, approved, dco-signoff: yes, sig/buildsystem

#11454 Apply monitoring linters
  Makefile
  go.mod
  go.sum
  hack/builder/Dockerfile
  hack/dockerized
  pkg/monitoring/rules/BUILD.bazel
  pkg/monitoring/rules/rules_suite_test.go
  pkg/monitoring/rules/rules_test.go
  vendor/github.com/grafana/regexp/.gitignore
  vendor/github.com/grafana/regexp/BUILD.bazel
  vendor/github.com/grafana/regexp/LICENSE
  vendor/github.com/grafana/regexp/README.md
  vendor/github.com/grafana/regexp/backtrack.go
  vendor/github.com/grafana/regexp/exec.go
  vendor/github.com/grafana/regexp/onepass.go
  vendor/github.com/grafana/regexp/regexp.go
  vendor/github.com/machadovilaca/operator-observability/pkg/testutil/BUILD.bazel
  vendor/github.com/machadovilaca/operator-observability/pkg/testutil/alert_custom_validations.go
  vendor/github.com/machadovilaca/operator-observability/pkg/testutil/alert_validation.go
  vendor/github.com/machadovilaca/operator-observability/pkg/testutil/linter.go
  vendor/github.com/machadovilaca/operator-observability/pkg/testutil/problem.go
  vendor/github.com/machadovilaca/operator-observability/pkg/testutil/recording_rule_validation.go
  vendor/modules.txt
Labels: size/XXL, release-note-none, lgtm, approved, dco-signoff: yes, area/monitoring, sig/buildsystem, sig/scale, sig/observability

#11953 e2e,compute: Quarantine flaky test with RunStrategyManual and failing VMI
  tests/vm_test.go
Labels: size/XS, release-note-none, lgtm, approved, dco-signoff: yes

#11778 tests, utils: Remove CreateSecret
  tests/config_test.go
  tests/migration/BUILD.bazel
  tests/migration/migration.go
  tests/operator/BUILD.bazel
  tests/operator/operator.go
  tests/utils.go
  tests/virtiofs/BUILD.bazel
  tests/virtiofs/config.go
Labels: size/L, release-note-none, lgtm, approved, dco-signoff: yes, sig/code-quality, sig/buildsystem

#11897 Eviction admitter: Use KubeVirt generated clientset
  pkg/virt-api/webhooks/validating-webhook/admitters/BUILD.bazel
  pkg/virt-api/webhooks/validating-webhook/admitters/pod-eviction-admitter.go
  pkg/virt-api/webhooks/validating-webhook/admitters/pod-eviction-admitter_test.go
  pkg/virt-api/webhooks/validating-webhook/validating-webhook.go
Labels: size/L, release-note-none, lgtm, approved, dco-signoff: yes, sig/code-quality, sig/buildsystem

#11942 Update virtctl to use v1beta1 endpoint
  pkg/virtctl/imageupload/imageupload.go
Labels: area/virtctl, release-note, size/XS, lgtm, approved, dco-signoff: yes

#11928 client-go: Move custom <resource> struct methods to <resource>_expansion files
  staging/src/kubevirt.io/client-go/generated/kubevirt/clientset/versioned/typed/core/v1/BUILD.bazel
  staging/src/kubevirt.io/client-go/generated/kubevirt/clientset/versioned/typed/core/v1/kubevirt_expansion.go
  staging/src/kubevirt.io/client-go/generated/kubevirt/clientset/versioned/typed/core/v1/virtualmachine_expansion.go
  staging/src/kubevirt.io/client-go/generated/kubevirt/clientset/versioned/typed/core/v1/virtualmachineinstance_expansion.go
  staging/src/kubevirt.io/client-go/generated/kubevirt/clientset/versioned/typed/core/v1/virtualmachineinstancereplicaset_expansion.go
  staging/src/kubevirt.io/client-go/kubecli/BUILD.bazel
  staging/src/kubevirt.io/client-go/kubecli/kv.go
  staging/src/kubevirt.io/client-go/kubecli/replicaset.go
  staging/src/kubevirt.io/client-go/kubecli/vm.go
  staging/src/kubevirt.io/client-go/kubecli/vmi.go
Labels: size/XL, release-note-none, lgtm, approved, dco-signoff: yes, sig/buildsystem

#11962 instancetype: Allow `VirtualMachines` referencing instance types when `LiveUpdate` is enabled and trigger the `RestartRequired` condition if changed
  pkg/virt-api/webhooks/validating-webhook/admitters/vms-admitter.go
  pkg/virt-api/webhooks/validating-webhook/admitters/vms-admitter_test.go
  pkg/virt-controller/watch/BUILD.bazel
  pkg/virt-controller/watch/vm.go
  pkg/virt-controller/watch/vm_test.go
Labels: size/M, release-note, lgtm, approved, dco-signoff: yes, sig/buildsystem

#11959 instancetype: Avoid hardcoding namespace in upgrade tests
  tests/instancetype/upgrade.go
Labels: size/S, release-note-none, lgtm, approved, dco-signoff: yes, area/instancetype

#11966 [release-1.2] instancetype: Allow `VirtualMachines` referencing instance types when `LiveUpdate` is enabled and trigger the `RestartRequired` condition if changed
  pkg/virt-api/webhooks/validating-webhook/admitters/vms-admitter.go
  pkg/virt-api/webhooks/validating-webhook/admitters/vms-admitter_test.go
  pkg/virt-controller/watch/vm.go
  pkg/virt-controller/watch/vm_test.go
Labels: size/L, release-note, lgtm, approved, dco-signoff: yes, area/instancetype

#11907 virt-launcher: Use interface for arch specific conversions
  pkg/virt-launcher/virtwrap/converter/BUILD.bazel
  pkg/virt-launcher/virtwrap/converter/amd64.go
  pkg/virt-launcher/virtwrap/converter/archconverter.go
  pkg/virt-launcher/virtwrap/converter/archconverter_test.go
  pkg/virt-launcher/virtwrap/converter/arm64.go
  pkg/virt-launcher/virtwrap/converter/converter.go
  pkg/virt-launcher/virtwrap/converter/converter_test.go
  pkg/virt-launcher/virtwrap/converter/ppc64le.go
Labels: size/L, release-note-none, lgtm, approved, dco-signoff: yes, sig/buildsystem

#11963 Fix RerunOnFailure RunStrategy
  api/openapi-spec/swagger.json
  pkg/virt-controller/watch/vm.go
  pkg/virt-controller/watch/vm_test.go
  pkg/virt-operator/resource/generate/components/validations_generated.go
  staging/src/kubevirt.io/api/core/v1/types.go
  staging/src/kubevirt.io/api/core/v1/types_swagger_generated.go
  staging/src/kubevirt.io/client-go/api/openapi_generated.go
Labels: size/L, release-note, kind/api-change, lgtm, approved, dco-signoff: yes

#11972 [release-1.2] Fix RerunOnFailure RunStrategy
  api/openapi-spec/swagger.json
  pkg/virt-controller/watch/vm.go
  pkg/virt-controller/watch/vm_test.go
  pkg/virt-operator/resource/generate/components/validations_generated.go
  staging/src/kubevirt.io/api/core/v1/types.go
  staging/src/kubevirt.io/api/core/v1/types_swagger_generated.go
  staging/src/kubevirt.io/client-go/api/openapi_generated.go
Labels: size/L, release-note, kind/api-change, lgtm, approved, dco-signoff: yes

#11973 Restart required correctly propagate
  pkg/virt-controller/watch/vm.go
  pkg/virt-controller/watch/vm_test.go
Labels: size/L, release-note, lgtm, approved, dco-signoff: yes

#11977 [release-1.2] Restart required correctly propagate
  pkg/virt-controller/watch/vm.go
  pkg/virt-controller/watch/vm_test.go
Labels: size/L, release-note, lgtm, approved, dco-signoff: yes

#11344 add device plugin interface
  pkg/virt-handler/device-manager/BUILD.bazel
  pkg/virt-handler/device-manager/device_controller_test.go
  pkg/virt-handler/device-manager/device_plugin_base.go
  pkg/virt-handler/device-manager/generic_device.go
  pkg/virt-handler/device-manager/mediated_device.go
  pkg/virt-handler/device-manager/pci_device.go
  pkg/virt-handler/device-manager/socket_device.go
  pkg/virt-handler/device-manager/socket_device_test.go
  pkg/virt-handler/device-manager/usb_device.go
Labels: size/XL, release-note, lgtm, approved, dco-signoff: yes, sig/compute, sig/buildsystem

#11835 Add Intel Gaudi as ADOPTERS
  ADOPTERS.md
Labels: release-note, size/XS, lgtm, approved, dco-signoff: yes

#11020 Document backup partner maturity validation
  docs/backup-restore-integration.md
Labels: size/L, release-note-none, lgtm, approved, dco-signoff: yes

#11883 Ctrl, VM: Require restart when socket count is reduced
  pkg/virt-controller/watch/vm.go
  pkg/virt-controller/watch/vm_test.go
Labels: size/M, release-note, lgtm, approved, dco-signoff: yes

#11974 controller: Fix event message recorded by migration
  pkg/virt-controller/watch/migration.go
Labels: size/S, release-note-none, lgtm, approved, dco-signoff: yes

#11986 [release-1.2] Ctrl, VM: Require restart when socket count is reduced
  pkg/virt-controller/watch/vm.go
  pkg/virt-controller/watch/vm_test.go
Labels: size/M, release-note, lgtm, approved, dco-signoff: yes

#11969 Infra components control-plane nodes NoSchedule toleration
  pkg/virt-operator/resource/apply/reconcile.go
  pkg/virt-operator/resource/apply/reconcile_test.go
Labels: size/S, release-note, lgtm, approved, dco-signoff: yes

#11906 Create kubevirt_vmi_info metric
  docs/metrics.md
  pkg/monitoring/metrics/virt-controller/vmistats_collector.go
  pkg/monitoring/metrics/virt-controller/vmistats_collector_test.go
  pkg/monitoring/rules/recordingrules/vmi.go
  tests/infrastructure/prometheus.go
  tests/monitoring/vm_monitoring.go
Labels: size/L, release-note, lgtm, approved, dco-signoff: yes, sig/observability

#11957 snapshot: Ignore unfreeze error if VMSnapshot deleting
  pkg/storage/snapshot/snapshot.go
  pkg/storage/snapshot/snapshot_test.go
Labels: size/S, sig/storage, release-note, lgtm, approved, dco-signoff: yes

#11996 [BUGFIX] Fix restore panic in case of volumesnapshot missing
  pkg/storage/export/export/vmsnapshot-source.go
  pkg/storage/snapshot/restore.go
  pkg/storage/snapshot/restore_test.go
Labels: size/M, sig/storage, release-note, lgtm, approved, dco-signoff: yes

#12017 dockerized: Remove Travis CI hack
  hack/dockerized
Labels: size/S, release-note-none, lgtm, approved, dco-signoff: yes, sig/buildsystem

#11934 Add a metric that reports the VMI last connection timestamp
  docs/metrics.md
  hack/prom-metric-linter/metric_name_linter.sh
  pkg/monitoring/metrics/virt-api/connection_metrics.go
  pkg/virt-api/rest/console.go
  pkg/virt-api/rest/portforward.go
  pkg/virt-api/rest/usbredir.go
  pkg/virt-api/rest/vnc.go
  tests/monitoring/BUILD.bazel
  tests/monitoring/metrics.go
  tests/monitoring/vm_monitoring.go
Labels: size/M, release-note, lgtm, approved, dco-signoff: yes, sig/buildsystem, sig/observability

#12011 e2e,quarantine: Quarantine flaky test using RunStrategyManual with a failing VMI
  tests/vm_test.go
Labels: size/XS, release-note-none, lgtm, approved, dco-signoff: yes

#12013 add test ID for test verify hook annotation updates domainxml
  tests/vmi_hook_sidecar_test.go
Labels: size/XS, release-note-none, lgtm, approved, dco-signoff: yes

#12015 Spell ppc64le correctly
  pkg/virt-api/webhooks/mutating-webhook/mutators/vm-mutator_test.go
  pkg/virt-api/webhooks/mutating-webhook/mutators/vmi-mutator_test.go
Labels: size/XS, release-note-none, lgtm, approved, dco-signoff: yes
