Repository kubevirt/kubevirt, pull requests merged in 2024-04, with the labels that each got.

#11610 Fix alerts duration to be triggered
  pkg/monitoring/rules/alerts/virt-operator.go
Labels: size/XS, release-note-none, lgtm, approved, dco-signoff: yes, area/monitoring

#11613 Fix kubevirt_vm_container_free_memory_bytes_based_on_working_set_bytes
  hack/prom-rule-ci/prom-rules-tests.yaml
  pkg/monitoring/rules/recordingrules/vm.go
Labels: size/S, release-note-none, lgtm, approved, dco-signoff: yes, area/monitoring, sig/buildsystem

#11628 tests/utils: Move RunCommandOnVmiTargetPod()
  tests/migration/migration.go
  tests/utils.go
Labels: size/M, release-note-none, lgtm, approved, dco-signoff: yes, sig/code-quality

#11631 tests/utils: move GetNodeHostModel to libnode
  tests/infrastructure/node-labeller.go
  tests/libmigration/migration.go
  tests/libnode/node.go
  tests/migration/migration.go
  tests/utils.go
Labels: size/S, release-note-none, lgtm, approved, dco-signoff: yes

#11561 Migration create mutator: Refactor unit test
  pkg/virt-api/webhooks/mutating-webhook/mutators/BUILD.bazel
  pkg/virt-api/webhooks/mutating-webhook/mutators/migration-create-mutator.go
  pkg/virt-api/webhooks/mutating-webhook/mutators/migration-create-mutator_test.go
Labels: size/L, release-note-none, lgtm, approved, dco-signoff: yes, sig/code-quality, sig/buildsystem

#11599 Create patchset type for patching operations
  pkg/apimachinery/patch/BUILD.bazel
  pkg/apimachinery/patch/patch.go
  pkg/apimachinery/patch/patch_suite_test.go
  pkg/apimachinery/patch/patch_test.go
  pkg/instancetype/instancetype.go
  pkg/virt-controller/watch/drain/disruptionbudget/disruptionbudget.go
  pkg/virt-controller/watch/drain/disruptionbudget/disruptionbudget_test.go
Labels: size/L, release-note-none, lgtm, approved, dco-signoff: yes, sig/buildsystem

#11307 Add e2e tests for metrics
  pkg/monitoring/metrics/virt-controller/metrics.go
  pkg/monitoring/metrics/virt-controller/migration_metrics.go
  pkg/monitoring/metrics/virt-controller/perfscale_metrics.go
  tests/libmonitoring/BUILD.bazel
  tests/libmonitoring/metric_matcher.go
  tests/libmonitoring/prometheus.go
  tests/monitoring/BUILD.bazel
  tests/monitoring/metrics.go
Labels: size/L, release-note, lgtm, approved, dco-signoff: yes, area/monitoring, sig/buildsystem

#11483 migrations: add check for vmi equal to nil
  pkg/util/migrations/BUILD.bazel
  pkg/util/migrations/migrations.go
Labels: size/XS, release-note-none, lgtm, approved, dco-signoff: yes, sig/buildsystem

#11615 e2e tests: Drop some checks for amount of containers in virt-launcher
  tests/guestlog/guestlog.go
  tests/virtiofs/datavolume.go
  tests/vmi_hook_sidecar_test.go
Labels: size/M, release-note-none, lgtm, approved, dco-signoff: yes

#11634 Introduce a generic thread-safe time-defined cache
  pkg/virt-launcher/virtwrap/BUILD.bazel
  pkg/virt-launcher/virtwrap/cmd-server/server.go
  pkg/virt-launcher/virtwrap/cmd-server/server_test.go
  pkg/virt-launcher/virtwrap/generated_mock_manager.go
  pkg/virt-launcher/virtwrap/manager.go
  pkg/virt-launcher/virtwrap/manager_test.go
  tools/cache/BUILD.bazel
  tools/cache/cache_suite_test.go
  tools/cache/time-defined-cache.go
  tools/cache/time-defined-cache_test.go
Labels: size/L, release-note-none, lgtm, approved, dco-signoff: yes, sig/compute, sig/buildsystem, sig/scale

#11642 tests, net: Remove legacy SLIRP tests
  tests/network/BUILD.bazel
  tests/network/vmi_networking.go
Labels: size/S, sig/network, release-note-none, lgtm, approved, dco-signoff: yes, sig/buildsystem

#11294 Fix kubevirt_vm_created_total being broken down by virt-api pod
  docs/metrics.md
  pkg/monitoring/metrics/virt-api/vm_metrics.go
  pkg/monitoring/rules/recordingrules/vm.go
Labels: size/S, release-note, lgtm, approved, dco-signoff: yes, area/monitoring

#11608 bump-common-instancetypes: Allow RC releases to be sync'd
  hack/bump-common-instancetypes.sh
Labels: size/XS, release-note-none, lgtm, approved, dco-signoff: yes, area/instancetype, sig/buildsystem

#11644 logger: Add Verbosity() method
  staging/src/kubevirt.io/client-go/log/log.go
  staging/src/kubevirt.io/client-go/log/log_test.go
Labels: size/S, release-note-none, lgtm, approved, dco-signoff: yes

#11653 cmd, cniplugins, passt-binding: Build the binary statically
  cmd/cniplugins/passt-binding/cmd/BUILD.bazel
Labels: sig/network, release-note, size/XS, lgtm, approved, dco-signoff: yes, sig/buildsystem

#11544 net, admitter: Move network related admiter validations to the `network/admitter` package
  pkg/network/admitter/BUILD.bazel
  pkg/network/admitter/admit.go
  pkg/network/admitter/admit_test.go
  pkg/network/admitter/binding.go
  pkg/network/admitter/binding_test.go
  pkg/network/admitter/netsource.go
  pkg/network/admitter/netsource_test.go
  pkg/network/admitter/slirp.go
  pkg/network/admitter/slirp_test.go
  pkg/network/admitter/validator.go
  pkg/virt-api/webhooks/validating-webhook/admitters/BUILD.bazel
  pkg/virt-api/webhooks/validating-webhook/admitters/vmi-create-admitter.go
  pkg/virt-api/webhooks/validating-webhook/admitters/vmi-create-admitter_test.go
Labels: sig/network, size/XL, release-note-none, lgtm, approved, dco-signoff: yes, sig/code-quality, sig/buildsystem

#11665 tests: fix namespace bug with root
  tests/vmi_configuration_test.go
Labels: size/XS, release-note-none, lgtm, approved, dco-signoff: yes

#11664 tests: fix flaky leader election test
  tests/infrastructure/virt-controller-leader-election.go
Labels: size/M, release-note-none, lgtm, approved, dco-signoff: yes

#11661 [release-1.2] e2e tests: Drop some checks for amount of containers in virt-launcher
  tests/guestlog/guestlog.go
  tests/virtiofs/datavolume.go
  tests/vmi_hook_sidecar_test.go
Labels: size/M, release-note-none, lgtm, approved, dco-signoff: yes

#11666 chore: fix function names in comment
  pkg/controller/controller_ref_manager.go
  pkg/util/util.go
  pkg/virt-api/webhooks/validating-webhook/admitters/vmclone-admitter.go
Labels: size/XS, release-note-none, lgtm, approved, dco-signoff: yes

#11625 VMClone create mutator: Refactor unit tests
  pkg/virt-api/webhooks/mutating-webhook/mutating-webhook.go
  pkg/virt-api/webhooks/mutating-webhook/mutators/BUILD.bazel
  pkg/virt-api/webhooks/mutating-webhook/mutators/clone-create-mutator.go
  pkg/virt-api/webhooks/mutating-webhook/mutators/clone-create-mutator_test.go
Labels: size/L, release-note-none, lgtm, approved, dco-signoff: yes, sig/code-quality, sig/buildsystem

#11651 Migration create mutator, tests: Avoid name collisions
  pkg/virt-api/webhooks/mutating-webhook/mutators/migration-create-mutator_test.go
Labels: size/XS, release-note-none, lgtm, approved, dco-signoff: yes

#11672 Evacuation controller, test: Tidy the imports
  pkg/virt-controller/watch/drain/evacuation/evacuation_test.go
Labels: size/L, release-note-none, lgtm, approved, dco-signoff: yes, sig/code-quality

#11605 tests: drop the deprecated NewRandomVMI
  tests/sysprep_test.go
  tests/utils.go
Labels: size/M, release-note-none, lgtm, approved, dco-signoff: yes, sig/code-quality

#11663 [time-defined cache] [follow-up]: Use a regular Mutex over RWMutex to lock the entire Get() function
  tools/cache/BUILD.bazel
  tools/cache/time-defined-cache.go
  tools/cache/time-defined-cache_test.go
Labels: size/M, release-note-none, lgtm, approved, dco-signoff: yes, sig/buildsystem, sig/scale

#11357 refectory: replace Seed() function to New() and NewSource() function
  pkg/virt-launcher/virtwrap/converter/vcpu/vcpu_test.go
Labels: size/XS, release-note-none, lgtm, approved, dco-signoff: yes

#11380 Refactor pod eviction admitter unit tests
  pkg/virt-api/webhooks/validating-webhook/admitters/BUILD.bazel
  pkg/virt-api/webhooks/validating-webhook/admitters/pod-eviction-admitter_test.go
Labels: size/XL, release-note-none, lgtm, approved, dco-signoff: yes, sig/code-quality, sig/buildsystem

#11540 tests: Use a function to build path for utility images
  tests/BUILD.bazel
  tests/libpod/BUILD.bazel
  tests/libpod/render.go
  tests/libregistry/BUILD.bazel
  tests/libregistry/images.go
  tests/libstorage/BUILD.bazel
  tests/libstorage/pvc.go
  tests/network/BUILD.bazel
  tests/network/bindingplugin.go
  tests/network/bindingplugin_passt.go
  tests/network/vmi_istio.go
  tests/storage/BUILD.bazel
  tests/storage/hotplug.go
  tests/sysprep_test.go
  tests/vmi_cloudinit_hook_sidecar_test.go
  tests/vmi_hook_sidecar_test.go
Labels: size/L, sig/network, sig/storage, release-note-none, lgtm, approved, dco-signoff: yes, sig/buildsystem

#11536 tests, k8s: Improve log collection logging
  tests/reporter/kubernetes.go
Labels: size/S, release-note-none, lgtm, approved, dco-signoff: yes

#11639 Generated client: embed generated methods into VMIM interface
  pkg/util/status/status.go
  pkg/util/status/status_test.go
  pkg/virt-api/rest/subresource.go
  pkg/virt-api/rest/subresource_test.go
  pkg/virt-api/webhooks/validating-webhook/admitters/migration-create-admitter.go
  pkg/virt-api/webhooks/validating-webhook/admitters/migration-create-admitter_test.go
  pkg/virt-controller/watch/drain/evacuation/evacuation.go
  pkg/virt-controller/watch/drain/evacuation/evacuation_test.go
  pkg/virt-controller/watch/migration.go
  pkg/virt-controller/watch/migration_test.go
  pkg/virt-controller/watch/workload-updater/workload-updater.go
  pkg/virt-controller/watch/workload-updater/workload-updater_test.go
  pkg/virtctl/vm/migrate_cancel.go
  pkg/virtctl/vm/migrate_cancel_test.go
  staging/src/kubevirt.io/client-go/kubecli/generated_mock_kubevirt.go
  staging/src/kubevirt.io/client-go/kubecli/kubevirt.go
  staging/src/kubevirt.io/client-go/kubecli/migration.go
  staging/src/kubevirt.io/client-go/kubecli/migration_test.go
  tests/dryrun_test.go
  tests/framework/matcher/getter.go
  tests/hotplug/cpu.go
  tests/hotplug/memory.go
  tests/kubectl_test.go
  tests/libmigration/migration.go
  tests/libwait/wait.go
  tests/migration/eviction_strategy.go
  tests/migration/migration.go
  tests/operator/operator.go
  tests/reporter/kubernetes.go
  tests/testsuite/namespace.go
  tests/vm_test.go
Labels: size/L, area/virtctl, release-note-none, lgtm, approved, dco-signoff: yes

#11684 tests/imageupload: add force bind for test to pass with wffc storage class
  tests/storage/imageupload.go
Labels: sig/storage, size/XS, release-note-none, lgtm, approved, dco-signoff: yes

#11445 [release-1.1] Deprecate cpu and memory exceeds alerts
  hack/prom-rule-ci/prom-rules-tests.yaml
  pkg/virt-operator/resource/generate/components/prometheus.go
  tests/monitoring/component_monitoring.go
Labels: size/L, release-note, lgtm, approved, dco-signoff: yes, area/monitoring

#11680 fix: Disable common-instancetypes feature gate before tests
  tests/operator/operator.go
Labels: size/M, release-note-none, lgtm, approved, dco-signoff: yes, area/instancetype

#11696 Remove unused old worqueue metrics code
  pkg/monitoring/workqueue/prometheus/BUILD.bazel
  pkg/monitoring/workqueue/prometheus/prometheus.go
Labels: size/L, release-note-none, lgtm, approved, dco-signoff: yes, sig/buildsystem, sig/observability

#11690 tests: always try adding a hotplug volume 3 times
  tests/storage/hotplug.go
Labels: size/S, sig/storage, release-note-none, lgtm, approved, dco-signoff: yes

#11492 sig-buildsystem: nominate xpivarc and brianmcarey as approvers for sig-buildsystem
  OWNERS_ALIASES
Labels: size/XS, release-note-none, lgtm, approved, dco-signoff: yes

#11557 Add rule to collect issues with the pods
  docs/metrics.md
  go.mod
  go.sum
  pkg/monitoring/rules/recordingrules/BUILD.bazel
  pkg/monitoring/rules/recordingrules/operator.go
  pkg/monitoring/rules/recordingrules/recordingrules.go
  vendor/github.com/machadovilaca/operator-observability/pkg/operatormetrics/collector.go
  vendor/github.com/machadovilaca/operator-observability/pkg/operatorrules/prometheusrules.go
  vendor/github.com/machadovilaca/operator-observability/pkg/operatorrules/registry.go
  vendor/modules.txt
Labels: size/M, release-note, lgtm, approved, dco-signoff: yes, area/monitoring, sig/buildsystem, sig/scale, sig/observability

#11645 Consolidate node-labeller's labels usage
  pkg/virt-controller/services/nodeselectorrenderer.go
  pkg/virt-controller/services/template.go
  pkg/virt-controller/services/template_test.go
  pkg/virt-controller/watch/topology/tsc.go
  tests/hyperv_test.go
  tests/libnode/node.go
  tests/vmi_configuration_test.go
  tests/vmi_lifecycle_test.go
Labels: size/M, release-note-none, lgtm, approved, dco-signoff: yes

#11676 Rename rest client metrics to include kubevirt prefix
  docs/metrics.md
  hack/prom-rule-ci/prom-rules-tests.yaml
  pkg/monitoring/metrics/common/client/rest_metrics.go
  pkg/monitoring/rules/alerts/alerts.go
  tests/monitoring/metrics.go
  tools/perfscale-audit/metric-client/metric-client.go
  tools/prom-metrics-collector/metrics_collector.go
Labels: size/M, release-note, lgtm, approved, dco-signoff: yes, sig/buildsystem, sig/scale

#11241 Un-quarantine clone tests
  pkg/storage/snapshot/snapshot.go
  pkg/storage/snapshot/snapshot_base.go
  pkg/storage/snapshot/snapshot_test.go
  tests/clone_test.go
  tests/storage/snapshot.go
  tests/testsuite/namespace.go
Labels: size/L, sig/storage, release-note-none, lgtm, approved, dco-signoff: yes

#11695 Generated client: embed generated methods into KV interface
  pkg/util/status/status.go
  pkg/util/status/status_test.go
  pkg/virt-controller/watch/workload-updater/workload-updater_test.go
  pkg/virt-operator/kubevirt.go
  pkg/virt-operator/kubevirt_test.go
  pkg/virt-operator/webhooks/kubevirt-create-admitter.go
  pkg/virt-operator/webhooks/kubevirt-create-admitter_test.go
  pkg/virt-operator/webhooks/webhook.go
  pkg/virt-operator/webhooks/webhook_test.go
  pkg/virtctl/adm/logverbosity/logverbosity.go
  pkg/virtctl/adm/logverbosity/logverbosity_test.go
  pkg/virtctl/configuration/configuration.go
  staging/src/kubevirt.io/client-go/kubecli/generated_mock_kubevirt.go
  staging/src/kubevirt.io/client-go/kubecli/kubevirt.go
  staging/src/kubevirt.io/client-go/kubecli/kv.go
  staging/src/kubevirt.io/client-go/kubecli/kv_test.go
  tests/canary_upgrade_test.go
  tests/dryrun_test.go
  tests/hotplug/cpu.go
  tests/hotplug/rolloutstrategy.go
  tests/libkvconfig/kvconfig.go
  tests/monitoring/monitoring.go
  tests/operator/operator.go
  tests/reporter/kubernetes.go
  tests/scale/virt-api.go
  tests/storage/export.go
  tests/testsuite/fixture.go
  tests/testsuite/kubevirtresource.go
  tests/testsuite/namespace.go
  tests/util/util.go
  tests/vmi_lifecycle_test.go
Labels: size/L, sig/storage, area/virtctl, release-note-none, lgtm, approved, dco-signoff: yes, sig/observability

#11283 Collect VMI OS info from the Guest agent
  pkg/monitoring/metrics/virt-controller/vmistats_collector.go
  pkg/monitoring/metrics/virt-controller/vmistats_collector_test.go
  tests/monitoring/BUILD.bazel
  tests/monitoring/vm_monitoring.go
Labels: size/L, release-note, lgtm, approved, dco-signoff: yes, area/monitoring, sig/buildsystem, sig/observability

#11633 tests/utils.go: move Configmap build logic to a dedicated package
  Makefile
  tests/BUILD.bazel
  tests/config_test.go
  tests/libconfigmap/BUILD.bazel
  tests/libconfigmap/configmap.go
  tests/migration/BUILD.bazel
  tests/migration/migration.go
  tests/operator/BUILD.bazel
  tests/operator/operator.go
  tests/sysprep_test.go
  tests/utils.go
  tests/virtiofs/BUILD.bazel
  tests/virtiofs/config.go
Labels: size/L, release-note-none, lgtm, approved, dco-signoff: yes, sig/code-quality, sig/buildsystem

#11714 Upgrade operator-observability to fix unit tests
  go.mod
  go.sum
  vendor/github.com/machadovilaca/operator-observability/pkg/operatorrules/prometheusrules.go
  vendor/modules.txt
Labels: size/S, release-note-none, lgtm, approved, dco-signoff: yes

#11671 BugFix: Refined CPU Validation per Libvirt Guidelines
  cmd/virt-launcher/node-labeller/node-labeller.sh
  pkg/virt-handler/node-labeller/cpu_plugin.go
  pkg/virt-handler/node-labeller/cpu_plugin_test.go
  pkg/virt-handler/node-labeller/model.go
  pkg/virt-handler/node-labeller/node_labeller.go
  pkg/virt-handler/node-labeller/node_labeller_test.go
  pkg/virt-handler/node-labeller/util/util.go
  pkg/virt-launcher/virtwrap/converter/converter.go
Labels: size/L, sig/storage, area/virtctl, release-note-none, lgtm, approved, dco-signoff: yes, sig/compute, sig/buildsystem, sig/observability

#11704 conformance: fix multi-arch image manifest issue
  tests/BUILD.bazel
Labels: size/XS, release-note-none, lgtm, approved, dco-signoff: yes, sig/buildsystem

#11618 Deviceinfo downwardAPI
  Makefile
  api/openapi-spec/swagger.json
  manifests/generated/kv-resource.yaml
  pkg/hooks/hooks.go
  pkg/network/deviceinfo/BUILD.bazel
  pkg/network/deviceinfo/deviceinfo.go
  pkg/network/deviceinfo/deviceinfo_suite_test.go
  pkg/network/deviceinfo/deviceinfo_test.go
  pkg/network/deviceinfo/sriov.go
  pkg/network/deviceinfo/sriov_test.go
  pkg/network/downwardapi/BUILD.bazel
  pkg/network/downwardapi/downwardapi_suite_test.go
  pkg/network/downwardapi/networkinfo.go
  pkg/network/downwardapi/networkinfo_test.go
  pkg/network/downwardapi/types.go
  pkg/network/netbinding/netbinding.go
  pkg/network/netbinding/netbinding_test.go
  pkg/network/setup/BUILD.bazel
  pkg/network/setup/netstat.go
  pkg/network/setup/netstat_test.go
  pkg/network/sriov/sriov.go
  pkg/network/vmispec/interface.go
  pkg/network/vmispec/interface_test.go
  pkg/virt-controller/network/BUILD.bazel
  pkg/virt-controller/network/pod_annotations.go
  pkg/virt-controller/network/pod_annotations_test.go
  pkg/virt-controller/services/BUILD.bazel
  pkg/virt-controller/services/rendervolumes.go
  pkg/virt-controller/services/template.go
  pkg/virt-controller/watch/BUILD.bazel
  pkg/virt-controller/watch/vmi.go
  pkg/virt-controller/watch/vmi_test.go
  pkg/virt-launcher/virtwrap/BUILD.bazel
  pkg/virt-launcher/virtwrap/device/hostdevice/sriov/BUILD.bazel
  pkg/virt-launcher/virtwrap/device/hostdevice/sriov/hostdev.go
  pkg/virt-launcher/virtwrap/device/hostdevice/sriov/hostdev_test.go
  pkg/virt-launcher/virtwrap/manager.go
  pkg/virt-operator/resource/generate/components/validations_generated.go
  staging/src/kubevirt.io/api/core/v1/types.go
  staging/src/kubevirt.io/api/core/v1/types_swagger_generated.go
  staging/src/kubevirt.io/client-go/api/openapi_generated.go
Labels: sig/network, release-note, size/XXL, kind/api-change, lgtm, approved, dco-signoff: yes, sig/buildsystem

#11728 fix: Lookup right FG in common-instancetypes FG test
  tests/operator/operator.go
Labels: size/XS, release-note-none, lgtm, approved, dco-signoff: yes, area/instancetype

#11715 Generated client: embed generated methods into VMIRS interface
  pkg/util/status/status.go
  pkg/util/status/status_test.go
  pkg/virt-controller/watch/replicaset.go
  pkg/virt-controller/watch/replicaset_test.go
  pkg/virt-operator/webhooks/webhook.go
  pkg/virt-operator/webhooks/webhook_test.go
  pkg/virtctl/expose/expose.go
  pkg/virtctl/expose/expose_test.go
  staging/src/kubevirt.io/client-go/kubecli/generated_mock_kubevirt.go
  staging/src/kubevirt.io/client-go/kubecli/kubevirt.go
  staging/src/kubevirt.io/client-go/kubecli/replicaset.go
  staging/src/kubevirt.io/client-go/kubecli/replicaset_test.go
  tests/dryrun_test.go
  tests/infrastructure/k8s-client-changes.go
  tests/libreplicaset/replicaset.go
  tests/network/expose.go
  tests/replicaset_test.go
  tests/vmi_lifecycle_test.go
Labels: size/L, sig/network, area/virtctl, release-note-none, lgtm, approved, dco-signoff: yes

#11719 Generated client: embed generated methods into VMIP interface
  staging/src/kubevirt.io/client-go/kubecli/generated_mock_kubevirt.go
  staging/src/kubevirt.io/client-go/kubecli/kubevirt.go
  staging/src/kubevirt.io/client-go/kubecli/vmipreset.go
  staging/src/kubevirt.io/client-go/kubecli/vmipreset_test.go
  tests/dryrun_test.go
  tests/vmipreset_test.go
Labels: size/L, release-note-none, lgtm, approved, dco-signoff: yes

#11588 refactor: remove informers from controllers
  pkg/controller/controller.go
  pkg/storage/types/dv.go
  pkg/storage/types/pvc.go
  pkg/util/migrations/migrations.go
  pkg/util/pdbs/pdbs.go
  pkg/virt-controller/watch/drain/disruptionbudget/disruptionbudget.go
  pkg/virt-controller/watch/drain/evacuation/evacuation.go
  pkg/virt-controller/watch/migration.go
  pkg/virt-controller/watch/node.go
  pkg/virt-controller/watch/pool.go
  pkg/virt-controller/watch/vmi.go
  pkg/virt-controller/watch/vmi_test.go
  pkg/virt-controller/watch/workload-updater/workload-updater.go
Labels: size/L, sig/storage, release-note-none, lgtm, approved, dco-signoff: yes

#11709 tests/utils.go: Remove `Running` function from utils.go
  tests/replicaset_test.go
  tests/utils.go
Labels: size/S, release-note-none, lgtm, approved, dco-signoff: yes, sig/code-quality

#11685 Have the Fakeclient implement the resources interfaces
  hack/generate.sh
  pkg/virt-api/rest/BUILD.bazel
  pkg/virt-api/rest/dialers.go
  pkg/virt-api/rest/streamer.go
  pkg/virt-api/rest/vnc.go
  pkg/virt-handler/rest/BUILD.bazel
  pkg/virt-handler/rest/console.go
  pkg/virtctl/console/BUILD.bazel
  pkg/virtctl/console/console.go
  pkg/virtctl/portforward/BUILD.bazel
  pkg/virtctl/portforward/portforward.go
  pkg/virtctl/portforward/portforwarder.go
  pkg/virtctl/ssh/BUILD.bazel
  pkg/virtctl/ssh/native.go
  pkg/virtctl/usbredir/BUILD.bazel
  pkg/virtctl/usbredir/usbredir.go
  pkg/virtctl/vnc/BUILD.bazel
  pkg/virtctl/vnc/vnc.go
  staging/src/kubevirt.io/client-go/generated/kubevirt/clientset/versioned/typed/core/v1/BUILD.bazel
  staging/src/kubevirt.io/client-go/generated/kubevirt/clientset/versioned/typed/core/v1/async.go
  staging/src/kubevirt.io/client-go/generated/kubevirt/clientset/versioned/typed/core/v1/fake/BUILD.bazel
  staging/src/kubevirt.io/client-go/generated/kubevirt/clientset/versioned/typed/core/v1/fake/fake_kubevirt_expansion.go
  staging/src/kubevirt.io/client-go/generated/kubevirt/clientset/versioned/typed/core/v1/fake/fake_virtualmachine_expansion.go
  staging/src/kubevirt.io/client-go/generated/kubevirt/clientset/versioned/typed/core/v1/fake/fake_virtualmachineinstance_expansion.go
  staging/src/kubevirt.io/client-go/generated/kubevirt/clientset/versioned/typed/core/v1/fake/fake_virtualmachineinstancemigration_expansion.go
  staging/src/kubevirt.io/client-go/generated/kubevirt/clientset/versioned/typed/core/v1/fake/fake_virtualmachineinstancereplicaset_expansion.go
  staging/src/kubevirt.io/client-go/generated/kubevirt/clientset/versioned/typed/core/v1/generated_expansion.go
  staging/src/kubevirt.io/client-go/generated/kubevirt/clientset/versioned/typed/core/v1/kubevirt_expansion.go
  staging/src/kubevirt.io/client-go/generated/kubevirt/clientset/versioned/typed/core/v1/streamer.go
  staging/src/kubevirt.io/client-go/generated/kubevirt/clientset/versioned/typed/core/v1/virtualmachine_expansion.go
  staging/src/kubevirt.io/client-go/generated/kubevirt/clientset/versioned/typed/core/v1/virtualmachineinstance_expansion.go
  staging/src/kubevirt.io/client-go/generated/kubevirt/clientset/versioned/typed/core/v1/virtualmachineinstancemigration_expansion.go
  staging/src/kubevirt.io/client-go/generated/kubevirt/clientset/versioned/typed/core/v1/virtualmachineinstancereplicaset_expansion.go
  staging/src/kubevirt.io/client-go/generated/kubevirt/clientset/versioned/typed/core/v1/websocket.go
  staging/src/kubevirt.io/client-go/generated/kubevirt/clientset/versioned/typed/core/v1/websocket_test.go
  staging/src/kubevirt.io/client-go/go.mod
  staging/src/kubevirt.io/client-go/go.sum
  staging/src/kubevirt.io/client-go/kubecli/BUILD.bazel
  staging/src/kubevirt.io/client-go/kubecli/async.go
  staging/src/kubevirt.io/client-go/kubecli/fake/BUILD.bazel
  staging/src/kubevirt.io/client-go/kubecli/fake/actions.go
  staging/src/kubevirt.io/client-go/kubecli/generated_mock_kubevirt.go
  staging/src/kubevirt.io/client-go/kubecli/kubevirt.go
  staging/src/kubevirt.io/client-go/kubecli/vm.go
  staging/src/kubevirt.io/client-go/kubecli/vmi.go
  staging/src/kubevirt.io/client-go/kubecli/vmi_test.go
  tests/BUILD.bazel
  tests/compute/BUILD.bazel
  tests/compute/console.go
  tests/console/BUILD.bazel
  tests/console/console.go
  tests/pausing_test.go
  tests/portforward_test.go
  tests/usbredir_test.go
  tests/vmi_headless_test.go
  tests/vmi_vsock_test.go
  tests/vnc_test.go
  vendor/modules.txt
Labels: area/virtctl, release-note, size/XXL, lgtm, approved, dco-signoff: yes, sig/compute, sig/buildsystem

#11738 e2e,sysprep: Fix VMI namespace for sysprep test
  tests/sysprep_test.go
Labels: size/XS, release-note-none, lgtm, approved, dco-signoff: yes

#11720 [release-1.2] Collect VMI OS info from the Guest agent
  pkg/monitoring/metrics/virt-controller/vmistats_collector.go
  pkg/monitoring/metrics/virt-controller/vmistats_collector_test.go
  tests/monitoring/BUILD.bazel
  tests/monitoring/vm_monitoring.go
Labels: size/L, release-note, lgtm, approved, dco-signoff: yes, area/monitoring, sig/buildsystem

#11752 fix: do not override original vmi during eventually cycle
  tests/libwait/wait.go
Labels: size/S, release-note-none, lgtm, approved, dco-signoff: yes, kind/flake

#11761 [release-1.2] Add rule to collect issues with the pods
  docs/metrics.md
  pkg/monitoring/rules/recordingrules/BUILD.bazel
  pkg/monitoring/rules/recordingrules/operator.go
  pkg/monitoring/rules/recordingrules/recordingrules.go
Labels: size/M, release-note, lgtm, approved, dco-signoff: yes, area/monitoring, sig/buildsystem

#11760 unit tests: Use TempDir
  pkg/host-disk/host-disk_test.go
  pkg/virt-handler/selinux/labels_test.go
  pkg/virt-launcher/virtwrap/manager_test.go
Labels: size/S, release-note-none, lgtm, approved, dco-signoff: yes, sig/code-quality, sig/compute

#11373 Wait until backend storage PVC is ready before starting VMIs
  pkg/storage/backend-storage/BUILD.bazel
  pkg/storage/backend-storage/backend-storage.go
  pkg/virt-controller/watch/BUILD.bazel
  pkg/virt-controller/watch/application.go
  pkg/virt-controller/watch/application_test.go
  pkg/virt-controller/watch/vmi.go
  pkg/virt-controller/watch/vmi_test.go
Labels: size/L, sig/storage, release-note-none, lgtm, approved, dco-signoff: yes, sig/buildsystem

#11718 Allow SEV requests in proxied servers
  staging/src/kubevirt.io/client-go/generated/kubevirt/clientset/versioned/typed/core/v1/fake/fake_virtualmachineinstance_expansion.go
  staging/src/kubevirt.io/client-go/generated/kubevirt/clientset/versioned/typed/core/v1/virtualmachineinstance_expansion.go
  staging/src/kubevirt.io/client-go/kubecli/generated_mock_kubevirt.go
  staging/src/kubevirt.io/client-go/kubecli/vmi.go
  staging/src/kubevirt.io/client-go/kubecli/vmi_test.go
  tests/launchsecurity/sev.go
Labels: size/L, release-note, lgtm, approved, dco-signoff: yes

#11723 [release-1.0] Collect VMI OS info from the Guest agent
  pkg/monitoring/vmistats/collector.go
  pkg/monitoring/vmistats/collector_test.go
  tests/monitoring/BUILD.bazel
  tests/monitoring/vm_monitoring.go
Labels: size/L, release-note, lgtm, approved, dco-signoff: yes, area/monitoring

#11724 [release-0.59] Collect VMI OS info from the Guest agent
  pkg/monitoring/vmistats/collector.go
  pkg/monitoring/vmistats/collector_test.go
  tests/monitoring/BUILD.bazel
  tests/monitoring/monitoring.go
Labels: size/L, release-note, lgtm, approved, dco-signoff: yes, area/monitoring

#11722 [release-1.1] Collect VMI OS info from the Guest agent
  pkg/monitoring/vmistats/collector.go
  pkg/monitoring/vmistats/collector_test.go
  tests/monitoring/BUILD.bazel
  tests/monitoring/vm_monitoring.go
Labels: size/L, release-note, lgtm, approved, dco-signoff: yes, area/monitoring

#11769 Adding SIG-release links to readme
  README.md
Labels: size/XS, release-note-none, lgtm, approved, dco-signoff: yes

#11785 Add ncr voyix adopters entry
  ADOPTERS.md
Labels: size/XS, release-note-none, lgtm, approved, dco-signoff: yes

#11791 flake, quarantine: test_id:1672 hugepages-2Mi with guest memory set explicitly
  tests/vmi_configuration_test.go
Labels: size/XS, release-note-none, lgtm, approved, dco-signoff: yes

#11675 [release-1.2] Integrate sidecar shim image
  hack/build-manifests.sh
  hack/cluster-patch.sh
  hack/generate.sh
  hack/parse-shasums.sh
  manifests/generated/operator-csv.yaml.in
  pkg/hooks/hooks.go
  pkg/virt-controller/services/BUILD.bazel
  pkg/virt-controller/services/template.go
  pkg/virt-operator/resource/generate/components/daemonsets.go
  pkg/virt-operator/resource/generate/components/deployments.go
  pkg/virt-operator/resource/generate/csv/csv.go
  pkg/virt-operator/resource/generate/install/strategy.go
  pkg/virt-operator/util/config.go
  tests/utils.go
  tests/vmi_hook_sidecar_test.go
  tools/csv-generator/csv-generator.go
  tools/manifest-templator/manifest-templator.go
  tools/util/marshaller_test.go
Labels: size/L, release-note, lgtm, approved, dco-signoff: yes, sig/buildsystem, sig/scale

#11741 tests, network: Remove SkipWhenNotDualStackCluster
  automation/test.sh
  tests/decorators/decorators.go
  tests/libnet/skips.go
  tests/network/expose.go
Labels: size/S, sig/network, release-note-none, lgtm, approved, dco-signoff: yes, sig/code-quality, sig/buildsystem

#11746 virt-launcher, libvirt: Remove unused methods and mocks
  pkg/virt-launcher/virtwrap/cli/generated_mock_libvirt.go
  pkg/virt-launcher/virtwrap/cli/libvirt.go
Labels: size/M, release-note-none, lgtm, approved, dco-signoff: yes, sig/code-quality

#11758 builder: Bump golangci-lint to v1.57.2
  hack/builder/Dockerfile
  hack/dockerized
  pkg/instancetype/instancetype.go
Labels: size/S, release-note-none, lgtm, approved, dco-signoff: yes, sig/buildsystem

#11762 Retire the NewRandomVMIWithEphemeralDisk function (cont)
  tests/container_disk_test.go
  tests/operator/operator.go
Labels: size/L, release-note-none, lgtm, approved, dco-signoff: yes, sig/code-quality

#11764 tests: Remove dump when cluster-up fails
  automation/test.sh
Labels: size/XS, release-note-none, lgtm, approved, dco-signoff: yes, sig/buildsystem

#11775 nit: make MultiArchitecture verbiage consistent
  pkg/virt-api/webhooks/validating-webhook/admitters/vmi-create-admitter.go
  pkg/virt-api/webhooks/validating-webhook/admitters/vmi-create-admitter_test.go
  pkg/virt-api/webhooks/validating-webhook/admitters/vms-admitter_test.go
  pkg/virt-config/feature-gates.go
Labels: size/S, release-note-none, lgtm, approved, dco-signoff: yes

#11790 Re-adding cloudflare to adopters, and some tidying
  ADOPTERS.md
Labels: size/S, release-note, lgtm, approved, dco-signoff: yes

#11756 tests: hide Copy/DeleteAlpineWithNonQEMUPermissions
  tests/storage/storage.go
  tests/utils.go
Labels: size/M, sig/storage, release-note-none, lgtm, approved, dco-signoff: yes, sig/code-quality

#11782 Fix leaked storage classes in tier 1 storage tests
  tests/storage/datavolume.go
Labels: sig/storage, size/XS, release-note-none, lgtm, approved, dco-signoff: yes

#11493 virt-api: Fix race condition on streamer unit-test
  pkg/virt-api/rest/BUILD.bazel
  pkg/virt-api/rest/streamer_norace_test.go
  pkg/virt-api/rest/streamer_race_test.go
  pkg/virt-api/rest/streamer_test.go
Labels: size/L, release-note-none, lgtm, approved, dco-signoff: yes, sig/buildsystem

#11750 virt-api, admitter: Remove unused method from the VM validation
  pkg/virt-api/webhooks/validating-webhook/admitters/vms-admitter.go
Labels: size/S, release-note-none, lgtm, approved, dco-signoff: yes, sig/code-quality

#11794 Fix kubevirt_memory_delta_from_requested_bytes label
  pkg/monitoring/rules/recordingrules/operator.go
Labels: size/XS, release-note-none, lgtm, approved, dco-signoff: yes, sig/observability

#11744 [release-1.1] BugFix: Refined CPU Validation per Libvirt Guidelines
  cmd/virt-launcher/node-labeller/node-labeller.sh
  pkg/virt-handler/node-labeller/cpu_plugin.go
  pkg/virt-handler/node-labeller/cpu_plugin_test.go
  pkg/virt-handler/node-labeller/model.go
  pkg/virt-handler/node-labeller/node_labeller.go
  pkg/virt-handler/node-labeller/node_labeller_test.go
  pkg/virt-handler/node-labeller/util/util.go
  pkg/virt-launcher/virtwrap/converter/converter.go
Labels: size/L, release-note-none, lgtm, approved, dco-signoff: yes

#11805 code cleanup: template.go: remove unused consts/params
  pkg/virt-controller/services/template.go
  pkg/virt-controller/services/template_test.go
  pkg/virt-controller/watch/migration.go
  pkg/virt-controller/watch/vmi.go
Labels: size/S, release-note-none, lgtm, approved, dco-signoff: yes, sig/code-quality

#11811 tests, net: Simplify console command execution to check connection
  tests/network/bindingplugin_passt.go
Labels: size/S, sig/network, release-note-none, lgtm, approved, dco-signoff: yes, sig/code-quality
