Repository kubevirt/kubevirt, pull requests merged in 2024-02, with the labels that each got.

#11073 Nominate victortoso as reviewer
  OWNERS_ALIASES
Labels: size/XS, release-note-none, lgtm, approved, dco-signoff: yes

#11108 tests: remove sanityCheckDeploymentsExist() lambda
  tests/operator/operator.go
Labels: size/M, release-note-none, lgtm, approved, dco-signoff: yes, sig/code-quality

#11121 [release-1.1] fix virtctl create vm volume-import flag
  pkg/virtctl/create/vm/vm.go
  pkg/virtctl/create/vm/vm_test.go
  tests/virtctl/create_vm.go
Labels: size/L, release-note, lgtm, approved, dco-signoff: yes

#11092 e2e: wait for all workers to enable cpumanager before starting
  tests/hotplug/cpu.go
  tests/testsuite/kubevirtresource.go
Labels: size/S, release-note-none, lgtm, approved, dco-signoff: yes

#11122 Bump runc dependency to version v1.1.12
  go.mod
  go.sum
  vendor/github.com/cyphar/filepath-securejoin/.travis.yml
  vendor/github.com/cyphar/filepath-securejoin/README.md
  vendor/github.com/cyphar/filepath-securejoin/VERSION
  vendor/github.com/cyphar/filepath-securejoin/join.go
  vendor/github.com/opencontainers/runc/libcontainer/cgroups/BUILD.bazel
  vendor/github.com/opencontainers/runc/libcontainer/cgroups/file.go
  vendor/github.com/opencontainers/runc/libcontainer/cgroups/fs/hugetlb.go
  vendor/github.com/opencontainers/runc/libcontainer/cgroups/fs/memory.go
  vendor/github.com/opencontainers/runc/libcontainer/cgroups/fs/paths.go
  vendor/github.com/opencontainers/runc/libcontainer/cgroups/fs2/hugetlb.go
  vendor/github.com/opencontainers/runc/libcontainer/cgroups/fs2/memory.go
  vendor/github.com/opencontainers/runc/libcontainer/cgroups/stats.go
  vendor/github.com/opencontainers/runc/libcontainer/configs/config.go
  vendor/github.com/opencontainers/runc/libcontainer/configs/config_linux.go
  vendor/github.com/opencontainers/runc/libcontainer/userns/BUILD.bazel
  vendor/github.com/opencontainers/runc/libcontainer/userns/userns_maps.c
  vendor/github.com/opencontainers/runc/libcontainer/userns/userns_maps_linux.go
  vendor/github.com/opencontainers/runc/libcontainer/utils/utils_unix.go
  vendor/modules.txt
Labels: size/XL, release-note, lgtm, approved, dco-signoff: yes

#10856 vmclone admitter: Replace string literals with consts
  pkg/virt-api/webhooks/validating-webhook/admitters/vmclone-admitter.go
  pkg/virt-api/webhooks/validating-webhook/admitters/vmclone-admitter_test.go
Labels: size/M, release-note-none, lgtm, approved, dco-signoff: yes

#11036 PR Template: Added a little more guidance on how to structure PR desc…
  .github/PULL_REQUEST_TEMPLATE.md
Labels: size/S, release-note-none, lgtm, approved, dco-signoff: yes

#11127 chore: Drop the OpenShift specific access tests
  tests/access_test.go
Labels: size/L, release-note-none, lgtm, approved, dco-signoff: yes, sig/code-quality

#11101 fix: `Eventually()` missing `Should()` statement and sync error
  tests/vm_test.go
Labels: size/S, release-note-none, lgtm, approved, dco-signoff: yes

#10946 test/utils: drop two public functions
  tests/compute/credentials_test.go
  tests/libvmi/cloudinit.go
  tests/utils.go
  tests/vmi_cloudinit_test.go
Labels: size/M, release-note-none, lgtm, approved, dco-signoff: yes, sig/code-quality

#11094 docs, network binding: The use of CNI plugins
  docs/network-binding-plugin.md
Labels: size/L, release-note-none, lgtm, approved, dco-signoff: yes

#11114 unit tests, volumes: Refactor in order to reduce unrequired parameters and ease readability
  pkg/virtctl/vm/add_volume_test.go
Labels: size/L, release-note-none, lgtm, approved, dco-signoff: yes, sig/code-quality

#11064 Support passt migration
  api/openapi-spec/swagger.json
  cmd/sidecars/network-passt-binding/BUILD.bazel
  cmd/sidecars/network-passt-binding/main.go
  cmd/sidecars/network-passt-binding/server/BUILD.bazel
  cmd/sidecars/network-passt-binding/server/server.go
  manifests/generated/kv-resource.yaml
  pkg/handler-launcher-com/cmd/v1/cmd.pb.go
  pkg/handler-launcher-com/cmd/v1/cmd.proto
  pkg/network/domainspec/BUILD.bazel
  pkg/network/domainspec/interface.go
  pkg/network/domainspec/interface_test.go
  pkg/network/vmispec/BUILD.bazel
  pkg/network/vmispec/interface.go
  pkg/network/vmispec/interface_test.go
  pkg/virt-handler/cmd-client/client.go
  pkg/virt-handler/cmd-client/generated_mock_client.go
  pkg/virt-handler/vm.go
  pkg/virt-handler/vm_test.go
  pkg/virt-launcher/virtwrap/api/deepcopy_generated.go
  pkg/virt-launcher/virtwrap/api/schema.go
  pkg/virt-launcher/virtwrap/cmd-server/server.go
  pkg/virt-launcher/virtwrap/cmd-server/server_test.go
  pkg/virt-launcher/virtwrap/generated_mock_manager.go
  pkg/virt-launcher/virtwrap/live-migration-target.go
  pkg/virt-launcher/virtwrap/manager.go
  pkg/virt-operator/resource/generate/components/validations_generated.go
  staging/src/kubevirt.io/api/core/v1/deepcopy_generated.go
  staging/src/kubevirt.io/api/core/v1/types.go
  staging/src/kubevirt.io/api/core/v1/types_swagger_generated.go
  staging/src/kubevirt.io/client-go/api/openapi_generated.go
  tests/network/bindingplugin_passt.go
Labels: sig/network, release-note, size/XXL, kind/api-change, lgtm, approved, dco-signoff: yes

#11152 tests: network: make linter happy
  tests/network/bindingplugin_passt.go
Labels: sig/network, size/XS, release-note-none, lgtm, approved, dco-signoff: yes

#11104 Change macvtap tests to use the network plugin binding API
  tests/exec/execute.go
  tests/libnet/interface.go
  tests/libnet/network_attachment_definition.go
  tests/libvmi/network.go
  tests/network/BUILD.bazel
  tests/network/bindingplugin_macvtap.go
  tests/network/hotplug_bridge.go
  tests/network/macvtap.go
  tests/network/vmi_multus.go
  tests/testsuite/BUILD.bazel
  tests/testsuite/kubevirtresource.go
Labels: sig/network, size/XL, release-note-none, lgtm, approved, dco-signoff: yes

#11054 VM rollout strategy
  api/openapi-spec/swagger.json
  manifests/generated/kv-resource.yaml
  pkg/virt-api/webhooks/validating-webhook/admitters/vms-admitter.go
  pkg/virt-api/webhooks/validating-webhook/admitters/vms-admitter_test.go
  pkg/virt-config/BUILD.bazel
  pkg/virt-config/configuration.go
  pkg/virt-config/configuration_test.go
  pkg/virt-config/feature-gates.go
  pkg/virt-config/virt-config.go
  pkg/virt-controller/watch/vm.go
  pkg/virt-controller/watch/vm_test.go
  pkg/virt-operator/resource/generate/components/validations_generated.go
  staging/src/kubevirt.io/api/core/v1/deepcopy_generated.go
  staging/src/kubevirt.io/api/core/v1/types.go
  staging/src/kubevirt.io/api/core/v1/types_swagger_generated.go
  staging/src/kubevirt.io/client-go/api/openapi_generated.go
  tests/hotplug/BUILD.bazel
  tests/hotplug/affinity.go
  tests/hotplug/cpu.go
  tests/hotplug/memory.go
  tests/hotplug/rolloutstrategy.go
Labels: release-note, size/XXL, kind/api-change, lgtm, approved, dco-signoff: yes

#11144 virtctl: Allow size to be optional when creating VMs
  pkg/virtctl/create/params/params.go
  pkg/virtctl/create/vm/vm.go
  pkg/virtctl/create/vm/vm_test.go
Labels: size/M, release-note, lgtm, approved, dco-signoff: yes

#11123 virtctl: Add owners
  cmd/virtctl/OWNERS
  pkg/virtctl/OWNERS
Labels: size/S, release-note-none, lgtm, approved, dco-signoff: yes

#11145 PR template: Fix markup
  .github/PULL_REQUEST_TEMPLATE.md
Labels: size/XS, release-note-none, lgtm, approved, dco-signoff: yes

#11143 Evacuation ctrl, recorder: Rename componentName
  pkg/virt-controller/watch/application.go
Labels: size/XS, release-note-none, lgtm, approved, dco-signoff: yes

#11162 tests: always retrieve vmi after creation
  tests/vmi_configuration_test.go
Labels: size/S, release-note-none, lgtm, approved, dco-signoff: yes

#8843 [restore tests]: Use supplied snapshot storage class, don't attempt discover
  tests/libstorage/storageclass.go
  tests/storage/datavolume.go
Labels: size/M, sig/storage, release-note-none, lgtm, approved, dco-signoff: yes

#11117 sig-node: Introduce some responsibilities
  OWNERS_ALIASES
  pkg/handler-launcher-com/OWNERS
  pkg/virt-handler/OWNERS
Labels: size/S, release-note-none, lgtm, approved, dco-signoff: yes

#11170 fix(pdb): fix possible nil pointer dereference
  pkg/util/pdbs/pdbs.go
  pkg/virt-controller/watch/drain/disruptionbudget/disruptionbudget.go
  pkg/virt-controller/watch/migration.go
Labels: size/XS, release-note-none, lgtm, approved, dco-signoff: yes

#11142 Evacuation ctrl: Wait for all informers' cache sync
  pkg/virt-controller/watch/drain/evacuation/evacuation.go
Labels: size/XS, release-note-none, lgtm, approved, dco-signoff: yes

#11156 Start moving vmi verifications to the CRD
  pkg/virt-api/webhooks/validating-webhook/admitters/vmi-create-admitter.go
  pkg/virt-api/webhooks/validating-webhook/admitters/vmi-create-admitter_test.go
  pkg/virt-operator/resource/generate/components/validations_generated.go
  staging/src/kubevirt.io/api/core/v1/schema.go
  staging/src/kubevirt.io/api/core/v1/schema_swagger_generated.go
  staging/src/kubevirt.io/api/core/v1/types.go
  staging/src/kubevirt.io/api/core/v1/types_swagger_generated.go
Labels: size/L, release-note, kind/api-change, lgtm, approved, dco-signoff: yes

#11147 functest: If doc changes only, then skip functests
  automation/test.sh
Labels: size/S, release-note-none, lgtm, approved, ok-to-test, dco-signoff: yes

#11169 fix(e2e flakes): Fix some flakes in compute lane
  tests/compute/BUILD.bazel
  tests/compute/console.go
  tests/compute/credentials.go
  tests/compute/vmidefaults.go
  tests/vmi_configuration_test.go
Labels: size/M, release-note-none, lgtm, approved, dco-signoff: yes, kind/flake

#9394 e2e: enable drain migration tests for several cluster topology
  tests/migration/eviction_strategy.go
Labels: size/L, release-note-none, lgtm, approved, dco-signoff: yes

#11154 tests, network: Move cloudinit helpers to their own package
  tests/BUILD.bazel
  tests/libnet/BUILD.bazel
  tests/libnet/cloudinit/BUILD.bazel
  tests/libnet/cloudinit/cloudinit.go
  tests/libnet/cloudinit/factory.go
  tests/libvmi/BUILD.bazel
  tests/libvmi/network.go
  tests/network/BUILD.bazel
  tests/network/bindingplugin_passt.go
  tests/network/hotplug_bridge.go
  tests/network/primary_pod_network.go
  tests/network/sriov.go
  tests/network/vmi_istio.go
  tests/network/vmi_multus.go
  tests/network/vmi_networking.go
  tests/utils.go
  tests/vm_state_test.go
Labels: size/L, sig/network, release-note-none, lgtm, approved, dco-signoff: yes

#11174 Add test IDs for CPU/Memory hotplug tests
  tests/hotplug/cpu.go
  tests/hotplug/memory.go
Labels: size/S, release-note-none, lgtm, approved, needs-ok-to-test, dco-signoff: yes

#10908 Use fakeclient instead of reactor in vmclone
  pkg/virt-api/webhooks/validating-webhook/admitters/vmrestore-admitter.go
  pkg/virt-controller/watch/clone/BUILD.bazel
  pkg/virt-controller/watch/clone/clone_test.go
Labels: size/XL, release-note-none, lgtm, approved, dco-signoff: yes

#11155 tests, sriov: Drop IPv6 connectivity test
  tests/network/sriov.go
Labels: size/M, sig/network, release-note-none, lgtm, approved, dco-signoff: yes

#11178 tests, utils: Extract container lookup helpers to libpod
  tests/container_disk_test.go
  tests/hotplug/BUILD.bazel
  tests/hotplug/cpu.go
  tests/hotplug/memory.go
  tests/libpod/BUILD.bazel
  tests/libpod/container.go
  tests/migration/migration.go
  tests/utils.go
  tests/vmi_configuration_test.go
  tests/vmi_headless_test.go
Labels: size/L, release-note-none, lgtm, approved, dco-signoff: yes, sig/code-quality

#11051 Improve error reporting when fsfreeze fails
  pkg/virt-handler/rest/lifecycle.go
  tests/storage/snapshot.go
Labels: size/M, sig/storage, release-note, lgtm, approved, dco-signoff: yes

#11194 virt-controller, vm: Set domain firmware UUID based on namespace & name
  pkg/virt-controller/watch/vm.go
  pkg/virt-controller/watch/vm_test.go
Labels: size/XS, release-note-none, lgtm, approved, dco-signoff: yes

#11157 Add test id for USB and TPM/EFI persistent
  tests/migration/migration.go
  tests/storage/storage.go
  tests/vm_state_test.go
Labels: size/S, sig/storage, release-note-none, lgtm, approved, ok-to-test, dco-signoff: yes

#11180 lint: Cover tests/libpod using the linter
  Makefile
  tests/libpod/blackhole.go
  tests/libpod/query.go
  tests/libpod/render.go
  tests/virt_control_plane_test.go
  tests/vm_test.go
Labels: size/M, release-note-none, lgtm, approved, dco-signoff: yes, sig/code-quality

#11130 chore: Inline SetupAlpineHostPath
  tests/hotplug/BUILD.bazel
  tests/hotplug/rolloutstrategy.go
  tests/storage/storage.go
  tests/tests_suite_test.go
  tests/utils.go
Labels: size/S, sig/storage, release-note-none, lgtm, approved, dco-signoff: yes, sig/code-quality

#11158 Handle virt-freezer failures focused on possible freeze windows vm issues
  cmd/virt-freezer/main.go
Labels: size/S, release-note-none, lgtm, approved, dco-signoff: yes

#11205 Fix migration when VM has rng devices and hotplugged block volume
  pkg/virt-handler/cgroup/util.go
  tests/storage/hotplug.go
Labels: size/L, sig/storage, release-note, lgtm, approved, dco-signoff: yes

#11198 downwardmetrics: add safety checks in StopServer()
  pkg/virt-handler/dmetrics-manager/dmetrics-manager.go
Labels: size/XS, release-note-none, lgtm, approved, dco-signoff: yes

#11239 [release-1.0] Fix migration when VM has rng devices and hotplugged block volume
  pkg/virt-handler/cgroup/util.go
  tests/storage/hotplug.go
Labels: size/L, release-note, lgtm, approved, dco-signoff: yes

#11244 [e2e] Quarantine flaky fsfreeze test
  tests/storage/snapshot.go
Labels: sig/storage, size/XS, release-note-none, lgtm, approved, dco-signoff: yes

#11243 [release-1.1] Fix migration when VM has rng devices and hotplugged block volume
  pkg/virt-handler/cgroup/util.go
  tests/storage/hotplug.go
Labels: size/L, release-note, lgtm, approved, dco-signoff: yes

#11222 virt-controller, template: Remove Passt binding SELinux adjustment
  pkg/virt-controller/services/template.go
  pkg/virt-controller/services/template_test.go
Labels: size/S, release-note-none, lgtm, approved, dco-signoff: yes

#11159 Add namespace to VM specific alerts descriptions
  hack/prom-rule-ci/prom-rules-tests.yaml
  pkg/monitoring/rules/alerts/vms.go
Labels: size/S, release-note-none, lgtm, approved, dco-signoff: yes, area/monitoring

#11258 owners: Remove inactive people from aliases
  OWNERS_ALIASES
Labels: size/XS, release-note-none, lgtm, approved, dco-signoff: yes

#11209 Add Ænix to the Adopters list
  ADOPTERS.md
Labels: size/XS, release-note-none, lgtm, approved, dco-signoff: yes

#11217 tests, libvmi: Reduce dependencies
  tests/container_disk_test.go
  tests/guestlog/BUILD.bazel
  tests/guestlog/guestlog.go
  tests/hotplug/BUILD.bazel
  tests/hotplug/affinity.go
  tests/hotplug/cpu.go
  tests/hotplug/memory.go
  tests/hyperv_test.go
  tests/libnet/BUILD.bazel
  tests/libnet/cloudinit/BUILD.bazel
  tests/libnet/cloudinit/cloudinit.go
  tests/libnet/dns/BUILD.bazel
  tests/libnet/dns/dns.go
  tests/libnet/vmibuilder.go
  tests/libpod/BUILD.bazel
  tests/libpod/query.go
  tests/libvmi/BUILD.bazel
  tests/libvmi/architecture.go
  tests/libvmi/factory.go
  tests/libvmi/network.go
  tests/libvmi/status.go
  tests/migration/eviction_strategy.go
  tests/migration/migration.go
  tests/monitoring/BUILD.bazel
  tests/monitoring/monitoring.go
  tests/network/BUILD.bazel
  tests/network/expose.go
  tests/network/hotplug_bridge.go
  tests/network/networkpolicy.go
  tests/network/probes.go
  tests/network/services.go
  tests/network/vmi_multus.go
  tests/network/vmi_networking.go
  tests/network/vmi_subdomain.go
  tests/operator/BUILD.bazel
  tests/operator/operator.go
  tests/security_features_test.go
  tests/storage/storage.go
  tests/testsuite/BUILD.bazel
  tests/testsuite/fixture.go
  tests/vm_test.go
  tests/vmi_configuration_test.go
  tests/vmi_headless_test.go
  tests/vmi_lifecycle_test.go
  tests/windows_test.go
Labels: size/L, sig/network, sig/storage, release-note-none, lgtm, approved, dco-signoff: yes, sig/code-quality

#11230 tests, network, bindingplugin: Create the VMI object directly
  tests/network/bindingplugin.go
Labels: sig/network, size/XS, release-note-none, lgtm, approved, dco-signoff: yes, kind/flake

#11250 revert: Set domain firmware UUID based on namespace & name
  pkg/virt-controller/watch/vm.go
  pkg/virt-controller/watch/vm_test.go
Labels: size/XS, release-note-none, lgtm, approved, dco-signoff: yes

#11148 Cleanup virtctl
  pkg/virtctl/create/vm/BUILD.bazel
  pkg/virtctl/create/vm/vm.go
  pkg/virtctl/create/vm/vm_test.go
Labels: size/L, release-note-none, lgtm, approved, dco-signoff: yes, sig/code-quality

#11181 tests: Move storage helpers from utils
  tests/storage/hotplug.go
  tests/storage/memorydump.go
  tests/storage/storage.go
  tests/utils.go
Labels: size/M, sig/storage, release-note-none, lgtm, approved, dco-signoff: yes, sig/code-quality

#11213 sidecar-shim: README: fix misinterpretation
  cmd/sidecars/README.md
Labels: size/XS, release-note-none, lgtm, approved, dco-signoff: yes

#11265 Vm controller copy fix
  pkg/virt-controller/watch/vm.go
  pkg/virt-controller/watch/vm_test.go
Labels: size/L, release-note, lgtm, approved, dco-signoff: yes

#11182 lint: Cover tests/libnode using the linter
  .golangci.yml
  Makefile
  tests/libnode/node.go
Labels: size/M, release-note-none, lgtm, approved, dco-signoff: yes, sig/code-quality

#11176 e2e,guestlog: update tests to just use the cirros VMI
  tests/guestlog/guestlog.go
Labels: size/S, release-note-none, lgtm, approved, dco-signoff: yes

#11150 tests: avoid triggering the failure parser
  tests/vm_test.go
Labels: size/XS, release-note-none, lgtm, approved, dco-signoff: yes

#11285 tests, network, vmi_passt: Create the VMI object directly
  tests/network/vmi_passt.go
Labels: sig/network, size/XS, release-note-none, lgtm, approved, dco-signoff: yes

#11206 tests, network: Move `vmi_servers` to a new `network/vmnetserver` pkg
  .golangci.yml
  Makefile
  tests/BUILD.bazel
  tests/libnet/vmnetserver/BUILD.bazel
  tests/libnet/vmnetserver/servers.go
  tests/migration/BUILD.bazel
  tests/migration/migration.go
  tests/network/BUILD.bazel
  tests/network/bindingplugin_passt.go
  tests/network/networkpolicy.go
  tests/network/port_forward.go
  tests/network/probes.go
  tests/network/services.go
  tests/network/vmi_istio.go
  tests/network/vmi_networking.go
  tests/vmi_vsock_test.go
Labels: size/L, sig/network, release-note-none, lgtm, approved, dco-signoff: yes, sig/code-quality

#11252 [release-1.0] tests, network, hot-unplug: Drop the VM restart step
  tests/network/hotplug.go
Labels: size/S, sig/network, release-note-none, lgtm, approved, dco-signoff: yes, kind/flake

#11234 tests/utils: Move GetSupportedCPUFeatures to libnode package
  tests/libnode/node.go
  tests/utils.go
  tests/vmi_configuration_test.go
  tests/vmi_lifecycle_test.go
Labels: size/M, release-note-none, lgtm, approved, dco-signoff: yes, sig/code-quality

#11291 [release-1.0] vm controller copy fix
  pkg/virt-controller/watch/vm.go
  pkg/virt-controller/watch/vm_test.go
Labels: size/L, release-note, lgtm, approved, dco-signoff: yes

#11292 [release-1.1] vm controller copy fix
  pkg/virt-controller/watch/vm.go
  pkg/virt-controller/watch/vm_test.go
Labels: size/L, release-note, lgtm, approved, dco-signoff: yes

#11245 tests: fix datarace in hotplug test and make it faster
  tests/storage/hotplug.go
Labels: size/M, sig/storage, release-note-none, lgtm, approved, dco-signoff: yes, kind/flake

#11284 e2e: Drop utils NewRandomFedoraVMIWithBlacklistGuestAgent
  tests/utils.go
  tests/vmi_configuration_test.go
Labels: size/S, release-note-none, lgtm, approved, dco-signoff: yes, sig/code-quality

#11109 test/swap: Refactor lambda functions to regular functions
  tests/swap_test.go
Labels: size/L, release-note-none, lgtm, approved, dco-signoff: yes, sig/code-quality

#11202 ownership, sig-network: arrange network code to separate directories and add OWNERS files
  cmd/cniplugins/OWNERS
  cmd/sidecars/network-passt-binding/OWNERS
  cmd/sidecars/network-slirp-binding/OWNERS
  pkg/network/admitter/BUILD.bazel
  pkg/network/admitter/admit.go
  pkg/network/admitter/admit_test.go
  pkg/virt-api/webhooks/validating-webhook/admitters/BUILD.bazel
  pkg/virt-api/webhooks/validating-webhook/admitters/vmi-create-admitter.go
  pkg/virt-controller/network/BUILD.bazel
  pkg/virt-controller/network/OWNERS
  pkg/virt-controller/network/hotplug.go
  pkg/virt-controller/network/hotplug_test.go
  pkg/virt-controller/network/multus_annotations.go
  pkg/virt-controller/network/multus_annotations_test.go
  pkg/virt-controller/network/render.go
  pkg/virt-controller/network/render_test.go
  pkg/virt-controller/services/BUILD.bazel
  pkg/virt-controller/services/renderresources.go
  pkg/virt-controller/services/template.go
  pkg/virt-controller/services/template_test.go
  pkg/virt-controller/watch/BUILD.bazel
  pkg/virt-controller/watch/vm.go
  pkg/virt-controller/watch/vmi.go
  pkg/virt-controller/watch/vmi_test.go
  tests/infrastructure/prometheus.go
  tests/libinfra/BUILD.bazel
  tests/libinfra/network.go
  tests/libmigration/BUILD.bazel
  tests/libmigration/migration.go
  tests/libnet/OWNERS
Labels: size/L, sig/network, release-note-none, lgtm, approved, dco-signoff: yes

#11058 fix(vmclone) Delete vmclone resource when target vm is deleted
  pkg/controller/virtinformers.go
  pkg/virt-controller/watch/clone/BUILD.bazel
  pkg/virt-controller/watch/clone/clone.go
  pkg/virt-controller/watch/clone/clone_base.go
  pkg/virt-controller/watch/clone/clone_test.go
  tests/clone_test.go
Labels: size/L, release-note, lgtm, approved, dco-signoff: yes

#11183 ownership, sig-buildsystem: add reviewers, add OWNERS files
  OWNERS
  OWNERS_ALIASES
  automation/OWNERS
  cluster-up-sha.txt
  cluster-up/OWNERS
  hack/OWNERS
  hack/builder/OWNERS
  hack/sync-kubevirtci.sh
Labels: size/M, release-note, lgtm, approved, dco-signoff: yes

#11220 tests: Move out some fns from tests/utils that used only in one place
  tests/storage/hotplug.go
  tests/utils.go
  tests/vmi_configuration_test.go
Labels: size/M, sig/storage, release-note-none, lgtm, approved, dco-signoff: yes, sig/code-quality

#11298 BugFix ipv4/ipv6 typo.
  pkg/network/setup/netpod/netpod.go
Labels: sig/network, size/XS, release-note-none, lgtm, approved, dco-signoff: yes

#11187 tests, network: Refactor services test
  tests/libvmi/network.go
  tests/network/services.go
Labels: size/L, sig/network, release-note-none, lgtm, approved, dco-signoff: yes, sig/code-quality

#11216 Remove client and config from migrationPolicy admitter
  pkg/virt-api/webhooks/validating-webhook/admitters/migrationpolicy-admitter.go
  pkg/virt-api/webhooks/validating-webhook/admitters/migrationpolicy-admitter_test.go
  pkg/virt-api/webhooks/validating-webhook/validating-webhook.go
Labels: size/M, release-note-none, lgtm, approved, dco-signoff: yes, sig/code-quality

#11299 tests, vmi_lifecycle: set the startup timeout
  tests/vmi_lifecycle_test.go
Labels: size/M, release-note-none, lgtm, approved, dco-signoff: yes

#11099 Follow-up #10970: Minor API fixes to get fsList disks
  api/api-rule-violations-known.list
  api/api-rule-violations.list
  api/openapi-spec/swagger.json
  pkg/virt-launcher/virtwrap/agent-poller/BUILD.bazel
  pkg/virt-launcher/virtwrap/agent-poller/agent_parser.go
  pkg/virt-launcher/virtwrap/agent-poller/agent_parser_test.go
  pkg/virt-launcher/virtwrap/api/deepcopy_generated.go
  pkg/virt-launcher/virtwrap/api/schema.go
  pkg/virt-launcher/virtwrap/manager.go
  pkg/virt-launcher/virtwrap/manager_test.go
  staging/src/kubevirt.io/api/core/v1/types.go
  staging/src/kubevirt.io/client-go/api/openapi_generated.go
  tests/vmi_configuration_test.go
Labels: size/L, release-note-none, kind/api-change, lgtm, approved, dco-signoff: yes, release-blocker/release-1.2

#11233 tests: move GetCertFromSecret()
  tests/BUILD.bazel
  tests/infrastructure/BUILD.bazel
  tests/infrastructure/certificates.go
  tests/utils.go
Labels: size/S, release-note-none, lgtm, approved, dco-signoff: yes, sig/code-quality

#11264 Fix perfscale buckets error
  go.mod
  go.sum
  pkg/monitoring/metrics/virt-controller/BUILD.bazel
  pkg/monitoring/metrics/virt-controller/migration_metrics.go
  pkg/monitoring/metrics/virt-controller/perfscale_metrics.go
  vendor/github.com/machadovilaca/operator-observability/pkg/operatormetrics/collector.go
  vendor/github.com/machadovilaca/operator-observability/pkg/operatormetrics/histogram.go
  vendor/github.com/machadovilaca/operator-observability/pkg/operatormetrics/histogram_vec.go
  vendor/github.com/machadovilaca/operator-observability/pkg/operatormetrics/registry.go
  vendor/github.com/machadovilaca/operator-observability/pkg/operatormetrics/summary.go
  vendor/github.com/machadovilaca/operator-observability/pkg/operatormetrics/summary_vec.go
  vendor/github.com/machadovilaca/operator-observability/pkg/operatormetrics/wrapper_registry.go
  vendor/github.com/machadovilaca/operator-observability/pkg/operatorrules/prometheusrules.go
  vendor/github.com/machadovilaca/operator-observability/pkg/operatorrules/registry.go
  vendor/modules.txt
Labels: size/L, release-note, lgtm, approved, dco-signoff: yes, area/monitoring, release-blocker/release-1.2

#11288 [Doc] Add VM instancetype and preference controller revisions to backup graph
  docs/backup-restore-integration.md
Labels: size/XS, release-note-none, lgtm, approved, dco-signoff: yes

#11313 E2E, CloudInitNoCloud: Refactor userdata and b64 userdata
  tests/vmi_cloudinit_test.go
Labels: size/S, release-note-none, lgtm, approved, dco-signoff: yes, sig/code-quality

#11314 tests/operator: Avoid usage of complex tests.NewRandomVMI
  tests/operator/operator.go
Labels: size/XS, release-note-none, lgtm, approved, dco-signoff: yes, sig/code-quality

#11326 Fix credential tests: Create secrets in VMI's namespace
  tests/compute/credentials.go
Labels: size/S, release-note-none, lgtm, approved, dco-signoff: yes

#11218 sig-tests: Add approvers and include unit tests under sig-tests ownership
  OWNERS
  OWNERS_ALIASES
  tests/OWNERS
Labels: size/S, release-note-none, lgtm, approved, dco-signoff: yes

#11188 tests,swap: Cosmetics
  tests/swap_test.go
Labels: size/M, release-note-none, lgtm, approved, dco-signoff: yes, sig/code-quality

#11231 Remove the listCgroupThreads func from utils
  tests/utils.go
  tests/vmi_configuration_test.go
Labels: size/M, release-note-none, lgtm, approved, dco-signoff: yes, sig/code-quality

#11334 ksm.go: move global vars to be local vars
  pkg/virt-handler/heartbeat/ksm.go
Labels: size/S, release-note-none, lgtm, approved, dco-signoff: yes, sig/code-quality

#11302 vnc_test: avoid usage of complex tests.NewRandomVMI
  tests/vnc_test.go
Labels: size/S, release-note-none, lgtm, approved, dco-signoff: yes, sig/code-quality

#11320 perfscale: Change v flag to verbose in load generator
  hack/perfscale-tests.sh
  tools/perfscale-load-generator/README.md
  tools/perfscale-load-generator/flags/flags.go
Labels: size/XS, release-note-none, lgtm, approved, dco-signoff: yes

#11295 kubevirt, check: update deprecated dryRun call
  hack/check-unassigned-tests.sh
Labels: size/XS, release-note-none, lgtm, approved, dco-signoff: yes

#11340 vnc_test: place err variable more locally
  tests/vnc_test.go
Labels: size/S, release-note-none, lgtm, approved, dco-signoff: yes

#11352 Manual bump of kubevirtci for crio fix
  cluster-up-sha.txt
  cluster-up/hack/common.sh
  cluster-up/version.txt
  hack/config-default.sh
Labels: size/XS, release-note-none, lgtm, approved, dco-signoff: yes

#11330 migration state: add source pod and failure reason
  api/openapi-spec/swagger.json
  pkg/controller/controller.go
  pkg/virt-controller/watch/migration.go
  pkg/virt-controller/watch/migration_test.go
  pkg/virt-controller/watch/vmi.go
  pkg/virt-handler/vm.go
  pkg/virt-operator/resource/generate/components/validations_generated.go
  staging/src/kubevirt.io/api/core/v1/types.go
  staging/src/kubevirt.io/api/core/v1/types_swagger_generated.go
  staging/src/kubevirt.io/client-go/api/openapi_generated.go
  tests/libmigration/migration.go
  tests/migration/migration.go
Labels: size/L, release-note, kind/api-change, lgtm, approved, dco-signoff: yes

#11210 Sig-storage ownership
  OWNERS_ALIASES
  cmd/libguestfs/OWNERS
  cmd/pr-helper/OWNERS
  cmd/virt-exportserver/OWNERS
Labels: size/S, release-note-none, lgtm, approved, dco-signoff: yes

#11261 e2e: Use libvmi and libnet directly instead NewRandomFedoraVMI
  tests/BUILD.bazel
  tests/mdev_configuration_allocation_test.go
  tests/migration/migration.go
  tests/monitoring/vm_monitoring.go
  tests/portforward_test.go
  tests/storage/restore.go
  tests/storage/snapshot.go
  tests/subresource_api_test.go
  tests/swap_test.go
  tests/utils.go
  tests/vm_state_test.go
  tests/vmi_configuration_test.go
  tests/vmi_headless_test.go
  tests/vmi_hostdev_test.go
  tests/vmi_multiqueue_test.go
  tests/vmi_tpm_test.go
  tests/vmi_vsock_test.go
Labels: size/L, sig/network, sig/storage, release-note-none, lgtm, approved, dco-signoff: yes, sig/code-quality

#11364 refectory: simplifying the routine of adding elements to a list
  pkg/network/dhcp/server/server.go
  pkg/virt-api/rest/subresource.go
Labels: size/S, sig/network, release-note-none, lgtm, approved, dco-signoff: yes

#11306 fix(ksm): set ksm-enabled label to true independently from node pressure
  pkg/virt-handler/heartbeat/ksm.go
  pkg/virt-handler/heartbeat/ksm_test.go
  staging/src/kubevirt.io/api/core/v1/types.go
Labels: size/L, release-note, kind/api-change, lgtm, approved, dco-signoff: yes

#11378 [release-1.2] fix(ksm): set ksm-enabled label to true independently from node pressure
  pkg/virt-handler/heartbeat/ksm.go
  pkg/virt-handler/heartbeat/ksm_test.go
  staging/src/kubevirt.io/api/core/v1/types.go
Labels: size/L, release-note, kind/api-change, lgtm, approved, dco-signoff: yes

#11377 live-migration: fix bytes to Mbps conversion in log
  pkg/virt-launcher/virtwrap/live-migration-source.go
Labels: size/XS, release-note-none, lgtm, approved, dco-signoff: yes

#11100 [release-1.1] fix: Reduce VM recovery times
  pkg/virt-controller/watch/vmi.go
  pkg/virt-controller/watch/vmi_test.go
  tests/BUILD.bazel
  tests/libpod/BUILD.bazel
  tests/libpod/blackhole.go
  tests/virt_control_plane_test.go
  tests/vm_test.go
Labels: size/L, release-note, lgtm, approved, dco-signoff: yes

#10900 Fixed incorrect APIVersion in APIResourceList
  pkg/virt-api/api.go
Labels: release-note, size/XS, lgtm, approved, needs-ok-to-test, dco-signoff: yes

#11138 Tests: Use matchers to get better info in case of failures
  tests/storage/snapshot.go
Labels: size/L, sig/storage, release-note-none, lgtm, approved, dco-signoff: yes, sig/code-quality

#11267 Add annotation to DataVolumeTemplates to better handle DR/Restore
  pkg/storage/types/dv.go
  pkg/storage/types/pvc.go
  pkg/virt-controller/watch/vm.go
  pkg/virt-controller/watch/vm_test.go
Labels: size/M, sig/network, sig/storage, release-note, lgtm, approved, dco-signoff: yes

#11379 Vm controller remove Informers
  pkg/controller/controller.go
  pkg/storage/types/dv.go
  pkg/storage/types/pvc.go
  pkg/virt-controller/watch/migration.go
  pkg/virt-controller/watch/vm.go
  pkg/virt-controller/watch/vmi.go
  pkg/virt-controller/watch/vmi_test.go
  pkg/virt-controller/watch/workload-updater/workload-updater.go
Labels: size/L, sig/storage, release-note-none, lgtm, approved, dco-signoff: yes
